apps/docs/src/app/core/component-docs/step-input/step-input-docs.component.scss

Part of https://github.com/SAP/fundamental-ngx/issues/4483
Before:
After:

docs: (Core) align input with unit description

---

apps/docs/src/app/core/component-docs/grid-list/examples/default/grid-list-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/delete/grid-list-delete-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/dnd/grid-list-dnd-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/footer/grid-list-footer-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/grid-list.component.scss
apps/docs/src/app/core/component-docs/grid-list/examples/group/grid-list-group-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/layout/grid-list-layout-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/more/grid-list-more-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/multi-select/grid-list-multi-select-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/single-select/grid-list-single-select-example.component.ts
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.scss
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.ts
libs/core/src/lib/grid-list/components/grid-list-more-btn/grid-list-more-btn.component.html
libs/core/src/lib/grid-list/components/grid-list-more-btn/grid-list-more-btn.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/4560#issuecomment-774880602
Closes https://github.com/SAP/fundamental-ngx/issues/4634
Fixed part of the issue, the other part was fixed in the Styles repository

fix: (Core) fix grid list

---

apps/docs/src/app/core/component-docs/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.html

docs: mobile calendars should have cozy buttons

---

libs/platform/src/lib/components/table/table.component.html

fixes #3842 
fixes #3847 
fixes #3849  
fixed a few issues related to wrong aria attributes

fix: (Platform) accessibility fixes for Table

---

karma.conf-ci.js

https://github.com/SAP/fundamental-ngx/issues/4727
improve unit test stability - added retries for connection issues and increased timeouts for connection and disconnection

test: improve unit tests ci runs

---

libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss

There is added necessar code, when header is not collapsible.
It won't be needed upon migrating https://github.com/SAP/fundamental-styles/pull/2154

fix: (Platform) Dynamic page non-collapsible background

---

apps/docs/src/app/core/component-docs/card/card-docs.component.html
apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.html
libs/core/src/lib/card/card-header.component.ts
libs/core/src/lib/card/card.component.scss
libs/core/src/lib/card/constants.ts

There is added non-interactive cards example with necessary styles added

fix: (Core) Non interactive cards

---

libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html

https://github.com/sap/fundamental-ngx/issues/4384
Apply contentDensity to the suggestion list

fix: (Platform) fix combobox list compact

---

apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts

0.26/0.27 versions added to dropdown

docs: Add new versions of NGX

---

libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-user-details/approval-flow-user-details.component.scss
libs/platform/src/lib/components/approval-flow/approval-flow.component.html
libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
libs/platform/src/lib/components/approval-flow/styles/approval-flow-dialog.scss

fixes #4734
- fixed avatar's extra margin in user details popup in RTL mode
- changed text for `edit` and `remove` buttons in approval flow node's menu
- disabled ability to add a new approver with an invalid date and added error state to datepicker field

fix: (Platform) defect hunting issues in approval flow

---

apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-basic-example.component.html
apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-basic-example.component.ts
apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-horizontal-example.component.ts
apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-video-media-example.component.ts
libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.html
libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.scss
libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.spec.ts
libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.ts
libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.html
libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.scss
libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.spec.ts
libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.ts
libs/platform/src/lib/components/thumbnail/thumbnail.component.html
libs/platform/src/lib/components/thumbnail/thumbnail.component.scss
libs/platform/src/lib/components/thumbnail/thumbnail.component.spec.ts
libs/platform/src/lib/components/thumbnail/thumbnail.component.ts
libs/platform/src/lib/components/thumbnail/thumbnail.module.ts
wdio.conf.js

https://github.com/SAP/fundamental-ngx/issues/4284
This PR contains code changes for Thumbnail component enhancements.

feat: (Platform)Thumbnail component v2 enhancements

---

apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.ts
apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html
apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.ts
apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.module.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/4609
add an enhancement to the Multi Input component - possibility to have a custom list item through template

feat: (Core) add custom item template option to Multi Input

---

libs/core/src/lib/slider/slider.component.scss

https://github.com/SAP/fundamental-ngx/issues/4738
Fixed Slider tooltip styles for RTL mode

fix: (Core) fix Slider tooltip RTL

---

libs/core/src/lib/utils/drag-and-drop/drag-and-drop.scss

Part of https://github.com/SAP/fundamental-ngx/issues/4482
Add `grab` cursor to Grid List items with drag and drop functionality

fix: (Core) add grab cursor to drag and drop Grid List items

---

apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html
apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss
apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
apps/docs/src/styles.scss
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/table/table.component.scss
package-lock.json

part of https://github.com/SAP/fundamental-ngx/issues/4772
This Pr contains fixes for:
- DateTimePicker - Additional change detection
- Table checkboxes:
Before:
After: 
- Documentation toolbar issues

fix: (Core|Docs) Defect hunting issues

---

apps/docs/src/app/core/component-docs/select/examples/select-programmatic-example/select-programmatic-example.component.ts

closes #4616 
Updated example to change values sequently.
- [n/a ] update `README.md`
- [n/a ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

docs: (Core) updating programmatic select example as requested by QA for testing

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-page-scrolling-example.component.ts
libs/platform/src/lib/components/table/components/table-p13-dialog/table-p13-dialog.component.ts
libs/platform/src/lib/components/table/directives/index.ts
libs/platform/src/lib/components/table/directives/table-cell-selectable.directive.ts
libs/platform/src/lib/components/table/table.component.html
libs/platform/src/lib/components/table/table.component.scss
libs/platform/src/lib/components/table/table.component.ts
libs/platform/src/lib/components/table/table.module.ts

Part of https://github.com/sap/fundamental-ngx/issues/4735
- Fixed row selection by Space/Enter button in single & multiple modes
- Fixed `ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.`
- Added ability to scroll table in "page scroll" by keyboard 
- Minor a11y enhancements _(`headers` for cells, `aria-colindex/rowindex`, roles, scopes)_
- Fixed anchors on the examples page  

fix: (Platform) table enhancements

---

libs/platform/src/lib/components/form/select/index.ts

export select option component
fixes #4796

fix: export select option component

---

libs/core/README.md

Similar Project anchor link, and link for license fix
https://sap.github.io/fundamental-ngx/#/core/home
Click on the **License** link gets you to **Similar Projects**
Fixed links to the best of my knowledge

docs: (Core) Update README.md

---

.github/PULL_REQUEST_TEMPLATE.md

introduce a new check in the PR template

chore: add a new check in the PR template

---

libs/core/src/lib/shellbar/shellbar.component.scss

fix: (Core) Remove small size shellbar unnecessary styles

---

apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.html
apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-single-example.component.ts
apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-example/datetime-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts
apps/docs/src/app/core/component-docs/global-config/examples/dialog-global-config-example/dialog-global-config-example.module.ts
apps/docs/src/app/core/component-docs/global-config/examples/message-box-global-config-example/message-box-global-config-example.module.ts
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-columns-example.component.ts
apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-example.component.html
libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/date-picker/date-picker.component.html
libs/core/src/lib/date-picker/date-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/dialog/base/dialog-config-base.class.ts
libs/core/src/lib/dialog/dialog.component.spec.ts
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
libs/core/src/lib/message-box/message-box.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/time-picker/time-picker.component.html
libs/core/src/lib/time-picker/time-picker.component.ts

part of https://github.com/SAP/fundamental-ngx/issues/4824
part of https://github.com/SAP/fundamental-ngx/issues/4826
In this PR there is:
- Added `inputId` for easier association with `label` element for - Combobox, DatePicker, DateTimePicker, MultiInput. TimePicker
- Changed dialog `closeOnBackdrop` default to false.- Now it won't close when user clicks outside of dialog
- Fix for FlexibleColumnLayout button - added `z-index: 1` to keep it visible all the time 
- Changed dialog default behaviour `closeOnBackdrop` - Now it won't close when user clicks outside of dialog

fix: Portal issues

---

.firebaserc
.gitignore
.travis.yml
deploy-to-preview-channel-core.sh
deploy-to-preview-channel-platform-a.sh
deploy-to-preview-channel-platform-b.sh
firebase.json
package-lock.json
package.json
wdio.conf.js

[4828](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4828)
Added allure to Travis CI build

test: added allure to Travis CI build

---

libs/platform/src/lib/components/slider/slider.component.spec.ts

comment randomly failing slider  unit test - issue for addressing it #4893

test: comment randomly failing slider  unit test

---

apps/docs/src/app/core/component-docs/object-number/examples/object-number-examples.component.scss
apps/docs/src/app/core/component-docs/object-number/examples/object-number-examples.component.ts
apps/docs/src/app/core/component-docs/object-number/examples/object-number-truncation-example.component.html
apps/docs/src/app/core/component-docs/object-number/object-number-docs.component.html
apps/docs/src/app/core/component-docs/object-number/object-number-docs.component.ts
apps/docs/src/app/core/component-docs/object-number/object-number-docs.module.ts
e2e/wdio/core/fixtures/appData/object-number-content.ts
e2e/wdio/core/pages/object-number.po.ts
e2e/wdio/core/tests/object-number.e2e-spec.ts

updating the example for the truncation behaviour
fixes https://github.com/SAP/fundamental-ngx/issues/3748
truncation behaviour of the component example not available so added an example to the code. 

fix: (Core) updating the example for the truncation behaviour

---

libs/store/src/lib/infrastructure/persistence/query/grammar/predicate.spec.ts
libs/store/src/lib/infrastructure/persistence/query/grammar/predicate.ts
libs/store/src/lib/infrastructure/persistence/query/grammar/query-expressions.ts

Closes #4888
This PR adds "test" methods to predicate classes for the purpose of executing logic of predicates.

feat: (Store) Store predicates

---

libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html
libs/platform/src/lib/components/approval-flow/approval-flow.component.html
libs/platform/src/lib/components/table/components/reset-button/reset-button.component.ts
libs/platform/src/lib/components/table/components/table-p13-dialog/columns/columns.component.html
libs/platform/src/lib/components/table/components/table-p13-dialog/filtering/filtering.component.html
libs/platform/src/lib/components/table/components/table-p13-dialog/grouping/grouping.component.html
libs/platform/src/lib/components/table/components/table-p13-dialog/sorting/sorting.component.html
libs/platform/src/lib/components/table/components/table-view-settings-dialog/filtering/filter-single-select.component.html
libs/platform/src/lib/components/table/components/table-view-settings-dialog/filtering/filter-step.component.html
libs/platform/src/lib/components/table/components/table-view-settings-dialog/filtering/filters-list-step.component.html
libs/platform/src/lib/components/table/components/table-view-settings-dialog/filtering/filters.component.html
libs/platform/src/lib/components/table/components/table-view-settings-dialog/grouping/grouping.component.html
libs/platform/src/lib/components/table/components/table-view-settings-dialog/sorting/sorting.component.html
libs/platform/src/lib/components/thumbnail/thumbnail-details/thumbnail-details.component.html
libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html

Closes: https://github.com/SAP/fundamental-ngx/issues/4911
This PR removed i18n duplicates.

fix: (Core|Platform) i18n id duplicates

---

apps/docs/src/app/core/component-docs/table/examples/table-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-example.component.ts
apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
libs/core/src/lib/table/directives/table-cell.directive.ts
libs/core/src/lib/table/directives/table-text.directive.ts
libs/core/src/lib/table/table.component.scss

part of https://github.com/SAP/fundamental-ngx/issues/4895
There is added `[noData]` flag to table cell and new `fd-table-text` directive usage, with `[noWrap]` flag

fix: (Core) Add no-data mode and text wrap to table cell

---

apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-url-example.component.html
apps/docs/src/app/core/component-docs/theme-switcher/examples/theme-url-example.component.ts
apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-docs.component.html
libs/core/src/lib/utils/services/themes.service.ts

fixes https://github.com/SAP/fundamental-ngx/issues/4902
There is added additional way to handle theming parameter. Now theming parameter will be also handled by javascript based solution.
- [NA] Stackblitz works for all examples

fix: (Core) Add handler for real query string

---

e2e/wdio/core/tests/object-number.e2e-spec.ts

disable object number e2e tests with hardcoded colors

test: disable object number e2e tests with hardcoded colors

---

e2e/wdio/core/tests/object-number.e2e-spec.ts

disable object number e2e visual test

test: disable object number e2e visual test [ci skip]

---

package-lock.json
package.json

bump theming-base-content version 11.1.27

chore: bump theming-base-content version 11.1.27

---

e2e/wdio/core/tests/alert.e2e-spec.ts
e2e/wdio/platform/tests/action-list-item.e2e-spec.ts
e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts

regarding https://github.com/SAP/fundamental-ngx/issues/4957
Some tests had to be temporary removed from CI, becuase of random fails

test: (Core|Platform) comment unstable tests

---

.travis.yml
deploy-to-preview-channel-core.sh
deploy-to-preview-channel-platform-a.sh
deploy-to-preview-channel-platform-b.sh

Skipped posting allure report to PRs

fix: (Core|Platform) skip posting allure report to PRs

---

apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.ts
apps/docs/src/app/core/component-docs/table/table-docs.module.ts

part of https://github.tools.sap/dxp/jukebox/issues/442
There is added documentation for busy indicator usage with table

docs: (Core) Add busy indicator to table documentation

---

libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.scss
libs/core/src/lib/multi-input/multi-input.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/token/tokenizer.component.html
libs/core/src/lib/token/tokenizer.component.spec.ts
libs/core/src/lib/token/tokenizer.component.ts
libs/platform/src/lib/components/form/multi-input/multi-input.component.html

fixes: https://github.com/SAP/fundamental-ngx/issues/4875
fixes: https://github.com/SAP/fundamental-ngx/issues/4873
There is removed unnecessary tabindex on `tokenizer` component.
Way how the focus indicator is added has been changed.
API:
- added `bodyMaxWidth` Input to MultiInput
- added `tokenizerFocusable` Input to Tokenizer
- showAll Button is improved - keydown support + visual fix
- Breaking Change - there is removed input named `tokenizerHasFocus`. It's not needed to be `@Input`

fix: (Core) Remove redundant tabbable item on multi input, remove default width limit, improve ShowAll button

---

libs/core/src/lib/dynamic-page/dynamic-page.component.html
libs/core/src/lib/dynamic-page/dynamic-page.component.scss
libs/core/src/lib/dynamic-page/dynamic-page.component.ts

There is another way of dealing with expanding `DynamicPage`
Now whole dynamic page has got hardocded height. Height for content is handled by css.

fix: (Core) Improve height calculations in dynamic page

---

libs/app-shell/src/lib/api/plugins/federation-utils.ts
libs/app-shell/src/lib/components/plugin-launcher/iframe-error.directive.spec.ts
libs/app-shell/src/lib/components/plugin-launcher/iframe-error.directive.ts
libs/app-shell/src/lib/components/plugin-launcher/plugin-launcher.component.spec.ts
libs/app-shell/src/lib/components/plugin-launcher/plugin-launcher.component.ts
libs/app-shell/src/lib/components/plugin-launcher/plugin-launcher.module.ts
libs/app-shell/src/lib/components/plugin-launcher/plugin-page-launcher.component.spec.ts
libs/app-shell/src/lib/components/plugin-launcher/plugin-page-launcher.component.ts
package.json

feat: (AppShell) Failover - Remote module loading error

---

apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.html
apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.scss
apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.ts
apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.html
apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.ts
apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.module.ts
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts

Part of https://github.com/SAP/fundamental-ngx/issues/4891
- provided an example in the documentation with Dynamic Page and controls (Expand/Exit FullScreen and Close buttons) used in the Flexible Column Layout
- fixed the direction of the animation when a column enters a fullscreen mode by replacing `ngIf` with `[style.visibility]` and `[attr.aria-hidden]` 

fix: add fix for FCL animation and example with Dynamic Page usage and layout controls

---

.travis.yml

temporarily skip not used a11y report PoC Travis Job 

test: skip a11y report PoC Travis job

---

package-lock.json
package.json

upgrade to theming-base-content version 11.1.28

chore: upgrade to theming-base-content version 11.1.28

---

libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/input-group/input-group.component.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts

fix: (Core) add input for tooltip for multi-input / input group

---

angular.json
apps/docs/browserslist
apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
package-lock.json

chore: clean up doc build

---

libs/core/src/lib/date-picker/date-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/time-picker/time-picker.component.ts

fix: datepicker/datetimepicker/timepicker console warnings

---

libs/core/src/lib/step-input/step-input.component.ts

Ignore branch name, I meant step input
part of #4908

fix: step input placeholder default value needs to be empty string

---

libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.ts

part of #4908 
because we removed the max width for multi-input i assume we need it for this component as well

fix: (Core) combobox minor tweaks for defect hunting

---

libs/core/src/lib/checkbox/checkbox/checkbox.component.ts

fix: (Core) remove non-existent method

---

apps/docs/src/app/schema/containers/schema-group/schema-group.component.html
apps/docs/src/app/schema/containers/schema-group/schema-group.component.scss

Closes #3845.
Improved Playground Platform component: label bounded to appropriate group.

docs: (Platform) playground - bind label to appropriate group

---

libs/core/src/lib/multi-input/multi-input.component.html

fix: (Core) multi input tab index bug

---

package-lock.json
package.json

chore: upgrade to npm 7.9.0

---

libs/core/src/lib/dialog/dialog-default/dialog-default.component.html

fixes  https://github.com/SAP/fundamental-ngx/issues/4967
Fixed dialog default cancel button

fix: (Core) fix dialog default cancel button

---

libs/platform/src/lib/components/table/table.component.html

Closes #4163.
Table rows are focusable now if enabled any of selection mode (single/multi).

fix: (Platform) table platform component selected row hover styles

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-tree-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-tree-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
libs/core/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.spec.ts
libs/core/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.ts
libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts
libs/platform/src/lib/components/table/components/table-column/table-column.component.ts
libs/platform/src/lib/components/table/models/index.ts
libs/platform/src/lib/components/table/models/table-row-toggle-open-state-event.model.ts
libs/platform/src/lib/components/table/models/table-row.model.ts
libs/platform/src/lib/components/table/models/table-rows-rearrange-event.model.ts
libs/platform/src/lib/components/table/public_api.ts
libs/platform/src/lib/components/table/table.component.html
libs/platform/src/lib/components/table/table.component.scss
libs/platform/src/lib/components/table/table.component.spec.ts
libs/platform/src/lib/components/table/table.component.ts
libs/platform/src/lib/components/table/table.module.ts
libs/platform/src/lib/components/table/table.service.ts
libs/platform/src/lib/components/table/table.ts
libs/platform/src/lib/utils/object.ts

Closes #4429.
This PR contains implementation on Phase 4 functionality of Tree table and Drag & Drop support.
Should not be tested for the tree table (as will be implemented in the next phase/separate ticker):
* Sorting rows.
* Filtering rows.
* Grouping rows.
* Frozen columns alongside Drag & Drop.
* Navigation over the three with the keyboard: for now you only can `tab` between actionable elements. Native navigation with the arrows will be implemented separately to handle all the tree structures.

feat: (Platform) Table Phase 4

---

libs/core/src/lib/breadcrumb/breadcrumb.component.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/pagination/pagination.component.ts
libs/core/src/lib/slider/slider.component.ts
libs/platform/src/lib/components/action-bar/action-bar.component.ts
libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
libs/platform/src/lib/components/form/combobox/combobox/combobox.component.ts
libs/platform/src/lib/components/form/multi-input/multi-input.component.ts
libs/platform/src/lib/components/split-menu-button/split-menu-button.component.ts
libs/platform/src/lib/components/table/table.component.ts

Fixes https://github.com/SAP/fundamental-ngx/issues/4802
Fixed optional rtl service

fix: (Core|Platform) fix optional rtl service

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.scss
apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.scss
apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.scss
apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.scss
apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.ts

fixes https://github.com/SAP/fundamental-ngx/issues/5086
Fixed wizard StackBlitz example

docs: (Docs) fix wizard StackBlitz example

---

libs/platform/src/lib/components/form/form-field.ts
libs/platform/src/lib/components/form/form-group.ts
libs/platform/src/lib/components/form/form-group/constants.ts
libs/platform/src/lib/components/form/form-group/form-field-group/form-field-group.component.ts
libs/platform/src/lib/components/form/form-group/form-field/form-field.component.ts
libs/platform/src/lib/components/form/form-group/form-group.component.ts
libs/platform/src/lib/components/form/form.spec.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/5151
This PR makes `fdp-form-group` capable to work with dynamicly rendered `fdp-form-field` elements.

fix: (Platform) Make fdp-form-group work with dynamic form-field child

---

package-lock.json
package.json

update how we refer rxjs version

chore: update how we refer rxjs version

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json

chore: bump ngx version to 0.29

---

apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.html
apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.html

Closes: https://github.com/SAP/fundamental-ngx/issues/5044
Closes: https://github.com/SAP/fundamental-ngx/issues/5046
- fix alignment of overflow popover header
- make phones and emails as a link (clickable)

docs: (Core) Avatar Group alignment of overflow header, phones and emails as link

---

libs/platform/src/lib/components/form/form-group.ts
libs/platform/src/lib/components/form/form-group/form-field-group/form-field-group.component.ts
libs/platform/src/lib/components/form/form-group/form-group.component.html
libs/platform/src/lib/components/form/form-group/form-group.component.ts
libs/platform/src/lib/components/form/form.spec.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/5281
This PR allows rendering of nested `fdp-form-field` 

fix: (Platform) Render fdp-form-field with wrapper

---

.github/workflows/codeql-analysis.yml

chore: enable security scanning

---

libs/store/src/lib/domain/decorators.ts
libs/store/src/lib/infrastructure/persistence/domain/base-classes/base-value.ts
libs/store/src/lib/infrastructure/persistence/domain/base-classes/composite.ts
libs/store/src/lib/infrastructure/persistence/domain/state-handler.spec.ts
libs/store/src/lib/infrastructure/persistence/domain/state-handler.ts
libs/store/src/lib/infrastructure/persistence/store/entity-collection-service-base.ts
libs/store/src/lib/infrastructure/persistence/store/entity-collections-service-base.ts
libs/store/src/lib/infrastructure/persistence/store/entity-store.spec.ts
libs/store/src/lib/infrastructure/persistence/utils/deep-copy.ts
libs/store/src/lib/infrastructure/persistence/utils/deep-freeze.ts
libs/store/src/lib/infrastructure/persistence/utils/index.ts

Closes SAP/fundamental-ngx#5217
Fix for Entity Format. It should give the ability access entity properties directly e.g. `myEntity.entityProperty`

fix: (Store) Fix entity format

---

libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts

Closes https://github.com/SAP/fundamental-styles/issues/2200

fix: (Core) wizard step indicator stacking bugs on narrow screens

---

apps/docs/src/app/platform/component-docs/platform-display-list-item/platform-display-list-item-examples/platform-display-list-item-example.component.html
apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-example.component.html
apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-with-group-header-example.component.html
apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-example.component.html
apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-with-group-header-example.component.html

Closes https://github.com/SAP/fundamental-ngx/issues/5201
Fixed platform list group title example

docs: (Platform) fix list group header title

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-loading-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-loading-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts

Part of https://github.com/SAP/fundamental-ngx/issues/3746

docs: (Platform) Table loading state example

---

apps/docs/src/app/core/component-docs/card/card-docs.component.ts
apps/docs/src/app/core/component-docs/card/examples/card-example.component.html
apps/docs/src/app/core/component-docs/card/examples/card-example.component.scss
apps/docs/src/app/core/component-docs/card/examples/card-example.component.ts

Closes SAP/fundamental-ngx#4710
Card with bottom header should have image in content as described in issue.
This PR corrects this example.
- na update `README.md`
- na [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

docs: (Core) correct card example with bottom header

---

libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html

Fixed https://github.com/sap/fundamental-ngx/issues/3454
Fixed https://github.com/sap/fundamental-ngx/issues/3456
Fixed not readable Combobox group header

fix: (Platform) combobox group header not readable for accessibility

---

commitlint.config.js

Updated commitlint rules: 
- body-max-line-length: 200
- footer-max-line-length: 200

chore: (deps-dev) update commitlint rules

---

apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-columns/combobox-columns-example.component.html
libs/platform/src/lib/components/form/combobox/commons/base-combobox.ts

Closes SAP/fundamental-ngx#3275
Fixed RTL mode for combobox secondary column

fix: (Platform) fix rtl mode for combobox secondary column

---

apps/docs/src/app/core/component-docs/popover/examples/popover-dialog/popover-dialog-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-dialog/popover-dialog-example.component.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/3143

docs: (Core) add ariaLabelledby to the dialog header for popover component

---

libs/core/src/lib/pagination/pagination.component.html
libs/core/src/lib/pagination/pagination.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/3129
Closes https://github.com/SAP/fundamental-ngx/issues/3154
This PR contains changes to fix the screen reading of "Page 1 Selected" label and also using of correct role dom element for aria-selected.

fix: (Core) fix for a11y issues of Pagination component.

---

apps/docs/src/app/documentation/core-helpers/playground/playground.component.html
apps/docs/src/app/documentation/core-helpers/playground/playground.components.scss
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/styles.scss
e2e/wdio/core/pages/pagination.po.ts

Closes #4413.
The layout of the playground component (doc-app) fixed. Also `max-height: 500px` removed (see no sense of it).

docs: (doc-app) playground layout fixes, improvements

---

libs/core/src/lib/select/select.component.ts
libs/platform/src/lib/components/form/select/commons/base-select.ts
libs/platform/src/lib/components/form/select/select/select.component.ts

Closes  #3946 
Updated a property related information for documentation-api purpose.

chore: (Core|Platform) Select Information details for docs are updated for properties

---

apps/docs/src/app/core/component-docs/popover/examples/popover-programmatic/popover-programmatic-open-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
libs/core/src/lib/icon/icon.component.ts
libs/core/src/lib/popover/popover.component.ts

Closes #3138 
Closes #3140 
Added tooltip and screenreader messages as suggested.

fix: (Core) tooltip and screenreader added for Popover

---

libs/core/src/lib/input-group/input-group.component.ts

Closes SAP/fundamental-ngx#5001
Fixed Date/Datetime/Time picker input group focus state

fix: (Core) fix pickers input groupt focus state

---

libs/core/src/lib/date-picker/date-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/time-picker/time-picker.component.html

Closes SAP/fundamental-ngx#5496
Fixed Date/Datetime/Time picker input groupt addon active state

fix: (Core) fix pickers input groupt addon active state

---

CONTRIBUTING.md
ci-scripts/hotfix-publish.sh
ci-scripts/publish.sh
commitlint.config.js
package-lock.json
package.json
parser-preset.js

Closes SAP/fundamental-ngx#
Update CONTRIBUTING.md to fix commit message and PR title pattern
Update changelog
Update commitlint
**Before:** 
type: (Scope) subject
**Now:**
type(scope): subject
- [na] all items on the PR Review Checklist are addressed :
- [na] Run npm run build-pack-library and test in external application

chore: update changelog, contribution guide, commitlint

---

libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.ts

fix: (Core) clicking on edit button in Grid List active card

---

libs/platform/src/lib/components/form/base.input.ts

Fixes https://github.com/SAP/fundamental-ngx/issues/4820
- issue about Grid list clicking on different elements of active card has been fixed.

fix: (Platform) playground disable option functions incorrectly

---

commitlint.config.js

Updated commitlint header-max-length role

chore: update commitlint header-max-length role

---

apps/docs/src/app/core/component-docs/card/card-docs.module.ts
apps/docs/src/app/core/component-docs/card/examples/card-table-example.component.html
apps/docs/src/app/core/component-docs/card/examples/link-list-card/card-link-list-example.component.html
apps/docs/src/app/core/component-docs/card/examples/list-card/card-list-example.component.html
apps/docs/src/app/core/component-docs/card/examples/list-card/card-list-example.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
e2e/wdio/core/fixtures/appData/card-content.ts

Closes SAP/fundamental-ngx#3548
Closes SAP/fundamental-ngx#3549
Closes SAP/fundamental-ngx#3863
Closes SAP/fundamental-ngx#4243
This PR fixes following issues:
1. 3548 - misplaced columns in table card corrected
2. 3549 - fix for currency in rtl mode
3. 3863 - created examples for list cards
4. 4243 - analytical cards were not showing correct colour status. table cards also fixed for column misplacement and currency.

docs: (Core) card component documentation fixes and missing examples created

---

package.json

chore: fix prerelease

---

apps/docs/src/app/platform/component-docs/platform-object-marker/platform-object-marker-docs.component.html

Closes SAP/fundamental-ngx#4698
Fixed incorrect Object Marker example title

docs: (Platform) fix incorrect Object Marker example title

---

wdio.conf.js

Closes SAP/fundamental-ngx#5506
for MacOS with FF and Chrome browsers, dialog e2e tests are flaky. Decided to temporarily skip the test suite now to prevent delays in dev PRs - will update and unskip in a future PR.

test: (e2e) skip dialog core e2e tests

---

ci-scripts/publish.sh
package.json

chore(deps-dev): fix version release

---

apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.html
libs/platform/src/lib/components/object-status/object-status.component.ts

Closes SAP/fundamental-ngx#5532
- [N/A] tests for the changes that have been done
- [N/A] Run npm run build-pack-library and test in external application
- [N/A] update `README.md`
- [N/A] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

fix(platform): clickable object status handle Enter and Space button

---

.github/workflows/greetings.yml

chore(deps-dev): greeting message for commits

---

apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-module-wrapper.ts

Closes SAP/fundamental-ngx#5591
Add focus-trap dependency for Stackblitz examples
- [na] Run npm run build-pack-library and test in external application

docs(docs): add focus-trap for stackblitz

---

.github/workflows/stale.yml

chore(deps-dev): auto close old PRs

---

ci-scripts/hotfix-publish.sh
ci-scripts/publish.sh
package-lock.json
package.json

chore: update bump version

---

apps/docs/src/app/core/component-docs/dialog/examples/component-based/component-based-dialog-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts

Component based dialog - right padding is not correct
Closes #5087 

docs(core): component based dialog - right padding is not correct

---

e2e/wdio/core/tests/carousel.e2e-spec.ts
libs/core/src/lib/carousel/carousel.component.html
libs/core/src/lib/carousel/carousel.component.scss
libs/core/src/lib/carousel/carousel.component.ts
libs/core/src/lib/carousel/carousel.module.ts

Closes SAP/fundamental-ngx#3880
Earlier importing ButtonModule in carousel module was having issue. which got resolved with new structure of main branch.
So, now using fd-button for carousel button and removed un-necessary code present.
- [NA] Documentation Examples

fix(core): use fd-button for carousel button and fix focus after last item reached

---

apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-basic-example.component.ts

Closes SAP/fundamental-ngx#4896
Fixed thumbnail example

docs(platform): fix thumbnail example

---

libs/platform/src/lib/components/search-field/search-field.component.ts

Closes SAP/fundamental-ngx#4314
Fixed Search field focus if click outside

fix(platform): fix Search field focus if click outside

---

libs/core/src/lib/scroll-spy/scroll-spy.directive.ts

Closes SAP/fundamental-ngx#3982
Fixed scroll spy target offset top

fix(core): fix scroll spy target offset top

---

package-lock.json
package.json

Closes https://github.com/SAP/fundamental-ngx/issues/4391
focus-trap version update

chore(deps): focus-trap update

---

apps/docs/src/app/core/component-docs/combobox/combobox-header/combobox-header.component.html
apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-docs.component.html

Closes SAP/fundamental-ngx#5187
Added information about the nuances of using a combobox in scrollable containers

docs: (docs) add info about dependency of combobox to popover

---

libs/platform/src/lib/components/table/table.component.scss

Closes  #5613.
Hotfix for the table selection cells.

fix(platform): table selection cells position fix

---

libs/platform/src/lib/components/base.ts
libs/platform/src/lib/components/button/button.component.html

Closes  #5548 
Updated the condensed version of the platform button looks exactly the same as compact to be in sync with latest core button changes.

fix(platform): updating condensed mode for platform button

---

libs/core/src/lib/title/title.component.ts

Closes #5036 
Update title component to calculate size after changes

fix(core): add fix for dialog header not applying styling correctly

---

apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.html
apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/second-dialog-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html
libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
libs/core/src/lib/dialog/dialog-default/dialog-default.component.html
libs/core/src/lib/dialog/dialog-default/dialog-default.component.spec.ts
libs/core/src/lib/dialog/dialog-default/dialog-default.component.ts

#5076 
Service updated, button size depends on config.mobile, documentation updated also

fix(core): fix dialogs footer button size

---

libs/core/src/lib/wizard/wizard.component.ts

Closes SAP/fundamental-ngx#5545
Added null check for wrapperComponent

fix(core): fix documentation api tab for wizard

---

.github/workflows/stale.yml

chore(deps-dev): reduce the days for stale PRs

---

.github/in-solidarity.yml

chore(deps-dev): add in-solidarity.yml file

---

libs/platform/src/lib/components/form/base.input.ts

Closes SAP/fundamental-ngx#4853

fix(platform): fix base input status if error

---

e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts
libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.html
libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.ts

Closes SAP/fundamental-ngx#4572
Closes SAP/fundamental-ngx#4573
Fixed hidden filter by default
Added missing search icon to search field

fix(platform): value help dialog, hidden filter by default, added missing search icon to search field

---

libs/core/src/lib/menu/services/menu.service.ts
libs/core/src/lib/split-button/split-button.component.html
libs/core/src/lib/split-button/split-button.component.ts

Closes SAP/fundamental-ngx#5348
After click on item, menu should close

fix(core): split button, close on click

---

libs/core/src/lib/ng-package.json
libs/core/src/lib/package.json

Closes SAP/fundamental-ngx#5703
Update package.json and use explicit library dependencies so they would also install for the third-party projects.

fix(core): use explicit dependencies

---

libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
libs/core/src/lib/date-picker/date-picker.component.html

Fixes https://github.com/SAP/fundamental-ngx/issues/5080
Fixes issue #4 about: add a mouse hover tooltip to date picker buttons

fix(core): add date picker hover tooltip

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-example.component.html

Fixes https://github.com/SAP/fundamental-ngx/issues/5080
Fixes issue 1 about: the information ‘required’ should be read for all the mandatory (*) marked fields on navigation

docs(platform): required is read for mandatory fields in date picker

---

libs/core/schematics/ng-add/styles.ts

Closes SAP/fundamental-ngx#5706
Update css paths in core schematics

fix(core): update schematics paths

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.ts

Fixes https://github.com/SAP/fundamental-ngx/issues/4466
Fixes problem with datetime picker form submission alert, returns form value instead of [object, object]

docs(platform): datetime picker form submission returns form value

---

libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html

Closes SAP/fundamental-ngx#4038
Added title for menu action

fix(platform): add title for menu action

---

.travis.yml

Fix for floating issue on Travis 

chore(deps): travis wait

---

.travis.yml

Removed Travis wait from deploy

chore: remove travis wait from deploy

---

libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts

Closes SAP/fundamental-ngx#3852

fix(core): fix shellbar-user-menu input type

---

apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts

add missing versions in doc site

docs(deps): add missing versions in doc site

---

README.md
libs/core/src/lib/README.md
libs/core/src/lib/package.json
libs/platform/package.json

update the library name in the doc

docs(docs): update library name

---

apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss
apps/docs/src/styles.scss
package-lock.json
package.json

bump theming-base-content and its usage

docs(core): bump theming-base-content and its usage

---

libs/core/src/lib/status-indicator/status-indicator.component.ts

Closes SAP/fundamental-ngx#5583
This PR adds aria attributes that announce the fill percentage of the status indicator.

fix(core): fix a11y for Status Indicator

---

libs/platform/src/lib/components/menu/menu-item.component.ts
libs/platform/src/lib/components/menu/menu-trigger.directive.ts
libs/platform/src/lib/components/menu/menu.component.ts

Closes SAP/fundamental-ngx#5753
Currently keyboard accessibility is not supported with spacebar for platform menu.
Spacebar should be able to open the menu and select a menu item on spacebar button.

fix(platform): open menu and select menu item with spacebar

---

.vscode/settings.json
libs/core/src/lib/slider/slider.component.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/5799
keyboard accessibility to RTL view working in reverse order, Fixed the issue in component.
- [NA] tests for the changes that have been done

fix(core): fix RTL view key press accessibility for Slider component

---

e2e/wdio/core/tests/carousel.e2e-spec.ts
package-lock.json
package.json

Closes https://github.com/SAP/fundamental-ngx/issues/5855
Update styles lib version in package to fix error with invalid selector.
- [n/a] all items on the PR Review Checklist are addressed :

fix(platform,core): update styles lib version

---

libs/core/src/lib/wizard/wizard-step/wizard-step.component.html

Closes #5860 
Always show dashed branching indicator for branching step

fix(core): always show dashed branching indicator

---

libs/core/src/lib/menu/menu-item/menu-item.component.ts

menuService is defined as optional and can be null. Checks added to prevent error when menuService is null.
- [na] all items on the PR Review Checklist are addressed :
- [na] Run npm run build-pack-library and test in external application

fix(core): prevent error on missing menuService

---

e2e/wdio/platform/pages/select.po.ts

none
fix e2e tests for select(platform) component

test(e2e): fix e2e tests for select component

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts

Closes #5811 
Fix navigation between step 1 and step 2 for mobile wizard examples.
- n/a tests for the changes that have been done
- n/a Run npm run build-pack-library and test in external application

fix(docs): fix wizard mobile step 2 navigation example

---

libs/core/src/lib/pagination/pagination.component.ts

Closes #5796
Added detection when direction has been changed.
- n/a tests for the changes that have been done

fix(core): fix pagination rtl

---

libs/core/src/lib/popover/popover-mobile/popover-mobile.component.spec.ts
libs/core/src/lib/popover/popover.component.spec.ts

Closes #5894 
Added missing methods to the stub services 
- n/a Run npm run build-pack-library and test in external application

fix(core): fix failing unit tests

---

libs/core/src/lib/checkbox/checkbox/checkbox.component.ts

fix(core): import FormStates to checkbox

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-disable-func-example.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/4553
This PR change contains updating the documentation for date picker example to disable the part of the calendar.

docs(platform): disable the part of the calendar in disable function example for date picker component

---

libs/core/src/lib/table/directives/table-row.directive.ts

Closes #5807.
Fix for the errors which appear on the table with `[pageScrolling]` enabled.

fix(platform): table navigatable row errors fix

---

libs/core/src/lib/popover/popover-body/popover-body.component.ts
libs/core/src/lib/popover/popover-service/popover.service.ts

Closes #4295 
Update import path in popover component and service to resolve 'deep imports' warnings.

fix(core): update imports for angular cdk connectionPositionPair

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.scss

Closes #5634 
Applied correct z-index to overlay mobile buttons from previous example on wizard page.
- n/a Run npm run build-pack-library and test in external application

fix(docs): apply correct z-index for overlay container

---

README.md

docs(core,platform): update README.md

---

apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts
libs/core/src/lib/fundamental-ngx.module.ts

Closes #4335 
Added correct component file contents, added PopoverMobileModule declaration into root module of fundamental-ngx core.

fix(docs,core): add missing modules and components

---

libs/core/src/lib/slider/slider.component.scss

Closes #5914 
Added correct box-sizing

fix(core): add box-sizing for correct tooltip size

---

apps/docs/src/app/core/component-docs/illustrated-message/examples/illustrated-message-dialog-example.component.html
apps/docs/src/app/core/component-docs/illustrated-message/examples/illustrated-message-dialog-example.component.ts
apps/docs/src/app/core/component-docs/illustrated-message/examples/illustrated-message-example.component.html
apps/docs/src/app/core/component-docs/illustrated-message/examples/illustrated-message-spot-example.component.html
apps/docs/src/app/core/component-docs/illustrated-message/illustrated-message-docs.component.html

Closes: https://github.com/SAP/fundamental-ngx/issues/4950
- [N/A] tests for the changes that have been done
- [N/A] Run npm run build-pack-library and test in external application
- [N/A] update `README.md`
- [N/A] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

docs(core): enhance Illustrated Message a11y

---

apps/docs/src/app/platform/api-files.ts
apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-docs.component.html
apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-header/platform-approval-flow-header.component.html
e2e/wdio/platform/pages/approval-flow.po.ts
e2e/wdio/platform/tests/approval-flow.e2e-spec.ts
libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.scss
libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.spec.ts
libs/platform/src/lib/components/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
libs/platform/src/lib/components/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.ts
libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-drop-zone.directive.ts
libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.scss
libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.ts
libs/platform/src/lib/components/approval-flow/approval-flow-select-type/approval-flow-select-type.component.html
libs/platform/src/lib/components/approval-flow/approval-flow-select-type/approval-flow-select-type.component.spec.ts
libs/platform/src/lib/components/approval-flow/approval-flow-select-type/approval-flow-select-type.component.ts
libs/platform/src/lib/components/approval-flow/approval-flow.component.html
libs/platform/src/lib/components/approval-flow/approval-flow.component.scss
libs/platform/src/lib/components/approval-flow/approval-flow.component.spec.ts
libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
libs/platform/src/lib/components/approval-flow/interfaces/approval-node.ts

Closes #5748, #4884.
Requested features implemented, component's code refactored a bit, toolbar buttons reordered.

feat(platform): approval flow phase 4

---

libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/dialog/base/dialog-base.class.ts

Closes #5777 
Show dropdown button if Combobox is in mobile mode.

fix(core): display dropdown button for mobile combobox

---

apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-docs.component.html

Closes #5890 
PR fixes a typo in the example.

docs(platform): fix typo in Upload Collection example

---

apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts
libs/core/src/lib/notification/notification-service/notification.service.ts
libs/core/src/lib/notification/notification/notification.component.ts

Closes #5515 
Added locally-scoped RTL service to the notification service and generated component.

fix(core,docs): add local rtl service for notification component

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts

Closes #5814 
Added navigation to the third step and submit button to complete wizard.

docs(core): add third step to mobile wizard example

---

e2e/wdio/core/tests/toolbar.e2e-spec.ts

none
- fix flakiness with toolbar tests

test(e2e): fix flaky toolbar e2e test

---

libs/platform/src/lib/components/button/button.component.spec.ts
libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
libs/platform/src/lib/components/form/step-input/step-input-control.directive.ts
libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
tslint.json

Closes #5951.
`no-restricted-globals` TSLint rule have been added.

chore(core,platform): no-restricted-globals lint rule

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-activable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-activable-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-navigatable-row-indicator-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
libs/platform/src/lib/components/table/components/table-column/table-column.component.ts
libs/platform/src/lib/components/table/models/index.ts
libs/platform/src/lib/components/table/models/table-row-activate-event.model.ts
libs/platform/src/lib/components/table/table.component.html
libs/platform/src/lib/components/table/table.component.scss
libs/platform/src/lib/components/table/table.component.ts
libs/platform/src/lib/components/table/table.module.ts

Closes #5961.
Table component refactored so the RouterModule is not required anymore.

fix(platform): table dependencies refactoring

---

e2e/wdio/core/pages/message-box.po.ts

Closes none
updates a message-box selector 

test(e2e): update message-box selector

---

libs/core/src/lib/list/list-item/list-item.component.ts
libs/core/src/lib/list/list.component.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/5779
removed list body focus and focused to the list items 

fix(core): remove list body focus and focus to the list items

---

libs/core/src/lib/datetime-picker/datetime-picker.component.html

Closes #5654 
Update cancel button type to transparent as mentioned in fiori specs.

fix(core): update button type for datetime picker cancel as per fiori

---

apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html
apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html
libs/core/src/lib/calendar/calendar-header/calendar-header.component.html

Closes #5786 
- For issues related to datepicker and datetimepicker `placement`, the docs have been updated.
- For the calendar one, it is actually a different issue. It should look like [this](https://sap.github.io/fundamental-styles/?path=/docs/components-calendar--days#landscape--mobile-) with a close button at the right, which isn't currently visible and needs to be fixed.
Before: 
After:

fix(core): fix datepicker bugs from defect hunting

---

apps/docs/src/app/core/component-docs/grid-list/examples/focusing/grid-list-focusing-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/focusing/grid-list-focusing-example.component.scss
apps/docs/src/app/core/component-docs/grid-list/examples/focusing/grid-list-focusing-example.component.ts
apps/docs/src/app/core/component-docs/grid-list/examples/index.ts
apps/docs/src/app/core/component-docs/grid-list/grid-list-docs.component.html
apps/docs/src/app/core/component-docs/grid-list/grid-list-docs.component.ts
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.ts

Closes #6001.
Focus method added.

feat(core): grid list item focus method

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-width-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-width-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-freezable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
libs/platform/src/lib/components/table/components/table-column-resizer/table-column-resizer.component.scss
libs/platform/src/lib/components/table/components/table-column-resizer/table-column-resizer.component.spec.ts
libs/platform/src/lib/components/table/components/table-column-resizer/table-column-resizer.component.ts
libs/platform/src/lib/components/table/components/table-column/table-column.component.ts
libs/platform/src/lib/components/table/components/table-column/table-column.ts
libs/platform/src/lib/components/table/constants/index.ts
libs/platform/src/lib/components/table/directives/index.ts
libs/platform/src/lib/components/table/directives/table-cell-resizable.directive.ts
libs/platform/src/lib/components/table/directives/table-scroller.directive.ts
libs/platform/src/lib/components/table/table-column-resize.service.spec.ts
libs/platform/src/lib/components/table/table-column-resize.service.ts
libs/platform/src/lib/components/table/table-scroll-dispatcher.service.spec.ts
libs/platform/src/lib/components/table/table-scroll-dispatcher.service.ts
libs/platform/src/lib/components/table/table.component.html
libs/platform/src/lib/components/table/table.component.scss
libs/platform/src/lib/components/table/table.component.spec.ts
libs/platform/src/lib/components/table/table.component.ts
libs/platform/src/lib/components/table/table.module.ts
libs/platform/src/lib/components/table/table.service.ts

Closes #4980
Input property added for the fdp-column, resizing feature implemented.
Limitations:
* Setting width in % not supported due to the `table-layout: auto` as for the frozen columns we have `position: absolute`.
* Resizing is disabled for tables with frozen columns due to the reason described in the first item. If there are only selection column present (it's also absolutely positioned by the way) - then resizing will be possible (as we definitely know the width of the selection column) but making overall columns width <100% not possible (same reason as previously).
All the items above are also mentioned in the docs and will be fixed in one of the next PRs where we will totally change the workflow to not use `position: absolute` on the table anymore. …

feat(platform): table column width & resizing

---

libs/platform/src/lib/components/table/components/table-p13-dialog/columns/columns.component.ts

Closes #5788.
Columns sorting removed.

fix(platform): table columns reordering feature columns sorting fix

---

e2e/wdio/platform/fixtures/appData/upload-collection-content.ts
e2e/wdio/platform/pages/upload-collection.po.ts
e2e/wdio/platform/tests/upload-collection.e2e-spec.ts
wdio-cron.conf.js

Closes SAP/fundamental-ngx#5746
add e2e tests for upload-collection(platform) component

test(e2e): add e2e tests for upload collection component

---

libs/core/src/lib/popover/popover-body/popover-body.component.ts

Closes #5182 
Added check if component has been already destroyed before calling detectChanges.

fix(core): check if component been destroyed before

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.scss

Closes #5808 
Various improvements to the documentation for better handling of selection/deselection/focusing of the payment option radio buttons.

docs(core): improvements to branching wizard focus/selection logic

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
libs/platform/src/lib/components/table/directives/table-cell-resizable.directive.ts
libs/platform/src/lib/components/table/table-column-resize.service.spec.ts
libs/platform/src/lib/components/table/table-column-resize.service.ts
libs/platform/src/lib/components/table/table.component.html
libs/platform/src/lib/components/table/table.component.scss
libs/platform/src/lib/components/table/table.component.spec.ts
libs/platform/src/lib/components/table/table.component.ts

Closes #5097.
Table layout fixed to support grouping & frozen columns.
Note: Text overflow in the frozen columns will be fixed in scope of #5692, see the screenshot below.

fix(platform): grouping & frozen columns table layout fix

---

apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-forms/combobox-forms-example.component.html
libs/platform/src/lib/components/form/combobox/combobox-mobile/combobox/combobox-mobile.component.spec.ts
libs/platform/src/lib/components/form/combobox/combobox-mobile/combobox/combobox-mobile.component.ts
libs/platform/src/lib/components/form/combobox/combobox.interface.ts
libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/components/form/combobox/combobox/combobox.component.ts
libs/platform/src/lib/components/form/combobox/commons/base-combobox.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/6046
This PR fixes some mobile combobox errors 

fix(platform): combobox in mobile mode

---

apps/docs/src/app/documentation/shared-core-modules.ts
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-header/platform-action-bar-header.component.html
apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-header/platform-approval-flow-header.component.html
apps/docs/src/app/platform/component-docs/platform-page-footer/platform-page-footer-header/platform-page-footer-header.component.html
apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-header/platform-thumbnail-header.component.html
apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-header/platform-upload-collection-header.component.html

add ariba labels to those component doc pages

docs(platform): add ariba labels to those component doc pages

---

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-default-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-default-example.component.ts
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-responsive-paddings-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-responsive-paddings-example.component.ts
libs/platform/src/lib/components/wizard-generator/base-wizard-generator.ts

Closes #6111
Removed title attr from examples.

fix(platform): remove unused title from examples

---

apps/docs/src/app/core/component-docs/notification/examples/component-as-content/notification-content.component.ts

Closes #6157 
This PR fixes the message strip message to reflect the state type.

docs(core): add correct state to the message strip message in Notification documentation

---

libs/core/src/lib/select/select.component.ts

Closes [#5943](https://github.com/SAP/fundamental-ngx/issues/5943)

fix(core): delete focus function

---

libs/core/src/lib/menu/menu.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/5982
We have to add listeners for submenu items changes so the menu map is updated on the service side accordingly.
- [n/a] update README.md

fix(core): add listener to submenu item changes

---

e2e/wdio/core/fixtures/testData/date-picker-tags.ts

Closes none
updates date picker (core) e2e test

test(e2e): update datePicker e2e

---

libs/core/src/lib/multi-input/multi-input.component.ts

Closes [#6159](https://github.com/SAP/fundamental-ngx/issues/6159)
Added generation of a unique id if field `inputId` doesn't set

fix(core): added default unique id for multiinput

---

apps/docs/src/app/core/component-docs/input-group/input-group-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/schema/containers/schema-group/schema-group.component.html

Closes #5691.
Playground select a11y issues fix.

fix(docs): playground select a11y fixes, refactoring

---

libs/core/src/lib/pagination/pagination.component.spec.ts
libs/core/src/lib/pagination/pagination.component.ts
libs/core/src/lib/pagination/pagination.service.spec.ts
libs/core/src/lib/pagination/pagination.service.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/6300
This PR adds some additional fields validation to avoid infinite loop

fix(core): validate itemsPerPage in pagination

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-example.component.ts
apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.ts
apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-observable-example.component.ts
apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-programatic-submit.component.ts

Closes #6277
Added correct input type for age input field.

fix(docs): correct input type for age field

---

apps/docs/src/app/core/component-docs/message-page/message-page-docs.component.ts
libs/core/src/lib/fundamental-ngx.module.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6284
Fixed StackBlitz message-page examples
The result will be visible after merging (needs new fundamental-ngx version)

fix(core): fix stackblitz message-page examples

---

libs/platform/src/lib/components/form/base.input.ts

Closes #6275
Added detection when field status changes.

fix(platform): trigger detection when field state changes

---

libs/core/src/lib/popover/popover.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6280
Fixed RTL mode for mobile view

fix(core): fix popover rtl mobile mode

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-docs.component.html
apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-example.component.html

Closes #6321 
PR improves the documentation for `showExceededText` feature.

docs(platform): improve Textarea documentation

---

e2e/wdio/platform/tests/checkbox.e2e-spec.ts

Closes none
updates checkbox e2e to work correctly on FireFox browser; based on cron job report Aug 15

test(e2e): update checkbox platform e2e test according to cron job report

---

apps/docs/src/app/core/component-docs/popover/examples/popover-new-placement/popover-cdk-placement-example.component.html

Closes https://github.com/SAP/fundamental-ngx/issues/6282
Removed static background on Popover CDK Placement example

docs(core): remove popover CDK placement example background

---

e2e/wdio/core/pages/table.po.ts
e2e/wdio/core/tests/table.e2e-spec.ts
e2e/wdio/platform/tests/button.e2e-spec.ts

Closes none
updates table e2e to run correctly on Firefox browser
skips button visual regression

test(e2e): update tests according to cron report Aug 16

---

libs/platform/src/lib/components/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.ts
libs/platform/src/lib/components/wizard-generator/wizard-generator.service.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6279
Added skip of notification about save progress if nothing change

fix(platform): wizard-generator, skip notification about save progress if nothing change

---

e2e/wdio/core/fixtures/appData/combobox-contents.ts
e2e/wdio/core/fixtures/appData/date-time-picker-contents.ts
e2e/wdio/core/pages/combobox.po.ts
e2e/wdio/core/pages/date-time-picker.po.ts
e2e/wdio/core/pages/pagination.po.ts
e2e/wdio/core/pages/popover.po.ts
e2e/wdio/core/tests/combobox.e2e-spec.ts
e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
e2e/wdio/core/tests/pagination.e2e-spec.ts
e2e/wdio/core/tests/popover.e2e-spec.ts

Closes none
updates and unskips core e2e tests to run on prod mode

test(e2e): fix and unskip core tests for prod 

---

e2e/wdio/core/fixtures/testData/date-picker-tags.ts
e2e/wdio/core/pages/date-picker.po.ts
e2e/wdio/core/tests/date-picker.e2e-spec.ts
e2e/wdio/platform/pages/date-time-picker.po.ts
e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts

Closes none
fixes e2e for date picker (core) and date time picker (platform)

test(e2e): fix date-picker and date-time-picker tests

---

e2e/wdio/platform/fixtures/appData/page-footer-contents.ts
e2e/wdio/platform/pages/page-footer.po.ts
e2e/wdio/platform/tests/page-footer.e2e-spec.ts
wdio-cron.conf.js

Closes
add e2e tests for page footer component (Platform)

test(e2e): add e2e tests for page footer platform

---

libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.html
libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.spec.ts
libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts
libs/core/src/lib/product-switch/product-switch/product-switch.component.html
libs/core/src/lib/product-switch/product-switch/product-switch.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/5770

fix(core): product-switch, fix keyboard navigation and selected item

---

apps/docs/src/app/core/component-docs/table/examples/table-navigatable-row-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-navigatable-row-example.component.ts
apps/docs/src/app/core/component-docs/table/table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-navigatable-row-button-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-navigatable-row-button-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
libs/core/src/lib/table/directives/table-row.directive.ts
libs/core/src/lib/table/table.component.ts
libs/platform/src/lib/components/table/models/table-row.model.ts
libs/platform/src/lib/components/table/public_api.ts
libs/platform/src/lib/components/table/table.component.html
libs/platform/src/lib/components/table/table.component.scss
libs/platform/src/lib/components/table/table.component.spec.ts
libs/platform/src/lib/components/table/table.component.ts

**This reverts commit 97d6f3c8**

fix(core,platform): table navigatable rows (#6357) REVERT

---

e2e/wdio/core/pages/date-picker.po.ts
e2e/wdio/core/tests/date-picker.e2e-spec.ts

Closes none
fixes issue where test fails when the current day is the last day in the week/month

test(e2e): update core datepicker tests

---

apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.scss
libs/core/src/lib/select/select.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6352
Fixed RTL mode for select

fix(core): select, fix rtl mode

---

PLATFORM_README.md
apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
apps/docs/src/app/platform/documentation/platform-documentation.component.scss

Closes https://github.com/SAP/fundamental-ngx/issues/6355
Fixed `content-margin` width for `@media (max-width: 992px)`
- [n/a] all items on the PR Review Checklist are addressed :

docs(platform): fix platform docs styles

---

wdio.conf.js

Closes none
due to test instability, will skip this spec until after the test can be reworked.

test(e2e): disable core datepicker e2e tests

---

apps/docs/src/app/core/component-docs/popover/examples/popover-scroll-example/popover-scroll-example.component.ts
libs/core/src/lib/popover/popover-body/popover-body.component.scss
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/core/src/lib/shared/interfaces/popover-position.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6287

fix(core): add RTL to left and right placement popover and visual fixes

---

apps/docs/src/app/core/component-docs/link/examples/link-example.component.html
apps/docs/src/app/core/component-docs/link/link-docs.module.ts
package-lock.json
package.json

Closes: https://github.com/SAP/fundamental-ngx/issues/6208
adding accessability label and  removing the hardcoded background

docs(core): adding accessability label and  removing the hardcoded background 

---

.travis.yml

chore: increase travis_wait time

---

apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.ts
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-generic-text-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-icon-text-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-generic-text-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.html
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts
libs/platform/src/lib/object-status/object-status.component.html

Closes https://github.com/SAP/fundamental-ngx/issues/5768
This PR contains changes to fix a11y issues for  platform object status component.  

fix(platform): fix a11y issue for object status component

---

apps/docs/src/app/core/component-docs/message-box/examples/complex-template/complex-template-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/component-based/component-based-message-box-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/custom-position/message-box-position-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/mobile-mode/message-box-mobile-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/object-based/object-based-message-box-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/semantic-types/semantic-types-example.component.ts
libs/core/src/lib/message-box/services/message-box.service.ts
libs/core/src/lib/message-box/utils/message-box-config.class.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6400
Closes https://github.com/SAP/fundamental-ngx/issues/6203
Closes https://github.com/SAP/fundamental-ngx/issues/6205
Closes https://github.com/SAP/fundamental-ngx/issues/6201
Fixed RTL mode for Message box component

fix(core): message-box, fix rtl mode

---

wdio-cron.conf.js

Closes none
update cron job wdio config to exclude datepicker test 
- [ n/a] update `README.md`
- [n/a ] Documentation Examples
- [n/a ] Stackblitz works for all examples

test(e2e): update cron job wdio config to exclude datepicker test

---

libs/platform/src/lib/menu/menu-item.component.html
libs/platform/src/lib/menu/menu-item.component.ts
libs/platform/src/lib/menu/menu-trigger.directive.ts
libs/platform/src/lib/menu/menu.component.html
libs/platform/src/lib/menu/menu.component.ts
libs/platform/src/lib/menu/menu.spec.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/5461
This fixes platform menu-item structure to follow fundamental-styles

fix(platform): fix fdp-menu-item extra spaces

---

apps/docs/src/app/core/component-docs/list/examples/list-dnd-example/list-dnd-example.component.html
apps/docs/src/app/core/component-docs/list/examples/list-dnd-example/list-dnd-example.component.ts
libs/core/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.ts
libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts

Closes https://github.com/SAP/fundamental-ngx/issues/5095

fix(core): dnd prevent focus applying after dropping item

---

.github/PULL_REQUEST_TEMPLATE.md

chore(release): update PR Template

---

libs/core/src/lib/tabs/tab-list.component.html
libs/core/src/lib/tabs/tab-list.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/4424
-  Icon only tabs works
- set collapseOverflowto true by default

fix(core): tabs, fix collapseOverflow for icon only mode

---

libs/platform/src/lib/form/auto-complete/auto-complete.directive.ts

Closes https://github.com/SAP/fundamental-ngx/issues/5541

fix(platform): combobox tab order in safari

---

apps/docs/src/app/core/component-docs/input-group/examples/input-group-states-example.component.html
libs/core/src/lib/input-group/input-group.component.html

Closes [#6220](https://github.com/SAP/fundamental-ngx/issues/6220) 

fix(core): overwrite title and aria-label in input-group component

---

libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts

Closes https://github.com/SAP/fundamental-ngx/issues/4195
Closes https://github.com/SAP/fundamental-ngx/issues/6406
Fixed flexible-column-layout unit tests

test(core): flexible-column-layout, fix tests

---

libs/platform/src/lib/object-attribute/object-attribute.component.html

Closes SAP/fundamental-ngx/https://github.com/SAP/fundamental-ngx/issues/5767
This PR change contains to fixes a11y issues for the platform object attribute component.
4. …

fix(platform): fix a11y issue for platform object attribute component

---

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-external-navigation-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-external-navigation-example.component.ts
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-summary-objects-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-summary-objects-example.component.ts
apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.module.ts
libs/platform/src/lib/form/form-generator/form-generator.service.ts
libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html
libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.ts
libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts
libs/platform/src/lib/form/form-group/form-field/form-field.component.html
libs/platform/src/lib/form/form-group/form-group.component.ts
libs/platform/src/lib/wizard-generator/base-wizard-generator.ts
libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.html
libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.html
libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.html
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.ts
libs/platform/src/lib/wizard-generator/interfaces/wizard-dialog-data.interface.ts
libs/platform/src/lib/wizard-generator/wizard-generator.service.spec.ts

Closes #6488 #6487 #6245
fix object rendering on summary page
fix overriding layout of form field
fix hiding navigation buttons for wizard generator
added example with object rendering on summary page
added example of external navigation buttons
4. …

fix(platform): fix wizard generator related issues

---

libs/platform/src/lib/form/input/input.component.html
libs/platform/src/lib/form/input/input.component.ts
libs/platform/src/lib/form/step-input/number/number-step-input.component.html
libs/platform/src/lib/form/text-area/text-area.component.html
libs/platform/src/lib/form/text-area/text-area.component.spec.ts
libs/platform/src/lib/form/text-area/text-area.component.ts
libs/platform/src/lib/shared/form/base.input.ts

Closes https://github.com/SAP/fundamental-ngx/issues/3092
implemented focus() interface for input and textarea components

fix(platform): input, textarea, fix focus

---

libs/core/src/lib/menu/menu.component.ts

Closes SAP/fundamental-ngx/#6401
Fixed close popover on destroying menu component …

fix(core): menu, fix close popover on destroy

---

libs/platform/src/lib/value-help-dialog/components/define-tab/define-tab.component.scss

Closes #6449
Fixed broken layout for value help dialog
- [n/a] different combinations of components …

fix(platform): vhd, fix row margin

---

libs/platform/src/lib/form/form-group/form-field/form-field.component.html

Removed unnecessary code from form-field html
- [n/a] missing API documentation …

fix(platform): form-field, remove unnecessary code

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-no-items-template-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-no-items-template-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
libs/platform/src/lib/table/components/no-data-wrapper/no-data-wrapper.component.ts
libs/platform/src/lib/table/public_api.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.module.ts

Closes SAP/fundamental-ngx/#6482
Added ability to define custom element for rendering "No data" message.

feat(platform): custom element for no data message

---

libs/core/src/lib/utils/directives/resize/resize.directive.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6397
Fixed resizable in RTL mode

fix(core): dialog, fix resizable in RTL mode

---

e2e/wdio/helper/common-helper.ts
e2e/wdio/platform/pages/form-container.po.ts
e2e/wdio/platform/tests/form-container.e2e-spec.ts
wdio-cron.conf.js

Closes none
add e2e tests for platform form container component
- [ …

test(e2e): add e2e for form container component

---

apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-clickable-example.component.html
apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-text-example.component.html
libs/core/src/lib/object-marker/object-marker.component.ts

Closes SAP/fundamental-ngx/#6094
There were a couple of accessibility issues found. This PR addresses them. Additionally fixed typo in `Object marker icon and text clickable` example.
- [n/a States - hover/disabled/focused/active/on click/selected/selected hover/press state
- [n/a] different combinations of …

fix(core): a11y for object marker component

---

package-lock.json

Quality of life improvement, removes notification on any build step to update browser list

chore(core): update browser list

---

e2e/wdio/core/fixtures/appData/message-page-content.ts
e2e/wdio/core/pages/message-page.po.ts
e2e/wdio/core/tests/message-page.e2e-spec.ts
e2e/wdio/helper/assertion-helper.ts

Closes none
add e2e tests for core message page component
- [ n/a] …

test(e2e): add tests for message page component

---

apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.html
apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.scss
libs/core/src/lib/switch/switch.component.html

Fixed a11y issues for `switch` component.
Also fixed an issue with trailing space is only one of `activeText`/`inactiveText` is provided
- [ n/a API boundary values
- [n/a] change the API values during …

fix(core): a11y issues with switch component

---

e2e/wdio/core/pages/timeline.po.ts
e2e/wdio/core/tests/timeline.e2e-spec.ts

Closes none
add e2e tests for core timeline component
- [ n/a] …

test(e2e): add tests for timeline component

---

e2e/wdio/core/pages/dynamic-page.po.ts
e2e/wdio/core/tests/dynamic-page.e2e-spec.ts

Closes none
add e2e tests for core dynamic page component
- [n/a ] change the API values during testing …

test(e2e): add e2e tests for dynamic page component

---

libs/core/src/lib/micro-process-flow/components/micro-process-flow/micro-process-flow.component.scss
libs/core/src/lib/micro-process-flow/mixins.scss

Relates to #6498
Fix margin property for connector in rtl mode

fix(core): rtl fix for connector margin

---

apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.html
apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.scss

Fixing comments for the PR https://github.com/SAP/fundamental-ngx/pull/6554

fix(core): switch component a11y

---

e2e/wdio/core/pages/token.po.ts
e2e/wdio/core/tests/token.e2e-spec.ts

Closes none
add e2e for core token component …

test(e2e): add tests for token component

---

apps/docs/src/app/core/component-docs/grid-list/examples/default/grid-list-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/delete/grid-list-delete-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/dnd/grid-list-dnd-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/focusing/grid-list-focusing-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/footer/grid-list-footer-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/group/grid-list-group-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/layout/grid-list-layout-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/more/grid-list-more-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/multi-select/grid-list-multi-select-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/single-select/grid-list-single-select-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/states/grid-list-states-example.component.html
apps/docs/src/app/core/component-docs/grid-list/examples/statuses/grid-list-statuses-example.component.html
libs/core/src/lib/grid-list/components/grid-list-group-header/grid-list-group-header.component.html
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.ts
libs/core/src/lib/grid-list/components/grid-list/grid-list.component.html
libs/core/src/lib/grid-list/components/grid-list/grid-list.component.ts

Closes SAP/fundamental-ngx/#5774
Fixed grid list a11y issues 
- [ n/a API boundary values
3. …

fix(core): grid list a11y

---

e2e/wdio/core/fixtures/appData/title-contents.ts
e2e/wdio/core/pages/title.po.ts
e2e/wdio/core/tests/title.e2e-spec.ts

Closes none
add e2e tests for core title component
- [n/a ] change the API values during testing …

test(e2e): add e2e test for title component

---

e2e/wdio/core/pages/dynamic-page.po.ts

Closes none
update dynamic page test selector to fix issue on FF for MacOS where the tab content area wasn't fully scrolled to
- [ n/a] visual misalignments/updates
- [n/a ] change the API …

test(e2e): update dynamicPage selector per cron job report

---

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-customizable-embeded-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-customizable-embeded-example.component.ts
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-customizable-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-customizable-example.component.ts
apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.module.ts
libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.html
libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.html
libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.html
libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.html
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-step.component.html
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-step.component.ts
libs/platform/src/lib/wizard-generator/directives/fdp-wizard-generator-finish-button.directive.ts
libs/platform/src/lib/wizard-generator/directives/fdp-wizard-generator-go-next-button.directive.ts
libs/platform/src/lib/wizard-generator/directives/wizard-generator-finish-button.directive.ts
libs/platform/src/lib/wizard-generator/directives/wizard-generator-go-next-button.directive.ts
libs/platform/src/lib/wizard-generator/directives/wizard-generator-summary-step.directive.ts
libs/platform/src/lib/wizard-generator/interfaces/wizard-dialog-data.interface.ts
libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-summary-item.interface.ts
libs/platform/src/lib/wizard-generator/public_api.ts
libs/platform/src/lib/wizard-generator/wizard-generator.module.ts

Closes #6576 
Closes #6576
Added ability to define a custom template for the Summary step of Wizard generator. …

feat(platform): custom wizard generator summary section

---

e2e/wdio/platform/fixtures/appData/form-generator-contents.ts
e2e/wdio/platform/fixtures/testData/form-generator.ts
e2e/wdio/platform/pages/form-generator.po.ts
e2e/wdio/platform/tests/form-generator.e2e-spec.ts
wdio-cron.conf.js

Closes none
add e2e tests for platform form generator component
- [ n/a] visual misalignments/updates …

test(e2e): add e2e tests for form generator component

---

apps/docs/src/app/core/component-docs/popover/examples/popover-focus-example/popover-focus-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-scroll-example/popover-scroll-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.ts
libs/core/src/lib/popover/popover.component.ts
libs/core/src/lib/segmented-button/segmented-button.component.ts

Closes SAP/fundamental-ngx/#6097
fix popover a11y issues …

fix(core): popover a11y issues

---

libs/platform/src/lib/form/combobox/combobox.module.ts
libs/platform/src/lib/form/combobox/pipes/highlight.pipe.spec.ts
libs/platform/src/lib/form/combobox/pipes/highlight.pipe.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox.module.ts
libs/platform/src/lib/form/multi-combobox/pipes/highlight.pipe.spec.ts
libs/platform/src/lib/form/multi-combobox/pipes/highlight.pipe.ts
libs/platform/src/lib/form/public_api.ts

Closes SAP/fundamental-ngx/#6481
Fixed failing unit tests when host app uses Jest …

fix(platform): rename pipes with the same name

---

apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-example.component.html
apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-ratings.component.html
apps/docs/src/app/core/component-docs/rating-indicator/examples/rating-indicator-sizes.component.html
apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-custom-icon-example.component.html
apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-display-mode-example.component.html
apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-dynamic-example.component.html
libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
libs/core/src/lib/rating-indicator/pipes/rating-star-label.pipe.ts
libs/core/src/lib/rating-indicator/rating-indicator.module.ts

Closes SAP/fundamental-ngx/#6183
Fixing a11y for rating indicator
- [n/a] [Breaking Changes …

fix(core): rating indicator a11y

---

apps/docs/src/app/core/component-docs/button/button-docs.component.html
apps/docs/src/app/core/component-docs/button/examples/button-state-example.component.html

enhance the button state doc with references related to #6206 Issue 1

docs(core): remove wrong button state example

---

libs/platform/src/lib/search-field/search-field.component.scss
libs/platform/src/lib/search-field/search-field.component.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
libs/platform/src/lib/table/constants/index.ts

Closes SAP/fundamental-ngx/#6540
- fixed issue with cleared value from lookup field not being applied to table
- fixed search field focus buttons visual defects …

fix(platform): table - filtering feature bugs

---

libs/platform/src/lib/table/components/table-p13-dialog/sorting/get-available-sort-columns.pipe.ts
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.html
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.ts
libs/platform/src/lib/table/table.module.ts

Closes SAP/fundamental-ngx/#6542
fixed an ability to select the same column multiple times …

fix(platform): table - sorting bug

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.service.ts

Closes SAP/fundamental-ngx/#6546
FIxed an issue with missing an indication when the column is filtered through the column option. When we sort from the column we have the icon. Now there's the same behavior when it is filtered from there
5. …

fix(platform): table - column sorting bug

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts

Closes SAP/fundamental-ngx/#6549
Fixed incorrect doc
- [n/a] missing API …

fix(platform): table missing doc

---

libs/platform/src/lib/search-field/search-field.component.html
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.service.ts

Closes SAP/fundamental-ngx/#6548
Fixed table filter in busy state
- [n/a] tests for the changes that have been …

fix(platform): table - busy state bug

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-activable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-column-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-width-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-default-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-filterable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-freezable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-groupable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-initial-state-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-loading-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-multiple-row-selection-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-navigatable-row-indicator-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-no-items-template-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-columns-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-filter-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-group-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-sort-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-page-scrolling-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-single-row-selection-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-sortable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-tree-example.component.html
libs/platform/src/lib/table/components/table-column/table-column.component.ts
libs/platform/src/lib/table/table-column-resize.service.ts
libs/platform/src/lib/table/table.component.ts

Closes SAP/fundamental-ngx/#6539
- removed hardcoded content density and added support for dynamic content density from the corresponding service
- fixed an issue with cell's `width` input working only when component is initialised
- [n/a] missing API documentation or it is not …

fix(platform): table - content density and width issues

---

angular.json
libs/platform/src/lib/form/text-area/text-area.component.spec.ts

Closes SAP/fundamental-ngx/#6696
Skip failed test

test(platform): textarea, skip test

---

apps/docs/src/app/core/component-docs/list-byline/examples/list-byline-button-example/list-byline-button-example.component.html
apps/docs/src/app/core/component-docs/list-byline/examples/list-byline-navigation-example/list-byline-navigation-example.component.html
libs/platform/src/lib/form/text-area/text-area.component.spec.ts

Closes SAP/fundamental-ngx/: https://github.com/SAP/fundamental-ngx/issues/6223
adding tooltip to the button for list biline component and adding role to the list item.

docs(core): adding tooltip to the button for list byline component

---

apps/docs/src/app/core/component-docs/switch/examples/semantic-switch-example/semantic-switch-example.component.html

Added `aria-labelledby` in switch example

fix(core): add aria-labelledby in switch example

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-default-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-default-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-single-row-selection-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-single-row-selection-example.component.ts
libs/platform/src/lib/table/models/index.ts
libs/platform/src/lib/table/models/row-comparator.model.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

Closes SAP/fundamental-ngx/#6545
1. Added an ability to preserve row selection when data has changed
2. Added `trackBy` functions to improve performance …

fix(platform): table - preserve row selection on data changed

---

e2e/wdio/core/tests/fixed-card-layout.e2e-spec.ts
e2e/wdio/core/tests/inline-help.e2e-spec.ts
e2e/wdio/core/tests/standard-list.e2e-spec.ts

Closes none
fix e2e according to failing builds and cron job report …

test(e2e): fix e2e tests

---

libs/platform/src/lib/search-field/search-field.component.scss
libs/platform/src/lib/search-field/search-field.component.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
libs/platform/src/lib/table/constants/index.ts

Closes SAP/fundamental-ngx/#6540
fixed issue with cleared value from lookup field not being applied to table
fixed search field focus buttons visual defects …

fix(platform): table, filtering feature bugs

---

apps/docs/src/app/platform/component-docs/platform-icon-tab-bar/platform-icon-tab-bar-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-icon-tab-bar/platform-icon-tab-bar-header/platform-icon-tab-bar-header.component.html
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-base.class.ts
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.html
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-icon-type/icon-tab-bar-icon-type.component.html
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.html
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
libs/platform/src/lib/icon-tab-bar/components/popovers/icon-tab-bar-popover-base.class.ts
libs/platform/src/lib/icon-tab-bar/components/popovers/icon-tab-bar-popover/icon-tab-bar-popover.component.html
libs/platform/src/lib/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.html
libs/platform/src/lib/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.ts
libs/platform/src/lib/icon-tab-bar/icon-tab-bar.component.html
libs/platform/src/lib/icon-tab-bar/icon-tab-bar.component.ts

Several issues from [Defect Hunting](https://github.com/SAP/fundamental-ngx/issues/6498) of Sprint 71
- Added accessibility to tabs and fix focus issue.
- Refactor docs
- Fixed destiny for tabs

fix(platform): icon tab bar sprint 71 defect hunting

---

apps/docs/src/app/core/component-docs/message-box/examples/complex-template/complex-template-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/complex-template/message-box-complex-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/component-based/component-based-message-box-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/component-based/message-box-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/custom-position/message-box-position-example.component.html
apps/docs/src/app/core/component-docs/message-box/examples/custom-position/message-box-position-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/mobile-mode/message-box-mobile-example.component.html
apps/docs/src/app/core/component-docs/message-box/examples/mobile-mode/message-box-mobile-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/object-based/object-based-message-box-example.component.html
apps/docs/src/app/core/component-docs/message-box/examples/object-based/object-based-message-box-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/semantic-types/semantic-types-example.component.html
apps/docs/src/app/core/component-docs/message-box/examples/semantic-types/semantic-types-example.component.ts
apps/docs/src/app/core/component-docs/message-box/examples/template-based/template-based-message-box-example.component.html
apps/docs/src/app/core/component-docs/message-box/examples/template-based/template-based-message-box-example.component.ts
libs/core/src/lib/message-box/message-box-header/message-box-header.component.html
libs/core/src/lib/message-box/message-box-header/message-box-header.component.spec.ts
libs/core/src/lib/message-box/message-box.component.html
libs/core/src/lib/message-box/message-box.component.ts

Closes SAP/fundamental-ngx/#6139
Fixed message box a11y issues
- [n/a] missing …

fix(core): message-box, fix a11y issues

---

apps/docs/src/app/core/component-docs/switch/examples/semantic-switch-example/semantic-switch-example.component.html
apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.html
apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.scss
libs/core/src/lib/switch/switch.component.html

fix(core): switch, fix a11y issues

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-freezable-example.component.html

Closes SAP/fundamental-ngx/#6547
Removed fixed height for the table, because it led to odd behavior when results are filtered 
- [n/a] different combinations of …

fix(platform): table - column freezing bug

---

e2e/wdio/core/pages/notification.po.ts
e2e/wdio/core/tests/notification.e2e-spec.ts

Closes none
add e2e for core notification component …

test(e2e): add e2e tests for notification component

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
libs/platform/src/lib/table/constants/index.ts
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts

Closes SAP/fundamental-ngx/#6543
There were few content density issues with playground example.
This PR addresses all of them except for one that is handled by https://github.com/SAP/fundamental-styles/pull/2751 …

fix(platform): table - content density bugs

---

apps/docs/src/app/core/component-docs/switch/examples/semantic-switch-example/semantic-switch-example.component.html
apps/docs/src/app/core/component-docs/switch/examples/switch-binding-example/switch-binding-example.component.html
libs/core/src/lib/switch/switch.component.html

fix(core):  switch, fix a11y issues

---

libs/platform/src/lib/table/components/table-p13-dialog/sorting/get-available-sort-columns.pipe.ts
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.html
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.ts
libs/platform/src/lib/table/table.module.ts

Closes SAP/fundamental-ngx/#6542
- fixed an ability to select the same column multiple times …

fix(platform): table, fix sorting issue

---

.github/workflows/on-push-or-pull.yml
ci-scripts/hotfix-publish.sh
ci-scripts/publish.sh

Closes none
fix github actions
- [ n/a] visual misalignments/updates
- [ n/a] missing API documentation …

chore(ci): should not overwrite standard env params like github_token

---

apps/docs/src/app/core/component-docs/popover/examples/popover-scroll-example/popover-scroll-example.component.html
libs/core/src/lib/dialog/dialog.component.ts
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.html
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.ts

Closes SAP/fundamental-ngx/#6097
Adjustments according to following comments https://github.com/SAP/fundamental-ngx/pull/6594#issuecomment-927789827

fix(core): mobile popover a11y adjustments

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss

Closes SAP/fundamental-ngx/#6546
Addressing PR comments

fix(platform): table - column sorting issue

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/combobox/combobox.component.scss

Closes SAP/fundamental-ngx/#5503
Fixed an issue with combobox items alignment in IE when tabbed over
- [n/a] update …

fix(platform): combobox item alignment issue in IE

---

apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
apps/docs/src/app/documentation/core-helpers/stackblitz/utils/parse-version.spec.ts
apps/docs/src/app/documentation/core-helpers/stackblitz/utils/parse-version.ts

Closes SAP/fundamental-ngx/#6671
There's an issue with stackblitz not being able to install recently published version of a package.
To fix this, instead of providing exact version to install, now providing the minor version. Based on it the most recent patch version will be installed from what's available. …

fix(core,platform): stackblitz examples are broken

---

.travis.yml

Closes none
revert RC release to Travis
- [n/a ] change the API values during testing
- [n/a ] missing API …

chore: travis RC release only

---

libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
libs/core/src/lib/rating-indicator/pipes/rating-star-label.pipe.ts

Closes SAP/fundamental-ngx/#6183
This PR introduces an ability to change rating indicator's value when JAWS is on.

fix(core): rating indicator keyboard a11y

---

apps/docs/tsconfig.json

Closes SAP/fundamental-ngx/#6671
Extra properties cause vscode to complain

chore: remove extra props from tsconfig.json

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-freezable-example.component.html
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss

Closes SAP/fundamental-ngx/#6547
Removed fixed height for the table, because it led to odd behavior when results are filtered 
- [n/a] change the API values …

fix(platform): table, fix column freezing issue

---

libs/core/src/lib/pagination/pagination.component.ts

Closes SAP/fundamental-ngx/#6753
`@angular/localize` requirement removed, input refactored.
Nothing changed.

fix(core): pagination a11y

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-data-items-example.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-semantic-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-semantic-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
libs/platform/src/lib/table/constants/index.ts
libs/platform/src/lib/table/table-column-resize.service.spec.ts
libs/platform/src/lib/table/table-column-resize.service.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts
package-lock.json
package.json

Closes #6360
Semantic Highlighting feature for Platform Table.
**Note**: due to the netlify cache you won't see the right colours in the semantic column. So please test it locally after `npm ci`.
-

feat(platform): table semantic highlighting

---

libs/platform/src/lib/search-field/search-field.component.html
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.service.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6548
Fixed table filter in busy state …

fix(platform): table, fix busy state issue

---

apps/docs/src/app/core/component-docs/moment-datetime-adapter/moment-datetime-adapter-header/moment-datetime-adapter-header.component.html
apps/docs/src/app/core/component-docs/moment-datetime-adapter/moment-datetime-adapter-header/moment-datetime-adapter-header.component.ts

There is no information that `@fundamental-ngx/moment-adapter` package should be installed separately. It's obvious in the assumption of the package's name but let's document this.

docs(core): moment adapter

---

apps/docs/src/app/core/component-docs/textarea/examples/textarea-example.component.html
apps/docs/src/app/core/component-docs/textarea/examples/textarea-form-group-example.component.html
apps/docs/src/app/core/component-docs/textarea/examples/textarea-inline-help-example.component.html
apps/docs/src/app/core/component-docs/textarea/examples/textarea-state-example.component.html
libs/core/src/lib/form/form-label/form-label.component.html
libs/core/src/lib/form/form-label/form-label.component.scss

Closes SAP/fundamental-ngx/#6180
Fixed textarea a11y issues
- [n/a] missing API …

fix(core): textarea, fix a11y issues

---

apps/docs/src/app/core/component-docs/popover/examples/popover-focus-example/popover-focus-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-scroll-example/popover-scroll-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
libs/core/src/lib/dialog/dialog.component.ts
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.html
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.ts
libs/core/src/lib/popover/popover.component.ts
libs/core/src/lib/segmented-button/segmented-button.component.ts

Closes SAP/fundamental-ngx/#6097
Fixed popover a11y issues
- [n/a] missing API …

fix(core): popover, fix a11y issues

---

libs/core/src/lib/multi-input/multi-input.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6290
Fixed mobile mode that does not fully exhibit RTL mode
- [n/a] …

fix(core): multi-input, fix rtl mode for mobile view

---

e2e/wdio/core/fixtures/appData/dialog-contents.ts
e2e/wdio/core/pages/dialog.po.ts
e2e/wdio/core/tests/dialog.e2e-spec.ts
wdio-cron.conf.js
wdio.conf.js

Closes none
update e2e tests for dialog component
- [ n/a] visual misalignments/updates
- [n/a ] missing …

test(e2e): update e2e tests for dialog component

---

apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
apps/docs/src/app/documentation/core-helpers/stackblitz/utils/parse-version.spec.ts
apps/docs/src/app/documentation/core-helpers/stackblitz/utils/parse-version.ts
apps/docs/tsconfig.app.json
apps/docs/tsconfig.json
apps/docs/tsconfig.netlify.json

Closes https://github.com/SAP/fundamental-ngx/issues/6671
There's an issue with stackblitz not being able to install recently published version of a package.
To fix this, instead of providing exact version to install, now providing the minor version. Based on it the most recent patch version will be installed from what's available. …

docs(core,platform): fix stackblitz examples

---

libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.spec.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/6827
Fixes for the unit tests of the Table Toolbar component.

test(platform): fix table unit tests

---

apps/docs/src/app/core/component-docs/icon/examples/icon-businessSuiteInAppSymbols-example.component.html
apps/docs/src/app/core/component-docs/icon/examples/icon-example.component.html
apps/docs/src/app/core/component-docs/icon/examples/icon-tnt-example.component.html

Closes SAP/fundamental-ngx/[#6195](https://github.com/SAP/fundamental-ngx/issues/6195) …

docs(core): add tabindex in icon examples components

---

libs/core/src/lib/slider/slider.component.ts
libs/platform/src/lib/form/combobox/commons/base-combobox.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox.interface.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
libs/platform/src/lib/form/step-input/base.step-input.ts
libs/platform/src/lib/form/text-area/text-area.component.ts
libs/platform/src/lib/shared/domain/data-model.ts

Closes SAP/fundamental-ngx/#6781
Some of the components are not being visually reset when using `setValue(null)` or `reset()` on the reactive form.
Affected components:
- combobox
- multi-combobox
- number step input
- textarea
- slider
- [ x all items on the PR Review Checklist are addressed :
- [n/a] Run npm run build-pack-library and test in external …

fix(platform): should be able to reset form components

---

libs/platform/src/lib/form/input-group/input-group.component.spec.ts
libs/platform/src/lib/shared/form/base.input.ts

Closes SAP/fundamental-ngx/#6719.
Fix for the base input class to mark a control as touched only on blur, not on focus.
Gets touched state only after blur/input.

fix(platform): input touched state

---

libs/core/src/lib/table/directives/table-row.directive.ts
libs/core/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.spec.ts
libs/platform/src/lib/table/table.component.ts

Relates to https://github.com/SAP/fundamental-ngx/issues/5025
There is still some amount of CSS code present due to the specific of the component, as many things have been overwritten in comparison to the original table.
~~**Note**: I've changed scrollbar style to prevent from having double borders (see screenshot below) but it works only in WebKit-based browsers and there is no way to get it in FF, IE. In the SAPUI5 it's made by writing a custom scrollbar using javascript code if we want also functionality like that we can implement it separately.~~
**EDIT:** Tested, not working properly even in Chrome. …

fix(core,platform): table styles refactoring

---

apps/docs/src/app/core/component-docs/bar/bar-docs.component.html
apps/docs/src/app/core/component-docs/bar/bar-docs.component.ts
apps/docs/src/app/core/component-docs/bar/bar-docs.module.ts
apps/docs/src/app/core/component-docs/bar/examples/bar-with-title-example.component.html
apps/docs/src/app/core/component-docs/bar/examples/bar-with-title-example.component.ts
libs/core/src/lib/bar/directives/bar-element.directive.spec.ts
libs/core/src/lib/bar/directives/bar-element.directive.ts

Closes SAP/fundamental-ngx/#5681
This is a follow-up change for https://github.com/SAP/fundamental-styles/pull/2480. Added a special case with title element …

feat(core): add title for the bar component

---

apps/docs/src/app/core/component-docs/button/button-header/button-header.component.html
apps/docs/src/app/core/component-docs/button/examples/button-icons-example.component.html
apps/docs/src/app/core/component-docs/button/examples/button-menu-example.component.html
apps/docs/src/app/core/component-docs/button/examples/button-sizes-example.component.html
apps/docs/src/app/core/component-docs/button/examples/button-types-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html
e2e/wdio/platform/pages/multi-input.po.ts
libs/core/src/lib/bar/button-bar/button-bar.component.ts
libs/core/src/lib/button/base-button.ts
libs/core/src/lib/button/button.component.ts
libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html
libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/panel/panel.component.html
libs/platform/src/lib/button/button.component.html
libs/platform/src/lib/panel/panel.component.spec.ts

Closes: https://github.com/SAP/fundamental-ngx/issues/6206
adding accessability label and reading button type

fix(core): adding accessability label and reading button type

---

apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-clickable-example.component.html
apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-example.component.html
apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-text-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-clickable/object-marker-text-clickable-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-only-example/object-marker-text-only-example.component.html
apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker/object-marker-example.component.html
e2e/wdio/core/fixtures/appData/object-marker-content.ts
libs/core/src/lib/object-marker/object-marker.component.ts
libs/platform/src/lib/object-marker/object-marker.component.html
libs/platform/src/lib/object-marker/object-marker.component.spec.ts
libs/platform/src/lib/object-marker/object-marker.component.ts
package-lock.json
package.json

Closes SAP/fundamental-ngx/https://github.com/SAP/fundamental-ngx/issues/6093, https://github.com/SAP/fundamental-ngx/issues/6094
This PR change fix accessibility bug for object marker component in both core and platform library.  …

fix(core,platform): fix a11y issues for object marker component for core and platform lib

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-activable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-column-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-custom-width-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-default-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-filterable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-freezable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-groupable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-initial-state-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-loading-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-multiple-row-selection-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-navigatable-row-indicator-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-no-items-template-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-columns-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-filter-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-group-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-p13-sort-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-page-scrolling-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-single-row-selection-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-sortable-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-tree-example.component.html
libs/platform/src/lib/table/components/table-column/table-column.component.ts
libs/platform/src/lib/table/table-column-resize.service.ts
libs/platform/src/lib/table/table.component.ts

Closes SAP/fundamental-ngx/#6539
- removed hardcoded content density and added support for dynamic content density from the corresponding service
- fixed an issue with cell's `width` input working only when component is initialised
- [n/a] missing API documentation or it is not …

fix(platform): table, fix content density and width issues

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-list-object.component.html

Closes https://github.com/SAP/fundamental-ngx/issues/6708

docs(platform): checkbox group pre-selected output label

---

libs/platform/src/lib/form/combobox/combobox.config.ts
libs/platform/src/lib/form/combobox/commons/base-combobox.ts
libs/platform/src/lib/form/combobox/pipes/highlight.pipe.spec.ts
libs/platform/src/lib/form/combobox/pipes/highlight.pipe.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/pipes/highlight.pipe.spec.ts
libs/platform/src/lib/form/multi-combobox/pipes/highlight.pipe.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input.component.ts
libs/platform/src/lib/form/multi-input/multi-input.config.ts
libs/platform/src/lib/form/multi-input/public_api.ts
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/list/list.config.ts
libs/platform/src/lib/shared/domain/array-data-source.ts
libs/platform/src/lib/shared/domain/base-data-provider.ts
libs/platform/src/lib/shared/domain/data-source.ts
libs/platform/src/lib/shared/domain/observable-data-source.ts

Closes https://github.com/sap/fundamental-ngx/issues/3529
Extended MatchingStrategy
Added STARTS_WITH_PER_TERM matching strategy, set to use by default for combobox, multi-combobox, multi-input platform components
- [n/a] …

fix(platform): extend MatchingStrategy

---

libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.html
libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.html
libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.ts

Closes #6829 
Added correct passing of the property to the form generator component
- n/a check for console logs (warnings, errors)
- n/a API boundary values
- n/a different combinations of components - free style
- n/a change the API values during testing
- n/a missing API …

fix(platform): pass property from wizard to form

---

libs/core/src/lib/multi-input/multi-input.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6257
adding keyboard accessabitlity to the multi input component

fix(core): adding keyboard accessabitlity to the multi input component

---

libs/platform/src/lib/form/public_api.ts

Currently `npm publish` job is failing in CI due to an issue with duplicated exports
- [n/a] change the API values …

fix(platform): add export for multi-input config

---

.github/PULL_REQUEST_TEMPLATE.md

> **NOTE:** _If this PR fixes multiple issues, please use the full syntax(`closes #issue-number`) for each issue so that each issue gets automatically closed on PR merge; for example: `closes #1234, closes #5678`, and so on._
n/a
Current PR template has few issues:
- includes a reference to existing ticket 1234, which results in it being attached to each new pull request in zenhub
- quite often developers doesn't remove tooltips and placeholders from pull request template, which results in a lot of extra text on the PR
- …

chore(core,platform,docs,e2e): update pull request template

---

libs/core/src/lib/button/button.component.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html

Removed non-existing input property
Added check that event target exists.
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
-   [x] States - …

fix(platform): fix failing jest tests

---

libs/core/src/lib/menu/menu-mobile/menu-mobile.component.spec.ts

closes #7020
There's another failing unit test in core. Fixing it …

test(core): fix flaky unit test

---

e2e/wdio/core/tests/step-input.e2e-spec.ts
e2e/wdio/driver/wdio.ts
e2e/wdio/platform/tests/step-input.e2e-spec.ts

Closes none
Added additional test case for step-input e2e (core & platform)
- …

test(e2e): add additional test case for step-input

---

e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts

closes none
fix date time picker test case that works wrong on the 1st day of the month

test(e2e): fix dateTimePicker test

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss

Closes #7045.
Navigation column width fix.
-   [X] Content Density (Cozy/Compact/(Condensed))
-   [X] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [X] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [X] Mouse vs. Keyboard support
-   [X] Text Truncation
-   [X] check for console logs (warnings, errors)
-   [X] API boundary values
-   [X] different combinations of components - free style
-   [X] change the API values during testing
-   [X] missing API documentation or …

fix(platform): table navigation column width

---

e2e/wdio/core/pages/date-time-picker.po.ts
e2e/wdio/core/pages/toolbar.po.ts

closes none
fixes selectors for getting current day on date-time-picker and toolbar e2e

test(e2e): fix dateTimePicker and Toolbar test selectors

---

libs/core/src/lib/checkbox/checkbox/checkbox.component.html
libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
libs/platform/src/lib/form/checkbox/checkbox.component.html
libs/platform/src/lib/form/checkbox/checkbox.component.spec.ts
libs/platform/src/lib/form/input-group/input-group.component.spec.ts
libs/platform/src/lib/form/input/input.component.spec.ts
package-lock.json
package.json

Closes https://github.com/SAP/fundamental-ngx/issues/6965
there's no test coverage for form controls with control value accessors. this can lead to not standardised behavior or even bugs
Under this PR covering the following components:
- platform-input
- platform-input-group
- platform-checkbox …

test(platform): checkbox, input, input-group - cva unit tests

---

e2e/wdio/platform/fixtures/appData/table-contents.ts
e2e/wdio/platform/pages/table.po.ts
e2e/wdio/platform/tests/table.e2e-spec.ts
wdio-cron.conf.js
wdio.conf.js

Closes none
add e2e tests for platform table component
- [ n/a] …

test(e2e): add e2e test for table

---

apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-docs.component.html
libs/platform/src/lib/fundamental-ngx.module.ts
libs/platform/src/lib/search-field/public_api.ts
libs/platform/src/lib/search-field/search-field.component.ts
libs/platform/src/lib/search-field/search-field.module.ts

Closes https://github.com/sap/fundamental-ngx/issues/4253
made dynamic loading of the module instead of importing the module manually for search-input mobile module
- [ x Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
- [n/a] tests for …

fix(platform): search-input, add mobile dynamic loading

---

e2e/wdio/platform/fixtures/appData/approval-flow-contents.ts
e2e/wdio/platform/fixtures/testData/approval-flow.ts
e2e/wdio/platform/pages/approval-flow.po.ts
e2e/wdio/platform/tests/approval-flow.e2e-spec.ts

closes none
adds test cases for functionality added after initial test implementation (phase 3)

test(e2e): add additional test cases for approval flow

---

libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
libs/platform/src/lib/form/input-group/input-group.component.spec.ts

n/a
fixing few more flaky tests:
- https://github.com/SAP/fundamental-ngx/runs/4067378777?check_suite_focus=true#step:4:1168
- https://github.com/SAP/fundamental-ngx/runs/4084804169?check_suite_focus=true#step:4:1942
-   [n/a] API …

test(core,platform): fix flaky unit tests

---

e2e/wdio/core/pages/multi-input.po.ts
e2e/wdio/core/tests/multi-input.e2e-spec.ts

closes none
fixes checkbox selector for multi-input core e2e tests

test(e2e): fix multiInput selectors

---

apps/docs/src/app/platform/component-docs/platform-forms/multi-input/platform-multi-input-example/platform-multi-input-reactive-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/multi-input/platform-multi-input-example/platform-multi-input-reactive-example.component.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.ts

closes : https://github.com/SAP/fundamental-ngx/issues/6782
closes: https://github.com/SAP/fundamental-ngx/issues/6726
fixing the empty error message on required field and adding reset example to the form component.

fix(platform): fixing the empty error message and adding reset example

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/7070
closes https://github.com/SAP/fundamental-ngx/issues/7069
fixed an issue with selection column height
- …

fix(platform): table - selection row height issue

---

apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-state-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-state-example.component.ts
libs/platform/src/lib/form/step-input/number/number-step-input.component.html
libs/platform/src/lib/form/step-input/step-input.module.ts

closes https://github.com/sap/fundamental-ngx/issues/3766
Added state message for step-input component
3. …

fix(platform): step-input, add state message

---

libs/platform/src/lib/table/table.component.ts

Closes
When using array as the data source and changing something in the data changes didn't reflect in the table. Even if the reference to the array is changed. Here is the fix.
Apply this patch file to get a workspace to test the fix.
[fix(platform)__table_data_source_change.patch.txt](https://github.com/SAP/fundamental-ngx/files/7476412/fix.platform.__table_data_source_change.patch.txt)
https://user-images.githubusercontent.com/20265336/140376882-41ec2dbe-648c-491b-89bd-f7d5157f9430.mov
https://user-images.githubusercontent.com/20265336/140376915-f43b5885-1ac1-48a7-a414-f5e0b10009be.mov
-   [X] Content Density …

fix(platform): table data source change

---

libs/platform/src/lib/form/input-group/input-group.component.spec.ts

closes
-   [v] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [x] missing API documentation or it is not understandable
-   [x] …

fix(platform): fix flaky unit test

---

e2e/wdio/platform/pages/table.po.ts
e2e/wdio/platform/tests/table.e2e-spec.ts

closes none
update selectors for table(platform) e2e tests

test(e2e): update table selectors

---

libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.ts
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.html
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.ts
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.model.ts
libs/platform/src/lib/table/components/table-p13-dialog/grouping/grouping.component.ts
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.ts
libs/platform/src/lib/table/components/table-view-settings-dialog/filtering/filters.component.ts
libs/platform/src/lib/table/components/table-view-settings-dialog/grouping/grouping.component.ts
libs/platform/src/lib/table/components/table-view-settings-dialog/sorting/sorting.component.ts

closes #7063
FIxed the behavior of "reset" button in platform table …

fix(platform): table - resettable bugs

---

e2e/wdio/core/fixtures/appData/pagination-contents.ts
e2e/wdio/core/tests/form-message.e2e-spec.ts
e2e/wdio/core/tests/pagination.e2e-spec.ts
e2e/wdio/platform/pages/input.po.ts
e2e/wdio/platform/pages/multi-combobox.po.ts
e2e/wdio/platform/pages/multi-input.po.ts
e2e/wdio/platform/tests/input.e2e-spec.ts
e2e/wdio/platform/tests/multi-combobox.e2e-spec.ts
e2e/wdio/platform/tests/multi-input.e2e-spec.ts

closes none
Added additional test cases for multi-input(platform), form-message(core), multi-combobox(platform), input(platform)
-   [n/a] …

test(e2e): add additional test cases to components e2e

---

libs/platform/src/lib/search-field/search-field.component.spec.ts

closes https://github.com/sap/fundamental-ngx/issues/4207
fixed search-field unit tests
3. …

test(platform): search-field, fix unit tests

---

apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-basic-example.component.html
apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-basic-example.component.ts
libs/platform/src/lib/search-field/search-field.component.html
libs/platform/src/lib/search-field/search-field.component.spec.ts
libs/platform/src/lib/search-field/search-field.component.ts

closes https://github.com/sap/fundamental-ngx/issues/7051
Fixed error in the console when there is a SearchField without suggestions being passed.
-   [n/a] different combinations of components - free …

fix(platform): search-field, fix empty suggestions

---

package.json

n/a
There was a request to add `fast-deep-equal` as a dependency since it's being used in the app https://github.com/SAP/fundamental-ngx/pull/7071#discussion_r742881604
This package is being used internally by Angular, so in this PR it's just an explicit declaration of the dependency  …

chore: add fast-deep-equal as dependency to package.json

---

e2e/wdio/platform/pages/search.po.ts
e2e/wdio/platform/tests/search.e2e-spec.ts

Closes none
update e2e for search(platform)
- [n/a ] missing API …

test(e2e): update search e2e

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.service.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6546
FIxed an issue with missing an indication when the column is filtered through the column option. When we sort from the column we have the icon. Now there's the same behavior when it is filtered from there
4. …

fix(platform): table, fix column sorting issue (#6702)

---

e2e/wdio/platform/pages/dynamic-page-layout.po.ts

closes none
update test selector for dynamic page layout e2e

test(e2e): update dynamic page e2e selector

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

Closes #7067.
Semantic column height fix.
-   [X] Content Density (Cozy/Compact/(Condensed))
-   [X] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [X] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [X] Mouse vs. Keyboard support
-   [X] Text Truncation
-   [X] check for console logs (warnings, errors)
-   [X] API boundary values
-   [X] different combinations of components - free style
-   [X] change the API values during testing
-   [X] missing API documentation or …

fix(platform): table semantic column height

---

apps/docs/src/app/core/documentation/core-documentation.component.scss
apps/docs/src/app/fn/documentation/fn-documentation.component.scss
apps/docs/src/app/platform/documentation/platform-documentation.component.scss

closes https://github.com/SAP/fundamental-ngx/issues/7145
Fixed disappeared header for mobile …

fix(docs): fix styles for mobile

---

libs/platform/src/lib/dynamic-page/dynamic-page.component.ts

Closes https://github.tools.sap/dxp/search/issues/177
Fix for the `ExpressionChangedAfterItHasBeenCheckedError` error on the Dynamic Page component because of input passed with `async` pipe. See also https://github.com/angular/angular/issues/44112
For testing please apply this git patch file to get the workflow.
[fix(platform)__dynamic_page_title_inputs_async.patch.txt](https://github.com/SAP/fundamental-ngx/files/7499195/fix.platform.__dynamic_page_title_inputs_async.patch.txt)
-   [X] Content Density (Cozy/Compact/(Condensed))
-   [X] States - hover/disabled/focused/active/on click/selected/selected hover/press …

fix(platform): dynamic page title inputs async

---

libs/platform/src/lib/form/form-group/form-field/form-field.component.html

Part of https://github.tools.sap/dxp/core/issues/402
Accordingly to the Fiori 3 design guidelines, XL should have `4:8:0` label-field ratio: https://experience.sap.com/internal/fiori-design-web/form/#labelfield-ratio
**Testing**: Affected components are all that using `fdp-form-field`.
-   [X] Content Density (Cozy/Compact/(Condensed))
-   [X] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [X] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [X] Mouse vs. Keyboard support
-   [X] Text Truncation
-   [X] check …

fix(platform): form field layout

---

apps/docs/src/app/core/api-files.ts

closes #7169 
Changed file name to correct one
-   n/a visual misalignments/updates
-   n/a check Light/Dark/HCB/HCW themes
-   n/a RTL/LTR - proper rendering and labeling
-   n/a responsiveness(resize)
-   n/a Content Density (Cozy/Compact/(Condensed))
-   n/a States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   n/a Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   n/a Mouse vs. Keyboard support
-   n/a Text Truncation
-   n/a different combinations of components - free style
-   n/a change the API values during testing …

fix(docs): correct file name

---

libs/core/src/lib/toolbar/toolbar.component.html
libs/core/src/lib/toolbar/toolbar.component.scss
libs/core/src/lib/toolbar/toolbar.component.ts

closes : https://github.com/SAP/fundamental-ngx/issues/2758
fixing the empty error message on required field and adding reset example to the form component.

fix(core): fixing the flickering issue for the toolbar component

---

e2e/wdio/core/fixtures/appData/button-contents.ts
e2e/wdio/core/fixtures/appData/inline-help-contents.ts
e2e/wdio/core/fixtures/appData/slider-contents.ts
e2e/wdio/core/pages/button.po.ts
e2e/wdio/core/pages/inline-help.po.ts
e2e/wdio/core/pages/object-number.po.ts
e2e/wdio/core/pages/slider.po.ts
e2e/wdio/core/tests/button.e2e-spec.ts
e2e/wdio/core/tests/carousel.e2e-spec.ts
e2e/wdio/core/tests/inline-help.e2e-spec.ts
e2e/wdio/core/tests/notification.e2e-spec.ts
e2e/wdio/core/tests/object-number.e2e-spec.ts
e2e/wdio/core/tests/object-status.e2e-spec.ts
e2e/wdio/core/tests/slider.e2e-spec.ts
e2e/wdio/platform/fixtures/appData/feed-input-page-contents.ts
e2e/wdio/platform/fixtures/appData/value-help-dialog-contents.ts
e2e/wdio/platform/pages/combobox.po.ts
e2e/wdio/platform/pages/upload-collection.po.ts
e2e/wdio/platform/pages/value-help-dialog.po.ts
e2e/wdio/platform/tests/combobox.e2e-spec.ts
e2e/wdio/platform/tests/feed-input.e2e-spec.ts
e2e/wdio/platform/tests/icon-tab-bar.e2e-spec.ts
e2e/wdio/platform/tests/list.e2e-spec.ts
e2e/wdio/platform/tests/slider.e2e-spec.ts
e2e/wdio/platform/tests/thumbnail.e2e-spec.ts
e2e/wdio/platform/tests/upload-collection.e2e-spec.ts
e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts
wdio-cron.conf.js
wdio.conf.js

closes none
upadates and unskips tests per resolved bugs/issues

test(e2e): unskip tests per resolved bugs

---

e2e/wdio/platform/tests/slider.e2e-spec.ts
e2e/wdio/platform/tests/thumbnail.e2e-spec.ts

closes none
updates 2 test cases to run correctly on localhost builds

test(e2e): update 2 tests for localhost builds

---

e2e/wdio/platform/pages/table.po.ts
e2e/wdio/platform/tests/table.e2e-spec.ts

closes none
upadate and unskip tests for table(platform) per fixed bugs/issues

test(e2e): unskip tests per fixed issues

---

e2e/wdio/core/pages/alert.po.ts
e2e/wdio/core/pages/inline-help.po.ts
e2e/wdio/core/pages/table.po.ts
e2e/wdio/core/tests/alert.e2e-spec.ts
e2e/wdio/core/tests/inline-help.e2e-spec.ts
e2e/wdio/core/tests/table.e2e-spec.ts
e2e/wdio/platform/pages/combobox.po.ts
e2e/wdio/platform/pages/date-time-picker.po.ts
e2e/wdio/platform/tests/combobox.e2e-spec.ts
e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts

closes none
Added additional test cases for combobox(platform) and table(core), inline help(core), date-time picker(platform), alert(core), table(core)
-   [n/a] different combinations of components - …

test(e2e): add additional test cases for components per reported bugs

---

libs/core/src/lib/select/select.component.html
libs/core/src/lib/select/select.component.scss
libs/platform/src/lib/form/select/commons/base-select.ts
libs/platform/src/lib/form/select/select/select.component.html
libs/platform/src/lib/form/select/select/select.component.ts

closes https://github.com/sap/fundamental-ngx/issues/4866
Fixed wrapping and trucation styles for mobile
-   [n/a] change the API values during …

fix(core,platform): select, fix wrapping and trucation styles

---

libs/platform/src/lib/form/radio-group/radio-group.component.html
libs/platform/src/lib/form/radio-group/radio-group.component.spec.ts
libs/platform/src/lib/form/radio-group/radio-group.component.ts
libs/platform/src/lib/form/radio-group/radio/radio.component.html
libs/platform/src/lib/form/radio-group/radio/radio.component.spec.ts
libs/platform/src/lib/form/radio-group/radio/radio.component.ts

closes https://github.com/sap/fundamental-ngx/issues/6784
Fixed reflect Radio Group value when set through reactive form
-   [n/a] change the …

fix(platform): radio-group, fix reflect value when set through reactive form

---

libs/platform/src/lib/table/table-column-resize.service.spec.ts
libs/platform/src/lib/table/table-column-resize.service.ts
libs/platform/src/lib/table/table.component.scss

closes https://github.com/SAP/fundamental-ngx/issues/7014
Fixed extra width for table component. Was replicatable in firefox on windows
-   [n/a] change the API …

fix(platform): table - fix horizontal scroll in firefox

---

e2e/wdio/core/tests/dialog.e2e-spec.ts
e2e/wdio/core/tests/rating-indicator.e2e-spec.ts
e2e/wdio/platform/pages/approval-flow.po.ts
e2e/wdio/platform/tests/approval-flow.e2e-spec.ts
e2e/wdio/platform/tests/search.e2e-spec.ts

closes none
update e2e per cron job report

test(e2e): update e2e for saucelabs

---

e2e/wdio/core/pages/action-bar.po.ts
e2e/wdio/core/tests/action-bar.e2e-spec.ts

closes none
Added missed test cases for action-bar(core) …

test(e2e): add e2e tests for action-bar

---

e2e/wdio/core/fixtures/appData/busy-indicator-contents.ts
e2e/wdio/core/pages/alert.po.ts
e2e/wdio/core/pages/busy-indicator.po.ts
e2e/wdio/core/tests/alert.e2e-spec.ts
e2e/wdio/core/tests/busy-indicator.e2e-spec.ts
e2e/wdio/platform/pages/menu.po.ts
e2e/wdio/platform/tests/menu.e2e-spec.ts

closes none
Added additional test cases for alert(core) and menu (platform) …

test(e2e): add additional test cases for menu, alert and busy indicator

---

e2e/wdio/core/fixtures/appData/input-page-contents.ts
e2e/wdio/core/pages/avatar-group.po.ts
e2e/wdio/core/pages/button.po.ts
e2e/wdio/core/pages/input.po.ts
e2e/wdio/core/tests/avatar-group.e2e-spec.ts
e2e/wdio/core/tests/button.e2e-spec.ts
e2e/wdio/core/tests/input.e2e-spec.ts

closes none
add additional test cases for button, avatar-group and input (core)

test(e2e): add additional test cases for button, avatar group, input

---

libs/core/src/lib/multi-input/multi-input.component.html

closes #6718
disable field clear at suggestion select …

fix(core): disable field clear at suggestion select

---

apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-custom-values-example.component.ts
apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts
libs/core/src/lib/checkbox/checkbox/checkbox.component.scss

closes https://github.com/SAP/fundamental-ngx/issues/5791
fix broken VoiceOver outline in Checkbox component 
-   [n\a] API …

fix(core): checkbox broken VoiceOver outline

---

apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-collapsible-example.component.html
libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.spec.ts

closes: https://github.com/SAP/fundamental-ngx/issues/5893
This pr fixes combobox clear button appearance in the shellbar. …

fix(core): fix combobox in shellbar

---

libs/core/src/lib/dialog/dialog.component.scss
libs/core/src/lib/dialog/dialog.component.ts

Closes #5286
added centering for the dialog without backdrop
this is a copy of https://github.com/SAP/fundamental-ngx/pull/5626 without changes to dialog styles
-   [n/a] different combinations of components - free …

fix(core): static dialog nobackdrop position fix

---

e2e/wdio/core/tests/toolbar.e2e-spec.ts
e2e/wdio/platform/pages/table.po.ts
e2e/wdio/platform/tests/table.e2e-spec.ts
wdio-cron.conf.js
wdio.conf.js

closes none
- skip wizard generator e2e until rework can be done
- update table selectors for saucelabs runs
- skip toolbar visual regression case
- increase saucelabs max test suite run time for table e2e

test(e2e): fix e2e for saucelabs

---

apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-examples.component.ts
apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-examples.component.ts
apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-examples.component.ts
apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group.module.ts
libs/core/src/lib/message-toast/message-toast.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/6165
Fixed radio-group a11y issues
1. done
2. can not reproduce
3. …

fix(platform): radio-group, fix a11y issues

---

e2e/wdio/platform/tests/dynamic-page-layout.e2e-spec.ts
libs/core/src/lib/resizable-card-layout/resizable-card-layout/resizable-card-item/resizable-card-item.component.ts
libs/core/src/lib/resizable-card-layout/resizable-card-layout/resizable-card-layout.component.ts

closes https://github.com/sap/fundamental-ngx/issues/6823
Fixed resizable card layout behavior on RTL mode
-   [n/a] change the API values during …

fix(core): resizable-card-layout, fix resizable behavior on RTL mode

---

e2e/wdio/core/fixtures/appData/message-box.ts
e2e/wdio/core/pages/dialog.po.ts
e2e/wdio/core/pages/input-group.po.ts
e2e/wdio/core/pages/multi-input.po.ts
e2e/wdio/core/pages/select.po.ts
e2e/wdio/core/tests/dialog.e2e-spec.ts
e2e/wdio/core/tests/input-group.e2e-spec.ts
e2e/wdio/core/tests/message-box.e2e-spec.ts
e2e/wdio/core/tests/multi-input.e2e-spec.ts
e2e/wdio/core/tests/select.e2e-spec.ts
e2e/wdio/platform/fixtures/testData/wizard-generator.ts
e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
wdio-cron.conf.js
wdio.conf.js

closes none
added additional case for message-box and refactored test structure, added additional case for dialog and input group, added additional test case for select and unskipped FF, fixed e2e for wizard-generator on local and saucelabs

test(e2e): add additional cases & refactoring

---

apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-emphasized-example.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-example.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-emphasized-example.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-icon-example.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-inverted-example.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-standard-example.component.html
apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-truncated-example.component.html
e2e/wdio/platform/fixtures/appData/link-page-contents.ts
libs/platform/src/lib/link/link.component.html

closes https://github.com/sap/fundamental-ngx/issues/6148
Fixed Platform Link a11y issues
3. …

fix(platform): link, fix a11y issues

---

apps/docs/src/app/core/component-docs/form-message/examples/form-message-example.component.html
apps/docs/src/app/core/component-docs/form-message/examples/form-message-example.component.ts
apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.html
apps/docs/src/app/core/component-docs/form-message/form-message-docs.module.ts
libs/core/src/lib/popover/popover-service/popover.service.ts

closes https://github.com/SAP/fundamental-ngx/issues/5203
- Prevented unexpected popover toggling to avoid inverted behavior in some cases 
- Added Multi Input example in Form Message component examples 
-   [x] different …

fix(core): form message inverted popover event triggers

---

e2e/wdio/core/fixtures/appData/info-label-contents.ts
e2e/wdio/core/pages/grid-list.po.ts
e2e/wdio/core/pages/info-label.po.ts
e2e/wdio/core/tests/grid-list.e2e-spec.ts
e2e/wdio/core/tests/info-label.e2e-spec.ts
e2e/wdio/platform/tests/icon-tab-bar.e2e-spec.ts

closes none
add e2e for info-label and additional test cases for grid list, unskip test for icon-tab-bar per fixed bug
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

test(e2e): add e2e for info-label, unskip test for icon-tab-bar and additional test cases for grid list

---

libs/platform/src/lib/form/select/commons/base-select.ts
libs/platform/src/lib/form/select/select/select.component.ts

closes #7266 
Adjusted content density configuration for the select component.
To test, please open form generator documentation page and change content density configuration, and verify that visuals are changed for select component inside any of the examples.
-   [x] check for console logs …

fix(platform): adjust select content density configuration

---

apps/docs/src/app/core/component-docs/fixed-card-layout/examples/custom-width/fixed-card-layout-custom-width-example.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/custom-width/fixed-card-layout-custom-width-example.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

closes #7250 
Added input property to apply custom min-width of the fixed card layout card. …

feat(core): custom min width for fixed card layout

---

libs/core/src/lib/button/button.component.ts
libs/core/src/lib/menu/directives/menu-trigger.directive.spec.ts
libs/core/src/lib/menu/directives/menu-trigger.directive.ts
libs/core/src/lib/menu/menu.component.html
libs/core/src/lib/menu/menu.component.ts
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/core/src/lib/split-button/split-button.component.html
libs/core/src/lib/split-button/split-button.component.spec.ts
libs/core/src/lib/split-button/split-button.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/6185
This PR fixes core split-button accessibility …

fix(core): fix split-button accessibility

---

e2e/wdio/core/fixtures/testData/date-picker-tags.ts
e2e/wdio/core/pages/date-time-picker.po.ts
e2e/wdio/core/pages/toolbar.po.ts
e2e/wdio/core/tests/date-picker.e2e-spec.ts
e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
e2e/wdio/core/tests/toolbar.e2e-spec.ts

closes none
fixed failed iterations in date picker, date-time picker and toolbar tests

test(e2e): fix failed tests on main branch

---

apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.html

closes https://github.com/sap/fundamental-ngx/issues/6304
Fixed datetime-picker view for ar language
-   [n/a] change the API values during …

docs(core): datetime-picker, fix view for ar language

---

libs/core/src/lib/progress-indicator/progress-indicator.component.spec.ts

Fix eslint error
-   [n/a] missing API documentation …

test(core): fix eslint error

---

libs/platform/src/lib/table/table.component.ts

Table change detection to react to new data passed to the component.

fix(platform): table cd

---

e2e/wdio/core/pages/dialog.po.ts
e2e/wdio/core/pages/toolbar.po.ts
e2e/wdio/core/tests/dialog.e2e-spec.ts
e2e/wdio/core/tests/notification.e2e-spec.ts
e2e/wdio/core/tests/splitter.e2e-spec.ts
e2e/wdio/core/tests/toolbar.e2e-spec.ts
e2e/wdio/platform/pages/value-help-dialog.po.ts
e2e/wdio/platform/tests/form-container.e2e-spec.ts
e2e/wdio/platform/tests/upload-collection.e2e-spec.ts
wdio-cron.conf.js

closes none
fix and stabilize a couple test suites
skip flaky splitter test suite
<s>change daily job to use localhost builds instead of firebase deployment</s> - done in another fix

test(e2e): fix e2e for daily build

---

e2e/wdio/core/pages/calendar.po.ts
e2e/wdio/core/pages/link.po.ts
e2e/wdio/core/pages/standard-list.po.ts
e2e/wdio/core/tests/calendar.e2e-spec.ts
e2e/wdio/core/tests/dynamic-page.e2e-spec.ts
e2e/wdio/core/tests/link.e2e-spec.ts
e2e/wdio/core/tests/list-byline.e2e-spec.ts
e2e/wdio/core/tests/notification.e2e-spec.ts
e2e/wdio/core/tests/standard-list.e2e-spec.ts
e2e/wdio/platform/pages/select.po.ts
e2e/wdio/platform/pages/time-picker.po.ts
e2e/wdio/platform/tests/object-attribute.e2e-spec.ts
e2e/wdio/platform/tests/select.e2e-spec.ts
e2e/wdio/platform/tests/split-menu-button.e2e-spec.ts
e2e/wdio/platform/tests/time-picker.e2e-spec.ts

closes none
add additional test cases for link & improve check for list-byline, added case for select, standard list, time picker, objecte attribute, redone few test cases for calendar

test(e2e): add additional test cases for components

---

e2e/wdio/core/pages/date-time-picker.po.ts
e2e/wdio/core/pages/time.po.ts
e2e/wdio/core/pages/toolbar.po.ts
e2e/wdio/core/tests/date-time-picker.e2e-spec.ts
e2e/wdio/core/tests/time.e2e-spec.ts
e2e/wdio/core/tests/toolbar.e2e-spec.ts
e2e/wdio/platform/pages/date-time-picker.po.ts
e2e/wdio/platform/pages/time-picker.po.ts
e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts
e2e/wdio/platform/tests/time-picker.e2e-spec.ts
libs/core/src/lib/time-picker/time-picker.component.ts
libs/core/src/lib/time/i18n/time-i18n.ts
libs/core/src/lib/time/time-column/time-column-config.ts
libs/core/src/lib/time/time-column/time-column.component.html
libs/core/src/lib/time/time-column/time-column.component.scss
libs/core/src/lib/time/time-column/time-column.component.ts
libs/core/src/lib/time/time.component.html
libs/core/src/lib/time/time.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/6187
This PR fixes some time component accessibility issues
3. …

fix(core): time component accessibility

---

libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html

fix(platform): form generator typo

---

apps/docs/src/app/core/component-docs/combobox/examples/combobox-mobile/combobox-mobile-example.component.ts
e2e/wdio/core/pages/combobox.po.ts
e2e/wdio/platform/pages/table.po.ts
e2e/wdio/platform/tests/wizard-generator.e2e-spec.ts
libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.html
libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.ts
libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.scss
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/input-group/input-group.component.ts
libs/core/src/lib/list/directives/list-group-header.directive.spec.ts
libs/core/src/lib/list/directives/list-group-header.directive.ts
libs/core/src/lib/utils/directives/auto-complete/auto-complete.directive.ts
libs/platform/src/lib/form/combobox/combobox/combobox.component.html

Closes #5801
This PR contains fixes for platform combobox component. 
Quick overview of changes according to original doc with issues from the ticket:
Issue 1: cannot reproduce
Issue 2: done
Issue 3: done
Issue 4: done
Issue 5: cannot reproduce
Issue 6: not done (the whole placeholder is pronounced no matter it’s truncated or not)
Issue 7: done
Issue 8: not done (not an issue, inputs with state information/warning/error/success in high contrast themes will have dashed borders according to fundamental-styles)
Issue 9: not done, there's a PR for this https://github.com/SAP/fundamental-ngx/pull/6941
Issue 10: done
Issue 11: cannot reproduce
Issue 12: not done (appears to be not an issue, there's some additional information, but it's not much and it's relevant
Issue 13: cannot reproduce
Issue …

fix(core): combobox a11y issues

---

apps/docs/src/app/core/component-docs/calendar/calendar-header/calendar-header.component.html
apps/docs/src/app/core/component-docs/date-picker/date-picker-header/date-picker-header.component.html
apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html
apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-header/datetime-picker-header.component.html
apps/docs/src/app/core/component-docs/time-picker/time-picker-header/time-picker-header.component.html
apps/docs/src/app/core/component-docs/time/time-header/time-header.component.html
apps/docs/src/app/documentation/common-components/datetime-important/datetime-important.component.html
apps/docs/src/app/documentation/common-components/datetime-important/datetime-important.component.ts
apps/docs/src/app/documentation/shared-documentation-page.module.ts
apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-header/platform-date-picker-header.component.html
apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-header/platform-datetime-picker-header.component.html

closes #4880 
Because of limited support of i18n features based on native javascript functionality we have problems with these features.
Moment date-time adapter was implemented to solve these issues.
This PR contains changes related to documentation, shows important information related to the new feature, and explains the problems with the default fundamental adapter.
Reopened this [PR](https://github.com/SAP/fundamental-ngx/pull/6351)
-   [n/a] …

docs(core,platform): add important notest related to i18n, formats, validation to date time pickers components documentation

---

libs/platform/src/lib/form/text-area/text-area.component.ts

Textarea component tries to work with the Clipboard API what is not needed and sends a notification to the user with requesting permissions. Error is thrown if permissions are not granted.
Here is the fix.

fix(platform): textarea clipboard api

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.module.ts
libs/platform/src/lib/table/table.ts

DXP/Backlog #446.
Themeable scrollbar applied for the platform table component.

feat(platform): themeable scrollbar for table

---

apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-scrolling-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-scrolling-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu.module.ts
e2e/wdio/platform/pages/menu.po.ts
libs/platform/src/lib/menu/menu-trigger.directive.ts

closes https://github.com/sap/fundamental-ngx/issues/6150
Fixed platform menu a11y issues
3. …

fix(platform): menu, fix a11y issues

---

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page.module.ts
e2e/wdio/platform/pages/dynamic-page-layout.po.ts
e2e/wdio/platform/tests/dynamic-page-layout.e2e-spec.ts
libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.html
libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.ts
libs/platform/src/lib/dynamic-page/dynamic-page.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.component.spec.ts
libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
libs/platform/src/lib/dynamic-page/dynamic-page.module.ts

closes https://github.com/SAP/fundamental-ngx/issues/7168
- Refactored Platform Dynamic Page built on top of Core implementation.
-   [n/a] change the API values …

feat(platform): refactor dynamic page on top of core

---

apps/docs/src/app/core/component-docs/calendar/examples/calendar-special-day-example/calendar-special-day-example.component.html
e2e/wdio/core/tests/calendar.e2e-spec.ts

calendar doc example update - precise the title of one field

docs(core): calendar doc example update

---

libs/platform/src/lib/form/step-input/number/number-step-input.component.spec.ts
libs/platform/src/lib/form/text-area/text-area.component.spec.ts
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-base.class.ts

n/a
fixing failing unit tests on CI
-   [n/a] missing …

test(platform): skip/fix failing unit tests

---

apps/docs/tsconfig.app.json
apps/docs/tsconfig.netlify.json
apps/docs/tsconfig.spec.json

closes #7409 
Corrected tsconfig paths

fix(docs): provide correct tsconfig paths

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
libs/core/src/lib/radio/radio-button/radio-button.component.ts
libs/platform/src/lib/form/checkbox-group/checkbox-group.component.spec.ts
libs/platform/src/lib/form/checkbox-group/checkbox-group.component.ts
libs/platform/src/lib/form/radio-group/radio-group.component.html
libs/platform/src/lib/form/radio-group/radio-group.component.spec.ts
libs/platform/src/lib/form/radio-group/radio-group.component.ts
libs/platform/src/lib/form/radio-group/radio/radio.component.html
libs/platform/src/lib/form/radio-group/radio/radio.component.spec.ts
libs/platform/src/lib/form/radio-group/radio/radio.component.ts
libs/platform/src/lib/form/test.ts
libs/platform/src/lib/shared/form/inline-layout-collection-base.input.ts

related to https://github.com/SAP/fundamental-ngx/issues/6866
Added `ngx-cva-test-suite` for `platform-checkbox-group` and `platform-radio-group` components. It was required to make some minor changes in order to fulfill requirements of standard behavior for CVA. Public API of these components were not changed.
2. API and …

fix(platform): adjust control-value-accessor behavior for checkbox group and radio group

---

libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.html
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.spec.ts
libs/platform/src/lib/form/step-input/number/number-step-input.component.spec.ts
libs/platform/src/lib/form/switch/switch/switch.component.spec.ts
libs/platform/src/lib/form/text-area/text-area.component.spec.ts
libs/platform/src/lib/form/time-picker/time-picker.component.spec.ts

related to https://github.com/SAP/fundamental-ngx/issues/6866
there's no test coverage for form controls with control value accessors. this can lead to not standardised behavior or even bugs
Under this PR covering the following components:
- platform timepicker
- platform textarea
- platform switch
- platform step input 
- core & platform datetime picker
-   [x] Mouse vs. Keyboard …

test(platform,core): cva unit tests

---

libs/platform/schematics/ng-add/index.ts

Closes #7383
Fix for the platform schematics due to not ordered run of tasks.
`npm run build-pack-library`
`ng add ../fundamental-ngx/dist/libs/platform`

fix(platform): schematics

---

apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-navigatable-row-indicator-example.component.html
libs/platform/src/lib/table/directives/table-cell-resizable.directive.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts

DXP
Disallow navigation column resize.

fix(platform): table disallow nav column resize

---

apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-example.component.ts
e2e/wdio/core/pages/date-picker.po.ts
e2e/wdio/core/tests/date-picker.e2e-spec.ts
libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
libs/core/src/lib/date-picker/date-picker.component.html
libs/core/src/lib/date-picker/date-picker.component.spec.ts
libs/core/src/lib/date-picker/date-picker.component.ts
libs/platform/src/lib/form/date-picker/date-picker.component.spec.ts

closes https://github.com/sap/fundamental-ngx/issues/6214
This PR provides some accessibility fixes for core date-time picker component
-   [na] different combinations of components - free style
-   [x] change the API …

fix(core): date picker accessibility

---

apps/docs/src/app/core/component-docs/menu/examples/menu-with-submenu-example.component.html
libs/core/src/lib/menu/menu-item/menu-item.component.spec.ts
libs/core/src/lib/menu/menu-item/menu-item.component.ts
libs/core/src/lib/menu/menu.component.ts
libs/core/src/lib/menu/services/menu.service.ts

closes https://github.com/SAP/fundamental-ngx/issues/7392
Close sub-menu when the pointer moves on menu item without sub-menu …

fix(core): close sub-menu

---

apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-visible-summary-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-visible-summary-example.component.ts
apps/docs/src/app/core/component-docs/wizard/wizard-docs.module.ts
e2e/wdio/core/tests/date-picker.e2e-spec.ts
libs/core/src/lib/wizard/wizard-navigation/wizard-navigation.component.ts
libs/core/src/lib/wizard/wizard-step/wizard-step.component.html
libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts
libs/core/src/lib/wizard/wizard.component.ts
libs/core/src/lib/wizard/wizard.service.spec.ts
libs/core/src/lib/wizard/wizard.service.ts

fixing the accessibility issue for the wizard core component
closes: https://github.com/SAP/fundamental-ngx/issues/6177
fixing the empty error message on required field and adding reset example to the form component.

fix(core): adding arialabel and roles to handle a11y for wizard component

---

apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-example.component.html
apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-form-example.component.html
libs/core/src/lib/shared/public_api.ts
libs/core/src/lib/shared/services/value-state-message.service.ts
libs/core/src/lib/time-picker/time-picker.component.html
libs/core/src/lib/time-picker/time-picker.component.ts

closes https://github.com/sap/fundamental-ngx/issues/6182
This PR fixes some accessibility issues with in core time-picker …

fix(core): core time-picker accessibility

---

apps/docs/src/app/platform/component-docs/platform-action-list-item/platform-action-list-item-examples/platform-action-list-item-border-less-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-list-item/platform-action-list-item-examples/platform-action-list-item-example.component.html

closes https://github.com/sap/fundamental-ngx/issues/6072
Fixed action-list-item a11y issues …

docs(platform): action-list-item, fix a11y issues

---

apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-async-example/multi-input-async-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-compact-example/multi-input-compact-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.ts
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.ts
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-filter-example/multi-input-filter-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-includes-example/multi-input-includes-example.component.html
e2e/wdio/core/tests/multi-input.e2e-spec.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/multi-input/multi-input.module.ts

closes https://github.com/SAP/fundamental-ngx/issues/7408
core-multi-select can work only with strings or object references. When the object is cloned, it can no longer be identified as selected. This is because selected state is determined by plain equality (===) and there's no way to pass comparer function. …

fix(core): multi-select doesn't work with objects

---

libs/platform/src/lib/value-help-dialog/components/define-tab/define-tab.component.html
libs/platform/src/lib/value-help-dialog/components/define-tab/define-tab.component.scss
libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.scss
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.scss

addressing comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-997686984
- controls are not verticaly centered:
- background and invisible label styles are not always applied
https://user-images.githubusercontent.com/33101123/147482085-891361d7-48a8-407f-86dc-4b5c5f5ee68b.mp4
-   [x] Mouse …

fix(platform): vhd controls styles

---

apps/docs/src/app/core/component-docs/dialog/examples/dialog-inner-popover/dialog-inner-popover.component.ts

issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-992761193
Fix dialog `Dialog with inner popovers` example
-   [n/a] check for console logs (warnings, …

docs(core): dialog, fix example

---

apps/docs/src/app/core/component-docs/feed-list-item/examples/fli-action/fli-action-example.component.html
e2e/wdio/core/pages/feed-list-item.po.ts
e2e/wdio/core/tests/feed-list-item.e2e-spec.ts

closes: https://github.com/SAP/fundamental-ngx/issues/7227
Updated docs to use action sheets instead of the classic menu. …

docs(core): add icons to feed list item actions

---

libs/core/src/lib/step-input/step-input.component.spec.ts
libs/core/src/lib/step-input/step-input.component.ts

issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-994104617
when clicking the plus or minus buttons to change the value of the input, and then pressing the space bar makes it look like the button is being pressed but the number does not change
-   [x] …

fix(core): step-input - keyboard interaction

---

libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.scss
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.ts

issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-994104617
- Platform upload collection - click checks to edit a filename then drag the column border to make the column wider - extension still wraps incorrectly. Also in my opinion let's just make the default column width settings wider in these examples to get a better look and feel 
- Platform upload collection - deleting a file often (not always) causes the window to scroll upwards
-   [n/a] Content Density …

fix(platform): upload collection fixes

---

e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts

closes none
added additional test case for value help dialog by created issue

test(e2e): add additional test case for value help dialog

---

libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
libs/core/src/lib/rating-indicator/components/rating-indicator.component.scss
package-lock.json
package.json

issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-992986339
closes https://github.com/SAP/fundamental-ngx/issues/7268
Updated Rating Indicator styles
- …

fix(core): rating-indicator, update styles

---

libs/platform/src/lib/form/form-generator/form-generator.service.ts

closes #7429 closes #7209
Added null coalescing operator when formatting password field.
To check, try to complete any wizard generator example and keep password field empty (inner value should be null or undefined). On summary page there should be a dash for password field value.
-   n/a visual misalignments/updates
-   n/a check Light/Dark/HCB/HCW themes
-   n/a RTL/LTR - proper rendering and labeling
-   n/a responsiveness(resize)
-   n/a Content Density (Cozy/Compact/(Condensed))
-   n/a States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   n/a Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   n/a Mouse vs. Keyboard support
-   n/a Text Truncation
-   [x] check for …

fix(platform): fix empty password field error

---

apps/docs/src/app/core/component-docs/carousel/carousel-docs.component.ts
apps/docs/src/app/core/component-docs/carousel/examples/carousel-dynamic-items-example.component.html
apps/docs/src/app/core/component-docs/carousel/examples/carousel-dynamic-items-example.component.ts
apps/docs/src/app/core/component-docs/carousel/examples/carousel-example.component.scss
apps/docs/src/app/core/component-docs/carousel/examples/carousel-multiple-active-item-example.component.html
apps/docs/src/app/core/component-docs/carousel/examples/carousel-multiple-active-item-example.component.ts
libs/core/src/lib/carousel/carousel-item.directive.ts
libs/core/src/lib/carousel/carousel-item/carousel-item.component.scss
libs/core/src/lib/carousel/carousel-item/carousel-item.component.ts
libs/core/src/lib/carousel/carousel.component.html
libs/core/src/lib/carousel/carousel.component.ts
libs/core/src/lib/carousel/carousel.directive.ts
libs/core/src/lib/carousel/carousel.service.ts

closes https://github.com/SAP/fundamental-ngx/issues/5969
fixed carousel issues …

fix(core): carousel, fix console error, arrows

---

apps/docs/src/app/platform/component-docs/platform-forms/multi-input/platform-multi-input-example/platform-multi-input-mobile-example.component.ts
e2e/wdio/platform/pages/multi-input.po.ts
e2e/wdio/platform/tests/multi-input.e2e-spec.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input-mobile/multi-input-mobile.component.html
libs/platform/src/lib/form/multi-input/multi-input-mobile/multi-input-mobile.component.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.spec.ts
libs/platform/src/lib/form/multi-input/multi-input.component.ts
libs/platform/src/lib/form/multi-input/multi-input.interface.ts
libs/platform/src/lib/list/list.component.ts

part of defect hunting sprint 77 https://github.com/SAP/fundamental-ngx/issues/7362
issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-993928134
- Platform multi-input mobile mode - button on right of input resets the search list but does not reset input. Also, "approve" button in dialog footer needs an uppercase "A". Lastly the top right X button does not close the dialog
- Platform multi-input decline list type - list options lose their X on subsequent opens of the popover
- when "close" is clicked, input values will be reset
-  null invalidity should style the input red on blur.
- added CVA unit tests
-   [n/a] RTL/LTR - proper rendering and …

fix(platform): multi-input issues

---

libs/core/src/lib/slider/slider.component.html
libs/core/src/lib/slider/slider.component.ts

part of defect hunting sprint 77 https://github.com/SAP/fundamental-ngx/issues/7362
issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-993928134
Platform slider with tooltip - using arrow keys to change value of the slider has the tooltip disappear every other keypress
2. API …

fix(core/platform): slider - show tooltip properly

---

libs/core/src/lib/carousel/carousel.component.html
libs/core/src/lib/carousel/carousel.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/5969
Fixed carousel indicator container …

fix(core): carousel, fix page indicator container

---

NEW_COMPONENT.md
tools/generators/sap-component/files/docs/__fileName__-docs.component.ts.template

Fixes an issue with the new component documentation and the code generating tool

docs(core): adjust documentation generation tool for source files

---

libs/platform/src/lib/search-field/search-field.component.ts

part of defect hunting sprint 77 https://github.com/SAP/fundamental-ngx/issues/7362
issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-993928134
Platform search field - both button and input can receive focus simultaneously. Happens when the user focuses the X button via tab and deletes via enter, then presses tab again
-   [x] Mouse vs. …

fix(platform): search-field - fix focus

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.html
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts
libs/platform/src/lib/form/form-group/form-field/form-field.component.ts
libs/platform/src/lib/shared/form/form-field.ts

part of defect hunting sprint 77 https://github.com/SAP/fundamental-ngx/issues/7362
issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-993861090
Fixing the following:
- Platform, datetime picker forms example - inputs should receive red outline on form submit when the fields are not valid
- Platform datetime w/ template forms - valid date displays as invalid
- Platform datetime pickers with required attribute, starting with a null value - input renders as invalid when the user focuses the input.  Should happen on blur
-   [n/a] Content Density …

fix(core/platform): datetime-picker "invalid" state visibiity

---

.eslintrc.json
angular.json
apps/docs/src/app/core/component-docs/splitter/splitter-docs.module.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.ts
apps/docs/src/app/core/component-docs/wizard/examples/wizard-visible-summary-example.component.ts
apps/docs/src/app/platform/component-docs/platform-icon-tab-bar/platform-icon-tab-bar-docs.module.ts
libs/core/src/lib/wizard/public_api.ts
libs/core/src/lib/wizard/wizard.service.ts
libs/platform/src/lib/approval-flow/tests/providers.ts

n/a
Enabling "@nrwl/nx/enforce-module-boundaries" rule to achieve the following:
- prevent cross-library imports using relative paths
- prevent ability to import libraries from platform/experimental to core and between them (platform and experimental still can depend on core)
- …

chore: enable "enforce-module-boundaries" eslint rule

---

apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.component.ts
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.module.ts
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-facets-example/dynamic-page-facets-example.component.ts
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
libs/core/src/lib/dynamic-page/dynamic-page.component.scss
libs/core/src/lib/facets/facet/facet.component.scss

closes https://github.com/SAP/fundamental-ngx/issues/4991
- Added Facets example to Core Dynamic Page …

docs(core): dynamic page add facets example

---

apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-basic-example.component.ts
apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-collapsible-example.component.ts

closes #7415
The avatar uses the full name to generate the initials image of the avatar. In the example docs of the Shellbar component, the initials were used. This has been fixed to use the full name instead.
- …

docs(core): ShellbarUser to use fullname instead of initial

---

libs/core/src/lib/date-picker/date-picker.component.spec.ts
libs/core/src/lib/date-picker/date-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
libs/core/src/lib/time-picker/time-picker.component.spec.ts
libs/core/src/lib/time/time.component.spec.ts
libs/core/src/lib/time/time.component.ts
libs/platform/src/lib/form/date-picker/date-picker.component.spec.ts
libs/platform/src/lib/form/date-picker/date-picker.component.ts
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.spec.ts
libs/platform/src/lib/menu/menu.spec.ts
libs/platform/src/lib/search-field/search-field.component.spec.ts
libs/platform/src/lib/table/table.component.spec.ts

closes #7475 
closes #7474
closes #7465
closes #7461 
Added CVA unit tests for:
- core date picker
- core time picker
- core time
- platform date-picker
-   [n/a] different combinations of components - …

fix(core): cva unit tests for date & time pickers

---

NEW_COMPONENT.md
tools/generators/sap-component/files/docs/__fileName__-docs.module.ts.template
tools/generators/sap-component/index.ts

closes none
`raw-loader` has been removed recently. This should be reflected in component generation schematic.
Also made few updates for import paths (mostly for experimental packages)
-   [n/a] different …

fix: component schematic import updates

---

apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-async-example/multi-input-async-example.component.html
apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-async-example/multi-input-async-example.component.ts
apps/docs/src/assets/multi-input-values.json
libs/core/src/lib/multi-input/multi-input.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/7372
Issue https://github.com/SAP/fundamental-ngx/issues/7372 describes the problem with new values not being selected. That particular one was addressed in https://github.com/SAP/fundamental-ngx/pull/7419
However, in the issue above multi-input works with dynamic values. This doesn't work properly right now: when list of selected options is changed, selected value disappears (see [stackblitz reproduction](https://stackblitz.com/edit/angular-ivy-gojgba)). This is being fixed by current PR
-   [x] States - …

fix(core): multi-input - keep selected options

---

libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/date-picker/date-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/time-picker/time-picker.component.ts
libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/commons/base-combobox.ts
libs/platform/src/lib/form/date-picker/date-picker.component.ts
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/time-picker/time-picker.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/7532
Controls with dropdowns have "expand" key not tabbable by default. 
- Changed default value to true for controls that do support that. 
- Added `buttonFocusable` option to to combobox, multi-combobox and multi-input
-   [x] check for …

fix(core,platform): tab navigation in controls with dropdowns 

---

apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-disabled-example/date-picker-range-disabled-example.component.ts
e2e/wdio/core/tests/date-picker.e2e-spec.ts

test(core): fix failed e2e on main branch

---

apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.module.ts
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-dynamic-container-height-example/dynamic-page-dynamic-container-height-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-dynamic-container-height-example/dynamic-page-dynamic-container-height-example.component.ts
libs/core/src/lib/dynamic-page/dynamic-page-wrapper.directive.ts
libs/core/src/lib/dynamic-page/dynamic-page.component.ts
libs/core/src/lib/dynamic-page/dynamic-page.module.ts
libs/core/src/lib/dynamic-page/public_api.ts

closes #7567 
Added ability to change size listener from window to the parent element of the dynamic page component.
3. …

fix(core): handle dynamic height of dynamic page wrapper

---

apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.html
apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.html
apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.html
apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.html
apps/docs/src/app/core/component-docs/bar/examples/bar-with-title-example.component.html
apps/docs/src/app/core/component-docs/list-byline/examples/list-byline-interactive-example/list-byline-interactive-example.component.html
apps/docs/src/app/core/component-docs/list/examples/list-interactive-example/list-interactive-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-form-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-standard-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-examples/platform-form-container-complex-example.component.html
e2e/wdio/platform/tests/input-group.e2e-spec.ts
libs/core/src/lib/form/form-message/form-message.component.scss
libs/platform/src/lib/form/input-message-group-with-template/input-message-group-with-template.component.scss

part of  #7551
Overview of changes made according to #7551 (screenshots were removed for readability, refer to original ticket for details)
- [n/a] Vertical alignment for Bar component:
**Not done.** 
Appears to be an expected behavior for subheader:
fundamental-styles: https://sap.github.io/fundamental-styles/?path=/docs/components-bar--default#subheader
Fiori design specs:
- [n/a] Carousel issues: 1. Check with the design if the buttons on hover should look like this. 2. Check the focus states. Should the whole element get a focus?
**Not done.** Buttons hover styles are according to fiori specs 
The whole element should get focus as once it's focused, user is able to use arrow navigation
- [n/a] List with Byline active state:
**Not done.** There's a pending PR …

fix(core,platform): defect hunting issues

---

libs/core/src/lib/avatar-group/avatar-group.component.spec.ts
libs/core/src/lib/avatar-group/avatar-group.component.ts
libs/core/src/lib/avatar-group/avatar-group.interface.ts
libs/core/src/lib/avatar-group/directives/avatar-group-focusable-avatar.directive.ts
libs/core/src/lib/avatar-group/directives/avatar-group-item.directive.spec.ts
libs/core/src/lib/avatar-group/directives/avatar-group-item.directive.ts
libs/core/src/lib/avatar-group/directives/avatar-group-overflow-body.directive.ts
libs/core/src/lib/avatar-group/directives/avatar-group-overflow-button.directive.ts
libs/core/src/lib/avatar-group/public_api.ts

issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-992695752
1th issue
Added Keyboard navigation for Avatar Group
-   [n/a] check for console logs (warnings, …

fix(core): avatar-group, add keyboard support

---

apps/docs/src/app/core/component-docs/action-bar/action-bar-header/action-bar-header.component.ts
apps/docs/src/app/core/component-docs/action-sheet/action-sheet-header/action-sheet-header.component.ts
apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-pagination-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-example-styles.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-scrolling-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-scrolling-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-scrolling-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.ts
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.html
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.scss
apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.ts
e2e/wdio/core/pages/table.po.ts
libs/core/src/lib/object-status/object-status.component.scss
libs/core/src/lib/object-status/object-status.component.spec.ts
libs/core/src/lib/object-status/object-status.component.ts
libs/core/src/lib/object-status/object-status.module.ts
libs/platform/src/lib/object-status/object-status.component.spec.ts
libs/platform/src/lib/table/table.component.spec.ts
libs/platform/src/lib/table/table.component.ts

relates #7587 
This PR fixes following issues:
* (Platform) Smart Filter Bar, filtering not working in the table (column header)
* Core Bar in RTL mode: button icon not centered
* Vertical nav (core): icons misaligned, wrong size
* (Core) bug Step Input: similar issue to the one above
* (Core) bug Select - wrong position of the button
-   [x] Text …

fix(core/platform): defect hunting issues

---

apps/docs/src/app/core/component-docs/table/examples/table-pagination-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/editable-rows/platform-table-editable-rows-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/editable-rows/platform-table-editable-rows-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
e2e/wdio/core/tests/multi-input.e2e-spec.ts
e2e/wdio/platform/pages/table.po.ts
libs/platform/src/lib/table/components/table-column/table-column.component.ts
libs/platform/src/lib/table/components/table-column/table-column.ts
libs/platform/src/lib/table/components/table-editable-cell/table-editable-cell.component.html
libs/platform/src/lib/table/components/table-editable-cell/table-editable-cell.component.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.spec.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
libs/platform/src/lib/table/constants/index.ts
libs/platform/src/lib/table/directives/table-cell.directive.ts
libs/platform/src/lib/table/interfaces/save-rows-event.interface.ts
libs/platform/src/lib/table/models/table-row.model.ts
libs/platform/src/lib/table/public_api.ts
libs/platform/src/lib/table/table-cell.class.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.module.ts
libs/platform/src/lib/table/table.service.ts
libs/platform/src/lib/table/table.ts

closes #7422 closes #7538
Added ability to add new rows to the platform table. Added default controls which can be overriten with custom templates.
-   [x] change …

feat(platform): ability to add rows to table

---

apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts
apps/docs/src/app/core/component-docs/dialog/examples/dialog-examples.component.scss
apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html
apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.ts

closes #7254 
Fixes margins for the first 2 buttons when in RTL mode.
Conditionally adds left margins for RTL mode and right margins for LTR mode
-   [n/a] …

docs(core): dialog, fix button margins for RTL mode

---

apps/docs/src/app/core/component-docs/input-group/examples/input-group-button-example.component.html
libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/input-group/input-group.component.ts

Part of https://github.com/SAP/fundamental-ngx/issues/7587
> Combobox (core): has the double focus outline again
Input Group focus fix.

fix(core): input group focus

---

apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html

Part of https://github.com/SAP/fundamental-ngx/issues/7587
> (Core) Table, header menu items don't have appropriate cursor (pointer).
Table's header menu items cursor fix, icons fix.

fix(docs): table header cell icons

---

apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.ts

adds the new scss file created in #7608 to stackblitz examples

docs(core): dialog, add new scss file to stackblitz example

---

e2e/wdio/core/tests/date-picker.e2e-spec.ts
e2e/wdio/platform/pages/menu.po.ts
e2e/wdio/platform/pages/table.po.ts
e2e/wdio/platform/pages/upload-collection.po.ts

None
* fixes for broken e2e on main

test(core,platform): e2e fixes

---

libs/core/src/lib/pagination/pagination.component.html
libs/core/src/lib/pagination/pagination.component.ts
libs/core/src/lib/pagination/pagination.module.ts
libs/core/src/lib/utils/directives/focus-key-manager/focus-key-manager-helpers.module.ts
libs/core/src/lib/utils/directives/focus-key-manager/focus-key-manager-item.directive.spec.ts
libs/core/src/lib/utils/directives/focus-key-manager/focus-key-manager-item.directive.ts
libs/core/src/lib/utils/directives/focus-key-manager/focus-key-manager-list.directive.spec.ts
libs/core/src/lib/utils/directives/focus-key-manager/focus-key-manager-list.directive.ts
libs/core/src/lib/utils/public_api.ts

Part of https://github.com/SAP/fundamental-ngx/issues/7550
* Shared directives created to provide keyboard navigation (one items focusable and others accessible using arrows).
* Directives applied to the pagination component.

feat(core): pagination keyboard navigation

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/combobox/combobox.component.scss

Part of https://github.com/SAP/fundamental-ngx/issues/7587#issuecomment-1024367521
Fixes for the platform's combobox states.

fix(platform): combobox states

---

libs/core/src/lib/pagination/pagination.component.html

Follow up https://github.com/SAP/fundamental-ngx/pull/7630
Tab order changes for the pagination component.

fix(core): pagination tab order

---

apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs-header/fixed-card-layout-docs-header.component.html
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/7617
Added notes to the documentation about D'n'D delay in the fixed card layout component.

docs(core): dnd fixed card layout notes

---

apps/docs/src/app/core/api-files.ts
apps/docs/src/app/core/component-docs/initial-focus/examples/initial-focus-basic-example.component.html
apps/docs/src/app/core/component-docs/initial-focus/examples/initial-focus-basic-example.component.ts
apps/docs/src/app/core/component-docs/initial-focus/examples/initial-focus-complex-example.component.html
apps/docs/src/app/core/component-docs/initial-focus/examples/initial-focus-complex-example.component.ts
apps/docs/src/app/core/component-docs/initial-focus/examples/initial-focus-example.component.scss
apps/docs/src/app/core/component-docs/initial-focus/initial-focus-docs.component.html
apps/docs/src/app/core/component-docs/initial-focus/initial-focus-docs.component.ts
apps/docs/src/app/core/component-docs/initial-focus/initial-focus-docs.module.ts
apps/docs/src/app/core/component-docs/initial-focus/initial-focus-header/initial-focus-header.component.html
apps/docs/src/app/core/component-docs/initial-focus/initial-focus-header/initial-focus-header.component.ts
apps/docs/src/app/core/core-documentation.routes.ts
apps/docs/src/app/core/documentation/core-documentation-data.ts
e2e/wdio/core/pages/pagination.po.ts
e2e/wdio/platform/pages/upload-collection.po.ts
libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.ts
libs/platform/src/lib/table/table.component.spec.ts

closes #7635 
* Extended old `initial-focus` directive to support nested focusable elements and configurable css selectors to focus on defined elements.
* Created separate documentation page for `initial-focus` directive under Utilities section in Core
-   [x] check for console logs (warnings, …

feat(core): initial focus directive improvements

---

ci-scripts/publish.sh

fix(ci): fixing unknown refspec main

---

ci-scripts/publish.sh

Second try on fixing release publish

fix(ci): fixing ci publish issue 2

---

libs/core/schematics/ng-add/index.ts

None.
Sass support for the core schematics

fix(core): schematics sass support

---

apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-base-data-provider.ts
e2e/wdio/platform/pages/upload-collection.po.ts
libs/core/src/lib/dialog/base/dialog-ref-base.class.ts
libs/core/src/lib/message-toast/message-toast-utils/message-toast-ref.ts
libs/core/src/lib/resizable-card-layout/resizable-card-layout/resizable-card-layout.component.ts
libs/core/src/lib/utils/directives/overflow-list/overflow-list.directive.ts
libs/platform/src/lib/icon-tab-bar/components/icon-tab-bar-base.class.ts
libs/platform/src/lib/icon-tab-bar/directives/extra-button/extra-button.directive.ts
libs/platform/src/lib/icon-tab-bar/icon-tab-bar.component.ts
libs/platform/src/lib/search-field/search-field.component.ts
libs/platform/src/lib/table/table-scroll-dispatcher.service.ts
package-lock.json
package.json

Closes #7695
rxjs update to v7, the default in ng13.

chore(core,platform): rxjs update to v7

---

angular.json
apps/docs/src/app/fn/component-docs/generic-tag/examples/generic-tag-example/generic-tag-example-component.ts
apps/docs/src/app/fn/component-docs/generic-tag/examples/generic-tag-example/generic-tag-example.component.html
apps/docs/src/app/fn/component-docs/generic-tag/examples/index.ts
apps/docs/src/app/fn/component-docs/generic-tag/generic-tag-docs.component.html
apps/docs/src/app/fn/component-docs/generic-tag/generic-tag-docs.component.ts
apps/docs/src/app/fn/component-docs/generic-tag/generic-tag-docs.module.ts
apps/docs/src/app/fn/component-docs/generic-tag/tag-header/tag-header.component.html
apps/docs/src/app/fn/component-docs/generic-tag/tag-header/tag-header.component.ts
apps/docs/src/app/fn/documentation/fn-documentation-data.ts
apps/docs/src/app/fn/fn-documentation.routes.ts
libs/fn/src/lib/fundamental-ngx-fn.module.ts
libs/fn/src/lib/generic-tag/.eslintrc.json
libs/fn/src/lib/generic-tag/README.md
libs/fn/src/lib/generic-tag/generic-tag.component.html
libs/fn/src/lib/generic-tag/generic-tag.component.scss
libs/fn/src/lib/generic-tag/generic-tag.component.spec.ts
libs/fn/src/lib/generic-tag/generic-tag.component.ts
libs/fn/src/lib/generic-tag/generic-tag.module.ts
libs/fn/src/lib/generic-tag/index.ts
libs/fn/src/lib/generic-tag/karma.conf.js
libs/fn/src/lib/generic-tag/ng-package.json
libs/fn/src/lib/generic-tag/package.json
libs/fn/src/lib/generic-tag/public_api.ts
libs/fn/src/lib/generic-tag/test.ts
libs/fn/src/lib/generic-tag/tsconfig.json
libs/fn/src/lib/generic-tag/tsconfig.lib.json
libs/fn/src/lib/generic-tag/tsconfig.lib.prod.json
libs/fn/src/lib/generic-tag/tsconfig.spec.json
tsconfig.base.json

relates #7670 
Added Generic Tag component
-
-   [x] missing API documentation …

feat(fn): introduce Generic Tag component in Fiori Next

---

apps/docs/src/app/platform/component-docs/platform-multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.html
apps/docs/src/app/platform/component-docs/platform-multi-combobox/examples/multi-combobox-states/multi-combobox-states-example.component.html
apps/docs/src/app/platform/component-docs/platform-multi-combobox/examples/multi-combobox-states/multi-combobox-states-example.component.ts
apps/docs/src/app/platform/component-docs/platform-multi-combobox/platform-multi-combobox-docs.component.html
apps/docs/src/app/platform/component-docs/platform-multi-combobox/platform-multi-combobox-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-multi-combobox/platform-multi-combobox-docs.module.ts
libs/platform/src/lib/form/auto-complete/auto-complete.directive.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.scss
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts

issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-993882743
2th and 3th issue
Fixed Multi Combobox selection in mobile mode
Fixed Multi Combobox DataSource last example, "example with" text was cut off
-   [n/a] …

fix(platform): multi-combobox, fix selection in mobile mode

---

.github/workflows/on-push-or-pull.yml

chore(deps): fix release script

---

apps/docs/src/app/core/component-docs/message-box/examples/template-based/template-based-message-box-example.component.html
libs/core/src/lib/message-box/message-box-body/message-box-body.component.spec.ts
libs/core/src/lib/message-box/message-box-body/message-box-body.component.ts
libs/core/src/lib/message-box/message-box-footer/message-box-footer.component.spec.ts
libs/core/src/lib/message-box/message-box-footer/message-box-footer.component.ts
libs/core/src/lib/message-box/message-box-header/message-box-header.component.html
libs/core/src/lib/message-box/message-box-header/message-box-header.component.spec.ts
libs/core/src/lib/message-box/message-box-header/message-box-header.component.ts
libs/core/src/lib/message-box/message-box-semantic-icon/message-box-semantic-icon.component.spec.ts
libs/core/src/lib/message-box/message-box-semantic-icon/message-box-semantic-icon.component.ts
libs/core/src/lib/message-box/message-box.component.ts
libs/core/src/lib/message-box/utils/message-box-config.class.ts

closes https://github.com/SAP/fundamental-ngx/issues/7672
Bringing an ability to use content projection to pass semantic icon inside the message box header component.
Also fixed an issue with config not being passed properly into dynamically added component (instead of setting config to content children directly now relying on DI)
2. …

fix(core): message-box - be able to display custom icons in header

---

libs/core/src/lib/README.md

docs(ci): update build badge

---

ci-scripts/hotfix-publish.sh

replace master with main in hostfix-publish script

chore(deps): replace master with main in hotfix-publish script

---

ci-scripts/sync-version.sh

Closes #7756.
Dist version fix.

fix(core,platform,fn): dist version

---

apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts

docs(core,platform): update version menu

---

libs/core/src/lib/README.md

docs(core): add npm download badge

---

libs/platform/src/lib/README.md

add monthly npm downloads badge

docs(platform): add monthly npm downloads badge

---

apps/docs/src/app/core/component-docs/upload-collection/examples/upload-collection-complex-example.component.html
apps/docs/src/app/core/component-docs/upload-collection/examples/upload-collection-complex-example.component.ts
apps/docs/src/app/core/component-docs/upload-collection/upload-collection-docs.component.html

closes https://github.com/sap/fundamental-ngx/issues/7749
An ability to select ranges should be implemented in upload-collection
-   [n/a] change the …

docs(core): upload-collection - add range selection to the example

---

e2e/wdio/platform/pages/multi-input.po.ts
e2e/wdio/platform/tests/multi-input.e2e-spec.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts

n/a
Currently platform-multi-input triggers data loading whenever escape is pressed. This behavior should be omitted.
Additionally adding delay for opening the dropdown in loading example to fix e2e tests
- …

fix(platform): multi-input - omit extra dataSource triggering

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.spec.ts
libs/platform/src/lib/table/table.component.ts

closes https://github.com/sap/fundamental-ngx/issues/7754
closes https://github.com/sap/fundamental-ngx/issues/7755
1. Added an ability to select ranges in platform table component
2. Fixed an issue with having multiple selected rows when changing the selection mode from multiple to single
3. Added an ability to ungroup the rows when clicking on the "group" action of the column, that is being grouped by
-   [x] Interaction/Animation - open/close, expand/collapse, …

feat(platform): table - range selection & bug fixes

---

libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.ts

feat(platform): emit event when smart filters have been updated

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.spec.ts
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.scss

closes https://github.com/SAP/fundamental-ngx/issues/7612
-   [n/a] …

fix(platform): upload collection enhancements

---

libs/core/schematics/ng-add/index.ts

Closes #7794.
Schematics @angular/cdk version issue fix.

fix(core): schematics angular cdk version issue

---

libs/core/src/lib/layout-grid/layout-grid.component.ts

Closes #7665.
Vertical gutter fix for the layout grid component.

fix(core): layout grid vertical gutter

---

apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss
apps/docs/src/styles.scss
libs/core/schematics/ng-add/styles.ts
libs/core/src/lib/utils/services/themes.service.ts
libs/fn/schematics/ng-add/styles.ts
package-lock.json
package.json

feat(core,platform): bring horizon themes

---

apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.html
apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.ts
apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-default/action-sheet-default-example.component.html
apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-default/action-sheet-default-example.component.ts
apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.html
apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.ts
libs/core/src/lib/action-sheet/action-sheet-body/action-sheet-body.component.html
libs/core/src/lib/action-sheet/action-sheet-body/action-sheet-body.component.ts
libs/core/src/lib/action-sheet/action-sheet-control/action-sheet-control.component.ts
libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.html
libs/core/src/lib/action-sheet/action-sheet-mobile/action-sheet-mobile.component.ts
libs/core/src/lib/action-sheet/action-sheet.component.html
libs/core/src/lib/action-sheet/action-sheet.component.ts

closes https://github.com/sap/fundamental-ngx/issues/6211
Fixed Action Sheet i11y issues
3. …

fix(core): action-sheet, fix a11y issues

---

apps/docs/src/app/core/component-docs/avatar/avatar-docs.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-borders-example.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-circle-example.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-icon-example.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-icon-example.component.ts
apps/docs/src/app/core/component-docs/avatar/examples/avatar-initials-example.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-transparent-example.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-zoom-icon-example.component.html
apps/docs/src/app/core/component-docs/avatar/examples/avatar-zoom-icon-example.component.ts
libs/core/src/lib/avatar/avatar.component.html
libs/core/src/lib/avatar/avatar.component.ts

Part of #7815.
* Avatar `clickable` input property & `avatarClicked` output property.
* Avatar `zoomGlyphClicked` output propert, emits only if `zoomGlyph` is set.

feat(core): avatar clickable & event, zoomGlyph event on click

---

libs/core/src/lib/form/form-label/form-label.component.scss

fix form label vertical spacing

fix(core): fix form label spacing

---

libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/form/form-control/form-control.component.ts
libs/core/src/lib/input-group/input-group-directives.ts
libs/core/src/lib/input-group/input-group.component.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/progress-indicator/progress-indicator.component.ts
libs/core/src/lib/radio/radio-button/radio-button.component.ts
libs/core/src/lib/step-input/step-input.component.ts
libs/core/src/lib/tabs/tab-panel/tab-panel.component.ts
libs/core/src/lib/tile/directives/numeric-content.directives.ts
libs/fn/src/lib/form/form-item/form-item.component.ts

make state input optional -> it allows passing `undefined` for `state`

fix(core): make state input optional

---

libs/core/src/lib/menu/services/menu.service.ts

fixes #7786 
Fixes a bug where left/right keyboard arrows did not work correctly in RTL mode

fix(core): fix backwards left/right arrows in RTL mode for menu

---

apps/docs/src/app/core/component-docs/table/examples/table-cdk-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.ts
apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-columns-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-focusable-example/table-focusable-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.ts
apps/docs/src/app/core/component-docs/table/examples/table-responsive-example.component.html
apps/docs/src/app/core/component-docs/table/table-docs.module.ts
e2e/wdio/core/pages/table.po.ts

Part of #7815.
Various defect hunting issues fixes. Relates only to the docs.
See issues here https://github.com/SAP/fundamental-ngx/issues/7815#issuecomment-1054510579

fix(core): table defect hunting issues

---

apps/docs/src/app/core/component-docs/textarea/textarea-docs.component.html

docs(core): update the documentation for textarea

---

libs/core/src/lib/dynamic-page/dynamic-page.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/7799
- fix flickering screen when the header starts to collapse on scrolling …

fix(core): dynamic page fix flickering screen

---

apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-compact-example.component.html
apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-example.component.html
apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-file-types-example.component.html
apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-max-file-size-example.component.html
apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-min-file-size-example.component.html
apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-reactive-example.component.html
libs/core/src/lib/file-uploader/file-uploader.component.html
libs/core/src/lib/file-uploader/file-uploader.component.spec.ts
libs/core/src/lib/file-uploader/file-uploader.component.ts
libs/platform/src/lib/form/platform-file-uploader/platform-file-uploader.component.html

closes https://github.com/SAP/fundamental-ngx/issues/7864
- add width property to the file uploader …

feat(core): file uploader add manageable width

---

apps/docs/src/app/core/component-docs/fixed-card-layout/examples/custom-column-width/fixed-card-layout-custom-column-width-example.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/custom-column-width/fixed-card-layout-custom-column-width-example.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

Closes none.
Fixed Card Layout component Column Width feature.

feat(core): fixed card layout column width

---

.github/mergeable.yml

chore(deps): update mergeable.yml

---

CHANGELOG.md
package.json

chore(ci): fix release version

---

.github/workflows/on-push-or-pull.yml

fix release script for hotfixes

chore(ci): fix release script for hotfixes

---

.github/workflows/on-push-or-pull.yml

try to fix the hotfix script v2

chore(ci): try to fix the hotfix script v2

---

ci-scripts/hotfix-publish.sh

chore(ci): test ci

---

.github/workflows/on-push-or-pull.yml
ci-scripts/hotfix-publish.sh

chore(ci): fix hotfix script

---

apps/docs/src/app/core/component-docs/form-message/examples/state-message/form-messaging-state-example.component.html
apps/docs/src/app/core/component-docs/form-message/examples/state-message/form-messaging-state-example.component.ts
apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.html
apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.ts
apps/docs/src/app/core/component-docs/form-message/form-message-docs.module.ts
apps/docs/src/app/core/component-docs/form-message/form-message-header/form-message-header.component.html

docs(core): form message update

---

apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.ts
apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts
apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
e2e/wdio/core/pages/popover.po.ts
e2e/wdio/core/tests/popover.e2e-spec.ts
libs/core/src/lib/popover/popover-container/popover-container.directive.ts
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/core/src/lib/popover/popover.module.ts
libs/core/src/lib/popover/public_api.ts

closes #7852 
* Added popover container directive which listens on element resize and refreshes popover positions accordingly.
* Added example of this functionality. …

feat(core): handle dynamic container height

---

package-lock.json
package.json

update to theming-base-content v 11.1.38

chore(deps): update to theming-base-content v 11.1.38

---

apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-docs.component.html
apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-basic-example.component.html
apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-custom-filter-example.component.html
apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-custom-labels-example.component.html
apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-dynamic-page-example.component.html
apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-observable-example.component.html
e2e/wdio/platform/tests/form-generator.e2e-spec.ts
libs/platform/src/lib/form/form-group/form-group.component.scss
libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-conditions-dialog/smart-filter-bar-conditions-dialog.component.html
libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-field-definition.directive.spec.ts
libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-field-definition.directive.ts
libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-subject.directive.spec.ts
libs/platform/src/lib/smart-filter-bar/directives/smart-filter-bar-subject.directive.ts
libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.scss
libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.spec.ts

closes #7928, closes #7958
Previously, [filterable] input property of smart filter bar interfered with same input property of the table cell. Now those properties are separated.
Additionaly styling has been fixed for grid system.
-   [x] API boundary …

fix(platform): rename input property

---

apps/docs/src/app/core/component-docs/carousel/carousel-docs.component.html
apps/docs/src/app/core/component-docs/carousel/carousel-docs.module.ts
apps/docs/src/app/core/component-docs/carousel/examples/carousel-auto-slides-example.component.html
apps/docs/src/app/core/component-docs/carousel/examples/carousel-auto-slides-example.component.ts
apps/docs/src/app/core/component-docs/carousel/examples/carousel-example.component.scss
libs/core/src/lib/carousel/carousel.component.ts

closes #7851 
Added ability to set visibleSlidesCount property to auto.
-   [x] …

fix(core): add auto slides calculation

---

libs/core/src/lib/grid-list/helpers/parse-layout-pattern.ts

closes #7865 
number 5 was missing from sequence

fix(core): added missing column numbers sequence

---

libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.scss
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.module.ts

closes https://github.com/SAP/fundamental-ngx/issues/5842
Date time Picker: in Mobile not able to select the date and time in both landscape and portrait mode
-   [n/a] different combinations of components - free …

fix(core): datetime picker - mobile mode switcher

---

apps/docs/src/app/core/component-docs/fixed-card-layout/examples/max-columns/fixed-card-layout-max-columns-example.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/max-columns/fixed-card-layout-max-columns-example.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.spec.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

closes none.
Ability to limit max number of columns for fixed card layout comp.

feat(core): maxColumns feature for fixed grid layout

---

.github/dependabot.yml

chore(deps): update dependabot.yml

---

.github/CODEOWNERS

chore(ci): update CODEOWNERS

---

apps/docs/src/app/core/component-docs/card/card-docs.component.html
apps/docs/src/app/core/component-docs/card/card-docs.module.ts
apps/docs/src/app/core/component-docs/card/examples/card-footer-example.component.html
apps/docs/src/app/core/component-docs/card/examples/list-card/card-list-example.component.html
apps/docs/src/app/core/component-docs/card/examples/quick-view-card/card-quick-view-example.component.html
e2e/wdio/core/fixtures/appData/card-content.ts
e2e/wdio/core/pages/card.po.ts
e2e/wdio/core/tests/card.e2e-spec.ts
libs/core/src/lib/card/card-action-item.directive.ts
libs/core/src/lib/card/card-content.component.ts
libs/core/src/lib/card/card-footer-action-item.directive.ts
libs/core/src/lib/card/card-footer.component.html
libs/core/src/lib/card/card-footer.component.scss
libs/core/src/lib/card/card-footer.component.ts
libs/core/src/lib/card/card.component.ts
libs/core/src/lib/card/card.module.ts
libs/core/src/lib/card/card.tokens.ts
libs/core/src/lib/card/constants.ts
libs/core/src/lib/card/public_api.ts
libs/core/src/lib/list/list.component.ts
libs/core/src/lib/list/list.tokens.ts
libs/core/src/lib/list/public_api.ts
package-lock.json
package.json

This PR adds footer to the card component and also added feature to card horizon component with list

fix(core): card horizon breaking changes

---

libs/core/src/lib/bar/button-bar/button-bar.component.ts
libs/core/src/lib/dialog/base/dialog-content-base.class.ts
libs/core/src/lib/dialog/dialog-default/dialog-default.component.html
libs/core/src/lib/message-box/message-box-default/message-box-default.component.html

closes https://github.com/SAP/fundamental-ngx/issues/8004
Adding an ability to configure "id" for dialog action buttons
-   [n/a] change the API …

feat(core): add an ability to set "id" for dialog buttons from config

---

apps/docs/src/app/core/component-docs/moment-datetime-adapter/moment-datetime-adapter-docs.module.ts
apps/docs/src/app/core/component-docs/schemas.ts
apps/docs/src/app/core/core-documentation.module.ts
apps/docs/src/app/documentation/core-helpers/docs-section-title/docs-section-title.component.ts
apps/docs/src/app/documentation/core-helpers/import/import.component.ts
apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
apps/docs/src/app/documentation/services/api-docs.service.ts
apps/docs/src/app/documentation/utilities/libraries.ts
apps/docs/src/app/fn/fn-documentation.module.ts
apps/docs/src/app/platform/component-docs/schemas.ts
apps/docs/src/app/platform/platform-documentation.module.ts
apps/docs/src/app/schema/consts/schemas.ts
apps/docs/src/app/schema/schema.module.ts
apps/docs/src/app/schema/services/schema-factory/schema-factory.service.ts

Should not be using plain strings for injection tokens

fix(docs): use injection tokens instead of plain strings

---

libs/core/src/lib/menu/directives/menu-title.directive.ts
libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.html

closes https://github.com/SAP/fundamental-ngx/issues/8056
Menu should be used with correct structure in order to have overflow
-   [ x] Text Truncation
-   [n/a] change the API …

fix(platform): approval-flow - approvers menu overflow

---

libs/core/src/lib/wizard/wizard-content/wizard-content.component.html

part of #7931 
This will be needed to handle a breaking change from https://github.com/SAP/fundamental-styles/pull/3382

fix(core): update for outstanding wizard PR in styles

---

libs/core/src/lib/busy-indicator/busy-indicator.component.html
package-lock.json
package.json

https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#busy-indicator-3414
closes none

fix(core): busy indicator breaking changes

---

apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-container-example/popover-container-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.scss
apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic-container-height/popover-dynamic-container-height-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-focus-example/popover-focus-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-focus-example/popover-focus-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-new-placement/popover-cdk-placement-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-new-placement/popover-cdk-placement-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-programmatic/popover-programmatic-open-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-programmatic/popover-programmatic-open-example.component.ts
apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.ts
apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
e2e/wdio/core/pages/popover.po.ts
e2e/wdio/core/tests/popover.e2e-spec.ts

part of #7984
Popover bodies should not have been containing fd-lists, this PR only changes the docs. No breaking changes to popover from fundamental-styles

fix(core): update popover docs to not use fd-list

---

libs/core/src/lib/inline-help/inline-help.directive.spec.ts
libs/core/src/lib/inline-help/inline-help.directive.ts

closes https://github.com/SAP/fundamental-ngx/issues/8107
The inline help popup should disappear when its hosting component/button is destroyed.
https://stackblitz.com/edit/angular-7eqlgq?file=src%2Fapp%2Finline-help-styled-example.component.html
-   [x] check for console logs …

fix(core): inline-help - fix destroy behavior

---

apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html
apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-template-example.component.html
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/7661
- fix improper form validation when the DateTime Picker's control has invalid datetime value
-   [n/a] …

fix(platform): date time picker form validation

---

libs/core/src/lib/product-switch/product-switch/product-switch.component.html

part of #7984 
Removes unnecessary class from product switch control

fix(core): remove unused product switch control class

---

apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-contextual-menu-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.html
apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.html
libs/platform/src/lib/action-bar/action-bar.component.html

closes https://github.com/sap/fundamental-ngx/issues/6092
Fixed action-bar i11y issues
3. …

fix(platform): action-bar, fix a11y issues

---

apps/docs/src/app/core/component-docs/slider/examples/disabled/slider-disabled-example.component.html
e2e/wdio/core/pages/product-switch.po.ts
e2e/wdio/platform/pages/form-generator.po.ts
e2e/wdio/platform/pages/list.po.ts
e2e/wdio/platform/tests/dynamic-page-layout.e2e-spec.ts
libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/slider/slider.component.html
libs/core/src/lib/slider/slider.component.scss
libs/core/src/lib/slider/slider.component.ts

relates #7931
Added Horizon theme for the Slider component. …

feat(core): slider horizon theme

---

apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-basic-example.component.html
apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-growing-example.component.html
apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-no-gap-example.component.html
apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-offset-example.component.html
apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-responsive-example.component.html
apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-responsive-offset-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.html
apps/docs/src/app/core/component-docs/wizard/examples/wizard-visible-summary-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-customizable-embeded-example.component.html
apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-customizable-example.component.html
libs/core/src/lib/layout-grid/directives/layout-grid-col.directive.spec.ts
libs/core/src/lib/layout-grid/layout-grid.component.html
libs/core/src/lib/layout-grid/layout-grid.component.ts
libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-conditions-dialog/smart-filter-bar-conditions-dialog.component.html
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.html
libs/platform/src/lib/value-help-dialog/components/define-tab/define-tab.component.html
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.html
package-lock.json
package.json

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1132079100
Layout Grid component fixes, nested rows issue fix.

fix(core): layout grid issues

---

apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-base-example.component.html
apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-base-example.component.ts
libs/core/src/lib/quick-view/quick-view/quick-view.component.scss

Changes required to accompany the merge of https://github.com/SAP/fundamental-styles/pull/3443
This branch will require a styles version bump as well

fix(core): quick view background, requires corresponding PR in styles

---

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-default-example.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.html

link optionalText from wizardGenerator's steps to wizard steps

fix(platform): link optionalText from wizardGenerator's steps to wizard steps

---

libs/core/src/lib/link/link.component.html
libs/core/src/lib/link/link.component.scss
libs/core/src/lib/link/link.component.ts
libs/core/src/lib/link/link.module.ts
package-lock.json
package.json

This PR adds `__content` element in link
Blocked until https://github.com/SAP/fundamental-styles/pull/3504

feat(core): link updates

---

libs/core/src/lib/list/list-item/list-item.component.ts
libs/core/src/lib/radio/radio-button/radio-button.component.ts

Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1128569978
Focus approach unified for the selectable list items.

fix(core): list single selection focus

---

libs/core/src/lib/link/constants.ts
libs/core/src/lib/link/public_api.ts
libs/core/src/lib/upload-collection/upload-collection-item.directive.spec.ts
libs/core/src/lib/upload-collection/upload-collection-item.directive.ts

part of #7984 
Due to breaking changes in fd-link, upload collection needs these updates

fix(core): upload collection title bug

---

libs/platform/src/lib/menu/menu-trigger.directive.ts
libs/platform/src/lib/menu/menu.component.ts

closes #8144
Adding an ability to disable opening of the menu using arrow keys …

feat(platform): menu - ability to disable opening by arrow keys

---

apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts

Add link to 0.34.2 docs in the version DDLB

docs(core,platform): include 0.34.2 docs link

---

libs/core/src/lib/token/tokenizer.component.ts

fixes #8227 
Refactors the tokenizer collapsing/expanding logic, instead of trying to expand one by one when the token list changes or the screen size expands, expands them all then runs the collapse logic again. This simplifies things and makes it easier to catch some edge cases that the previous implementation struggled with. Shouldn't have any tangible performance effects.

fix(core): refactor tokenizer collapse/expand behavior

---

package-lock.json
package.json

none
update sap-theming to 11.1.40

chore(core/platform): update sap-theming to 11.1.40

---

apps/docs/src/app/core/component-docs/table/examples/table-activable-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-cdk-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.ts
apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-columns-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-focusable-example/table-focusable-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-focusable-example/table-focusable-example.component.ts
apps/docs/src/app/core/component-docs/table/examples/table-footer-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-navigatable-row-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-pagination-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-responsive-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-semantic-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-semantic-example.component.ts
apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
apps/docs/src/app/core/component-docs/table/examples/table-without-borders-example.component.html
apps/docs/src/app/core/component-docs/table/table-docs.component.html
apps/docs/src/app/core/component-docs/table/table-docs.component.ts
apps/docs/src/styles.scss
e2e/wdio/core/pages/table.po.ts
e2e/wdio/core/tests/table.e2e-spec.ts
e2e/wdio/platform/tests/table.e2e-spec.ts
libs/core/src/lib/table/directives/table-cell.directive.ts
libs/core/src/lib/table/directives/table-row.directive.ts
libs/core/src/lib/table/directives/table-status-indicator.directive.ts
libs/core/src/lib/table/fd-table.interface.ts
libs/core/src/lib/table/table.component.ts

closes #6178
- Issue 1 - cannot reproduce
- Issue 2 - fixed
- Issue 3 - fixed
- Issue 4 - fixed
- Issue 5 - fixed
- Issue 6 - fixed
- Issue 7 - fixed
- Issue 8 - done
- Issue 9 - fixed
- Issue 10 - not an issue, checkbox column is a separate one, ‘Fruit Description’ and ‘Price’ should not be associated with it
- Issue 11 - fixed
- Issue 12 - fixed
- Issue 13 - fixed
-   [x] Mouse vs. …

feat(core): table - a11y issues

---

libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.html
libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts

closes #8189
Temporary solution while waiting for #7900

fix(core,platform): add inputs for datetimepicker ok/cancel buttons

---

e2e/wdio/core/pages/date-time-picker.po.ts
e2e/wdio/platform/pages/date-time-picker.po.ts

fix: fix failiing e2e tests

---

libs/core/schematics/ng-add/index.ts
libs/core/schematics/ng-add/schema.json
libs/core/schematics/ng-add/schema.ts

With this udpated user will have ability to select supported themes in their application during ng-add.

fix(core): modified ng-add schema of core, will include theme

---

apps/docs/src/app/core/component-docs/flexible-column-layout/examples/custom-config/flexible-column-layout-custom-config-example.component.html
apps/docs/src/app/core/component-docs/flexible-column-layout/examples/custom-config/flexible-column-layout-custom-config-example.component.scss
apps/docs/src/app/core/component-docs/flexible-column-layout/examples/custom-config/flexible-column-layout-custom-config-example.component.ts
apps/docs/src/app/core/component-docs/flexible-column-layout/examples/custom-config/flexible-column-layout-global-config-example.ts
apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.html
apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.ts
apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.module.ts
libs/core/src/lib/flexible-column-layout/constants.ts
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts
libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.ts
libs/core/src/lib/flexible-column-layout/flexible-column-layout.module.ts
libs/core/src/lib/flexible-column-layout/public_api.ts

closes #8194 
* Added configurable layout definitions for the Flexible Column layout component.
* Removed button styling import and replaced buttons with fd-button component.
-   [x] different combinations of components - …

feat(core): configurable flexible column layout

---

libs/core/schematics/ng-add/index.ts
libs/core/schematics/utils/angular-json-utils.ts

This should fix failing installations

fix(core): cdk reference in schematics

---

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.spec.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

Closes none.
Fixed Card Layout code improvements.
Fixed Card Layout in Tabs fix.
Apply git patch to update tabs example to reproduce the issue
[tabs.txt](https://github.com/SAP/fundamental-ngx/files/8967059/tabs.txt)

fix(core): fixed card layout improvements, tabs issue

---

libs/core/src/lib/wizard/wizard.component.html
libs/core/src/lib/wizard/wizard.component.scss
libs/core/src/lib/wizard/wizard.module.ts

closes 311 in DXP
* Added cdkScrollable directive to wizard scrollable body element
* Added z-index for wizard progress bar in order to hide popovers from wizard body on scroll
-   [x] different combinations of components - …

fix(core): popovers inside wizard scrollable body

---

apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-icon-example.component.html
libs/core/src/lib/info-label/info-label.component.html
libs/core/src/lib/info-label/info-label.component.spec.ts
libs/core/src/lib/info-label/info-label.component.ts
libs/core/src/lib/info-label/info-label.module.ts
libs/platform/src/lib/info-label/info-label.component.html
libs/platform/src/lib/info-label/info-label.component.spec.ts
libs/platform/src/lib/info-label/info-label.component.ts

closes #8301 8301
Added input property for changing the font family of the info label icon. Migrated to icon component instead of plain `<i>` element.
-   [x] change …

feat(core): info label different icon fonts

---

metadata.yaml

fix(core,platform): metadata.yaml nx format

---

apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.ts
apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
e2e/wdio/core/pages/fixed-card-layout.po.ts
e2e/wdio/core/tests/fixed-card-layout.e2e-spec.ts
libs/core/src/lib/card/card-content.component.ts
libs/core/src/lib/card/card.component.ts
libs/core/src/lib/card/card.tokens.ts
libs/core/src/lib/card/constants.ts
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
libs/core/src/lib/list/list.component.ts
libs/core/src/lib/list/list.tokens.ts
libs/core/src/lib/list/public_api.ts
libs/core/src/lib/utils/functions/get-document-font-size.ts
libs/core/src/lib/utils/functions/index.ts

Relates to DXP.
Fixed Card Layout component 
* edge use cases fixes, 
* code optimisations, 
* growing cards processing feature.

fix(core): fixed card layout issues, growing card feature

---

apps/docs/src/app/core/component-docs/alert/examples/alert-component-as-content-example.component.html

part of https://github.com/SAP/fundamental-ngx/issues/8342
before:
after:

docs(core): fix text issue with alert from component

---

libs/core/src/lib/select/option/option.component.html
package.json
yarn.lock

dxp.
Select's dropdown items overflow.

fix(core): select overflow & styles version bump

---

package.json
yarn.lock

upgrade to fundamental-styles version 0.24.2

chore(deps): upgrade to fundamental-styles version 0.24.2

---

libs/core/src/lib/avatar/avatar.component.html
libs/core/src/lib/avatar/avatar.component.ts

fix(core): fix zoom icon clickability and avatar focus

---

libs/core/src/lib/breadcrumb/breadcrumb.component.html
libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts
libs/core/src/lib/breadcrumb/breadcrumb.component.ts

closes #8325 
Added menu container element width into calculation of free space. …

fix(core): correct breadcrumb overflow calculation

---

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

Refers to DXP.
Fixed Card Layout enhancements
* fixed issue when jest tests failed because of checking container element width (always is 0 in jsdom).
* calculations optimisation
* naming improvements
No changes.

fix(core): fixed card layout minor enhancements

---

apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-docs.module.ts
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-dynamic-container-height-example/dynamic-page-dynamic-container-height-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html
apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html
apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.html
apps/docs/src/app/core/component-docs/inline-help/inline-help-header/inline-help-header.component.html
apps/docs/src/app/core/component-docs/resizable-card-layout/examples/resizable-card-layout-example-itemconfig.component.html
apps/docs/src/app/core/component-docs/resizable-card-layout/examples/resizable-card-layout-example-layoutconfig.component.html
apps/docs/src/app/core/component-docs/resizable-card-layout/examples/resizable-card-layout-example.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.html
apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page.module.ts
apps/docs/src/app/platform/component-docs/platform-smart-filter-bar/platform-smart-filter-bar-examples/platform-smart-filter-bar-dynamic-page-example.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.module.ts

relates dxp/metadata-registry/issues/389
* Updated the examples of the dynamic page component.
* Added notice for Inline Help component regarding placing it in scrollable container
* Updated platform dynamic page component …

fix(core): dynamic page with inline hint

---

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts

Refers to DXP.
More enhancements & fixes for the Fixed Card Layout component.
* no cards issue fix (previously we skipped any calculations in that case)
* unneeded scrollbars issues fixes
* manual triggering of change detection improvements

fix(core): fixed card layout enhancements

---

package.json
yarn.lock

update to fundamental-styles 0.24.3

chore(core,platform): update to fundamental-styles 0.24.3

---

package.json
yarn.lock

Related to https://github.com/SAP/fundamental-styles/issues/3748

chore: bumped fundamental-styles version

---

package.json
yarn.lock

update to fundamental-styles 0.24.4

chore(core,platform): update to fundamental-styles 0.24.4

---

libs/platform/src/lib/list/list.component.ts

closes #8410
Added correct click handler so that current active item index gets updated. …

fix(platform): fix list keyboard navigation

---

libs/core/schematics/ng-add/index.ts

closes #8457 
- Fixed styling migration
- Added info message regarding theming.

fix(core): fix theming schematics

---

libs/core/src/lib/overflow-layout/overflow-layout.service.ts
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html

closes #8472 
Changed Upload Collection markup to correct one so that DOM portals of the Breadcrumbs component would work properly. …

fix(platform): correct markup for breadcrumbs

---

apps/docs/src/app/core/component-docs/overflow-layout/examples/complex/overflow-layout-complex-example.component.html
apps/docs/src/app/core/component-docs/overflow-layout/examples/complex/overflow-layout-complex-example.component.scss
libs/core/src/lib/breadcrumb/breadcrumb.component.html
libs/core/src/lib/breadcrumb/breadcrumb.component.scss
libs/core/src/lib/overflow-layout/directives/overflow-item-ref.directive.ts
libs/core/src/lib/overflow-layout/interfaces/overflow-item-ref.interface.ts
libs/core/src/lib/overflow-layout/interfaces/overflow-item.interface.ts
libs/core/src/lib/overflow-layout/overflow-layout.component.html
libs/core/src/lib/overflow-layout/overflow-layout.component.scss
libs/core/src/lib/overflow-layout/overflow-layout.component.ts
libs/core/src/lib/overflow-layout/overflow-layout.service.ts

closes #8429 
* Refactored available space calculation method;
* Refactored markup to allow placing more button right next to the last visible item;
* Fixed `reverse` logic for breadcrumbs;
* Updated `complex` example of Overflow Layout;
* Added `globalIndex` property which indicates index of the item in original array of items;
* Fixed focusableItems for `FocusKeyManager`;
-   [x] Mouse vs. …

fix(core): adjust calculation method for overflow layout

---

libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.spec.ts
libs/core/src/lib/combobox/combobox.component.spec.ts
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/select/select.component.spec.ts

chore: fix unit tests

---

libs/core/src/lib/time/time-column/time-column.component.ts

closes #5644 
Added mouse-wheel event listener to time column.

feat(core): enable scrolling in time picker

---

libs/datetime-adapter/src/lib/dayjs-datetime-adapter.spec.ts

closes None
So, this happened recently https://github.com/iamkun/dayjs/pull/1954 and because of it, our units were failing. hopefully this PR fixes it

chore: updated unit tests to adapt with changes from 3rd party

---

libs/core/src/lib/wizard/wizard.component.ts

closes #5797
Added timeout on progress-bar's `visible=false`.

fix(core): solve wizard flicker on summary

---

apps/docs/src/app/core/component-docs/object-page/object-page-docs.component.html
apps/docs/src/app/core/component-docs/object-page/object-page-docs.component.ts
apps/docs/src/app/core/component-docs/object-page/object-page-docs.module.ts
apps/docs/src/app/core/component-docs/object-page/object-page-examples/object-page-example.component.html
apps/docs/src/app/core/component-docs/object-page/object-page-examples/object-page-example.component.ts
apps/docs/src/app/core/component-docs/object-page/object-page-header/object-page-docs-header.component.ts
apps/docs/src/app/core/component-docs/object-page/object-page-header/object-page-header.component.html
apps/docs/src/app/core/core-documentation.routes.ts
apps/docs/src/app/core/documentation/core-documentation-data.ts

Closes #8369
Object Page documentation & examples. No new components were created because Object Page is just a certain components set used with Dynamic Page component, see more https://experience.sap.com/internal/fiori-design-web/object-page/

docs(core): object page docs & examples

---

apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts

closes #8529
Added missing dependencies for stackblitz package.json

fix(docs): stackblitz missing deps

---

apps/docs/src/app/platform/api-files.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/editable-rows/platform-table-editable-rows-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-filterable-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-responsive-columns-example.component.html
apps/docs/src/app/platform/component-docs/platform-table/platform-table-examples/platform-table-responsive-columns-example.component.ts
apps/docs/src/app/platform/component-docs/platform-table/platform-table.module.ts
e2e/wdio/platform/tests/table.e2e-spec.ts
libs/platform/src/lib/table/components/table-column/table-column.component.ts
libs/platform/src/lib/table/components/table-column/table-column.ts
libs/platform/src/lib/table/directives/platform-table-column-responsive.directive.ts
libs/platform/src/lib/table/directives/table-cell.directive.ts
libs/platform/src/lib/table/interfaces/column-responsive-state.interface.ts
libs/platform/src/lib/table/interfaces/index.ts
libs/platform/src/lib/table/public_api.ts
libs/platform/src/lib/table/table-responsive.service.spec.ts
libs/platform/src/lib/table/table-responsive.service.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/table/table.module.ts
libs/platform/src/lib/table/table.service.ts
libs/platform/src/lib/table/table.ts

closes #8467 closes #8371
* Added `PlatformTableColumnResponsiveDirective`
* Added `TableResponsiveService`
* Added example of responsive platform table columns
`PlatformTableColumnResponsiveDirective` controls which state should each column has. Whether it's visible or hidden or pop-in.
-   [x] …

feat(platform): responsive table columns

---

libs/core/src/lib/table/table.component.ts

Missed a PR comment https://github.com/SAP/fundamental-ngx/pull/8562#discussion_r947484977

fix(core): table arrow prevent default

---

apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html

Small fix on the table sorting example from defect hunting 
Part of https://github.com/SAP/fundamental-ngx/issues/8423

fix(core): table sorting example fix

---

libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html

fix(core): allow click of entire separator in flexible column layout

---

apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.html
apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.ts
apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.html
apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.ts
libs/core/src/lib/avatar/avatar.component.ts

fix(core): avatar group defect hunting

---

apps/docs/src/app/core/component-docs/alert/alert-docs.component.html
apps/docs/src/app/core/component-docs/alert/alert-docs.component.ts
apps/docs/src/app/core/component-docs/alert/examples/alert-inline-example.component.html
apps/docs/src/app/core/component-docs/alert/examples/alert-inline-example.component.ts

closes #6405 
1. Updated alert playground and inline alert to handle on page-load alert dismiss and alert open on button click only.

fix(docs): alert playground and Inline alert - on page-load alert dismiss

---

libs/core/src/lib/breadcrumb/breadcrumb-item.component.ts
libs/core/src/lib/breadcrumb/breadcrumb.component.ts

fix(core): breadcrumb overflow click

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.spec.ts
libs/platform/src/lib/table/table.component.ts

closes #8597 
closes #8603 
Issue was wrong index number was passing while we click on checkbox because of which other row was getting selected while we select one particular row.
I changed the selected index of the items of the tree table and passed the correct index.
-   [x] check for console logs …

fix(platform): fix random selection of table checkbox

---

apps/docs/src/app/core/component-docs/tabs/examples/default-tab/default-tab-example.component.html
apps/docs/src/app/core/component-docs/tabs/examples/default-tab/default-tab-example.component.ts
apps/docs/src/app/core/component-docs/tabs/examples/index.ts
apps/docs/src/app/core/component-docs/tabs/tabs-docs.component.html
apps/docs/src/app/core/component-docs/tabs/tabs-docs.component.ts
e2e/wdio/core/pages/tabs.po.ts
e2e/wdio/core/tests/dynamic-page.e2e-spec.ts
e2e/wdio/core/tests/tabs.e2e-spec.ts
libs/core/src/lib/tabs/tab-list.component.html
libs/core/src/lib/tabs/tab-list.component.ts
libs/core/src/lib/tabs/tab-panel/tab-panel.component.ts
libs/core/src/lib/tabs/tab-utils/tab-info.class.ts

Refers to DXP.
* `defaultTab` input property to be able to specify the default tab.
* `selectDefaultOnTabsChange` input property to be able to control tab selection behavior on tabs change.

feat(core): tabs defaultTab and selectDefaultOnTabsChange

---

libs/core/src/lib/select/select.component.ts

fix(core): focus select control on escape press

---

libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts

fix(platform): scroll to end of tokenizer when adding tokens

---

libs/core/src/lib/list/list.component.ts
libs/core/src/lib/utils/services/keyboard-support/keyboard-support.service.ts

closes #8687 
Removed list focus trap on tab key.

fix(core): remove list focus trap

---

libs/core/src/lib/time/time-column/time-column.component.ts

closes #5645 
Added time input via keyboard.

feat(core): add time selection using keyboard

---

libs/core/src/lib/list/directives/list-group-header.directive.ts

part of #8397 
Removed focus from list header.

fix(core): remove list-header focus

---

.github/actions/npm-publish/index.js

I forgot to remove these when updated CI pipelines. It was for working locally and testing those scripts without publishing

fix(ci): removed npm publish script hardcodes and dry-run

---

libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/input-group/input-group.component.ts
libs/core/src/lib/multi-input/multi-input.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/8398
Core multi-input focusing issue.

fix(core): multi input focusing

---

.github/workflows/on-schedule.yml

closes none
Rewrote scheduled CI workflow to use cloud and distributed executions

chore(ci): scheduled ci run update

---

libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.html

fix(docs): documentation sorting

---

libs/core/src/lib/list/list-component.interface.ts
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.ts

Part of #8557 
1. Added arrow key navigation. (Not for condensed mode)
2. Added list expansion using Arrow, Space & Enter key.

fix(core): key navigation in vertical navigation

---

apps/docs/src/styles.scss

fix(docs): fix home page color issue for dark themes

---

libs/core/src/lib/scrollbar/scrollbar.component.ts

part of #8557 
Solves [this](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215412466): Added arrow key control to scrollbar.

fix(core): add key control to scrollbar

---

libs/core/src/lib/list/list-component.interface.ts
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.html
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.ts

closes #8761 
Added arrow key navigation to vertical navigation.

fix(core): add keyboard support to condensed mode of vertical navigation

---

libs/docs/core/checkbox/e2e/checkbox.e2e-spec.ts
libs/docs/core/dialog/e2e/dialog.e2e-spec.ts
libs/docs/core/feed-input/e2e/feed-input.e2e-spec.ts
libs/docs/core/list/e2e/standard-list.e2e-spec.ts
libs/docs/core/menu/e2e/menu.e2e-spec.ts
libs/docs/core/product-switch/e2e/product-switch.e2e-spec.ts
libs/docs/platform/date-picker/e2e/date-picker.e2e-spec.ts
libs/docs/platform/datetime-picker/e2e/datetime-picker.e2e-spec.ts
libs/docs/platform/dynamic-page/e2e/dynamic-page.e2e-spec.ts
libs/docs/platform/feed-input/e2e/feed-input.e2e-spec.ts
libs/docs/platform/info-label/e2e/info-label.e2e-spec.ts
libs/docs/platform/list/e2e/list.e2e-spec.ts
libs/docs/platform/panel/e2e/panel.e2e-spec.ts
libs/docs/platform/switch/e2e/switch.e2e-spec.ts

remove e2e tests that check hardcoded colors

test(core,platform): remove e2e tests that check hardcoded colors

---

CHANGELOG.md
package.json

chore(release): version 0.36.1 build [ci skip]

---

.github/actions/bump-styles-version/action.yml
.github/actions/bump-styles-version/index.js
.github/actions/nodejs/action.yml
.github/workflows/bump-styles.yml

Closes none.
Added workflow to automatically bump styles version every 2 days.

feat(core,platform): automatically bump styles version

---

.github/actions/nodejs/action.yml

fix(core,platform): typo in workflow
