SAP/fundamental-ngx

docs/modules/documentation/containers/modal/modal-docs.component.ts, docs/modules/documentation/documentation.module.ts, package-lock.json, package.json
#13 
Enhancement
The documentation application should import components directly from the library source, so that anyone developing components can see their changes reflected in the demo application running locally without having to build the library with each change
=> docs: documentation should import components from library source (#13)

package.json
Yes
#49 
Enhancement
Needed npm scripts for building and deploying the fundamental-ngx npm library as well as the GitHub Pages documentation site
=> build: adds build scripts for docs and library to package.json

docs/modules/documentation/containers/alert/alert-docs.component.html, docs/modules/documentation/containers/alert/alert-docs.component.ts, docs/modules/documentation/containers/badge-label/badge-label-docs.component.ts, docs/modules/documentation/containers/button-group/button-group-docs.component.ts, docs/modules/documentation/containers/button/button-docs.component.ts, docs/modules/documentation/containers/dropdown/dropdown-docs.component.ts, docs/modules/documentation/containers/icon/icon-docs.component.ts, docs/modules/documentation/containers/identifier/identifier-docs.component.ts, docs/modules/documentation/containers/tile/tile-docs.component.ts
#7 
Enhancement
Empty select options for component attributes should say 'default'
=> docs: add "default" option on selects

docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html, docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.ts, projects/fundamental-ngx/src/lib/breadcrumb/breadcrumb-item.component.html, projects/fundamental-ngx/src/lib/breadcrumb/breadcrumb-item.component.ts
#57 
Enhancement/refactor
Refactored the breadcrumb component.  User now provides breadcrumb text inside the <fd-breadcrumb-item> tags rather than as input [text]
=> refactor: breadcrumb text should be ng-content, not @Input()

docs/styles.scss, projects/fundamental-ngx/src/lib/breadcrumb/breadcrumb-item.component.html
#68 
Previously we were using only spans for the breadcrumb input, and conditionally applying the link class depending on whether or not the user provided a url.  However the fundamental-ui only applies the styling to anchors, so we had to hardcode the styling on spans.  No longer the case with this PR
=> fix: breadcrumb links now styled correctly

projects/fundamental-ngx/src/lib/dropdown/dropdown.component.html, projects/fundamental-ngx/src/lib/dropdown/dropdown.component.ts
#65 
Using (blur) to close the dropdown causes some undesirable effects. If the user clicks and holds one of the selectable options (rather than a quick click), the dropdown perceives this as a blur event and closes the dropdown, and the option the user clicks on does not register as a click.
Also, clicking the main button on an expanded dropdown should close it.
=> fix: better handling of dropdown open/close

projects/fundamental-ngx/src/lib/dropdown/dropdown.component.html
Resolves #109 
The dropdown was duplicating the id for the fd-dropdown element and the nav child. Instead of using the same id it now appends '--items' to maintain id uniqueness.
The '--items' refers to the 'fd-dropdown-item' (s) nested in the nav element.
=> Fix dropdown duplicate id usage

docs/modules/documentation/containers/button/button-docs.component.html, docs/modules/documentation/containers/icon/icon-docs.component.html, docs/modules/documentation/containers/image/image-docs.component.html, projects/fundamental-ngx/src/lib/icon/icon.directive.ts
#167 
allow `button`, `fd-icon`, `fd-image` to be extensible. Updated the documentation
yes
=> #167 allow and document button, icon, and image to be extensible

docs/modules/documentation/containers/table/table-docs.component.html, docs/modules/documentation/containers/table/table-docs.component.ts, projects/fundamental-ngx/src/lib/table/table.component.html, projects/fundamental-ngx/src/lib/table/table.component.ts
#196 
allow `fd-table` to accept custom column width
by default(if no custom widths are passed) the columns will take equal space. In case custom values are passed then the columns will take those values. Example:
`
<fd-table [tableData]="tableData"
[headers]="headers"
[headerWidths]="headerWidths">
</fd-table>
`
the format of that input `headerWidths` is string[]. Example:
`
headerWidths: string[] = ['10%', '30%', '20%', '20px', '20px'];
`
=> #196 allow table columns to have custom width

docs/modules/documentation/containers/panel/panel-docs.component.html, projects/fundamental-ngx/src/lib/panel/panel.component.html, projects/fundamental-ngx/src/lib/panel/panel.component.ts
So you can add inline styles to a panel like so: `<fd-panel style="color: blue;">` to change the text color of the panel to blue.  However, I was unable to change the background (color, image, etc) in this manner.  Any ideas why?  In this pull request I expose a backgroundImage input on the popover component to get around this issue.
=> add input for panel background image

docs/modules/documentation/containers/calendar/calendar-docs.component.html, docs/modules/documentation/containers/calendar/calendar-docs.component.ts, docs/modules/documentation/containers/calendar/examples/calendar-monday-start-example.component.ts, docs/modules/documentation/documentation.module.ts, library/src/lib/calendar/calendar.component.ts
=> add option for calendar weeks to start on Monday instead of Sunday

README.md
None
ReadMe npm badge was linking to the actual image, which we don't want obviously.
=> Added proper npm link to readme

.travis.yml, package.json
Fundamental-react Travis builds were failing all day due to a coveralls report error. This is a known recurring issue on their end:
[lemurheavy/coveralls-public#1264](https://github.com/lemurheavy/coveralls-public/issues/1264)
This is the same method we used to fix the failure in fundamental-react, see: https://github.com/SAP/fundamental-react/pull/417
The travis build will still fail if any tests fail, but will not fail the build if the coverage cannot be reported to coveralls.
=> fix: temporary fix for coveralls failures

docs/modules/documentation/containers/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.html, docs/modules/documentation/containers/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.ts, docs/modules/documentation/containers/multi-input/multi-input-docs.component.html, library/src/lib/multi-input/multi-input.component.html, library/src/lib/multi-input/multi-input.component.spec.ts, library/src/lib/multi-input/multi-input.component.ts
Allows users to provide a displayFn function, which then handles the display. With this method, users can display the text however they like. Pretty flexible compared to the previous [displayWith] property that only allowed 1-level deep object support.
=> multi-input better object support

CHANGELOG.md, library/package-lock.json, library/package.json
fixes #572 
fundamental-bot's admin rights have been reinstated, we need to manually bump the version because of the where the failure occurred in the travis script. version 0.2.0-rc.9 was published to npm, but the changes were not pushed back to the repo.
=> chore: manual upgrade for bug fix

docs/modules/documentation/components/example-background/example-background.component.ts, docs/modules/documentation/containers/toggle/examples/toggle-binding-example/toggle-binding-example.component.html, docs/modules/documentation/containers/toggle/toggle-docs.component.html, library/src/lib/toggle/toggle.component.spec.ts, library/src/lib/toggle/toggle.component.ts
fixes #582 
Exposed the checked property and added checkedChange event for two-way binding without FormsModule.
yes
=> fix: toggle no longer requires FormsModule

library/src/lib/calendar/calendar.component.ts, library/src/lib/date-picker/date-picker.component.ts, library/src/lib/input-group/input-group.component.ts, library/src/lib/list/list-item.component.ts, library/src/lib/menu/menu-group.component.ts, library/src/lib/menu/menu.component.ts, library/src/lib/panel/panel-actions.component.ts, library/src/lib/panel/panel-body.component.ts, library/src/lib/panel/panel-filters.component.ts, library/src/lib/panel/panel-footer.component.ts, library/src/lib/panel/panel-head.component.ts, library/src/lib/panel/panel-header.component.ts, library/src/lib/panel/panel.component.ts
fixes #609 
Not sure why that wasn't working with custom classes. I think behaviour with this changed between Angular versions and the docs never reflected it. Using @HostBinding is a more modern approach to this anyways.
Fixed:
Calendar
Datepicker
InputGroup
Menu
List
Panel
=> fix: classes no longer overriden by custom classes for some components

ci-scripts/publish.sh
n/a
It was found in the `fundamental` repo that the calls to GitHub API to build the release notes _could_ happen prior to the commits being pushed (or updated within GitHub).  To help ensure this works, I have moved the create release call below publish.
n/a
=> chore: Release notes

docs/modules/documentation/containers/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.ts, library/src/lib/multi-input/multi-input.component.html, library/src/lib/multi-input/multi-input.component.scss
fixes #650 
The maxHeight property had broken with our migration to Popper.js.
=> fix: fixed maxHeight multi-input property

docs/modules/documentation/containers/tabs/tabs-docs.component.html
#698 
Just fixes an example number. My bad for forgetting to change it earlier.
Now that I think about it, it'd be nice to remove this dependency on an example number 🤔
=> fix: fixed missed example number in tab docs

library/src/lib/time-picker/time-picker.component.ts, package-lock.json
=> docs: new docs for timepicker

library/src/lib/popover/popover.component.spec.ts, library/src/lib/popover/popover.component.ts, library/src/lib/popover/popover.module.ts
=> fix: Provide HashService in popover

library/src/lib/toggle/toggle.component.ts
closes #763 
For some reason we didn't implement the disabled state for the toggle used as a form
=> fix: support form-disabled toggle

docs/fd-typedoc-theme/helpers/main.helpers.js, docs/fd-typedoc-theme/partials/comment.hbs, docs/fd-typedoc-theme/partials/member.hbs, docs/fd-typedoc-theme/partials/members.group.hbs, docs/fd-typedoc-theme/partials/members.hbs, docs/styles.scss, library/src/lib/alert/alert.component.ts, library/src/lib/badge-label/badge.component.ts, library/src/lib/badge-label/label.component.ts, library/src/lib/button/button.directive.ts, library/src/lib/file-input/directives/file-dragndrop.directive.ts, library/src/lib/file-input/directives/file-select.directive.ts, library/src/lib/file-input/file-input.component.ts, library/src/lib/multi-input/multi-input.component.ts, library/src/lib/popover/popover-directive/popover.directive.ts, library/src/lib/popover/popover.component.ts, library/src/lib/search-input/search-input.component.ts, library/src/lib/tabs/tab-list.component.ts, package.json
- Separates API properties into inputs/outputs
- Adds selector of components/directives
- Removes need for @Input/@Output in the property docs
- Adds some spacing between the markdown 'home' and the top
Basically this makes the docs better
=> docs: separated api properties into input/output

docs/modules/documentation/containers/datetime-picker/examples/datetime-non-meridian-example/datetime-non-meridian-example.component.html, docs/modules/documentation/containers/datetime-picker/examples/datetime-program-example/datetime-program-example.component.html, library/src/lib/datetime-picker/datetime-picker.component.html, library/src/lib/datetime-picker/datetime-picker.component.spec.ts, library/src/lib/datetime-picker/datetime-picker.component.ts
closes #749 
Also adds type safety, and cleans up some weird stuff that I don't remember ever seeing? Like accessing the input value directly instead of using what we have as ngModel
=> fix: added onClose event to datetime picker

library/src/lib/toggle/toggle.component.ts
[#696](https://github.com/SAP/fundamental-ngx/issues/696)
Documented Toggle component
=> docs: added toggle documentation

library/src/lib/date-picker/date-picker.component.ts, library/src/lib/datetime-picker/datetime-picker.component.ts
Bug was occurring in Safari and Firefox.
The fix is to use more conventional ways of checking for the element contents.
=> fix: fixed datetime picker global listener

docs/modules/documentation/containers/button/button-docs.component.html, docs/modules/documentation/containers/button/button-docs.component.ts, docs/modules/documentation/containers/button/examples/button-examples.component.ts, docs/modules/documentation/containers/button/examples/button-state-example.component.html, library/src/lib/button/button.directive.spec.ts, library/src/lib/button/button.directive.ts
[#740](https://github.com/SAP/fundamental-ngx/issues/740)
Removed the `state` input property from the `fd-button` directive.
=> fix: remove the state input from the fd-button

.travis.yml
This will prevent us from pushing something that doesn't build as an Angular library.
**The build for this PR will be fixed by #826. **
=> chore: add packing library to travis

docs/app/documentation/component-docs/alert/examples/alert-component-as-content-example.component.ts, library/src/lib/alert/alert-service/alert.service.ts, library/src/lib/alert/alert-utils/alert-config.ts, library/src/lib/alert/alert.component.ts
https://github.com/SAP/fundamental-ngx/issues/654
I included minimum width option to alert component which handles responsive problems. By default right now min-width is set to 300px, which means that it will look good on every device.
I put this option usage into one example
=> fix: Add min-width option on alerts with default value

library/src/lib/calendar/calendar.component.ts, library/src/lib/date-picker/date-picker.component.ts
=> docs: calendar datepicker typedocs

library/src/lib/panel/panel-grid/panel-grid.component.ts
https://github.com/SAP/fundamental-ngx/issues/864
In issue there is noticed that, basic fd-grid-panel classes dissapear, when number of columns is changed 
Not needed.
=> fix: Add removed classes while changed on grid panel

library/src/lib/tree/tree.component.ts
No issue, found the issue while using fd-tree.
When using the `<fd-tree>` without a `[header]` this part of the code throws errors because `this.header` is undefined, practically making `[header]` a mandatory attribute even if you do not need headers (currently you need to provide an empty array).
As a side note the documentation for <fd-tree> I could not find on https://sap.github.io/fundamental-ngx/home.
=> fix: fd-tree throwing error when used without header

docs/app/documentation/component-docs/toggle/examples/toggle-form-example/toggle-forms-example.component.html, docs/app/documentation/component-docs/toggle/examples/toggle-form-example/toggle-forms-example.component.ts, docs/app/documentation/component-docs/toggle/toggle-docs.component.html, docs/app/documentation/component-docs/toggle/toggle-docs.component.ts, docs/app/documentation/documentation.module.ts
#677 
Adds another example to the fd-toggle component in the documentation (using angular reactive forms)
Not necessary
=> docs: added an example to the fd-toggle docs (using reactive forms)

docs/app/documentation/component-docs/datetime-picker/datetime-picker-docs.component.html, docs/app/documentation/component-docs/datetime-picker/datetime-picker-docs.component.ts, docs/app/documentation/component-docs/datetime-picker/examples/datetime-format-example/datetime-format-example.component.html, docs/app/documentation/component-docs/datetime-picker/examples/datetime-format-example/datetime-format-example.component.ts, docs/app/documentation/documentation.module.ts, library/src/lib/datetime-picker/datetime-picker.component.ts, library/src/lib/datetime-picker/format/datetime-parser.ts
fixes https://github.com/SAP/fundamental-ngx/issues/804
I added possibility to put custom formatting for datetime picker
Added 1 example with usage.
=> fix: add custom formatting to datetime picker

library/src/lib/calendar/calendar.component.ts, library/src/lib/popover/popover.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/947
I added id inputs for calendar and popover to allow user putting custom ids 
-
=> fix: Add Input id on calendar and popover to allow custom

library/src/lib/calendar/calendar.component.ts
fixes #855 
Fixed bug where if the 31st day of the month is selected and the user clicks the next month button, and the next month has fewer than 31 days, the next month will be skipped and the one after that will be displayed.  So for example if Jan 31 is selected and the next month button is clicked, March will be displayed.
=> fix: month gets skipped when the current date is the 31st and the user clicks next month button

README.md, angular.json, library/package.json, package-lock.json, package.json
closes #880 
Migrates our documentation to fundamental-styles and also adds the new repo to the peer dependencies of the lib. Note that fiori-fundamental is still compatible with fundamental-ngx, but that may eventually change so migrating now is encouraged.
=> chore: fundamental-styles migration

docs/app/documentation/component-docs/dropdown/examples/dropdown-default-example.component.html, docs/app/documentation/component-docs/dropdown/examples/dropdown-icons-example.component.html, docs/app/documentation/component-docs/dropdown/examples/dropdown-infinite-scroll-example.component.html, docs/app/documentation/component-docs/dropdown/examples/dropdown-state-example.component.html, docs/app/documentation/component-docs/dropdown/examples/dropdown-toolbar-example.component.html, docs/app/documentation/core-helpers/api/api.component.html, library/src/lib/calendar/calendar.component.ts, library/src/lib/datetime-picker/datetime-picker.component.html, library/src/lib/popover/popover-dropdown/popover-dropdown.component.html, library/src/lib/popover/popover-dropdown/popover-dropdown.component.spec.ts, library/src/lib/popover/popover-dropdown/popover-dropdown.component.ts, library/src/lib/popover/popover.component.html, library/src/lib/popover/popover.component.ts, library/src/lib/popover/popover.module.ts, library/src/lib/time/time.component.ts
https://github.com/SAP/fundamental-ngx/issues/771
I added popover-dropdown component and removed isDateTimePicker from time component,
changed input flag on calendar component to make it more clear.
I changed documentation due to dropdown changes.
=> fix: remove isComponent

docs/app/documentation/component-docs/combobox-input/combobox-input-header/combobox-input-header.component.html, docs/app/documentation/component-docs/combobox-input/examples/combobox-input-example.component.html, library/src/lib/combobox-input/combobox-input.component.html, library/src/lib/combobox-input/combobox-input.component.ts
fixes https://github.com/SAP/fundamental-ngx/issues/965
I added the way to hide `new item` element by checking if there is any observers on `newItemClicked` event
I added example to documentation
=> fix: combobox input add way to hide new item

library/src/lib/multi-input/multi-input.component.spec.ts, library/src/lib/multi-input/multi-input.component.ts
https://github.com/SAP/fundamental-ngx/issues/995
Fundamental components are dependant on Popper. Popper's update function is not called while user types. This leads to described bug.
no need, documentation will display dropdown correctly post merge
=> fix: fd-multi-input does not update its position upon typing

docs/app/documentation/component-docs/inline-help/examples/inline-help-example.component.html, docs/app/documentation/component-docs/inline-help/examples/inline-help-examples.component.ts, docs/app/documentation/component-docs/inline-help/examples/inline-help-trigger-example.component.html, docs/app/documentation/component-docs/inline-help/inline-help-docs.component.html, docs/app/documentation/component-docs/inline-help/inline-help-docs.component.ts, docs/app/documentation/component-docs/inline-help/inline-help-header/inline-help-header.component.html, docs/app/documentation/documentation.module.ts, library/src/lib/badge-label/badge.directive.ts, library/src/lib/badge-label/label.directive.ts, library/src/lib/inline-help/inline-help.component.html, library/src/lib/inline-help/inline-help.component.scss, library/src/lib/inline-help/inline-help.component.spec.ts, library/src/lib/inline-help/inline-help.component.ts, library/src/lib/inline-help/inline-help.module.ts
fixes https://github.com/SAP/fundamental-ngx/issues/620
I made inline help component using popover component inside, the popover control contains only the help icon. I adde dalso possibility to change trigger event. Had to put some styles, cause popover for example already got some borders/positions. I added also some styles which simulates the fact that the inline help component is always hovered, cause right now popover is controlling view.
I added one example.
=> fix: make inline help component using popover component

docs/app/documentation/component-docs/icon/examples/icon-example.component.html, docs/app/documentation/component-docs/icon/examples/icon-example.component.ts, docs/app/documentation/utilities/api-files.ts, library/src/lib/icon/icon.component.spec.ts, library/src/lib/icon/icon.component.ts, library/src/lib/icon/icon.module.ts
fixes https://github.com/SAP/fundamental-ngx/issues/890
I changed icon directive to component and added some tests. Also tried to add support for adding icon name inside component brackets, but it's hard to deal with it on any changes. Other libraries got different system, where font-style interpretate whole words as a icons.
-
=> fix: Change icon to component, add tests

library/src/lib/menu/menu-list.directive.ts
fd-menu-list directive was attaching to the host `fd-menu_list` class. The correct class from Fundamental-styles is `fd-menu__list`.
=> fix: adds the correct class for fd-menu-list

library/src/lib/time-picker/time-picker.component.html, library/src/lib/time-picker/time-picker.component.spec.ts, library/src/lib/time-picker/time-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/913
I removed stopPropagation() for click event on time picker icon. 
-
=> fix: Close time picker on another open click

library/src/lib/alert/alert.component.ts
fixes #1066 
We were not adding the `fd-alert--dismissible` class to the component which was causing the overlapping of the content of the alert with the dismissible button. 
`fd-alert--dismissible` class adds an additional `padding-right: 48px` which prevents the overlapping.
BEFORE:
AFTER:
=> fix: adds missing fd-alert--dismissible class

library/src/lib/combobox/combobox.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/912
I put tabindex to -1, to prevent from focusing on combobox dropdown icon.
=> fix: Make combobox dropdown trigger unfocusable

docs/app/documentation/component-docs/calendar/examples/calendar-single-example.component.ts, library/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, library/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html, library/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts, library/src/lib/calendar/calendar.component.scss, library/src/lib/calendar/calendar.component.ts, library/src/lib/calendar/calendar.service.ts, library/src/lib/calendar/models/fd-date.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1068
Issues with focus has been fixed. 
Right now:
- Shift tab escapes the focus on all views (that's how it's supposed to be)
- Tab doesn't escape the focus, by default.
- After changing month/year the active(selected > today > first) day is focused
- When year list is switched (+/- 12), it's possible to focus on active(selected > today > first) year, by tab key.
- Also added some statements which will provide protection from `undefined is not an object/function` errors.
=> fix: improved focus on calendar

docs/app/documentation/component-docs/button/button-docs.component.html, docs/app/documentation/component-docs/calendar/calendar-docs.component.html, docs/app/documentation/component-docs/calendar/examples/calendar-single-example.component.ts
closes#1091
- Made blocked date on calendar match current month and year
- added a short description for disabled and blocked date 
- fixed small typo in button
=> docs: made blocked date dynamic + add description + fix small typo

docs/app/documentation/component-docs/shellbar/examples/shellbar-basic-example.component.html, library/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html, library/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1099
I added option to declare, if popover should be closed on shellbar actions component.
Bigger refactor will be pushed soon.
-
=> fix: Add option about closing popup on selecting option

library/package.json
For some reason the build errors with the latest merge. Not sure why but it seems like downgrading from 6.5.2 does the trick.
=> fix: downgrade rxjs

.github/mergeable.yml
Small edit to mergeable file to move `or` to the beginning so it doesn't require 2 approvals AND one of the listed reviewers.
Edited title regex to allow dependabot pr's to pass `chore(` versus `chore:`
=> chore: edit mergeable

docs/app/documentation/component-docs/action-bar/action-bar-docs.component.html, docs/app/documentation/component-docs/action-bar/action-bar-docs.component.ts, docs/app/documentation/component-docs/action-bar/examples/action-bar-examples.component.ts, docs/app/documentation/component-docs/action-bar/examples/action-bar-long-string-title-truncation-example.component.html, docs/app/documentation/documentation.module.ts
https://github.com/SAP/fundamental-styles/issues/237
Added an example to demonstrate the truncation long string title in the action bar.
No
=> docs: added long string title truncation code example.

docs/app/documentation/component-docs/action-bar/examples/action-bar-back-example.component.html, docs/app/documentation/component-docs/action-bar/examples/action-bar-long-string-title-truncation-example.component.html, docs/app/documentation/component-docs/action-bar/examples/action-bar-no-back-example.component.html, library/src/lib/action-bar/action-bar-description/action-bar-description.directive.spec.ts, library/src/lib/action-bar/action-bar-description/action-bar-description.directive.ts
fixes #1126 
[#1126 ](https://github.com/SAP/fundamental-ngx/issues/1126)
- `action-bar-description` directive was not attaching the `fd-action-bar__description` class to the host element. 
- updated the test for this directive
- updated the `Action bar with long page title` example in the documentation with a very long description text
- updated the placement of the actions in the documentation to follow the design guidelines (`Cancel` btn should be of type `light` and after the main action)
=> fix: adds missing class for Action Bar description, updates the tests, updates the documentation

docs/app/documentation/component-docs/calendar/calendar-docs.component.html, docs/app/documentation/component-docs/time-picker/examples/time-picker-examples.component.ts, docs/app/documentation/component-docs/time-picker/examples/time-picker-only-hours-example.component.html, docs/app/documentation/component-docs/time-picker/time-picker-docs.component.html, docs/app/documentation/component-docs/time-picker/time-picker-docs.component.ts, docs/app/documentation/component-docs/time/examples/time-examples.component.ts, docs/app/documentation/component-docs/time/examples/time-only-hours-example.component.html, docs/app/documentation/component-docs/time/time-docs.component.html, docs/app/documentation/component-docs/time/time-docs.component.ts, docs/app/documentation/documentation.module.ts, library/src/lib/datetime-picker/datetime-picker.component.html, library/src/lib/datetime-picker/datetime-picker.component.ts, library/src/lib/time-picker/time-picker.component.html, library/src/lib/time-picker/time-picker.component.ts, library/src/lib/time/time.component.html, library/src/lib/time/time.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1084
I added `displayMinutes` option to time, timePicker, datetimePicker component, which controls the display of minuts input.
The documentation is updated by 2 examples on timePicker and time components.
=> fix: Add displayMinutes option to time component

docs/app/documentation/component-docs/date-picker/examples/date-picker-i18n-example.component.ts, library/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, library/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html, library/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.spec.ts, library/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.ts, library/src/lib/calendar/i18n/calendar-i18n.ts
fixes #1140 build the fields after a new locale is being applied
add a localization examples for the calendar(3 languages)
=> fix: datepicker update all fields after changing the locale

docs/app/documentation/component-docs/date-picker/examples/date-picker-i18n-example.component.ts, library/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts, library/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, library/src/lib/calendar/calendar.component.ts, library/src/lib/date-picker/date-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1141
I made datepicker and calendar first day consistent, the bug was caused by the fact that on datepicker the sunday was marked as a 0 number and on calendar as a 1. Right now sunday is marked as 1 everywhere.
=> fix: first day issues

docs/app/documentation/component-docs/shellbar/examples/shellbar-collapsible-example.component.html, library/src/lib/shellbar/product-menu/product-menu.component.html, library/src/lib/shellbar/product-menu/product-menu.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1146
I added option to automatically close popover on product menu component in shellbar, when item is chosen.
=> fix: Add option to close popover product menu in shellbar on choose

docs/app/documentation/component-docs/menu/examples/menu-examples.component.ts, docs/app/documentation/component-docs/menu/examples/menu-separator-example.component.html, docs/app/documentation/component-docs/menu/menu-docs.component.html, docs/app/documentation/component-docs/menu/menu-docs.component.ts, docs/app/documentation/documentation.module.ts, library/src/lib/menu/menu-list.directive.ts, library/src/lib/menu/menu.component.scss, library/src/lib/menu/menu.component.ts
#1133 
Added optional separator line to menu list items. On fd-menu tag, use **[separator] = "true"** to get the line separator on the list items.
Yes.
=> fix: added optional separator line to menu list items

library/src/lib/combobox/combobox.component.html, library/src/lib/combobox/combobox.component.spec.ts, library/src/lib/combobox/combobox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1170
I added focus-tap library to combobox. Right now focus trap is activated, when the popover body is open. I also added triggers input, to combobox, which is passed to popover. It can be handy, when someone want's to change or remove events that open/close the popover body inside combobox.
=> fix: Add focus trap to combobox

library/src/lib/alert/alert.component.ts
Protractor waits until an Alert disappears before proceeding to next line.
Example case:
inside e2e test
```     
showAlert({message: 'sample message', duration: 5000});
closeAlertByIndex(0);
```
Protractor will wait until "setTimeout" is resolved before calling next line "closeAlertByIndex(0)" which will result in error because the Close Button cannot be found.
According to docs
> Protractor will wait until the Angular Zone stabilizes. This means long running async operations will block your test from continuing. To work around this, run these tasks outside the Angular zone
I've tried the `browser.waitForAngularEnabled(false)` but it's not deterministic. Sometimes it works, sometimes it doesn't.
I've also tried to wrap `alertService.open()` method call into …
=> fix: Protractor no longer waits for Alert timeout to be resolved

docs/app/documentation/component-docs/select/examples/select-height/select-max-height-example.component.html, docs/app/documentation/component-docs/select/examples/select-height/select-max-height-example.component.ts, docs/app/documentation/component-docs/select/examples/select-nested-options/select-nested-options.component.html, docs/app/documentation/component-docs/select/select-docs.component.html, docs/app/documentation/component-docs/select/select-docs.component.ts, docs/app/documentation/documentation.module.ts, library/src/lib/select/select.component.html, library/src/lib/select/select.component.scss, library/src/lib/select/select.component.ts
https://github.com/SAP/fundamental-ngx/issues/1166
I added `maxHeight` input on a select component and also the default `maxHeight`, to prevent popover body from hiding. 
Added 1 example of maxHeight usage
=> feat: Added maxHeight to select component

docs/app/documentation/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.html, docs/app/documentation/component-docs/multi-input/examples/multi-input-example/multi-input-example.component.ts, library/src/lib/multi-input/multi-input.component.html, library/src/lib/token/token.component.scss, library/src/lib/token/token.component.ts
fixes #1204 
- Introduce input for disabled `token`
- fix an issue with disabled `multi input` when the user is able to remove an item
=> feat: introduce disabled token and fix disabled multi input

library/src/lib/datetime-picker/datetime-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1201
Right now, when there is no date and time is picked, date is automatically changed to Today date.
=> fix: Datetime picker crash

docs/app/documentation/component-docs/combobox/combobox-docs.component.html, docs/app/documentation/component-docs/combobox/combobox-docs.component.ts, docs/app/documentation/component-docs/combobox/examples/combobox-forms-example.component.html, docs/app/documentation/component-docs/combobox/examples/combobox-forms-example.component.ts, docs/app/documentation/documentation.module.ts, library/src/lib/combobox/combobox.component.spec.ts, library/src/lib/combobox/combobox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1075
I added dropdown mode to combobox component, thanks to it component can communicate with the outside not only by strings, but with whole objects that are passed as a options.  
I added new example with reactive forms and usages of 2 combobox components, to compare enabled and disabled dropdown mode.
=> feat: added option in combobox to return whole object; added forms example

library/src/lib/date-picker/date-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1213
So since now date picker reset input field, when the value passed by ValueController(ngModel, RectiveForms) is wrong.
=> fix: Reset input on invalid date

docs/app/documentation/component-docs/input/examples/input-form-group-example.component.scss, docs/app/documentation/component-docs/input/input-docs.component.html, docs/app/documentation/core-helpers/docs-section-title/docs-section-title.component.scss, docs/app/documentation/core-helpers/docs-section-title/docs-section-title.component.ts, docs/app/documentation/documentation.module.ts, docs/styles.scss
#1182
Added link before header title for easy navigate. 
There is also new component named `fd-docs-section-title`, which is used to add titles before section, we should refactor whole docs page in future.
Only input group component updated so far.
=> docs: Links on Input docs component sections

docs/app/documentation/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html, docs/app/documentation/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts, docs/app/documentation/component-docs/popover/popover-docs.component.html, docs/app/documentation/component-docs/popover/popover-docs.component.ts, docs/app/documentation/documentation.module.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1125
I added one example of `updatePopover()` method in popover, to refresh positioning of popover, when the height of body is changed.
There is one example
=> docs: Add example of dynamic height popover body

apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-button-example.component.html, apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-icon-example.component.html, apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-text-compact-example.component.html, apps/docs/src/app/documentation/component-docs/input-group/examples/input-group-text-example.component.html, libs/core/src/lib/list/list-checkbox.component.html, libs/core/src/lib/toggle/toggle.component.html
closes #1191 
[#1191 ](https://github.com/SAP/fundamental-ngx/issues/1191)
In some examples in the documentation the labels were using `class="fd-form__label"` instead of the directive  `fd-form-label`.
=> docs: replaces the occurrence of fd-form__label class with fd-form-label directive

libs/core/src/lib/multi-input/multi-input.component.html
as selections of multi-input is using innerHtml with which i can wrap a new line to my selections. Actually the display of selected items should have the same behavior of the selection items.
fixes #1233 
change the way of showing selected items made it following the same behavior of the selection items
=> feat:change the way of showing selected items of multi-input selector

libs/platform/src/lib/platform.module.ts
Fixes #1273 
Changed the name of the platform module from `PlatformModule` to `FundamentalNgxPlatformModule`.
=> feat(platform): Changing platform module name to "FundamentaNgxPlatformModule"

apps/docs/src/app/documentation/component-docs/shellbar/examples/shellbar-collapsible-example.component.html, libs/core/src/lib/search-input/search-input.component.html, libs/core/src/lib/select/select.component.html, libs/core/src/lib/select/select.module.ts, libs/core/src/lib/shellbar/shellbar-action/shellbar-action.component.html, libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html, libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.scss, libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts, libs/core/src/lib/shellbar/shellbar.component.html, libs/core/src/lib/shellbar/shellbar.component.scss, libs/core/src/lib/shellbar/shellbar.component.ts, libs/core/src/lib/shellbar/shellbar.module.ts, libs/core/src/lib/side-navigation/side-navigation-item/side-navigation-item.component.html, libs/core/src/lib/side-navigation/side-navigation.component.scss, libs/core/src/lib/side-navigation/side-navigation.component.ts
[#1234 ](https://github.com/SAP/fundamental-ngx/issues/1234)
I need to go back to fund-styles and bring the `fd-dropdown` styling because Select is using it. 
Then we can merge the PR. But it's OK for the review process.
=> [NOT FOR MERGE] adds self-contained styles for side navigation, shellbar and select

ci-scripts/publish.sh, ci-scripts/sync-version.sh
This corrects path in the publish script relative to the root and improve readibility of the script. 
This shoudl fix up paths as current build failed that was caused by syncup that has cd dist but never jump out
=> chore(build):Update path to the dist and improve readability of script

ci-scripts/publish.sh
For initial package 
You need to provide --access public to the initial publication to publish a scoped package because, as Linus points out, scoped packages are private and paid by default. The publish readme doesn't show any way to provide arbitrary commands to npm, so you'll likely have to do the first publish by hand, without lerna and with npm directly.
=> chore(build): Added public package for npm publish

libs/core/src/lib/select/select.component.html, libs/core/src/lib/select/select.component.scss
The control element of Select component depends on `fd-dropdown__control` class from Fundamental-styles for styling. Since Dropdown is not included in the Fundamental-styles dist folder we need to come up with a `temporary` solution and provide custom styling here in Fundamental-ngx. This `temporary` solution is necessary until we create a select control element in fund-styles and  use the styling from there.
=> adds custom styling for select control

scripts/publish-release.sh
At the moment if we try to release it check `package.json` in `/libs/core` which doesn't have any `rc-`. It gives an error:
```
Sorry, this branch is not a release candidate.
In order to publish a release, the package must be an 'rc' version.
```
=> chore: update release script

libs/core/src/lib/mega-menu/mega-menu.component.scss
Mega menu component is deprecated in Fundamental-styles and the styling is not exposed in dist folder. For this reason, as a temporary solution we are bringing the styling for Mega menu in Fund-NGX.
=> adds styling for mega menu

apps/docs/src/environments/environment.hmr.ts, apps/docs/src/environments/environment.prod.ts, apps/docs/src/environments/environment.ts
#1304 
There is not need to refer `../../libs/core/package.json'` as library
version does not hold the actual number, the root `package.json` does
=> docs: Correct version number for the docs app

ci-scripts/publish.sh
Now .RC versions counts as `latest` version, it should be prerelease instead. On CI script I check if there is pre-release, then I add prerelease tag to publish script.
=> chore: Add prerelease tag to rc

apps/docs/tsconfig.json, libs/platform/tsconfig.json, tsconfig.json
This changes on tsconfig provides detecting changes from library on `ng serve`. So if anything is changed from `libs`, the `docs` page will refresh with these changes.
=> chore: Modify tsconfig, allow detecting changes form lib

apps/docs/src/app/core/component-docs/menu/menu-docs.component.html
It's just a small typo correction in a template of the documentation app. I haven't seen an issue for it.
=> fix: fix typo meni -> menu

apps/docs/src/app/core/documentation/core-documentation.component.html, apps/docs/src/app/core/documentation/core-documentation.component.ts, apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.ts, apps/docs/src/app/platform/documentation/platform-documentation.component.html, apps/docs/src/app/platform/documentation/platform-documentation.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1389
The general section-toolbar didn't react to route change, when it's below 992. It's fixed, now when it's below 992 and the route change, side nav collapse. There is also included overlay. When user clicks on overlay, the side nav also collapse.
=> docs: Fix collapsing sidebar on platform and core

apps/docs/src/app/core/component-docs/input-group/examples/input-group-button-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-complex-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-examples.component.ts, apps/docs/src/app/core/component-docs/input-group/input-group-docs.component.html, apps/docs/src/app/core/component-docs/input-group/input-group-docs.component.ts, apps/docs/src/app/core/core-documentation.module.ts
Due to self contained adoption, we added new way to build `input group` component. The examples are added in this PR. 
One new example of usage in `input group` component.
=> docs: Add input group complex example

libs/core/src/index.ts, libs/core/src/lib/fundamental-ngx-core.module.ts, libs/core/src/lib/utils/public_api.ts
need to extend the library for the UTIL package for the platform team to use the code instead of rewriting the same.
fixes: #1269
####Please provide a link to the associated issue.
https://github.com/SAP/fundamental-ngx/issues/1269
need to extend the library for the UTIL package for the platform team to use the code instead of rewriting the same.
enhancement of existing feature
=> fix(core): expose Util package to platform

apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.html, apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.scss, apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.ts, apps/docs/src/app/core/component-docs/scroll-spy/scroll-spy-docs.component.html, apps/docs/src/app/core/core-documentation.module.ts, apps/docs/src/app/documentation/documentation.module.ts, libs/core/src/lib/scroll-spy/scroll-spy.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1446
There is added one example and one new input to scrollspy with `targetOffset`, that is measured in px.
There is 1 new example
=> fix: Add Offset in pixels to scroll spy

apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-examples.component.ts, apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-styled-example.component.html, apps/docs/src/app/core/component-docs/inline-help/inline-help-docs.component.html, apps/docs/src/app/core/component-docs/inline-help/inline-help-docs.component.ts, apps/docs/src/app/core/component-docs/popover/examples/popover-modal/popover-modal-example.component.html, apps/docs/src/app/core/core-documentation.module.ts, libs/core/src/lib/inline-help/inline-help.component.html, libs/core/src/lib/inline-help/inline-help.component.ts
**New PR to trigger deploy-preview from beginning. [Old one](https://github.com/SAP/fundamental-ngx/pull/1448)**
fixes: https://github.com/SAP/fundamental-ngx/issues/1415
Made possible to add the dynamically styling of the elements inside `inline help` component.
There is 1 new example of documentation
=> fix: Add styling options to inline help component

apps/docs/src/app/core/component-docs/modal/examples/component-as-content/modal-component-as-content-example.component.ts, apps/docs/src/app/core/component-docs/modal/examples/component-as-content/modal-content.component.ts, libs/core/src/lib/modal/modal-utils/modal-directives.ts, libs/core/src/lib/modal/modal.component.scss, libs/core/src/lib/modal/modal.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1474
I changed the way how there are added classes, when modal is generated `as component`. There is also fixed `max-height` value for whole modal. 
I added some classes to the icon element, following fundamental-styles. 
There is changed example a little bit, with height specified.
=> fix: Modal height example issues. Close icon fix.

apps/docs/src/app/core/component-docs/product-switch/examples/product-switch-dnd-example.component.ts, apps/docs/src/app/core/component-docs/product-switch/examples/product-switch-list/product-switch-list-example.component.ts, apps/docs/src/app/core/component-docs/product-switch/examples/product-switch-small-example.component.ts, apps/docs/src/app/core/component-docs/product-switch/product-switch-docs.component.html, libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.html, libs/core/src/lib/product-switch/product-switch-body/product-switch.item.ts, libs/core/src/lib/product-switch/product-switch/product-switch.component.ts, libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.ts, libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.spec.ts, libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1491
There is added one new option to product switch item which is called `stickToPosition`. Passing true value to this variable will disable element from changing it's position.
=> fix: (core) Add stick to position option

libs/core/src/lib/time-picker/format/time-parser.ts, libs/core/src/lib/time-picker/time-picker.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/1505
There was some bugs in time picker input. Regexp for seconds didn't work properly and the `keyup` event sometimes refreshed value too early.
No changes in interface.
=> fix: seconds regexp, trigger timepicker on enter/focusout

apps/docs/src/assets/README.md, libs/core/README.md
There are changed occurance of invalid `FundamentalNgxModule` name in README.
Yes
=> chore: Change FundamentalNgxModule to FundamentalNgxCoreModule in readme

libs/core/src/lib/loading-spinner/loading-spinner.component.html
Currently `aria-hidden`  behaves inconsistently across browsers.  [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute)
Solution (temporary) - replace `aria-hidden="true"` with ngIf
=> fix: loading spinner aria-hidden issue

apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.scss
The example for popover placement is broken. All control elements are situated together. 
The styling for `fd-col-#` is in `layout.css but it doesn't bring the styling to the component. We need to import the whole lib to make it work. 
Until we find the problem in Fundamental-styles we are going to use this solution.
Before:
After:
=> fix: popover-placement-example fix for the control elements

apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.component.ts, apps/docs/src/app/core/component-docs/badge-label/examples/badge-label-examples.component.scss
fixes: #1551
added the component strings for the example files in badge label
=> fix: stackblitz for badge label

apps/docs/src/app/core/component-docs/calendar/calendar-docs.component.ts, libs/core/src/lib/calendar/i18n/calendar-i18n-labels.ts, libs/core/src/lib/calendar/i18n/calendar-i18n.ts
fixes:#1544
Calendar internationalization was not working because the read only property was protected and incorrect components were being imported
=> fix: calendar not working in stackblitz

libs/platform/src/lib/components/search-input/search-input.component.spec.ts, libs/platform/src/lib/components/search-input/search-input.component.ts
Fixes: #1472
Added an if guard to suppress emit of "searchSubmit" event if the input text is empty.
=> fix(platform:search-input): Supress emit or "searchSubmit" event when input text is empty

package-lock.json, package.json
There is `@angular-devkit/build-angular": "^0.803.5` dependency moved to dev-dependency.
=> fix: Move angular-devkit to dev-dependency

apps/docs/src/app/core/core-documentation.module.ts, apps/docs/src/app/documentation/core-helpers/docs-section-title/docs-section-title.component.ts, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts, apps/docs/src/app/documentation/shared-documentation.module.ts, apps/docs/src/app/documentation/utilities/libraries.ts, apps/docs/src/app/platform/platform-documentation.module.ts, libs/core/src/lib/shellbar/product-menu/product-menu.component.scss, libs/core/src/lib/shellbar/product-menu/product-menu.component.ts
I added providers with names of libraries in our modules, to detect, on which library user currently is. Before it was calculated by checking url string.
Also there is changed switcher between libraries
=> docs: Change way how we recognize library, change switch library button

libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/file-input/file-input.component.ts, libs/core/src/lib/modal/modal.component.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/select/select.component.ts, libs/core/src/lib/time-picker/time-picker.component.ts, libs/core/src/lib/time/time.component.ts, libs/core/src/lib/toggle/toggle.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1578
Here is changed `change detection strategy: on push` on modal.
There is also added manually change detection on `setDisabledState()` method
=> fix: Remove Change Detection on push on modal and toggle

apps/docs/src/app/core/component-docs/select/examples/select-basic-example/select-basic-example.component.ts, apps/docs/src/app/core/component-docs/select/select-docs.component.html, libs/core/src/lib/select/select.component.spec.ts, libs/core/src/lib/select/select.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1597
There is added `unselectMissingOption`, to prevent removing chosen option, when option array is still not present.
=> fix: (core) Add unselectMissingOption to select component

apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.html, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.scss, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.ts, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-single-example.component.ts, apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html, apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.ts, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.html, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.scss, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts, apps/docs/src/app/core/core-documentation.module.ts, libs/core/src/lib/date-picker/date-picker.component.spec.ts, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/date-picker/format/date-parser.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/datetime-picker/format/datetime-parser.ts, libs/core/src/lib/datetime-picker/public_api.ts, libs/core/src/lib/popover/popover-directive/popover.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1388
There is added angular's date pipe, which took responsibility of formatting Date models to string.
It has no compact on default formatting/parsing, default format is the same as before.
=> feat:(core) Introduction of Angular DatePipe 

libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, libs/core/src/lib/date-picker/date-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1598
Right now I check if the input is empty and allowNull flag is added. Also there was some minor bug on datepicker, which is fixed now.
**This is only fix PR, without any new things. So no docs needs to be changed.**
=> fix: (core) DatePicker - fix form's valid flag, when allowNull

apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-form-example/multi-input-form-example.component.html, libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/menu/menu.component.scss, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.spec.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts, libs/core/src/lib/popover/popover-dropdown/popover-dropdown.component.html, libs/core/src/lib/popover/popover.component.html, libs/core/src/lib/popover/popover.component.spec.ts, libs/core/src/lib/popover/popover.component.ts, libs/core/src/lib/tabs/tab/tab-panel.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/911
I added `alt + ArrowDown` support for popovers components. Also I improved a little multi input keyboard support, Now it's possible to navigate by arrows. There was some leftover after fundamental-styles 0.2.0 adapation, which is remvoed.
=> fix: (core) Add popover new open shortcut, improve multi input keyboard support, fix visual menu focus

apps/docs/src/app/core/component-docs/input/examples/input-form-group-example.component.html, apps/docs/src/app/core/component-docs/input/examples/input-form-group-example.component.ts
fixes: #1624 
Adding the form array feature to the reactive forms example for input component
=> docs: (core) add form-array

libs/core/src/lib/shellbar/product-menu/product-menu.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1659
There was `item.callback()` method called even, when callback wasn't defined.
=> fix: Prevent from undefined error on ProductMenu

libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts, libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.spec.ts, libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.spec.ts, libs/core/src/lib/calendar/calendar.service.spec.ts, libs/core/src/lib/calendar/calendar.service.ts, libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.spec.ts, libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.ts, libs/core/src/lib/menu/menu-keyboard.service.ts, libs/core/src/lib/menu/menu.component.spec.ts, libs/core/src/lib/multi-input/multi-input.component.spec.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/nested-list/nested-list-keyboard.service.spec.ts, libs/core/src/lib/nested-list/nested-list-keyboard.service.ts, libs/core/src/lib/pagination/pagination.component.spec.ts, libs/core/src/lib/pagination/pagination.component.ts, libs/core/src/lib/popover/popover.component.spec.ts, libs/core/src/lib/popover/popover.component.ts, libs/core/src/lib/select/select.component.ts, libs/core/src/lib/tabs/tabs.service.spec.ts, libs/core/src/lib/tabs/tabs.service.ts, libs/core/src/lib/time/time.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1621
There is changed usage of detecting keyboard events. Before `event.code` was null on IE11 and Microsoft Edge. `event.key` is fully supported by all of the browsers.
**Internal change, so no need to put anything in the docs**
=> fix: (core) Change event.code to event.key

libs/core/src/lib/notification/notification-utils/default-notification/default-notification.component.html, libs/core/src/lib/notification/notification-utils/default-notification/default-notification.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1503
There is changed the way how the optional methods passed to default-notification are used. The optional functions were causing errors on compilation
=> fix: (core) Error while AOT compilation with `strictNullChecks: true`

libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1623
There is added new method `resetDisplayedValues`, which changes filtered displayedValues to all of available dropdownValues. 
=> fix: (core) Add reset displayed values method

apps/docs/src/app/core/component-docs/dropdown/dropdown-header/dropdown-header.component.html, apps/docs/src/app/core/component-docs/dropdown/examples/dropdown-icons-example.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.scss, apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.ts, apps/docs/src/app/core/component-docs/popover/popover-docs.component.html, apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts, apps/docs/src/app/core/core-documentation.module.ts, libs/core/src/lib/popover/popover-dropdown/popover-dropdown.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1654
There is marked `dropdown-popover` as a deprecated, also there is added one section presenting popover composed with `button menu`  
=> docs: (core) Add dropdown deprecated, put dropdown example into popover

apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-object-example/side-navigation-condensed-object-example.component.ts, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-object-example/side-navigation-object-example.component.ts, libs/core/package.json, libs/core/src/lib/nested-list/nested-list-model.ts, libs/core/src/lib/nested-list/nested-list.module.ts, libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.html
There is added [routerLink] to links on object-generated side navigation. 
It required to add `@angular/router` to peerDependencies.
Also there is added header to sublist and footer.
=> fix: add routerLink to sideNav Links, change example

libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts
There was some bug in parser function no tests inside DateTimePicker, it didn't force to have 2 digits, when sec/min/hour/day/month was less than 10.
=> fix: Date Time Picker tests parser

libs/platform/src/lib/components/search-input/search-input.component.html, libs/platform/src/lib/components/search-input/search-input.component.spec.ts, libs/platform/src/lib/components/search-input/search-input.component.ts
Fixes: #1637 
Adding "disabled" option for Search Input component.
=> feat(platform:search-input): Adding disabled state to search input component

libs/platform/src/lib/components/search-input/search-input.component.scss
Fixes: #1657 
After upgrade of fundamental-styles, the SCSS for the Search Input component was broken. SCSS for Search Input is updated to fix the styles.
***BEFORE:***
***AFTER:***
=> fix(platform:search-input): Fixing SCSS after fundamental-styles upgrade

apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-docs.component.html, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.html, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.ts, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-click-close-example.component.html, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-click-close-example.component.ts, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-complex-example.component.ts, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-group-example.component.ts, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-icons-example.component.html, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-icons-example.component.ts, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-separator-example.component.ts, libs/platform/src/lib/components/menu/menu-component/menu-item.component.html, libs/platform/src/lib/components/menu/menu-component/menu-item.component.scss, libs/platform/src/lib/components/menu/menu-component/menu-item.component.ts, libs/platform/src/lib/components/menu/menu-component/menu.component.ts
https://github.com/SAP/fundamental-ngx/issues/1710
Address PR #1563 comments by Frank: https://github.com/SAP/fundamental-ngx/pull/1563#issuecomment-553385144
Additionally,
1. Need to use fd-icon instead of span classes
2. Using dropdown popover with button instead of deprecated fd-dropdown-control
=> fix(platform): menu component library review fixes

libs/core/src/lib/calendar/calendar-header/calendar-header.component.html, libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html, libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html, libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.spec.ts, libs/core/src/lib/calendar/calendar-views/calendar-month-view/calendar-month-view.component.ts, libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html, libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.spec.ts, libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1536
There is changed the way how we build the calendar month and year components. Also there is changed the way how the models are generated. There is also added one missing `aria-live`
=> fix: (core) Calendar A11y - change ul/li to table with grid

libs/core/src/lib/calendar/models/fd-date.ts
Issue: #1740 
This pull request changes implementation of calculation of the next year in `FdDate.nextDay()` method. Year is now correctly calculated based on change of the month.
Cause of the bug was year calculation based on number of the moth, ignoring information about month change.
=> fix: (core:calendar) nextDay() method increasing year when used for date in January

libs/core/src/lib/alert/alert-service/alert.service.spec.ts, libs/core/src/lib/alert/alert.component.html, libs/core/src/lib/alert/alert.component.scss, libs/core/src/lib/alert/alert.component.spec.ts, libs/core/src/lib/alert/alert.module.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1758
There was changes in `styles@0.4.0` about the close button on alert component. There are new classes added. 
Due to `AbstractFdxNgClass` usage, which changes the hierarchy of classes I had to add some additional styles, to make it look the same as on styles. 
=> fix: (core:Alert) Add new button classes to alert component

libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts
There was some bugs with selected state and keyboard support, when there was created a SideNavigation from object.
Before:
After:
Screens are quite outdated (PR removing 2nd level icons are already included)
=> fix: SideNav From object - selected and keyboard func

apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-compact-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-example/side-navigation-condensed-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-object-example/side-navigation-condensed-object-example.component.ts, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-icons-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-multiple-selected-example/side-navigation-multiple-selected-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-object-example/side-navigation-object-example.component.ts, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-programmatically-example/side-navigation-programmatically-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-three-levels-example/side-navigation-three-levels-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-titles-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.html, libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.html, libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1644
There is new side navigation component usage on popover's last example.
Also during implementation I noticed that there are some files missing in popover's public_api,ts
=> docs: (core) Update popover's usage of side nav, add important files of popover to public_api.ts

libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/input-group/input-group.component.ts, libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.html, libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.ts, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/time-picker/time-picker.component.html, libs/core/src/lib/time-picker/time-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1639
There is `buttonFocusable` flag in all of the `input-group` related components 
=> fix: add ButtonFocusable flag to input-group related components

apps/docs/src/app/core/component-docs/time/examples/time-two-digits-example/time-two-digits-example.component.html, apps/docs/src/app/core/component-docs/time/examples/time-two-digits-example/time-two-digits-example.component.ts, apps/docs/src/app/core/component-docs/time/time-docs.component.html, apps/docs/src/app/core/component-docs/time/time-docs.component.ts, apps/docs/src/app/core/core-documentation.module.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/time-picker/time-picker.component.html, libs/core/src/lib/time-picker/time-picker.component.spec.ts, libs/core/src/lib/time-picker/time-picker.component.ts, libs/core/src/lib/time/time.component.html, libs/core/src/lib/time/time.component.spec.ts, libs/core/src/lib/time/time.component.ts, libs/core/src/lib/time/time.module.ts, libs/core/src/lib/utils/pipes/pipe.module.ts, libs/core/src/lib/utils/pipes/two-digits.pipe.ts, libs/core/src/lib/utils/public_api.ts
This is response for https://github.com/SAP/fundamental-ngx/issues/1796 . There was requested two digits forcing on time and time related components. So I added flag, which keeps 2 digits, by adding 0. It's disabled by default.
=> fix: Add two digits pipe to time component

libs/core/src/lib/time/time.component.html, libs/core/src/lib/time/time.component.scss
https://github.com/SAP/fundamental-ngx/issues/1811
I added prepared classes to `inputs` on time component.
Also there was `max-width` shadowed by `fd-input`, I added it on `ngx` level.
=> fix: remove spinners, add some place between inputs

apps/docs/src/app/core/component-docs/input/examples/input-example.component.html, apps/docs/src/app/core/component-docs/textarea/examples/textarea-example.component.html, libs/core/src/lib/form/form-control/form-control.directive.ts
- Input compact mode was broken
- in the documentation added : in the label of required inputs
=> fix: add fix for input compact mode

libs/core/src/lib/combobox/combobox.component.ts
https://github.com/SAP/fundamental-ngx/issues/1811
I changed the order of setting value / throwing it. Before invalid old value was thrown, 
=> fix: (combobox) - reorder event throw 

apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts, libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
#1811 
This PR fixes weird behavior of tristate checkbox in IE11, caused by IE11 not emitting change event on indeterminate state change. To fix this error I've changed the source triggering change of checkbox state from input `(change)` to label `(click)` and input `(keyup)` events.
=> fix: change checkbox state update trigger

libs/core/src/lib/modal/modal.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1869
In case of stacked modal, focusTrap library in first modal didn't allow to propagate mouse events on second modal
=> fix: Allow outside click for modal

libs/core/src/lib/side-navigation/side-navigation.module.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1910
There is added `nested-list.module` in export array of `side-nav.module`. 
=> fix: Add nested-list module export to side-nav module

apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.html, apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-no-seconds-example.component.html, apps/docs/src/app/core/component-docs/time-picker/time-picker-docs.component.html
part of [1967](https://github.com/SAP/fundamental-ngx/issues/1967)
- fixed the typo in the Time Picker example
- removed the form message from the Localization editor example
=> docs: fix the time-picker example title and removed messages from localization editor

apps/docs/src/app/core/component-docs/list/examples/list-example.component.html
[defect hunting](https://github.com/SAP/fundamental-ngx/issues/1967)
Fix the link to be a fiori/fundamentals link for styling. It is completely normal that it is blue since it is a link but at least now if it has been visited or whatever, it will be attributed to a fundamental link and not a normal anchor tag. Changing the wording in the documentation will help clarify this to users
=> docs: use link component in list example

apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.html, apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.ts
[defect hunting](https://github.com/SAP/fundamental-ngx/issues/1967)
Put the new implementation of checkboxes on table
=> docs: table checkbox

libs/core/src/lib/tabs/tab-list.component.ts
Sometimes tests are failing, because of `Attempt to use a dstroyes view`
The way how it can be fixed is to replace `detectChanges` by `markForCheck` method 
=> fix: detect change on destroyed view

apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-reactive-forms-example.component.ts
There is removed `Object.values` method usage on examples, cause it's not supported by IE11
=> docs: Replace Object.values by Object.keys in examples

apps/docs/src/app/core/components.ts, libs/core/src/lib/modal/modal.component.scss
Detect Hunting
There was unnecessary `position: absolute` on `fd-modal-custom`. For IE11 it caused some problems with centering the modal inside `flex` container.
=> fix: modal center, restore missing entryComponent

angular.json, apps/docs/tsconfig.netlify.json
Closes #1907
Ivy renderer has been disabled becaue it it throws error in IE 11
related to https://github.com/angular/angular/issues/30569
=> chore: disabled ivy on netlify till  angular 9

ci-scripts/publish.sh
There is something wrong with travis CI.
=> chore: keep messages from GitHub on CI script

libs/core/src/lib/select/select.component.html, libs/core/src/lib/select/select.component.scss
Part of #1967
Centering children with `position: absolute` using flex-box doesn't work on IE11.
Flex-box centering has been replaced with absolute centering.
=> fix: Change select loader positioning to absolute center

libs/core/src/lib/pagination/pagination-reverse.pipe.ts, libs/core/src/lib/pagination/pagination.component.html, libs/core/src/lib/pagination/pagination.component.scss, libs/core/src/lib/pagination/pagination.component.spec.ts, libs/core/src/lib/pagination/pagination.component.ts, libs/core/src/lib/pagination/pagination.module.ts, src/stories/pagination/fd-pagination.stories.ts
Closes #1967 
Simply using `dir="rtl"` won't flip the array of numbers presented in the `*ngFor`.  Here I'm using the RtlService and forcing `dir="ltr"` and reversing the array using a pipe.  This feels code-smelly so I'd love to get some other opinions
=> fix: pagination RTL idea

libs/core/src/lib/pagination/pagination.service.spec.ts, libs/core/src/lib/pagination/pagination.service.ts
#2012 
Do not add ellipses a second time when 3rd to last page is selected.
**Before:**
**After**
=> fix: remove 2nd ellipses when 3rd to last page is selected

apps/docs/src/app/platform/platform-documentation.module.ts
Closes #2020
Closes #2009
Fix for importing and declaring StackblitzService inside PlatformDocumentationModule
=> Fix: (platform) stackblitz module not declared for PlatformDocumentationModule

libs/core/src/lib/modal/modal-service/modal.service.spec.ts, libs/core/src/lib/modal/modal-service/modal.service.ts, libs/core/src/lib/modal/modal.component.scss
fixes: https://github.com/SAP/fundamental-ngx/issues/2010
`Position: Absolute` is needed to keep placement feature. I'm centering 
Results:
IE11:
All positions:
Position on IE
=> fix: Restore absolute modal position, fix ie11

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2027
There is added some workaround for IE11 and third state for checkbox.
I had to put 4th state, which is supposed to force `(ngModelChange)` and finally set `checked` state. 
Also there was some issues during change detecting and `checked` property is added manually to input.
there is also method, that informs if the user uses IE11, to force `nextValue` call on `intederminate` state, when it's mouse clicked, or space key is dispatched.
=> fix: Add 3rd state support for Ie11

apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.html, apps/docs/src/app/core/component-docs/localization-editor/examples/localization-editor-forms-example.component.ts
Closes #2032
This PR updates Localization editor documentation example by removing main language from form displayed in popover.
=> docs: Remove main language input from popover

libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts
#2029 
If the search term changes and affects the length of the resulting list, the popover body could be positioned incorrectly.  This updates the popover whenever the search term changes.
=> fix: combobox search term change popover positioning bug

apps/docs/src/app/core/component-docs/select/examples/select-basic-example/select-basic-example.component.html
Closes: https://github.com/SAP/fundamental-ngx/issues/2030
There was the same value provided to `option` component in examples. Also it was shared with disabled one.
=> docs: (select) fix example

libs/core/src/lib/select/option/option.component.scss, libs/core/src/lib/select/option/option.component.ts, libs/core/src/lib/select/select.component.ts
Closes https://github.com/SAP/fundamental-ngx/issues/2052
Right now there select is closed, when the same value is chosen.  
=> fix: (select) fix select close behaviour

apps/docs/src/app/core/component-docs/bar/bar-docs.component.html
Remove `name` property from `component-example` in Bar docs
=> docs: fix the broken Bar documentation

apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
closes: https://github.com/SAP/fundamental-ngx/issues/2061
There is changed placement on popover dynamic example, to prevent overflowing behind the page. 
=> docs: (popover) change dynamic popover example placement

apps/docs/src/app/core/component-docs/input-group/examples/input-group-form-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-number-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-number-example/input-group-number-example.component.html, libs/core/src/lib/input-group/input-group-number.component.ts
#2106 
Fix bug where default placeholder for number input group would read 'undefined'
=> fix: missing input group number placeholder

libs/core/src/lib/input-group/input-group.component.html, libs/core/src/lib/select/select.component.html
fixes #2083
Added the attribute type=`button` to input group and select so forms are not submitted when placed in them.
- [ x] the commit message follows the guideline:
=> fix: add type button to input group and select

CONTRIBUTING.md
In the PR Types there was a wrong type for the documentation. Changing it from `doc:xxx` to `docs:xxxx`
- [ x] the commit message follows the guideline:
=> docs: Fix allowed PR types in the contribution guidelines

libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2155
Right now every change from input is handled and parsed to date model on date/datetime pickers. 
It's the only way how we can enable `dirty` flag form support. From code perspective this change is very small, but it has a great impact on pickers.
=> fix: Change datepickers model on ngModelChange

apps/docs/src/app/core/component-docs/file-input/file-input-docs.component.html, apps/docs/src/app/core/component-docs/image/image-docs.component.html
Part of #2192 
Removed duplicate section heading from the documentation of Image and File Input
=> docs: remove duplicate section headings in the documentation

src/stories/breadcrumb/fd-breadcrumb.stories.ts
This Pr updates the breadcrumb to have cleaner code. It does not use the input as it requires typescript elements which storybook wont support.
=> test: breadcrumb storybook cleanup

apps/docs/src/styles.scss, libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
fixes: #2164
- This PR will fix the bullets on the product switch. 
- It needs to be done in NGX because it is not strictly following the styles template for the drag and drop option. 
- Fundamental-React and Vue would also need to be notified
=> fix: remove product switch bullets

libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.spec.ts, libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.ts, libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts
One of https://github.com/SAP/fundamental-ngx/issues/2192
There are some native JS methods replaced, because of IE11 compatibility
`getBoundingClientRect().x/y` to `getBoundingClientRect().left/top` and
`element.remove()` to `element.parentNode.removeChild(element)`
=> fix: Make properties DND IE11 compatible

apps/docs/src/app/core/component-docs/breadcrumb/breadcrumb-docs.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.ts
Also explain that the responsive behavior will not work if the container has a fixed width.
#2160 
Before: 
After:
=> fix: fixed-width breadcrumb containers not collapsing overflowing breadcrumbs

apps/docs/src/app/core/component-docs/input-group/examples/input-group-search-example/input-group-search-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-search-example/input-group-search-example.component.ts, apps/docs/src/app/core/component-docs/input-group/input-group-docs.component.html, libs/core/src/lib/input-group/input-group.component.html, libs/core/src/lib/input-group/input-group.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2136
There is added way to add `type` of input inside input-group component. 
=> fix: (input group) Add type of input group and example

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/component-docs/button/button-docs.component.html, apps/docs/src/app/core/component-docs/button/examples/button-icons-example.component.html, apps/docs/src/app/core/component-docs/button/examples/button-types-example.component.html, apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.component.ts, apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.module.ts, apps/docs/src/app/core/component-docs/split-button/examples/split-button-programmatical-example.component.html, apps/docs/src/app/core/component-docs/split-button/examples/split-button-programmatical-example.component.ts, apps/docs/src/app/core/component-docs/split-button/examples/split-button-types-example.component.ts, libs/core/src/lib/button/button.component.ts, libs/core/src/lib/segmented-button/segmented-button.component.ts, libs/core/src/lib/segmented-button/segmented-button.directive.spec.ts, libs/core/src/lib/segmented-button/segmented-button.directive.ts, libs/core/src/lib/split-button/split-button.component.html, libs/core/src/lib/split-button/split-button.component.ts
The PR brings:
* fix for RTL mode for split button
* fix for build of documentation for segmented button
* `deprecated` label in button component for properties being deprecated (for documentation purpose)
Segmented button API not built
Options not marked as deprecated 
The default value for params are missing
RTL mode not working
Segmented button API not built
Options not marked as deprecated 
The default value for params are missing
RTL mode not working
=> fix: button fiori3 fixes and documentation improvements

apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts, libs/core/src/lib/shellbar/product-menu/product-menu.component.html
=> fix:  broken toolbar replaced by Shellbar

libs/core/src/lib/popover/popover-directive/popover.directive.ts
https://github.com/SAP/fundamental-ngx/issues/2252
And it's the same issue and the same solution as in https://github.com/mapbox/mapbox-gl-draw/issues/479
On click of Buttons of Components like Datepicker, Combobox, and so on this issue is triggered because IE11 cannot handle empty Arrays on a spread operator e.g. `...this.additionalClasses`. Second thing is that the Array should be queried by `.length > 0` otherwise the statement will be always true.
=> fix: IE11 crash by avoiding argument-less calls to classList.add

libs/core/src/lib/button/button.component.ts
Revert the changes in the button done in https://github.com/SAP/fundamental-ngx/pull/2204
Reverted changes made by other PR
=> fix: reverted changes, removed 'this' keyboard from function call

libs/core/src/lib/product-switch/product-switch/product-switch.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/2098
There was missing class on product switch button, which caused old issues with button styling.
Before:
After:
=> fix: add missing class to Shellbar button

package-lock.json, package.json
Closes #2300 
Relates [ngx-markdown#210](https://github.com/jfcere/ngx-markdown/issues/210) [markedjs#1630](https://github.com/markedjs/marked/issues/1630)
Ngx-markdown depends on package called `marked` which recent version has issues on IE11.
Although PR fixes displaying documentation on IE11 it brings `npm ls` error again.
We have to wait with `ngx-markdown` upgrade till the fix is provided
=> chore: package downgraded to fix IE 11

apps/docs/src/app/core/component-docs/button/examples/button-examples.component.scss
Relates #2304
PR brins extra space arround example's buttons
=> docs: space added for example's buttons

libs/core/src/lib/input-group/input-group-number.component.html
#2304
PR provides a fix for height of input group number arrows
=> fix: input group number arrow's size fixed

libs/core/src/lib/dialog/dialog-header/dialog-header.component.html, libs/core/src/lib/dialog/dialog.component.ts
Part of #2304
Dialog was off center on IE11 browser because of `flexbox` and `position: absolute` combination.
Solution: using `position: relative` by default, and `position: absolute` when dialog is customly positioned.
=> fix: Center dialog on IE11

libs/core/src/lib/dialog/dialog.component.scss
Part of #2304
IE11 cannot properly interpret `border-radius: initial` value.
Use `border-radius: 0px` instead of `border-radius: initial`.
=> fix: Dialog with header has body with rounded top corners | IE11

libs/core/src/lib/dialog/dialog.component.ts
Part of #2304
IE11 standard has different naming of some of the keys. PR introduces support for "Escape" and "Esc" key code.
=> fix: Close Dialog on Esc key | IE11

libs/core/src/lib/input-group/input-group-directives.ts
The input group with complex templates example was broken, fixed by having input group directives use CssClassBuilder instead of AbstractFdNgxClass
=> fix: input group directives should use CssClassBuilder

libs/core/src/lib/radio/radio-button/radio-button.component.ts, libs/core/src/lib/split-button/split-button.component.ts
=> fix: set ViewEncapsulation.None for radio button and split button

libs/core/src/lib/calendar/calendar.service.ts
Part of: #2304
IE11 keyboard events keys have different naming. This PR adds support for IE11 key names.
=> fix: Support Calendar key navigation | IE11

libs/core/src/lib/radio/radio-button/radio-button.component.html, libs/core/src/lib/radio/radio-button/radio-button.component.ts
Relates #2304
PR brings fix for radio button inside reactive forms
=> fix: radio button reactive form

libs/core/src/lib/select/select.component.scss
Part of: #2304
Change icon `::after` element height from `fit-content` to `auto`
AFTER:
=> fix: Misaligned select icon | IE11

ci-scripts/sync-version.sh, libs/core/ng-package.json, libs/core/package.json, libs/core/schematics/ng-add/index.ts, libs/core/schematics/ng-add/schema.json, libs/core/schematics/ng-add/styles.ts, libs/core/tsconfig.lib.prod.json, package-lock.json, package.json
There are new schematics added into ngx core library `ng add @fundamental-ngx/core`
- There is one additional question before instalation: `Add default font imports into styles.scss?`, which is yes by default
- Chalk package is removed, it caused some issues for schematics (It's package for changing colors of messages in console)
If there are some `@sap-theming` imports in styles, it's skipped
If the styles.scss can't be found, it throws message:
Otherwise it's added
=> chore: Add new font imports to schematics

libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.html
Relates to: https://github.com/SAP/fundamental-ngx/issues/2334
Add focus trap to popover on datepicker and datetimepicker
=> fix: DatePickers add focus trap

apps/docs/src/app/core/component-docs/alert/alert-header/alert-header.component.html, apps/docs/src/app/core/component-docs/badge-label/badge-label-docs.module.ts, apps/docs/src/app/core/component-docs/badge-label/badge-label-header/badge-label-header.component.html, apps/docs/src/app/core/component-docs/dropdown/dropdown-docs.module.ts, apps/docs/src/app/core/component-docs/dropdown/dropdown-header/dropdown-header.component.html, apps/docs/src/app/core/component-docs/loading-spinner-docs/loading-spinner-docs.module.ts, apps/docs/src/app/core/component-docs/loading-spinner-docs/loading-spinner-header/loading-spinner-header.component.html, libs/core/src/lib/badge-label/badge-label.module.ts, libs/core/src/lib/badge-label/badge-label/badge.component.ts, libs/core/src/lib/badge-label/label/label.component.ts, libs/core/src/lib/badge-label/status-label/status-label.component.ts, libs/core/src/lib/loading-spinner/loading-spinner.component.ts, libs/core/src/lib/loading-spinner/loading-spinner.module.ts, libs/core/src/lib/popover/popover-dropdown/popover-dropdown.component.ts
Part of: #2334
This PR:
- deprecates Loading Spinner and Status Indicator components
- sets Message Strip components used for marking other components as deprecated as undismissable.
=> docs: Deprecate Loading Spinner and Status Indicator

apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.html, apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2316
related to: https://github.com/SAP/fundamental-ngx/issues/2304
Table with checkbox example fixed
=> docs: fix table with checkbox example

libs/core/README.md
#2304 
Adding notes to the setup guide about es5 and RtlService being required.  Hopefully we can find workarounds for this
=> docs: add note about es5/RtlService to readme

libs/core/src/lib/dialog/dialog-header/dialog-header.component.html
The close button was placed inside `fd-bar-left` together with the title which had fullWidth prop set to true. The close button should be placed inside `fd-bar-right` div
=> fix: add fix for Dialog header template close button

ci-scripts/publish.sh
PR brings workaround for creating release notes. Bash script checks if tag starts with 'v' letter as prefix if not then 'v' will be added
=> fix: workound added to check if tag starts with 'v'

apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss, apps/docs/src/app/documentation/shared-core-modules.ts
Latest Docs Issues:
Sidebar - collapse, when not fullfiled.
Menu Icon - Added module to shared modules.
Before:
After: 
IE11:
Opera:
=> docs: fix sidebar squashing, add icons to shared module

apps/docs/src/app/core/api-files.ts, libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts, libs/core/src/lib/nested-list/nested-item/nested-item.directive.ts, libs/core/src/lib/nested-list/nested-item/nested-item.service.ts, libs/core/src/lib/nested-list/nested-link/nested-link.directive.spec.ts, libs/core/src/lib/nested-list/nested-link/nested-link.directive.ts, libs/core/src/lib/nested-list/nested-list-keyboard.service.spec.ts, libs/core/src/lib/nested-list/nested-list-keyboard.service.ts, libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.ts, libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.interface.ts, libs/core/src/lib/nested-list/nested-list/nested-list.directive.spec.ts, libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts, libs/core/src/lib/nested-list/nested-list/nested-list.interface.ts, libs/core/src/lib/nested-list/prepared-nested-list/prepared-nested-list.component.ts, libs/core/src/lib/nested-list/public_api.ts, libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts, libs/core/src/lib/utils/decorators/apply-css-style.decorator.ts
Those changes removed circular dependency warning/error and all of the issues, that comes with it.
Tested with The lib es6/ng9 lib.
We could achieve that, thanks to services and interfaces, which allowed to avoid circular imports.
=> fix: remove circular dependency for Nested List 

libs/core/src/lib/alert/alert.component.ts
This PR changes call order in Alert component constructor, moving `super()` call to the top.
=> fix: Fix alert derived class constructor bug

apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-disabled-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-example.component.html, libs/platform/src/lib/components/base.ts, libs/platform/src/lib/components/form/base.input.ts, libs/platform/src/lib/components/form/combo-box/combo-box.component.html, libs/platform/src/lib/components/form/form-control.ts, libs/platform/src/lib/components/form/input/input.component.html, libs/platform/src/lib/components/form/radio-group/radio-group.component.html, libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts, libs/platform/src/lib/components/form/radio-group/radio-group.component.ts, libs/platform/src/lib/components/form/radio-group/radio/radio.component.html, libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
https://github.com/SAP/fundamental-ngx/issues/2368
In Platform we have multiple components with some common properties eg. id, name, placeholder etc. these can be moved to a common class and can be extended by all components being developed or to be developed. This PR includes base class and changes to existing components to extend this base class.
=> fix: (platform) Create common base class for Platform components

libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2364
There is check on every change detection, to not trigger it, when component is destroyed
=> fix: Checkbox check destroyed state on detect changes

libs/core/src/lib/product-switch/product-switch/product-switch.component.html, libs/core/src/lib/product-switch/product-switch/product-switch.component.ts
#2476
This pr will add an aria label input on the product switch component so that the button doesn't give the component a11y issues
=> fix: add ariaLabel input to product-switch for button

src/stories/link/link.stories.ts
This pr will add link to storybook. It does not use routerLink because there is not router for it to connect to. The accessibility issue from the inverted is normal. No way to add a class because storybook cannot access those/
=> test: add link to storybook

src/stories/sidenav/fd-side-nav.stories.ts
This pr will add side navigation to storybook. There are two different ones as condensed must be separate from regular. There is no knob for the condensed because the situation would not happen
=> test: add side nav to storybook

src/stories/textarea/fd-textarea-stories.ts, src/stories/textarea/fd-textarea.stories.ts
This or adds textarea to storybook
The disabled for textarea is broken, an issue as been created and will be targeted in another pr
=> test: add textarea to storybook

libs/core/src/lib/popover/popover-directive/popover.directive.ts
Issue is well reproduced [there](https://stackblitz.com/edit/angular-z4pvxw?file=src/app/popover-placement-example.component.html).
For some reason, popover is not updated, when it overflows the browser window.
There is forced update, on every open.
We should consider migrating to `@angular/cdk/overflow`
=> fix: Add popover update, when created

libs/core/src/lib/select/select.component.spec.ts
Fix failing `SelectComponent Should support alphanumerical keys selection` test
=> fix: Fix failing Select alphanumeric navigation test

libs/core/src/lib/button/button.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2507
There is default button type for button component. Sometimes buttons are treated as `type="submit"` by default, what causes form submission.
=> fix: Add default button type to buttons

apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-reactive-forms-example.component.ts, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2275
This solution protects from passing value to checkbox, which is not recognized by checkbox as one of certain state value. There was a case with undefined values, which are not the same as null/false.
Now if this situation occurs, it will be  treated as false, by default.
=> fix: Add default behaviour to checkbox

libs/core/src/lib/popover/popover-directive/popover-container.scss
Closes #2468
Closes #2465
Before: 
After:
=> fix: Remove hard coded background color from popover

apps/docs/src/app/core/component-docs/menu/examples/menu-addon-example.component.html
Menu items should not be combined with checkbox, this is List use-case.
=> docs: Remove menu with checkbox example

libs/core/src/lib/menu/menu.component.scss
PR removes extra space from first and last child of menu, but doing so, I introduced an issue from styles. We should wait with merging this until https://github.com/SAP/fundamental-styles/pull/895 will be merged.
=> fix: removed extra space from first and last child

libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
fixes #2393
PR removes slected state from header's buttons and restore missing button on year-range selection
=> fix: missing button restored, removed selected state from header

libs/core/src/lib/dialog/dialog-utils/dialog-ref.class.ts, libs/core/src/lib/dialog/dialog.component.ts
We should have some loaded events thrown, when body of dialog is initialised.
=> fix: Add loaded to dialog component

apps/docs/src/app/platform/api-files.ts, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs-module.ts, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-aria-label-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.scss, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.ts, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-numeric-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-and-icon-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-header/platform-info-label-header.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-header/platform-info-label-header.component.ts, apps/docs/src/app/platform/documentation/platform-documentation.component.ts, apps/docs/src/app/platform/platform-documentation.module.ts, apps/docs/src/app/platform/platform-documentation.routes.ts, libs/core/src/lib/info-label/info-label.component.ts, libs/platform/src/index.ts, libs/platform/src/lib/components/form/public_api.ts, libs/platform/src/lib/components/info-label/info-label.component.html, libs/platform/src/lib/components/info-label/info-label.component.spec.ts, libs/platform/src/lib/components/info-label/info-label.component.ts, libs/platform/src/lib/components/info-label/info-label.module.ts, libs/platform/src/lib/components/info-label/public_api.ts, libs/platform/src/lib/platform.module.ts
https://github.com/SAP/fundamental-ngx/issues/2338
This PR is mainly for converting InfoLabel directive from core to Info Label Component in platform
The Info Label component is used to highlight the status of an information by coloring the text.
=> fix: Platform wrapper component for info Label  with document changes

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
PR reverts [for] property in the checkbox component. We have to wait for chrome fix
=> fix: checkbox for reverted

libs/core/src/lib/time/time.component.scss
Since we have 0.9.0 styles on master, old time component is not compatible with new styles css.
There are included old styles.
=> fix: Add 0.8.1 Css to time component

libs/core/src/lib/checkbox/checkbox/checkbox.component.html
related to https://github.com/SAP/fundamental-ngx/issues/2602
There is a workaround for possibility to make use `:empty` state
Before:
After:
=> fix: enable :empty selector on checkbox

apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html, libs/core/src/lib/shellbar/product-menu/product-menu.component.html, libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html, libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/2608
Before placement that was passed to popover from shellbar menu item was hardcoded. There is introduced binding placement passed, with bottom-start by default.
=> fix: Provide way to put placement to shellbar product menu

libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts, libs/core/src/lib/switch/switch.component.spec.ts
On travis, tests for checkbox and switch components are randomly failing. It happens quite often. Those hcanges should fix it.
=> fix: Failing tests on checkbox and switch

libs/core/src/lib/popover/popover.component.ts, libs/core/src/lib/product-switch/product-switch/product-switch.component.html, libs/core/src/lib/shellbar/product-menu/product-menu.component.html, libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/2593
There is deprecated isDropdown flag on popover
=> fix: Deprecate isDropdown flag on popover

apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-basic-example.component.html, apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-categories-example.component.html, apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-header/platform-search-field-header.component.html, libs/platform/src/lib/components/button/button.component.scss, libs/platform/src/lib/components/menu/menu-item.component.scss, libs/platform/src/lib/components/menu/menu-item.component.ts, libs/platform/src/lib/components/menu/menu.component.scss, libs/platform/src/lib/components/search-field/search-field.component.html, libs/platform/src/lib/components/search-field/search-field.component.scss, libs/platform/src/lib/components/search-field/search-field.component.spec.ts, libs/platform/src/lib/components/search-field/search-field.component.ts
#2277 
The architecture of the Menu CSS styles in Fundamental-Styles 0.8.x has changed from previous versions, and as a result, has broken the display of the platform Menu and SearchField components.
This PR makes fixes to the Menu and SearchField components to account for the Menu style changes.
**Menu BEFORE:**
**Menu AFTER:**
**SearchField BEFORE:**
**SearchField AFTER:**
=> feat: (platform) Fixing Menu/SearchField styles after fundamental-style upgrade

apps/docs/src/app/core/component-docs/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/2674
The header of the Calendar was overflowing on mobile view
=> docs: fix overflowing header on landscape calendar mobile view

libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts, libs/core/src/lib/nested-list/nested-list-directives.spec.ts, libs/core/src/lib/nested-list/nested-list-directives.ts
relates to: https://github.com/SAP/fundamental-ngx/issues/2674
Click event now is not propagated upper, so it doesn't provide selected flag change.
=> fix: Stop propagating clicks from nested icon

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Relates to https://github.com/SAP/fundamental-ngx/issues/2674
There are reverted some changes, which broken ie11 support for tristate mode on checkbox.
=> fix: Bring IE11 support for tristate on checkbox

libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts, libs/core/src/lib/radio/radio-button/radio-button.component.spec.ts, libs/core/src/lib/switch/switch.component.spec.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2685
This PR is only to fix randomly failing tests for radio/checkbox/switch
The main problem was that, we tested click events that are maintained by browser. I changed all of them to trigger methods, that are be triggered, when any of control is clicked.
=> test: Remove click event testing on native radio/checkbox input elements

libs/core/src/lib/breadcrumb/breadcrumb.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/2590
blocked by: https://github.com/SAP/fundamental-ngx/pull/2572
there is added way to focus on overflow breadcrumb and trigger popover from there.
=> fix: Add support for focus/trigger on breadcrumb overflow indicator

libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.spec.ts, libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/multi-input/multi-input.interface.ts, libs/core/src/lib/select/select-mobile/select-mobile/select-mobile.component.ts, libs/core/src/lib/select/select.component.ts, libs/core/src/lib/select/select.interface.ts
relates: https://github.com/SAP/fundamental-ngx/issues/2674
There are included interfaces of components that have mobile mode. Also the way how we provide themselves is changed, to break import of each others there is InjectionToken
=> fix: remove circular dependency on mobile modes

libs/core/src/lib/dialog/dialog.component.ts, libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html, libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.scss, libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
Related to https://github.com/SAP/fundamental-ngx/issues/2674
There are 2 things changed
- Passing configuration objects to dialog components, like header/body/footer wasn't working well, so the cozy mode wasn't applied as well
- There is some weird issue with flex, so I had to hard code some styles in ngx. 
=> fix: Fix sizing of mobile mode multi input, fix dialog components configuration passing

libs/core/src/lib/busy-indicator/busy-indicator.component.html, libs/core/src/lib/busy-indicator/busy-indicator.component.scss
#2674
This PR changes focus event from `focus` to `focusin` because IE11 does not fully support `focus` event and moves visual focus to main Busy Indicator container.
=> fix: focus over loading Busy Indicators on IE11

libs/core/src/lib/list/list.component.scss
relates: https://github.com/SAP/fundamental-ngx/issues/2674
There is removed limit for max-width of dropdowns
=> fix: Remove max-width limits from dropdown

apps/docs/src/app/core/component-docs/notification/notification-docs.module.ts
Previously Notification API docs were displaying Multi Input documentation because of wrong content attachment.
=> docs: Fix notification API content

libs/core/src/lib/panel/panel-expand/panel-expand.component.spec.ts, libs/core/src/lib/panel/panel-expand/panel-expand.component.ts, libs/core/src/lib/panel/panel.component.spec.ts, libs/core/src/lib/panel/panel.component.ts, libs/core/src/lib/panel/panel.service.ts
Current Panel implementation does not support `expanded` two-way binding and includes duplicate `expanded` state settings inside PanelComponent logic, for example within `PanelExpandComponent`:
=> `PanelExpand.click()`
=> `set expanded state`
=> `updateExpanded`
=> `updateExpandedListener`
=> `set expanded state`
The problem was there was no way to distinguish if the expanded event is coming from outside or inside of the components and it has been resolved with adding `isExpandTriggerClick` parameter to internal expand event.
I think it is a little bit over-complicated but I cannot find other quick solution.
=> Fix panel expanded binding

CHANGELOG.md, package-lock.json, package.json
Accidentally included breaking change in commit message for https://github.com/SAP/fundamental-ngx/pull/2619. This pr manually reverts back to 0.19.0. 1.0.0-rc.0 has been deprecated on npm and tags deleted from github.
=> fix: manually remove 1.0.0-rc.0

libs/core/src/lib/menu/menu-item/menu-item.component.ts
Closes: #2721 
Cyclic dependency between `MenuItemComponent` and `SubmenuComponent` was causing an error when resolving metadata for the components.
This PR introduces `BaseSubmenu` interface helping to properly resolve the dependencies.
=> fix: Resolve menu declaration order issue

libs/core/src/lib/pagination/pagination.component.html
fixes #2736 
Angular was stripping whitespace from the pagination template, which inline-block needs to display the pagination numbers correctly.  Also removes the pagination link class from the ellipses.
Before:
After:
=> fix: pagination layout and dot hover issues

libs/core/src/lib/notification/notification/notification.component.ts
[#2755](https://github.com/SAP/fundamental-ngx/issues/2755)
Fix for super call in NotificationComponent
Moved it to the top of constructor
=> fix: super call error when using NotificationComponent

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.scss, libs/core/src/lib/multi-input/multi-input.component.ts
Related to: https://github.com/SAP/fundamental-ngx/issues/2674
There was addon button rendered in tokenizer, instead of input group.
Also the checkbox should now if it's used in list component, to apply paddings and change focus outline.
Before:
After:
=> fix: Change addon place on multi input, remove doubled padding from dropdown list on multi input

libs/core/src/lib/date-picker/date-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2757
There was missing change detection trigger, when any null value was passed into datepicker.
=> fix: Add change detection, when passed null value on datepicker

apps/docs/src/app/core/component-docs/mega-menu/mega-menu-docs.module.ts, apps/docs/src/app/core/component-docs/mega-menu/mega-menu-header/mega-menu-header.component.html, apps/docs/src/app/core/component-docs/select-native/select-native-docs.module.ts, apps/docs/src/app/core/component-docs/select-native/select-native-header/select-native-header.component.html
Part of https://github.com/SAP/fundamental-ngx/issues/2777
Mega Menu and Select Native are deprecated. An alert has been added to both components
=> docs: add depreciation alert for Mega Menu and Select Native

libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
related to: https://github.com/SAP/fundamental-ngx/issues/2777
There is a prevention from keeping old value, by clicking too fast in ie11 on checkbox.
=> fix: checkbox ie11 too fast click fix

libs/core/src/lib/toolbar/toolbar.component.ts
related to https://github.com/SAP/fundamental-ngx/issues/2777
`element.remove` method is not supported by ie11, so there is added workaround.
=> fix: change remove method in toolbar

libs/core/src/lib/breadcrumb/breadcrumb.component.html
Part of: #2777
`/` sign is added based on child order. In previous implementation the Menu component was always last child.
=> fix: Breadcrumb '/' after last item

libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts
This PR "turns off" randomly failing radio-button test. Lets turn it off for now so we dont have to re-run travis builds and investigate as separate issue.
=> fix: Ignore failing radio-button test

libs/core/src/lib/select/select.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/2777
The first element of the Popover body had rounded corners. They have been removed.
=> fix: remove rounded corners for the first element of Select component

libs/core/src/lib/list/list.component.scss, libs/core/src/lib/select/select.component.scss
Part of: #2777
This PR introduces a fix for collapsed lists used inside popover (IE11 issue).
The problems were:
- IE11 does not accept `flex-basis` values in percentage units
- IE11 does not support `width: max-content`
=> fix: add fix for lists in popovers (IE11 related issues)

apps/docs/src/app/core/component-docs/link/examples/link-example.component.html, libs/core/src/lib/link/link.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/2777
Inverted Link is supposed to be used in the Shell Header's Bar. The documentation has been updated to show this case.
On hover the colour of the link is not correct. A temporary fix has been added till we release and adapt the latest version of Fundamental-styles
=> fix: add correct colour for Inverted Link, improve doc example

libs/core/src/lib/token/tokenizer.component.scss
Minor issue from April 30 defect hunting.  Fixes this:
=> fix: add fix for tokenizer input overlapping tokenizer border

apps/docs/src/app/core/component-docs/tabs/examples/tabs-example.component.html, libs/core/src/lib/tabs/tab-item/tab-item.directive.ts, libs/core/src/lib/tabs/tab-link/tab-link.directive.ts, libs/core/src/lib/tabs/tab-list.component.html, libs/core/src/lib/tabs/tab-list.component.scss, libs/core/src/lib/tabs/tab-list.component.ts, libs/core/src/lib/tabs/tab-nav/tab-nav.component.spec.ts, libs/core/src/lib/tabs/tab-nav/tab-nav.component.ts, libs/core/src/lib/tabs/tab/tab-panel.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2651
There is added disabled state for tabs. It's not shown in examples, but property is opened to be changed by passing `[disabled]="true"`
=> fix: add disabled state to tabs

apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.html, apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/second-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html, libs/core/src/lib/dialog/dialog.component.ts, libs/core/src/lib/dialog/dialog.module.ts, libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.spec.ts, libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.ts, libs/core/src/lib/utils/public_api.ts, libs/core/src/lib/utils/tests/element-ref-mock.class.ts
Closes: #2765
Previously the Dialog was always focusing first `[fd-dialog-decisive-button]` and this behavior could not be changed.
This PR:
- Changes default Dialog focus behavior
- Introduces `[fd-initial-focus]` directive
Now by default the Dialog focuses first focusable element and user can change this behavior by placing `[fd-initial-focus]` on any element that should be focused first after opening the dialog.
=> fix: create initial focus directive

libs/core/src/lib/datetime-picker/datetime-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2849
Change detection + input reset wasn't there, when null/undefined was passed.
=> fix: Datetime Picker null detection

libs/core/src/lib/combobox/combobox.component.html
fixes #2831 where combobox raises exception when used with *ngIf inside of reactive form
=> fix: bug where error occasionally thrown due to missing check

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/component-docs/form-message/examples/form-message-example.component.html, apps/docs/src/app/core/component-docs/form-message/examples/form-message-example.component.ts, apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.html, apps/docs/src/app/core/component-docs/form-message/form-message-docs.component.ts, apps/docs/src/app/core/component-docs/form-message/form-message-docs.module.ts, apps/docs/src/app/core/component-docs/form-message/form-message-header/form-message-header.component.html, apps/docs/src/app/core/component-docs/form-message/form-message-header/form-message-header.component.ts, apps/docs/src/app/core/component-docs/input/examples/input-state-example.component.html, apps/docs/src/app/core/core-documentation.routes.ts, apps/docs/src/app/core/documentation/core-documentation.component.ts, libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html, libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts, libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.html, libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2133
I introduced new documentation page with form message group component.
There are some examples with various form components.
Also form message group component has been extended, now it renderes `<ng-content>` as control element.
I added 2 new inputs and removed RTL support, which is already inside popover.
=> fix: form message group example

libs/core/src/lib/panel/panel.component.html, libs/core/src/lib/panel/panel.component.ts, libs/core/src/lib/panel/panel.module.ts
Closes: #2904
Closes: #2893 
This PR:
- makes panel use `fd-button` component so proper stylesheets for button are loaded together with the Panel
- fixes `[attr.aria-controls]` attribute value
=> fix: Bring button styling to Panel and aria-controls attribute value

libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, libs/core/src/lib/calendar/calendar.service.ts, libs/core/src/lib/date-picker/date-picker.component.spec.ts, libs/core/src/lib/date-picker/date-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2769
fixes: https://github.com/SAP/fundamental-ngx/issues/2926
That change enables possibility to differentiate invalid dates and empty values. It is correct behaviour.
The model now is changed, when invalid date is passed by string.
Before:
After:
before:
After:
=> fix: Add difference between invalid dates

apps/docs/src/app/core/component-docs/input/examples/input-state-example.component.html
related to: https://github.com/SAP/fundamental-ngx/issues/2939
`focus` and `blur` are not event thrown natively by html elements. It has been changed to `focusin` and `focusout`
=> docs: Change example of blur/focus on input state

libs/core/src/lib/list/list-item.directive.ts, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.scss
related to: https://github.com/SAP/fundamental-ngx/issues/2939
There is fixed `max-width` on list container
Also Focus is placed for whole list, instead of only checkbox. The problem with keyboard support on IE11 is fixed. Before events was muted, by checkbox and it wasn't propagated. Now selection state is controlled only by list item,
=> fix: Change focusing strategy on multi input list

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/core/src/lib/list/list-item.directive.ts, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts
Part of: #2939
Checkbox used inside list needs to have additional class applied to display properly. Previously class was applied directly to the `nativeElement` in some specific moments of component life-cycle but it didn't work well with filter quiery based rendering. The easiest way is creating `Checkbox[labelClass]` to pass class directly to the label. I think this solution would be sooner or later requested by the users.
=> fix: (core) Add Checkbox label class input | Simplify Multi Input

libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.scss
related to: https://github.com/SAP/fundamental-ngx/issues/2939
Right now combobox keeps full width, instead of 600px limits.
=> fix: Combobox keep full width

libs/core/src/lib/switch/switch.component.html, libs/core/src/lib/switch/switch.component.spec.ts, libs/core/src/lib/switch/switch.component.ts
https://github.com/SAP/fundamental-ngx/issues/2979
Added `name` property to the core Switch component
=> fix: (core) add name property to switch component

libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts
Related to: https://github.com/SAP/fundamental-ngx/issues/2939
Now, after closing combobox, another opened will be closed as well. It will fix IE11 crashing issue
=> fix: combobox IE11 focus/blur crashing 

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/documentation/core-documentation.component.ts
Part of: #2976
This PR removed documentation references to Loading Spinner missed in #2988.
=> chore: Remove Loading Spinner docs references

apps/docs/src/app/platform/api-files.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-auto-complete-validation-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-auto-complete-validation-example.component.scss, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-auto-complete-validation-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-reactive-validation-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-reactive-validation-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-header/platform-input-header.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-header/platform-input-header.component.ts, apps/docs/src/app/platform/documentation/platform-documentation.component.ts, apps/docs/src/app/platform/platform-documentation.module.ts, apps/docs/src/app/platform/platform-documentation.routes.ts, libs/platform/src/lib/components/form/base.input.ts, libs/platform/src/lib/components/form/form-control.ts, libs/platform/src/lib/components/form/form-group/fdp-form.module.ts, libs/platform/src/lib/components/form/form.spec.ts, libs/platform/src/lib/components/form/input/fdp-input.module.ts, libs/platform/src/lib/components/form/input/input.component.html, libs/platform/src/lib/components/form/input/input.component.ts
#https://github.com/SAP/fundamental-ngx/issues/2655
The text input is used to enter single of text. When empty, it can hold a placeholder similar to a select component. You can define the height and width of the text input and also determine specific behaviour when handling texts.
The Input has the same features and functionality as the Input component in Fundamental NGX: Core. As such, the Platform Input component will be a wrapper around the Core Input component and will provide identical bindings as Input. Additionally, since this is an input element, it needs to implement the FormFieldControl as described in the FormGroup Layout or extend existing BaseInputComponent. …
=> fix: (platform) Input Component and documentation code changes 

libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts, libs/core/src/lib/tabs/tab-list.component.spec.ts
fixes:
#2801
#1997 
Fixes the tests for radio button and uncomments out the tab tests
=> chore: fix tests

apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.ts, apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.module.ts, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.html, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.scss, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, tsconfig.json
https://github.com/SAP/fundamental-ngx/issues/2825
This pr will show to users an example of how to apply moment.js locale support to the application with fd-date-time-picker
=> fix: add locale to i18n example of datetime picker

libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.html, libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss, libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts, libs/core/src/lib/product-switch/public_api.ts, libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.spec.ts, libs/core/src/lib/utils/drag-and-drop/dnd-container/dnd-container.directive.ts, libs/core/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.spec.ts, libs/core/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.ts, libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.spec.ts, libs/core/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts, libs/core/src/lib/utils/drag-and-drop/drag-and-drop.module.ts, libs/core/src/lib/utils/public_api.ts
related to: https://github.com/SAP/fundamental-ngx/issues/2776
Drag and drop directive for now is used only inside product switch. Before there was a requirement, to keep `cdkDrag` directive under `fd-dnd-container`. So the final structure had to be 
`ul fd-dnd-list` > `li fd-dnd-container` > `div cdkDrag`.
Now `fd-dnd-container` is changed to `fd-dnd-item` and has cdk drag as a service. It allows optimized usage of dnd.
`ul fd-dnd-list` > `li fd-dnd-item`
It changed final markup of product-switch, but it's not visible from end-user perspective
=> feat: refactor DND directive

libs/platform/src/lib/components/form/switch/switch/switch.component.ts, libs/platform/src/lib/components/form/text-area/text-area.component.ts
#3039 
missing return type was resulting in some random type added on running `ng build`
This can be observed even on running `ng build` in ngx repo, and looking for the affected files in the dist lib, but no error is thrown on terminal. 
=> fix: (platform) add types to contentDensity to fix build error

apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-example.component.ts, apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-overflow-grouping-example.component.html, apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-overflow-priority-example.component.html, apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.component.html, apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.component.ts, apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.module.ts, libs/core/src/lib/toolbar/toolbar-overflow-group.directive.ts, libs/core/src/lib/toolbar/toolbar-overflow-priority.directive.ts, libs/core/src/lib/toolbar/toolbar.component.html, libs/core/src/lib/toolbar/toolbar.component.spec.ts, libs/core/src/lib/toolbar/toolbar.component.ts, libs/core/src/lib/toolbar/toolbar.module.ts, libs/core/src/lib/utils/consts/index.ts, libs/core/src/lib/utils/consts/overflow-priority-score.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/2890
Closes: https://github.com/SAP/fundamental-ngx/issues/3018
=> fix: (core) toolbar enhancements

libs/core/src/lib/utils/directives/carousel/carousel.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/3133
In this PR there is added `destroy()` method on hammer js, when the time component is destroyed. 
=> fix: Time performance

apps/docs/src/app/core/api-files.ts, libs/core/src/lib/form/form-control/form-control.component.scss, libs/core/src/lib/form/form-control/form-control.component.spec.ts, libs/core/src/lib/form/form-control/form-control.component.ts, libs/core/src/lib/form/form-control/form-control.module.ts, libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss, libs/core/src/lib/form/form-item/form-item.component.scss, libs/core/src/lib/form/public_api.ts, libs/core/src/lib/token/tokenizer.component.spec.ts, libs/core/src/lib/token/tokenizer.component.ts, src/stories/fd-form-control/fd-form-control.stories.ts, src/stories/textarea/fd-textarea.stories.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/3084
There is changed `form-control` directive to component, so it contains styles now
=> fix: Transform form-control to component

libs/core/src/lib/tabs/tab-list.component.spec.ts, libs/core/src/lib/tabs/tab-list.component.ts
fixes: #1785 
The event is not emited in `ngAfterViewInit` and `ngOnChanges`
=> fix: Stop emitting change events on ViewInit and OnChanges

apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.ts, libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts, libs/core/src/lib/popover/popover-directive/popover.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2772
In shadow DOM, event target returns a root container, not certain element. So there is another way to read it.
=> fix: Bring support for shadow dom on Popover

libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/utils/services/keyboard-support/keyboard-support.service.ts
part of https://github.com/SAP/fundamental-ngx/issues/3085
Now combobox items react on `enter` keyboard event, so now user can select item by pressing enter.
=> fix: add enter key support for list in combobox

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.scss
=> fix: multi input should attach to body

libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts
Closes: #3181
This PR brings:
- Proper initialization of `_classMap[this._uuidv4]` value, previously initialized with nested array instead of an array
- Proper typing for `updateComponentClassList(..., previousComponentClassList,..)` argument
=> fix: applyCssClass value initialization

libs/core/src/lib/list/list.component.scss
Part of: #3085 
This PR:
- Adds custom styles patch missing in Fundamental Styles, making it possible to mark list items as selected without the necessity of using `fd-list__item--link` or `fd-list--selectable`.
=> fix: Add missing styles to List

libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/time-picker/time-picker.component.html, libs/core/src/lib/time-picker/time-picker.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/3085
DateTimePicker had old implementation of handling closing popover. Now this functionality is provided by popover component.
Also clicking on input now won't trigger popovers. This behaviour is same on SapUi5. 
=> fix: stop opening pickers on input click

apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-docs.component.html, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu.module.ts
#3086 
This fixes the "Platform menu doesn't scroll" defect in platform. On the menu examples page in platform, the menu would detach from the target button, when the sub section would scroll. The issue was caused by a missing module import: CDK's ScrollingModule.
The documentation has also been updated to mention the required module import.
=> fix: (platform) Fix detached menu while scrolling

apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts, libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.module.ts
fixes #2950 
Add submit and cancel buttons for datetime picker.
This does not have breaking changes for the developer but results in a slightly different UX which developers may need to consider
=> fix: add submit/cancel buttons for datetime picker

apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-auto-complete-validation-example.component.scss, apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-auto-complete-validation-example.component.ts
defect fix for the input width reduced 3086 issue
FormMessage had to be imported in the docs for one of the examples, without which the 'without Platform Forms' example was showing some broken form message styling.
Fix for width issue by overriding the fd-popover styles. A similar fix is already being used in core.
=> fix: (platform) defect fix for the input width reduced

apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-button-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-form-example/input-group-form-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-search-example/input-group-search-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-states-example.component.html, apps/docs/src/app/core/component-docs/input-group/examples/input-group-text-compact-example.component.html, apps/docs/src/app/core/component-docs/list/examples/list-data-example/list-data-example.component.html, libs/core/src/lib/dialog/dialog.component.html, libs/core/src/lib/shellbar/product-menu/product-menu.component.html
Closes: #3235 
Using static string bindings for boolean values can be confusing and have a negative impact on readability.
This PR changes static string bindings used for boolean values into bindings with brackets.
=> fix: Change usages of static string bindings for boolean values

libs/core/src/lib/toolbar/toolbar.component.ts, libs/platform/src/lib/components/panel/panel-actions/panel-actions.component.html, libs/platform/src/lib/components/panel/panel-actions/panel-actions.component.ts, libs/platform/src/lib/components/panel/panel.component.html
#3086 
`libs/core/src/lib/toolbar/toolbar.component.ts.ToolbarComponent._getSortedByPriorityAndGroupItems`
There is no space between the action buttons in the Panel with Actions Example.
=> fix: (platform) panel - space between the actions & console error

apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-basic-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-basic-example.component.scss, libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.scss, libs/platform/src/lib/components/form/text-area/text-area.component.ts, libs/platform/src/lib/components/form/text-area/text-area.module.ts
#3086 
- FormMessage had to be imported in the docs for one of the examples, without which the 'without Platform Forms' example was showing some broken form message styling.
- Removed custom class added to example
- The ElementRef being used was, for some reason, not able to get the component's reference. This was fixed by using the `read` attribute.
- Fix for width issue by overriding the `fd-popover` styles. A similar fix is already being used in core.
- Using only required FormControlModule iinstead of loading entire core FdFormModule in textarea module.
=> fix: (platform) fix for textarea breaking

apps/docs/src/app/core/component-docs/info-label/examples/info-label-icon-numeric-example.component.html, apps/docs/src/app/core/component-docs/info-label/info-label-docs.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-docs.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-numeric-example.component.html, libs/core/src/lib/info-label/info-label.component.spec.ts, libs/core/src/lib/info-label/info-label.component.ts
fixing infolabel Defects raised
>  info label only icon not matching the spec and its vertical alignment shifted.
> Icon-only type has been removed as its not necessary.
=> fix: (core) remove icon-only prop of Info Label and fix the vertical alignment

apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-reactive-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-template-example.component.ts, libs/platform/src/lib/components/form/form-group/form-field/form-field.component.html, libs/platform/src/lib/components/form/step-input/base.step-input.ts, libs/platform/src/lib/components/form/step-input/number/number-step-input.component.html, libs/platform/src/lib/components/form/step-input/number/number-step-input.component.spec.ts, libs/platform/src/lib/components/form/step-input/step-input-action-button.ts, libs/platform/src/lib/components/form/step-input/step-input-control.directive.ts, libs/platform/src/lib/components/form/step-input/step-input-decrement.directive.ts, libs/platform/src/lib/components/form/step-input/step-input-increment.directive.ts
https://github.com/SAP/fundamental-ngx/issues/3225 
It's a fix to handle `platform step-input` entry correctly
until that it relied only on 'change' event to commit new entered value.
From now it's also listening to `input` event and store intermediate value in variable so it can be used to perform `increase/decrease` actions without waiting for `change` event.
Regarding this issue:
It's not connected to step-input itself actually and I believe should be resolved in a separate pull request.
The issue lays in `fdp-input-message-group` due to popover `triggers` settings
https://github.com/SAP/fundamental-ngx/blob/cd4932dd5edb59dbfc674fe755da1a7a4e4ddd90/libs/platform/src/lib/components/form/input-message-group-with-template/input-message-gro …
=> fix: (platform) step input component defects

libs/core/src/lib/select/select.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/3261
There is included old trick from inputs/textareas, to remove spacing between select and message component.
Before:
After:
=> fix: remove spacing between message and select

libs/core/src/lib/utils/pipes/search-highlight.pipe.ts, libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts, libs/platform/src/lib/components/menu/menu-trigger.directive.ts, libs/platform/src/lib/components/menu/menu.spec.ts, libs/platform/src/lib/components/search-field/search-field.component.html, libs/platform/src/lib/components/search-field/search-field.component.scss, libs/platform/src/lib/components/search-field/search-field.component.spec.ts, libs/platform/src/lib/components/search-field/search-field.component.ts, libs/platform/src/lib/components/split-menu-button/split-menu-button.component.spec.ts
#3086 
The following issues were addressed:
=> fix: (platform) fix of defects related to Search Field

libs/core/src/lib/dialog/dialog-service/dialog.service.ts
fixes: #3106 
Adds partial keyword so not all properties have to be defined in the dialog config with the open message
=> fix: add partial keyword in DialogConfig

apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-form-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-standard-example.component.html, libs/platform/src/lib/components/form/input-group/addon.component.ts, libs/platform/src/lib/components/form/input-group/input-group.component.html, libs/platform/src/lib/components/form/input-group/input-group.component.ts
https://github.com/SAP/fundamental-ngx/issues/3324
https://github.com/SAP/fundamental-ngx/issues/3316
Added disabled state for fdp-input-group input and addon buttons.
In example added tootlip for an icon.
=> fix: (platform) input group states

libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts, libs/core/src/lib/utils/decorators/apply-css-class.spec.ts
https://github.com/SAP/fundamental-ngx/issues/3315
probably after these [changes](https://github.com/SAP/fundamental-ngx/pull/2937) `applyCssClass` started removing `classes` that are attached outside of this decarator during `@ContentChild` phase.
As result `input-group` buttons look broken.
=> fix: (core) applyCssClass decorator

libs/core/src/lib/dialog/dialog.component.spec.ts, libs/core/src/lib/dialog/dialog.component.ts
Closes: #3359 
optionally inject angular `Router` and subscribe to router events only if a router is present
change not relevant for documentation
=> fix: (core) make router in dialog optional

libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html, libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
Closes: #3072 
This PR:
- Moves `fd-popover--input-message-group` class to popover body section reducing the impact of styling of other popovers used within message-group popover.
- Overrides `margin-top: 0` property of message group. It looks like this styling parameter is not relevant to current core implementation.
=> fix: Improve message group to work with controls with overlay

apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.html, apps/docs/src/app/core/component-docs/file-input/examples/file-input-custom-example/file-input-custom-example.component.html, apps/docs/src/app/core/component-docs/icon/icon-docs.component.html, apps/docs/src/app/core/component-docs/link/examples/link-example.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html, apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.html, apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.html, apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-example/scroll-spy-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-templates/combobox-templates-example.component.html, apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-emphasized-example.component.html, apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-example.component.html, apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-emphasized-example.component.html, apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-icon-example.component.html, apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-standard-example.component.html, apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-truncated-example.component.html, libs/core/src/lib/icon/icon.component.spec.ts, libs/core/src/lib/icon/icon.component.ts, libs/platform/src/lib/components/select/select.component.html
deprecate icon size since we don't support predefined sizes and remove its usage from the examples in the doc
=> chore: deprecate icon size

apps/docs/src/app/core/component-docs/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/component-based/component-based-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/dialog-stacked-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.ts, apps/docs/src/app/core/component-docs/global-config/examples/dialog-global-config-example/dialog-global-config-example.module.ts, apps/docs/src/app/core/component-docs/global-config/examples/mobile-mode-global-config-example/mobile-mode-global-config-example.module.ts, apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-mobile-example/multi-input-mobile-example.component.ts, apps/docs/src/app/core/component-docs/popover/examples/popover-dialog/popover-dialog-example.component.ts, apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-columns-example.component.ts, apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.ts, apps/docs/src/app/documentation/utilities/consts/mobile-dialog.consts.ts, libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts, libs/core/src/lib/dialog/dialog-footer/dialog-footer.component.ts, libs/core/src/lib/dialog/dialog-header/dialog-header.component.ts, libs/core/src/lib/dialog/dialog-service/dialog.service.ts, libs/core/src/lib/dialog/dialog-utils/dialog-config.class.ts, libs/core/src/lib/dialog/dialog.component.ts, libs/core/src/lib/menu/menu-mobile/menu-mobile.component.spec.ts
This PR:
- Disables `no-inferrable-types` for `dialog-config.class.ts` file
- Removes `Partial<T>` type annotation from `Dialog.open` and `Dialog._applyDefaultConfig`
- Removes unnecessary `as DialogConfig` type casting
`DialogConfig` is a class that is used both to describe the default config of the Dialog (with optional properties and default values), and to describe config properties which all should remain optional.
Previously introduced changes made optional parameters required, which is conflicting with the main idea of the `DialogConfig`, and required users to cast the `DialogConfig` type, or specify the required properties.
Solution with `Partial<T>` annotation is partially good, but it remains some use-cases of `DialogConfig` still requiring type casting , using `DialogConfig` …
=> fix: Disable no-inferrable-types for DialogConfig

apps/docs/src/app/core/api-files.ts, libs/core/src/lib/tabs/tab-utils/tab-directives.ts, libs/core/src/lib/tabs/tab-utils/tab-icon.component.spec.ts, libs/core/src/lib/tabs/tab-utils/tab-icon.directive.spec.ts, libs/core/src/lib/tabs/tabs.module.ts, package-lock.json, package.json
There is change from `TabIconDirective` to `TabIconComponent`, but the selector hasn't been changed so this is not breaking change
=> fix: migrate tabs to 0.12.0 styles

libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.html, libs/core/src/lib/product-switch/product-switch-body/product-switch.item.ts, package-lock.json, package.json
There are minor changes inside product switch component. Also one of property `image` has been deprecated
=> fix: migrate product switch to 0.12.0 styles

apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-content-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-examples/platform-radio-group-list-items-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group.module.ts
https://github.com/SAP/fundamental-ngx/issues/3356
We should be using simple button, as we have fundamental buttons available.
=> fix: (platform) Removed simple button use from Radio Group Documentation

apps/docs/src/app/core/component-docs/menu/examples/menu-addon-example.component.html, apps/docs/src/app/core/component-docs/menu/examples/menu-mobile-example.component.html, apps/docs/src/app/core/component-docs/menu/examples/menu-with-submenu-example.component.html, libs/core/src/lib/menu/directives/menu-addon.directive.ts, libs/core/src/lib/menu/menu.module.ts, package-lock.json, package.json
part of https://github.com/SAP/fundamental-ngx/issues/3370
In this PR `fd-menu-addon` directive is changed to component and the way how it can be used:
Before:
```
<fd-icon fd-menu-addon position="before" [glyph]="'cart'"></fd-icon>
```
After:
```
<fd-menu-addon position="before" [glyph]="'cart'"></fd-menu-addon>
```
=> fix: Update menu addon to 0.12.0 styles

libs/core/src/lib/avatar/avatar.component.html, libs/core/src/lib/avatar/avatar.component.ts, package-lock.json, package.json
Part of: #3370 
This PR updates Avatar Component to support Fundamental Styles v0.12.0 markup, by moving the icon to separate `<i>` element.
=> fix: Adapt Avatar to 0.12.0 Fundamental Styles

apps/docs/src/app/core/component-docs/tile/examples/kpi-tile-example.component.html, apps/docs/src/app/core/component-docs/tile/examples/launch-tile-example.component.html, libs/core/src/lib/tile/directives/tile.directives.spec.ts, libs/core/src/lib/tile/directives/tile.directives.ts, package-lock.json, package.json
Part of: #3370
This PR updates Tile component to match Fundamental Styles v0.12.0, by changing refresh-icon tag from `<span>` to `<i>`.
=> fix: Adapt Tile to 0.12.0 Fundamental Styles

apps/docs/src/app/core/component-docs/list/examples/list-complex-example.component.html, apps/docs/src/app/core/component-docs/list/examples/list-icon-example.component.html, apps/docs/src/app/core/component-docs/list/examples/list-nav-indicator-example/list-nav-indicator-example.component.html, apps/docs/src/app/core/component-docs/list/examples/list-navigation-example/list-navigation-example.component.html, apps/docs/src/app/core/component-docs/select/examples/select-nested-options/select-nested-options.component.html, apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html, libs/core/src/lib/list/directives/list-icon.directive.ts
part of https://github.com/SAP/fundamental-ngx/issues/3370
There are only A11y changes included.
From:
```
<span fd-list-icon glyph="cart"></span>
```
To:
```
<i fd-list-icon glyph="cart"></i>
```
=> docs: Adapt list icons to 0.12.0 styles

apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-condensed-example/side-navigation-condensed-example.component.html, apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-icons-example.component.html, libs/core/src/lib/nested-list/nested-list-directives.ts, src/stories/sidenav/fd-side-nav.stories.ts
part of https://github.com/SAP/fundamental-ngx/issues/3370
There are only A11y changes included.
From:
```
<span fd-nested-list-icon [glyph]="'menu'"></span>
```
To:
```
<i fd-nested-list-icon glyph="menu"></i>
```
=> fix: Migrate nested list icon due to 0.12.0 styles

libs/core/src/lib/notification/notification/notification.component.scss
Part of [#3420](https://github.com/SAP/fundamental-ngx/issues/3420)
Notifications have been completely refactored in 0.12.0 version of Fundamental-styles. Temporary we are bringing back the old styling in ngx so we can release 0.22.0 in ngx and later work on adopting the new styling and markup of Notifications
=> fix: bring temporary the old styling of Notifications

apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss
Part of [#3420](https://github.com/SAP/fundamental-ngx/issues/3420)
=> docs: align vertically the GitHub icon in documentation shellbar

apps/docs/src/app/core/component-docs/object-status/examples/object-status-clickable-and-icon-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-generic-text-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-icon-text-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-generic-text-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-text-example.component.html, libs/core/src/lib/object-status/object-status.component.spec.ts, libs/core/src/lib/object-status/object-status.component.ts
Part of [#3420](https://github.com/SAP/fundamental-ngx/issues/3420)
Replace the content projection with an input property in order to apply the `<span *ngIf="label" class="fd-object-status__text">{{ label }}</span>` conditionally.
Before:
```
<span fd-object-status status="negative" inverted="true">Negative</span>
```
After:
```
<span fd-object-status status="negative" inverted="true" label="Negative"></span>
```
Replace the content projection of the Object Status with an input property called `label`.
=> fix: refactor Object Status to use an input property instead of content projection

apps/docs/src/app/core/component-docs/popover/examples/popover-dialog/popover-dialog-example.component.ts, apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown-example.component.ts, apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.ts, libs/core/src/lib/popover/popover-directive/popover.directive.ts
This PR:
- Removes example with shadow dom from the documentation
- Adds check for `composedPath` method
- Removes unused imports/variables
=> fix: Popover shadow dom for IE11

libs/core/src/lib/breadcrumb/breadcrumb.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.scss, libs/core/src/lib/breadcrumb/breadcrumb.component.ts
Part of: #3420
This PR:
- updates breadcrumb markup to match Fundamental Styles v0.12.0 (yes, this should be a span with `fd-breadcrumb__dropdown-icon` class)
- fixes `Placement` typing
=> fix: Breadcrumb expand collapsed items styling 

apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.scss, apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.scss, apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/3420
Removed styling related to grid that was used for displaying the Popover placement documentation. Added much simpler styles for this purpose
=> docs: fix Popover Placement documentation

libs/core/src/lib/card/card.component.scss
Closes: https://github.com/SAP/fundamental-ngx/issues/3418
This PR fixes negative numbers in RTL mode, also it adds avatar side margin which got overridden from fundamental-styles.
Corresponding issues have been created in fundamental-styles as well.
=> fix: (core) card RTL mode

libs/core/src/lib/nested-list/nested-content/nested-list-content.directive.spec.ts, libs/core/src/lib/nested-list/nested-content/nested-list-content.directive.ts, libs/core/src/lib/nested-list/nested-item/nested-item.directive.spec.ts, libs/core/src/lib/nested-list/nested-list-directives.spec.ts, libs/core/src/lib/nested-list/nested-list-directives.ts, libs/core/src/lib/nested-list/nested-list.module.ts, libs/core/src/lib/side-navigation/side-navigation.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3420
There is side navigation expand icon changed from directive to component, regarding latest 0.12.0 changes
=> fix: Show side navigation expand icon

libs/core/src/lib/dialog/dialog-utils/dialog-directives.ts, libs/core/src/lib/dialog/dialog.component.scss
This PR:
- updates CSS classes used to style Dialog title according to Fundamental Styles v0.12.0
=> fix: Update Dialog title styling

apps/docs/src/app/core/component-docs/bar/bar-docs.component.html
Part of https://github.com/SAP/fundamental-ngx/issues/3420
Floating footer was missing from the documentation example due to latest release of styles where the floating footer got a `position: absolute` and now requires a parent component with relative position.
=> docs: fix missing Floating footer from documentation

apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-dialog.component.ts
This PR:
- Updates Table Dialog with proper selection list markup
=> docs: Update Table example

apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-with-selection-example.component.html, apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-with-selection-example.component.html, libs/platform/src/lib/components/list/base-list-item.ts, libs/platform/src/lib/components/list/list.component.ts, libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.html
#3423 
#3266 
#3416 
labels with special characters in toolbar are not supported in rtl to ltr mode.  So removed special charters in the label text as per current toolbar styles support.
=> fix: (platform) addressed list header label issue

libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/core/src/lib/list/list-item/list-item-utils.ts, libs/core/src/lib/list/list-item/list-item.component.ts, libs/core/src/lib/list/public_api.ts
In one of defect hunting issues there was introduced circular dependency, which can unable to run `es5` based project
=> fix: Remove circular dep between checkbox and list component

apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html, apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-icons-example.component.html, apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-sizes-example.component.html, apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-state-example.component.html, apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-truncate-example.component.html, apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-types-example.component.html, libs/platform/src/lib/components/button/button.component.html, libs/platform/src/lib/components/button/button.component.ts
https://github.com/SAP/fundamental-ngx/issues/3370
The `[label]` property should be used now instead of adding text as a content. The content still works fine, unless it's used with icons.
The value for the text button is now passed as an input property, not as content projection.
Before: `<fdp-button>Text</fdp-button>`
After: `<fdp-button label="Text"></fdp-button>`
=> fix: (platform) updating button with styles 0.12.0

apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-group/combobox-group-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-templates/combobox-templates-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-templates/combobox-templates-example.component.ts, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.ts, libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.scss
#3358, #3410, SAP#3413
- Added width fix from SAP#3358 issue (secondary issue)
- Added fix for updating value with groupKey option SAP#3410
- Added fix for icons in RTL mode inside the custom template SAP#3413
Issue for the `startsWtihTheTerm` filter is: #3529 And it will be implemented in separate PR
=> fix: (platform) combobox width, custom template and groupKey issues

libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/time-picker/time-picker.component.html, libs/core/src/lib/time-picker/time-picker.component.ts, libs/core/src/lib/time/time-column/time-column.component.ts, libs/core/src/lib/time/time.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/3133
this PR removes time component inside time and datetime pickers. The `fd-time` there is completely removed from DOM / angular scope by `*ngIf`. So anytime popover with time/datetime picker is opened, there is enabled whole life cycling. It's still worth because otherwise multiple instances of timepicker, or datetimepicker completely breaks performance
=> fix: Performance on time and datetime pickers

libs/core/src/lib/popover/popover.component.ts
remove deprecated method `isDropdown` from popover
=> fix: remove deprecated input isDropdown from popover

libs/core/src/lib/input-group/input-group.component.ts
remove deprecated input`buttonType` from `input-group`
=> fix: remove deprecated input from input group - buttonType

.travis.yml
Part of: https://github.com/SAP/fundamental-ngx/issues/3433
This PR is going to improve travis CI by 
- skipping jobs from non-pr branches
- **To Check, after this PR merged** - Skip lint/tests, when PR is merged to master
Before:
After:
Taken from [requests](https://travis-ci.org/github/SAP/fundamental-ngx/requests)
=> chore: Limit travis only to build PRs

package.json
It seems like one of commands is not necessary and takes time from netlify's build
7m 17s
6m 11s
=> chore: Remove redundant build command from netlify

apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-compact-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-disabled-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-form-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/input-group/platform-input-group-examples/platform-input-group-standard-example.component.html, libs/platform/src/lib/components/form/input-group/input-group.component.spec.ts, libs/platform/src/lib/components/form/input-group/input-group.module.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/3638
Partially fixes https://github.com/SAP/fundamental-ngx/issues/3615 (first item in the list)
This PR fixes button usage in the `platform input-group` documentation examples and unit tests. 
=> fix: (platform) Input group - fix button usage

libs/core/src/lib/breadcrumb/breadcrumb.component.ts, libs/core/src/lib/busy-indicator/busy-indicator.component.ts, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/core/src/lib/combobox/auto-complete.directive.ts, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/list/list-item/list-item.component.ts, libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.ts, libs/core/src/lib/menu/menu-keyboard.service.ts, libs/core/src/lib/menu/services/menu.service.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/nested-list/nested-list-keyboard.service.ts, libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts, libs/core/src/lib/select/option/option.component.ts, libs/core/src/lib/select/select.component.ts, libs/core/src/lib/step-input/step-input.component.ts, libs/core/src/lib/tabs/tabs.service.ts, libs/core/src/lib/time/time-column/time-column.component.ts, libs/core/src/lib/time/time.component.ts, libs/core/src/lib/token/tokenizer.component.ts, libs/core/src/lib/utils/functions/index.ts, libs/core/src/lib/utils/functions/key-util.spec.ts, libs/core/src/lib/utils/functions/key-util.ts, libs/core/src/lib/utils/functions/keyboard-unification.ts, libs/core/src/lib/utils/public_api.ts, libs/core/src/lib/utils/services/keyboard-support/keyboard-support.service.ts, libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts, libs/platform/src/lib/components/form/step-input/step-input-control.directive.ts
Closes: #3105 
This PR:
- Updates existing `KeyUtil` implementations
- Removes `KeyUtil.isKey` in favor of `KeyUtil.isKeyCode`
- Removes `UnifyKeyboardKey` util
=> fix: (Core) Unify KeyUtil usages

apps/docs/src/app/core/component-docs/message-toast/examples/message-toast-example.component.ts, libs/core/src/lib/message-toast/message-toast-utils/message-toast-config.ts
There is added nullable typing for message toast classes, to get rid of `as ...` casting.
=> fix: (Core) add optional typing for class properties

apps/docs/src/app/core/component-docs/bar/bar-docs.component.html, apps/docs/src/app/core/component-docs/bar/bar-header/bar-header.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.html, apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html, libs/core/src/lib/bar/bar.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/dialog/dialog-footer/dialog-footer.component.html, libs/core/src/lib/dialog/dialog-header/dialog-header.component.html, src/stories/bar/fd-bar.stories.ts
close #3518
for the cozy property both `cosy` and `cozy` were used. It was decided that only `cozy` should be used. This PR is removing all the appearances of `cosy` in the Bar component and in the documentation examples.
In Bar component the Input property `cosy` was renamed to `cozy` for consistency with other components and Fiori 3 naming. Affected components: DateTime Picker, Dialog (footer and header).
Before:
```
<div fd-bar barDesign="footer" [cosy]="!compact">
```
Now:
```
<div fd-bar barDesign="footer" [cozy]="!compact">
```
=> fix: (Core) unify the naming of the cozy property

apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-overflow-example.component.html
There is updated split button, so it doesn't throw console errors anymore
=> docs: (core) update split button in toolbar example

libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/3634
There was some glitch in method logic checking if date is between 2 dates.
Previously it was based only on days for current month, so it didn't work well for days in different months 
=> fix: Calendar range date

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/component-docs/title/examples/title-elision-example.component.html, apps/docs/src/app/core/component-docs/title/examples/title-examples.component.ts, apps/docs/src/app/core/component-docs/title/examples/title-semantic-example.component.html, apps/docs/src/app/core/component-docs/title/examples/title-visual-example.component.html, apps/docs/src/app/core/component-docs/title/examples/title-wrapping-example.component.html, apps/docs/src/app/core/component-docs/title/title-docs.component.html, apps/docs/src/app/core/component-docs/title/title-docs.component.ts, apps/docs/src/app/core/component-docs/title/title-docs.module.ts, apps/docs/src/app/core/component-docs/title/title-header/title-header.component.html, apps/docs/src/app/core/component-docs/title/title-header/title-header.component.ts, apps/docs/src/app/core/core-documentation.routes.ts, apps/docs/src/app/core/documentation/core-documentation.component.ts, libs/core/src/index.ts, libs/core/src/lib/title/public_api.ts, libs/core/src/lib/title/title.component.scss, libs/core/src/lib/title/title.component.spec.ts, libs/core/src/lib/title/title.component.ts, libs/core/src/lib/title/title.module.ts
fixes #3703 
Surprise PR as I found this is something we need (in addition to some other things) in order to implement the wizard summary page.
=> feat: implement title component

libs/core/src/lib/title/title.component.spec.ts
There shouldn't be any `@fundamental-ngx/core` imports, even on tests.
=> test: update imports on title test

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.scss
Part of: #3685
This PR:
- Prevents custom styles from overriding compact list item height
=> fix: Multi input list item height in compact mode

libs/core/src/lib/toolbar/toolbar.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3685
Right now popover-body is rendered outside popover DOM. So styles for `.fd-toolbar {}` are not visible in `fd-toolbar__overflow__body {}` anymore. This is already addressed in styles on https://github.com/SAP/fundamental-styles/pull/1851. But it will take time to merge/adapt everything form newest version
=> fix: Add temporary styles for overflow toolbar

apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss, apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
There are added cdk-overlay styles and hammerjs dependency into stackblitz config file
=> chore: Add overlay styles and hammerjs dep into stackblitz config file

libs/core/src/lib/message-strip/message-strip.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3685
Tested on external app
Before:
After:
=> fix: (Core) add stronger selector for Message strip

libs/core/src/lib/form/form-item/form-item.component.ts
remove deprecated input `isCheck` from `FormItemComponent`
=> fix: remove deprecated isCheck from FormItemComponent

libs/core/src/lib/switch/switch.component.html
fixes https://github.com/SAP/fundamental-ngx/issues/3720
=> fix: (Core) cursor on disabled Switch should not be pointer

libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts
fixes #3793
Adding initialization of dummy subscriptions so that during the `OnDestroy` lifecycle hook, the code will not error trying to call `unsubscribe()` on an undefined variable.
=> fix: (platform) Fixing unsubscribe error onDestroy of DynamicPage component

apps/docs/src/app/platform/component-docs/platform-panel/platform-panel-examples/platform-panel-expandable-example.component.html, libs/core/src/lib/panel/panel.component.html, libs/core/src/lib/panel/panel.component.scss, libs/core/src/lib/panel/panel.component.spec.ts, libs/core/src/lib/panel/panel.component.ts
Related https://github.com/SAP/fundamental-ngx/issues/3674 _(with [this PR](https://github.com/SAP/fundamental-styles/pull/1861) would close the issue)_
Arrow-button looks into wrong side and has an extra/redundant icon 
=> fix: (Core) RTL mode arrows is showing wrong in Panel

apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html, apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html, apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs-header/fixed-card-layout-docs-header.component.html, apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts, package-lock.json, package.json
https://github.com/SAP/fundamental-ngx/issues/3809
We were using "https://www.npmjs.com/package/angular-resize-event"  for detecting Fixed card layout available width change detection. As this is third party library. we have decided to remove this dependency and have documentation for guiding user to use such technique to trigger change detection.
=> fix: (Core) removed angular-resize-event from fixed card layout and documention

apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-aria-label-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-example.component.ts, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-numeric-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-and-icon-example.component.html, apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-example/platform-info-label-text-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-generic-text-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-icon-text-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-generic-text-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-text-example.component.html, libs/core/src/lib/info-label/info-label.component.html, libs/core/src/lib/info-label/info-label.component.ts, libs/platform/src/lib/components/info-label/info-label.component.html, libs/platform/src/lib/components/info-label/info-label.component.ts, libs/platform/src/lib/components/object-marker/object-marker.component.html, libs/platform/src/lib/components/object-marker/object-marker.component.ts, libs/platform/src/lib/components/object-status/object-status.component.html, libs/platform/src/lib/components/object-status/object-status.component.ts
platform tool tip adding
fixes https://github.com/SAP/fundamental-ngx/issues/3697
Actual: None of the info label examples have a tooltip.
Expected: info label should have a tooltip on hover.
=> fix: (Platform) add tooltip to the components

apps/docs/src/styles.scss, libs/core/src/lib/popover/popover.component.scss
fixes: https://github.com/SAP/fundamental-ngx/issues/3860
There are needed css added to `popover.compnoent.scss`, so there won't be a need to add it separately in consumer application 
External app:
Before:
After:
=> fix: (Core) Add overlay css to Popover

libs/core/src/lib/popover/popover.component.scss
part of: https://github.com/SAP/fundamental-ngx/issues/3786
For some unknown reason this height has to be specified by CDK functionality.
To prevent datetime-picker / other talll components to be cut, I had to change `max-height` of another component from 100% to initial.
=> fix: (Core) Popover sides position

libs/core/src/lib/shellbar/shellbar.component.scss
part of: https://github.com/SAP/fundamental-ngx/issues/3786
fex-basis had to be changed to auto. IE11 doesn't like `flex-basis: 0` 
before:
after:
=> fix: (Core) Shellbar IE11 shrink

apps/docs/src/app/core/component-docs/inline-help/inline-help-header/inline-help-header.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.html, libs/core/src/lib/form/form-control/form-control.component.scss, libs/core/src/lib/form/form-control/form-control.component.ts, libs/core/src/lib/inline-help/inline-help.component.scss, libs/core/src/lib/inline-help/inline-help.component.ts, libs/core/src/lib/inline-help/inline-help.module.ts
Address the breaking changes introduced in v.0.13.0 release of  fundamental-styles.
1. Removed `form-select` from form control
2. Added a deprecation message to Inline help and brought temporary the styling in ngx
3. Adapted the template of Breadcrumb
- [NA ] tests for the changes that have been done
- [NA] Documentation Examples
- [NA] Stackblitz works for all examples
=> fix: (Core) adapt the Breaking Changes from fundamental-styles v.0.13.0

libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss, libs/core/src/lib/form/form-message/form-message.component.scss
part of: #3786
Width of form message outside the popover has been reduced only to needed width.
=> fix: (Core) FormMessage width reduce

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
part of: https://github.com/SAP/fundamental-ngx/issues/3786
Changed `flex: 0` to `flex: 1` in flexible card layout. IE11
Before:
After:
=> fix: (Core) change flex property on fixed card layout for IE11

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.html, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
#3840
#3839 
PR fixes some a11y issues:
- hovering over title area gives same tooltip everywhere: this is because on removing input binding from `title` field, the native action of setting to tooltip from the title attribute takes place. Hence, we need to specify `[title]` with the binding, while giving the toolbar buttons their own `title` attributes.
- content going behind floating bar is not visible when end of scroll is reached: since no specs or requirements are provided for this, following the same behaviour as UI5- by providing an empty div with height~floating bar height to give ample space for content visibility.
=> fix: (Platform) add accessibility fixes for Dynamic Page

apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-Icon-text-example.component.html, apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-clickable-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html
https://github.com/SAP/fundamental-ngx/issues/3797
https://github.com/SAP/fundamental-ngx/issues/3749
correct misspelling of "Critical" in object status Object.
The self-explanatory statuses Flag and Favorite are always displayed as an icon.", not icon and text - Visual core.
=> fix: (Core) remove wrong examples Object marker and Object Status

apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-and-icon-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-clickable-example.component.html
https://github.com/SAP/fundamental-ngx/issues/3749
The self-explanatory statuses Flag and Favorite are always displayed as an icon.", not icon and text - Visual core.
=> fix: (Platform) remove wrong examples Object marker

apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-basic-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-disable-function-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html
#3906 
The format of datetime picker appears in the placeholder by default. Since previously all examples explicitly had a placeholder, there was no example showcasing the default format in placeholder. This PR adjusts some examples to show that specifying no placeholder shows up the default datetime format instead. It also fixes a couple of failing unit tests.
=> fix: (Platform) show default format for placeholder in DatetimePicker docs

apps/docs/src/app/core/component-docs/theme-switcher/theme-switcher-docs.component.html, libs/core/src/lib/utils/consts/error-messages.ts, libs/core/src/lib/utils/services/themes.service.ts
There is a need to handle lack of router module import, when theme switching via url is enabled
=> fix: (Core) throw error on theme switcher via url, when router is not imported

apps/docs/src/app/core/component-docs/message-strip/examples/message-strip-width-example.component.html, libs/core/src/lib/message-strip/message-strip.component.html
and small fix for a message strip examples
Closes: https://github.com/SAP/fundamental-ngx/issues/3121
Closes: https://github.com/SAP/fundamental-ngx/issues/3122
- Added a `title` to close button
- Changed value of `width` in examples
=> fix: (Core) add title to close button in Message Strip component

libs/core/src/lib/button/button.component.scss
This PR introduces a temporary fix for the missing space between the Button text and icon. Once the newest version of fundamental-styles is adopted, the current fix won't be necessary and will be removed
=> fix: (Core) add fix for missing space between text and icon in Menu Button

apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
The Popover has moved from Popper.js to Angular CDK `overlay` package but the documentation wasn't updated.
=> docs: (Core) update Popover documentation to point to CDK overlay

libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts
#3970 
This PR replaced the 'Submit' button in datetime picker to the recommended 'OK' button as per visual spec.
=> fix: (Core) replace datetime picker button label from 'Submit' to 'OK'

libs/core/src/lib/token/tokenizer.component.scss
part of #3922 
Removes max-width from .fd-token class
=> fix: (Core) remove token max-width

libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/input-group/input-group.component.scss
Part of: #3922 
This PR:
- Brings `input` styles into `input-group`
- Removes outdated custom styling from `input-group`
- Removes glyph stub from `combobox` (it was used to keep proper height of the form-group, which collapsed when the addon was missing and all of this because of missing `input` styles which normally provide the height for the input).
=> fix: (Core) Combobox without expand button

libs/core/src/lib/form/form-message/constants.ts, libs/core/src/lib/form/form-message/consts.ts, libs/core/src/lib/form/form-message/form-message.component.html, libs/core/src/lib/form/form-message/form-message.component.scss, libs/core/src/lib/form/form-message/form-message.component.ts
Part of: #3922 
Previous implementation of the Form Message has diverged from Fundamental Styles.
This PR:
- Flattens the component by moving `fd-form-message` classes to the host element
- Removes outdated `compact` input
- Changes message form `display` property to `block` (as shown in Fundamental Styles)
**Breaking change**
- `[compact]` input has been removed
The issue found during the deffect hunting was caused by `display: inline`.
=> fix: (Core) Update form message to match Fundamental Styles

libs/core/src/lib/card/card.component.scss
this PR temporary brings styling rules for fixing overflow issues for Numeric content used in Cards. The issues were browser related and due to IE11 not supporting `width: initial`.
The fix in styles is https://github.com/SAP/fundamental-styles/pull/1940
=> fix: (Core) add fix for numeric content IE11 overflow issues in Cards

libs/core/src/lib/select/select.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/3038
In a situation of race condition caused by setTimeout user could not add an option and select it immediately (when this option was added the selected.viewValueText was not refreshed).
=> fix: (Core) adding and setting new options dynamically in 'Select'

libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html, libs/platform/src/lib/components/form/combobox/directives/auto-complete.directive.ts
https://github.com/SAP/fundamental-ngx/issues/3978
Prevent maximum calls the `setSelectionRange` function on Safari
=> fix: (Platform) fix a Range Error (Maximum calls) on Mobile View Combobox Safari

apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html
The filter pipe in the Table example was causing a console error and was not working. The problem was the missing 'key' parameter. 
=> docs: fix broken filtering in Table example

libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.html, libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.scss, libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.spec.ts, libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.ts, libs/platform/src/lib/components/thumbnail/thumbnail.component.ts
#3964
On load of the Thumbnail component the first avatar is not highlighted to indicate the currently selected image.
=> fix: (Platform) First avatar in Thumbnail needs highlight on default load

apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-autogrow-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-basic-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-template-example.component.html, libs/platform/src/lib/components/form/form-group/form-field/form-field.component.html, libs/platform/src/lib/components/form/text-area/text-area.component.html
fixes: #3442 
fixes: #3500 
fixes: #3501 
fixes: #3502
- This PR fixes some a11y issues raised for Textarea. Verified with VoiceOver.
- It also cleans up some of unnecessary string bindings in the textarea examples.
=> fix: (Platform) accessibility fixes for Textarea

apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-columns-example.component.ts
In Customizable Columns example Column 1 was appearing after Column 2. Now Column 1 comes before Column 2
=> docs: re-order the Table columns in the Customizable Columns example

libs/platform/src/lib/components/menu/menu.component.html
Closes https://github.com/SAP/fundamental-ngx/issues/4088
Removed popover classes from `fdp-menu`
=> fix: (Platform) remove popover classes from menu component

apps/docs/src/app/core/component-docs/tabs/examples/tab-selection-example.component.html, libs/core/src/lib/tabs/tab-list.component.ts
closes: https://github.com/SAP/fundamental-ngx/issues/3976
In presented example an argument of `selectTab()` was missing
=> fix: (Core) add fix for Tabs programmatic selection not being applied properly

apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-compact-example.component.html, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-compact-example.component.ts, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-example.component.html, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-example.component.ts, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-file-types-example.component.ts, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-max-file-size-example.component.html, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-max-file-size-example.component.ts, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-min-file-size-example.component.html, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-min-file-size-example.component.ts, apps/docs/src/app/platform/component-docs/platform-file-uploader/platform-file-uploader-examples/platform-file-uploader-reactive-example.component.ts
updating the documentation  for the file uplaoder component
https://github.com/SAP/fundamental-ngx/issues/4025
Description: Even after drag and drop the valid file the popup is showing invalid file upload. After load successful it should showing in green.
Expected: If user is trying upload the valid file then it should not show the wrong message: FIXED
=> fix: (platfrom) Addressing the invalid file handling issue.

libs/core/src/lib/button/button.component.scss
Class `.fd-button--text-alignment-left` has increased hierarchy now
Before:
After:
=> fix: (Core) Action sheet buttons left position

libs/core/src/lib/utils/services/themes.service.ts
There is a need to prevent theme service from undefined query param, otherwise generated values are invalid
=> fix: Add null validation for route change in theme service

apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-columns/combobox-columns-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-states/combobox-states-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-states/combobox-states-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/platform-combobox-docs.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/platform-combobox-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/platform-combobox-docs.module.ts, libs/core/src/lib/form/public_api.ts, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss, libs/platform/src/lib/components/form/combobox/commons/base-combobox.ts
Issue link https://github.com/SAP/fundamental-ngx/issues/3767
Fixed issue related to two columnt align
**Before**
**After**
Implement state property to combobox
=> fix: (Platform) Combobox - Two columns wrong align and add value states

libs/core/src/lib/wizard/wizard.component.ts
Should simply be removing the step completed class rather than setting the component's completed property.  Setting the property caused the action sheet to display on step indicator click when the step indicator had no stacked steps. Also, this issue would sometimes cause the "next steps" buttons to remain visible when they should be hidden.
=> fix: (Core) wizard quick fix for bug related to marking step as not completed

libs/platform/src/lib/components/form/text-area/text-area.component.html
fixes #3439 
PR adds aria tags, specifically `aria-describedby` is needed for screen readers to read the counter message when textarea is accessed.
=> fix: (Platform) add aria tags to Textarea to read counter messages

apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-behaviors-example.component.html, apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-behaviors-example.component.ts, apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-icons-example.component.html, apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-icons-example.component.ts, apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-types-example.component.html, apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-types-example.component.ts, libs/platform/src/lib/components/menu/menu-trigger.directive.ts, libs/platform/src/lib/components/split-menu-button/split-menu-button.component.html, libs/platform/src/lib/components/split-menu-button/split-menu-button.component.spec.ts, libs/platform/src/lib/components/split-menu-button/split-menu-button.component.ts
#3535 #3637 
1. fix for Overlay position relative to split-menu-button
2. fix for padding of sub-menu in case of cascading menu.
=> fix: (platform) Menu position in split-menu-button and Sub-menu padding fix in cascading menu

apps/docs/src/app/core/component-docs/object-status/examples/object-status-clickable-and-icon-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-default-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-icon-text-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-example.component.html, apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-icon-text-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-example.component.html, apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.html
updatig the object status icon to the latest version
https://github.com/SAP/fundamental-ngx/issues/3533
Object status icon, we still use the old version.
=> docs: (Core) update object status icon to the latest version

libs/core/ng-package.json, libs/core/package.json, libs/core/schematics/ng-add/index.ts, libs/core/schematics/ng-add/versions.ts, libs/core/schematics/utils/ng-module-utils.ts, libs/core/schematics/utils/package-utils.ts
There were some old methods, that are not supported by angular cli above and equal 10.1 version.
Now some of them are imported from `@schematics/angular` library.
To test it:
- You need testing app with ng@10.1 or above
- Fetch this branch
- run `npm run build-pack-library`
- copy `.tgz` file from `dist/libs/core/` to testing app directory
- Add this version of lib by writing `ng add @fundamental-ngx/core@{{path to tgz file}}`
=> chore: fix Schematics for NG versions above 10.1

libs/core/src/lib/form/form-label/form-label.component.scss
asterisk not in a proper place in IE11 for form field
https://github.com/SAP/fundamental-ngx/issues/4234
Fixed 
=> fix: (Core) asterisk not in a proper place in IE11 for form field

apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-error-handling.component.html, libs/platform/src/lib/components/form/base.input.ts, libs/platform/src/lib/components/form/checkbox-group/checkbox-group.component.html, libs/platform/src/lib/components/form/form-control.ts, libs/platform/src/lib/components/form/form-group/form-field/form-field.component.ts
#3823 
It provides fix of screen reader reading required/Mandatory field.
this fix will need for all form field components like checkbox, radio, datepicker, multi-input etc.
raised issue https://github.com/SAP/fundamental-ngx/issues/4280 for tracking that.
=> fix: (Platform) add screen reader detection for required form field

e2e/wdio/core/fixtures/appData/object-marker-content.ts, e2e/wdio/core/pages/core-base-component.po.ts, e2e/wdio/core/pages/object-marker.po.ts, e2e/wdio/core/tests/object-marker.e2e-spec.ts, e2e/wdio/platform/fixtures/appData/multi-input.page-content.ts, e2e/wdio/platform/pages/multi-input.po.ts, e2e/wdio/platform/tests/multi-input.e2e-spec.ts
Covered multi input component (Platform)
[4197](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4197)
[4302](https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4302)
Added e2e test for multi input and object marker components
=> test: add e2e test for multi input and object marker components

apps/docs/src/app/core/component-docs/popover-directive/popover-directive-header/popover-directive-header.component.html, libs/core/src/lib/form/form-label/form-label.component.scss, libs/core/src/lib/menu/menu-mobile/menu-mobile.component.spec.ts, libs/core/src/lib/menu/menu.component.html, libs/core/src/lib/menu/menu.component.spec.ts, libs/core/src/lib/menu/menu.component.ts, libs/core/src/lib/menu/menu.module.ts, libs/core/src/lib/menu/services/menu.service.ts, libs/core/src/lib/popover/base/base-popover.class.ts, libs/core/src/lib/popover/popover-body/popover-body.component.spec.ts, libs/core/src/lib/popover/popover-body/popover-body.component.ts, libs/core/src/lib/popover/popover-directive/popover.directive.ts, libs/core/src/lib/popover/popover-position/popover-position.ts, libs/core/src/lib/popover/popover-service/popover.service.ts, libs/core/src/lib/time/time.module.ts, libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.ts
closes: https://github.com/SAP/fundamental-ngx/issues/4203
There is added deprecation of popover directive. now simple popover can easly replace it. 
Also menu component
- Now uses popover service with CDK Overlay, instead of popover directive with popper.js.
- Mobile mode (false|true) can't be dynamically changed - I don't see any reason of having it.
- Has all properties extended from popover base class.
- Removed `[options]` from menu component
=> fix: deprecate Popper.js and refactor Menu component

libs/core/src/lib/time/time-column/time-column.component.scss, libs/core/src/lib/time/time-column/time-column.component.spec.ts, libs/core/src/lib/time/time-column/time-column.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/3695
Now time component doesn't scroll on popover open/init.
There is no way to speed up switching between columns, because all of them are shown and hidden by css
=> fix: (Core) Time Component stop scrolling on init

libs/core/src/lib/checkbox/checkbox/checkbox.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/4316
Due to a recent change in Checkbox introduced in https://github.com/SAP/fundamental-ngx/pull/4192 the span with class `fd-checkbox__text` is always present even when the checkbox is "empty" (has no label). This element brings a margin left of 0.6875rem which causes the issue. I added css to remove this margin when the span element has no content inside (is empty).
Before:
Now:
- [na] …
=> fix: (Core) add fix for empty checkbox focus

libs/core/src/lib/form/form-label/form-label.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/4316
The icon and the text of the Inline Help were not vertically aligned. Provided a css fix for the issue.
Before:
After:
=> fix: (Core) add fix for Inline Help icon-text misalignment

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
fixes #4311 
- In Firefox, the PR fixes an issue where a secondary scrollbar would appear behind the dynamic page scrollbar, and scrolling the secondary one and closing the dynamic page example would have scrolled the underlying page examples. It also happens in other browsers but the two scrollbars don't appear together. This is a documentation examples pages issue.
=> docs: (Platform) fix underlying documentation page scroll in Dynamic Page

libs/core/src/lib/datetime/fd-date-formats.ts, libs/core/src/lib/datetime/fd-datetime-adapter.spec.ts, libs/core/src/lib/datetime/fd-datetime-adapter.ts
Closes https://github.com/SAP/fundamental-ngx/issues/4334
This PR is adding ability to parse "en" time string
So time picker examples where locale is "en" should start working.
=> fix: (core) FdDatetimeAdapter: add time parsing

e2e/wdio/platform/tests/checkbox.e2e-spec.ts, libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts, libs/core/src/lib/form/form-message/form-message.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/4229
Form Message become readable by screen readers like VoiceOver
=> fix: (Core) make Form's Input Message readable by screen readers

libs/core/src/lib/list/directives/byline/list-content.directive.ts
There is wrong `@hostbinding` in list content directive 
=> fix: (Core) byline list content typo

libs/core/src/lib/dialog/dialog.component.html, libs/core/src/lib/utils/directives/resize/resize.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/3618
There is added anohter way to pass element for `resize` directive.
Because of `shadowRoot` there was no way to select (by `querySelctor`) mandatory element. This element is now provided directly.
=> fix: (Core) Add another way to put resize boundaries

apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.html, apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.ts, apps/docs/src/app/core/component-docs/combobox/examples/combobox-search-field-example.component.html, apps/docs/src/app/core/component-docs/combobox/examples/combobox-search-field-example.component.ts, apps/docs/src/app/core/component-docs/combobox/examples/index.ts, libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.scss, libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/combobox/combobox.module.ts
Closes https://github.com/SAP/fundamental-ngx/issues/3375
This PR introduces Search Field enhancement to Combobox component. When the `isSearch` property is set to true, the glyph of the Input Group changes to 'search' icon and also an additional clear button is shown when the user starts typing in the input field. The Clear button can be hidden by setting the `showClearButton` to false. By default it's set to true. 
=> feat: (Core) add Search Field functionality to Combobox component

apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-popover-example.component.html, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-popover-example.component.ts, libs/core/src/lib/quick-view/quick-view-title/quick-view-title.component.html, libs/core/src/lib/quick-view/quick-view-title/quick-view-title.component.ts, libs/core/src/lib/quick-view/quick-view.module.ts
**Note:** issue with title gaps resolved here https://github.com/SAP/fundamental-styles/pull/2069
Closes: https://github.com/SAP/fundamental-ngx/issues/4406
Related: https://github.com/SAP/fundamental-ngx/issues/4400 
=> fix: (Core) Quick View title's corners and added ability to align title

libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
This is temporary fix for scrollbar, which shouldn't be shown all the time
=> fix: (Platform) Dynamic Content Page overflow

apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.ts, apps/docs/src/app/core/component-docs/combobox/examples/combobox-forms-example.component.scss, apps/docs/src/app/core/component-docs/combobox/examples/combobox-forms-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-columns/combobox-columns-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-datasource/combobox-datasource-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-forms/combobox-forms-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-group/combobox-group-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-mobile/combobox-mobile-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-standard/combobox-standard.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-states/combobox-states-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-templates/combobox-templates-example.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/platform-combobox-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-combobox/platform-combobox-docs.module.ts, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.ts
Part of https://github.com/SAP/fundamental-ngx/issues/4392
All Combobox examples work on StackBlitz
=> fix: (Platform) fix combobox examples for stackblitz

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.scss, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.scss, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.scss, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.scss, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.scss, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.scss, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page.module.ts, libs/core/src/lib/flexible-column-layout/public_api.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-tabbed-content.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.spec.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.module.ts, libs/platform/src/lib/platform.module.ts
#4337 
- This PR fixes issue with having `position: fixed` in Dynamic Page that was causing other side-effects like appearing over the entire page and not taking up its parent's space. We are now using `position: static`. Also added an example for using with Flexible Column Layout.
Before:
After:
- This PR also fixes issue where dynamic page tab styles were getting applied to other `fd-tabs` used within the page. It fixes the issue by applying more specificity to the dynamic page tab styles application.
Before:
After:
Within tabbed dynamic page example, styles will only apply to dynamic page tabs, not user-provided tabs in content:
- …
=> fix: (Platform) remove dependency on position: fixed for Dynamic Page

apps/docs/src/app/core/component-docs/table/examples/table-focusable-example/table-focusable-example.component.html, apps/docs/src/app/core/component-docs/table/examples/table-focusable-example/table-focusable-example.component.ts, apps/docs/src/app/core/component-docs/table/table-docs.component.html, apps/docs/src/app/core/component-docs/table/table-docs.component.ts, apps/docs/src/app/core/component-docs/table/table-docs.module.ts, libs/core/src/lib/table/directives/table-cell.directive.ts, libs/core/src/lib/table/directives/table-row.directive.ts, libs/core/src/lib/table/table.component.scss
This brings some fixes for table styles, that will come in https://github.com/SAP/fundamental-styles/pull/2088 .
As we need them ASAP, it's good idea to bring them into ngx now.
=> fix: (Core) add temporary fixes to table component

libs/core/src/lib/input-group/input-group.component.ts
part of https://github.com/SAP/fundamental-styles/issues/2089
There is a check if focused element is button inside input group. If so, InputGroup is not focused
=> fix: (Core) remove double focus on Input Group with button

libs/core/src/lib/menu/menu.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/4482
Right now popover service is reinitialised, when trigger element is changed
=> fix: (Core) add fix for Breadcrump overflow menu

libs/core/src/lib/carousel/carousel.component.html, libs/core/src/lib/carousel/carousel.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/4482
Before:
After:
=> fix: (Core) add fix for keeping the focus on the button for Carousel component

libs/platform/src/lib/components/search-field/search-field.component.html, libs/platform/src/lib/components/search-field/search-field.component.scss
Closes https://github.com/SAP/fundamental-ngx/issues/4332
Add an incapsulation for input search styles so it does not override default input border 
=> fix: (Platform) Incapsulate input search styles

CHANGELOG.md, ci-scripts/hotfix-publish.sh, package-lock.json, package.json
During running hotfix release script, there was some error:
That made unable to increment version of current `main`  tag.
=> chore: increase version to 0.26.1 add necessary stash to hotfix deploy script

libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.html, libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.ts
part of #4482 
depends on https://github.com/SAP/fundamental-styles/pull/2094 but contains hardcoded styling for now
The shellbar notifications, when moved into the overflow menu on small screens, were not positioned correctly.  This was not known in the styles library because we had only seen it in ngx thus far.  This PR fixes the positioning and adds an example
Before:
After:
=> fix: (Core) add fix for incorrect Shellbar overflowed counter position

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts
fixes #4514 
fixes #4495 
Core tab had some breaking changes, where selectedIndexChange was replaced with selectedTabChange. This was not changed in Dynamic Page implementation which uses this output event, due to which the `tabChange` event was not being emitted. This PR makes the necessary changes. You can see the console.log message appear now when the tab is changed.
It also refactors 'disable header' example and fixes a theming related issue for the same example.
=> fix: (Platform) fix tabChange event not emitting in Dynamic Page 

libs/core/src/lib/button/base-button.ts, libs/core/src/lib/button/button.component.spec.ts, libs/core/src/lib/button/button.component.ts, libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
Part of https://github.com/SAP/fundamental-ngx/issues/4391
Set `is-disabled` class to `disabled` or `aria-disabled="true"` buttons.
Don't understand why, but this test case not working on the default test case. That's why I've added a new test case.
```
it('should add is-disabled class to disabled button', () => {
element.setAttribute('disabled', null);
fixture.detectChanges(); // or componentInstance.ngOnChanges();
componentInstance.buildComponentCssClass();
let cssClass = …
```
=> fix: (Core) set is-disabled class to disabled button

apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.html, apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.scss, apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html, libs/core/src/lib/shellbar/shellbar.component.html, libs/core/src/lib/shellbar/shellbar.component.scss, libs/core/src/lib/shellbar/shellbar.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/4556
This PR removes the responsive paddings which are applied based on the screen size so that the control button (hamburger ) is aligned vertically with the icons/text in the Side Nav. This is achieved by introducing a modifier class `fd-shellbar--side-nav` which applies `0 0.5rem 0 0` paddings on the Shellbar.  
=> fix: (Core) remove responsive paddings when Shellbar is used with Side Nav

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.spec.ts, libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts
fixes #4530 
This PR allows one to programmatically set the Dynamic Page's tabs as the selected one. To see this in action, check the example `Tabbed Dynamic Page`, switch over to Tab 2 and click the button `Switch to Tab 1`. This should switch the tab to Tab 1.
To programmatically switch/set the dynamic page tab, call `setSelectedTab(id)` on the DynamicPageComponent and pass in the id of the tab to switch/set to.
=> fix: (Platform) provide programmatic tab selection for Dynamic Page

e2e/wdio/platform/fixtures/testData/radio-button-group.ts, e2e/wdio/platform/pages/radio-button-group.po.ts, e2e/wdio/platform/tests/radio-button-group.e2e-spec.ts
[4172](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4172)
Added e2e tests for radio button group component (platform)
=> test: (e2e) add radio button group e2e tests

libs/core/src/lib/tile/tile.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/4483
Temp fix for truncation of content text in Feed Tile not working in IE11
=> fix: (Core) add fix for content text in Feed Tile truncation

libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.spec.ts, libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.ts
part of https://github.com/SAP/fundamental-ngx/issues/4483
It fixes issue with IE11 and initial focus, for some reason there is a need to wait for all synchronous jobs, before the focus method is being called.
=> fix: (Core) Add setTimeout for IE11 on InitialFocusDirective

apps/docs/src/app/core/component-docs/card/examples/card-example.component.html, apps/docs/src/app/core/component-docs/carousel/examples/carousel-dynamic-items-example.component.html, apps/docs/src/app/core/component-docs/carousel/examples/carousel-multiple-active-item-example.component.html, apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html, apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html, libs/core/src/lib/card/card-header.component.html, libs/core/src/lib/card/card-header.component.ts
The avatar in card header doesn't allow setting icons and different sizes
The avatar in card header needs to set size
=> fix: expose avatar inputs as part of card header

libs/platform/src/lib/components/table/components/table-p13-dialog/filtering/filter-rule.component.html
closes #4602 
due to latest refactoring in Core: Select, `<ng-container>` can no longer be used as a content of `fd-option`, replaced with `span` to fix this
=> fix: (Platform) Empty table filtering options

apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.html, apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts, apps/docs/src/app/core/component-docs/multi-input/multi-input-docs.component.html, libs/core/src/lib/multi-input/multi-input.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/4483
There is added multi input new token validation method.
- [x [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
=> fix: (Core) Add token validate function to MultiInput

libs/core/src/lib/popover/popover.component.ts, libs/core/src/lib/select/select-key-manager.service.ts, libs/core/src/lib/select/select.component.html, libs/core/src/lib/select/select.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/4483
there was repeated key down handler in select component
=> fix: (Core) Readonly select and arrow down fix

libs/core/src/lib/split-button/split-button.component.scss
The text of the Split button should not be centered but left-aligned.
Css was provided as a temporary solution until the new version of fund-styles is released.
=> fix: (Core) proper alignment of the Split Button text

libs/core/src/lib/multi-input/multi-input.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/4483
remove custom styling in fund-ngx that was causing problems with the focus outline in Multi Input
Before:
After:
=> fix: (Core) add fix for checkbox focus inside Multi Input

libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
closes https://github.com/SAP/fundamental-ngx/issues/4557
Currently elements passed through content projection to the Shellbar were not hiding "hiding" in mobile mode. 
=> fix: (Core) hide Shellbar custom elements in mobile mode

libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.html
Part of https://github.com/SAP/fundamental-ngx/issues/4482
Added `(focus)="onTouched()"` to the inputs of Date-picker and Datetime-picker so that the `touched` control changes to true when the input is focused.
=> fix: (Core) change touched state on focus for Datepickers

libs/core/src/lib/split-button/split-button.component.html, libs/core/src/lib/split-button/split-button.component.scss, libs/core/src/lib/split-button/split-button.component.spec.ts, libs/core/src/lib/split-button/split-button.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/3684
- There are added split button text classes.
- Removed unnecessary styling
- Added another styling, that should be removed after migrating next versions of styles
=> fix: (Core) Split Buton 0.16.1 migration

apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-no-gap-example.component.html, apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.component.html, libs/core/src/lib/layout-grid/constants.ts, libs/core/src/lib/layout-grid/layout-grid.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/3684
There is added `noHorizontalGap` and `noVerticalGap` to layout grid
=> fix: (Core) Add noHorizontal and noVertical  gaps to layout grid -  *0.16.1* migration

apps/docs/src/app/core/component-docs/wizard/examples/wizard-dialog-example.component.html, apps/docs/src/app/core/component-docs/wizard/examples/wizard-example.component.scss
fixes #4692 
Moves the wizard title into a dialog header and adds some custom styles to remove the unwanted box-shadow between the title and the progress bar.
=> docs: (Core) refactor dialog example to remove box shadow issue

apps/docs/src/app/core/component-docs/popover/popover-docs.component.html, apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts, ci-scripts/sync-version.sh, libs/core/ng-package.json, libs/core/package.json, libs/core/src/lib/breadcrumb/breadcrumb.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts, libs/core/src/lib/product-switch/product-switch/product-switch.component.ts, libs/core/src/lib/shellbar/product-menu/product-menu.component.ts, libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html, libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.ts, libs/core/src/lib/time-picker/time-picker.component.ts, libs/platform/src/lib/components/form/date-picker/date-picker.component.ts, libs/platform/src/lib/components/form/datetime-picker/datetime-picker.component.ts, libs/platform/src/lib/components/form/time-picker/time-picker.component.ts, package-lock.json, package.json
PR removing popper.js from deps.
Also it brings one **breaking change**
-  Removed `@Input options` from `ShellbarUserMenuComponent`
=> fix: (Core) Remove popper.js dependency

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.scss, libs/core/src/lib/multi-input/multi-input.component.spec.ts, libs/core/src/lib/multi-input/multi-input.component.ts
fixes https://github.com/SAP/fundamental-ngx/issues/4816
Multi Input bug has been removed.
Instead of closing multi input now it is hidden, when `displayedValues` array is empty.
=> fix: (Core) Fix hide bug for multi input

libs/core/src/lib/dynamic-page/dynamic-page.component.ts
There are some issues in height calculations for content inside dynamic page, when page is being redirected.
Before:
After:
=> fix: (Core) Dynamic page init content resize

apps/docs/src/app/documentation/core-helpers/playground/playground.components.scss
=> docs: fix playground background color 

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
part of https://github.tools.sap/dxp/jukebox/issues/420
Issue with card resize exist only on cards that are bigger than should be.
=> fix: (Core) Break word in every component under fixed card layout

libs/core/src/lib/fixed-card-layout/fixed-card-layout-item/fixed-card-layout-item.component.ts
fixes https://github.com/SAP/fundamental-ngx/issues/4498
There is removed tabindex from card item inside fixed card layout. Now it will focus header
=> fix: (Core) Fixed Card Layout Change focus target to header

apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.html, apps/docs/src/app/core/component-docs/table/table-docs.component.html, libs/core/src/lib/table/table.component.scss, libs/core/src/lib/table/table.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/4622
There is added `responsive` mode, which means that it is BREAKING CHANGE
- now it's required to have `[responsive]="true"`  to the table, to achieve responsive mode.
=> fix: Remove borders from responsvie table

libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.html, libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts, libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.html, libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.ts, libs/core/src/lib/wizard/wizard-step/wizard-step.component.html, libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts, libs/core/src/lib/wizard/wizard.component.scss, libs/core/src/lib/wizard/wizard.component.spec.ts, libs/core/src/lib/wizard/wizard.component.ts
fixes #4420 
Fixes a number of bugs where the stacked step indicator action sheet would be missing steps it should have, or clicking the step indicator would change to a step rather than open the action sheet
Before
After
=> fix: (Core) wizard step indicator stacking bugs on narrow screens

e2e/wdio/core/tests/card.e2e-spec.ts, e2e/wdio/core/tests/object-status.e2e-spec.ts, e2e/wdio/platform/tests/object-status.e2e-spec.ts
disable card and object status e2e tests
disabling visual regression testing against hardcoded colors
to be addressed in #4939
=> test: disable card and object status e2e tests

libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html, libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html, libs/platform/src/lib/components/value-help-dialog/components/define-tab/define-tab.component.html
Closes: https://github.com/SAP/fundamental-ngx/issues/4911
Remove i18n custom id duplicates in upload-collection and value-help-dialog modules
=> fix: (Platform) drop not unique i18n custom ids

apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/approval-flow-example-data-source.class.ts, apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-examples/platform-approval-flow-example.component.ts, libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.scss, libs/platform/src/lib/components/approval-flow/approval-flow.component.html, libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
issue hasn't been created yet, these tasks were discussed on a call with Kevin and application developers
- added ability to start the approval flow from a bunch of parallel nodes (previously only 1 root node was supported)
- fixed issue with missing watchers input in edit mode if there were no watchers in the beginning
- added input `watchersLabel` to customize text label near watchers block
- added ability to set all statuses in demo examples to `not started` to see how the graph responds to that 
=> feat: (Platform) approval flow adjustments

libs/core/src/lib/utils/directives/line-clamp/line-clamp.directive.ts
#4870 
Both fixes are for the LineClamp directive.
- Changed `innerText` parameter to `textContent`, because of empty spaces in ie11
- Added reset fix for ie on resize
=> fix: (core) added text component fixes for ie11

apps/docs/src/app/core/component-docs/text/examples/text-basic.component.ts, apps/docs/src/app/core/component-docs/text/examples/text-expandable.component.ts, apps/docs/src/app/core/component-docs/text/examples/text-hyphenation.component.ts, apps/docs/src/app/core/component-docs/text/examples/text-max-lines.component.ts, apps/docs/src/app/core/component-docs/text/examples/text-whitespaces.component.ts, apps/docs/src/app/core/component-docs/text/text-docs.component.html, apps/docs/src/app/core/component-docs/text/text-docs.component.ts
#4867 
- Changed selectors of the text examples
=> fix: (core) chaged text examples selectors to fix stackblitz

libs/core/src/lib/fundamental-ngx-core.module.ts
The GridListModule is not currently added in fundamental-ngx-core.module.ts
=> fix: add GridListModule to the exports

libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
part of #4908 
Fixes a bug where an invisible element would get focused with the single select grid list
=> fix: tab index bug for single select grid list item

libs/app-shell/package.json
Bump version to 0.2.37 by https://github.com/SAP/fundamental-ngx/pull/4124
=> chore: (AppShell) bump to 0.2.37

e2e/wdio/platform/tests/checkbox.e2e-spec.ts, libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/platform/src/lib/components/form/checkbox/checkbox.component.spec.ts
Closes #3850 
* ARIA `aria-checked` attribute removed from Checkbox Core component.
* Unit, E2E tests updated.
=> fix: (Core) aria checked removed from native checkbox input

apps/docs/src/app/schema/containers/schema-group/schema-group.component.html, apps/docs/src/app/schema/containers/schema-group/schema-group.component.ts
Closes #3844.
`for` & `id` attributes set for labels & selects in Playground Platform component.
=> docs: (Platform) playground - 'for' attribute for label to bound to appropriate select

e2e/wdio/core/tests/standard-list.e2e-spec.ts
when there is a poor connection to Saucelabs, this test takes too long to run and times out. Skipping element state checks (hover, focus, active) to reduce time while pending VR discussion.
=> test: skip element state checks

libs/platform/src/lib/components/form/form-group/form-field/form-field.component.ts, libs/platform/src/lib/components/form/form.spec.ts
Closes:  https://github.com/SAP/fundamental-ngx/issues/5121
This PR adds optional input to the `fdp-form-field` component.
Currently `fdp-form-field` injects `fdp-form-group` instance through the component constructor, which means this injection doesn't work when `fdp-form-field` is defined out of `fdp-form-group` content.
New optional input gives the possibility to define parent FormGroupContainer explicitly through component input.
=> fix: (Platform) Add ability to use fdp-form-field out of fdp-form-group-content

PLATFORM_README.md, libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.html, libs/platform/src/lib/components/approval-flow/approval-flow-user-list/approval-flow-user-list.component.html, libs/platform/src/lib/components/approval-flow/approval-flow.component.html, libs/platform/src/lib/components/form/text-area/text-area.component.html, libs/platform/src/lib/components/table/components/table-p13-dialog/columns/columns.component.html, libs/platform/src/lib/components/table/components/table-p13-dialog/filtering/filter-rule.component.html, libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html, libs/platform/src/lib/components/value-help-dialog/components/define-tab/define-tab.component.html, libs/platform/src/lib/components/value-help-dialog/models/vhd-strategy.enum.ts
Closes #5098.
Code of the Platform components refactored to get rid of plural & select features of the i18n. The [wiki page](https://github.com/SAP/fundamental-ngx/wiki/Internationalization-Supporting-in-@fundamental-ngx-platform#select--plural) about internationalization updated.
As i18n isn't an Angular directive - we're highly limited in next things:
* Cannot **bind** i18n id - so we cannot implement & use helper component.
* Cannot set i18n markers **inside** of the loops, components code (there exist hacky solution but it isn't applicable as translations extracting isn't working).
=> fix: (Platform) i18n remove select, plurals

libs/store/src/index.ts, libs/store/src/lib/infrastructure/persistence/query/query-adapter.ts
n/a
In order for the end user to develop their own customized QueryAdapter, they need query and predicate types which are currently not exported.
Adding exports for
* QueryAdapterFactory
* QuerySnapshot
* OrderBy
* collection of Predicate types
=> fix: (Store) Exporting additional types for QueryAdapter

e2e/wdio/platform/pages/multi-input.po.ts, libs/platform/src/lib/components/form/multi-input/multi-input.component.html, libs/platform/src/lib/components/form/multi-input/multi-input.component.scss
styles Migrated to latest version and removed the styles from ngx component scss file.
part of: https://github.com/SAP/fundamental-ngx/issues/5025
style clean up post the migration. since its a patterned component few customisable css is retained as part of the clean up.
=> chore: (Platform)css cleanup hardcoded styles from multi Input component

libs/store/src/lib/infrastructure/persistence/store/entity-store-builder.ts
n/a
`DefaultQueryService.getWithQuery` is supposed to return a observable with an array of proxied entity objects. Instead it was  returning a proxied array of entities.
=> fix: (Store) Fixing data returned by getWithQuery

libs/core/src/lib/dynamic-page/dynamic-page.component.ts
When the SubHeader of a Dynamic Page is not collapsible, the Header should not have hover state.
- [na] Run npm run build-pack-library and test in external application
=> fix: (Core) add fix for Dynamic Page header hover state when subheader is not collapsible

libs/platform/src/lib/components/base.ts, libs/platform/src/lib/components/list/action-list-item/action-list-item.component.ts, libs/platform/src/lib/components/list/base-list-item.ts, libs/platform/src/lib/components/list/display-list-item/display-list-item.component.ts, libs/platform/src/lib/components/list/object-list-item/object-list-item.component.ts, libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.ts
Closes SAP/fundamental-ngx#5213
Makes router optional and also content density no longer relies on route changes to be set
=> fix: (platform) make router optional

apps/docs/src/app/core/component-docs/facets/facet-examples/facet-group-example.component.html, apps/docs/src/app/core/component-docs/facets/facet-examples/form-facet-example.component.html, libs/core/src/lib/facets/facet-group.component.scss, libs/core/src/lib/facets/facet/facet.component.scss, libs/core/src/lib/facets/facet/facet.component.ts
fixes #5016 
1. move the css import to facet component
2. update the examples to use form-label directives
=> fix: import form label styling and update facet examples

apps/docs/src/app/core/component-docs/avatar/avatar-docs.component.html, libs/core/src/lib/avatar/avatar.component.spec.ts, libs/core/src/lib/avatar/avatar.component.ts
Closes https://github.com/SAP/fundamental-styles/issues/1874
Add [random] option for avatar component to randomly select accent background color
=> feat: (Core) add random accent color option for avatar

apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-list-object.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-list-object.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-list.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-list.component.ts, libs/platform/src/lib/components/form/checkbox-group/checkbox-group.component.ts
Closes #5173 
Not able is use non template driven checkbox group outside form fields.
- [n/a ] update `README.md`
- [n/a ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
=> fix: (Platform) make formcontrol non mandatory  in checkbox group for non form cases

libs/core/src/lib/text/text.component.html
Closes SAP/fundamental-ngx https://github.com/SAP/fundamental-ngx/issues/5077
Text component more or less label for expand/collapse functionality is not readable for accessibility.
=> fix: (Core) Text component's more or less label for expand/collapse functionality is not readable for accessibility.

angular.json
Closes #5356.
Since we've switched to the nrwl/nx builder we started adding dependencies to the packages - it's the default for that builder (and the situation is the opposite for angular/package builder). 
In that case `@fundamental-ngx/core` & `@fundamental-ngx/platform` packages have their own angular package dependencies and their versions may be different from the respective packages provided by the host application - it leads to the various errors (at least the ones described in #5356).
The goal is to disable including packages to avoid any mismatching and use only the packages provided by the host application.
- [n/a] [Breaking Changes …
=> fix: (Core|Platform) remove deps from packages nx builder improvement

libs/core/src/lib/dialog/base/dialog-config-base.class.ts, libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts, libs/platform/src/lib/components/table/components/table-p13-dialog/table-p13-dialog.component.ts, libs/platform/src/lib/components/table/components/table-view-settings-dialog/table-view-settings-dialog.component.ts
Closes #4411, #4412, #5465.
`flex-grow: 1` isn't working in IE11 for the dialog body (container has `flex-direction: column`). Instead of having CSS in several places, as we have `DialogConfig` class it makes sense to just extend it - that will lead to smaller code changes for every dialog where we want to fix that IE11 issue.
=> fix: (Core|Platform) core dialog body min height (ie11 fix)

libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts, libs/core/src/lib/wizard/wizard.component.ts
fixes #5402 
Moves wizard padding logic away from the dialog body to remove circular dependency between components
=> fix: (Core) remove wizard padding logic from dialog body component

libs/core/src/lib/wizard/wizard-step/wizard-step.component.html, libs/core/src/lib/wizard/wizard-step/wizard-step.component.ts, libs/core/src/lib/wizard/wizard.component.ts
fixes #5435 
This PR allows the application developer to use `*ngIf` on wizard steps to add them conditionally.
=> fix: (Core) allow for conditionally adding steps to a wizard via *ngIf

apps/docs/src/app/core/component-docs/dialog/examples/component-based/component-based-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/dialog-stacked-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/second-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.ts
Closes : https://github.com/SAP/fundamental-ngx/issues/3117
fix: adding ariaLabelledby to the dialog header for screen reader
=> docs: (Core) add ariaLabelledby to the dialog header for screen reader

apps/docs/src/app/core/component-docs/icon/examples/icon-businessSuiteInAppSymbols-example.component.html, apps/docs/src/app/core/component-docs/icon/examples/icon-example.component.html, apps/docs/src/app/core/component-docs/icon/examples/icon-example.component.scss, apps/docs/src/app/core/component-docs/icon/examples/icon-tnt-example.component.html
Closes SAP/fundamental-ngx#3152
This PR modifies the documentation classes to show the icons properly in smaller screen sizes.
=> docs: (Core) fix overlapping of icon labels in Icon component documentation

libs/core/src/lib/pagination/pagination.component.html, libs/core/src/lib/pagination/pagination.component.ts
Closes SAP/fundamental-ngx#3128
Fixed not readable pagination label for accessibility
=> fix: (Core) fix not readable pagination label for accessibility

apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-example.component.html, apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.html, e2e/wdio/platform/tests/menu-button.e2e-spec.ts, libs/platform/src/lib/components/menu/menu-trigger.directive.ts
Closes SAP/fundamental-ngx#3734
Closes SAP/fundamental-ngx#3757
Closes SAP/fundamental-ngx#4058
This PR fixes following issues:
1. #3734 : applied tab focus on avatar-menu - documentation change.
2. #3757 : removed example for non-disable menu-button from disabled section.
3. #4058: fixes IE 11 issue, where menu is not opening on click.
=> fix: (Platform) Open Menu on click for Internet explorer

apps/docs/src/app/core/component-docs/notification/examples/notification-options/notification-options-example.component.html
Closes SAP/fundamental-ngx #5393
Screenreader tooltips added for overflow button in notification examples.
=> docs: (Core) screenreader helper added for overflow button

libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.ts
Closes SAP/fundamental-ngx#4851
Fixed calendar aria-label wrong date for year range
=> fix: (Core) fix calendar aria-label wrong date for year range

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Closes  #5120.
If checkbox placed inside the element with `tabindex` set (even `-1`) that element gets focus when checkbox got clicked. So checkbox wrapped with element with `tabindex="-1"` to avoid that.
=> fix(core): checkbox parent element focus fix

e2e/wdio/core/fixtures/appData/calendar-contents.ts, e2e/wdio/core/tests/calendar.e2e-spec.ts
add fix for calendar (core) e2e tests where the test on the 1st of the month tries to choose the 1st as a new date and fails.
=> test: (e2e) fix flaky calendar e2e tests

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-page-overflow.service.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts
Closes SAP/fundamental-ngx#4619
The documentation page class `page-content` overflow styles are changed in the documentation examples to hide multiple scrollbar visibility in some browsers when dynamic page examples are opened in full screen. When back pressed, this class's overflow styles were not being reset, due to which the scroll would get disabled in the previous documentation page. This PR resets the styles of `page-content` to fix this issue.
=> docs(platform): fix disabled scroll in other pages on back press from Dynamic Page examples

libs/core/src/lib/dialog/dialog.component.scss
Closes #4518
`z-index` for the dialog fix to be available to have an overlay on top of the dialog.
=> fix(core): dialog z-index fix

libs/core/src/lib/datetime/public_api.ts, package.json
This issue related to broken build libraries on the main branch
To fix this issue was fixed datetime exports
=> fix(core): fix datetime exports

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-base-example.component.html, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-base-example.component.ts, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-dialog-example.component.html, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-dialog-example.component.ts, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-popover-example.component.html, apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-popover-example.component.ts, libs/core/src/lib/quick-view/public_api.ts, libs/core/src/lib/quick-view/quick-view-group-item-content/quick-view-group-item-content-element.directive.spec.ts, libs/core/src/lib/quick-view/quick-view-group-item-content/quick-view-group-item-content-element.directive.ts, libs/core/src/lib/quick-view/quick-view-group-item-content/quick-view-group-item-content.component.ts, libs/core/src/lib/quick-view/quick-view-group-item-label/quick-view-group-item-label.component.ts, libs/core/src/lib/quick-view/quick-view-group-item/quick-view-group-item.component.html, libs/core/src/lib/quick-view/quick-view-group-item/quick-view-group-item.component.ts, libs/core/src/lib/quick-view/quick-view.module.ts, libs/core/src/lib/utils/functions/closest-element.ts
added `QuickViewGroupItemContentElementDirective` (`fd-quick-view-group-item-content-element`) needed for bind the corresponding label to the element (email, phone, link, etc.)
Closes: SAP/fundamental-ngx#4963
- readable corresponding label
- focus trap & close on ESC for popover and dialog variants 
=> fix(core): fix Quick View Accessibility issues

apps/docs/src/app/core/component-docs/grid-list/examples/default/grid-list-example.component.html, apps/docs/src/app/core/component-docs/grid-list/examples/default/grid-list-example.component.ts, apps/docs/src/app/core/component-docs/grid-list/examples/delete/grid-list-delete-example.component.ts, apps/docs/src/app/core/component-docs/grid-list/examples/dnd/grid-list-dnd-example.component.html, apps/docs/src/app/core/component-docs/grid-list/examples/dnd/grid-list-dnd-example.component.ts, apps/docs/src/app/core/component-docs/grid-list/examples/multi-select/grid-list-multi-select-example.component.ts, apps/docs/src/app/core/component-docs/grid-list/examples/single-select-left/grid-list-single-select-left-example.component.ts, apps/docs/src/app/core/component-docs/grid-list/examples/single-select-right/grid-list-single-select-right-example.component.ts, apps/docs/src/app/core/component-docs/grid-list/examples/single-select/grid-list-single-select-example.component.ts, e2e/wdio/core/pages/grid-list.po.ts, libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html, libs/core/src/lib/grid-list/components/grid-list/grid-list.component.html
Closes SAP/fundamental-ngx#4666
This PR does the following:
- adds appropriate `aria-labelledby` fields to convey the header details
- for single select mode, radio button info was being read; therefore hiding the display of radio button from screen readers.
- added appropriate roles for the list items count to be read.
- clicks on buttons were not performing any action according to the issue: console logs were present, but added alerts instead so that it looks like an action has taken place.
- added `aria-selected` attribute conditionally to read for the different grid list modes.
- [n/a] [Breaking Changes …
=> fix(core): fix a11y for Grid List component

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/component-docs/avatar-group/avatar-group-docs.module.ts, apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-group-type-example.component.html, apps/docs/src/app/core/component-docs/avatar-group/examples/avatar-group-individual-type-example.component.html, libs/core/src/lib/avatar-group/avatar-group.component.ts, libs/core/src/lib/avatar-group/avatar-group.module.ts, libs/core/src/lib/avatar-group/directives/avatar-group-popover-control.directive.spec.ts, libs/core/src/lib/avatar-group/directives/avatar-group-popover-control.directive.ts, libs/core/src/lib/avatar-group/public_api.ts
added `AvatarGroupPopoverControlDirective` (`fd-avatar-group-popover-control`) needed to bind the corresponding CSS class and attributes to group type overflow popover control.
Closes https://github.com/SAP/fundamental-ngx/issues/5575
- a11y issues in examples
- new directive for styling group type popover control
- [N/A] update `README.md`
=> fix(core): fix Avatar Group's popover control styles & enhance a11y

apps/docs/src/app/core/component-docs/facets/facet-examples/facet-group-example.component.html, apps/docs/src/app/core/component-docs/facets/facet-examples/form-link-facet-example.component.html, apps/docs/src/app/core/component-docs/facets/facet-examples/image-facet-example.component.html
Closes SAP/fundamental-ngx#5577
This PR fixes:
- missing tooltip on image facets- added title attribute
- missing focus is a separate issue that is already being worked on in Styles; this is elaborated in the issue 5577 comments
- incorrect reading of form facet with links example- added appropriate aria tags
- incorrect reading of rating indicator facet example- related to rating indicator component, a11y/qa to raise separate issue
=> docs(core): fix a11y for Facets component

libs/core/src/lib/time/time.component.ts
Closes SAP/fundamental-ngx#4428
This PR fixes the logic on changing the meridian. It was miscalculating the display hours and adding/subtracting 12 hours extra. For eg: if time set was 1 PM and user clicked on PM again, it would calculate 13hrs+12hrs= 25hrs and take `Math.min` of 23hrs and set time as 11 PM.
=> fix(core): fix meridian switch changing hour display in Time component

libs/core/src/lib/datetime/datetime-format.pipes.ts
Quick fix for the datetime pipes, making the error message string parameter optional
=> fix(core): make no date message optional

libs/platform/src/lib/components/form/combobox/combobox/combobox.component.html
`fd-input-group` does not have a `[readOnly]` input property. Temporary remove it from the template until it's introduced properly.
=> fix(platform): remove the readonly prop from combobox

apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.html
Closes #5679
Removed multiple overflow options from action bar examples to avoid duplication.
=> docs(core): remove multiple overflow options from action bar
