- docs/modules/documentation/containers/badge-label/badge-label-docs.component.html
- docs/modules/documentation/containers/button-group/button-group-docs.component.html
- docs/modules/documentation/containers/button/button-docs.component.html
- docs/modules/documentation/containers/image/image-docs.component.html
- docs/modules/documentation/containers/inline-help/inline-help-docs.component.html
#52 
enhancement
Added margins between components that were touching in the docs
> docs: add margins between components that are touching

- docs/modules/documentation/components/documentation/documentation.component.ts
- docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.html
- docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- projects/fundamental-ngx/src/lib/fundamental-ngx.module.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-group.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-group.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-icon.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-icon.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-icons.directive.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-item.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-item.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-link.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-link.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-list.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-list.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-subitem.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-subitem.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-sublist.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-sublist.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-title.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-title.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation.component.ts
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation.module.ts
https://github.com/SAP/fundamental-ngx/issues/79
Implement side navigation 
enhancement
> Issue#79 Side Navigation component implementation

- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-icon.component.ts
> add missing property presentation to side-navigation-icon

- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-icon.component.html
- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-icon.component.ts
> side-navigation-icon set the presentation as string

- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html
- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.ts
- docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.html
- docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.ts
- projects/fundamental-ngx/src/lib/breadcrumb/breadcrumb-item.component.html
- projects/fundamental-ngx/src/lib/breadcrumb/breadcrumb-item.component.ts
#83 
Links should support URL's and routerLinks
> feat: links should support both URL inputs and routerLinks

- docs/modules/documentation/containers/dropdown/dropdown-docs.component.html
- docs/modules/documentation/containers/dropdown/dropdown-docs.component.ts
- projects/fundamental-ngx/src/lib/dropdown/dropdown.component.html
- projects/fundamental-ngx/src/lib/dropdown/dropdown.component.ts
https://github.com/SAP/fundamental-ngx/issues/87
Adds text button for the contextual menu, adds noBorder property for the dropdown
> Issue#87 Text button for contextual menu

- docs/modules/documentation/containers/icon/icon-docs.component.html
- docs/modules/documentation/containers/icon/icon-docs.component.ts
- projects/fundamental-ngx/src/lib/icon/icon.directive.ts
#93 
at the moment the icon component wipes any custom class
> #93 update icon to support custom class

- docs/modules/documentation/containers/action-bar/action-bar-docs.component.html
- docs/modules/documentation/containers/action-bar/action-bar-docs.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar-actions.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar-actions.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar-back.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar-back.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar-description.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar-description.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar-header.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar-header.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar-mobile.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar-mobile.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar-title.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar.component.html
- projects/fundamental-ngx/src/lib/action-bar/action-bar.component.ts
- projects/fundamental-ngx/src/lib/action-bar/action-bar.module.ts
[Issue#116](https://github.com/SAP/fundamental-ngx/issues/116)
*****
`host: { class: 'some-class'}` allows the user to set up custom classes and does not overwrite them as in the case with dynamic classes - `host: { '[class]': 'some-class'}` 
*****
- adds back button `fd-action-bar-back`
- adds title and description for the Action Bar header
- removes the Action Bar input property for title (now title is a component).
- adds an `fd-action-bar-actions` component for the main actions. 
- adds a mobile view for the Action Bar `fd-action-bar-mobile`
> Issue#116 Refactor Action Bar

- projects/fundamental-ngx/src/lib/badge-label/badge.component.ts
- projects/fundamental-ngx/src/lib/badge-label/label.component.ts
- projects/fundamental-ngx/src/lib/button-group/button-grouped.directive.ts
- projects/fundamental-ngx/src/lib/button/button.directive.ts
- projects/fundamental-ngx/src/lib/form/form-control.directive.ts
- projects/fundamental-ngx/src/lib/form/form-item.component.ts
- projects/fundamental-ngx/src/lib/icon/icon.directive.ts
- projects/fundamental-ngx/src/lib/identifier/identifier.directive.ts
- projects/fundamental-ngx/src/lib/navbar/navbar-group.directive.ts
- projects/fundamental-ngx/src/lib/tile/product-tile.component.ts
- projects/fundamental-ngx/src/lib/tile/tile-grid.directive.ts
- projects/fundamental-ngx/src/lib/tile/tile.component.ts
- projects/fundamental-ngx/src/lib/utils/abstract-custom-style-manager.ts
- projects/fundamental-ngx/src/lib/utils/abstract-fd-ngx-class.ts
#100 
Sorry I'm issuing another PR for this issue... but I want to rename the file and rephrase code comments so the purpose of this class is more obvious ("class" is vague and can mean many things which i think could be confusing down the road, "style" is a little more specific)
> refactor: rename style and rephrase code comments

- docs/modules/documentation/components/documentation/documentation.component.ts
- docs/modules/documentation/containers/popover/popover-docs.component.html
- docs/modules/documentation/containers/popover/popover-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- projects/fundamental-ngx/src/lib/fundamental-ngx.module.ts
- projects/fundamental-ngx/src/lib/popover/popover-body.component.html
- projects/fundamental-ngx/src/lib/popover/popover-body.component.ts
- projects/fundamental-ngx/src/lib/popover/popover-control.component.html
- projects/fundamental-ngx/src/lib/popover/popover-control.component.ts
- projects/fundamental-ngx/src/lib/popover/popover.component.html
- projects/fundamental-ngx/src/lib/popover/popover.component.ts
- projects/fundamental-ngx/src/lib/popover/popover.module.ts
[Issue#102](https://github.com/SAP/fundamental-ngx/issues/102)
- implements [popover](https://sap.github.io/fundamental/components/popover.html) component released in fundamental-ui v. 1.1
- the popover body is closed by clicking on the popover control element, anywhere on the DOM, or with the esc key. Only one dropdown body stays open as per requirements in fundamental-ui
> Feature/popover v1.1

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
update README.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
#139 
Updating the md files
> update md files

- docs/modules/documentation/containers/navbar/navbar-docs.component.html
- projects/fundamental-ngx/src/lib/popover/popover.component.ts
> #150 fix console erros during build

- docs/modules/documentation/containers/alert/alert-docs.component.ts
- docs/modules/documentation/containers/button/button-docs.component.ts
- docs/modules/documentation/containers/form/form-docs.component.ts
- docs/modules/documentation/containers/icon/icon-docs.component.ts
- docs/modules/documentation/containers/input-group/input-group-docs.component.html
- docs/modules/documentation/containers/input-group/input-group-docs.component.ts
- docs/modules/documentation/containers/list/list-docs.component.ts
- docs/modules/documentation/containers/tabs/tabs-docs.component.ts
My last push didn't go through
> use multiline strings in example code throughout the app

- projects/fundamental-ngx/src/lib/input-group/input-group-number.component.html
[#157](https://github.com/SAP/fundamental-ngx/issues/157)
adds arrow up and arrow down for the number input
> Issue#157 fixes the issue with the missing arrows in the number input

- docs/modules/documentation/containers/tile/tile-docs.component.ts
#159 
fix a type in tile-docs.component.ts
> #159 fix a build issue in tile-docs.component.ts

- docs/modules/documentation/containers/action-bar/action-bar-docs.component.html
- docs/modules/documentation/containers/alert/alert-docs.component.html
- docs/modules/documentation/containers/badge-label/badge-label-docs.component.html
- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html
- docs/modules/documentation/containers/button-group/button-group-docs.component.html
- docs/modules/documentation/containers/button/button-docs.component.html
- docs/modules/documentation/containers/dropdown/dropdown-docs.component.html
- docs/modules/documentation/containers/form/form-docs.component.html
- docs/modules/documentation/containers/form/form-docs.component.ts
- docs/modules/documentation/containers/icon/icon-docs.component.html
- docs/modules/documentation/containers/identifier/identifier-docs.component.html
- docs/modules/documentation/containers/image/image-docs.component.html
- docs/modules/documentation/containers/inline-help/inline-help-docs.component.html
- docs/modules/documentation/containers/input-group/input-group-docs.component.html
- docs/modules/documentation/containers/list/list-docs.component.html
- docs/modules/documentation/containers/mega-menu/mega-menu-docs.component.html
- docs/modules/documentation/containers/menu/menu-docs.component.html
- docs/modules/documentation/containers/modal/modal-docs.component.html
- docs/modules/documentation/containers/modal/modal-docs.component.ts
- docs/modules/documentation/containers/navbar/navbar-docs.component.html
- docs/modules/documentation/containers/pagination/pagination-docs.component.html
- docs/modules/documentation/containers/panel/panel-docs.component.html
- docs/modules/documentation/containers/panel/panel-docs.component.ts
- docs/modules/documentation/containers/popover/popover-docs.component.html
- docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.html
- docs/modules/documentation/containers/table/table-docs.component.html
- docs/modules/documentation/containers/tabs/tabs-docs.component.html
- docs/modules/documentation/containers/tile/tile-docs.component.html
- docs/modules/documentation/containers/tree/tree-docs.component.html
[Issue#133](https://github.com/SAP/fundamental-ngx/issues/133)
> Issue#133 fixes the binding syntax inconsistency in documentation

- docs/modules/documentation/containers/action-bar/action-bar-docs.component.html
- docs/modules/documentation/containers/action-bar/action-bar-docs.component.ts
[Issue#162](https://github.com/SAP/fundamental-ngx/issues/162)
> Issue#162 changes the type property of fd-button to fdType

- docs/app/components/home/home.component.scss
- docs/modules/documentation/components/documentation/documentation.component.html
- docs/modules/documentation/components/documentation/documentation.component.scss
> #169 match fdui nav bar styling

- docs/modules/documentation/components/documentation/documentation.component.html
- docs/modules/documentation/containers/button/button-docs.component.html
- docs/modules/documentation/containers/internationalization/internationalization.component.html
- docs/modules/documentation/containers/internationalization/internationalization.component.ts
- docs/modules/documentation/documentation.module.ts
#135 
Add a new documentation page that shows examples in LTR and RTL mode
> #135 add globalization page with examples

- docs/modules/documentation/containers/internationalization/internationalization.component.ts
- projects/fundamental-ngx/package.json
> #183 add alertHtml and showAlert

- projects/fundamental-ngx/src/lib/input-group/input-group.component.html
> #185 add an input parameter to the methond inputChanged

- docs/modules/documentation/components/documentation/documentation.component.ts
- docs/modules/documentation/containers/calendar/calendar-docs.component.html
- docs/modules/documentation/containers/calendar/calendar-docs.component.ts
- docs/modules/documentation/containers/date-picker/date-picker-docs.component.html
- docs/modules/documentation/containers/date-picker/date-picker-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- projects/fundamental-ngx/src/lib/calendar/calendar.component.html
- projects/fundamental-ngx/src/lib/calendar/calendar.component.scss
- projects/fundamental-ngx/src/lib/calendar/calendar.component.ts
- projects/fundamental-ngx/src/lib/calendar/calendar.module.ts
- projects/fundamental-ngx/src/lib/date-picker/date-picker.component.html
- projects/fundamental-ngx/src/lib/date-picker/date-picker.component.scss
- projects/fundamental-ngx/src/lib/date-picker/date-picker.component.ts
- projects/fundamental-ngx/src/lib/date-picker/date-picker.module.ts
- projects/fundamental-ngx/src/lib/fundamental-ngx.module.ts
[Issue #165 ](https://github.com/SAP/fundamental-ngx/issues/165)
- Calendar implementation
- Date picker implementation
yes
> Calendar and Date Picker components implementation

- projects/fundamental-ngx/src/lib/table/table.component.ts
#199 
convert table.calculateColumnWidth to public
> #199 make convert table.calculateColumnWidth to public

- projects/fundamental-ngx/src/lib/table/table.component.html
- projects/fundamental-ngx/src/lib/table/table.component.ts
- projects/fundamental-ngx/src/lib/tree/tree.component.ts
> fix bug where non-string values for simple table does not display

- docs/modules/documentation/containers/installation/installation.component.html
#210 
specify ng-bootstrap v.2.2.2
> #210 specify ng-bootstrap version in the intallation guide

- projects/fundamental-ngx/src/lib/menu/menu-item.component.html
- projects/fundamental-ngx/src/lib/menu/menu-item.component.ts
With the previous implementation, the component would override any class set by the user
> menu item should be less opinionated about cursor

- docs/modules/documentation/components/RTL/RTLToggle.component.ts
- docs/modules/documentation/documentation.module.ts
Add New component as Toggle to test/simulate the RTL behavior for each components.
> Update documentation to support RTL testing for components.

- docs/styles.scss
- package.json
- projects/fundamental-ngx/src/lib/icon/icon.directive.ts
- **Icon-Component:** Update Icon Component; add support to take new parameter for "Glyph-Group" other then SAP-- Icon, following the same convention of **"<glyph-group>-icon--"**.
- **Style.scss:** Add Ariba font-Icon SCSS to documentation style.
- **Package.json:** Update Fundamental-UI package reference to 'develop-ariba' branch to pull ariba theme artifacts.
>  Update Icon component with Ariba-Icons

- CONTRIBUTING.md
> Update contact  information

- package.json
- projects/fundamental-ngx/package.json
#237 fix issue with gh pages build and publish
fix the issue
> #237 fix an issue during gh page build and publish

- docs/modules/documentation/components/component-example/component-example.component.ts
- package-lock.json
- package.json
#237 downgrade to fundamental-ui 1.1 and hide RTL toggle
> #237 downgrade to fundamental-ui 1.1 and hide RTL mode

- docs/modules/documentation/components/documentation/documentation.component.html
- docs/modules/documentation/containers/input-group/input-group-docs.component.html
- docs/modules/documentation/containers/input-group/input-group-docs.component.ts
- projects/fundamental-ngx/src/lib/input-group/input-group-number.component.spec.ts
- projects/fundamental-ngx/src/lib/input-group/input-group-number.component.ts
- projects/fundamental-ngx/src/lib/input-group/input-group-search.component.html
- projects/fundamental-ngx/src/lib/input-group/input-group-search.component.spec.ts
- projects/fundamental-ngx/src/lib/input-group/input-group-search.component.ts
- projects/fundamental-ngx/src/lib/input-group/input-group.component.html
- projects/fundamental-ngx/src/lib/input-group/input-group.component.ts
- projects/fundamental-ngx/src/lib/time-picker/time-picker.component.html
- projects/fundamental-ngx/src/lib/time-picker/time-picker.component.ts
Input Group should implement ControlValueAccessor, enabling the use of ngModel, form state/validity, etc
> input group should implement ControlValueAccessor

- docs/modules/documentation/components/documentation/documentation.component.html
#241 
allow search by upper/lower case term
> #241 fix a bug with component search

- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html
- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.ts
> #248 bring breadcrumb url example back

- docs/modules/documentation/components/documentation/documentation.component.html
> #241 search components by name or url params

- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html
- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.ts
> #248 fix typos and update markup

- projects/fundamental-ngx/src/lib/input-group/input-group.component.html
> #257 fix an issue in input group with a missing handler

- README.md
Added the live demo link to the README.md for easy access and discovery
> docs: add links to live demo to README.md(#263)

- projects/fundamental-ngx/src/lib/menu/menu-item.component.ts
Fix bug where menu items without links were not displaying property
> fix menu styling bug

- projects/fundamental-ngx/src/lib/side-navigation/side-navigation-link.component.ts
fix bug where class is not applied to side navigation items that are not anchors
> side navigation styling bug

- projects/fundamental-ngx/src/lib/calendar/calendar.component.ts
> fix bug where user can select disabled dates with the keyboard

- projects/fundamental-ngx/src/lib/calendar/calendar.component.ts
> fix bug where newly selected day loses focus

- docs/modules/documentation/containers/date-picker/date-picker-docs.component.html
- docs/modules/documentation/containers/date-picker/examples/date-picker-single-example.component.ts
- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/date-picker/date-picker.component.ts
https://github.com/SAP/fundamental-ngx/issues/289
Added compact mode to date picker.
> #289 added compact mode to date picker component

- docs/modules/documentation/containers/button/button-docs.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-contextual-menu-example.component.html
- docs/modules/documentation/containers/internationalization/internationalization.component.html
- docs/modules/documentation/containers/internationalization/internationalization.component.ts
- docs/modules/documentation/containers/list/examples/list-actions-example.component.html
- docs/modules/documentation/containers/modal/examples/modal-confirmation-example.component.ts
- docs/modules/documentation/containers/navbar/examples/navbar-example.component.html
- docs/modules/documentation/containers/tile/examples/tile-actions-example.component.html
- docs/modules/documentation/containers/tile/tile-docs.component.html
- library/src/lib/calendar/calendar.component.html
- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/input-group/input-group.component.html
- library/src/lib/time-picker/time-picker.component.html
- library/src/lib/time/time.component.html
- library/src/lib/tree/tree-child.component.html
https://github.com/SAP/fundamental-ngx/issues/325
https://github.com/SAP/fundamental-ngx/issues/295
Swap button type secondary to options light.
> #295 and #325 to swap type secondary to options light buttons

- docs/modules/documentation/containers/popover/examples/popover-example.component.html
- library/src/lib/popover/popover.component.html
- library/src/lib/popover/popover.component.ts
https://github.com/SAP/fundamental-ngx/issues/320
Added options for popover alignment and popover arrow absence.
> #320 refactored to add dropdown alignment and no arrow options

- docs/modules/documentation/containers/time-picker/examples/time-picker-compact-example.component.html
- docs/modules/documentation/containers/time-picker/examples/time-picker-examples.component.ts
- docs/modules/documentation/containers/time-picker/time-picker-docs.component.html
- docs/modules/documentation/containers/time-picker/time-picker-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/time-picker/time-picker.component.html
- library/src/lib/time-picker/time-picker.component.ts
https://github.com/SAP/fundamental-ngx/issues/296
Added compact mode to time-picker and adapted this to docs.
> Feature/#296 add compact mode to time-picker

- library/src/lib/modal/modal.component.scss
> fix modal causing window to shrink

- package-lock.json
- package.json
#343 
the old version of ng-bootstrap is causing an error during the doc build
> #343 fix the doc build

- README.md
- docs/app/app.module.ts
- docs/modules/documentation/containers/installation/installation.component.html
- docs/modules/documentation/containers/modal/examples/modal-confirmation-example.component.ts
- docs/modules/documentation/containers/modal/examples/modal-example.component.ts
- library/README.md
- library/package.json
- library/src/lib/fundamental-ngx.module.ts
- library/src/lib/modal/modal-header.component.spec.ts
- library/src/lib/modal/modal.component.html
- library/src/lib/modal/modal.component.scss
- library/src/lib/modal/modal.component.spec.ts
- library/src/lib/modal/modal.component.ts
- library/src/lib/modal/modal.module.ts
- library/src/lib/modal/modal.service.spec.ts
- library/src/lib/modal/modal.service.ts
- library/src/lib/navbar/navbar.component.spec.ts
- package-lock.json
- package.json
> refactor modal and remove ng-bootstrap dependency

- docs/modules/documentation/containers/breadcrumb/breadcrumb-docs.component.html
- docs/modules/documentation/containers/button-group/button-group-docs.component.html
- docs/modules/documentation/containers/button/button-docs.component.html
- docs/modules/documentation/containers/calendar/calendar-docs.component.html
- docs/modules/documentation/containers/date-picker/date-picker-docs.component.html
- docs/modules/documentation/containers/dropdown/dropdown-docs.component.html
- docs/modules/documentation/containers/form/form-docs.component.html
- docs/modules/documentation/containers/list/list-docs.component.html
- docs/modules/documentation/containers/menu/menu-docs.component.html
- docs/modules/documentation/containers/pagination/pagination-docs.component.html
- docs/modules/documentation/containers/popover/popover-docs.component.html
- docs/modules/documentation/containers/side-navigation/side-navigation-docs.component.html
- docs/modules/documentation/containers/tabs/tabs-docs.component.html
- docs/modules/documentation/containers/time-picker/time-picker-docs.component.html
- docs/modules/documentation/containers/time/time-docs.component.html
- library/src/lib/popover/popover.component.ts
- library/src/lib/time-picker/time-picker.component.html
- library/src/lib/time-picker/time-picker.component.ts
> keyboard support docs

- library/package.json
- package-lock.json
- package.json
> update fundamentals version

- docs/modules/documentation/containers/form/examples/form-checkbox-example.component.html
- docs/modules/documentation/containers/form/examples/form-example.component.html
- library/src/lib/form/form-label.component.html
- library/src/lib/form/form-label.component.ts
> update required form label docs

- docs/modules/documentation/containers/action-bar/examples/action-bar-contextual-menu-example.component.html
- docs/modules/documentation/containers/action-bar/examples/action-bar-mobile-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-contextual-menu-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-default-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-icons-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-state-example.component.html
- docs/modules/documentation/containers/menu/examples/menu-example.component.html
- docs/modules/documentation/containers/menu/examples/menu-group-example.component.html
- docs/modules/documentation/containers/popover/examples/popover-example.component.html
- docs/modules/documentation/containers/tile/examples/tile-actions-example.component.html
- docs/modules/documentation/containers/tile/tile-docs.component.html
- library/src/lib/combobox-input/combobox-input.component.html
- library/src/lib/menu/menu-item.component.ts
- library/src/lib/menu/menu-list.component.html
- library/src/lib/search-input/search-input.component.html
- library/src/lib/shellbar/product-menu.component.html
- library/src/lib/shellbar/shellbar-actions.component.html
- library/src/lib/tree/tree-child.component.html
> menu items should use <li>

- docs/modules/documentation/containers/modal/examples/modal-component-as-content-example.component.ts
- docs/modules/documentation/containers/modal/examples/modal-confirmation-example.component.ts
- docs/modules/documentation/containers/modal/examples/modal-content.component.ts
- docs/modules/documentation/containers/modal/examples/modal-example.component.ts
- docs/modules/documentation/containers/modal/modal-docs.component.html
- docs/modules/documentation/containers/modal/modal-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/modal/modal-header.component.html
- library/src/lib/modal/modal.component.ts
- library/src/lib/modal/modal.service.spec.ts
- library/src/lib/modal/modal.service.ts
- library/src/public_api.ts
> modal handles promises, open function accepts component as parameter

- docs/modules/documentation/containers/toggle/examples/disabled-toggle-example/disabled-toggle-example.component.html
- docs/modules/documentation/containers/toggle/examples/disabled-toggle-example/disabled-toggle-example.component.ts
- docs/modules/documentation/containers/toggle/examples/toggle-binding-example/toggle-binding-example.component.html
- docs/modules/documentation/containers/toggle/examples/toggle-sizes-example/toggle-sizes-example.component.html
- docs/modules/documentation/containers/toggle/examples/toggle-sizes-example/toggle-sizes-example.component.ts
- docs/modules/documentation/containers/toggle/toggle-docs.component.html
- library/src/lib/toggle/toggle.component.html
- library/src/lib/toggle/toggle.component.spec.ts
- library/src/lib/toggle/toggle.component.ts
- library/src/lib/toggle/toggle.module.ts
#421 
Add support for ngModel on toggle
> toggle handles ngModel

- docs/modules/documentation/containers/list/examples/list-single-select-example.component.html
- docs/modules/documentation/containers/list/examples/list-single-select-example.component.ts
- docs/modules/documentation/containers/list/list-docs.component.html
- docs/modules/documentation/containers/list/list-docs.component.ts
- docs/modules/documentation/containers/toggle/toggle-docs.component.html
- docs/modules/documentation/documentation.module.ts
- library/src/lib/list/list-checkbox.component.html
- library/src/lib/list/list-checkbox.component.spec.ts
- library/src/lib/list/list-checkbox.component.ts
- library/src/lib/list/list.module.ts
#422 
Added an example on single-selection lists that follow the [Fiori](https://experience.sap.com/fiori-design-web/list-overview/#mode) radio button guidelines.
Also added more input functionality with list-checkbox.
Yes
[![Image from Gyazo](https://i.gyazo.com/255edbda409cefd4a34cc96e6e5a6502.gif)](https://gyazo.com/255edbda409cefd4a34cc96e6e5a6502)
> Enhancement/#422 added single selection + updated list checkbox

- library/src/lib/modal/modal.component.html
- library/src/lib/modal/modal.component.scss
> use fd-overlay/fd-overlay--modal

- docs/modules/documentation/containers/panel/examples/panel-example.component.html
- docs/modules/documentation/containers/panel/examples/panel-examples.component.ts
- docs/modules/documentation/containers/panel/examples/panel-grid-column-span-example.component.html
- docs/modules/documentation/containers/panel/examples/panel-grid-example.component.html
- docs/modules/documentation/containers/panel/examples/panel-grid-nogap-example.component.html
- docs/modules/documentation/containers/panel/panel-docs.component.html
- docs/modules/documentation/containers/panel/panel-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/panel/panel.component.html
- library/src/lib/panel/panel.component.spec.ts
- library/src/lib/panel/panel.component.ts
> update panel to match fiori-fundamentals

- docs/modules/documentation/containers/calendar/calendar-docs.component.html
- docs/modules/documentation/containers/calendar/examples/calendar-monday-start-example.component.ts
- docs/modules/documentation/containers/calendar/examples/calendar-range-example.component.ts
- docs/modules/documentation/containers/calendar/examples/calendar-single-example.component.ts
- docs/modules/documentation/containers/date-picker/date-picker-docs.component.html
- docs/modules/documentation/containers/date-picker/examples/date-picker-range-example.component.ts
- docs/modules/documentation/containers/date-picker/examples/date-picker-single-example.component.ts
- library/src/lib/calendar/calendar.component.ts
- library/src/lib/date-picker/date-picker.component.ts
Part of #421 
Refactors the datepicker-calendar interaction and adds ngModel/forms support for both.
@mikerodonnell89 I encourage you to boot my branch up and try to break it. I tested all the functionalities, but it's possible that some cases could escape.
yes
> Enhancement/#421 datepicker + calendar ngmodel

- docs/modules/documentation/containers/popover/examples/popover-programmatic-open-example.component.html
- docs/modules/documentation/containers/popover/examples/popover-programmatic-open-example.component.ts
- docs/modules/documentation/containers/popover/popover-docs.component.html
- docs/modules/documentation/containers/popover/popover-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/popover/popover.component.ts
> make open/close functions public, add docs

- docs/modules/documentation/containers/dropdown/dropdown-docs.component.html
- docs/modules/documentation/containers/dropdown/dropdown-docs.component.ts
- docs/modules/documentation/containers/dropdown/examples/dropdown-examples.component.ts
- docs/modules/documentation/containers/dropdown/examples/dropdown-toolbar-example.component.html
- docs/modules/documentation/documentation.module.ts
- library/src/lib/popover/popover.component.html
- library/src/lib/popover/popover.component.ts
> add toolbar dropdown and docs

- library/src/lib/calendar/calendar.component.ts
- library/src/lib/date-picker/date-picker.component.spec.ts
> select new date when user clicks new month or year

- library/package.json
> chore: #494 add description to package.json

- library/src/lib/calendar/calendar.component.ts
> do not automatically update date when selecting new month/year

- docs/modules/documentation/containers/dropdown/examples/dropdown-contextual-menu-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-default-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-examples.component.ts
- docs/modules/documentation/containers/dropdown/examples/dropdown-icons-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-state-example.component.html
- docs/modules/documentation/containers/dropdown/examples/dropdown-toolbar-example.component.html
- docs/modules/documentation/containers/popover/examples/popover-example.component.html
- docs/modules/documentation/containers/popover/examples/popover-example.component.ts
- docs/modules/documentation/containers/popover/popover-docs.component.html
- library/src/lib/popover/popover.component.html
- library/src/lib/popover/popover.component.ts
> hide popover body if contents are empty

- library/src/public_api.ts
> add alert service to public api

- .gitignore
- library/package-lock.json
- library/package.json
This fix updates package.json to include missing dependencies. See: https://bundlephobia.com/result?p=fundamental-ngx@0.0.33
> fix: bundlephobia errors

- docs/modules/documentation/components/component-example/component-example.component.ts
- package-lock.json
- package.json
> chore: #510 enable RTL toggle in the documentation

- docs/modules/documentation/containers/file-input/examples/file-input-custom-example/file-input-custom-example.component.html
- docs/modules/documentation/containers/file-input/file-input-docs.component.html
- library/src/lib/file-input/directives/file-dragndrop.directive.ts
- library/src/lib/file-input/file-input.component.html
- library/src/lib/file-input/file-input.component.spec.ts
- library/src/lib/file-input/file-input.component.ts
- package-lock.json
fixes #515 
- Removed some events that were not super useful and fired a lot. 
- Optimized other events to only emit once per drop cycle.
- Updated docs
> feat: file-input optimization

- angular.json
> chore: #531 fix the path to tsconfig files

- docs/modules/documentation/components/documentation/documentation.component.ts
- docs/modules/documentation/containers/datetime-picker/datetime-picker-docs.component.html
- docs/modules/documentation/containers/datetime-picker/datetime-picker-docs.component.ts
- docs/modules/documentation/containers/datetime-picker/examples/datetime-example/datetime-example.component.html
- docs/modules/documentation/containers/datetime-picker/examples/datetime-example/datetime-example.component.ts
- docs/modules/documentation/containers/datetime-picker/examples/datetime-non-meridian-example/datetime-non-meridian-example.component.html
- docs/modules/documentation/containers/datetime-picker/examples/datetime-non-meridian-example/datetime-non-meridian-example.component.ts
- docs/modules/documentation/containers/datetime-picker/examples/datetime-program-example/datetime-program-example.component.html
- docs/modules/documentation/containers/datetime-picker/examples/datetime-program-example/datetime-program-example.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/calendar/calendar.component.ts
- library/src/lib/datetime-picker/datetime-picker.component.html
- library/src/lib/datetime-picker/datetime-picker.component.scss
- library/src/lib/datetime-picker/datetime-picker.component.spec.ts
- library/src/lib/datetime-picker/datetime-picker.component.ts
- library/src/lib/datetime-picker/datetime-picker.module.ts
- library/src/lib/fundamental-ngx.module.ts
- library/src/lib/time/time.component.html
- library/src/lib/time/time.component.ts
- library/src/public_api.ts
> feat: #431 datetime picker

- docs/modules/documentation/containers/modal/examples/modal-example.component.ts
- docs/modules/documentation/containers/modal/examples/modal-fullscreen-example.component.ts
- docs/modules/documentation/containers/modal/modal-docs.component.html
- docs/modules/documentation/containers/modal/modal-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/modal/modal.component.html
- library/src/lib/modal/modal.component.spec.ts
- library/src/lib/modal/modal.component.ts
fixes #522 
Allows more control over modal sizing for users.
> feat: add height/width inputs to modal

- library/src/lib/modal/modal.component.ts
- library/src/lib/modal/modal.service.ts
- package-lock.json
fixes #524 
Added a Subject to the modal component, which is subscribed to when the modal is first opened. When the modal is closed, it triggers the subscription and removes the dom element from the body.
I need thoughts on this solution. @mikerodonnell89 for next week when you're done skiing!
> fix: dynamically generated modals should destroy on close

- ci-scripts/publish-rc.sh
- ci-scripts/publish.sh
add npm install to publish scripts
> chore: add npm install to script

- CHANGELOG.md
- ci-scripts/publish.sh
- library/package-lock.json
- library/package.json
- package-lock.json
- package.json
angular-cli-ghpages was missing from the dev dependencies, needed to publish docs site from Travis
> chore: add dependency

- library/src/lib/toggle/toggle.component.spec.ts
fixes #555 
Added some tests for the toggle component
> fix: added toggle tests

- CONTRIBUTING.md
- README.md
> chore: #550 update README.md and CONTRIBUTING.md reflecting semantic versioning

- docs/modules/documentation/components/documentation/documentation.component.html
- docs/modules/documentation/components/documentation/documentation.component.ts
> chore: move search input to top of side nav

- NOTICE.txt
> chore: #569 bump the year

- CHANGELOG.md
- library/package-lock.json
- library/package.json
Manual bump to fix travis failure.
> fix: manual bump to fix travis

- library/src/lib/alert/alert.component.spec.ts
- library/src/lib/calendar/calendar.component.ts
- library/src/lib/date-picker/date-picker.component.ts
- library/src/lib/tile/product-tile.component.ts
- library/src/lib/tile/tile.component.ts
- tslint.yaml
> chore: #585 auto fixing lint errors

- README.md
> chore: update readme to show how to use toggles

- docs/app/app.module.ts
- library/package.json
- library/src/lib/breadcrumb/breadcrumb.module.ts
- library/src/lib/fundamental-ngx.module.ts
> fix: remove router dependency from library

- docs/modules/documentation/containers/pagination/examples/pagination-example.component.ts
- docs/modules/documentation/containers/pagination/pagination-docs.component.html
- docs/modules/documentation/containers/pagination/pagination-docs.component.ts
- docs/styles.scss
- library/src/lib/pagination/pagination.component.html
- library/src/lib/pagination/pagination.component.spec.ts
- library/src/lib/pagination/pagination.component.ts
- library/src/lib/pagination/pagination.service.ts
fixes #598 
@droshev I was also thinking about removing the [pagination] input and replacing it with individual [totalItems], [currentPage] and [itemsPerPage] inputs, thoughts?
> fix: clean up pagination component

- README.md
- Fixed some punctuation issues.
- Replaced text in the getting started section with actual code.
- Replaced the reference to [(ngModel)] in the getting started section with [(checked)]. The ngModel would not work without FormsModule and we weren't mentioning that.
> chore: updated/cleaned readme

- docs/assets/multi-input-values.json
- docs/modules/documentation/containers/multi-input/examples/multi-input-async-example/multi-input-async-example.component.html
- docs/modules/documentation/containers/multi-input/examples/multi-input-async-example/multi-input-async-example.component.ts
- docs/modules/documentation/containers/multi-input/multi-input-docs.component.html
- docs/modules/documentation/containers/multi-input/multi-input-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/multi-input/multi-input.component.ts
> feat: demonstrate multi-input observable support

- library/ng-package.json
- library/ng-package.prod.json
fixes #635 
whitelisted popper.js
> chore: whitelist popper.js

- library/src/lib/calendar/calendar.component.html
- library/src/lib/calendar/calendar.component.spec.ts
- library/src/lib/calendar/calendar.component.ts
> fix: do not close calendar when selecting month/year/date

- library/src/lib/combobox-input/combobox-input.component.html
- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/datetime-picker/datetime-picker.component.html
- library/src/lib/multi-input/multi-input.component.html
> fix: add type="button" to form components where the button should not submit

- docs/modules/documentation/components/documentation/documentation.component.scss
- docs/modules/documentation/components/toolbar/toolbar.component.scss
fixes #647 
Should fix display issue on chrome mobile.
> fix: fixed docs on chrome mobile

- docs/assets/search-input-values.json
- docs/modules/documentation/containers/search-input/examples/search-input-async-example.component.html
- docs/modules/documentation/containers/search-input/examples/search-input-async-example.component.ts
- docs/modules/documentation/containers/search-input/search-input-docs.component.html
- docs/modules/documentation/containers/search-input/search-input-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/search-input/search-input.component.html
- library/src/lib/search-input/search-input.component.ts
> fix: search input observable support and examples

- docs/environments/environment.hmr.ts
- docs/environments/environment.prod.ts
- docs/environments/environment.ts
- docs/index.html
- docs/modules/documentation/components/toolbar/toolbar.component.html
- docs/modules/documentation/components/toolbar/toolbar.component.scss
- docs/modules/documentation/components/toolbar/toolbar.component.ts
- docs/tsconfig.app.json
- package-lock.json
- package.json
Part of #596 
Displays the library version number by extracting it from the package.json and putting it inside an environment variable which can then be used everywhere in the app.
Also updated Node types
> chore: display version number in documentation

- docs/modules/documentation/containers/combobox-input/examples/combobox-input-example.component.html
- library/src/lib/combobox-input/combobox-input.component.html
> fix: disable the button of disabled combobox

- docs/modules/documentation/containers/shellbar/examples/shellbar-collapsible-example.component.html
- library/src/lib/shellbar/shellbar-actions.component.html
> fix: allow the shellbar accepting custom elements

- docs/modules/documentation/containers/combobox-input/combobox-input-docs.component.html
- docs/modules/documentation/containers/search-input/examples/search-input-displaywith-example.component.html
- docs/modules/documentation/containers/search-input/examples/search-input-displaywith-example.component.ts
- docs/modules/documentation/containers/search-input/examples/search-input-dynamic-example.component.html
- docs/modules/documentation/containers/search-input/examples/search-input-dynamic-example.component.ts
- docs/modules/documentation/containers/search-input/search-input-docs.component.html
- docs/modules/documentation/containers/search-input/search-input-docs.component.ts
- docs/modules/documentation/documentation.module.ts
- library/src/lib/combobox-input/combobox-input.component.html
- library/src/lib/combobox-input/combobox-input.component.spec.ts
- library/src/lib/search-input/search-input.component.html
- library/src/lib/search-input/search-input.component.spec.ts
- library/src/lib/search-input/search-input.component.ts
- library/src/lib/search-input/search-input.module.ts
> feat: search input now uses multi input filter logic

- library/src/lib/time-picker/time-picker.component.html
- library/src/lib/time-picker/time-picker.component.spec.ts
- library/src/lib/time-picker/time-picker.component.ts
> fix: timepicker should call onChange when time model changes

- package-lock.json
- package.json
n/a
Get new version of `github-assistant` that will include a "Documentation" section in the release notes.
n/a
> chore: Include documentation section in release notes

- library/src/lib/date-picker/date-picker.component.ts
> fix: bug where datepicker events fire when calendar is opened/closed

- library/src/lib/modal/modal.component.scss
- library/src/lib/popover/popover-directive/popover-container.scss
- library/src/lib/popover/popover.component.scss
- library/src/lib/popover/popover.component.ts
> fix: make dropdown position static inside modals

- library/src/lib/calendar/calendar.component.ts
> fix: bug where calendar would not display years

- library/src/lib/file-input/directives/file-dragndrop.directive.ts
- library/src/lib/file-input/directives/file-select.directive.ts
- library/src/lib/file-input/file-input.component.html
- library/src/lib/file-input/file-input.component.ts
closes #695 
Documented file-input.
> docs: documented file-input

- library/src/lib/time-picker/time-picker.component.html
- library/src/lib/time/time-object.ts
- library/src/lib/time/time.component.ts
- package-lock.json
> docs: new time docs

- library/src/lib/popover/popover-body/popover-body.component.ts
- library/src/lib/popover/popover-control/popover-control.component.ts
- library/src/lib/popover/popover-directive/popover.directive.ts
- library/src/lib/popover/popover.component.ts
> docs: documented popover

- docs/modules/documentation/containers/panel/examples/panel-edge-bleed-example.component.html
- docs/modules/documentation/containers/table/examples/table-checkboxes-example.component.html
- docs/modules/documentation/containers/table/examples/table-example.component.html
- library/src/lib/table/table-body.directive.ts
- library/src/lib/table/table-header.directive.ts
- library/src/lib/table/table.module.ts
> fix: remove unused table header/body directives

- library/src/lib/action-bar/action-bar-actions.component.ts
- library/src/lib/action-bar/action-bar-back.component.ts
- library/src/lib/action-bar/action-bar-description.component.ts
- library/src/lib/action-bar/action-bar-header.component.ts
- library/src/lib/action-bar/action-bar-mobile.component.ts
- library/src/lib/action-bar/action-bar-title.component.ts
- library/src/lib/action-bar/action-bar.component.ts
> docs: add action bar typedocs

- package.json
Add netlify command for PR previews
> chore: add netlify command

- library/src/lib/shellbar/shellbar-actions.component.html
> fix: hide the notification icon if there are no notifications

- docs/fd-typedoc-theme/partials/typeAndParent.hbs
- docs/modules/documentation/containers/action-bar/examples/action-bar-contextual-menu-example.component.html
- docs/modules/documentation/containers/action-bar/examples/action-bar-mobile-example.component.html
- docs/modules/documentation/containers/button/button-docs.component.html
- package-lock.json
- package.json
closes #713 
Upgrades to fundamentals 1.5.3
> chore: upgraded fiori fundamentals to 1.5.3

- library/src/lib/breadcrumb/breadcrumb-item.directive.ts
- library/src/lib/breadcrumb/breadcrumb-link.directive.ts
- library/src/lib/breadcrumb/breadcrumb.directive.ts
> docs: breadcrumb typedocs

- library/src/lib/button/button.directive.spec.ts
- library/src/lib/button/button.directive.ts
> docs: added button docs

- library/src/lib/badge-label/badge.component.ts
- library/src/lib/badge-label/label.component.ts
> docs: add badge and label typedocs

- library/src/lib/multi-input/multi-input.component.ts
> docs: added multi-input documentation

- library/src/lib/search-input/search-input.component.ts
> added search input documentation

- library/src/lib/toggle/toggle.component.html
- library/src/lib/toggle/toggle.component.spec.ts
- library/src/lib/toggle/toggle.component.ts
closes #743 
- Improved toggle accessibility
- Added programmatic focus
- Fixed id issue
> fix: fixed toggle id bug

- docs/modules/documentation/containers/alert/examples/alert-component-as-content-example.component.html
- docs/modules/documentation/containers/alert/examples/alert-component-as-content-example.component.ts
- library/src/lib/alert/alert-utils/alert-ref.ts
- library/src/lib/alert/alert.component.html
- library/src/lib/alert/alert.component.ts
> fix: support passing back data for alerts

- library/src/lib/toggle/toggle.component.html
> fix: fixed small toggle bug

- library/src/lib/menu/menu-group.component.ts
- library/src/lib/menu/menu-item.directive.ts
- library/src/lib/menu/menu-list.directive.ts
- library/src/lib/menu/menu-title.directive.ts
- library/src/lib/menu/menu.component.ts
[Document Menu component #697 ](https://github.com/SAP/fundamental-ngx/issues/697)
Adds documentation for Menu component
> docs: adds menu typedocs

- library/src/lib/infinite-scroll/infinite-scroll.directive.ts
> docs: added infinite-scroll docs

- library/src/lib/token/token.component.ts
- library/src/lib/token/token.module.ts
Part of #687 
Adds token docs and fixes a very small bug with assigning id to host.
> docs: added token docs

- docs/modules/documentation/containers/calendar/calendar-docs.component.html
- docs/modules/documentation/containers/calendar/examples/calendar-single-example.component.ts
- library/src/lib/calendar/calendar.component.ts
> fix: construct calendar when disable function changes

- docs/modules/documentation/containers/calendar/calendar-docs.component.html
- docs/modules/documentation/containers/calendar/examples/calendar-monday-start-example.component.ts
- library/src/lib/calendar/calendar.component.spec.ts
- library/src/lib/calendar/calendar.component.ts
- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/date-picker/date-picker.component.ts
- library/src/lib/datetime-picker/datetime-picker.component.html
- library/src/lib/datetime-picker/datetime-picker.component.ts
…datepicker and datetimepicker.  Also fixes bug where days of the week did not show up in the date selection grid.
fixes #761
> fix: allow user to set any day as starting day of week

- library/src/lib/button-group/button-group.component.ts
- library/src/lib/button-group/button-grouped.directive.spec.ts
- library/src/lib/button-group/button-grouped.directive.ts
Part of #687 
Adds documentation for button group and also cleans it up a little.
> docs: added button group docs

- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/date-picker/date-picker.component.spec.ts
- library/src/lib/date-picker/date-picker.component.ts
- library/src/lib/datetime-picker/datetime-picker.component.html
- library/src/lib/datetime-picker/datetime-picker.component.spec.ts
- library/src/lib/datetime-picker/datetime-picker.component.ts
- library/src/lib/time-picker/time-picker.component.html
- library/src/lib/time-picker/time-picker.component.spec.ts
- library/src/lib/time-picker/time-picker.component.ts
> bug: datepicker and datetimepicker input validation

- library/src/lib/icon/icon.directive.ts
added documentation typedoc comments for icon component
> docs: added documentation typedoc comments for icon component

- library/src/lib/identifier/identifier.directive.ts
added documentation typedoc comments for identifier component
> docs: added documentation typedoc comments for identifier component

- library/src/lib/image/image.component.ts
added documentation typedoc comments for image component
> docs: added documentation typedoc comments for image component

- library/src/lib/inline-help/inline-help.component.ts
added documentation typedoc comments for inline-help component
> docs: added documentation typedoc comments for inline-help component

- library/src/lib/combobox-input/combobox-input.component.ts
- library/src/lib/input-group/input-group-number.component.ts
- library/src/lib/input-group/input-group-search.component.ts
- library/src/lib/input-group/input-group.component.ts
added documentation typedoc comments for  input-group and combobox-input components
> docs: added documentation typedoc comments for input-group and combobox-input components

- library/src/lib/list/list-action.directive.ts
- library/src/lib/list/list-checkbox.component.ts
- library/src/lib/list/list-item.component.ts
- library/src/lib/list/list.component.ts
added documentation typedoc comments for list component
> docs: added documentation typedoc comments for list component

- library/src/lib/tile/product-tile-content/product-tile-content.component.ts
- library/src/lib/tile/product-tile-media/product-tile-media.component.ts
- library/src/lib/tile/product-tile-title/product-tile-title.directive.ts
- library/src/lib/tile/product-tile.component.ts
- library/src/lib/tile/tile-actions/tile-actions.component.ts
- library/src/lib/tile/tile-content/tile-content.directive.ts
- library/src/lib/tile/tile-grid/tile-grid.directive.ts
- library/src/lib/tile/tile-media/tile-media.directive.ts
- library/src/lib/tile/tile-title/tile-title.directive.ts
- library/src/lib/tile/tile.component.ts
added documentation typedoc comments for tile component
> docs: aded typedocs for tile component

- library/src/lib/loading-spinner/loading-spinner.component.ts
added documentation typedoc comments for loading spinner component
> docs: added typedocs for loading spinner component

- library/src/lib/pagination/pagination.component.ts
- library/src/lib/pagination/pagination.service.ts
added documentation typedoc comments for pagination component
> docs: added typedocs for pagination component

- library/src/lib/calendar/i18n/calendar-i18n.ts
> chore: added calendar fallbacks

- library/src/lib/side-navigation/side-navigation-group/side-navigation-group.component.ts
- library/src/lib/side-navigation/side-navigation-icon/side-navigation-icon.component.ts
- library/src/lib/side-navigation/side-navigation-item/side-navigation-item.component.ts
- library/src/lib/side-navigation/side-navigation-link/side-navigation-link.component.ts
- library/src/lib/side-navigation/side-navigation-list/side-navigation-list.component.ts
- library/src/lib/side-navigation/side-navigation-subitem/side-navigation-subitem.component.ts
- library/src/lib/side-navigation/side-navigation-sublink/side-navigation-sublink.component.ts
- library/src/lib/side-navigation/side-navigation-sublist/side-navigation-sublist.component.ts
- library/src/lib/side-navigation/side-navigation.component.ts
added documentation typedoc comments for side nav component
> docs: added typedocs for side-nav component

- library/src/lib/scroll-spy/scroll-spy.directive.ts
added documentation typedoc comments for scrollspy component
> docs: added typedocs for scrollspy component

- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/date-picker/date-picker.component.ts
> fix: only trigger onChange if input value changes

- library/src/lib/datetime-picker/datetime-picker.component.html
- library/src/lib/datetime-picker/datetime-picker.component.ts
> fix: datetime invalid time in input should not nullify ngModel

- docs/app/documentation/utilities/api-files.ts
- library/src/lib/table/column-sortable.directive.ts
- library/src/lib/table/table.component.ts
added documentation typedoc comments for table component
> docs: added typedocs for table component

- README.md
closes #800 
Adds instructions for adding @angular/animations and BrowserAnimationsModule.
> chore: updated readme getting started section

- library/src/lib/alert/alert.component.scss
Quick fix to the style encapsulation pr from friday.
> chore: amend style encapsulation pr

- package-lock.json
Reset the package.lock and then ran a quick npm audit fix to resolve the node-tar vulnerability.
> fix: updated tar dependency

- package-lock.json
> chore: lock update

- library/src/lib/alert/alert.component.scss
- library/src/lib/alert/alert.component.spec.ts
- library/src/lib/alert/alert.component.ts
> fix: dismissing alerts display: none style fix

- docs/app/documentation/component-docs/form/examples/form-group-input-example.component.html
- docs/app/documentation/component-docs/form/examples/form-group-input-example.component.scss
- docs/app/documentation/component-docs/form/examples/form-group-input-example.component.ts
- docs/app/documentation/component-docs/form/form-docs.component.html
- docs/app/documentation/component-docs/form/form-docs.component.ts
- docs/app/documentation/documentation.module.ts
- package-lock.json
fixes #677 
Adds another example to the forms components in the docs (using angular reactive forms)
> docs: Added form examples for form-input

- docs/app/documentation/component-docs/time/examples/time-form-example.component.html
- docs/app/documentation/component-docs/time/examples/time-form-example.component.ts
- docs/app/documentation/component-docs/time/time-docs.component.html
- docs/app/documentation/component-docs/time/time-docs.component.ts
- docs/app/documentation/documentation.module.ts
fixes #677 
Adds another example to the time component in the documentation (using angular reactive forms)
> docs: Added example of fd-time being using within a form

- README.md
> chore: remove demo app section in readme

- library/src/lib/alert/alert-service/alert.service.ts
https://github.com/SAP/fundamental-ngx/issues/865
Put default config to alert open function
Not needed
> fix: make alert service follow the modal service pattern

- docs/app/documentation/component-docs/panel/panel-docs.component.html
https://github.com/SAP/fundamental-ngx/issues/873
small fix, changed [name] in panel component from ex1 to ex5
> docs: fix panel toggle background issue

- angular.json
- docs/index.html
- docs/tsconfig.app.json
- tsconfig.json
closes #893 
Removes useless resources being loaded on startup.
> docs: removed useless resources from index.html

- docs/app/documentation/component-docs/time-picker/examples/time-picker-form-example.component.html
- docs/app/documentation/component-docs/time-picker/examples/time-picker-form-example.component.ts
- docs/app/documentation/component-docs/time-picker/time-picker-docs.component.html
- docs/app/documentation/component-docs/time-picker/time-picker-docs.component.ts
- docs/app/documentation/documentation.module.ts
#677 
Added an example to the documentation that shows how to use the time-picker component inside an Angular reactive form.
> docs: Added example for using time picker in Angular reactive form

- docs/app/documentation/component-docs/input-group/examples/input-group-form-example.component.html
- docs/app/documentation/component-docs/input-group/examples/input-group-form-example.component.ts
- docs/app/documentation/component-docs/input-group/input-group-docs.component.html
- docs/app/documentation/component-docs/input-group/input-group-docs.component.ts
- docs/app/documentation/documentation.module.ts
#677 
Adds another example to the input-group components (using Angular Reactive Forms)
Not necessary
> docs: Added example of input-group-search component within Form

- docs/app/documentation/component-docs/multi-input/examples/multi-input-form-example/multi-input-form-example.component.html
- docs/app/documentation/component-docs/multi-input/examples/multi-input-form-example/multi-input-form-example.component.ts
- docs/app/documentation/component-docs/multi-input/multi-input-docs.component.html
- docs/app/documentation/component-docs/multi-input/multi-input-docs.component.ts
- docs/app/documentation/documentation.module.ts
- library/src/lib/multi-input/multi-input.component.ts
fixes #677 
Adds another example to the multi-input component in the documentation (using angular reactive forms)
Not necessary
> docs: added example of multi-input used in angular reactive form

- library/src/lib/alert/alert.component.scss
- library/src/lib/shellbar/shellbar-actions/shellbar-actions.component.scss
fixes #916 
also removed related unused overrides from alert scss
> fix: bug where shellbar search input body did not display properly

- docs/app/documentation/component-docs/list/examples/list-checkbox-form-example.component.html
- docs/app/documentation/component-docs/list/examples/list-checkbox-form-example.component.ts
- docs/app/documentation/component-docs/list/list-docs.component.html
- docs/app/documentation/component-docs/list/list-docs.component.ts
- docs/app/documentation/documentation.module.ts
#677
Adds another example for the list-checkbox component in the documentation (using angular reactive forms)
Not necessary
> docs: added example of list-checkbox component used within form

- library/src/lib/pagination/pagination.service.ts
closes #938 
Makes the error a warning, and now only appears in development mode.
> fix: paging error is now a devmode warning

- docs/app/documentation/component-docs/date-picker/date-picker-docs.component.html
- docs/app/documentation/component-docs/date-picker/examples/date-picker-format-example.component.ts
- library/src/lib/calendar/format/date-parser.ts
- library/src/lib/date-picker/date-picker.component.spec.ts
fixes #932 
Strictly enforces mm/dd/yyyy formatting by default and details how to change this to the internationally used dd-mm-yyyy.
> fix: date format bug

- docs/app/documentation/component-docs/date-picker/examples/date-picker-i18n-example.component.ts
- docs/app/documentation/component-docs/datetime-picker/examples/datetime-example/datetime-example.component.html
- library/src/lib/date-picker/date-picker.component.ts
- library/src/lib/datetime-picker/datetime-picker.component.ts
> fix: datepicker/datetimepicker placement

- docs/app/documentation/component-docs/datetime-picker/datetime-picker-docs.component.html
- docs/app/documentation/component-docs/datetime-picker/datetime-picker-docs.component.ts
- docs/app/documentation/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.html
- docs/app/documentation/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.ts
- docs/app/documentation/documentation.module.ts
- library/src/lib/datetime-picker/datetime-picker.component.ts
> fix: datetimepicker form bugs, add form example

- docs/app/documentation/component-docs/badge-label/badge-label-docs.component.html
- docs/app/documentation/component-docs/badge-label/examples/label-build-status-example.component.html
- docs/app/documentation/component-docs/badge-label/examples/label-icon-status-example.component.html
- docs/app/documentation/component-docs/badge-label/examples/label-status-colors-example.component.html
- docs/app/documentation/utilities/api-files.ts
- library/src/lib/badge-label/badge-label.module.ts
- library/src/lib/badge-label/badge.directive.ts
- library/src/lib/badge-label/label.directive.ts
- library/src/lib/badge-label/status-label.directive.spec.ts
- library/src/lib/badge-label/status-label.directive.ts
fixes https://github.com/SAP/fundamental-ngx/issues/952
I Added new directive which is named status-label, it replaces isStatusLabel input, Also some tests
Updated by itself
> feat: Refactor isStatus input on label

- package-lock.json
> chore: fix vulnerability

- library/src/public_api.ts
> fix: #1051 include timepicker in public_api.ts

- library/src/lib/calendar/public_api.ts
- library/src/lib/date-picker/public_api.ts
- library/src/lib/datetime-picker/public_api.ts
- library/src/lib/time/public_api.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1071
I added missing model files to public api files.
> fix: Add TimeObject, FdDate, FdRangeDate, FdDateTime to public apis

- docs/app/documentation/component-docs/input-group/examples/input-group-number-form-example.component.html
- docs/app/documentation/component-docs/input-group/examples/input-group-number-form-example.component.ts
- docs/app/documentation/component-docs/input-group/input-group-docs.component.html
- docs/app/documentation/component-docs/input-group/input-group-docs.component.ts
- docs/app/documentation/documentation.module.ts
#1087 
added an example of input group number within angular reactive form
> docs: added input group (number) example in reactive form

- README.md
- angular.json
- docs/app/documentation/component-docs/button/button-docs.component.html
- docs/app/documentation/component-docs/icon/icon-docs.component.html
- docs/app/documentation/component-docs/image/image-docs.component.html
- library/package.json
- package.json
Rename all usages of Fiori Fundamentals to Fundamental-Styles
> docs: Rename all usages of Fiori Fundamentals to Fundamental-Styles

- docs/app/documentation/component-docs/combobox/examples/combobox-template-example.component.html
- docs/app/documentation/component-docs/dropdown/examples/dropdown-contextual-menu-example.component.html
- docs/app/documentation/component-docs/dropdown/examples/dropdown-default-example.component.html
- docs/app/documentation/component-docs/dropdown/examples/dropdown-icons-example.component.html
- docs/app/documentation/component-docs/dropdown/examples/dropdown-state-example.component.html
- docs/app/documentation/component-docs/dropdown/examples/dropdown-toolbar-example.component.html
- docs/app/documentation/component-docs/menu/examples/menu-group-example.component.html
- docs/app/documentation/component-docs/popover/examples/popover-placement/popover-placement-example.component.html
- docs/app/documentation/component-docs/popover/examples/popover-programmatic/popover-programmatic-open-example.component.html
- docs/app/documentation/component-docs/popover/examples/popover-simple/popover-example.component.html
- docs/app/documentation/component-docs/split-button/examples/split-button-icons-example.component.html
- docs/app/documentation/component-docs/split-button/examples/split-button-options-example.component.html
- docs/app/documentation/component-docs/split-button/examples/split-button-programmatical-example.component.html
- docs/app/documentation/component-docs/split-button/examples/split-button-template-example.component.html
- docs/app/documentation/component-docs/split-button/examples/split-button-types-example.component.html
- library/src/lib/combobox/combobox.component.html
- library/src/lib/combobox/combobox.component.spec.ts
- library/src/lib/combobox/combobox.component.ts
- library/src/lib/menu/menu-item.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1062
I added menu built-in keyboard support to combobox. And changed a little bit split button examples, cause there was visual bug with anchors color.
I also modified the tests, deleted some useless code.
I updated documentation for split button.
> fix: introduce menu built-in keyboard support

- .github/mergeable.yml
> chore: add initial mergeable.yml

- docs/app/documentation/component-docs/calendar/calendar-docs.component.html
- docs/app/documentation/component-docs/calendar/examples/calendar-form-range-example.component.ts
- docs/app/documentation/component-docs/calendar/examples/calendar-form-single-example.component.ts
- docs/app/documentation/component-docs/calendar/examples/calendar-programmatically-change-example.component.ts
- docs/app/documentation/component-docs/calendar/examples/calendar-single-example.component.ts
- docs/app/documentation/component-docs/date-picker/date-picker-docs.component.html
- docs/app/documentation/component-docs/date-picker/examples/date-picker-form-example.component.ts
- docs/app/documentation/component-docs/date-picker/examples/date-picker-form-range-example.component.ts
- docs/app/documentation/component-docs/date-picker/examples/date-picker-format-example.component.ts
- docs/app/documentation/component-docs/datetime-picker/datetime-picker-docs.component.html
- docs/app/documentation/component-docs/datetime-picker/examples/datetime-form-example/datetime-form-example.component.html
- library/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
- library/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
- library/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts
- library/src/lib/calendar/calendar.component.spec.ts
- library/src/lib/calendar/calendar.component.ts
- library/src/lib/calendar/calendar.service.ts
- library/src/lib/calendar/models/fd-date.ts
- library/src/lib/date-picker/date-picker.component.html
- library/src/lib/date-picker/date-picker.component.spec.ts
- library/src/lib/date-picker/date-picker.component.ts
- library/src/lib/date-picker/format/date-parser.ts
- library/src/lib/datetime-picker/datetime-picker.component.html
- library/src/lib/datetime-picker/datetime-picker.component.spec.ts
- library/src/lib/datetime-picker/datetime-picker.component.ts
- library/src/lib/datetime-picker/models/fd-datetime.ts
- library/src/lib/time-picker/time-picker.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/998
I added Validator support for calendar/date/datetime components. It forced me to change handling the invalid data. Before on invalid data, model wasn't changed and the data, until it's valid. That approach caused, that the wrong data wasn't shown on examples. 
Right now invalid data is stored on component model and is reflected on forms/models on components that are using calendar components. Tests has been changed also.
Additionally there are provided some basic UX/Visual fixes.
I added examples of usage on all of calendar related components.
> feat: Add calendar components form validation

- library/package-lock.json
- package-lock.json
> chore: reset lock

- library/package-lock.json
- library/package.json
- package-lock.json
- package.json
> chore: Update rxjs test

- docs/app/documentation/component-docs/popover/examples/popover-simple/popover-example.component.html
Add an example with fixed popover position(bottom) - using popper.js API
> docs: Add a fixed position popover

- docs/app/documentation/component-docs/select/examples/select-basic-example/select-basic-example.component.html
- docs/app/documentation/component-docs/select/examples/select-basic-example/select-basic-example.component.ts
- library/src/lib/select/select.component.html
- library/src/lib/select/select.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1128
I added compact mode to select component
I added 1 example of compact input usage.
> fix: Add compact mode to select component

- library/src/lib/calendar/models/fd-date.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1160
There was little bug with previousDay() method on FdDate model.
> fix: fix previous day method

- library/src/lib/pagination/public_api.ts
- library/src/lib/tile/public_api.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1158
I Added some missing files to public_api.ts files.
> fix: Add files to pagination and tile public api

- docs/app/documentation/component-docs/input/examples/input-inline-help-example.component.html
#1106
update inline help in the input component
> docs: update inline help inside input 

- docs/app/documentation/component-docs/action-bar/examples/action-bar-contextual-menu-example.component.html
- docs/app/documentation/component-docs/action-bar/examples/action-bar-mobile-example.component.html
- library/src/lib/action-bar/action-bar-mobile/action-bar-mobile.directive.ts
fixes https://github.com/SAP/fundamental-styles/issues/234
PR has changes to fix for the responsiveness of menu list in the action bar and also removed hard coded value for width of the mobile screen size.
> fix: action bar fix for the responsiveness of menu list

- docs/app/documentation/component-docs/combobox/combobox-docs.component.html
- docs/app/documentation/component-docs/combobox/combobox-docs.component.ts
- docs/app/documentation/component-docs/combobox/examples/combobox-search-function-example.component.html
- docs/app/documentation/component-docs/combobox/examples/combobox-search-function-example.component.ts
- docs/app/documentation/documentation.module.ts
- library/src/lib/combobox/combobox.component.html
- library/src/lib/combobox/combobox.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1139
I added search function call on primary button click.
> fix: combobox primary button click

- docs/app/documentation/component-docs/combobox/combobox-docs.component.html
- docs/app/documentation/component-docs/combobox/combobox-docs.component.ts
- docs/app/documentation/component-docs/combobox/examples/combobox-disabled-example.component.html
- docs/app/documentation/component-docs/combobox/examples/combobox-disabled-example.component.ts
- docs/app/documentation/documentation.module.ts
- library/src/lib/combobox/combobox.component.ts
> fix: fixed issue with disabled combobox in Reactive Form

- docs/app/documentation/component-docs/inline-help/examples/inline-help-example.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/1171
I changed documentation to bottom-end.
> change example to bottom-end

- docs/app/documentation/component-docs/menu/examples/menu-addon-example.component.html
- docs/app/documentation/component-docs/menu/examples/menu-addon-examples.component.ts
- docs/app/documentation/component-docs/menu/menu-docs.component.html
- docs/app/documentation/component-docs/menu/menu-docs.component.ts
- docs/app/documentation/documentation.module.ts
- docs/app/documentation/utilities/api-files.ts
- library/src/lib/menu/menu-addon.directive.ts
- library/src/lib/menu/menu-item-addon.directive.ts
- library/src/lib/menu/menu.component.spec.ts
- library/src/lib/menu/menu.module.ts
fixes #1132 
- created directives for menu addons(used for icons)
- added an example in the documentation
> feat: created directives for menu addon

- docs/app/documentation/component-docs/checkbox/examples/checkbox-form-group-example.component.html
- docs/app/documentation/component-docs/checkbox/examples/checkbox-form-group-example.component.ts
> docs: Added Disabled Checkboxes in a Reactive Form Example

- library/src/lib/time/time.component.html
- library/src/lib/time/time.module.ts
- library/src/lib/utils/directives/only-digits.directive.spec.ts
- library/src/lib/utils/directives/only-digits.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1202
I added only digits directive, which prevent from writing any non-digits chars on time component. It can be used anywhere.
> feat: added a directive that accepts only digits and special keys

- package.json
> chore: fix gh pages publishing

- .gitignore
Due to latest changes, there was a need to change .gitignore, to exclude auto generated files
> fix: Changed .gitignore

- README.md
- libs/core/schematics/collection.json
> docs: update README.md and schematics to reflect the latest package name

- libs/core/src/lib/button/button.directive.ts
We should be more restrictive and use types as much as we can,
When working with button on app level compiler will be able to tell if
you pass something wrong
> fix(button): Add typings to buttons Inputs

- apps/docs/src/app/documentation/component-docs/shellbar/examples/shellbar-advanced/shellbar-advanced-example.component.html
- apps/docs/src/app/documentation/component-docs/shellbar/examples/shellbar-advanced/shellbar-advanced-example.component.ts
- apps/docs/src/app/documentation/component-docs/shellbar/shellbar-docs.component.html
- apps/docs/src/app/documentation/component-docs/shellbar/shellbar-docs.component.ts
- apps/docs/src/app/documentation/documentation.module.ts
- libs/core/src/lib/shellbar/product-menu/product-menu.component.html
- libs/core/src/lib/shellbar/product-menu/product-menu.component.ts
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.spec.ts
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts
- libs/core/src/lib/shellbar/shellbar-product-switcher/shellbar-product-switcher.component.html
- libs/core/src/lib/shellbar/shellbar-product-switcher/shellbar-product-switcher.component.spec.ts
- libs/core/src/lib/shellbar/shellbar-product-switcher/shellbar-product-switcher.component.ts
- libs/core/src/lib/shellbar/shellbar.module.ts
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.spec.ts
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.ts
- netlify.toml
fixes: https://github.com/SAP/fundamental-ngx/issues/1241
I Added separated components, which uses popovers and extend the popover components. It allows to add any configuration that is provided in popovers.
There is 1 more example.
> fix: extend shellbar

- package.json
UPdating to the latest published version and setting it to the root package.json
> chore(build): Sync up to latest published tag

- ci-scripts/publish.sh
- ci-scripts/setup-npm.sh
- ci-scripts/sync-version.sh
Trying to track down problem in travis  - added more debugging info. I test this similar on the other repo and i have all the comand available in the same setup. 
Need to find out what is going on.
> chore(build): Add verbose logging for CI to track issue

- .travis.yml
- ci-scripts/publish.sh
- ci-scripts/sync-version.sh
Final build that updates scritpt files and travis.yml
> chore(build): Debugging travis

- .editorconfig
- .travis.yml
- CHANGELOG.md
- ci-scripts/publish.sh
- libs/core/package-lock.json
- package-lock.json
- package.json
- scripts/archive-publish-release.sh
I Added some scripts and 2 new pipelines on Travis to make having 2 branches for othe angular versions available. Pushing / Merging commits to `archive-ngx-core-ng7` will also increment the RC version of npm package.
> chore: Add CI for  archive-ngx-core-ng7 branch

- libs/platform/package.json
Added some missing attribute that needs show up on npmjs such license.
> chore(npm): Update package.json with required info for npmjs

- apps/docs/src/app/documentation/component-docs/calendar/calendar-docs.component.ts
- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.html
- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.ts
- apps/docs/src/app/documentation/core-helpers/code-example/example-file.ts
- apps/docs/src/app/documentation/core-helpers/documentation/documentation.component.ts
- apps/docs/src/typings.d.ts
There was some issues on showing example code. It was due to raw-loader version change.
> fix: Adapt to new raw-loader interface

- apps/docs/src/app/documentation/component-docs/popover/examples/popover-placement/popover-placement-example.component.ts
- apps/docs/src/app/documentation/component-docs/popover/examples/popover-placement/popover-placement-example.scss
- apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.scss
- apps/docs/src/app/documentation/core-helpers/documentation/documentation.component.ts
- libs/core/package.json
- libs/core/src/lib/breadcrumb/breadcrumb.component.scss
- libs/core/src/lib/identifier/identifier.component.scss
- libs/core/src/lib/input-group/input-group-number.component.html
- libs/core/src/lib/input-group/input-group-search.component.html
- libs/core/src/lib/input-group/input-group.component.scss
fixes #1326 
- This PR fixes issues 1, 2, 5, 8, 9, 10, 12. The other issues (3, 4, 6, 11) should be fixed in Fundamental-styles
> fix: self-contained adoption issues

- libs/core/src/lib/calendar/models/fd-date.spec.ts
- libs/core/src/lib/calendar/models/fd-date.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1332
I fixed `previousDay()` function, right now there it calculate number of days, basing on good month/year.
> fix: Add tests, fix previous day issues

- libs/core/src/lib/multi-input/multi-input.component.html
https://github.com/SAP/fundamental-ngx/issues/1326
I Added disabled mode to multi input. It wasn't passed to input group component,
> fix: Add disabled mode to multi input

- libs/core/src/lib/date-picker/date-picker.component.ts
There was some weird issue on choosing date. When the date before was wrong and user picked any day from calendar, this date was still shown as a invalid.
> fix: Add valid detection on date change from calndar

- libs/core/src/lib/modal/modal-utils/modal-ref.ts
Complete rxjs subject when closing modal
Closes #1002
#1002
> fix: complete rxjs subject when closing modal

- apps/docs/src/app/core/api-files.ts
- apps/docs/src/app/core/core-documentation.routes.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
I updated `public-api.ts`, because it was outdated, also removed search input from component list.
> fix: Add and change file list on api-files.ts

- apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-format-example.component.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.ts
- libs/core/src/lib/date-picker/date-picker.component.ts
- libs/core/src/lib/datetime-picker/datetime-picker.component.ts
- libs/core/src/lib/popover/popover-dropdown/popover-dropdown.component.html
- libs/core/src/lib/time/time.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/1355
I added some improvements and fixes to lib code. Also there was some trash code, which caused issues with performance.
> fix: Improve performance on popover's components. Resolve console errors

- NEW_COMPONENT.md
- README.md
Outdated files for old fundamental-ngx library
Changed the documentation for the read me and new component.md files to correspond with the new videos
> docs: fixed read me and new component

- libs/platform/src/index.ts
- libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.html
- libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.scss
- libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.spec.ts
- libs/platform/src/lib/components/action-bar/action-bar-actions/action-bar-actions.component.ts
- libs/platform/src/lib/components/action-bar/action-bar.component.html
- libs/platform/src/lib/components/action-bar/action-bar.component.scss
- libs/platform/src/lib/components/action-bar/action-bar.component.spec.ts
- libs/platform/src/lib/components/action-bar/action-bar.component.ts
- libs/platform/src/lib/components/action-bar/action-bar.module.ts
- libs/platform/src/lib/components/action-bar/public_api.ts
- libs/platform/src/lib/platform.module.ts
https://github.com/SAP/fundamental-ngx/issues/1263
This PR contains a code to enhance the action bar as a component.
This enhancement contains, providing an option to edit the Action bar Title and also displaying of overflow dynamically if the user configure more than 3 actions.
New feature
> feat(platform): Code changes to convert action bar as a component"

- libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
- libs/core/src/lib/time-picker/format/time-parser.ts
- libs/core/src/lib/time-picker/time-picker.component.scss
- libs/core/src/lib/time-picker/time-picker.component.spec.ts
- libs/core/src/lib/time-picker/time-picker.component.ts
- libs/core/src/lib/time/time.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1356
I changed parser/format functions to allow using only hours mode. There are also some tests added into. I fixed change detection between timepicker and time component. Also there is fixed validation on timepicker.
> fix: timepicker without minutes/seconds and add some tests

- apps/docs/src/app/core/component-docs/calendar/calendar-docs.component.html
- libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
- libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts
- libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
- libs/core/src/lib/calendar/calendar-views/calendar-year-view/calendar-year-view.component.ts
- libs/core/src/lib/calendar/calendar.component.scss
fixes: https://github.com/SAP/fundamental-ngx/issues/1363
I had to add `setTimeout` to keep focus on calendar, while using `IVY`. There are also some visual fixes, hardcoded color code is presented in css right now
> fix: calendar focusing issues

- libs/core/package.json
> chore: update core package.json

- CONTRIBUTING.md
Please provide a link to the associated issue.
fixes #1322
Please provide a brief summary of this pull request.
Added more steps to guide developers thru the submittion process.
If this is a new feature, have you updated the documentation?
> docs(contribute): Added more details to contribution doc

- README.md
- libs/core/README.md
fixes: https://github.com/SAP/fundamental-ngx/issues/1320
> chore: #1320 change readme.md

- libs/core/src/lib/badge-label/badge-label/badge.component.ts
- libs/core/src/lib/badge-label/label/label.component.ts
- libs/core/src/lib/badge-label/status-label/status-label.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1436
I added requested types to badge components.
> fix: Add types to badge components

- ci-scripts/sync-version.sh
- libs/core/package.json
- libs/core/schematics/ng-add/index.ts
- libs/core/src/lib/calendar/calendar-header/calendar-header.component.html
- libs/core/src/lib/calendar/calendar-header/calendar-header.component.spec.ts
- libs/core/src/lib/calendar/calendar.module.ts
- libs/core/src/lib/notification/notification/notification.component.ts
There is added @angular/cdk general version to peerDependencies (our dnd module requires it)
Also we had visual bug on calendar component, using buttons.
There was 1 console log left, it had to be removed.
> fix: Add @angular/cdk to peer dependency, add button module to calendar 

- apps/docs/src/app/documentation/core-helpers/code-example/code-example-stack/app/app.module.ts
- apps/docs/src/app/documentation/core-helpers/code-example/code-example-stack/main.ts
- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.ts
fixes: #1458
Removed the comments and cleaned up the code-example file
> docs: fixed maints file

- NEW_COMPONENT.md
double step14
change step to 15
> docs: Update NEW_COMPONENT.md

- apps/docs/src/app/core/documentation/core-documentation.component.html
- apps/docs/src/app/documentation/core-helpers/docs-section-title/docs-section-title.component.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/1477
There are fixed directly links to the component's sections. Also scrolling with offset is fixed
> fix: Fix docs fragment links

- apps/docs/src/app/core/component-docs/product-switch/examples/product-switch-dnd-example.component.ts
- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
Added some additional styling to the item being dragged. 
- removed the focus dotted border
- added box-shadow
- changed the cursor to grabbing
- changed the drop-area z-index because the circle was not visible in some cases
- in the Shellbar example made the Home icon not-draggable
> fix: add DnD styling improvements to Product Switch

- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.html
fixes: #1478 
Change the icon of the stackblitz and keep the appropriate styling
> docs: changed glyph for stackblitz

- libs/core/src/index.ts
> fix:  export grid-layout public api

- NEW_COMPONENT.md
- libs/core/README.md
No links for tutorials in md files
Add video links to md files
> docs: (core) added videos to md files

- libs/core/ng-package.json
- libs/core/package.json
> fix: make @angular/cdk as a peer dependancy

- apps/docs/src/app/core/component-docs/tabs/examples/tabs-navigation-mode-example.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/1519
There is fix for navigation mode tab example
> fix: navigation mode for tab

- apps/docs/src/app/core/component-docs/button/button-docs.component.html
- apps/docs/src/app/core/component-docs/button/button-docs.component.ts
- apps/docs/src/app/core/component-docs/button/examples/button-options-example.component.html
- libs/core/src/lib/button/button.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1561
I added `menu` option to button element
> fix: Add menu option to button

- package.json
> chore: bump package version number

- apps/docs/browserslist
- apps/docs/src/index.html
fix a console error from the doc site run under IE11
> docs: IE11 navigation in the doc app

- libs/core/src/lib/alert/alert.module.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1606
There is added DynamicComponentService to alert module, following notification and modal modules
> fix:(core) Add DynamicComponentService to alert module

- libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.html
- libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.ts
- scripts/archive-publish-release.sh
fixes: https://github.com/SAP/fundamental-ngx/issues/1585
**This is for NG 7 version.**
There is changed button type changed in localization editor. Also there is added event, on main button click
> fix: ng7 - Change localization button type

- apps/docs/src/app/core/component-docs/menu/examples/menu-addon-example.component.html
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.spec.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1581
fixes: https://github.com/SAP/fundamental-ngx/issues/373
There is changed menu addon usage on example.
> fix(core): Fix menu with addons

- apps/docs/src/app/core/component-docs/select/examples/select-types-example/select-types-example.component.html
- apps/docs/src/app/core/component-docs/select/examples/select-types-example/select-types-example.component.scss
- apps/docs/src/app/core/component-docs/select/examples/select-types-example/select-types-example.component.spec.ts
- apps/docs/src/app/core/component-docs/select/examples/select-types-example/select-types-example.component.ts
- apps/docs/src/app/core/component-docs/select/select-docs.component.html
- apps/docs/src/app/core/component-docs/select/select-docs.component.ts
- apps/docs/src/app/core/core-documentation.module.ts
- libs/core/src/lib/select/select.component.html
- libs/core/src/lib/select/select.component.scss
- libs/core/src/lib/select/select.component.ts
- libs/core/src/lib/select/select.module.ts
- package.json
https://github.com/SAP/fundamental-ngx/issues/1268
feat: (core) Core select components changes to introduce 2 variable 1) introducing icon and another is to have different types of button , and have introduced few changes in css to  accommodate the above changes.
> fix: (core) Add support for icon and select border types

- libs/core/README.md
> chore: (core) update read me

- libs/platform/src/lib/components/select/public_api.ts
- libs/platform/src/lib/components/select/select.component.html
- libs/platform/src/lib/components/select/select.component.spec.ts
- libs/platform/src/lib/components/select/select.component.ts
- libs/platform/src/lib/components/select/select.module.ts
- libs/platform/src/lib/platform.module.ts
feat(platform): adding new wrapper select component  for platform
https://github.com/SAP/fundamental-ngx/issues/1268
wrapper component for the select component, with pluggable options and diff css for selectTypes
> feat(platform): select component  for platform to enhance the core

- libs/platform/src/index.ts
- libs/platform/src/lib/components/select/select.component.ts
https://github.com/SAP/fundamental-ngx/issues/1268
extending the select component to the 3rd party application 
> fix(platform): extending the select component to the 3rd party application 

- apps/docs/src/app/core/api-files.ts
- apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html
- apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.ts
- apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-header/busy-indicator-header.component.html
- apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-header/busy-indicator-header.component.ts
- apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-basic-example.component.html
- apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-basic-example.component.ts
- apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-toggle-example.component.html
- apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-toggle-example.component.ts
- apps/docs/src/app/core/core-documentation.module.ts
- apps/docs/src/app/core/core-documentation.routes.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- libs/core/src/lib/busy-indicator/busy-indicator.component.html
- libs/core/src/lib/busy-indicator/busy-indicator.component.scss
- libs/core/src/lib/busy-indicator/busy-indicator.component.spec.ts
- libs/core/src/lib/busy-indicator/busy-indicator.component.ts
- libs/core/src/lib/busy-indicator/busy-indicator.module.ts
- libs/core/src/lib/busy-indicator/public_api.ts
- libs/core/src/lib/fundamental-ngx-core.module.ts
fixes:  #1699
Add the busy indicator component
> feat: Busy indicator

- libs/platform/README.md
> chore: (platofrm) fix read me link

- apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-select/platform-select-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-default-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-noborder-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-split-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.html
- apps/docs/src/app/platform/component-docs/platform-select/platform-select-examples/platform-select-types-with-icon-example.component.ts
- apps/docs/src/app/platform/platform-documentation.module.ts
- libs/platform/src/lib/components/select/select.component.html
- libs/platform/src/lib/components/select/select.component.scss
- libs/platform/src/lib/components/select/select.component.ts
- libs/platform/src/lib/components/select/select.module.ts
https://github.com/SAP/fundamental-ngx/issues/1268
platform(feat):adding new select with icon and adding documentation for the same
> platform(feat):adding new select with icon and adding documentation for the same

- .github/PULL_REQUEST_TEMPLATE.md
Add stackblitz as a checkbox for pr creation
> docs: add StackBlitz to PR template

- apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.ts
fixes: #1705
Fixed all shellbars for 0.13.0 to work in stackblitz
> docs: fix StackBlitz for 0.13.0

- libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts
- libs/core/src/lib/utils/decorators/apply-css-style.decorator.ts
This PR fixes problem of missing classes in button and radio button components
> fix: add fix for missing classes in radio button and button components

- apps/docs/src/app/core/component-docs/select/select-docs.component.html
#1834 
fixes bug where toggle switches the RTL/background for the wrong example
> fix: rtl/bg toggle on select page

- apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-multiple-selected-example/side-navigation-multiple-selected-example.component.html
- apps/docs/src/app/core/component-docs/side-navigation/side-navigation-docs.component.ts
fixes: #1707
Fixing the file names for them to work in stackbitz. There is still a query selector issue for the condensed side-nav. 
> docs: fix StackBlitz for SideNav

- apps/docs/src/app/core/api-files.ts
- apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.ts
- apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
- apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
- libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-footer.directive.spec.ts
- libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-footer.directive.ts
- libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-header.directive.spec.ts
- libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-header.directive.ts
- libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-subheader.directive.spec.ts
- libs/core/src/lib/popover/popover-body/popover-body-directives/popover-body-subheader.directive.ts
- libs/core/src/lib/popover/popover-body/popover-body.component.html
- libs/core/src/lib/popover/popover.module.ts
- libs/core/src/lib/toggle/toggle.component.scss
- package-lock.json
- package.json
closes #1841
Added Header, Subheader and Footer directives
> fix: #1841 popover refactoring 

- .github/mergeable.yml
add a PR date check in mergeable
> chore: add PR date check in mergeable

- apps/docs/src/app/core/component-docs/modal/examples/backdrop-examples/backdrop-examples.component.html
- apps/docs/src/app/core/component-docs/modal/examples/backdrop-examples/backdrop-examples.component.ts
- apps/docs/src/app/core/component-docs/modal/modal-docs.component.html
- apps/docs/src/styles.scss
- libs/core/src/lib/modal/modal-service/modal.service.ts
- libs/core/src/lib/modal/modal-utils/modal-config.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/1863
There is added new property in modal configuration, which allows to add additional class to `modal-container`. It can be helpful in reducing z-index of containers.
> fix: add new way to put class into modal container

- netlify.toml
- package.json
> chore: optimize netlify build

- apps/docs/src/app/core/component-docs/token/token-docs.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/1968
> docs: Token, change naming on example

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- NEW_COMPONENT.md
- NEW_PLATFORM_COMPONENT.md
- PLATFORM_README.md
- README.md
- apps/docs/src/app/core/component-docs/table/table-docs.component.html
- apps/docs/src/app/core/component-docs/time-picker/time-picker-header/time-picker-header.component.html
- apps/docs/src/index.html
- libs/core/README.md
- libs/core/schematics/ng-add/schema.json
- libs/core/src/lib/shellbar/model/shellbar-user.ts
- libs/core/src/lib/utils/abstract-fd-ngx-class.ts
- libs/platform/README.md
- package.json
fixes: #1846 
fixes: #1610 
fixes: #1810 
> docs: update the library name

- ignore.sh
- netlify.toml
Although ignore flag is set, netlify still builds bot PR. This PR brings netlify's support suggested solution 
https://community.netlify.com/t/common-issue-how-can-i-optimize-my-netlify-build-time/3907/21
> fix: for ignore flag for netlify

- apps/docs/src/app/core/component-docs/panel/panel-docs.component.ts
- apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Detect Hunting
There was a mistake in stackblitz service, the html file property was overwrote by scss file.
> chore: Fix Stackblitz Service

- .travis.yml
> chore: Change memory limit on travis

- package-lock.json
- package.json
> chore: fix security issues

- libs/core/src/lib/tabs/tab-list.component.ts
> fix: Check if view is destroyed [Test Purposes]

- libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.html
- libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.ts
- libs/core/src/lib/utils/services/rtl.service.ts
Closes #1967 (side nav rtl)
Pr also resolves error in master's netlify
Before:
After:
> fix: added support for rtl

- .travis.yml
- libs/core/src/lib/tabs/tab-list.component.spec.ts
open an issue to fix the randomly failing tabs test https://github.com/SAP/fundamental-ngx/pull/1996
For now there are removed tab tests, they randomly caused fails.
It's the temporary solution.
> test: tabs - disable randomly failing tab list tests

- libs/core/src/lib/tabs/tabs.service.ts
Defect hunting
There is provided RTL support for tab service. 
> fix: tabs rtl service

- libs/core/src/lib/checkbox/checkbox.module.ts
- libs/core/src/lib/checkbox/checkbox/checkbox.component.html
- libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
Defect Hunting
I changed strategy that was used on checkbox component. Now it's based more on native input/label elements. 
> fix: Remove event prevention on Checkbox

- libs/core/src/lib/token/tokenizer.component.spec.ts
Pr fixes problem with unit test for tokenizer
> fix: unit test fails for tokenizer

- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.html
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.scss
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-example/scroll-spy-custom-example.component.ts
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.html
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.scss
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-custom-offset/scroll-spy-offset-example.component.ts
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-example/scroll-spy-example.component.html
- apps/docs/src/app/core/component-docs/scroll-spy/examples/scroll-spy-example/scroll-spy-example.component.scss
- apps/docs/src/app/core/component-docs/scroll-spy/scroll-spy-docs.component.html
- apps/docs/src/styles.scss
There was a need to add some `css` code to general `styles.scss`, because scroll spy components are encapsulated. 
> docs: (rtl) add RTL support for examples of scroll spy

- apps/docs/src/app/core/components.ts
#2011 
add NotificationOptionsContentComponent to entryComponents
> fix: add NotificationOptionsContentComponent to entryComponents

- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
> fix: product switch drag and drop blue box issue

- karma.conf.js
Execution units increased to 6 which speed up testing time locally and in travis
> chore: increased execution units to 6

- apps/docs/src/app/core/component-docs/dropdown/examples/dropdown-icons-example.component.html
Closes #2028
This PR updates markup of Dropdown with icons example
> fix: Update Dropdown with icons example markup

- libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
- libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
- libs/core/src/lib/input-group/input-group-number.component.html
- libs/core/src/lib/nested-list/nested-list-popover/nested-list-popover.component.ts
Closes: #2037 
This PR adds RTL support for input message displayed inside popover.
> fix: Add RTL support for input messages

- libs/core/src/lib/mega-menu/mega-menu-item/mega-menu-item.component.ts
- libs/core/src/lib/mega-menu/mega-menu.component.html
- libs/core/src/lib/mega-menu/mega-menu.component.scss
- libs/core/src/lib/mega-menu/mega-menu.component.ts
- libs/core/src/lib/utils/keyboard-unification.ts
- libs/core/src/lib/utils/public_api.ts
Fixes #2039 
RTL support added to keyboard events and visuals 
> fix: rtl support added to mega menu

- apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown-example.component.ts
- apps/docs/src/app/core/component-docs/popover/examples/popover-dropdown/popover-dropdown.component.html
- libs/core/src/lib/popover/popover.component.ts
> fix: dropdown menu position fixed

- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss
closes: https://github.com/SAP/fundamental-ngx/issues/2063
there is solved issue with docs side nav on tablets
Before:
After:
> docs: tablet-sidenav

- libs/core/src/lib/select/select.component.html
- libs/core/src/lib/select/select.component.scss
- libs/core/src/lib/select/select.component.spec.ts
- libs/core/src/lib/select/select.component.ts
- libs/platform/src/lib/components/select/select.component.ts
Fixes #2041
Rtl service added in select component to handle rtl
> fix: placeholder's position fixed in rtl

- apps/docs/src/app/core/component-docs/link/examples/link-example.component.html
- apps/docs/src/app/core/component-docs/link/examples/link-example.component.ts
- apps/docs/src/app/core/component-docs/link/link-docs.component.ts
#2106 
Link arrow icons facing wrong direction in arrow mode
> docs: link icon direction in rtl mode and provide example source code

- apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
- apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.ts
Part of #2106 
This PR adds RTL support based on RTLService to "Simple Popovers" exmaple.
Unfortunately I couldn't make it work with custom popover modifier.
> docs: Add RTL support to Simple Popovers example

- apps/docs/src/app/core/component-docs/bar/bar-docs.component.ts
- apps/docs/src/app/core/component-docs/bar/bar-docs.module.ts
- apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.html
- apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.ts
- apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.html
- apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.ts
- apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.html
- apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.ts
- apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.html
- apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.ts
- apps/docs/src/app/core/component-docs/bar/examples/bar-simple-examples.component.ts
#2106 
Fix bar navigation arrows in RTL mode and add examples
> docs: bar nav arrow direction in RTL mode, example source code

- libs/core/src/lib/multi-input/multi-input.component.scss
Part of #2110 
added custom styles for checkbox in multiinput
> fix: fixed popover in modal

- libs/core/README.md
#2114 
Add icon.css and and fonts.css to readme.  Also change example component to checkbox, since switch no longer has any inputs or built-in label
> docs: get installation README.md up to date

- libs/platform/src/index.ts
- libs/platform/src/lib/components/form/collection-base.input.ts
- libs/platform/src/lib/components/form/combo-box/combo-box.component.html
- libs/platform/src/lib/components/form/combo-box/combo-box.component.ts
- libs/platform/src/lib/components/form/combo-box/fdp-combo-box.module.ts
- libs/platform/src/lib/components/form/form-group/form-field/form-field.component.scss
- libs/platform/src/lib/components/form/public_api.ts
- libs/platform/src/lib/components/select/select.component.ts
- libs/platform/src/lib/domain/array-data-source.ts
- libs/platform/src/lib/domain/data-model.ts
- libs/platform/src/lib/domain/data-source.ts
- libs/platform/src/lib/domain/public_api.ts
- libs/platform/src/lib/utils/lang.ts
This combobox with enterprise readyness and we have fixed and updated some form group functionality
#2157
Based on the [specification](https://github.com/SAP/fundamental-ngx/wiki/Platform:-ComboBox-Component-Technical-Design) We have implemented Combobox that can accepts `DataSource` as a INPUT. 
As described [here](https://github.com/SAP/fundamental-ngx/issues/2157) We need to separate how we manipulate our data within the context of component (combobox, dttable,..)  and how we access data. 
> feat(combobox): Adding platform ComboBox version

- libs/platform/README.md
Added nessesary changes and some fixes.
#2167
Getting Platform readme up to date. 
> docs: update platform README.md with UpToDate info

- apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.html
- apps/docs/src/app/core/component-docs/popover/examples/popover-complex-example/popover-complex-example.component.ts
- apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.scss
- apps/docs/src/app/core/component-docs/popover/popover-docs.component.html
- apps/docs/src/app/core/component-docs/popover/popover-docs.component.ts
- apps/docs/src/app/core/component-docs/popover/popover-docs.module.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2132
There is new section with popover header/footer examples
> docs: add new section with headers/footers for popover

- apps/docs/src/app/documentation/core-helpers/api/api.component.html
> fix: use menu button for "select a file"

- src/stories/bar/fd-bar.stories.ts
This pull request fix all of the errors in the bar stories
> test: remove errors in bar story

- angular.json
- apps/docs/src/styles.scss
- libs/core/src/lib/icon/icon.component.scss
- libs/platform/src/lib/components/button/button.component.ts
- package-lock.json
- package.json
This PR is bringing the fonts and the icons into the feature branch.
> fix: bring icons and fonts

- CONTRIBUTING.md
- README.md
fixes: https://github.com/SAP/fundamental-ngx/issues/1909
There are some updates on documentation, on README and on CONTRIBUTION
> docs: Update README and Contributing

- angular.json
Due to errors with lint and google's question:
`Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
how to change this setting, see http://angular.io/analytics`
There is added default answer for that question 
> chore: Change property of anaytics CLI to false

- apps/docs/src/app/core/documentation/core-documentation.component.scss
> docs: fix width of documentation on small screens

- apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html
- apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-format-example.component.ts
- apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-format-example/datetime-format-example.component.html
- libs/core/src/lib/date-picker/date-picker.component.ts
#2135 
Elaborate on setting placeholders for datepickers and datetimepickers with custom formatting
> docs: improve datepicker/datetimepicker placeholder formatting info

- angular.json
- src/stories/fd-form-control/fd-form-control.stories.ts
https://github.com/SAP/fundamental-ngx/pull/2200
This PR adds the input to storybook. It adds all types of knobs to test both the input and the input-message. It is waiting on other PR's to take care of the class order.
> test: add input with form message to storybok

- libs/core/src/lib/select/option/option.component.spec.ts
- libs/core/src/lib/select/option/option.component.ts
#2242 
Fix bug where clicking a disabled option would still fire a change event
> fix: bug where disabled options could be selected

- src/stories/inline-help/inline-help.stories.ts
This or adds inline help to storybook with 
> test:add inline help story to storybook

- libs/core/src/lib/utils/decorators/apply-css-class.decorator.ts
- libs/core/src/lib/utils/decorators/apply-css-class.spec.ts
- libs/core/src/lib/utils/functions/get-string-from-hashmap.ts
- libs/core/src/lib/utils/functions/index.ts
- libs/core/src/lib/utils/functions/uuidv4-generator.ts
- libs/core/src/lib/utils/public_api.ts
Mentioned [#2228#issuecomment-606608608](https://github.com/SAP/fundamental-ngx/pull/2228#issuecomment-606608608)
relates #2228 
The PR brings support for building css classes from multiple directives 
> chore: support for multiple directive in cssclassbuilder added

- src/stories/input-group/input-group.stories.ts
This PR adds input group to storybook using the input group api
> test: add input-group to storybook

- libs/core/src/lib/bar/bar.component.ts
- libs/core/src/lib/form/form-group/form-group.component.ts
- libs/core/src/lib/link/link.component.spec.ts
- libs/core/src/lib/link/link.component.ts
- libs/core/src/lib/list/list-message.directive.ts
- libs/core/src/lib/list/list.component.ts
- libs/core/src/lib/list/list.directives.ts
- libs/core/src/lib/radio/radio-button/radio-button.component.spec.ts
- libs/core/src/lib/radio/radio-button/radio-button.component.ts
- libs/core/src/lib/segmented-button/segmented-button.component.html~HEAD
- libs/core/src/lib/segmented-button/segmented-button.component.html~feat: replaced setters in favor of ngOnChanges
- libs/core/src/lib/segmented-button/segmented-button.component.spec.ts~HEAD
- libs/core/src/lib/segmented-button/segmented-button.component.spec.ts~feat: replaced setters in favor of ngOnChanges
- libs/core/src/lib/tabs/tab-item/tab-item.directive.ts
- libs/core/src/lib/tabs/tab-nav/tab-nav.component.ts
- libs/core/src/lib/tabs/tab-utils/tab-directives.ts
Replaced setters in favour of ngOnChanges for building component CSS classes.
[Code-Contribution-Guideline](https://github.com/SAP/fundamental-ngx/wiki/Code-Contribution-Guideline#building-component-css-classes) has been updated
> fix: replacing setters to ngonchanges

- apps/docs/src/app/documentation/core-helpers/stackblitz/code-example-stack/styles.scss
- apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts
- apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Before there was issues with fonts and icons on stackblitz, to specify additional `styles.scss` file, it was needed to add `angular.json` file
Before:
After:
> chore: add fonts to stackblitz

- apps/docs/src/styles.scss
- libs/core/src/lib/menu/menu.component.scss
- libs/core/src/lib/menu/mixins.scss
This PR brings the old styling for Menu component as a temporary solution.
> chore: bring old styles for menu component

- libs/core/src/lib/link/link.component.spec.ts
- libs/core/src/lib/message-strip/message-strip.component.spec.ts
- libs/core/src/lib/object-status/object-status.component.spec.ts
Ngonchanges method removed from unit test when unnecessary.
> test: ngonchanges removed from unit test when unnecessary

- libs/core/README.md
> docs: remove bit about importing fonts and icons in angular.json

- angular.json
- nx.json
- package-lock.json
- package.json
#2331 
This PR provides fix for the above ticket and updates required libraries to compatible version.
- [x ] the commit message follows the guideline:
> chore: migrate NX lib to version 9 

- libs/core/src/lib/shellbar/shellbar.component.scss
Fix issue with shellbar search input hover styles.  This is only happening on ngx and not styles, not apparent why, so this is probably a temp fix.  Also fix issue with shellbar side nav button
> fix: add fix for Shellbar search input hover styles and Shellbar side nav button

- libs/core/src/lib/multi-input/multi-input.component.html
- libs/core/src/lib/multi-input/multi-input.component.scss
> fix: bug where user cannot click edges of multi input item

- libs/core/src/lib/calendar/calendar.service.ts
RTL support for calendar's keybaord support
> fix: add RTL support for keyboard calendar service

- apps/docs/src/app/core/component-docs/popover/examples/popover-placement/popover-placement-example.component.scss
For some reason, when importing layout.css, the "fd-col--" styles don't get imported.  So hardcoding here for now.  Wondering if anyone else has a better idea of how to fix in styles
> docs: popover placement menus

- libs/core/src/lib/calendar/calendar.component.ts
relates: https://github.com/SAP/fundamental-ngx/issues/2334
fixes: https://github.com/SAP/fundamental-ngx/issues/2314
> fix:rRemove default week count for Calendar

- libs/core/src/lib/radio/radio-button/radio-button.component.ts
Closes #2328
PR replaced ngOnInit to ngAfterViewInit
> fix: changed ngOnInit to ngAfterViewInit

- libs/core/src/lib/shellbar/shellbar.component.scss
https://github.com/SAP/fundamental-ngx/issues/2334
Before:
After:
> fix: side nav Shellbar RTL support

- libs/core/src/lib/input-group/input-group.component.html
- libs/core/src/lib/input-group/input-group.component.ts
Relates #2334
PR changed fdtype of button to transparent
> fix: removed option and changed button fdtype

- libs/core/src/lib/token/tokenizer.component.scss
- libs/core/src/lib/token/tokenizer.component.spec.ts
- libs/core/src/lib/token/tokenizer.component.ts
#2304 
Fixes tokenizer keyboard support and resizing issues in RTL mode.
Depends on https://github.com/SAP/fundamental-styles/pull/861
> fix: rtl tokenizer

- libs/core/src/lib/token/tokenizer.component.html
#2334 
Fix bug where tokenizer/multi-input/combobox button would sometimes have border
> fix: tokenizer input addon should be type transparent

- libs/core/src/lib/tabs/tab-list.component.ts
Closes #2354
PR replaces setTimeout method in favor of observable timer
> fix: settimeout replaced by observable timer

- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss
> docs: Fix sidebar

- libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts
- libs/core/src/lib/popover/popover-directive/popover.directive.ts
It provides improvements on performance 
Before:
After:
> fix: (popover) Fix popover performance

- package.json
remove tslib from devDependencies and add repo and homepage link from package.json
> chore: remove tslib from devDependencies and add repo and homepage link

- apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-examples.component.ts
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-icons-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-options-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-types-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.html
- apps/docs/src/app/platform/platform-documentation.module.ts
- libs/platform/src/lib/components/button/button.component.html
- libs/platform/src/lib/components/button/button.component.scss
- libs/platform/src/lib/components/button/button.component.ts
#2111
1). Light is renamed to transparent
2).half type is removed as Fiori does not have type half.
3). [Options] attribute removed only [type] is present.
4). Ghost style type is added.
5). Documentation examples updated.
6). Test scenarios are tested for all the updated changes.
> fix: (platform) button styles updated to 0.8 styles

- apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
fixes: #2106
update the button for dynamic content in a popover
> docs: update a popover example button #2106

- libs/core/src/lib/popover/popover-directive/popover.directive.spec.ts
- libs/core/src/lib/popover/popover-directive/popover.directive.ts
- libs/core/src/lib/popover/popover.component.ts
- libs/core/src/lib/product-switch/product-switch/product-switch.component.html
- libs/core/src/lib/shellbar/product-menu/product-menu.component.html
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
- package-lock.json
fixes: https://github.com/SAP/fundamental-ngx/issues/2374
Before: 
After:
> fix: Add RTL to popover

- libs/core/src/lib/notification/notification-header/notification-header.component.html
- libs/core/src/lib/notification/notification-header/notification-header.component.ts
> fix: add aria label to notification header for a11y

- apps/docs/src/app/platform/api-files.ts
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-compact-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-compact-examples.component.ts
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-cozy-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-cozy-examples.component.ts
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-examples.component.ts
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-header/platform-menu-button-header.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-header/platform-menu-button-header.component.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
- apps/docs/src/app/platform/platform-documentation.module.ts
- apps/docs/src/app/platform/platform-documentation.routes.ts
- libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
- libs/platform/src/lib/components/menu-button/menu-button.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.scss
- libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
- libs/platform/src/lib/components/menu-button/menu-button.component.ts
- libs/platform/src/lib/components/menu-button/menu-button.module.ts
- libs/platform/src/lib/components/menu-button/public_api.ts
- libs/platform/src/lib/platform.module.ts
https://github.com/SAP/fundamental-ngx/issues/2222
A new standalone component of menu button component
> fix: (platform) Menu button As a component

- libs/core/src/lib/product-switch/product-switch/product-switch.component.html
- libs/core/src/lib/product-switch/product-switch/product-switch.component.ts
#2444
This PR makes the input for the product-switch placement attribute dynamic
> fix: change static placement value

- NEW_COMPONENT.md
- apps/docs/src/assets/NEW_COMPONENT.md
> docs: update new component documentation

- karma.conf.js
> test: Lower parallel tests to 3

- libs/core/src/lib/select/select.component.spec.ts
Change indirect import path (causing TS errors) to direct import path.
> fix: Fix indirect import path - Select tests

- package-lock.json
- package.json
> fix: ie11 fixed

- apps/docs/src/app/core/component-docs/select/select-docs.component.html
Because we will introduce new way of handling mobile view this PR hides Select mobile documentation section.
> docs: Hide select mobile section

- apps/docs/src/app/core/component-docs/calendar/examples/calendar--i18n-moment-example.component.ts
- apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-complex-i18n-example/date-picker-complex-i18n-example.component.ts
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts
- package-lock.json
- package.json
fix the calendars using moment.js localization packages
> docs: fix the calendars using moment.js localization packages

- docker/Dockerfile
- karma.conf.js
- package.json
There is included new command for testing in docker
> test: Add docker to unit tests

- libs/core/src/lib/switch/switch.component.html
Closing #2076
PR adds a click call on a label in order to set focus on the input element
> fix: added click event to set focus on input

- libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
Closes #2119
PR brings a workaround, it creates a stronger selector in order to force display flex, although I don't like it but I don't like using !important even more.
> fix: more powerful selector added

- PLATFORM_README.md
- libs/platform/README.md
#2506 
Updates the Readme.md file with a section on i18n support for platform lib.
> docs: Update platform lib README.md with i18n section

- .github/mergeable.yml
Kevin is one of the core Approval. Its either Me or Kevin that needs to review/approve the request
> chore: update mergeable 

- apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.module.ts
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-contextual-menu-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.scss
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar.module.ts
- libs/platform/src/lib/components/action-bar/action-bar.component.html
- libs/platform/src/lib/components/action-bar/action-bar.component.ts
https://github.com/SAP/fundamental-ngx/issues/2553
This PR contains fix for rtl issue of action bar back button.
> Fix(Platform): RTL Action bar back button.

- package-lock.json
- package.json
> fix: highlightsjs version downgraded in order to fix ie 11

- libs/core/src/lib/menu/menu-keyboard.service.spec.ts
- libs/core/src/lib/menu/menu-keyboard.service.ts
Closes: #2591
This PR adds: 
- `KeyUtil` support in `MenuKeyboardService`
- `MenuKeyboardService` tests
> fix: Use KeyUtil in MenuKeyboardService

- libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts
- libs/core/src/lib/checkbox/checkbox/checkbox.component.html
- libs/core/src/lib/checkbox/checkbox/checkbox.component.spec.ts
- libs/core/src/lib/checkbox/checkbox/checkbox.component.ts
- libs/core/src/lib/token/tokenizer.component.spec.ts
- libs/core/src/lib/utils/tests/when-stable.ts
Closes #2568
Fixing checkbox crashing chrome.
Local unit tests fixed.
> fix: checkbox crashing chrome fix and unit tests

- apps/docs/src/app/core/documentation/core-documentation.component.html
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.html
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.ts
- apps/docs/src/app/documentation/documentation-base.component.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.html
- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
PR brings fix for 'expression has been changed' error and also brings small improvement
> docs: exp has been changed fix

- apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.component.ts
- apps/docs/src/app/core/component-docs/calendar/calendar-docs.component.ts
- apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.ts
- apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts
- apps/docs/src/app/core/component-docs/segmented-button/segmented-button-docs.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2617
There were some mistakes in stackblitz, which are fixed now.
> chore: Add fixes to stackblitz examples

- libs/core/src/lib/pagination/pagination.component.html
> fix: update pagination class name

- libs/core/README.md
There is changed versioning descriptions, old one was quite out of date
> docs: change versioning

- apps/docs/src/app/core/component-docs/popover/examples/popover-dynamic/popover-dynamic-example.component.html
- libs/core/src/lib/popover/popover-directive/popover.directive.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2596
There is fixed initial opened popover,
Also documentation example with side nav had to be changed, due to side nav markup changes.
> fix: Fix initially open popover, change example on popover with side nav

- libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts
- libs/core/src/lib/switch/switch.component.spec.ts
Closes: #2670 
`markForCheck` tested component before running `detectChanges` on fixture
> fix: Fix failing Switch test

- libs/core/src/lib/date-picker/date-picker.component.spec.ts
The code was pushed by accident, revering the changes
> test: uncomment accidentally commented out tests for Date Picker

- libs/core/src/lib/list/list.component.scss
Relates to: List example on dialog, https://github.com/SAP/fundamental-ngx/issues/2674
proper migration will be tackled with https://github.com/SAP/fundamental-ngx/issues/2701
There was new css from styles, without migration on ngx.
In this PR i bring them back.
> fix: bring old list css

- package-lock.json
- package.json
> chore: bump theming package

- apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
fix theme selector
related #2674
> docs: fix theme selector

- apps/docs/src/fd-typedoc/helpers/main.helpers.js
- libs/platform/src/lib/components/action-bar/action-bar.component.spec.ts
- libs/platform/src/lib/components/form/collection-base.input.ts
- libs/platform/src/lib/components/form/form.spec.ts
- libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
- libs/platform/src/lib/components/form/radio-group/radio-group.component.ts
N/A
The FormGroup and FormField component code currently have no unit tests. I wanted to create an initial unit test spec with a test component set-up and a few basic tests.
While creating the unit tests for FormGroup and FormField, I found some broken tests in the platform code - namely the ActionBar and RadioGroup components.
_ActionBar_
The ActionBar component tests were failing because some of the query selectors were returning undefined. The selectors were based off of Fundamental-Style CSS class names. However, it relied on the assumption that these class names would not change within the core component templates.
I changed the query selectors to be based of custom `data-*` attributes which are defined in the ActionBar component template. In this way the query definition and …
> test: (platform) Adding tests for FormGroup/FormField and fixing tests for ActionBar and RadioGroup

- libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts
- libs/core/src/lib/menu/menu.component.ts
- libs/core/src/lib/menu/menu.interface.ts
- libs/core/src/lib/multi-input/multi-input.component.ts
- libs/core/src/lib/select/select.component.ts
This PR fixes `MenuComponent` <=> `MenuMobileComponent` dependency and updates `Injector.create()` call signatures.
> fix: Menu circular dependency

- libs/core/src/lib/localizator-editor/localization-editor.component.html
- libs/core/src/lib/localizator-editor/localization-editor.component.spec.ts
- libs/core/src/lib/localizator-editor/localization-editor.module.ts
Part of: #2674
Switch from menu to list usage
> fix(core) Localization editor using list instead of menu

- apps/docs/src/app/core/component-docs/table/table-docs.component.scss
- apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.scss
- apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts
- apps/docs/src/app/documentation/core-helpers/example-background/example-background.component.ts
- apps/docs/src/styles.scss
- libs/core/src/lib/tile/tile.component.scss
#2674
PR brings fix for docs and restores old style for tile
> fix: fixed docs and restored old tile styles

- apps/docs/src/app/core/component-docs/panel/examples/panel-compact-example.component.html
- apps/docs/src/app/core/component-docs/panel/examples/panel-expandable-example.component.html
- apps/docs/src/app/core/component-docs/panel/examples/panel-fixed-example.component.html
- apps/docs/src/app/core/component-docs/panel/examples/panel-fixed-height-example.component.html
- libs/core/src/lib/panel/panel-expand/panel-expand.component.spec.ts
- libs/core/src/lib/panel/panel-expand/panel-expand.component.ts
- libs/core/src/lib/panel/panel.component.spec.ts
- libs/core/src/lib/panel/panel.component.ts
- libs/core/src/lib/panel/panel.service.ts
The PR for the new Panel component was merged before some comments by @salarenko were added. This PR addresses the following comments:
> fix: add Panel component improvements

- apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.scss
> docs: fix docs tile background

- apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-header/platform-button-header.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-header/platform-checkbox-header.component.html
- apps/docs/src/app/platform/component-docs/platform-info-label/platform-info-label-header/platform-info-label-header.component.html
- apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-header/platform-split-menu-button-header.component.html
- libs/platform/src/lib/components/form/checkbox/checkbox.component.ts
> docs: platform docs cleanup

- apps/docs/src/app/core/component-docs/button/button-docs.module.ts
> docs: format button example

- libs/core/src/lib/radio/radio-button/radio-button-reactive-form.component.spec.ts
commend randomly failing test - radio button
> test: commend randomly failing test

- package-lock.json
- package.json
> chore: bump semantic version to 8

- libs/core/src/lib/date-picker/date-picker.component.html
> fix: replace datepicker icon

- apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.scss
- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.scss
fixes https://github.com/SAP/fundamental-ngx/issues/2166
This PR replaces all hardcoded colors related to the Drag and Drop functionality of the Product switch with theme variables.
> fix: replace hardcoded colors in Product switch with theme variables

- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
This is just a cleanup for the platform definition to removed un-used select definition
> fix(select): Cleanup unused doc definition

- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-header/platform-menu-button-header.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.spec.ts
- libs/platform/src/lib/components/menu-button/menu-button.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2632
Documentation changes for common format with other component.
Accessibility fixes.
> fix: (platform) Menu button Accessibility fix and Documentation changes.

- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-header/platform-action-bar-header.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/2405
Adding Platform specific enhancement documentation.
Adding platform specific enhancement details for platform Action Bar component.
> docs(platform): action bar document update

- apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-disabled-emphasized-example.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-emphasized-example.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-standard-example.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-header/platform-link-header.component.html
- libs/platform/src/lib/components/link/link.component.html
- libs/platform/src/lib/components/link/link.component.spec.ts
- libs/platform/src/lib/components/link/link.component.ts
mentioned in https://github.com/SAP/fundamental-ngx/issues/2542
1). It has documentation details updated.
2). added type attribute for setting native type attribute on <a> tag.
3). Added examples for added attributes.
BREAKING CHANGES:
Renamed properties:
Before :type After: linktype
> fix: (platform) Link documentation changes and Extending from Base class.

- libs/core/src/lib/shellbar/shellbar.component.html
relates to https://github.com/SAP/fundamental-ngx/issues/2777
Before:
After:
> fix: Shellbar positioning items on Ie11

- apps/docs/src/app/core/component-docs/action-bar/action-bar-docs.component.ts
Part of: #2777
Fixed invalid file names
> fix: Correct ActionBar example StackBlitz configuration

- libs/core/src/lib/tabs/tab-list.component.ts
- libs/core/src/lib/tabs/tabs.service.spec.ts
- libs/core/src/lib/tabs/tabs.service.ts
Part of: #2777
Tabs now support cross browser keyboard navigation using `KeyUtil`
> fix: Add cross browser key support to tabs component

- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.html
minor change from defect hunting
> docs: code example button margin

- apps/docs/src/app/core/documentation/core-documentation.component.ts
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/section.interface.ts
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.html
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.scss
- apps/docs/src/app/documentation/shared-core-modules.ts
> docs: use side navigation instead of sections toolbar #2709

- apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
- apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.ts
- apps/docs/src/app/core/component-docs/table/table-docs.component.html
- apps/docs/src/app/core/component-docs/table/table-docs.component.ts
- apps/docs/src/app/core/component-docs/table/table-docs.module.ts
fixes #2435, #2436, #2437 
Decided to just handle all these issues in one ticket because they are really just documentation, so much easier than initial estimations
> docs: demonstrate toolbar with table

- apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.module.ts
- apps/docs/src/app/core/component-docs/checkbox/checkbox-header/checkbox-header.component.html
- apps/docs/src/app/core/component-docs/radio/radio-docs.module.ts
- apps/docs/src/app/core/component-docs/radio/radio-header/radio-header.component.html
There is added information about the checkbox/radio crashing browsers. There is also added workaround for it.
> docs: add checkbox and radio issue description

- libs/core/src/lib/pagination/pagination.service.spec.ts
- libs/core/src/lib/pagination/pagination.service.ts
Part of https://github.com/SAP/fundamental-ngx/issues/2777
Fixes the issue where pagination goes 1 2 3 ... 5 when there are 5 pages.
> fix: pagination ... issue when there are 5 pages

- PLATFORM_README.md
- apps/docs/src/app/platform/api-files.ts
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-cozy-mode-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-positive-and-negative-action-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-simple-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-back-button-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-description-example.component.html
- apps/docs/src/app/platform/component-docs/platform-action-bar/platform-action-bar-examples/platform-action-bar-with-long-title-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-icons-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-sizes-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-state-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-types-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-header/platform-button-header.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button.module.ts
- apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-error-handling.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.html
- libs/platform/src/lib/components/base.ts
- libs/platform/src/lib/components/button/button.component.html
- libs/platform/src/lib/components/button/button.component.scss
- libs/platform/src/lib/components/button/button.component.spec.ts
- libs/platform/src/lib/components/button/button.component.ts
- libs/platform/src/lib/components/button/button.module.ts
#2538 
1). It has documentation details updated.
2). Aria Selected, area disabled added as properties for accessibility.
3). Test specs are updated with the same.
4). Class added for width truncation because in the latest (0.9.0 +)version truncation is not working as per Fiori3.same issue is observed in core.
BREAKING CHANGES:
Renamed properties:
Before :compact       After: contentDensity
Before: type               After:buttonType
> feat:(platform) button is updated with core changes

- apps/docs/src/app/platform/api-files.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-docs.module.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-autogrow-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-autogrow-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-basic-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-basic-example.component.scss
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-basic-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-template-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-template-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-i18n-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-i18n-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-header/platform-textarea-header.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-header/platform-textarea-header.component.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
- apps/docs/src/app/platform/platform-documentation.routes.ts
- libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.html
- libs/platform/src/lib/components/form/input-message-group-with-template/input-message-group-with-template.component.scss
- libs/platform/src/lib/components/form/public_api.ts
- libs/platform/src/lib/components/form/text-area/text-area.component.html
- libs/platform/src/lib/components/form/text-area/text-area.component.scss
- libs/platform/src/lib/components/form/text-area/text-area.component.spec.ts
- libs/platform/src/lib/components/form/text-area/text-area.component.ts
- libs/platform/src/lib/components/form/text-area/text-area.module.ts
- libs/platform/src/lib/platform.module.ts
#2571 
Introducing textarea as a component in ngx/platform, which works with Platform Forms in a reactive and template approach, and also has the added features of autogrowing and displaying a counter message.
> fix: (platform) Introduce textarea as a component

- apps/docs/src/app/documentation/core-helpers/code-example/example-file.ts
- apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Per Gracjan's request on the table PR: https://github.com/SAP/fundamental-ngx/pull/2819#discussion_r452228038
> docs: add support for pipes in stackblitz examples

- libs/core/src/lib/step-input/step-input.component.html
- libs/core/src/lib/step-input/step-input.component.ts
This PR adds input placeholder to StepInput
> fix: add placeholder to StepInput

- apps/docs/src/app/core/component-docs/table/examples/table-cdk-example.component.scss
- apps/docs/src/app/core/component-docs/table/table-docs.component.html
- libs/core/src/lib/table/table-wrapper.component.ts
#2440 
update table wrapper component to apply classes to thead/tbody/tfoot
> fix: update table wrapper component to apply classes to thead/tbody/tfoot

- apps/docs/src/app/documentation/documentation-base.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2881
There is fixed behaviour of sidebar, which now doesn't collapse/expand always when it's being resized.
Now, when window approach less than 560px, it will be hidden
> docs: stop showing side bar on resize

- apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-mobile/combobox-mobile-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-mobile/combobox-mobile-example.component.ts
- libs/core/src/lib/calendar/calendar-views/calendar-aggregated-year-view/calendar-aggregated-year-view.component.spec.ts
- libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.html
- libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.spec.ts
- libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.ts
- libs/core/src/lib/combobox/combobox.component.ts
- libs/core/src/lib/combobox/combobox.interface.ts
- libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts
- libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
- libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
- libs/core/src/lib/select/select-mobile/select-mobile.component.ts
- libs/core/src/lib/utils/base-class/mobile-mode.class.ts
This PR implements `MobileModeBase` class into `ComboboxMobileComponent` as well as other mobile control utils.
> fix(core) Implement MobileModeBase into mobile Combobox

- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.html
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts
- libs/core/src/lib/time-picker/time-picker.component.ts
- report.20200727.103939.65846.0.001.json
fixes: #2851 
This pr makes the placeholder as not being hidden anymore. It is now an Input, the default is set to the type of time picker that is being used
> fix: change placeholder to input on time picker

- libs/core/src/lib/toolbar/toolbar.component.ts
- libs/core/src/lib/utils/directives/carousel/carousel.directive.spec.ts
- libs/core/src/lib/utils/directives/carousel/carousel.directive.ts
- libs/core/src/lib/utils/directives/carousel/carousel.module.ts
- libs/core/src/lib/utils/directives/carousel/hammer.config.ts
- libs/core/src/lib/utils/public_api.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/2917
> fix: Remove circular dependency from library

- apps/docs/src/app/core/component-docs/toolbar/examples/toolbar-overflow-example.component.html
- apps/docs/src/app/core/component-docs/toolbar/toolbar-docs.module.ts
- libs/core/src/lib/toolbar/toolbar.component.ts
- src/stories/toolbar/fd-toolbar.stories.ts
Closing #2861
PR brings an update and small fix for toolbar order of items
> fix: fixed order of component

- libs/core/src/lib/avatar/avatar.component.ts
- libs/platform/src/lib/components/form/checkbox-group/checkbox-group.component.ts
- libs/platform/src/lib/components/form/checkbox/checkbox.component.ts
- libs/platform/src/lib/components/form/form-group/form-field/form-field.component.ts
We recently updated tsLint config. Some of existing PRs have been checked using previous tsLint config, and changes they bring might not pass on master.
We merged some PRs without rebase bringing some code that doesn't pass linting process automatically failing master build.
> fix: Linter issues 

- libs/core/src/lib/multi-input/multi-input.component.scss
Part of #2939
Fixes Multi Input visual issue.
Before:
After:
> fix: Remove Multi Input  toggle button space

- libs/core/src/lib/combobox/combobox.component.ts
Related to: https://github.com/SAP/fundamental-ngx/issues/2939
Now the change detection is forced to update, when item is picked from list on combobox.
> fix: Update value on combobox pick

- apps/docs/src/app/core/component-docs/button/examples/button-icons-example.component.html
- apps/docs/src/app/core/component-docs/button/examples/button-menu-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-icons-example.component.html
#2965 
For the non-text button need tooltip for sharing information about it and aria-label for. screen readers
> docs: Button accessibility issues addressed for screen readers

- apps/docs/src/app/core/component-docs/time/examples/time-form-example.component.html
- apps/docs/src/app/core/component-docs/time/examples/time-form-example.component.ts
- libs/core/src/lib/shellbar/shellbar.component.scss
There are some things left for 0.21.0
- Shellbar Combobox
Before:
After:
- Time disalbed example removed, there is no such thing as disabled time
> fix: remove time disabled example, fix combobox in shellbar

- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-examples.component.ts
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-examples.scss
View encapsulation has to be removed from button documentation for alignment in the platform as requested by 
> docs: (platform) encapsulation from button documentation removed

- libs/core/src/lib/input-group/input-group.component.html
https://github.com/SAP/fundamental-ngx/issues/3049
Fixed class binding for input-group
> fix: (core) fix class binding for input-group

- apps/docs/src/app/platform/api-files.ts
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-docs.module.ts
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-clickable-and-icon-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.scss
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-generic-text-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-icon-text-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-inverted-generic-text-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-large-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-example/platform-object-status-text-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-header/platform-object-status-header.component.html
- apps/docs/src/app/platform/component-docs/platform-object-status/platform-object-status-header/platform-object-status-header.component.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
- apps/docs/src/app/platform/platform-documentation.routes.ts
- libs/core/src/lib/object-status/object-status.component.ts
- libs/platform/src/index.ts
- libs/platform/src/lib/components/object-status/object-status.component.html
- libs/platform/src/lib/components/object-status/object-status.component.spec.ts
- libs/platform/src/lib/components/object-status/object-status.component.ts
- libs/platform/src/lib/components/object-status/object-status.module.ts
- libs/platform/src/lib/components/object-status/public_api.ts
- libs/platform/src/lib/platform.module.ts
https://github.com/SAP/fundamental-ngx/issues/2505
The ObjectStatus component is used to highlight the status of an object by coloring the text.
The Platform component is implemented as a component as opposed to the directive approach that Core takes.
> fix: Platform wrapper component for object status with document changes

- libs/core/src/lib/fundamental-ngx-core.module.ts
> fix: export toolbar module

- libs/core/src/lib/file-uploader/file-uploader.component.scss
- package-lock.json
- package.json
revert including fundamental styles version 0.11
> fix: revert including fundamental styles version 0.11

- libs/platform/src/lib/components/form/switch/switch/switch.config.ts
https://github.com/SAP/fundamental-ngx/issues/3039
https://github.com/SAP/fundamental-ngx/issues/3066
Fixed wrong path in `switch.config.d.ts`
> fix: (platform) fix wrong path after build

- apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/platform-input/platform-input-example/platform-input-reactive-validation-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-panel/platform-panel-docs.component.ts
- libs/platform/src/lib/components/form/input/input.component.html
- libs/platform/src/lib/components/form/input/input.component.scss
- libs/platform/src/lib/components/form/input/input.component.ts
- libs/platform/src/lib/platform.module.ts
Addressing stackblitz error and Input error
https://github.com/SAP/fundamental-ngx/issues/3029
In Platform few components examples in stack blitz not working 
> fix(platform): Addressing stackblitz error and Input error

- libs/core/src/lib/datetime-picker/datetime-picker.component.scss
- libs/core/src/lib/datetime-picker/datetime-picker.component.ts
- libs/core/src/lib/popover/popover-body/popover-body.component.ts
> fix: datetime picker not rendering correctly

- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
> fix: add shellbar button user menu class

- apps/docs/src/app/core/component-docs/localization-editor/localization-editor-header/localization-editor-header.component.html
- libs/core/src/lib/localizator-editor/localization-editor-item/localization-editor-item.component.spec.ts
- libs/core/src/lib/localizator-editor/localization-editor-item/localization-editor-item.component.ts
- libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.spec.ts
- libs/core/src/lib/localizator-editor/localization-editor-main/localization-editor-main.component.ts
- libs/core/src/lib/localizator-editor/localization-editor.component.ts
- libs/core/src/lib/localizator-editor/localization-editor.directives.ts
- libs/core/src/lib/localizator-editor/localization-editor.module.ts
deprecate Localization Editor component
> chore: deprecate Localization Editor component

- libs/core/src/lib/menu/menu.component.html
- libs/core/src/lib/menu/menu.component.ts
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.ts
> fix: display popover arrow by default but also provide option to disable

- apps/docs/src/app/core/component-docs/combobox/examples/combobox-disabled-example.component.html
- apps/docs/src/app/core/component-docs/input-group/examples/input-group-states-example/input-group-states-example.component.html
- apps/docs/src/app/core/component-docs/table/table-docs.module.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- libs/core/src/lib/combobox/combobox.component.html
> docs: fix combobox and table docs

- libs/core/src/lib/combobox/combobox.component.ts
https://github.com/SAP/fundamental-ngx/issues/2733
Fixed Combobox readonly mode
> fix: (core) fix combobox readonly mode

- apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.html
- apps/docs/src/app/core/component-docs/dialog/dialog-docs.module.ts
- apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts
- apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html
- apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.html
- apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html
- apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.html
- apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html
- apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html
- apps/docs/src/app/core/component-docs/dialog/examples/index.ts
- apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts
- apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html
Part of: #3085
This PR:
- Changes to static string bindings when possible
- Imports `InputGroupModule`
- Creates barrel import
> chore: Improve Dialog documentation

- apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html
- apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.module.ts
- apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-wrapper-example.component.html
- apps/docs/src/app/core/component-docs/busy-indicator/examples/index.ts
- libs/core/src/lib/busy-indicator/busy-indicator.component.scss
Part of: #3085
This PR:
- Import missing `FormsModule`
- Changes to static string binding
- Import barrel
- Removes visual focus indicator when Busy indicator should not be focusable
> Fix: Improve Busy Indicator documentation and focus behavior

- apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.html
- apps/docs/src/app/core/component-docs/combobox/combobox-docs.component.ts
- apps/docs/src/app/core/component-docs/combobox/combobox-docs.module.ts
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-async-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-columns-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-disabled-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-disabled-example.component.scss
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-disabled-example.component.ts
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-displaywith-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-dynamic-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.scss
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-example.component.ts
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-forms-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-forms-example.component.ts
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-group-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-height-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-mobile/combobox-mobile-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-open-control-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-search-function-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/index.ts
Part of: #3085 
This PR:
- Changes to static string binding when possible
- Makes examples use `fd-form-item` and `fd-form-label`
- Creates import barrel
- Imports missing `ListModule`
> chore: Improve Combobox documentation

- apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.html
- apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
part of https://github.com/SAP/fundamental-ngx/issues/3085
> docs: fix links for images on bar component examples

- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.html
- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.spec.ts
- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts
- libs/core/src/lib/utils/tests/event-objects.ts
fixes #2899, #2896 
wrong issue number on the branch name
> fix: programmatically click product menu item on space/enter and add keyboard arrow navigation

- apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.html
- apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.module.ts
- apps/docs/src/app/core/component-docs/checkbox/checkbox-header/checkbox-header.component.html
- apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-custom-values-example.component.ts
- apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-reactive-forms-example.component.ts
- apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-states-example.component.ts
- apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-tristate-example.component.ts
- apps/docs/src/app/core/component-docs/checkbox/examples/index.ts
- apps/docs/src/app/core/component-docs/radio/examples/index.ts
- apps/docs/src/app/core/component-docs/radio/examples/radio-example.component.html
- apps/docs/src/app/core/component-docs/radio/radio-docs.component.html
- apps/docs/src/app/core/component-docs/radio/radio-docs.module.ts
- apps/docs/src/app/core/component-docs/radio/radio-header/radio-header.component.html
Part of: #3085
This PR:
- Creates import barrel
- Changes to static string binding when possible
> chore(core): minor docs examples improvements

- libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.html
> fix: product switch line wrap bug

- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-inverted-example.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-truncated-example.component.html
This PR provides fixes for defects found in link component.
> fix: (platform) Defect fixes for platform link components

- libs/core/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.ts
part of https://github.com/SAP/fundamental-ngx/issues/3085
There are soem workarounds for IE11 included into DND.
> fix: fix DND on IE11

- apps/docs/src/app/platform/component-docs/platform-button/platform-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-icons-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-sizes-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-state-example.component.html
- apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-types-example.component.html
- libs/platform/src/lib/components/button/button.component.html
- libs/platform/src/lib/components/button/button.component.ts
#3205 
#3245
removal of [] from the documentation.
properties alignment as per angular styling guidelines, along with type attribute.
> fix: (platform) button issues fix after defect hunt

- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-compact-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-cozy-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-example.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.ts
this PR fixes issues that were raised during defect hunting.
> fix: (platform) fix for menu position in menu button

- apps/docs/src/app/core/component-docs/icon/examples/icon-example.component.html
- apps/docs/src/app/core/component-docs/icon/examples/icon-example.component.ts
- apps/docs/src/app/core/component-docs/icon/icon-docs.component.html
- apps/docs/src/app/core/component-docs/icon/icon-docs.component.ts
- apps/docs/src/app/core/component-docs/schemas.ts
- apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.scss
- apps/docs/src/app/documentation/shared-core-modules.ts
- apps/docs/src/app/schema/containers/schema-group/schema-group.component.scss
> docs: update theming colors for docs; update icon example

- .reuse/dep5
- LICENSES/Apache-2.0.txt
- README.md
- libs/core/README.md
- libs/platform/README.md
> chore: update README.md with REUSE badge

- apps/docs/src/app/core/component-docs/object-status/examples/object-status-default-example.component.html
- libs/core/src/lib/object-status/object-status.component.spec.ts
- libs/core/src/lib/object-status/object-status.component.ts
- package-lock.json
- package.json
This PR contains migration of object status
> fix: Migrate object status to 0.12.0

- libs/core/src/lib/switch/switch.component.html
- package-lock.json
Minor A11Y change inside switch component
> fix: migrate switch changes to 0.12.0 styles

- apps/docs/src/app/core/component-docs/table/examples/table-popin-example/table-popin-example.component.html
this PR contains: table icon update A11y regarding to 0.12.0 styles
> fix: table update A11y regarding to 0.12.0 styles

- apps/docs/src/app/core/component-docs/tile/examples/action-tile-example.component.html
- apps/docs/src/app/core/component-docs/tile/examples/kpi-tile-example.component.html
- apps/docs/src/app/core/component-docs/tile/examples/launch-tile-example.component.html
Minor A11y changes due to 0.12.0 styles changes
> fix: Migrate A11y changes from 0.12.0 to numeric content and tiles

- apps/docs/src/app/core/component-docs/calendar/examples/calendar--i18n-moment-example.component.ts
update calendar internationalization examples with momentjs
> docs: update calendar internationalization examples with momentjs

- apps/docs/src/app/core/component-docs/checkbox/checkbox-header/checkbox-header.component.html
- apps/docs/src/app/core/component-docs/radio/radio-header/radio-header.component.html
part of #3420 
remove the message strip messages from radio and checkbox buttons
> docs: remove message strip info message from radio and checkbox

- apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.scss
This PR:
- Removes animation from select example
> chore: Remove animation from select example

- apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.html
- apps/docs/src/app/core/component-docs/combobox/examples/combobox-template-example.component.ts
This PR:
- Updates Combobox custom item template documentation example to use proper list markup
> docs: Combobox custom template

- libs/core/src/lib/combobox/combobox.component.ts
This PR:
- Fixes missing method call to properly disable/enable focus trap
> fix: Combobox navigate with tab

- apps/docs/src/app/core/component-docs/table/examples/table-checkboxes-example.component.ts
Part of https://github.com/SAP/fundamental-ngx/issues/3420
> docs: add missing icons to table examples

- apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-collapsible-example.component.html
- apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-collapsible-example.component.ts
- apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.html
- apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.scss
- apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav/shellbar-side-nav-example.component.ts
- apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html
- apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.ts
- apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.module.ts
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.html
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.html
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.spec.ts
- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts
- libs/core/src/lib/shellbar/shellbar.component.html
- libs/core/src/lib/shellbar/shellbar.component.scss
- libs/core/src/lib/shellbar/shellbar.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/3420
This PR contains:
Lib:
- Added `size` property for shellbar
- Fixed Menu with icons usage
- Removed unused code from  *.scss regarding `fd-shellbar-side-nav-control`
From Documentation:
- Changed example of collapsible shellbar - Added description about size
- Fixed example of visual in shellbar with side nav
> fix: Shellbar Examples and Size added

- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-compact-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-cozy-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu-button/platform-menu-button-examples/platform-menu-button-example.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.html
- libs/platform/src/lib/components/menu-button/menu-button.component.ts
- libs/platform/src/lib/components/menu/menu.component.html
- libs/platform/src/lib/components/menu/menu.component.ts
https://github.com/SAP/fundamental-ngx/issues/3357
https://github.com/SAP/fundamental-ngx/issues/3364
This PR fixes both issues.
1. Remove invalid example fro menu button.
2. Include compact density for menu and modify compact menu example for the same.
> fix: (platform) Removed Invalid examples and compact menu button fix

- libs/core/src/lib/avatar/avatar.component.html
- libs/core/src/lib/avatar/avatar.component.ts
- libs/core/src/lib/shellbar/shellbar.component.scss
- libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.html
Part of https://github.com/SAP/fundamental-ngx/issues/3420
Add glyph to Avatar inside user menu button.
> fix: add fix for ShellBar user menu button using Avatar

- libs/core/src/lib/layout-grid/layout-grid.component.scss
Brings back Layout Grid styles from 0.11.0
> fix: Bring Layout Grid 0.11.0 styles

- apps/docs/src/app/core/component-docs/card/card-docs.component.html
- apps/docs/src/app/core/component-docs/card/card-docs.component.ts
- apps/docs/src/app/core/component-docs/card/card-docs.module.ts
- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.html
- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.scss
- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.ts
- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/card-bar.component.html
- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/card-bar.component.scss
- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/card-bar.component.ts
- apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.html
- apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.scss
- apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.ts
- apps/docs/src/app/core/component-docs/card/examples/charts/google-charts.service.ts
- package-lock.json
- package.json
Closes: https://github.com/SAP/fundamental-ngx/issues/3508
The purpose of this PR is to extend core `Card` documentation by adding `bar chart list card` example and extend `analytical card` example by adding a chart using third party library for that. 
> docs: (core) add bar chart list card example

- libs/platform/src/lib/components/form/combobox/index.ts
#3555 
Added export of `highlight.pipe` and `auto-complete.directive` to combobox index.tx file.
This fixes the following compilation error:
```
Compiling @fundamental-ngx/platform : es2015 as esm2015
Error: Error on worker #1: Error: Failed to find exported name of node (class HighlightPipe {
constructor(comboboxConfig) {
this.comboboxConfig = comboboxConfig;
}
transform(value, searchText, matchingStrategy = this.comboboxConfig.matchingStrategy) {
if (!(value && searchText)) {
return value;
}
if (matchingStrategy === MatchingStrategy.STARTS_WITH) {
return this._searchByStrategyStartsWith(value, searchText);
}
if (matchingStrategy === MatchingStrategy.CONTAINS) {
return this._searchByStrategyContains(value, searchText);
}
return value;
}
_searchByStrategyStartsWith(value, searchText) { …
```
> fix: (Platform) add highlight.pipe and auto-complete.directive to exports

- apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.html
- apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
fixes #3107 
The menu is very long and should have a max-height - this will be fixed as part of https://github.com/SAP/fundamental-ngx/issues/3522
> docs: (Core) add dropdown for switching to old docs versions

- apps/docs/src/app/platform/api-files.ts
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-example.component.scss
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-and-icon-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-clickable-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-only-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-header/object-marker-header.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-header/object-marker-header.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-marker/platform-object-marker-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/platform-object-marker-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-marker/platform-object-marker.module.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
- apps/docs/src/app/platform/platform-documentation.routes.ts
- libs/platform/src/index.ts
- libs/platform/src/lib/components/object-marker/object-marker.component.html
- libs/platform/src/lib/components/object-marker/object-marker.component.spec.ts
- libs/platform/src/lib/components/object-marker/object-marker.component.ts
- libs/platform/src/lib/components/object-marker/object-marker.module.ts
- libs/platform/src/lib/components/object-marker/public_api.ts
- libs/platform/src/lib/platform.module.ts
https://github.com/SAP/fundamental-ngx/issues/2601
This indicates the technical status of an object.
It is enabled for the dynamic page layout, snapping header, object page header, upload collection, and object list item.
The technical status can be represented as and icon, with an icon and text, or as text only, depending on the screen size.
Currently, the following technical statuses can be visualized by the object marker:
Flag
Favorite
Editing Status (Draft, Locked, Unsaved Changes)
The editing status is part of the draft handling concept.
> feat: (Platform) add Object Marker documentation and platform library changes

- libs/platform/src/lib/components/list/base-list-item.ts
- libs/platform/src/lib/components/list/list.component.ts
- libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.ts
#3578
Adds missing types which cause the following error:
```
ERROR in node_modules/@fundamental-ngx/platform/lib/components/list/base-list-item.d.ts:123:29 - error TS2307: Cannot find module '../../../../../../dist/libs/core/fundamental-ngx-core' or its corresponding type declarations.
123     _contentDensity: import("../../../../../../dist/libs/core/fundamental-ngx-core").ToolbarSize;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@fundamental-ngx/platform/lib/components/list/list.component.d.ts:114:29 - error TS2307: Cannot find module '../../../../../../dist/libs/core' or its corresponding type declarations.
114     _contentDensity: import("../../../../../../dist/libs/core").ToolbarSize;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
> fix: (Platform) add missing type definitions for ContentDensity

- apps/docs/src/app/core/api-files.ts
- apps/docs/src/app/core/component-docs/formatted-text/examples/base/formatted-text-example.component.html
- apps/docs/src/app/core/component-docs/formatted-text/examples/base/formatted-text-example.component.ts
- apps/docs/src/app/core/component-docs/formatted-text/examples/links/formatted-text-example.component.html
- apps/docs/src/app/core/component-docs/formatted-text/examples/links/formatted-text-example.component.ts
- apps/docs/src/app/core/component-docs/formatted-text/examples/script/formatted-text-example.component.html
- apps/docs/src/app/core/component-docs/formatted-text/examples/script/formatted-text-example.component.ts
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.component.html
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.component.ts
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.module.ts
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-header/formatted-text-header.component.html
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-header/formatted-text-header.component.ts
- apps/docs/src/app/core/core-documentation.routes.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- apps/docs/src/assets/README.md
- libs/core/src/index.ts
- libs/core/src/lib/formatted-text/formatted-text.component.spec.ts
- libs/core/src/lib/formatted-text/formatted-text.component.ts
- libs/core/src/lib/formatted-text/formatted-text.module.ts
- libs/core/src/lib/formatted-text/public_api.ts
- libs/core/src/lib/formatted-text/utils/html-sanitizer.ts
- libs/core/src/lib/fundamental-ngx-core.module.ts
[SAP#3395](https://github.com/SAP/fundamental-ngx/issues/3395)
Implement core formatted text component
> feat: (Core) introduce Formatted text component #3574

- apps/docs/src/app/core/api-files.ts
- apps/docs/src/app/core/component-docs/message-toast/examples/message-toast-content-example.component.ts
- apps/docs/src/app/core/component-docs/message-toast/examples/message-toast-example.component.html
- apps/docs/src/app/core/component-docs/message-toast/examples/message-toast-example.component.scss
- apps/docs/src/app/core/component-docs/message-toast/examples/message-toast-example.component.ts
- apps/docs/src/app/core/component-docs/message-toast/message-toast-docs.component.html
- apps/docs/src/app/core/component-docs/message-toast/message-toast-docs.component.ts
- apps/docs/src/app/core/component-docs/message-toast/message-toast-docs.module.ts
- apps/docs/src/app/core/component-docs/message-toast/message-toast-header/message-toast-header.component.html
- apps/docs/src/app/core/component-docs/message-toast/message-toast-header/message-toast-header.component.ts
- apps/docs/src/app/core/core-documentation.routes.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- libs/core/src/index.ts
- libs/core/src/lib/fundamental-ngx-core.module.ts
- libs/core/src/lib/message-toast/message-toast-service/message-toast.service.spec.ts
- libs/core/src/lib/message-toast/message-toast-service/message-toast.service.ts
- libs/core/src/lib/message-toast/message-toast-utils/message-toast-config.ts
- libs/core/src/lib/message-toast/message-toast-utils/message-toast-container.component.ts
- libs/core/src/lib/message-toast/message-toast-utils/message-toast-ref.ts
- libs/core/src/lib/message-toast/message-toast.component.scss
- libs/core/src/lib/message-toast/message-toast.component.spec.ts
- libs/core/src/lib/message-toast/message-toast.component.ts
- libs/core/src/lib/message-toast/message-toast.module.ts
- libs/core/src/lib/message-toast/public_api.ts
closes #3002
Introduces new Message Toast component. The component resembles a lot to the Alert component that we deprecated so I basically based its implementation on it. 
> feat: (Core) introduce new Message Toast component

- apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
- apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
- apps/docs/src/app/core/component-docs/wizard/examples/wizard-customizable-example.component.html
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.component.html
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.component.ts
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.module.ts
> docs: wizard branching docs

- apps/app-shell-app/src/app/app.component.ts
- libs/app-shell/src/lib/api/app-shell-provider.service.ts
- libs/app-shell/src/lib/api/error/default-error-handler.service.ts
- libs/app-shell/src/lib/api/error/error-formatter.ts
- libs/app-shell/src/lib/api/error/error-notifier.ts
- libs/app-shell/src/lib/api/events/message-bus.ts
- libs/app-shell/src/lib/api/events/messaging.config.ts
- libs/app-shell/src/lib/api/events/messaging.service.spec.ts
- libs/app-shell/src/lib/api/events/messaging.service.ts
- libs/app-shell/src/lib/api/events/topics.service.ts
- libs/app-shell/src/lib/api/extensions/component/plugin-configuration.model.ts
- libs/app-shell/src/lib/api/extensions/federation-utils.ts
- libs/app-shell/src/lib/api/extensions/lookup/lookup.service.ts
- libs/app-shell/src/lib/api/extensions/lookup/plugin-descriptor.model.ts
- libs/app-shell/src/lib/api/extensions/plugin-manager.service.ts
- libs/app-shell/src/lib/api/extensions/shell-bar.service.ts
- libs/app-shell/src/lib/api/theming/theme-manager.service.ts
- libs/app-shell/src/lib/app-shell.module.ts
- libs/app-shell/src/lib/components/plugin-launcher/plugin-launcher.component.ts
- libs/app-shell/src/lib/components/plugin-launcher/plugin-page-launcher.component.ts
- libs/core/src/lib/utils/services/rtl.service.ts
> fix: Plugin configuration changes

- apps/docs/src/app/core/component-docs/alert/alert-docs.component.html
> chore: Test Travis

- apps/docs/src/app/platform/api-files.ts
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-docs.module.ts
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-examples/platform-object-attribute-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-examples/platform-object-attribute-examples.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-examples/platform-object-attribute-examples.scss
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-examples/platform-object-attribute-link-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-examples/platform-object-attribute-link-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-examples/platform-object-attribute-truncate-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-header/platform-object-attribute-header.component.html
- apps/docs/src/app/platform/component-docs/platform-object-attribute/platform-object-attribute-header/platform-object-attribute-header.component.ts
- apps/docs/src/app/platform/documentation/platform-documentation.component.ts
- apps/docs/src/app/platform/platform-documentation.routes.ts
- libs/platform/src/index.ts
- libs/platform/src/lib/components/object-attribute/object-attribute.component.html
- libs/platform/src/lib/components/object-attribute/object-attribute.component.scss
- libs/platform/src/lib/components/object-attribute/object-attribute.component.spec.ts
- libs/platform/src/lib/components/object-attribute/object-attribute.component.ts
- libs/platform/src/lib/components/object-attribute/object-attribute.module.ts
- libs/platform/src/lib/components/object-attribute/public_api.ts
- libs/platform/src/lib/platform.module.ts
closes: #3530 
Object Attribute component for platform-specific component usage.
for example : Object list item uses object attribute.
> feat: (Platform) introduce new Object Attribute 

- libs/platform/src/lib/components/table/table.component.ts
- libs/platform/src/lib/domain/data-source.ts
Fix build. Changed `isKey` to `isKeyCode`. And fix for default table state (for `Upload Collection` component).
> fix: (Platform) keyboard handling in table

- apps/docs/src/app/core/component-docs/multi-input/examples/multi-input-filter-example/multi-input-filter-example.component.ts
> docs: (Core) remove console error on multi input custom filter

- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-compact-example/file-uploader-compact-example.component.html
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-compact-example/file-uploader-compact-example.component.ts
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-drag-disabled-example/file-uploader-drag-disabled-example.component.html
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-drag-disabled-example/file-uploader-drag-disabled-example.component.ts
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-example/file-uploader-example.component.html
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-example/file-uploader-example.component.ts
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-max-example/file-uploader-max-example.component.html
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-max-example/file-uploader-max-example.component.ts
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-min-example/file-uploader-min-example.component.html
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-min-example/file-uploader-min-example.component.ts
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-truncation-example/file-uploader-truncation-example.component.html
- apps/docs/src/app/core/component-docs/file-uploader/examples/file-uploader-truncation-example/file-uploader-truncation-example.component.ts
- apps/docs/src/app/core/component-docs/file-uploader/file-uploader-docs.component.html
There is added static binding for strings, added onPush strategy and changed documentation in one example, to match the rest.
> docs: (Core) improve file uploader docs

- apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html
- apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.ts
There is included:
- Fixed toolbar search method in TableToolbar
- Added handler for event on list inside ColumnSortingTable, to not trigger click on list item.
> docs: (Core) add Table documentation improvements

- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.ts
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.ts
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.ts
- apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs-header/fixed-card-layout-docs-header.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/fixed-card-layout-docs.module.ts
- libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
- libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.scss
- libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
- package-lock.json
- package.json
#3603  #3600  #3594  #3595 #3552 #3542 
This PR addresses fix for bugs raised against fixed card layout component.
Above mentioned issues has been fixed in this PR.
> fix: (Core) bug fixes for fixed card layout

- apps/docs/src/app/core/component-docs/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.html
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-allow-null-example/datetime-allow-null-example.component.ts
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-example/datetime-example.component.html
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-format-example/datetime-format-example.component.html
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-non-meridian-example/datetime-non-meridian-example.component.html
- apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-program-example/datetime-program-example.component.html
- apps/docs/src/app/core/component-docs/popover/examples/popover-dialog/popover-dialog-example.component.html
- apps/docs/src/app/core/component-docs/side-navigation/examples/side-navigation-programmatically-example/side-navigation-programmatically-example.component.html
- apps/docs/src/app/core/component-docs/split-button/examples/split-button-behaviors-example.component.html
- apps/docs/src/app/core/component-docs/split-button/examples/split-button-template-example.component.html
There are documentation improvements, like
- added some additional spacing on examples
- cleared a little bit split button documentation
- removed spacing on datetimepicker
> docs: (Core) add Documentation improvements

- libs/platform/src/lib/components/table/table-column/table-column.component.ts
#3676
When installing the latest @fundamental-ngx/platform rc build into an application, we see the following error when starting the application (`ng serve`):
```
ERROR in node_modules/@fundamental-ngx/platform/lib/components/table/table-column/table-column.component.d.ts:37:9 - error TS2380: 'get' and 'set' accessor must have the same type.
37     set align(align: ColumnAlign);
~~~~~
node_modules/@fundamental-ngx/platform/lib/components/table/table-column/table-column.component.d.ts:38:9 - error TS2380: 'get' and 'set' accessor must have the same type.
38     get align(): string;
```
Normally this error should be ignored because we have used the `// @ts-ignore ` comment in the source code:
https://github.com/SAP/fundamental-ngx/blob/2ffd49d3db4079a49709a68fcd37a77ee6dceabc/libs/platform/ …
> fix: (platform) Fixing Table component compile errors

- libs/core/src/lib/input-group/input-group.component.ts
> fix: Remove console error on shellbar's input group

- libs/core/src/lib/combobox/auto-complete.directive.spec.ts
- libs/core/src/lib/combobox/auto-complete.directive.ts
- libs/core/src/lib/combobox/combobox.component.html
- libs/core/src/lib/combobox/combobox.component.ts
- libs/core/src/lib/input-group/input-group.component.html
- libs/core/src/lib/input-group/input-group.component.ts
part of: https://github.com/SAP/fundamental-ngx/issues/3641
There is:
- fixed enter on autofill
- fixed strange bug with button, so now it's not focusable even after click
- fixed compact mode
- added space key support.
> fix: (Core) add Combobox improvements

- apps/docs/src/app/core/component-docs/formatted-text/examples/base/formatted-text-example.component.html
- apps/docs/src/app/core/component-docs/formatted-text/examples/base/formatted-text-example.component.ts
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-docs.component.html
- apps/docs/src/app/core/component-docs/formatted-text/formatted-text-header/formatted-text-header.component.html
> docs: (core) Change formatted text example

- libs/core/src/lib/wizard/wizard.component.scss
> fix: (core) Apply changes to wizard styling for IE11

- apps/docs/src/app/core/component-docs/list/examples/list-data-example/list-data-example.component.ts
Part of: #3685 
This PR:
- Fixes documentation example
> docs: Improve list with filtering example

- apps/docs/src/app/core/component-docs/layout-grid/examples/index.ts
- apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-examples.component.ts
- apps/docs/src/app/core/component-docs/layout-grid/examples/layout-grid-growing-example.component.html
- apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.component.html
- apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.component.ts
- apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.module.ts
- libs/core/src/lib/layout-grid/constants.ts
- libs/core/src/lib/layout-grid/directives/layout-grid-col.directive.ts
- libs/core/src/lib/layout-grid/layout-grid.component.scss
Closes: #3693
This PR:
- Introduces growing behavior into layout grid column
Local styles will be removed once `Fundamental Styles v0.13.0` will be adapted (#3684).
> fix: Add growing behavior to grid column

- apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-range-example.component.ts
- apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-range-disabled-example/date-picker-range-disabled-example.component.html
There is added width property to range datepicker examples
> docs: Change datepicker range width

- ci-scripts/sync-version.sh
- libs/core/ng-package.json
- libs/core/package.json
There is added hammerjs dependency on library + sync of version
> chore: (Core) add hammerjs dependency to the library

- libs/core/src/lib/popover/popover.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3685
There is added border-radius in all lists inside popover component
> fix: (Core) add border radius to List inside Popover

- apps/docs/src/app/core/component-docs/info-label/examples/info-label-default-example.component.html
- apps/docs/src/app/core/component-docs/info-label/examples/info-label-icon-numeric-example.component.html
- apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-example.component.html
- apps/docs/src/app/core/component-docs/info-label/examples/info-label-text-icon-example.component.html
- apps/docs/src/app/core/component-docs/object-status/examples/object-status-default-example.component.html
- apps/docs/src/app/core/component-docs/object-status/examples/object-status-inverted-example.component.html
- apps/docs/src/app/core/component-docs/object-status/examples/object-status-large-example.component.html
- apps/docs/src/app/core/component-docs/object-status/examples/object-status-text-example.component.html
- libs/core/src/lib/info-label/info-label.component.html
- libs/core/src/lib/info-label/info-label.component.ts
adding tooltip to the components
https://github.com/SAP/fundamental-ngx/issues/3697
Actual: None of the info label examples have a tooltip.
Expected: info label should have a tooltip on hover.
> fix:(Core) adding tooltip to the components for info label.

- apps/docs/src/app/platform/component-docs/platform-split-menu-button/platform-split-menu-button-examples/platform-split-button-icons-example.component.html
fixes: https://github.com/SAP/fundamental-ngx/issues/3708
> fix: (platform) platform split button icons example

- libs/platform/src/lib/components/form/public_api.ts
#3711 
exports base input class
> fix: (platform) export base input class

- libs/core/src/lib/carousel/carousel.component.html
- libs/core/src/lib/carousel/carousel.component.scss
- libs/core/src/lib/carousel/carousel.component.ts
- libs/core/src/lib/utils/services/carousel.service.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/3752
Additional fixes for: https://github.com/SAP/fundamental-ngx/issues/3853
Prevent native focus behavior on carousel buttons if buttons will be disabled.
Fixed issue with showing active slide and navigation with arrow buttons after change RTL.
> fix: (Core)  arrow keys in Core carousel component

- libs/core/src/lib/utils/functions/closest-element.ts
fixes https://github.com/SAP/fundamental-ngx/issues/3893
closestElement function works correct
> fix: (Core) fix closest element function

- libs/core/src/lib/popover/popover.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3786
> fix: (Core) add raw values for IE11 into popover arrow styles

- libs/core/src/lib/shellbar/product-menu/product-menu.component.scss
- libs/core/src/lib/shellbar/shellbar.component.scss
part of: https://github.com/SAP/fundamental-ngx/issues/3786
There are some styles added to shellbar.
For 0.13.0 fundamental-styles those issues are not existing.
> fix: (Core) add styles to shellbar elements

- apps/docs/src/app/core/component-docs/action-sheet/action-sheet-docs.component.ts
- apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.html
- apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-compact/action-sheet-compact-example.component.ts
- apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-cosy/action-sheet-cosy-example.component.html
- apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-cosy/action-sheet-cosy-example.component.ts
- apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.html
- apps/docs/src/app/core/component-docs/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.ts
part of: #3786
There are added some behaviour examples in action sheet.
> docs: (Core) add example behaviour to action sheet

- CODE_OF_CONDUCT.md
> chore: add code of conduct file

- libs/core/src/lib/tile/directives/tile.directives.ts
part of: #3786
There are added icons rendering on action tile buttons.
> fix: (Core) Add icons to Action Tile buttons

- libs/core/src/lib/multi-input/multi-input.component.html
- libs/core/src/lib/multi-input/multi-input.component.ts
- libs/core/src/lib/token/tokenizer.component.ts
part of: #3786
There is added `delete` and `backspace` buttons support for tokenizer following sapui5 behaviour.
Also I applied some code refactor and moved some functionalities to smaller methods
> fix: (Core) add delete button support in tokenizer

- libs/core/src/lib/toolbar/toolbar.component.scss
part of: #3786
There are fixes for styles in:
- menu button
- label
inside toolbar
> fix: (Core) Toolbar label and button additional styles

- CHANGELOG.md
- package-lock.json
- package.json
part of https://github.com/SAP/fundamental-ngx/issues/3924
This is PR that bump manually version to 0.24.1. So after merging we'll have 0.24.2-rc.0.
> chore: version 0.24.1 bump

- ci-scripts/hotfix-publish.sh
- scripts/hotfix-publish-release.sh
part of #3727
There are 2 minor fixes included into hotfix pipeline
> chore: fixes to hotfix pipeline

- ci-scripts/hotfix-publish.sh
part of #3727
Another typo, that made script fail
> chore: fix hotfix pipeline

- ci-scripts/hotfix-publish.sh
part of #3727
Package list added
> chore: Add packages array to hotfix pipeline

- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-example.component.html
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.html
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.scss
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-non-collapsible-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-responsive-padding-example.component.html
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-snap-scroll-example.component.html
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html
- apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page.module.ts
- libs/platform/src/lib/components/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
- libs/platform/src/lib/components/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
- libs/platform/src/lib/components/dynamic-page/dynamic-page.component.html
- libs/platform/src/lib/components/dynamic-page/dynamic-page.component.scss
- libs/platform/src/lib/components/dynamic-page/dynamic-page.component.spec.ts
- libs/platform/src/lib/components/dynamic-page/dynamic-page.component.ts
#3794 
This PR:
- Fixes issue of clicking on title area collapses the Dynamic Page header when header attribute `collapsible=false`
- Adds Non-Collapsible header example to documentation
- Adds Non-Collapsible suite of unit tests
> fix: (Platform) fix non-collapsible Dynamic Page header

- ci-scripts/hotfix-publish.sh
closes https://github.com/SAP/fundamental-ngx/issues/3727
There is added incrementing of version on master, when latest tag is used.
Pipieline tests for hotfixes passed. You can check logs from
- [non-latest test hotfix CI](https://travis-ci.com/github/SAP/fundamental-ngx/jobs/450715678)
- [latest test hotfix CI](https://travis-ci.com/github/SAP/fundamental-ngx/jobs/450730819)
Wiki:
https://github.com/SAP/fundamental-ngx/wiki/Releasing-Backward-Versions-Above-0.24
> chore: finalise hotfix pipeline

- libs/core/src/lib/button/button.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3922
In this PR there are:
- Removed old unused styles for button
- Added temporary centering styles for icons/text in button
> fix: (Core) add fix for Button text not being centered

- apps/docs/src/app/core/api-files.ts
- apps/docs/src/app/core/component-docs/flexible-column-layout/examples/default/flexible-column-layout-example.component.html
- apps/docs/src/app/core/component-docs/flexible-column-layout/examples/default/flexible-column-layout-example.component.scss
- apps/docs/src/app/core/component-docs/flexible-column-layout/examples/default/flexible-column-layout-example.component.ts
- apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs-header/flexible-column-layout-docs-header.component.html
- apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs-header/flexible-column-layout-docs-header.component.ts
- apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.html
- apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.component.ts
- apps/docs/src/app/core/component-docs/flexible-column-layout/flexible-column-layout-docs.module.ts
- apps/docs/src/app/core/core-documentation.routes.ts
- apps/docs/src/app/core/documentation/core-documentation.component.ts
- karma.conf.js
- libs/core/src/index.ts
- libs/core/src/lib/flexible-column-layout/constants.ts
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.ts
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.module.ts
- libs/core/src/lib/flexible-column-layout/public_api.ts
- libs/core/src/lib/fundamental-ngx-core.module.ts
- package-lock.json
- package.json
closes https://github.com/SAP/fundamental-ngx/issues/3874
Introduces new Flexible Column Layout component. 
Adds "karma-viewport" so I can test the layouts in desktop and tablet.
**Note 1**: Please visit the [Fiori3 Guidelines](https://experience.sap.com/fiori-design-web/flexible-column-layout/#possible-layouts) to check the behaviour of the component, its layouts and responsive design. Also check the description provided in the documentation. 
**Note 2**: the css code will be removed once Fundamental-styles is released. 
- [NA] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Change …
> feat: (Core) introduce Flexible Column Layout component

- libs/core/src/lib/popover/popover-position/popover-position.ts
- libs/core/src/lib/popover/popover.component.html
- libs/core/src/lib/popover/popover.component.scss
- libs/core/src/lib/popover/popover.component.spec.ts
- libs/core/src/lib/popover/popover.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/3922
There is changed the way how arrow is added to popover. Now it's inside container, so there won't be problems about floating arrow on control. Also simple popover and popover with different container finally support arrow.
> fix: (Core) attach arrow to container on Popover

- libs/platform/src/lib/components/menu/menu.component.html
- libs/platform/src/lib/components/menu/menu.component.scss
- libs/platform/src/lib/components/menu/menu.component.ts
https://github.com/SAP/fundamental-ngx/issues/3972
https://github.com/SAP/fundamental-ngx/issues/3981
https://github.com/SAP/fundamental-ngx/issues/3977
https://github.com/SAP/fundamental-ngx/issues/3980
MenuTriggerDirective works correct
> fix: (Platform) add cdk styles to menu component

- libs/core/src/lib/carousel/carousel.component.html
- libs/core/src/lib/carousel/carousel.component.scss
- libs/core/src/lib/carousel/carousel.component.ts
https://github.com/SAP/fundamental-ngx/issues/3987
Keyboard navigation works proper
> fix: (Core) add carousel focus

- libs/platform/src/lib/components/search-field/search-field.component.html
- libs/platform/src/lib/components/search-field/search-field.module.ts
https://github.com/SAP/fundamental-ngx/issues/3979
https://github.com/SAP/fundamental-ngx/issues/3773
Icons look correct
> fix: (Platform) fix icons of Search Field component

- libs/core/src/lib/product-switch/product-switch/product-switch.component.html
- libs/core/src/lib/product-switch/product-switch/product-switch.component.ts
and made the default button label text a more meaningful
Closes: https://github.com/SAP/fundamental-ngx/issues/3145
Closes: https://github.com/SAP/fundamental-ngx/issues/3146
- Added a `title` to the product switch button
- Default label text of product switch button changed to a more meaningful 
> fix: (Core) added title to Product Switch button

- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions-mobile.component.html
Closes: https://github.com/SAP/fundamental-ngx/issues/2636
> fix: (Core) added notification counter to action in Shellbar's collapsible menu

- apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.html
- libs/core/src/lib/feed-input/feed-input.component.scss
- libs/platform/src/lib/components/feed-input/feed-input.component.html
- libs/platform/src/lib/components/feed-input/feed-input.component.scss
Closes: https://github.com/SAP/fundamental-ngx/issues/4024
Closes: https://github.com/SAP/fundamental-ngx/issues/4026
> fix: (Platform|Core) Feed Input placeholder color and button alignment

- apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.html
- apps/docs/src/app/core/component-docs/wizard/examples/wizard-branching-example.component.ts
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.module.ts
- libs/core/src/lib/wizard/wizard-step/wizard-step.component.html
- libs/core/src/lib/wizard/wizard.component.ts
Part of defect hunting
Fixes issue where payment details would not change if user scrolled up and changed payment type
> docs: improve wizard branching docs

- apps/docs/src/app/platform/component-docs/platform-object-list-item/platform-object-list-item-examples/platform-object-list-item-border-less-example.component.ts
closes #3747 
Added a long title that shows truncation after 2 lines as requested by designers.
> fix: (Platform) Long title example added for object list item

- libs/core/src/lib/card/card.component.spec.ts
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts
- package-lock.json
- package.json
This PR:
- removes the focus from one of the tests
- installs version `6.1.4` of focus-trap to fix the failing tests
- fixes failing test for Badge in Card component due to the changes in [this PR](https://github.com/SAP/fundamental-ngx/pull/4068)
> test: (Core) remove test force

- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-base-data-provider.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-disabled-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-items-generator.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-readonly-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-turn-off-example.component.ts
- libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.html
- libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.ts
- libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.html
- libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.ts
- libs/platform/src/lib/components/upload-collection/domain/upload-collection-data-source.ts
- libs/platform/src/lib/components/upload-collection/models/upload-collection.models.ts
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection-data-provider-test.ts
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.scss
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.spec.ts
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
Fixes https://github.com/SAP/fundamental-ngx/issues/4032
Fixes https://github.com/SAP/fundamental-ngx/issues/4037
Fixes https://github.com/SAP/fundamental-ngx/issues/4038
Fixes https://github.com/SAP/fundamental-ngx/issues/4039
Fixes https://github.com/SAP/fundamental-ngx/issues/4043
Fixes https://github.com/SAP/fundamental-ngx/issues/4053
Fixes https://github.com/SAP/fundamental-ngx/issues/4033
Fixes https://github.com/SAP/fundamental-ngx/issues/4041
Addressed issues
> fix: (Platform) add bug fixes for Upload Collection

- libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts
- libs/core/src/lib/shellbar/shellbar.component.html
part of https://github.com/SAP/fundamental-ngx/issues/3922
Shellbar Component had invalid structure, so flex properties didn't work well (items weren't vertically centered).
Now class is attached to selector.
> fix: (Core) fix structure on Shellbar

- libs/core/src/lib/button/button.component.scss
fixes: https://github.com/SAP/fundamental-ngx/issues/4078
Added inherit style for font-weight on button text
> fix: (Core) Button emphasized text

- libs/platform/src/index.ts
- libs/platform/src/lib/components/upload-collection/public_api.ts
#4087 
Adds missing exports os components and modules.
- [ x] the commit message follows the guideline:
- [x ] tests for the changes that have been done
- [ x] all items on the PR Review Checklist are addressed :
- [x ] update `README.md`
- [x ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
- [ x] Documentation Examples
- [ x] Stackblitz works for all examples
> fix: (Platform) add missing exports

- apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-example.component.html
- apps/docs/src/app/core/component-docs/object-marker/examples/object-marker-text-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-clickable-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-marker/object-marker-example/object-marker-text-only-example.component.html
- libs/core/src/lib/object-marker/object-marker.component.ts
- libs/platform/src/lib/components/object-marker/object-marker.component.html
- libs/platform/src/lib/components/object-marker/object-marker.component.ts
fixing the Accessibility issue for the Object marker component
https://github.com/SAP/fundamental-ngx/issues/3558
https://github.com/SAP/fundamental-ngx/issues/3557
https://github.com/SAP/fundamental-ngx/issues/3821
fixed the tab index and Accessibility issues.
> fix: (Core) address accessibility issues for the Object marker component

- apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-with-selection-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-with-single-selection-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-list-item/platform-object-list-item-examples/platform-object-list-item-with-row-selection-and-navigation-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-object-list-item/platform-object-list-item-examples/platform-object-list-item-with-row-selection-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-with-selection-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-with-single-selection-example.component.ts
- libs/core/src/lib/list/directives/list-group-header.directive.ts
- libs/platform/src/lib/components/list/action-list-item/action-list-item.component.html
- libs/platform/src/lib/components/list/action-list-item/action-list-item.component.spec.ts
- libs/platform/src/lib/components/list/base-list-item.ts
- libs/platform/src/lib/components/list/display-list-item/display-list-item.component.html
- libs/platform/src/lib/components/list/display-list-item/display-list-item.component.spec.ts
- libs/platform/src/lib/components/list/list.component.html
- libs/platform/src/lib/components/list/list.component.scss
- libs/platform/src/lib/components/list/list.component.spec.ts
- libs/platform/src/lib/components/list/list.component.ts
- libs/platform/src/lib/components/list/object-list-item/object-list-item.component.html
- libs/platform/src/lib/components/list/object-list-item/object-list-item.component.spec.ts
- libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.html
Closes #3830 
Closes #3831 
Closes #3832 
Closes #3833 
Closes #3834 
Closes #3835 
Closes #3837 
Closes #3485 
Closes #3503 
This PR addresses few accessibility and screen reader issues for list and it items.
> fix: (Platform) list screen reader and accessibility issues.

- libs/core/src/lib/tabs/tab-list.component.html
- libs/core/src/lib/tabs/tab-list.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/3922
This PR brings temporary solution, semantic colors should be fixed in fundamental-styles. 
Issue connected with changes from PR: [#1865](https://github.com/SAP/fundamental-styles/pull/1865).
> fix: (Core) add fix for missing styling of selected Tabs

- apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
There are added links to older versions (0.22.0 - 0.24.1)
> docs: Add older documentation page versions to toolbar

- ci-scripts/publish.sh
Release was made with prerelease tag, it's leftover after publish script refactor and introducement of hotfix CI pipeline
> chore: remove prerelease tag form release scrpit

- libs/core/src/lib/carousel/carousel.component.html
- libs/core/src/lib/carousel/carousel.component.scss
- libs/core/src/lib/carousel/carousel.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/4035
Closes: https://github.com/SAP/fundamental-ngx/issues/4036
> fix: (Core) Carousel direction defects

- .ci-env/flags.sh
- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- CONTRIBUTING.md
- PLATFORM_README.md
- README.md
- apps/docs/src/app/core/component-docs/checkbox/checkbox-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/radio-group/platform-radio-group-header/platform-radio-group-header.component.html
- ci-scripts/hotfix-publish.sh
- ci-scripts/publish.sh
- ci-scripts/test-lint.sh
- libs/core/README.md
- libs/core/src/lib/dynamic-side-content/dynamic-side-content.component.scss
- libs/core/src/lib/feed-list-item/original-styles.css
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
- libs/core/src/lib/inline-help/inline-help.component.scss
- libs/core/src/lib/layout-grid/layout-grid.component.scss
- libs/core/src/lib/rating-indicator/components/rating-indicator.css
- libs/platform/README.md
- scripts/hotfix-publish-release.sh
- scripts/publish-release.sh
part of: https://github.com/SAP/fundamental-ngx/issues/3554
This PR contains changes of `master` word occurences in code/CI/docs.
> chore: Migrate master to main

- apps/docs/src/app/core/component-docs/dialog/dialog-docs.module.ts
PR testing CI on new default (main) branch
> test: CI main change

- apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.html
- apps/docs/src/app/core/component-docs/wizard/examples/wizard-ngfor-example.component.ts
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.component.html
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.component.ts
- apps/docs/src/app/core/component-docs/wizard/wizard-docs.module.ts
Adds an example for the wizard using ngFor
> docs: (core) add wizard ngFor example

- apps/docs/src/app/platform/component-docs/platform-display-list-item/platform-display-list-item-examples/platform-display-list-item-border-less-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-with-item-counter-example.component.html
- apps/docs/src/app/platform/component-docs/platform-object-list-item/platform-object-list-item-examples/platform-object-list-item-border-less-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-border-less-example.component.ts
- libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.html
- libs/platform/src/lib/components/list/standard-list-item/standard-list-item.component.scss
closes #4112 
closes #3487 
1).Added long text as requested to check accessibility with title.
2).Added unread in aria-label for screen readers.
> fix: (Platform) Add examples in list with long text for accessibility test

- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-docs.component.ts
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.scss
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu.module.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/3564
> docs: (Platform) added example Menu with icons

- libs/core/src/lib/toolbar/toolbar.component.scss
- libs/core/src/lib/toolbar/toolbar.component.ts
fixes: https://github.com/SAP/fundamental-ngx/issues/3996
There is added listener for query list change. Also styles are added for container, to keep max-height as 50vh
> fix: (Core) Toolbar refresh on item change, add height limits

- e2e/wdio/platform/pages/panel.po.ts
- e2e/wdio/platform/pages/switch.po.ts
- e2e/wdio/platform/tests/checkbox.e2e-spec.ts
- e2e/wdio/platform/tests/panel.e2e-spec.ts
- e2e/wdio/platform/tests/switch.e2e-spec.ts
- karma.conf-ci.js
- libs/core/src/lib/combobox/auto-complete.directive.spec.ts
- libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.spec.ts
- libs/platform/src/lib/components/approval-flow/approval-flow-node/approval-flow-node.component.spec.ts
- libs/platform/src/lib/components/form/auto-complete/auto-complete.directive.spec.ts
- libs/platform/src/lib/components/form/combobox/combobox/combobox.component.spec.ts
- libs/platform/src/lib/components/form/step-input/number/number-step-input.component.spec.ts
- libs/platform/src/lib/components/menu/menu.spec.ts
- libs/platform/src/lib/components/search-field/search-field.component.spec.ts
Skip failed tests for unblock CI
> test: (Core|Platform) temporary skip tests to unblock CI

- libs/core/src/lib/dialog/base/dialog-base.class.ts
- libs/core/src/lib/dialog/dialog-close-button/dialog-close-button.component.ts
- libs/core/src/lib/dialog/dialog.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/3119
Closes: https://github.com/SAP/fundamental-ngx/issues/3118
> fix: (Core) Dialog close button arial-label

- apps/docs/src/app/platform/component-docs/platform-link/platform-link-docs.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-standard-example.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-truncated-example.component.html
- libs/core/src/lib/link/link.component.ts
- libs/platform/src/lib/components/link/link.component.html
- libs/platform/src/lib/components/link/link.component.scss
- libs/platform/src/lib/components/link/link.component.ts
#3612 
1. Added missing subtle link in Core link and platform link.
2. fix for vertical alignment of platform link
> fix: (Platform) add subtle mode in core and platform. Fix vertical align in platform link.

- apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.html
- apps/docs/src/app/core/component-docs/input-group/examples/input-group-button-example.component.html
- apps/docs/src/app/core/component-docs/input-group/examples/input-group-form-example/input-group-form-example.component.html
- apps/docs/src/app/core/component-docs/input-group/examples/input-group-icon-example.component.html
- apps/docs/src/app/core/component-docs/input-group/examples/input-group-search-example/input-group-search-example.component.html
- apps/docs/src/app/core/component-docs/input-group/examples/input-group-text-compact-example.component.html
- apps/docs/src/app/core/component-docs/table/examples/table-custom-columns-example/table-custom-dialog.component.ts
- apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.html
- libs/core/src/lib/input-group/input-group.component.html
- libs/core/src/lib/input-group/input-group.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/4186
`aria-label` for a button with icon 
> fix: (Core) added aria-label to button with icon in Input Group

- e2e/wdio/platform/tests/checkbox.e2e-spec.ts
- libs/platform/src/lib/components/search-field/search-field.component.html
- libs/platform/src/lib/components/search-field/search-field.component.scss
- libs/platform/src/lib/components/search-field/search-field.component.spec.ts
- libs/platform/src/lib/components/search-field/search-field.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/4118
Closes: https://github.com/SAP/fundamental-ngx/issues/4030
Closes: https://github.com/SAP/fundamental-ngx/issues/4029
> fix: (Platform) title for buttons with icon in Search Field and trigger submit with empty value

- apps/docs/src/app/core/component-docs/popover/examples/popover-simple/popover-example.component.html
- apps/docs/src/app/core/component-docs/tile/examples/badge-tile-example.component.html
- apps/docs/src/app/core/component-docs/tile/examples/launch-tile-example.component.html
- apps/docs/src/app/core/component-docs/tile/examples/slide-tile-example.component.html
- apps/docs/src/app/core/component-docs/wizard/examples/wizard-mobile-example.component.html
- apps/docs/src/app/platform/component-docs/platform-link/platform-link-examples/platform-link-standard-example.component.html
- apps/docs/src/assets/NEW_COMPONENT.md
- libs/core/src/lib/tile/directives/tile.directives.spec.ts
- libs/platform/src/lib/components/list/object-list-item/object-list-item.component.spec.ts
- libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.spec.ts
- libs/platform/src/lib/components/thumbnail/thumbnail.component.spec.ts
https://github.com/SAP/fundamental-ngx/issues/4137
Image service changed
> fix: (Core|Platform) change image service

- apps/docs/src/app/core/component-docs/object-status/examples/object-status-text-example.component.html
https://github.com/SAP/fundamental-ngx/issues/4238
Fixed example
> docs: (Core) fix object status example

- apps/docs/src/app/core/component-docs/rating-indicator/rating-indicator-docs.component.html
https://github.com/SAP/fundamental-ngx/issues/4240
Fixed code example
> docs: (Core) fix rating indicator example

- .github/mergeable.yml
> chore: update mergeable.yaml

- libs/core/src/lib/toolbar/toolbar.component.html
- libs/core/src/lib/toolbar/toolbar.component.scss
- libs/core/src/lib/toolbar/toolbar.component.ts
fixes: #3700
In this PR there are:
- Method that Removes all last spacers elements.
- Some methods are added/refactored, but without any side results
> fix: (Core) Toolbar spacing elements, simplify code

- e2e/wdio/platform/tests/combobox.e2e-spec.ts
- e2e/wdio/platform/tests/input-group.e2e-spec.ts
- e2e/wdio/platform/tests/switch.e2e-spec.ts
- e2e/wdio/platform/tests/textarea.e2e-spec.ts
> test: fixed flaky tests

- e2e/wdio/core/fixtures/appData/card-content.ts
- e2e/wdio/core/pages/card.po.ts
- e2e/wdio/core/pages/core-base-component.po.ts
- e2e/wdio/core/tests/card.e2e-spec.ts
- e2e/wdio/helper/assertion-helper.ts
https://app.zenhub.com/workspaces/sap-ui-framework-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4165
Add e2e tests for card component (core)
> test: add card e2e tests

- libs/platform/src/lib/components/search-field/search-field.component.html
- libs/platform/src/lib/components/search-field/search-field.component.ts
#4232 #3355 
fixes for following
1. adds outline for search field
2. fixes category contentDensity in case of compact
> fix: (Platform) add outline in search field, fix category contentDensity for compact case

- libs/platform/src/lib/components/approval-flow/approval-flow.component.html
- libs/platform/src/lib/components/approval-flow/approval-flow.component.scss
- libs/platform/src/lib/components/approval-flow/approval-flow.component.ts
#4225 #4235 #4236 
This PR fixes issues linked above.
1. Detect window resize and show navigation button
2. fix focus outline for avatar and approval nodes
3. fix accessibility issue
1. #4235 issue for stackblitz is not handled in this PR, as that is a general issue for all components like Core calendar example for special days. This needs to be investigated and fixed in a different PR. 
Here stackblitz is appending .component in extra data class files provided. so examples not working on stackblitz.
> fix: (Platform) Add outline on nodes, detects window change for Approval flow component

- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-basic-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-cascade-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-scrolling-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-with-icons-example.component.html
- apps/docs/src/app/platform/component-docs/platform-menu/platform-menu-examples/platform-menu-x-position-example.component.html
- e2e/wdio/platform/fixtures/appData/menu-contents.ts
- e2e/wdio/platform/tests/menu.e2e-spec.ts
- libs/platform/src/lib/components/menu/menu-item.component.ts
- libs/platform/src/lib/components/menu/menu-trigger.directive.ts
#3650 #4244 #4119 
1. fix of visual for opened sub-menu item.
2. example fix for menu with icon
3. Tooltip for menu-item.
> fix: (Platform) add fix for selected state for opened sub-menu item in Menu component

- libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.ts
- libs/core/src/lib/grid-list/components/grid-list/grid-list.component.scss
- libs/core/src/lib/grid-list/components/grid-list/grid-list.component.ts
- libs/core/src/lib/grid-list/helpers/parse-layout-pattern.ts
Part of #4316
Fixed broken Grid Layout of Grid List on IE11
> fix: (Core) fix Grid List IE11 issues

- libs/core/src/lib/popover/popover.module.ts
For NON-IVY users there is still a need to add entry component.
> fix: (Core) Popover add missing entry component

- libs/core/src/lib/step-input/step-input.component.scss
- libs/core/src/lib/step-input/step-input.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/4316
Center of unit description next to step input
> fix: IE11 unit description center

- libs/core/src/lib/input-group/input-group.component.html
Closes: https://github.com/SAP/fundamental-ngx/issues/4230
> fix: (Core) InputGroup editing text in disabled state

- libs/core/src/lib/menu/menu-item/menu-item.component.ts
Small nullchecks added, to prevent from crashing whole app
> fix: (Core) add nullcheck to menu component

- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.html
- apps/docs/src/app/documentation/core-helpers/code-example/code-example.component.ts
Displays SCSS files in examples when scssFileCode property is provided
> docs: (Core) display scss files in code examples

- apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.html
- apps/docs/src/app/core/component-docs/card/examples/card-example.component.html
- apps/docs/src/app/core/component-docs/card/examples/card-kpi-example.component.html
- apps/docs/src/app/core/component-docs/card/examples/card-loader-example.component.html
- apps/docs/src/app/core/component-docs/card/examples/card-table-example.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/default/fixed-card-layout-examples.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/disabled-drag-drop/fixed-card-layout-disabled-drag.component.html
- apps/docs/src/app/core/component-docs/fixed-card-layout/examples/mobile/fixed-card-layout-mobile-examples.component.html
- libs/core/src/lib/card/card.component.html
- libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.html
#3545 #3546 #3547 #3560 #3811 #3813 #3817 #3818
1. Fixes tab issues
2. screen reader issues
> fix: (Core) fix Card accessibility issue

- libs/core/src/lib/tabs/tab-list.component.ts
- libs/core/src/lib/utils/functions/index.ts
- libs/core/src/lib/utils/functions/scroll.ts
- libs/core/src/lib/wizard/wizard.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/4316
> fix: (Core) add scrollTo IE11 alternative

- libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
There is added nullcheck for Optional RTL Service. 
> fix: (Core) add null check for Rtl service

- apps/docs/src/app/platform/component-docs/platform-thumbnail/platform-thumbnail-examples/platform-thumbnail-video-media-example.component.ts
- libs/platform/src/lib/components/thumbnail/thumbnail-image/thumbnail-image.component.html
- libs/platform/src/lib/components/thumbnail/thumbnail.component.html
- libs/platform/src/lib/components/thumbnail/thumbnail.component.ts
https://github.com/SAP/fundamental-ngx/issues/3825
https://github.com/SAP/fundamental-ngx/issues/3826
https://github.com/SAP/fundamental-ngx/issues/3828
This PR contains fixes for the accessibility bugs for thumbnail component. 
> fix: (Platform) Thumbnail accessibility bug fixes.

- e2e/wdio/platform/fixtures/testData/date-time-picker.ts
- e2e/wdio/platform/pages/date-time-picker.po.ts
- e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts
[4360](https://app.zenhub.com/workspaces/fundamental-library-5f32933d64202b0012e3572e/issues/sap/fundamental-ngx/4360)
Covered date time picker component for e2e tests
> test: (e2e) add date time picker component

- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-basic-example.component.html
- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-filters-example.component.html
- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-input-example.component.html
- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-mobile-example.component.html
- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-multi-input-example.component.html
- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-strategy-labels-example.component.html
- apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-token-example.component.html
- libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.html
- libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.scss
- libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.spec.ts
- libs/platform/src/lib/components/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
[4367](https://github.com/SAP/fundamental-ngx/issues/4367)
[4371](https://github.com/SAP/fundamental-ngx/issues/4371)
[4382](https://github.com/SAP/fundamental-ngx/issues/4382)
[4386](https://github.com/SAP/fundamental-ngx/issues/4386)
[4387](https://github.com/SAP/fundamental-ngx/issues/4387)
Fixed issues after defect hunting
> fix: (Platform) Value Help Dialog - updates, few minor issues in examples

- e2e/wdio/core/fixtures/appData/object-number-content.ts
- e2e/wdio/core/pages/object-number.po.ts
- e2e/wdio/core/tests/object-number.e2e-spec.ts
https://github.com/SAP/fundamental-ngx/issues/4377
Add e2e tests for the object number component
> test: (e2e) add object number e2e tests

- libs/core/src/lib/popover/popover-body/popover-body.component.html
- libs/core/src/lib/popover/popover-body/popover-body.component.ts
- libs/core/src/lib/popover/popover-service/popover.service.ts
part of https://github.com/SAP/fundamental-ngx/issues/4482
Previously there was some bugs with `cdkInitialFocus` directive. It has been removed and replaced by custom solution, that is using cdk tools
> fix: (Core) Popover Focus trap

- libs/platform/src/lib/components/form/combobox/combobox.module.ts
- libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss
https://github.com/SAP/fundamental-ngx/issues/4251
Fixed 2d part of issue `Combobox is missing styles`
Added `overlay-prebuilt.css` and `popover.css`
> fix: (Platform) fix combobox styles

- e2e/wdio/core/fixtures/appData/object-status-contents.ts
- e2e/wdio/core/pages/object-status.po.ts
- e2e/wdio/core/tests/object-number.e2e-spec.ts
- e2e/wdio/core/tests/object-status.e2e-spec.ts
- e2e/wdio/platform/tests/link.e2e-spec.ts
https://github.com/SAP/fundamental-ngx/issues/4489
add e2e tests for object status (core)
> test: (e2e) add object status e2e tests

- package-lock.json
- package.json
> chore: revert typedoc version

- apps/docs/src/app/core/component-docs/popover/popover-header/popover-header.component.html
there is added information, that sometimes is necessary to make popover work.
> docs: Add annotation about cdk-scrollable

- libs/core/src/lib/menu/menu.component.ts
> fix: (Core) Remove double mobile menu

- libs/platform/src/lib/components/form/radio-group/radio-group.component.html
- libs/platform/src/lib/components/form/radio-group/radio-group.component.ts
- libs/platform/src/lib/components/form/radio-group/radio/radio.component.html
- libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
- libs/platform/src/lib/components/form/radio-group/radio/radio.component.ts
#4282 
Previous implementation had following bugs:
1. for vertical radio group, radio button was getting clicked from any horizontal position
2. selection was getting removed without selection of other radio
3. removed code duplication
- N/A [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
> fix: (Platform) Removed dependency on click event for Radio button group

- apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-module-wrapper.ts
- libs/core/src/lib/fundamental-ngx-core.module.ts
- libs/platform/src/lib/platform.module.ts
There was some missing modules in Core global modules
> fix: (Core|Platform) Add missing modules in main global module

- libs/core/src/lib/panel/panel-title/panel-title.directive.ts
- libs/core/src/lib/panel/panel.component.scss
Closes: https://github.com/SAP/fundamental-ngx/issues/3494
Made a panel title accessible
> fix: (Core) readable Panel title by screen readers

- apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts
There is added version of NGX - `0.25.1` to documentation
> docs: Add missing version of ngx

- libs/core/src/lib/wizard/wizard.component.ts
fixes #4576 
Depends on https://github.com/SAP/fundamental-styles/pull/2118 for the full solution but this can be merged now regardless as it's still an improvement
> fix: (Core) put back step completed on last step

- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-base-data-provider.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-disabled-example.component.html
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-disabled-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-example.component.html
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-readonly-example.component.html
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-readonly-example.component.ts
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-turn-off-example.component.html
- apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-examples/platform-upload-collection-turn-off-example.component.ts
- libs/platform/src/lib/components/upload-collection/dialogs/move-to/move-to.component.ts
- libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.html
- libs/platform/src/lib/components/upload-collection/dialogs/new-folder/new-folder.component.ts
- libs/platform/src/lib/components/upload-collection/models/upload-collection-events.models.ts
- libs/platform/src/lib/components/upload-collection/models/upload-collection.models.ts
- libs/platform/src/lib/components/upload-collection/upload-collection.module.ts
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.scss
- libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/4039
closes https://github.com/SAP/fundamental-ngx/issues/4478
closes https://github.com/SAP/fundamental-ngx/issues/4477
closes https://github.com/SAP/fundamental-ngx/issues/4475
closes https://github.com/SAP/fundamental-ngx/issues/4472
closes https://github.com/SAP/fundamental-ngx/issues/4472
Fixed Upload Collection issues
> fix: (Platform) fix Upload Collection issues

- apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-reactive-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-state-example.component.html
- apps/docs/src/app/platform/component-docs/platform-forms/step-input/platform-step-input-examples/platform-number-step-input-template-example.component.html
- libs/platform/src/lib/components/form/step-input/base.step-input.ts
- libs/platform/src/lib/components/form/step-input/number/number-step-input.component.html
Closes https://github.com/sap/fundamental-ngx/issues/3489
Closes https://github.com/sap/fundamental-ngx/issues/3490
Closes https://github.com/sap/fundamental-ngx/issues/3488
Closes https://github.com/sap/fundamental-ngx/issues/3491
This PR contains fixes for the accessibility bugs for Step Input component.
> fix: (Core) Step Input accessibility

- apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.scss
- apps/docs/src/app/core/component-docs/select/examples/select-custom-trigger/select-custom-trigger.component.ts
- apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox.component.html
- libs/platform/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
- libs/platform/src/lib/components/form/input-group/input-group.component.spec.ts
- libs/platform/src/lib/components/form/radio-group/radio-group.component.spec.ts
- libs/platform/src/lib/components/form/step-input/number/number-step-input.component.spec.ts
- libs/platform/src/lib/components/form/text-area/text-area.component.spec.ts
closes #4596
Updating styles for custom example.
- [ n/a] update `README.md`
- [n/a ] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
> docs: (Core) Select custom item styles

- e2e/wdio/platform/pages/switch.po.ts
- e2e/wdio/platform/tests/switch.e2e-spec.ts
- libs/core/src/lib/switch/switch.component.html
- libs/core/src/lib/switch/switch.component.scss
- libs/core/src/lib/switch/switch.component.ts
https://github.com/sap/fundamental-ngx/issues/3495
https://github.com/sap/fundamental-ngx/issues/3496
This PR contains fixes for the accessibility bugs for Switch component.
> fix: (Core) Switch accessibility

- apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-dialog-example.component.html
- apps/docs/src/app/core/component-docs/quick-view/examples/quick-view-popover-example.component.html
Closes: https://github.com/SAP/fundamental-styles/pull/2127
Centered Quick View title
> docs: (Core) Quick View title alignment

- libs/core/src/lib/utils/services/themes.service.ts
Adds description for each theme in the Theme switcher service
> fix: (Core) add description to the Themes in Themes service
