SAP/fundamental-ngx

libs/core/src/lib/bar/button-bar/button-bar.component.ts
Closes SAP/fundamental-ngx#5457
Users expect that if disabled state set on fd-button-bar, any clicks wouldn't work on element, but it didn't work because disabled attribute works only for specific html elements. So I set real disabled state for fd-button-bar element if disabled is true.
=> fix(core): set real disabled state for button-bar element

apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-disable-function-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-reactive-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-template-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-header/platform-datetime-picker-header.component.html, libs/platform/src/lib/components/form/datetime-picker/datetime-picker.component.spec.ts, libs/platform/src/lib/components/form/datetime-picker/datetime-picker.component.ts
Closes SAP/fundamental-ngx#4442 #3973
This PR adjusts the width of DatetimePicker when used along with Platform Forms such that it takes up 100% of its container space and looks consistent with other form controls.
Before:
After:
=> fix(platform): adjust Datetime Picker width to container width when used with Platform Forms

apps/docs/src/app/core/component-docs/dialog/examples/component-based/component-based-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/dialog-stacked-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/second-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.ts, libs/core/src/lib/dialog/dialog.component.ts
Closes : https://github.com/SAP/fundamental-ngx/issues/3117
fixes for the adding focus to the dialog popup when dialog is opened and added ariaLabelledby to the dialog header for screen reader
- [NA] tests for the changes that have been done
=> fix(core): add ariaLabelledby to the dialog header for screen reader

LICENSE.txt
In order to be able to identify the main license of all managed repositories centrally, the SAP Open Source Program Office (OSPO) asks all teams to have an identifiable license in their repositories. For some reason (probably formatting - we usually have these issues with licenses copied via the [REUSE tool](https://reuse.software)) the [license in this repository is not detected properly by GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#detecting-a-license). This PR includes text from a [GitHub license template](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) that should facilitate the automated license detection. …
=> chore: Use GitHub license template

e2e/wdio/platform/pages/combobox.po.ts, e2e/wdio/platform/pages/textarea.po.ts, libs/platform/src/lib/components/form/base.input.ts, libs/platform/src/lib/components/form/form-group/form-field/form-field.component.html
Closes SAP/fundamental-ngx#3440
Inline help is being used with `fd-form-label` and its contents are passed as attributes. So the normal way of associating through `for` and `id` does not read out the inline help content. This PR replaces `for` and `id` with `aria-labelledby` at the base-input class to fix this issue.
=> fix(platform): associate both label and inline help with Textarea component for a11y

apps/docs/src/app/core/component-docs/notification/examples/notification-group/notification-group-example.component.html
Closes #5648
Reduce the size by removing the unwanted space for notification group example of notification component.
=> docs(core): reduce the size of the notification group example of notification component.

apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-docs.component.html, libs/platform/src/lib/components/form/select/commons/base-select.ts, libs/platform/src/lib/components/form/select/select/select.component.html, libs/platform/src/lib/components/form/select/select/select.component.ts
Closes #5650 
When user changes the content density option in documentation. Detect the changed option and display accordingly when no contentDensity value is set for select component.
=> fix(platform): fix content density in select component with no predefined value

apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-allow-null-example.component.ts, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-allow-null-example/datetime-allow-null-example.component.ts, libs/core/src/lib/calendar/calendar-header/calendar-header.component.ts, libs/core/src/lib/calendar/calendar.component.ts, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/core/src/lib/datetime/fd-date.spec.ts, libs/core/src/lib/datetime/fd-date.ts, libs/core/src/lib/datetime/fd-date.utils.ts, libs/core/src/lib/datetime/fd-datetime-adapter.spec.ts, libs/core/src/lib/datetime/fd-datetime-adapter.ts, libs/core/src/lib/time/time.component.ts, libs/core/src/lib/utils/consts/error-messages.ts
Closes SAP/fundamental-ngx#5059
This request fixed this issues(read point 3) [stackblitz](https://stackblitz.com/edit/fundamental-ngx-date-time-fields?embed=1&file=src/app/datetime-program-example.component.ts).
What was done:
- Implemented standard behavior(as it works for Date calss of native JS or moment.js) for invalid date. Now we don't get error exception if we pass invalid date during creating instance of FdDate class. If FdDate instance contains invalid date, we get NaN value for all number formats and string  message "Invalid Date" for string format.
- Adapted date's components for new behavior 
- Fixed several bugs of date's components.
**BREAKING CHANGES:**
FdDate class invalid date handling:
- Before: 
You set invalid date params -> You are getting throwing error.
- After:
You …
=> fix(core): handle invalid date inside date's components

libs/platform/src/lib/components/form/form-group/form-group.component.html
Closes #5130 
position form fields on top instead of the middle
Before:
After:
=> fix(platform): position the form fields on top

apps/docs/src/app/core/component-docs/message-strip/message-strip-docs.component.html, apps/docs/src/app/core/component-docs/message-strip/message-strip-docs.component.ts, apps/docs/src/app/documentation/core-helpers/playground/playground.component.html, apps/docs/src/app/documentation/core-helpers/playground/playground.component.ts, apps/docs/src/app/schema/containers/schema-group/schema-group.component.html, apps/docs/src/app/schema/containers/schema-group/schema-group.component.ts, apps/docs/src/app/schema/containers/schema/schema.component.html, apps/docs/src/app/schema/containers/schema/schema.component.ts
Closes #5795 
Add reset button for playground component and reset components inside playground when button being pressed.
- n/a tests for the changes that have been done
- n/a Run npm run build-pack-library and test in external application
=> fix(docs): add resettable flag for playground and reset message strip

apps/docs/src/app/core/component-docs/bar/examples/bar-default-example.component.html, apps/docs/src/app/core/component-docs/bar/examples/bar-header-example.component.html, apps/docs/src/app/core/component-docs/bar/examples/bar-page-example.component.html, apps/docs/src/app/core/component-docs/bar/examples/bar-page-responsive-example.component.html, libs/core/src/lib/bar/button-bar/button-bar.component.ts
Closes https://github.com/SAP/fundamental-ngx/issues/5764
This changes contains to fix the screen reader to read the label for the non textual UI components like navigation icon and 
image.
=> fix(core): fix a11y issues for bar component

libs/platform/src/lib/components/form/checkbox-group/checkbox-group.module.ts
Closes https://github.com/SAP/fundamental-ngx/issues/3999
This PR optimises the import for checkbox-group.
instead of importing entire core/formModule, importing only required `formgroup`.
=> fix(platform): correct imports for checkbox group module

libs/core/src/lib/slider/slider.component.scss, libs/platform/src/lib/components/form/combobox/combobox/combobox.component.scss, libs/platform/src/lib/components/form/select/select/select.component.scss
Closes #5657 
Removed duplicated css imports from select, combobox and slider components.
=> fix(core): remove duplicated css imports

apps/docs/src/app/core/component-docs/dialog/examples/component-based/component-based-dialog-example.component.ts, apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts, libs/core/src/lib/dialog/base/dialog-base.class.ts, libs/core/src/lib/dialog/dialog-service/dialog.service.ts, libs/core/src/lib/dialog/dialog.component.ts, libs/core/src/lib/message-box/message-box.component.ts
Closes #5792 
Added scoped DialogService to the example container component in order for DialogService to have the same RtlService as the component.
=> fix(docs): fix documentation rtl for dialog

apps/docs/src/app/core/component-docs/layout-grid/layout-grid-docs.component.html, apps/docs/src/app/core/component-docs/notification/notification-docs.component.html, apps/docs/src/app/core/component-docs/title/title-docs.component.html, apps/docs/src/app/platform/component-docs/platform-approval-flow/platform-approval-flow-docs.component.html, apps/docs/src/app/platform/component-docs/platform-upload-collection/platform-upload-collection-docs.component.html
Closes #5649 
Added correct heading components instead of h2
=> docs(docs): apply correct headings

libs/core/src/lib/radio/radio-button/radio-button.component.html, libs/platform/src/lib/components/form/radio-group/radio-group.component.html, libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
Closes https://github.com/SAP/fundamental-ngx/issues/5656
currently tab order is not working on radio button examples. Tab does not take you from one example to another, but it skips.
Same behaviour is in Platform Radio and Platform radio-group. fix is provided in core radio by replacing [name]="name" to [attr.name]="name".
- [NA] Documentation Examples
=> fix(core,platform): replace name with attr.name for taborder to work correctly

apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-format-example.component.ts
Closes #5750 
This is a known issue with the Intl.DateTimeFormat class. This example uses the option `hour12:false` :
[This option returns strange results at times as seen in this stackoverflow post.](https://stackoverflow.com/questions/65604554/intl-datetimeformat-returns-an-hour-over-24)
This PR uses the suggested solution of using the `hourCycle` option instead to fix this issue. 
=> docs(core): fix displayFormat option for Time Picker example

apps/docs/src/app/core/component-docs/textarea/examples/textarea-example.component.html, apps/docs/src/app/core/component-docs/textarea/examples/textarea-form-group-example.component.html, apps/docs/src/app/core/component-docs/textarea/examples/textarea-inline-help-example.component.html, apps/docs/src/app/core/component-docs/textarea/examples/textarea-state-example.component.html
Closes https://github.com/SAP/fundamental-ngx/issues/5899,
Closes https://github.com/SAP/fundamental-ngx/issues/5907
This PR change contains applying the required mark for label in compact example for text area component.
=> docs(core): apply required mark for label  and remove inline help class in compact example for text area component 

apps/docs/src/app/platform/component-docs/platform-button/platform-button-examples/platform-button-sizes-example.component.html
Closes #5752 
When we change the content density from the central select to compact then the normal button should not become compact. 
The normal example has explicit contentDensity input set to cozy in order to be valid as an example.
=> docs(platform): update cozy button example in sizes section

libs/platform/ng-package.json, libs/platform/package.json, libs/platform/schematics/utils/translation-utils.ts
Closes #5941 
On creating a new Ang12 project, the `angular.json` configuration does not add `options` field to the `serve` configuration like in previous versions. Also, there is probably stricter checking of how modules/external libraries are used due to which `xml2js` library was not being found. This PR:
- targets the `extract-i18n` config of angular.json instead which shows the correct `browserTarget` path as before
- adds `xml2js` as platform lib dependency to overcome `module not found` errors on Angular12.
The changes have been verified against both Ang12 and Ang10 projects and work fine for both `ng-add` and `ng-update`.
To verify, 
- take this branch and run `npm run build-pack-library`. Copy the path to the `fundamental-ngx-platform-0.31.0-rc.xyz.tgz`  file from the platform …
=> fix(platform): fix Platform ng-add schematics failing in Angular12 apps

apps/docs/src/app/core/component-docs/card/examples/bar-chart-list-card/bar-chart-list-card-example.component.html
Closes: https://github.com/SAP/fundamental-ngx/issues/5776
bar chart list using directive instead of css class and focus list
=> docs(core): bar chart list using directive instead of css class

libs/core/src/lib/input-group/input-group.component.ts
Closes #6003 
This PR removes `private` modifier from the method `_getAriaLabelledbyIdsForInput`.
=> fix(core): fix access modifier for method in Input Group

apps/docs/src/app/core/component-docs/illustrated-message/illustrated-message-docs.component.ts, apps/docs/src/app/documentation/core-helpers/code-example/example-file.ts, apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz-dependencies.ts, apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
Closes #5178 #6008
Added ability to include assets into stackblitz project.
NOTE: assets are rendering after stackblitz project has been forked. I might be a problem on stackblitz side itself and not on ours.
=> fix(docs): add ability to include assets to examples

libs/platform/src/lib/components/form/multi-input/multi-input.component.html
Closes https://github.com/SAP/fundamental-ngx/issues/6005
Currently platform multi-input value help list items are created with anchor link. So it displays underscore below the text.
It is not needed, as fiori does not mention it to be navigable list item.
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2059233657
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2059233657
=> fix(platform): remove anchor from list item for multi-input value help

libs/platform/src/lib/components/button/button.component.html
Closes #5877
When platform button is used in any user angular application the button should have a content density as cozy by default.
Before:
After:
=> fix(platform): display default content density  as core for components

libs/platform/src/lib/components/form/step-input/step-input.scss
Part of SAP/fundamental-ngx#5025
Remove hardcoded styles for step-input as part of style cleanup
=> fix(platform): remove hardcoded styles for step-input as part of style cleanup

apps/docs/src/app/core/component-docs/radio/examples/radio-example.component.html, libs/core/src/lib/radio/radio-button/radio-button.component.html, libs/platform/src/lib/components/form/radio-group/radio/radio.component.spec.ts
Closes https://github.com/SAP/fundamental-ngx/issues/6055
Closes https://github.com/SAP/fundamental-ngx/issues/5656
Because of change made in PR https://github.com/SAP/fundamental-ngx/pull/5895, selection behaviour of radio button became buggy. It is changing the selection is another radio group as well.
This issue is happening in **Core radio button** as well.
Reverting the change, so it can be fixed.
Opening original issue https://github.com/SAP/fundamental-ngx/issues/5656 for tab order behaviour.
Before:
After:
=> fix(core,platform): fix weird selection behaviour because of using attr.name in radio button

apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.html, apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/auto-label/auto-label-dialog-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/auto-label/auto-label-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/index.ts, libs/core/src/lib/dialog/base/dialog-base.class.ts, libs/core/src/lib/dialog/base/dialog-base.service.ts, libs/core/src/lib/dialog/base/dialog-config-base.class.ts, libs/core/src/lib/dialog/base/dialog-footer-base.class.ts, libs/core/src/lib/dialog/base/dialog-header-base.class.ts, libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts, libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts, libs/core/src/lib/dialog/dialog-default/dialog-default.component.ts, libs/core/src/lib/dialog/dialog-footer/dialog-footer.component.ts, libs/core/src/lib/dialog/dialog-header/dialog-header.component.ts, libs/core/src/lib/dialog/dialog.component.html, libs/core/src/lib/dialog/dialog.component.ts, libs/core/src/lib/dialog/dialog.module.ts, libs/core/src/lib/dialog/directives/dialog-title.directive.ts
Closes #6052.
Dialog auto labeling feature using the directive.
=> feat(core): dialog auto labeling

apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-form-example.component.html, apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-form-example.component.ts, e2e/wdio/core/tests/time-picker.e2e-spec.ts, libs/core/src/lib/time-picker/time-picker.component.html, libs/core/src/lib/time-picker/time-picker.component.spec.ts, libs/core/src/lib/time-picker/time-picker.component.ts, libs/platform/src/lib/components/form/time-picker/time-picker.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/5126
This PR brings fix not to fire extra FormControl.onChange event if the input element wasn't changed.
Also, this brings some code formatting according to the code styles rules
=> fix(core): fix extra onChange event in the TimePicker component

libs/core/src/lib/dialog/dialog-service/dialog.service.ts
Closes #6106
The root of the problem was that the injector was redefined to the subsequent dialog, and the connection with the parent DialogService service was lost.
=> fix(core): added existed instance of dialog to injector of component

libs/platform/src/lib/components/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.ts
Closes #6120 
Changed logic of gathering summary section items to reflect original order of the form groups in wizard generator steps.
=> fix(platform): correct order for summary items

apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-examples/platform-field-layout/platform-field-column-change-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-examples/platform-field-layout/platform-field-column-change-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-examples/platform-field-layout/platform-field-isinline-change-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-examples/platform-field-layout/platform-field-isinline-change-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-header/platform-form-container-header.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.ts, libs/platform/src/lib/components/form/checkbox-group/checkbox-group.component.ts, libs/platform/src/lib/components/form/collection-base.input.ts, libs/platform/src/lib/components/form/form-generator/dynamic-form-generator-checkbox/dynamic-form-generator-checkbox.component.html, libs/platform/src/lib/components/form/form-generator/dynamic-form-generator-radio/dynamic-form-generator-radio.component.html, libs/platform/src/lib/components/form/form-generator/form-generator/form-generator.component.html, libs/platform/src/lib/components/form/form-generator/interfaces/dynamic-form-item.ts, libs/platform/src/lib/components/form/form-group/form-field/form-field.component.ts, libs/platform/src/lib/components/form/form-group/form-group.component.ts, libs/platform/src/lib/components/form/form-options.ts, libs/platform/src/lib/components/form/inline-layout-collection-base.input.ts, libs/platform/src/lib/components/form/public_api.ts, libs/platform/src/lib/components/form/radio-group/radio-group.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/5900
1. This PR introduces property `columnLayout` in `fdp-form-field` for placing a field in certain column whenever layout changes. It takes an object as input in the form of `{ XL: 1, L: 2, M: 1, S: 1 }`.
2. It also introduces property `inlineLayout` for collection-based-input fields, so this field layout can change from `inline` to `vertical` or vice-versa based on layout.
created example inside `platform/form-container` and `platform/form-generator`.
1. Change of column number for a field
2. Change of isInline value for a field
Form generator:
1. Form Generator with form field column layout and inline layout
https://github.com/SAP/fundamental-ngx/wiki/PR-Review-Checkli …
=> feat(platform): introduce feature to change column and inline value based on form container layout

libs/core/src/lib/file-uploader/file-uploader.component.html, libs/core/src/lib/file-uploader/file-uploader.component.scss
Part of #5025
PR change contains remove style from ngx to reuse the style from fundamental-style lib for file uploader component.
=> fix(core): remove style from ngx to reuse the style from fundamental-style lib for file uploader component

apps/docs/src/app/core/component-docs/radio/examples/radio-example.component.html, apps/docs/src/app/core/component-docs/rating-indicator/examples/ri-dynamic-example.component.html
Closes [#5940](https://github.com/SAP/fundamental-ngx/issues/5940)
Closes [#5942](https://github.com/SAP/fundamental-ngx/issues/5942)
Limit user's possibility to set value less then 1 using arrows
Correct name for disabled radio-buttons group.
=> docs(core): update radio button and rating indicator examples (add limitation and correct name)

apps/docs/src/app/core/api-files.ts, apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.html, apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.ts, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-basic-example.component.html, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-extended-example.component.html, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-extended-example.component.ts, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-label-example.component.html, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-label-example.component.ts, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-size-example.component.html, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-wrapper-example.component.html, apps/docs/src/app/core/component-docs/busy-indicator/examples/index.ts, libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.spec.ts, libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts, libs/core/src/lib/busy-indicator/busy-indicator.component.html, libs/core/src/lib/busy-indicator/busy-indicator.component.scss, libs/core/src/lib/busy-indicator/busy-indicator.component.ts, libs/core/src/lib/busy-indicator/busy-indicator.module.ts, libs/core/src/lib/busy-indicator/public_api.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/3111, https://github.com/SAP/fundamental-ngx/issues/3112
adding extened example and adding extended label to the component
- [] Run npm run build-pack-library and test in external application
=> fix(core): extended example, label for the busy indicator

apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.html, apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-example/feed-input-example.component.html, apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-grow-example/feed-input-grow-example.component.html, apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-no-avatar-example/feed-input-no-avatar-example.component.html, apps/docs/src/app/core/component-docs/feed-input/examples/feed-input-placeholder-example/feed-input-placeholder-example.component.html
Closes #6216 
It seems that in textarea, when `aria-label` is present, `placeholder` is not given significance and won't be read out at all([w3 link describing the computation for element accessible name](https://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-computation), `placeholder` comes at fourth place in priority). 
To get the screen reader to announce `placeholder`, we have removed `aria-label`. 
As suggested in 6216 issue, we have also removed `example` word from the feed-input element's `aria-label`. …
=> docs(core): fix placeholder not being read by JAWS for Feed Input

apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-observable-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-programatic-submit.component.ts
Closes #6276
Corrected validation error message for password field in form generator examples
=> fix(docs): correct validation hint

apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-custom-error-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-observable-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-programatic-submit.component.ts
Closes #6274
Added missing required validators for documentation examples.
=> fix(docs): add missing required validators

libs/platform/src/lib/components/table/table.module.ts
Closes https://github.wdf.sap.corp/Ariba-Sourcing/minerva/pull/8737
In the `TableModule` was used relative import which refers to the barrel files, it breaks customer's app when using View Engine (not Ivy).
1 Create an app using Angular 10
2 Import `FundamentalNgxPlatformModule`
3 Try to run `ng xi18n`
=> fix(platform): table imports fix

apps/docs/src/app/core/component-docs/checkbox/examples/checkbox-default-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-error-handling.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-multiselect-checkbox.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-tristate-checkbox.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-example.component.html, libs/core/src/lib/form/form-label/form-label.component.html, libs/platform/src/lib/components/form/base.input.ts, libs/platform/src/lib/components/form/form-group/form-field/form-field.component.html
Closes https://github.com/SAP/fundamental-ngx/issues/6073
Closes https://github.com/SAP/fundamental-ngx/issues/6135
Closes https://github.com/SAP/fundamental-ngx/issues/6213
Fixing checkbox a11y.
1. having visual label for required checkbox
2. reading value is required
3. fixing multiple time reading of "hint"
=> fix(core,platform): checkbox a11y issues fix

libs/platform/src/lib/components/upload-collection/models/upload-collection.models.ts, libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.html, libs/platform/src/lib/components/upload-collection/upload-collection/upload-collection.component.ts
Closes SAP/fundamental-ngx#4474
Added `sameFilenameAllowed` input that allows using the same name for a file when editing the file name.
'Same name' refers to an already existing file name in the list.
Default value: `false`
**It the same closed PR** https://github.com/SAP/fundamental-ngx/pull/5709
=> fix(platform): add sameFilenameAllowed

libs/platform/src/lib/components/form/form-generator/dynamic-form-control-field.directive.ts
Closes https://github.com/SAP/fundamental-ngx/issues/6283
Fixed dynamic-form-control-field directive that fixes stackblitz examples like Wizard generator and Form generator
What's done: re-sorting the inputs
=> fix(platform): fix dynamic-form-control-field directive that fixes stackblitz examples

e2e/wdio/platform/pages/date-time-picker.po.ts
Closes none
fixes broken selector for datetime picker platform e2e test
=> test(e2e): update datetime picker selector

libs/core/src/lib/pagination/pagination.component.html, libs/core/src/lib/pagination/pagination.component.ts
Closes #6096 
This PR modifies the `aria-current` attribute value and uses LiveAnnouncer from CDK to announce the currently selected page.
Unfortunately, `aria-current` does not announce `"current page"` each time the page is changed; it seems to only announce the actively(or first time) selected `aria-current` element and doesn’t announce on page switch when handled dynamically. For this, there were two ways to handle this:
1. To add `current page` to the element’s aria-label attribute itself. This works okay for the pages themselves, but when we try to associate the previous and next buttons to also announce the page navigated to, it announces something like `Previous, Page 4, current page; button`; including the page’s aria-label before completely describing the previous button.
2. To …
=> fix(core): fix Pagination component a11y to announce currently chosen page

apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.html, apps/docs/src/app/core/component-docs/dialog/dialog-docs.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/auto-label/auto-label-dialog-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/component-based/component-based-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/component-based/dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-complex/dialog-complex-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-configuration/dialog-configuration-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-inner-popover/dialog-inner-popover.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-mobile/dialog-mobile-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-object-example/dialog-object-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/dialog-position/dialog-position-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/dialog-state/dialog-state-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/stacked-dialogs/second-dialog-example.component.ts, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.html, apps/docs/src/app/core/component-docs/dialog/examples/template-based/template-based-dialog-example.component.ts, e2e/wdio/core/tests/illustrated-message.e2e-spec.ts, e2e/wdio/platform/pages/approval-flow.po.ts, libs/core/src/lib/bar/button-bar/button-bar.component.ts, libs/core/src/lib/dialog/base/dialog-config-base.class.ts, libs/core/src/lib/dialog/base/dialog-content-base.class.ts, libs/core/src/lib/dialog/dialog-close-button/dialog-close-button.component.ts, libs/core/src/lib/dialog/dialog-default/dialog-default.component.html, libs/core/src/lib/dialog/dialog-header/dialog-header.component.html, libs/core/src/lib/dialog/dialog-header/dialog-header.component.spec.ts, libs/core/src/lib/dialog/dialog.component.html, libs/core/src/lib/dialog/dialog.component.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/6100
fixing the accessability test cases
=> fix(core): fixing the accessibility for the dialog component

libs/core/src/lib/bar/button-bar/button-bar.component.ts, libs/platform/src/lib/menu-button/menu-button.component.html, libs/platform/src/lib/upload-collection/dialogs/new-folder/new-folder.component.html, libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html, libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.ts
Closes #4670 
This PR fixes the below issues: 
- Issue 1: no longer reproducible
- Issue 2: added `title` attribute to the `More` action button
- Issue 3: already fixed by Pagination component
- Issue 4: added `fd-dialog-title` directive and also `aria-labelledby` to the `fd-button-bar`'s `Cancel` button which receives initial focus
- Issue 5: added `aria-labelledby` to the search input group element to read out the table header content.
- Issue 6: `title` attribute to `More` button fixes this
- Issue 7: added `aria-labelledby` to the `menu-button` element
- Issue 8: keyboard support is already present by pressing `Enter` or `Space`
- Issue 9: no longer reproducible, for `disabled` example, the `More` button is also disabled as expected so won't be accessed. …
=> fix(core,platform): fix a11y for Upload Collection

apps/docs/src/app/core/component-docs/tile/examples/action-tile-example.component.html
Closes: https://github.com/SAP/fundamental-ngx/issues/6186
adding tooltip to the button for tile component
=> docs(core): adding tooltip to the button for tile component

libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.ts, libs/core/src/lib/combobox/combobox.component.ts
Closes https://github.com/SAP/fundamental-ngx/issues/6395
Fixed RTL mode for mobile
Added ability to close dialog on pressing Escape key
=> fix(core): combobox, fix rtl mode for mobile

apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-no-colons-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-no-colons-example.component.ts, libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html, libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts
Closes #6526
Previously form generator rendered label value "as is". Now by default it will add colon at the end of the text. This can be changed with GuiOptions property per the form generator control. …
=> feat(platform): add automatic colons for the labels

libs/core/src/lib/timeline/components/timeline-node-footer/timeline-node-footer.component.ts
Add a temporary styling for adding space between buttons inside `fd-timeline-node-footer` container. 
=> fix: add temporary style fix for action buttons in Timeline

libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.html, libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.html
After some changes in wizard generator, Stackblitz examples stopped to work and throw an error, which is fixed with this PR
2. …
=> fix(platform): remove broken properties from wizard generator

libs/platform/src/lib/approval-flow/approval-flow.module.ts, libs/platform/src/lib/approval-flow/tsconfig.json
It seems ComboboxModule, ToolbarModule was imported but never used in Approval flow
=> fix(platform): remove unused module imports in ApprovalFlow component

libs/platform/src/lib/form/text-area/text-area.component.ts
Closes #6525 
Previously backspace/delete keypress caused of the removal of the whole textarea value if no maxlength property was provided. Now if it's not provided, the behaviour of the keypress is native.  …
=> fix(platform): correct delete behaviour for textarea

libs/core/src/lib/grid-list/components/grid-list/grid-list.component.html
Closes SAP/fundamental-ngx/#5774
VoiceOver doesn't bind radio buttons to the parent div with `role="listbox"`. Because of this all radio buttons exist in the single scope and are included in shared total count. To overcome this, changing parent element tag from `div` to `form`
=> fix(core): grid list a11y for voice over

libs/platform/src/lib/approval-flow/approval-flow-select-type/approval-flow-select-type.component.html
Closes SAP/fundamental-ngx/#6467
Replace duplicate i18n ids with a new unique id, because the localized strings are different from the first usage of the previous ids.
=> fix(platform): replace duplicate i18n ids

apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-example.component.html, apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-styled-example.component.html, apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-template-example/inline-help-template-example.component.html, apps/docs/src/app/core/component-docs/inline-help/examples/inline-help-trigger-example.component.html, apps/docs/src/app/core/component-docs/inline-help/inline-help-docs.module.ts, libs/core/src/lib/inline-help/inline-help.directive.ts
Closes: https://github.com/SAP/fundamental-ngx/issues/6219
adding accessability label and  removing the hardcoded background
=> fix(core): adding accessability label to the inline help component

e2e/wdio/core/tests/notification.e2e-spec.ts
Closes none
fixes broken test - selector and variable both named 'button' caused test to click on the wrong button, renamed var button to buttonChoice.
- [n/a ] Run npm run build-pack-library and test in external application
- [ n/a] update `README.md`
- [ n/a] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
=> test(e2e): fix notification e2e test

libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.scss
Closes SAP/fundamental-ngx/#6547
add styles for extra space of fixed-height table
=> fix(platform): add styles for extra space of fixed-height table

libs/platform/src/lib/table/table.component.scss
Closes SAP/fundamental-ngx/#6543
Adjusted header and body cells' heights as follows:
Content density "condensed":
- header 2 rem
- body 1.563rem
Content density "compact":
- header 2 rem
- body 2rem
=> fix(platform): table - content density bugs

apps/docs/tsconfig.app.json, apps/docs/tsconfig.json, apps/docs/tsconfig.netlify.json
Closes SAP/fundamental-ngx/#6671
Currently docs application's `.spec` files are included in build process, that results in that build to fail. This is fixed by properly placing `include`/`exclude` statements in tsconfigs
=> chore: update tsconfig to not include spec files on build

libs/platform/src/lib/form/text-area/text-area.component.ts, libs/platform/src/lib/shared/form/base.input.ts
Closes SAP/fundamental-ngx/#3013
There is an extra ngModelChange event for all components based on BaseInput class: 
- when value is set by reactive form with `emitEvent: true`, there was 2 emissions of valueChanges (should be 1)
- when value is set with `emitEvent: false`, it still emitted once (while it should not)
Although the change is pretty simple, it affected a lot of platform CVAs. The following components were tested to be working correctly:
- checkbox-group
- date-picker
- datetime-picker
- input
- input-group
- base-multi-input
- radio
- time-picker
- combobox
- multi-combobox
- multi-input
- platform-file-uploader
- radio-group
- select
- number-step-input
- switch
- text-area
- list
- slider
- [n/a] check …
=> fix(platform): baseInput CVAs emit extra event

apps/docs/src/app/platform/component-docs/platform-icon-tab-bar/platform-icon-tab-bar-docs.component.html
Closes #6761 
Added appropriate anchors and separators to the documentation page
- [n/aStates - hover/disabled/focused/active/on click/selected/selected hover/press state
- n/a check for console logs (warnings, errors)
- n/a API boundary values
- n/a different combinations of components - free style
- n/a change the API values during testing
- n/a missing API …
=> fix(docs): add appropriate anchors to the documentation

apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-field-layout-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-generator/platform-form-generator-examples/platform-form-generator-observable-example.component.ts, libs/platform/src/lib/form/form-generator/dynamic-form-generator-datepicker/dynamic-form-generator-datepicker.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-editor/dynamic-form-generator-editor.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-select/dynamic-form-generator-select.component.html
Closes #6725 
Added usage of placeholder property of form generator metadata
=> fix(platform): use placeholder property for form generator

libs/core/src/lib/multi-input/multi-input.component.html
Closes SAP/fundamental-ngx/#5987
Disabled browser native autocomplete for multi-input …
=> fix(core): multi-input, disable browser native autocomplete

apps/docs/src/app/platform/component-docs/platform-table/platform-table-docs.component.ts, libs/platform/src/lib/table/constants/index.ts, libs/platform/src/lib/table/table.component.scss, libs/platform/src/lib/table/table.component.ts
Closes #6543
There were few content density issues with the playground example.
This PR addresses all of them except for one that is handled by SAP/fundamental-styles#2751
Already approved here https://github.com/SAP/fundamental-ngx/pull/6748 …
=> fix(platform): table, content density issues

libs/core/src/lib/menu/directives/menu-interactive.directive.ts, libs/core/src/lib/menu/menu-item/menu-item.component.ts, libs/core/src/lib/split-button/split-button.component.ts
fixes #6451 
Selected styling needs to appear on the selected option in the split button dropdown menu.
Before
After
=> fix(core): split button selection

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-default-example.component.ts, libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-step.component.ts
fixes #7136 
mask password at summary page
-   [x] missing API documentation or …
=> fix(platform): hide password at summary page

libs/platform/src/lib/table/table-column-resize.service.ts, libs/platform/src/lib/table/table.component.spec.ts, libs/platform/src/lib/table/table.component.ts
Related to https://github.tools.sap/dxp/organization/issues/76
Platform table columns' width recalculation on resizing.
https://user-images.githubusercontent.com/20265336/141960333-189fc89a-223e-4ff1-8223-ef1b374cac3a.mov
Resizing goes not instantly to decrease the number of recalculations.
https://user-images.githubusercontent.com/20265336/141960202-98d379d6-812f-43f0-a781-28f1cfdd7c58.mov
=> fix(platform): table columns' width recalc on resize

libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
Fix for the `fd-table-cell` directive missed in value help dialog so build may fail because `fitContent` is not a known property of `td`.
=> fix(platform): value help dialog table cell

libs/core/src/lib/utils/functions/intersection-observable.ts
Fix for intersection observable for unsupported browsers.
`.subscribe()` fails on `intersectionObservable()` if no `IntersectionObserver` present in `window` object.
No error.
=> fix(core): intersection observable for unsupported browsers

apps/docs/src/app/core/component-docs/table/examples/table-toolbar-example.component.html
closes #7096 
Disable table toolbar while loading …
=> docs(core): disable table toolbar while loading

libs/platform/src/lib/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.html, libs/platform/src/lib/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.spec.ts, libs/platform/src/lib/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.ts
closes https://github.com/sap/fundamental-ngx/issues/6743
This pr fixes the highlight of the parent tab when the child tab is selected …
=> fix(platform): fix icon-tab-bar nested selection

apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-textarea/platform-textarea-examples/platform-textarea-counter-example.component.ts, libs/core/src/lib/slider/slider.component.ts, libs/platform/src/lib/form/combobox/commons/base-combobox.ts, libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.html, libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox.interface.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts, libs/platform/src/lib/form/step-input/base.step-input.ts, libs/platform/src/lib/form/text-area/text-area.component.ts, libs/platform/src/lib/shared/domain/data-model.ts
Closes https://github.com/sap/fundamental-ngx/issues/6781
Some of the components are not being visually reset when using `setValue(null)` or `reset()` on the reactive form.
Affected components:
- combobox
- multi-combobox
- number step input
- textarea
- slider
- [n/a] update …
=> fix(platform): should be able to reset form components

libs/platform/src/lib/table/table.component.ts
DXP, Jest
While using jest for the testing app that consumes ngx library then `ViewDestroyedError: Attempt to use a destroyed view: detectChange` error is shown. Here is the fix.
=> fix(platform): table change detection

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
Previously, setting cardMinimumWidth property may cause an error due to the component's incomplete initialization. This fix adds a check whether or not the layout is initialized.
=> fix(core): update layout when component initialized completely

.github/workflows/on-push-or-pull.yml, .github/workflows/on-schedule.yml, package-lock.json
closes none
github actions virtual machines switched to node 16 which doesn't support some of our dependencies. This PR makes the github actions machines use node 15.11.0 instead.
=> chore(ci): override github actions virtual machine node version

.eslintrc.json
Prohibit `fit` on the linting level same as `fdescribe`.
=> chore(core,platform): prohibit fit

libs/core/schematics/ng-add/index.ts, libs/core/schematics/ng-add/schema.json, libs/core/schematics/ng-add/schema.ts, libs/fn/schematics/ng-add/schema.json, libs/moment-adapter/schematics/ng-add/index.ts, libs/moment-adapter/schematics/ng-add/schema.json, libs/moment-adapter/schematics/utils/ng-module-utils.ts, libs/moment-adapter/schematics/utils/package-utils.ts, libs/platform/schematics/collection.json, libs/platform/schematics/migration-collection.json, libs/platform/schematics/ng-add/index.ts, libs/platform/schematics/ng-add/schema.json, libs/platform/schematics/ng-add/schema.ts, libs/platform/schematics/ng-update/index.ts, libs/platform/schematics/ng-update/schema.json, libs/platform/schematics/utils/package-utils.ts, libs/platform/schematics/utils/translation-utils.ts
Closes #7349 
Closes #7347
Schematics fixes & refactoring.
* Fixed
* Added ability to add font imports to `*.css` and `*.less` files, not only to `*.scss` as before.
* Implemented installing of dependent libraries. 
* Fixed
* Refactored
* `installations` prompt removed due to not making any sense.
* If `fundamental-ngx/core` or (and) `@angular/localize` dependent libraries haven't installed then will be installed and their schematics will be run.
* Fixed
* `npm run build-pack-library` locally
* Run `ng add ../fundamental-ngx/dist/libs/core` from the new application's folder
* Run `ng add ../fundamental-ngx/dist/libs/platform` from the new application's folder
* Run `ng add ../fundamental-ngx/dist/libs/moment-adapter` from the new application's folder
=> fix(core,platform): schematics

libs/platform/src/lib/form/select/commons/base-select.ts, libs/platform/src/lib/form/select/select/select.component.spec.ts, libs/platform/src/lib/form/select/select/select.component.ts
related to https://github.com/SAP/fundamental-ngx/issues/6866
Added `ngx-cva-test-suite` for `platform-select` component. It was required to make some minor changes in order to fulfill requirements of standard behavior for CVA. Also made some cleanup to get rid of unnecessary methods. 
**Breaking changes:**
- `source` has been removed from `FdpSelectionChangeEvent`, `FdpSelectionChangeEvent` itself is now deprecated
- `valueChange` output has been removed as it completely duplicates `selectionChange` output
-   [x] States - hover/disabled/focused/active/on …
=> fix(platform): select - fix CVA behavior and remove extra methods

CHANGELOG.md, libs/core/src/lib/README.md
* Readme update, postinstall scripts not needed anymore if using jest.
* Changelog breaking changes added because i forgot to add them before
=> chore(core,platform): readme & changelog update after ng13 migration

apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html, apps/docs/src/app/core/component-docs/dynamic-page/dynamic-page-examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.ts, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-docs.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.ts, e2e/wdio/core/tests/dynamic-page.e2e-spec.ts, e2e/wdio/platform/tests/dynamic-page-layout.e2e-spec.ts, libs/platform/src/lib/dynamic-page/dynamic-page.component.html, libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
closes #7374 
Added ability to define stackedTabs property for platform tabs.
Extended documentation examples.
3. …
=> fix(core,platform): add ability to define stacked tabs property

libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.scss
issue has been raised in comment https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-992775647
Grid List Item does not indicate the new position on drag.
-   [n/a] check for console logs …
=> fix(core): grid-list, not show indicator of new position on drag

libs/platform/schematics/collection.json, libs/platform/schematics/ng-add/index.ts, libs/platform/schematics/ng-update/index.ts, libs/platform/schematics/utils/translation-utils.ts
Closes #7420.
Platform schematics uses `xml2js` package while processing translation files. But the package may not be present in the host application so it leads schematic run to fail. Added steps of installing & removing `xml2js` package.
Previously bug wasn't catched because when running `ng add ../fundamental-ngx/dist/libs/platform` `xml2js` was found in `../fundamental-ngx/node_modules`.
```
npm run build-pack-library
cd (new angular application folder)
cp ../fundamental-ngx/dist/libs/platform/fundamental-ngx-platform-0.33.0-rc.*.tgz ./
ng add fundamental-ngx-platform-0.33.0-rc.*.tgz
```
=> fix(platform): schematics' translations tasks

libs/core/src/lib/popover/popover.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/7445
Temporary fix for the popover's vertical overflow.
It's not the final solution because to reach the popover's footer you need to scroll down. Ideally, only the popover's body should be scrollable but due to the complexity of the task it will be done later.
=> fix(core): popover vertical overflow

libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.scss, libs/core/src/lib/popover/popover.component.scss
Refers to https://github.com/SAP/fundamental-ngx/issues/7445
Previously we merged https://github.com/SAP/fundamental-ngx/pull/7528. There was a fix to add a scrollbar if popover goes `> 80vh` but it brokes some other components that use popover.
Here i limit the fix by applying it only for the datetime and the rest will be fixed separately.
=> fix(core): datetime vertical overflow

apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html, apps/docs/src/app/documentation/common-components/datetime-important/datetime-important.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.ts
Part of https://github.com/SAP/fundamental-ngx/issues/7362
[Comment with the issue description](https://github.com/SAP/fundamental-ngx/issues/7362#issuecomment-992755343) 
1. 
> Disabled DateTime Picker has pointer events and triggers the validation message
- changed to `focusin focusout` instead.
2. 
> DateTime Picker i18n example. Click inside the input field and delete the `m.`, it shows the input field is invalid and colors in red. Add back `m.` and the field is still invalid. Expected behaviour: field should become valid again
This is by design. There is a warning message right before this example that by default parsing is limitted only to en locale
-   [na] visual misalignments/updates
-   [na] check Light/Dark/HCB/HCW themes
-   [na] RTL/LTR - proper rendering …
=> fix(core): datetime picker form-message trigger

PLATFORM_README.md, libs/core/src/lib/ng-package.json, libs/core/src/lib/package.json, libs/fn/src/lib/ng-package.json, libs/fn/src/lib/package.json, libs/platform/src/lib/ng-package.json, libs/platform/src/lib/package.json
Closes https://github.com/SAP/fundamental-ngx/issues/7542
* Platform readme update to notify about jest issue with lodash-es
* `lodash-es` & `fast-deep-equal` added as `deps`, not `peerDeps`
https://deploy-preview-7544--fundamental-ngx.netlify.app/#/platform/home
https://github.com/SAP/fundamental-ngx/wiki/Full-Installation-Guide
=> fix(core,platform,fn): lodash-es & fast-deep-equal as deps & docs update about jest issue with lodash-es

libs/platform/src/lib/table/table-column-resize.service.ts
DXP.
Currently, if table column has width set in `%` and table has `0` width - we will see a lot of errors in the console. 
Table can be initialized and not rendered due to many reasons (it's inside the not active tab, for example) and it shouldn't come up with endless errors in the console.
The fix is to return `auto` as a column width and skip all the calculations if table doesn't have width.
Errors in the console.
No errors.
=> fix(platform): table column's width

apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav-responsive/shellbar-side-nav-responsive-example.component.html, apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav-responsive/shellbar-side-nav-responsive-example.component.scss, apps/docs/src/app/core/component-docs/shellbar/examples/shellbar-side-nav-responsive/shellbar-side-nav-responsive-example.component.ts, apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.html, apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.component.ts, apps/docs/src/app/core/component-docs/shellbar/shellbar-docs.module.ts, libs/core/src/lib/shellbar/shellbar.component.ts, libs/core/src/lib/side-navigation/side-navigation.component.ts
closes #4522 
Adds the optional input `collapseWidth` to the side navigation component, allowing the developer to set a breakpoint at which the sidebar will automatically collapse on window resize.
=> feat(core): add input for responsive side nav

libs/core/src/lib/token/token.component.html, libs/core/src/lib/token/token.component.ts, libs/core/src/lib/token/token.module.ts, libs/core/src/lib/token/tokenizer.component.html, libs/core/src/lib/token/tokenizer.component.scss, libs/core/src/lib/token/tokenizer.component.ts
Part of https://github.com/SAP/fundamental-ngx/issues/7550
Overflow list implemented for the tokenizer component in compact mode.
Because of https://github.com/angular/angular/issues/37995#issuecomment-1015880820 approach with `viewContainerRef` was used, i.e. we cannot have token projected via `ng-content` in tokenizer & overflow list at the same time, so token content hides from the tokenizer (or overflow list) `viewContainer` and shows in overflow list (or tokenizer) `viewContainer`, depending on the current state.
=> fix(core): tokenizer overflow

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-visibility-between-steps-example.component.html, apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-visibility-between-steps-example.component.ts, apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.component.html, apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.module.ts, libs/platform/src/lib/form/form-generator/dynamic-form-control-field.directive.ts, libs/platform/src/lib/form/form-generator/dynamic-form-control.ts, libs/platform/src/lib/form/form-generator/fdp-form-generator.module.ts, libs/platform/src/lib/form/form-generator/form-generator-components-accessor.service.spec.ts, libs/platform/src/lib/form/form-generator/form-generator-components-accessor.service.ts, libs/platform/src/lib/form/form-generator/form-generator.service.spec.ts, libs/platform/src/lib/form/form-generator/form-generator.service.ts, libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.ts, libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-group.ts, libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts, libs/platform/src/lib/wizard-generator/base-wizard-generator.ts, libs/platform/src/lib/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.ts, libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.html, libs/platform/src/lib/wizard-generator/components/wizard-body/wizard-body.component.ts, libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.ts, libs/platform/src/lib/wizard-generator/components/wizard-generator/wizard-generator.component.ts, libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-form-group.interface.ts, libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-item.interface.ts, libs/platform/src/lib/wizard-generator/wizard-generator.service.ts
closes #7332 
* Updated `when` function scope for wizard generator. Previously it was only form group scope, now it can be uses as whole wizard scope.
* Refactored Form Generator Service so that storing custom components is now independent from the form generator service itself, because form generator service can be provided on component level, thus, previously registered components are not available for this instance of the service.
For testing, please check last example of Platform Wizard Generator.
-   [x] States - hover/disabled/focused/active/on …
=> feat(platform): when function for global wizard generator scope

apps/docs/src/app/core/component-docs/tile/examples/clickable-tile-example.component.html, apps/docs/src/app/core/component-docs/tile/examples/tile-examples.component.ts, apps/docs/src/app/core/component-docs/tile/tile-docs.component.html, apps/docs/src/app/core/component-docs/tile/tile-docs.component.ts, apps/docs/src/app/core/component-docs/tile/tile-docs.module.ts, libs/core/src/lib/tile/tile.component.html, libs/core/src/lib/tile/tile.component.ts
Part of https://github.com/SAP/fundamental-ngx/issues/7587
>  (Core) Tile, has unneeded tab stop (or event on click needed)
As tile is focusable in [SAPUI5](https://sapui5.hana.ondemand.com/#/entity/sap.m.GenericTile/sample/sap.m.sample.GenericTileAsLaunchTile) i decided to left such behavior but also add:
* event emitting on click (as in the SAPUI5)
* ability to make tile not focusable (of course clicking is not possible also).
=> feat(core): tile clickable flag & event emit on click

apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-docs.component.html, apps/docs/src/app/platform/component-docs/platform-search-field/platform-search-field-examples/platform-search-field-categories-example.component.html, libs/platform/src/lib/search-field/search-field.component.html, libs/platform/src/lib/search-field/search-field.component.ts
Closes https://github.com/SAP/fundamental-ngx/issues/7377
Feature to set predefined category from categories for search field component.
=> feat(platform): search field predefined category

apps/docs/src/app/platform/component-docs/platform-wizard-generator/examples/wizard-generator-visibility-between-steps-example.component.ts, apps/docs/src/app/platform/component-docs/platform-wizard-generator/platform-wizard-generator-docs.component.html, libs/platform/src/lib/form/form-generator/form-generator.service.ts, libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.html, libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.ts, libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-form-group.interface.ts, libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-item.interface.ts, libs/platform/src/lib/wizard-generator/wizard-generator.service.ts
closes #7500 
Added `when` method for form groups of wizard generator step.
To check the functionality, please check last wizard generator example.
-   [x] change …
=> feat(platform): when property of form groups

apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-flexible-column-example.component.html, apps/docs/src/app/platform/component-docs/platform-dynamic-page/platform-dynamic-page-examples/platform-dynamic-page-tabbed-example.component.html, libs/platform/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts, libs/platform/src/lib/dynamic-page/dynamic-page.component.html, libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
None.
Event emitting of tab change for the platform dynamic page component.
Event is now emitted from dynamic page component instead of dynamic page content (tab) component to fix the behavior when events were emitted only from the first content (tab) component and to avoid emitting multiple identical events from every content (tab) component.
BREAKING CHANGES:
`(tabChange)` event now emitted on `DynamicPageComponent` instead of `DynamicPageContentComponent`.
Interface not changed.
https://github.com/SAP/fundamental-ngx/wiki/0.33.0-Breaking-Changes#dynamic-page-component-platform-7669
=> fix(platform): dynamic tab page event on tab change

apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.module.ts, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-update-on-blur-example.component.ts, apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.html, apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.component.ts, apps/docs/src/app/core/component-docs/datetime-picker/datetime-picker-docs.module.ts, apps/docs/src/app/core/component-docs/datetime-picker/examples/datetime-picker-update-on-blur-example/datetime-picker-update-on-blur-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-date-picker/platform-date-picker-examples/platform-date-picker-update-on-blur-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-docs.module.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-datetime-picker/platform-datetime-picker-examples/platform-datetime-picker-update-on-blur-example.component.ts, e2e/wdio/platform/tests/date-time-picker.e2e-spec.ts, libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/date-picker/date-picker.component.spec.ts, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/datetime-picker/datetime-picker.component.spec.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/platform/src/lib/form/date-picker/date-picker.component.html, libs/platform/src/lib/form/date-picker/date-picker.component.ts, libs/platform/src/lib/form/datetime-picker/datetime-picker.component.html, libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts
closes #7525 
Currently input updates it's value and validity as user types. Adding an ability to apply changes on leaving the input or by hitting enter.
Functionality has been added to:
- core-date-picker
- core-datetime-picker
- platform-date-picker
- core-datetime-picker
-   [x] check …
=> feat(core,platform): date & datetime picker - ability to process input value on blur

libs/core/src/lib/pagination/pagination.component.ts
None.
Disable limiting `itemsPerPage` for the pagination component.
Example: If user provides only 18 pages he should can set `itemsPerPage` to 18+ (20, 40, etc).
=> fix(core): disable max items per page

package.json, transform-typedoc-files.js
closes #7677 
Since some servers are case-sensitive for filenames in url, now we transform typedoc files to be in lowercase registry.
=> fix(docs): lowercase typedoc files

apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-examples/platform-select-height/platform-select-max-height-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-examples/platform-select-mobile-example/platform-select-mobile-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-examples/platform-select-mode-example/platform-select-mode-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-examples/platform-select-none/platform-select-none-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-examples/platform-select-nowrap/platform-select-nowrap-example.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-select/platform-select-examples/platform-select-semantic-state-example/platform-select-semantic-state-example.component.ts, libs/platform/src/lib/form/public_api.ts, libs/platform/src/lib/form/select/commons/base-select.ts, libs/platform/src/lib/form/select/models/select.models.ts, libs/platform/src/lib/form/select/public_api.ts
closes https://github.com/SAP/fundamental-ngx/issues/7616
When selecting option in select, selected value should be displayed as text, instead we have `[object Object]`
-   [n/a] different combinations of …
=> fix(platform): select - display proper value

libs/platform/src/lib/table/table-column-resize.service.ts, libs/platform/src/lib/table/table.component.ts
Closes #7648.
Platform table columns' width error not emitted anymore if the table container has 0 width, instead method that returns styles for the cells returns `{}` (empty object) instead of constructing styles object.
No errors.
In case you need to reproduce the issue you need to adjust any of the table examples by wrapping table in tab/tabbed-dynamic-page & set width in `%` for any column. Or just apply this path - [table-patch.txt](https://github.com/SAP/fundamental-ngx/files/8004979/table-patch.txt)
=> fix(platform): table columns' width error

libs/core/schematics/ng-add/index.ts, libs/core/src/lib/ng-package.json, libs/core/src/lib/package.json, libs/fn/src/lib/ng-package.json, libs/fn/src/lib/package.json, libs/platform/src/lib/ng-package.json, libs/platform/src/lib/package.json
Closes #7710.
`@angular/cdk` listed as the dependency for the core, platform and fn. It's working okay for any local applications. But stackblitz resolves dependency slightly different so it's doesn't work there. `@angular/*` packages should be listed as `peerDependency`. Here is the recommendation from official angular docs https://angular.io/guide/creating-libraries#peer-dependencies. 
Example https://fundamental-ngx.netlify.app/#/core/popover#trigger in StackBlitz.
* `@angular/cdk` as `dependency` (current behavior): https://stackblitz.com/edit/angular-ecunnt **not working**
* `@angular/cdk` as `peerDependency` (i've published fork of the package to be able to test it): https://stackblitz.com/edit/angular-pdyeqe **working**
**Note**: this fix doesn't solve any `strictTemplates` \ …
=> fix(core,platform,fn): stackblitz inject issue

apps/docs/src/app/core/component-docs/time-picker/examples/time-picker-form-example.component.ts, e2e/wdio/core/tests/time-picker.e2e-spec.ts
closes n/a
Fixed `expressionchangedafterithasbeencheckederror`, commented out e2e test, that is constantly failing on CI
-   [n/a] change the …
=> fix(core): time-picker - fix e2e and console errors

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts
user type in input and then press enter to select option or add new token.
this commit resolve one of issue in this #7611
if token is new and user allow to add new token and token is not exist in current list then user by pressing enter can add the new token to tokenlist.
if the token exist in list so user by pressing enter can add it to token list.
closes
_onsubmit method check this behavior for adding token.
=> fix(core): solve multi input add new token

apps/docs/src/app/platform/component-docs/platform-vhd/platform-vhd-examples/platform-vhd-input-example.component.html, libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html, libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/7615
Fundamental-ngx:
Guideline:
-   [x ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck …
=> fix(platform): vhd - misc issues

apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-columns/combobox-columns-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-datasource/combobox-datasource-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-forms/combobox-forms-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-group/combobox-group-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-loading/combobox-loading-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-mobile/combobox-mobile-example.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-standard/combobox-standard.component.html, apps/docs/src/app/platform/component-docs/platform-combobox/examples/combobox-templates/combobox-templates-example.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-form-container/platform-form-container-examples/platform-form-custom-layout.component.html, e2e/wdio/platform/pages/input.po.ts, e2e/wdio/platform/tests/form-generator.e2e-spec.ts, libs/core/src/lib/input-group/input-group.component.scss, libs/platform/src/lib/form/form-group/fdp-form.module.ts, libs/platform/src/lib/form/form-group/form-field-extras/form-field-extras.component.ts, libs/platform/src/lib/form/form-group/form-field/form-field.component.html, libs/platform/src/lib/form/form-group/form-field/form-field.component.ts, libs/platform/src/lib/form/form-group/form-group.component.scss, libs/platform/src/lib/form/form-group/form-group.component.ts, libs/platform/src/lib/form/public_api.ts, libs/platform/src/lib/form/text-area/text-area.component.html, libs/platform/src/lib/form/text-area/text-area.component.scss, libs/platform/src/lib/form/text-area/text-area.component.spec.ts, libs/platform/src/lib/form/text-area/text-area.component.ts, libs/platform/src/lib/shared/form/form-control.ts, libs/platform/src/lib/slider/slider.component.spec.ts
closes https://github.com/SAP/fundamental-ngx/issues/7607
closes https://github.com/SAP/fundamental-ngx/issues/7614
This PR combines changes from https://github.com/SAP/fundamental-ngx/pull/7697 (textarea label alignment) with additional enhancements for aligning labels, when there're additional content inside form-field.
Created a new component `fpd-form-field-extras`, that should be used to wrap such additional content.
-   [n/a] Interaction/Animation - open/close, …
=> fix(platform): compensate label offset when additional form-field content is added

libs/core/src/lib/menu/menu-item/menu-item.component.spec.ts, libs/core/src/lib/menu/menu-item/menu-item.component.ts, libs/core/src/lib/menu/menu.component.html, libs/core/src/lib/menu/menu.component.scss
part of https://github.com/SAP/fundamental-styles/issues/3168
Menu item should not receive focus styles on mouse hover. Also remove extra box shadow coming from popover + menu..
=> fix(core): menu item should not receive focus on mouse hover and remove extra box shadow [ci visual]

libs/core/schematics/add-animations/index.ts, libs/core/schematics/collection.json, libs/core/schematics/ng-add/index.ts
Closes none.
Methods that are using `@angular/cdk` moved into separate schematics to avoid importing package before its installation.
Probably, issue is reproducible using node v14 or below, doing `npm cache clear --force` also may help to reproduce the initial issue.
=> fix(core): @angular/cdk schematics issue

apps/docs/src/app/core/component-docs/notification/examples/component-as-content/notification-content.component.html, apps/docs/src/app/core/component-docs/notification/examples/component-as-content/notification-content.component.ts, apps/docs/src/app/core/component-docs/notification/examples/notification-group/notification-group-example.component.html, apps/docs/src/app/core/component-docs/notification/examples/notification-options/notification-options-example.component.html, apps/docs/src/app/core/component-docs/notification/examples/template-as-content/notification-open-template-example.component.html, apps/docs/src/app/core/component-docs/notification/examples/template-as-content/notification-open-template-example.component.ts, apps/docs/src/app/core/component-docs/notification/notification-docs.module.ts, apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts, libs/core/src/lib/notification/notification-actions/notification-actions.component.spec.ts, libs/core/src/lib/notification/notification-actions/notification-actions.component.ts, libs/core/src/lib/notification/notification-body/notification-body.component.ts, libs/core/src/lib/notification/notification-content/notification-content.component.spec.ts, libs/core/src/lib/notification/notification-footer/notification-footer.component.spec.ts, libs/core/src/lib/notification/notification-group-header/notification-group-header.component.ts, libs/core/src/lib/notification/notification-header/notification-header.component.spec.ts, libs/core/src/lib/notification/notification-header/notification-header.component.ts, libs/core/src/lib/notification/notification-limit/notification-limit.component.spec.ts, libs/core/src/lib/notification/notification-service/notification.service.spec.ts, libs/core/src/lib/notification/notification-service/notification.service.ts, libs/core/src/lib/notification/notification-utils/notification-config.ts, libs/core/src/lib/notification/notification-utils/notification-group-base.ts, libs/core/src/lib/notification/notification.module.ts, libs/core/src/lib/notification/notification/notification.component.spec.ts, libs/core/src/lib/notification/notification/notification.component.ts, libs/core/src/lib/notification/public_api.ts
closes https://github.com/SAP/fundamental-ngx/issues/5579
Fixing a11y issues for notifications component.
Overview of changes that were made according to the ticket:
Issue 1: cannot reproduce
Issue 2: cannot reproduce
Issue 3: done
Issue 4: done
Issue 5: done
Issue 6: done
Issue 7: done
Issue 8: done
Issue 9: done
Issue 10: not done, should be fixed within https://github.com/sap/fundamental-ngx/issues/3123
Issue 11: cannot reproduce
Issue 12: not done, navigation information for tabs is needed
Issue 13: cannot reproduce
-   [x] States - …
=> fix(core): notification a11y

libs/core/src/lib/notification/notification-service/notification.service.ts, libs/core/src/lib/notification/notification-utils/notification-group-base.ts
fix lint errors in notification
=> chore(core): fix lint errors in notification

apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox-no-form.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox-no-form.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-binary-checkbox.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-a11y.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-checkbox-error-handling.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-multiselect-checkbox.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-tristate-checkbox.component.html, apps/docs/src/app/platform/component-docs/platform-forms/checkbox/platform-checkbox-examples/platform-tristate-checkbox.component.ts, apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-content-checkbox.component.html, apps/docs/src/app/platform/component-docs/platform-forms/platform-checkbox-group/platform-checkbox-group-examples/platform-checkbox-group-example.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/core/src/lib/checkbox/checkbox/fd-checkbox-values.interface.ts, libs/core/src/lib/checkbox/public_api.ts, libs/platform/src/lib/form/checkbox-group/checkbox-group.component.html, libs/platform/src/lib/form/checkbox-group/checkbox-group.component.spec.ts, libs/platform/src/lib/form/checkbox-group/checkbox-group.component.ts, libs/platform/src/lib/form/checkbox/checkbox.component.html, libs/platform/src/lib/form/checkbox/checkbox.component.spec.ts, libs/platform/src/lib/form/checkbox/checkbox.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/7751
Adding range selection capabilities to platform checkbox group.
Identified, that there're a lot of redundant component logic both in checkbox and checkbox group, so made the following changes:
- removed logic for changing selection state. Now everything is handled by internal `fd-checkbox`
- deprecated `isBinary` input as it's completely redundant
- deprecated `value` input, that was used to pass `trueValue` for `fd-checkbox`. Now it's recommended to use `values` input, that is the same to what's used inside `fd-checkbox`
- removed deprecated `stateType` input
- deprecated `indeterminateChange` output in favour of `checkedChange`
- deprecated `change` output in favour of `checkedChange`
- deprecated `checked` input in favour of …
=> feat(platform): checkbox,checkbox-group - range selection & code enhancements

apps/docs/src/app/documentation/core-helpers/sections-toolbar/sections-toolbar.component.html
Not aware if any
Sub items of the toolbar sections were not rendered correctly. Now it is fixed
=> fix(docs): fixed incorrect rendering of subItems

libs/core/src/lib/grid-list/components/grid-list-filter-bar/grid-list-filter-bar.component.html, libs/core/src/lib/grid-list/components/grid-list-group-header/grid-list-group-header.component.html
Part of #7815.
Tabindexes set to `-1` for filter-bar & group-header elements.
=> fix(core): grid list filter-bar & group-header tabindexes

libs/core/src/lib/time/time-column/time-column.component.html
Part of #7815.
Unneeded tab stop removed when tabbing between elements (hours, minutes, am\pm) of the time picker.
2 tab stops.
1 tab stop.
=> fix(core): time picker tabindexes

apps/docs/src/app/core/component-docs/list/examples/list-action-example/list-action-example.component.html, apps/docs/src/app/core/component-docs/list/examples/list-action-example/list-action-example.component.ts, e2e/wdio/core/tests/standard-list.e2e-spec.ts
Part of #7815.
Action list unneeded tab stop removed from the "load more" button.
2 tab stops.
1 tab stop.
=> fix(core): action list tabindex

libs/core/src/lib/splitter/splitter-resizer/splitter-resizer.component.ts, libs/platform/src/lib/table/table-column-resize.service.ts
Closes #7911.
rxjs `debounceTime` instead of `delay` where it were misapplied.
=> fix(core,platform): rxjs debounceTime instead of delay

libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html, libs/core/src/lib/dynamic-page/dynamic-page.module.ts, libs/core/src/lib/utils/directives/ignore-click-on-selection/ignore-click-on-selection.directive.ts, libs/core/src/lib/utils/directives/ignore-click-on-selection/ignore-click-on-selection.module.ts, libs/core/src/lib/utils/directives/ignore-click-on-selection/tokens.ts, libs/core/src/lib/utils/public_api.ts
closes #7910 
Added directive, which will listen on element click and if document has active selection from that element it will not propagate click events. This way we do not have to cancel every event, but only the ones which result selection
=> feat(core): added ignore click on selection directive

libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.html, libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts, libs/core/src/lib/dynamic-page/dynamic-page.component.html, libs/core/src/lib/dynamic-page/dynamic-page.component.ts
Closes #7914.
Dynamic page spacer aka footer pad now is shown only if footer component is provided.
This pr also fixes platform dynamic page implicitly.
=> fix(core, platform): dynamic page spacer

libs/core/src/lib/menu/services/menu.service.ts
closes #7968
Problem was that after re-render, in menuMap old item would not exist, but code was still thinking that it existed and tried to access `item` on non-existent node, although next lines were ready for that circumstances, Find was still going on. This change fixes that.
=> fix(core): clicking on tabs in overflow menu produced errors

libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.html, libs/core/src/lib/dynamic-page/dynamic-page-content/dynamic-page-content.component.ts, libs/core/src/lib/dynamic-page/dynamic-page.component.spec.ts, libs/core/src/lib/dynamic-page/dynamic-page.component.ts, libs/core/src/lib/dynamic-page/tsconfig.json
Follow up https://github.com/SAP/fundamental-ngx/pull/7962
I missed that dynamic page may contain tabs and then there will be several dynamic page content components, so the approach of showing spacer should be different a bit. 
Spacer is not shown in stacked tabs example
Spacer is shown for only the last content component when there is stacked tabs
=> fix(core, platform): dynamic page spacer fix, update for tabs

libs/core/src/lib/time-picker/time-picker.component.ts
closes #6428 
This fix will make time picker respect null values, when locale is changed
=> fix(core): time picker locale change incorrect behavior

libs/core/src/lib/time/time-column/time-column.component.ts
closes #7959
Equal check was missing, it would try to access out of boundary element from array to get value, instead it should have started from delta index element when index was out of boundary
=> fix(core): fixed time picker drag end on last array element

apps/docs/src/app/documentation/core-helpers/stackblitz/stackblitz.service.ts
It was reported from community slack channel
Added missing delta variables files
=> fix(docs): fixed missing variables file in stackblitz examples

libs/core/src/lib/split-button/split-button.component.html, libs/core/src/lib/split-button/split-button.component.scss, libs/core/src/lib/split-button/split-button.component.ts, libs/platform/src/lib/split-menu-button/split-menu-button.component.html, libs/platform/src/lib/split-menu-button/split-menu-button.component.ts
part of #7984
Type class should have been applied to the parent class too
=> fix(core,platform): missing class on split button

e2e/wdio/platform/fixtures/appData/value-help-dialog-contents.ts, e2e/wdio/platform/pages/value-help-dialog.po.ts, e2e/wdio/platform/tests/value-help-dialog.e2e-spec.ts, libs/platform/src/lib/search-field/search-field.component.html, libs/platform/src/lib/search-field/search-field.component.ts, libs/platform/src/lib/value-help-dialog/value-help-dialog.module.ts, libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html, libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Closes #7908.
Previously search button was used only to focus search field input, now by clicking on it search is performed by the value in the search field input without any other filter values. Button "Go" still performs search by all of the filters, including search, nothing changed here.
=> fix(platform): value help dialog search

apps/docs/src/app/core/component-docs/breadcrumb/breadcrumb-docs.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.ts
Fixes the default breadcrumb overflow order and allows the developer via input to specify if they'd like to stack the items in reverse
part of #7631
=> fix(core): correct breadcrumb order

apps/docs/src/app/core/component-docs/card/card-docs.component.ts, apps/docs/src/app/core/component-docs/card/examples/card-example.component.html
part of #7984 
Fixed card image example. Updating fundamental styles version so that after that cards do not have overflown content
https://github.com/SAP/fundamental-styles/pull/3379
=> fix(docs): card examples

libs/core/src/lib/panel/panel.component.html, libs/core/src/lib/panel/panel.component.spec.ts, libs/core/src/lib/panel/panel.component.ts, package-lock.json, package.json
part of #8085 
Changes the panel template API by adding a div but I do not believe this should be a breaking change for anyone.
Before:
After:
=> fix(core): panel horizon updates

libs/core/src/lib/nested-list/nested-content/nested-list-content.directive.ts, libs/core/src/lib/nested-list/nested-item/nested-item.directive.ts, libs/core/src/lib/nested-list/nested-link/nested-link.directive.ts, libs/core/src/lib/nested-list/nested-list-directives.ts, libs/core/src/lib/nested-list/nested-list-keyboard.service.ts, libs/core/src/lib/nested-list/nested-list/nested-list.directive.ts
closes https://github.com/SAP/fundamental-ngx/issues/6179
Fix nested-list a11y issues
3. …
=> fix(core): nested-list, fix a11y issues

apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.module.ts, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-disable-focus-scroll-example.component.ts, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-form-example.component.ts, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts, libs/platform/src/lib/form/date-picker/date-picker.component.html, libs/platform/src/lib/form/date-picker/date-picker.component.ts, libs/platform/src/lib/form/datetime-picker/datetime-picker.component.html, libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts
closes #7792
* Added input property to disable scrolling into viewport of focused element for datepicker and datetime picker in core and platform.
-   [x] change the …
=> fix(core,platform): dont scroll into view on focus

libs/core/src/lib/select/select.component.html
Closes https://github.com/SAP/fundamental-ngx/issues/7929
Select `fillControlMode` property forwarding to the popover
=> fix(core): select fillControlMode property forwarding to the popover

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.spec.ts, libs/core/src/lib/multi-input/multi-input.component.ts
Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1146820476
Do not hide multi input when mobile dialog is open.
=> fix(core): multi input - show input when mobile dialog opened

apps/docs/src/app/core/component-docs/flexible-column-layout/examples/default/flexible-column-layout-example.component.scss, apps/docs/src/app/core/component-docs/flexible-column-layout/examples/dynamic-page/flexible-column-layout-dynamic-page-example.component.scss, libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html, libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1111398246
Added 0 height overflow: hidden, if column is hidden.
=> fix(core): handle overflow scrollbar with hidden columns

libs/core/src/lib/table/directives/table-text.directive.ts, libs/platform/src/lib/table/components/table-column/table-column.component.ts, libs/platform/src/lib/table/components/table-column/table-column.ts, libs/platform/src/lib/table/table.component.html
Closes https://github.com/SAP/fundamental-ngx/issues/7930
Ability to optionally apply table-text directive in platform table.
=> feat(core): ability to optionally apply table-text directive in table

libs/core/src/lib/popover/base/base-popover.class.ts, libs/core/src/lib/popover/popover-service/popover.service.spec.ts, libs/core/src/lib/popover/popover-service/popover.service.ts
closes none
When there're multiple triggers specified for the popover, the same trigger event will not change popover state if invoked subsequently. For example, `triggers = ['keydown', 'click']`, then if clicked twice, the second event won't do anything.
There was a fix for https://github.com/SAP/fundamental-ngx/issues/5203, in which there was some logic added to fulfil the behavior described in the ticket. However, the previous behavior was correct and we should not prevent subsequent events from being triggered. 
Reproduction https://stackblitz.com/edit/angular-dm5bfi
Instead, in this PR adding `TriggerConfig` support, that will allow do specify whether specific events should apply for both opening and close actions (as default behavior) or to work only for close/open behavior apart
1. …
=> fix(core): popover - fix subsequent openings triggered by same event

libs/core/src/lib/busy-indicator/busy-indicator.component.scss
Part of https://github.com/SAP/fundamental-ngx/issues/7984#issuecomment-1151480271
Changed overlay color from hardcoded value to theme-based color
=> fix(core): fixed busy indicator overlay background color

apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html, apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.ts, apps/docs/src/app/core/component-docs/table/table-docs.component.html, apps/docs/src/app/core/component-docs/table/table-docs.module.ts, e2e/wdio/core/pages/table.po.ts, e2e/wdio/core/tests/table.e2e-spec.ts
part of #7984 
Improves the table sort/filter example documentation.
before:
after:
=> docs(core): improve table sort/filter docs

libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/token/tokenizer.component.html, libs/core/src/lib/token/tokenizer.component.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts, libs/platform/src/lib/form/multi-input/multi-input.component.ts
closes none
Fixes a bug that arose from #7619 where clicking the "more" text on a multi-input would display the multi-input's dropdown list as well as the tokenizer's popover of overflowing tokens.
before:
after:
=> fix(core,platform): fix bug where extra popover would be shown when clicking more text on multi-input

libs/i18n/src/lib/languages/english.ts, libs/i18n/src/lib/languages/pluralization/set1.ts, libs/i18n/src/lib/languages/russian.ts, libs/i18n/src/lib/languages/ukrainian.ts, libs/i18n/src/lib/pipes/fd-translate.pipe.ts
closes none
Enhancing existing translations for ukrainian and russian languages by adding proper plural forms to nouns.
This PR also includes few fixes to the translation params and wording updates according to SAP translation guidelines (see below)
[Translation_Style_Guide_UK.pdf](https://github.com/SAP/fundamental-ngx/files/8919761/Translation_Style_Guide_UK.pdf)
=> feat: i18n pluralization

libs/platform/src/lib/menu/menu-item.component.html, libs/platform/src/lib/menu/menu-item.component.ts
fixes none, requested via slack
Allows the developer to disable platform menu items via input
=> fix(platform): allow platform menu items to be disabled

libs/platform/src/lib/table/table.component.scss
Closes none.
platform table empty message box-sizing. 
*previously we didn't see the bug because of the styles in the docs app*
=> fix(platform): table empty message box-sizing

apps/docs/src/app/app.component.ts, apps/docs/src/app/app.module.ts, apps/docs/src/app/documentation/core-helpers/toolbar/toolbar.component.ts, apps/docs/src/app/documentation/shared-documentation.module.ts, libs/core/src/lib/theming/theming.service.ts
Closes none.
Fit for the theming service was initialising a bit too late.
_To see the difference come directly to the page (or reload) because if we come from another page -  styles are already loaded so we don't see the issue._
_http://localhost:4200/fundamental-ngx#/core/fixed-card-layout_
=> fix(docs): theming service init

apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.html, apps/docs/src/app/core/component-docs/action-bar/examples/action-bar-mobile-example.component.ts, e2e/wdio/core/tests/action-bar.e2e-spec.ts
relates 8342
Changed desktop menu to mobile one for Action Bar Mobile example.
=> fix(docs): action bar mobile example

apps/docs/src/styles.scss
relates #8342
Added `:not` selector for anchor styling in order to skip `.fd-link` elements.
=> fix(docs): ignore fd-link styling

libs/core/src/lib/popover/popover-body/popover-body.component.scss
=> fix(core): small bug with combobox border radius

apps/docs/src/app/core/component-docs/illustrated-message/examples/illustrated-message-inline-example.component.html, apps/docs/src/app/core/component-docs/illustrated-message/examples/illustrated-message-inline-example.component.ts, apps/docs/src/app/core/component-docs/illustrated-message/illustrated-message-docs.component.html, apps/docs/src/app/core/component-docs/illustrated-message/illustrated-message-docs.component.ts, apps/docs/src/app/core/component-docs/illustrated-message/illustrated-message-docs.module.ts, libs/core/src/lib/illustrated-message/illustrated-message.component.spec.ts, libs/core/src/lib/illustrated-message/illustrated-message.component.ts, libs/core/src/lib/utils/interfaces/require.interface.ts, libs/core/src/lib/utils/public_api.ts
closes #8361 
Added option to pass inline svg code into illustrated message.
- …
=> feat(core): add inline svg option for illustrated message

libs/core/src/lib/time/time-column/time-column.component.html, libs/core/src/lib/time/time-column/time-column.component.ts
closes #8390 
Added recalculation after time column has been resized (can be happening when calendar popover in tabs mode) for correct current time position calculation.
-   [x] different combinations of components - free …
=> fix(core): adjust size on time column resize

apps/docs/src/app/core/component-docs/dialog/examples/dialog-form/form-dialog-example.component.html
part of #7744 - remove word `disabled` from not-disabled textarea example in dialog
=> docs(core): update dialog with textarea example

libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.spec.ts, libs/core/src/lib/product-switch/product-switch-body/product-switch-body.component.ts
fixes #8406 
When the user has navigated to the end of the products, right arrow key (or left in RTL) should bring focus back to the start
=> fix(core): product switch should loop back to the start after right arrow key

apps/docs/src/app/documentation/core-helpers/component-example/component-example.component.ts
Closes none.
RTL support for the Platform Wizard Generator examples in the docs app.
=> docs(platform): rtl support for wizard generator in dialogs

libs/core/src/lib/tile/directives/numeric-content.directives.ts
Export missing types for correct binding in user's templates
=> fix(core): export missing types

libs/core/src/lib/content-density/classes/deprecated-compact.directive.ts, libs/core/src/lib/content-density/classes/deprecated-condensed.directive.ts, libs/core/src/lib/content-density/classes/deprecated-cozy.directive.ts
N/a
Moved content density directive warnings to the setter, instead of the constructor. This way it will only log warns if the directive was actually used and not just created. Directives are also provided and injected into documentation pages
=> chore(core): moved deprecated warnings to setter instead of constructor

apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.html, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.component.ts, apps/docs/src/app/core/component-docs/date-picker/date-picker-docs.module.ts, apps/docs/src/app/core/component-docs/date-picker/examples/date-picker-today-button-example.component.ts, libs/core/src/lib/date-picker/date-picker.component.html, libs/core/src/lib/date-picker/date-picker.component.spec.ts, libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/date-picker/date-picker.module.ts, libs/platform/src/lib/form/date-picker/date-picker.component.html, libs/platform/src/lib/form/date-picker/date-picker.component.ts
closes #8362 
Added Today Selection Button in the footer selects today's date in the system or user-preferred timezone and closes the DatePicker popover.
`Important:`
For date range it sets start and end both to today's date.
=> feat(core, platform): datepicker today button

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.spec.ts, libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
Refers to Kafka.
* calculations optimisation.
* flickering issue fix.
_Notice: scrollbars present for a moment._
https://user-images.githubusercontent.com/20265336/181748403-568fdf08-3f1a-4ea3-9a65-89c648ee46b0.mov
https://user-images.githubusercontent.com/20265336/181748437-f8b41c97-233d-4047-aef0-a2a5acf33c6d.mov
-   [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/0.36.0-Breaking-changes#fixed-card-layout-8476) 
_Notice: Relates only to unit testing._
=> fix(core): fixed card layout flickering issue

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.spec.ts, libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
This reverts commit 54e89a92813020f476dce25d73acaecc4559ec35.
Reverting to apply again because minor version haven't been promoted (because of typo `BREAKING CHANGE`**`S`**).
=> fix(core): revert "fix(core): fixed card layout flickering issue (#8476)"

libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
Removed property, which was deprecated 6 months ago
[BREAKING CHANGE: removed input searchTableDensity from value help dialog](https://github.com/SAP/fundamental-ngx/wiki/0.36.0-Breaking-changes#value-help-dialog-8477)
=> chore(platform): removed deprecated searchTableDensity input

karma.conf.js, libs/core/src/lib/bar/directives/bar-element.directive.spec.ts, libs/core/src/lib/card/card.component.spec.ts, libs/core/src/lib/dialog/dialog-header/dialog-header.component.html, libs/core/src/lib/flexible-column-layout/flexible-column-layout.component.html, libs/core/src/lib/menu/menu.module.ts, libs/core/src/lib/message-box/message-box-footer/message-box-footer.component.html, libs/core/src/lib/message-box/message-box-header/message-box-header.component.html, libs/core/src/lib/shellbar/shellbar-action/shellbar-action.component.html, libs/core/src/lib/tile/directives/tile.directives.spec.ts, libs/core/src/lib/toolbar/toolbar.component.spec.ts, libs/core/src/lib/upload-collection/upload-collection-item.directive.spec.ts
Reduced amount of logs in unit tests. Logs were caused by calling deprecated properties. Also since I was there, I removed deprecated properties from docs too. It was not mentioned anywhere and already stated in the docs that those inputs are removed, so not a big deal. I also added `spec` reporter to unit tests, so now we see a nice and clean list of tests that work and which do not
=> chore: reduced background noise in unit tests and made test results cleaner

libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.spec.ts, libs/core/src/lib/fixed-card-layout/fixed-card-layout.component.ts
**This pr applies changes from previously reverted (original) [PR](https://github.com/SAP/fundamental-ngx/pull/8476)**.
**Original one was reverted in that [PR](https://github.com/SAP/fundamental-ngx/pull/8494) because of incorrect applying**.
Refers to Kafka.
* calculations optimisation.
* flickering issue fix.
_Notice: scrollbars present for a moment._
https://user-images.githubusercontent.com/20265336/181748403-568fdf08-3f1a-4ea3-9a65-89c648ee46b0.mov
https://user-images.githubusercontent.com/20265336/181748437-f8b41c97-233d-4047-aef0-a2a5acf33c6d.mov
-   [X] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/0.36.0-Breaking-changes#fixed-card-layout-8476) 
_Notice: Relates only to unit testing._
=> fix(core): fixed card layout flickering issue (#8476)

libs/core/src/lib/list/list-item/list-item.component.ts
Adopting @g-cheishvili's comments from a PR that has been stuck in the stale loop for a while https://github.com/SAP/fundamental-ngx/pull/8271
Fixes an issue where checkboxes in list items would receive focus in addition to the list item itself.
=> fix(core): getters and setters for list-item checkboxes/radios to fix tab issue

libs/core/src/lib/table/table.component.ts
part of #8557 
Disable page scroll when user is navigating through a focusable table with up/down arrow keys
=> fix(core): prevent page scroll on up/down arrow key in table

apps/docs/src/app/core/component-docs/busy-indicator/busy-indicator-docs.component.ts, apps/docs/src/app/core/component-docs/busy-indicator/examples/busy-indicator-extended-example.component.html
part of #8557 
Removed common margin applied to all buttons of examples.
=> fix(docs): busy indicator - remove common margin for buttons in examples

libs/core/src/lib/timeline/services/position-strategies/base-strategy.ts
fixes #8576 
Fixes logic for splitting timeline nodes in half for double sided views when there is an even number of timeline nodes. Previous logic would put too many nodes on the first side, breaking positioning calculation.
Before:
After:
=> fix(core): logic for splitting timeline nodes in half

apps/docs/src/app/core/component-docs/table/examples/table-column-sorting-example.component.html, apps/docs/src/app/core/component-docs/table/examples/table-focusable-example/table-focusable-example.component.html, apps/docs/src/app/core/component-docs/table/table-docs.component.html, apps/docs/src/app/core/component-docs/table/table-docs.module.ts, libs/core/src/lib/table/directives/table-body.directive.ts, libs/core/src/lib/table/directives/table-cell.directive.ts, libs/core/src/lib/table/directives/table-row.directive.ts, libs/core/src/lib/table/fd-table.interface.ts, libs/core/src/lib/table/table.component.ts, libs/core/src/lib/utils/directives/initial-focus/initial-focus.directive.ts, libs/core/src/lib/utils/public_api.ts, libs/core/src/lib/utils/services/tabbable-element.service.ts
relates #8469 
Changed core table keyboard navigation. Extended documentation with explanation of the keys that are used for the navigation inside table's elements. …
=> feat(core): table keyboard navigation

libs/core/src/lib/combobox/combobox.component.html, libs/core/src/lib/combobox/combobox.component.ts
Closes #8228.
Combobox scroll strategy fix.
Ideally, the scroll strategy should be set to `BLOCK` the same as the default HTML select but it seems very buggy and doesn't respect when the scroll container if it's not a body. https://github.com/angular/components/issues/21195
So, the scroll strategy is set to `REPOSITION` but with the "close when scrolled out of viewport" flag enabled.
The issue about z-indexes probably should be fixed separately because it relates to our docs app and not any component. We have various z-indexes set for different components, and probably we have to review all those values.
https://user-images.githubusercontent.com/20265336/187691632-73ea3dfc-74d0-4909-b687-6f96b95f15a6.mov
=> fix(core): combobox scroll strategy

libs/core/src/lib/dialog/dialog.component.ts
=> fix(core): fix dialog positioning when hasBrackdrop is false

libs/core/src/lib/time/time-column/time-column.component.ts
part of #8557 
solves [this](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1247309526) : Wrong label for hours and seconds in time column.
=> fix(core): fix label for hour and sec

apps/docs/src/app/platform/component-docs/platform-display-list-item/platform-display-list-item-examples/platform-display-list-item-example.component.html, apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-example.component.html, apps/docs/src/app/platform/component-docs/platform-list/platform-list-examples/platform-list-with-group-header-example.component.html, apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-example.component.html, apps/docs/src/app/platform/component-docs/platform-standard-list-item/platform-standard-list-item-examples/platform-standard-list-item-with-group-header-example.component.html, libs/platform/src/lib/form/multi-input/multi-input.component.html, libs/platform/src/lib/list/list.component.html, libs/platform/src/lib/list/list.component.ts, libs/platform/src/lib/list/list.module.ts, libs/platform/src/lib/shared/domain/data-source.ts
closes #8629 
- Updated logic of setting rendered items to reflect new items coming from dataSource;
- Refactored component names and few input properties;
- Added missing imports/exports to the list module
-   [x] …
=> fix(platform): update items on new event

libs/docs/core/wizard/examples/wizard-example.component.scss
part of #8557
solves [this](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1216778888): Wizard example overlap
[Wizard Example](https://fundamental-ngx.netlify.app/#/core/wizard#customizable)
=> fix(docs): fix wizard example overlap

libs/core/src/lib/overflow-layout/overflow-layout.component.spec.ts, libs/core/src/lib/overflow-layout/overflow-layout.component.ts, libs/core/src/lib/overflow-layout/overflow-layout.service.ts
Refers to dxp/search/issues/556
* overflow layout edge case fixed when placed inside nested template directives (ngIf, ngFor, etc).
=> fix(core): overflow layout nested struct directives

apps/docs/project.json
@platon-rov suggested this change through review comment
Added hmr target. To use it you should just type `nx run docs:serve:hmr` . Deleted unused serve targets, which I suppose were for serving app in different languages
=> feat(docs): added hmr serve target

libs/core/src/lib/quick-view/quick-view-group-item-content/quick-view-group-item-content-element.directive.ts, libs/docs/core/quick-view/examples/quick-view-popover-example.component.html
part of defect hunting 94, this comment: https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215401360
Also relies on https://github.com/SAP/fundamental-styles/pull/3896
=> fix(core): quick view should not use fd-input and should be focus trapped in popovers

netlify.toml
`IMPORTANT` When merging this one setting 'Build image' should be changed to 'Ubuntu Focal 20.04 (default)' in netlify settings.
Relates to https://github.com/SAP/fundamental-ngx/issues/8758
Python version changed to 3.8 (default for ubuntu 20.04).
=> fix(docs): netlify update to ubuntu 20.04

libs/core/src/lib/popover/popover-body/popover-body.component.html, libs/core/src/lib/popover/popover-body/popover-body.component.scss, libs/core/src/lib/popover/popover.module.ts
Closes https://github.com/SAP/fundamental-ngx/issues/7445
Scrollbars for the popover body when it's too big for the viewport.
_Note: Firefox doesn't support custom scrollbars, default ones are shown._
=> fix(core): popover overflow

apps/docs/src/styles.scss
Part of #8557 
Solves one of [these](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1215609973): 
Removed black color from pre tag.
=> fix(docs): remove color from pre tag

libs/docs/core/menu/examples/menu-addon-example.component.scss
closes #8430 
Remove margin from example file.
RTL
RTL
=> fix(docs): fix wrong margin for icon in RTL menu

libs/core/src/lib/combobox/combobox.component.ts
closes #8655 
Issue was: Passing custom `@Input glyph` in combobox wasn't working.
=> fix(core): fix combobox glyph issue

libs/docs/platform/info-label/platform-info-label-docs-module.ts
closes #8798 
Added `currentComponentProvider` for  info-label.
=> fix(docs): fix broken platform docs of info-label

libs/core/src/lib/message-toast/message-toast.component.scss, libs/core/src/lib/pagination/pagination.component.scss, libs/core/src/lib/select/select.component.scss, libs/core/src/lib/slider/slider.component.scss, libs/core/src/lib/step-input/step-input.component.scss, libs/core/src/lib/table/table.component.scss, libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss, libs/fn/src/lib/slider/slider.component.scss, libs/platform/src/lib/search-field/search-field.component.scss, libs/platform/src/lib/table/table.component.scss
Closes none.
Previously we were hiding live announcer element only on the the docs app level, not on the component level. So anywhere on the client side this element was visible, here is the fix.
=> fix(core,platform): hiding live announcer element

libs/core/src/lib/multi-input/multi-input.component.scss
fixes none
Fixes an issue with multi-input that only became apparent with fundamental-styles v. 0.25.0-rc.31 but will be fixed in later styles versions. But regardless is unused code
screenshot:
=> fix(core): minor CSS bug that is only visible with certain styles RC

libs/core/src/lib/menu/menu.component.scss, libs/core/src/lib/menu/menu.component.ts
Closes https://github.com/SAP/fundamental-ngx/issues/8792.
Submenu overflow issue.
=> fix(core): submenu overflow

libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
closes #8756
Solved: `unread="true"` wasn't making list title bold in Standard list with navigation indicator.
First Item with `unread="true"`:
=> fix(platform): fix unread issue in standard list with nav indicator

libs/docs/core/datetime-picker/datetime-picker-docs.component.html, libs/docs/core/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.html, libs/docs/core/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts
Part of #8717 
This updates core's datetime picker documentation to show how to localize all child components of the DatetimePicker pattern component. See linked issue above for more details
=> docs(core): demonstrate how to update datetimepicker locale

libs/core/src/lib/calendar/calendar.component.ts
closes #8835 
fix: Year-range in calendar header wasn't changing according to years-grid.
=> fix(core): change year-range on next/previous button clicks in calendar

apps/docs/src/styles.scss
fixes none. Some additional updates to the documentation to make the API page look better in the dark modes
=> fix: the API documentation colors for dark modes

apps/docs/src/app/app.module.ts, apps/docs/src/fd-typedoc/assets/css/main.scss, apps/docs/src/styles.scss, libs/core/schematics/ng-add/schema.json, libs/core/src/lib/theming/standard-themes.ts, libs/core/src/lib/utils/services/themes.service.ts, libs/docs/core/feed-input/e2e/feed-input.e2e-spec.ts, libs/docs/platform/radio-group/e2e/radio-group.e2e-spec.ts, libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss, libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
align Theme's Names with the other technologies
- Replace `Fiori 3` with `Quartz`
- Add `Quarts` to `fiori 3` HC Themes
- Add `Horizon` to horizon themes
=> docs(core,platform): align Theme's Names with the other technologies

libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
fixes #8762 
When the user enters something into the multi-combobox that returns nothing from the datasource, the combobox input should return to its previous value.  There was some logic there previously to remove the last character when this happened, but this often failed due to a lifecycle issue, allowing the user to press the erroneous button twice to see it in the input. Also the previous logic did not account for copy/pastes
=> fix(platform): multi combobox bug where inputText is manipulated incorrectly

libs/core/src/lib/text/text.component.spec.ts, libs/core/src/lib/utils/directives/line-clamp/line-clamp.directive.ts
fixes #8867 
Fixes a bug where line clamp directive was not displaying "MORE" text when fd-text elements were placed inside the fd-layout-grid, until after a window resize.
Maybe this is not the best solution - I initially thought some sort of eventing (from line clamp to fd-text to fd-layout-grid, and back) could be more performant, but would introduce coupling between unrelated components. So I am open to suggestions.
=> fix(core): need to run setTimeout in line clamp logic to force recheck of parents

libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.ts, libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-step.component.ts, libs/platform/src/lib/wizard-generator/wizard-generator.service.ts
Refers to DXP.
Closes https://github.com/SAP/fundamental-ngx/issues/8728
Fix for the issue when hidden form groups being shown on the summary step and in the resulting object.
Prerequisite
=> fix(platform): wizard generator hidden form groups visible

e2e/tsconfig.json, e2e/wdio.base-config.js, libs/plugins/wdio/executors/utils/run-wdio.ts
Closes none.
Removing `cross-env` package usage from e2e ci workflow to get rid of the following error
```
sh: 1: cross-env: Permission denied
```
=> fix(e2e): removing cross-env from e2e workflow

libs/core/src/lib/datetime-picker/datetime-picker.component.html, libs/core/src/lib/menu/menu.component.scss, libs/core/src/lib/popover/popover-body/popover-body.component.html, libs/core/src/lib/popover/popover-body/popover-body.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/8893#issuecomment-1291088741
Solved popover arrow overflow.
Fixed double scrollbar for popover with list.
=> fix(core): solve popover arrow overflow

libs/core/src/lib/combobox/combobox.component.spec.ts, libs/core/src/lib/combobox/combobox.component.ts
closes #8858 
Set value to null on clear button in Combobox.
=> fix(core): combobox: set value to null on clear button

libs/platform/src/lib/form/select/select/select.component.html, libs/platform/src/lib/form/select/select/select.component.ts
closes #8801 
Platform: Fixed broken two-columns options in select.
=> fix(platform): fix broken two-columns options in select

libs/core/src/lib/segmented-button/segmented-button.component.ts
closes #8791 
Set touched state of segmented-button on click and  `space`/`enter `keydown.
Gets touched state on blur:
Gets touched state on click or  `space`/`enter `keydown:
=> fix(core): set touched state of segmented-button on click/key down

libs/core/src/lib/dialog/dialog.component.html, libs/core/src/lib/dialog/dialog.component.scss, libs/core/src/lib/dialog/dialog.component.spec.ts, libs/core/src/lib/dialog/utils/dialog-config.class.ts, libs/docs/core/dialog/e2e/dialog-contents.ts, libs/docs/core/dialog/e2e/dialog.e2e-spec.ts
Closes none.
In https://github.com/SAP/fundamental-styles/pull/3957 refactoring of the dialog was done, so we can get rid of some hardcoded styles.
=> fix(core): dialog's fund-styles refactoring adoption

libs/docs/fn/select/examples/select-example/select-editable-example-component.ts, libs/docs/fn/select/examples/select-example/select-editable-example.component.html, libs/docs/fn/select/examples/select-example/select-example-component.ts, libs/docs/fn/select/examples/select-example/select-example.component.html, libs/docs/fn/select/examples/select-example/select-forms-example.component.html, libs/docs/fn/select/examples/select-example/select-semantic-example.component.html, libs/fn/src/lib/select/option/option.component.html, libs/fn/src/lib/select/option/option.component.ts, libs/fn/src/lib/select/select-menu.directive.ts, libs/fn/src/lib/select/select.component.html, libs/fn/src/lib/select/select.component.scss, libs/fn/src/lib/select/select.component.ts, libs/fn/src/lib/select/select.interface.ts
closes #8138
Added [label] property to fn-option.
Was showing value of selected option in input-field.
=> fix(fn): show selected option label in select

libs/core/schematics/migrations/migration-0-37/index.ts, libs/core/schematics/ng-add/index.ts, libs/core/src/lib/ng-package.json, libs/core/src/lib/package.json, libs/cx/src/lib/package.json, libs/datetime-adapter/package.json, libs/moment-adapter/package.json, libs/platform/src/lib/package.json
Closes none, 
Follows-up https://github.com/SAP/fundamental-ngx/pull/8479
* fix: schematics migration issue when previously set theme CSS files hasn't been removed.
* fix: issue when `fundamental-ngx-core.css` hasn't been included in the build.
* fix: deps issue.
*Deps error*
```
./node_modules/@fundamental-ngx/core/node_modules/@angular/platform-browser/fesm2020/platform-browser.mjs:1318:9-38 - Error: export 'ɵinternalBootstrapApplication' (imported as 'ɵinternalBootstrapApplication') was not found in '@angular/core' (possible exports: ANALYZE_FOR_ENTRY_COMPONENTS...
```
=> fix(core,platform): schematics and deps

package.json, yarn.lock
Closes none.
Recently a new minor version of fund-styles was released, so we have to bump the version manually to process breaking changes.
Breaking changes were related to applying `fd-button--toggled` in segmented button component. Luckily, we're already doing things in the right way, nothing needed to be updated.
=> chore(core,platform): bump styles to 0.26.0-rc.5

libs/core/src/lib/carousel/carousel-item/carousel-item.component.ts, libs/core/src/lib/carousel/carousel.component.ts, libs/platform/src/lib/table/table.component.spec.ts
closes #8955 
Added delay when zone is stable.
Original issue was appearing when parent component which included carousel used default change detection strategy.
- …
=> fix(core): fix expression changed error for carousel

libs/core/src/lib/action-sheet/action-sheet.component.html, libs/core/src/lib/menu/menu.component.html, libs/core/src/lib/menu/menu.component.scss, libs/core/src/lib/menu/menu.component.ts, libs/core/src/lib/popover/base/base-popover.class.ts, libs/core/src/lib/popover/popover-body/popover-body.component.html, libs/core/src/lib/popover/popover-body/popover-body.component.ts, libs/core/src/lib/popover/popover-service/popover.service.ts, libs/docs/core/menu/examples/menu-scrollbar-example.component.html, libs/docs/core/menu/examples/menu-scrollbar-example.component.ts, libs/docs/core/menu/menu-docs.component.html, libs/docs/core/menu/menu-docs.component.ts, libs/docs/core/menu/menu-docs.module.ts, libs/platform/src/lib/message-popover/message-popover.component.html
closes #8929 
closes #8969
feat: Added scrollbar to Menu. (https://github.com/SAP/fundamental-ngx/pull/8964/commits/3e8624c3a5edddf0ad83bf0147611c8e6ad8c251)
feat: Added a property to popover to make `fd-scrollbar` `tabbable` or not. (https://github.com/SAP/fundamental-ngx/pull/8964/commits/84b0f9b6e70c7de2e929fd380efa8a16e948a082)
fix: Made `fd-scrollbar` un-tabbable for popover in Action sheet. So it can focus first element on open. (https://github.com/SAP/fundamental-ngx/pull/8964/commits/2ffb57107b13c7bb59ba6ba6d10311ba58eeb2b0)
fix: Merged logic from https://github.com/SAP/fundamental-ngx/pull/8926 that make use of `focusAutoCapture` to focus first menu-item in Menu instead using `initial-focus` directive, (https://github.com/SAP/fundamental-ngx/pull/8964/commits/7d1317b79094156f2e4f0 …
=> feat(core): add scrollbar to menu

libs/core/src/lib/tabs/tab-list.component.scss, libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
PR in styles https://github.com/SAP/fundamental-styles/pull/4058
Closes https://github.com/SAP/fundamental-ngx/issues/8011
Refers to `dxp/organization/issues/87`
Tabs in fdp dynamic page padding issue fix.
=> fix(platform): dynamic page tabs padding

libs/core/src/lib/vertical-navigation/vertical-navigation.component.scss
Closes #9021.
Quick fix for the vertical nav component to unblock release.
=> fix(core): vertical nav regression

libs/docs/platform/list/examples/platform-list-border-less-example.component.html, libs/docs/platform/list/examples/platform-list-border-less-example.component.ts, libs/platform/src/lib/list/list.component.ts, libs/platform/src/lib/shared/domain/data-source.ts
closes #8996
`ListDataSource` extends from `ComboBoxDataSource`, which would add limitation to the items. Now ListDataSource is considered to have a limitless amount of the items. If chunking is needed, list has `itemSize`, which will load only certain amount of items
=> fix(platform): fixed data source limitation of 5 items in the list

libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts, libs/platform/src/lib/list/base-list-item.ts, libs/platform/src/lib/list/fdpListComponent.token.ts, libs/platform/src/lib/list/list.component.ts, libs/platform/src/lib/list/public_api.ts
closes #8847
List item's modes were having late detection triggers, because ordinary property changes through direct modification do not trigger re-render.
=> fix(platform): fixed list item change detection latency

libs/core/src/lib/select/option/option.component.html, libs/core/src/lib/select/select.component.html, libs/core/src/lib/select/select.component.scss, libs/core/src/lib/select/select.component.spec.ts, libs/core/src/lib/select/select.component.ts, libs/docs/core/select/select-docs.module.ts
Closes https://github.com/SAP/fundamental-ngx/issues/8995
Refers to `dxp/backlog/issues/720`
Select component fixes & refactoring to be able to set custom width easily.
**Before**
```CSS
.my-custom-select {
width: 500px;
}
::ng-deep .fd-select .fd-popover-custom {
min-width: 100%;
}
```
**After**
```CSS
.my-custom-select {
width: 500px;
}
```
=> fix(core): select custom width & refactoring

package.json, yarn.lock
None
This package was not used anywhere and last update for it was 3 years ago. It depends on electron 2(!!!!). It has to go
=> chore(deps-dev): removed wdio-html-format-reporter from dependencies

libs/docs/shared/src/lib/core-helpers/code-example/example-file.ts, libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz.service.ts, libs/docs/shared/src/lib/getAsset.ts
closes #5351
Finally, here it is. Now you can use the `pure` type in examples and those example files will not end up in the module
=> feat(docs): added pure example file type

versions.json
Closes none.
"Update `versions.json`" workflow was disabled because it was broken, but then when I fixed it, I forgot to enable it. Here are versions we released which are not present in `versions.json` because workflow was disabled. From now, updating `versions.json` will be done automatically when we publish a new stable release.
=> chore(docs): update versions.json

apps/docs/src/index.html, e2e/wdio/core-base-component.po.ts, e2e/wdio/platform-base-component.po.ts, libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts, libs/docs/shared/src/lib/getAsset.ts, package.json
Removed `fundamental-ngx` prefix so now nothing(firebase, netlify, gh pages) has prefix. Fixed URLs to example files so that they are coming from `currentUrl/` and not from `/`. Removed base URL from e2e test URLs
=> fix(docs): fixed asset urls so now links work properly

libs/docs/core/flexible-column-layout/e2e/flexible-column-layout.e2e-spec.ts, nx.json
closes probably none
Added previous default behavior. When package json is changed(version changed for example), build should begin from scratch
=> fix: invalidate nx cache on package.json change

.github/actions/npm-publish/index.js, .github/workflows/create-hotfix.yml
closes none hopefully
- NPM publish sometimes would fail because it encountered 402 from npm. Public access fixes that
- Previously NPM publish would fail silently, without causing breaking of the entire pipeline, but looks like that is not a good way. So now I added retry logic in case of failure
- Hotfix latest publish was lacking the GH pages deploy script
=> fix(ci): npm publish always set to public and added gh publish for hotfix latest

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts, libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.html, libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.ts, libs/docs/core/multi-input/multi-input-docs.component.html, libs/docs/core/multi-input/multi-input-docs.component.ts, libs/docs/core/multi-input/multi-input-docs.module.ts
closes #9047 
Changed `bodyMaxWidth` signature. Not it accepts: 'none' | 'container' | 'number'.
If none selected, width is not limited.
If container selected, width will be limited by the width of the multi input component.
If number passed, width will be limited by this number in px.
-   [x] check …
=> feat(core): multi input dropdown width

tools/generators/sap-component/index.ts, tools/generators/utils/ast-utils.ts, tools/generators/utils/linting.ts
After migration to 15 version, component generator stopped working.
This fixes the issue.
Migrated from running schematics to running generators.
There was incompatible Tree types netween nrwl and angular, so had to rewrite some functions to work with nrwl's tree
=> fix: component generator fix

libs/core/src/lib/breadcrumb/breadcrumb.component.html
Closes none.
Breadcrumb overflow icon to better match with specs.
=> fix(core): breadcrumb overflow icon

libs/core/src/lib/select/select.component.html, libs/docs/platform/select/e2e/select.e2e-spec.ts
closes #9024
removed not recommended attribute from select div
=> fix: removed not recommended aria attribute on `div`

libs/core/schematics/add-dependencies/index.ts
closes none
i18n package should be added alongside core, so when there are both platform and core packages in client's application, without this, with npm duplications of the i18n package occur and it messes up with angular DI, as a result platform modules, which use i18n fail to initialize
=> fix(core): added i18n package installation in core's ng-add

libs/i18n/project.json
closes #9138
This is a follow up PR to https://github.com/SAP/fundamental-ngx/pull/9144 and https://github.com/SAP/fundamental-ngx/pull/9145
Set `updateBuildableProjectDepsInPackageJson` to `false`. Previously deps zonejs and platform-browser dependencies were ending up in output package.json, because they were mentioned in the files outside of src and in testing files.
=> fix: fixed i18n package dependencies

libs/core/src/lib/dynamic-page/dynamic-page.component.scss
fixes #9152 
Note that the original issue isn't apparent until clicking on the dynamic page content.
=> fix(core): dynamic footer z-index must be higher than that of fd-scrollbar

libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-basic-example.component.html, libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-basic-example.component.ts, libs/platform/src/lib/smart-filter-bar/smart-filter-bar.class.ts, libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.ts
closes #9143 
Added new events: `smartFiltersApplied` and `searchInputChanged`.
`smartFiltersApplied` emitted when 'Go' button clicked.
`searchInputChanged` emitted when `inputChange` event of search field is emitted.
`smartFiltersChanged` is now triggered everytime when filters model has been updated without 'GO' button click.
2. …
=> feat(platform): change and apply smart filter bar events

libs/core/src/lib/pagination/pagination.component.html, libs/core/src/lib/pagination/pagination.component.ts
fixes none
Mobile pagination was showing the total number of items in a pagination component rather than total pages
=> fix(core): pagination mobile displaying total items count instead of total pages

libs/core/src/lib/nested-list/nested-list-directives.spec.ts, libs/core/src/lib/nested-list/nested-list-directives.ts, libs/core/src/lib/nested-list/nested-list.module.ts, libs/cx/src/lib/nested-list/nested-list-directives.spec.ts, libs/cx/src/lib/nested-list/nested-list-directives.ts, libs/cx/src/lib/nested-list/nested-list.module.ts, libs/docs/core/shared/src/lib/api-files.ts
fixes #8902 
<code>NestedListIconDirective</code> becomes <code>NestedListIconComponent</code> and extends <code>IconComponent</code>, allowing devs to pass a <code>[font]</code> input to change the icon set. No breaking changes to existing templates
=> fix(core,cx): nested list icon should extend fd-icon

.github/workflows/on-pull-request.yml
If firebase deploy fails for some reason, agents should be stopped, otherwise they will go on timeout, because local e2e tests do not require DTE
=> fix(ci): fixed agents timeout when running e2e tests on local

libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts, libs/core/src/lib/calendar/calendar.component.spec.ts, libs/core/src/lib/calendar/calendar.component.ts, libs/core/src/lib/date-picker/date-picker.component.ts
closes #9060 
The calendar would alter date-range values, as a result, there was no way of knowing whether or not the user had finished selecting dates, and also date-picker was not respecting `closeOnDateChoose` input.
=> fix(core): date-picker respects closeOnDateChoose input now

libs/core/schematics/add-theming/index.ts
This is a patch for type issues. Source file and Node are compatible for that function in reality. Also same is true for ConstructorDeclaration, if node with that kind is found, it is ConstructorDeclaration
=> fix(core): schematics type incompatibility

libs/platform/src/lib/table/table.component.ts
part of #9248
On our current build, go to the platform table custom columns example, which has a column where the cells have input components. Note that you can not press space to enter a space character in the input
=> fix(platform): can not enter space characters in inputs inside table cells

package.json, yarn.lock
fixes none
Fixes the `Error: Nx no longer supports using positional arguments for base and head. Please use --base and --head instead.` we're all seeing
=> fix: update nx/lint versions to fix commit error

libs/core/src/lib/avatar/avatar.component.ts, libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts, libs/core/src/lib/nested-list/nested-list-directives.ts, libs/cx/src/lib/nested-list/nested-list-directives.ts, libs/fn/src/lib/avatar/avatar.component.ts, libs/platform/src/lib/form/multi-input/multi-input.component.ts, libs/platform/src/lib/table/utils.ts
Closes none.
`textContent` causes reflow and its performance a way worse than `textContent`s. In our cases, usage of `textContent` should not cause breaking changes or unpredicted behavior.
*Platform Table doc page loading*
=> fix(core,cx,fn,platform): textContent instead of innerText for matter of performance

libs/core/src/lib/tabs/tab-list.component.ts
closes #9385 
When clicking on the menu item under  "More" - collapsed Overflow tab(click icon under tab 3 menu item, screenshot below), this menu stays open. Should provide a way(like calling tab.menu.close) to close it if needed.
No any UI change. Just expose the overflow menu so that menu.close() can be called to close the menu in event handler code.
-   [na] tests for the changes that have been done
-   [na] Run npm run build-pack-library and test in external application
-   [na] update `README.md`
-   [na] [Breaking Changes …
=> feat(core): allowing close the overflowed tab menu under More when clicked

libs/docs/platform/multi-input/e2e/multi-input.e2e-spec.ts, libs/platform/src/lib/form/multi-input/base-multi-input.ts, libs/platform/src/lib/form/multi-input/multi-input.component.html, libs/platform/src/lib/form/multi-input/multi-input.component.ts, libs/platform/src/lib/list/base-list-item.ts, libs/platform/src/lib/list/list.component.ts, libs/platform/src/lib/list/object-list-item/object-list-item.component.html, libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
relates #8985
- Fixed `reset` functionality with reactive forms example;
- Fixed focused item when dropdown is opened;
- Fixed issue with focusing the checkbox;
=> fix(platform): multi-input bugfixes

libs/core/src/lib/multi-combobox/multi-combobox.component.html, libs/core/src/lib/multi-combobox/multi-combobox.component.ts, libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.spec.ts, libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts, libs/docs/core/multi-input/examples/multi-input-addon-clicked-example/multi-input-addon-clicked-example.component.html, libs/docs/core/multi-input/examples/multi-input-addon-clicked-example/multi-input-addon-clicked-example.component.ts, libs/docs/core/multi-input/multi-input-docs.component.html, libs/docs/core/multi-input/multi-input-docs.component.ts, libs/docs/core/multi-input/multi-input-docs.module.ts, libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html, libs/platform/src/lib/form/multi-input/base-multi-input.ts, libs/platform/src/lib/form/multi-input/multi-input.component.html, libs/platform/src/lib/form/multi-input/multi-input.component.ts
fixes none
Adds documentation for fd-multi-input addOnButtonClicked event. Also applies to fdp-multi-input, fd-multi-combobox, and fdp-multi-combobox
Also fixes a bug where multi-input mobile mode would automatically open its dialog during ngOnInit, then hide it, which would effectively create an invisible focus trap, so tab keys would not work on any page which creates a mobile fd-multi-input
=> fix: documentation for multi-input addon button events

libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html
remove version selector
we will enable it once we find a working alternative
=> docs(docs): remove version selector

libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-custom-filter-example.component.ts, libs/platform/src/lib/form/form-generator/base-dynamic-form-generator-control.ts, libs/platform/src/lib/form/form-generator/dynamic-form-control.directive.ts, libs/platform/src/lib/form/form-generator/dynamic-form-generator-checkbox/dynamic-form-generator-checkbox.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-datepicker/dynamic-form-generator-datepicker.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-editor/dynamic-form-generator-editor.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-input/dynamic-form-generator-input.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-multi-input/dynamic-form-generator-multi-input.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-radio/dynamic-form-generator-radio.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-select/dynamic-form-generator-select.component.html, libs/platform/src/lib/form/form-generator/dynamic-form-generator-switch/dynamic-form-generator-switch.component.html, libs/platform/src/lib/form/form-generator/form-generator-field/form-generator-field.component.html, libs/platform/src/lib/form/form-generator/interfaces/dynamic-form-item.ts, libs/platform/src/lib/form/form-group/form-group.component.ts, libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-condition-field/smart-filter-bar-condition-field.component.html
closes #8729 
Added `id` property to the `BaseDynamicFormGeneratorControlInterface` and made dynamic fields respect that. Previously `name` would have been used as an `id` for control fields, now users can use different id for their DOM elements.
As before, `fdp-form-label-${id || name}` is used for labels, `fdp-form-label-content-${id || name}` is used for label contents and additionally `id || name` is now used for the form controls themselves. Placement and usage of that passed id depend on the control itself, but provided controls are attaching those ids to the correct places.
Custom controls will have to implement that by themselves, examples that are given for custom controls are fixed
=> feat(platform): added id property to form generator items

libs/cdk/src/lib/utils/directives/initial-focus/initial-focus.directive.ts, libs/core/src/lib/token/token.component.ts, libs/core/src/lib/token/tokenizer.component.ts, libs/docs/platform/multi-input/examples/platform-multi-input-complex-example.component.ts, libs/docs/platform/multi-input/examples/platform-multi-input-decline-example.component.ts, libs/docs/platform/multi-input/examples/platform-multi-input-disabled.component.html, libs/docs/platform/multi-input/examples/platform-multi-input-disabled.component.ts, libs/docs/platform/multi-input/examples/platform-multi-input-grouped-example.component.ts, libs/docs/platform/multi-input/examples/platform-multi-input-loading-example.component.html, libs/docs/platform/multi-input/platform-multi-input-docs.component.html, libs/docs/shared/src/lib/core-helpers/component-example/component-example.component.ts, libs/docs/shared/src/lib/core-helpers/directionality/directionality.component.ts, libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.ts, libs/platform/src/lib/form/multi-input/base-multi-input.ts, libs/platform/src/lib/form/multi-input/multi-input.component.ts
fixes #9226
- Fixed token `ExpressionChangedAfterItHasBeenCheckedError` error;
- Fixed initial focus `ExpressionChangedAfterItHasBeenCheckedError`;
- Added couple of `ChangeDetectionStrategy.OnPush` to documentation components;
=> fix(platform): multi input dh fixes

libs/docs/core/dialog/examples/auto-label/auto-label-dialog-example.component.html, libs/docs/core/dialog/examples/component-based/dialog-example.component.ts, libs/docs/core/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html, libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.html, libs/docs/core/dialog/examples/dialog-configuration/dialog-configuration-example.component.html, libs/docs/core/dialog/examples/dialog-form/form-dialog-example.component.html, libs/docs/core/dialog/examples/dialog-inner-popover/dialog-inner-popover.component.ts, libs/docs/core/dialog/examples/dialog-mobile/dialog-mobile-example.component.html, libs/docs/core/dialog/examples/dialog-object-example/dialog-object-example.component.html, libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.html, libs/docs/core/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, libs/docs/core/dialog/examples/stacked-dialogs/second-dialog-example.component.ts, libs/docs/core/dialog/examples/template-based/template-based-dialog-example.component.html
part of #9228
Dialog examples had incorrect initial focus targets, targeting close button
=> fix(docs): core dialog examples initial focus targets

libs/core/src/lib/scrollbar/scrollbar.directive.ts, libs/docs/platform/menu/examples/platform-menu-scrolling-example.component.html, libs/docs/platform/menu/platform-menu-docs.component.html, libs/docs/platform/menu/platform-menu.module.ts
part of #9228 
When you have a menu or something which needs repositioning inside the scrollable area, you need to specify cdkScrollable for the scrollable area. So why not include it in fdScrollbar and alongside styles, functionality will also be included
=> feat(core): scrollbar uses cdk scrollable

libs/core/src/lib/multi-combobox/multi-combobox.component.html, libs/core/src/lib/multi-combobox/multi-combobox.component.spec.ts, libs/core/src/lib/multi-combobox/multi-combobox.component.ts, libs/core/src/lib/multi-input/multi-input.component.spec.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/docs/core/multi-input/examples/multi-input-addon-clicked-example/multi-input-addon-clicked-example.component.html, libs/docs/core/multi-input/multi-input-docs.component.html, libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts, libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts, libs/platform/src/lib/form/multi-input/base-multi-input.ts, libs/platform/src/lib/form/multi-input/multi-input.component.spec.ts, libs/platform/src/lib/form/multi-input/multi-input.component.ts
fixes none
Adds an input `openDropdownOnAddOnClicked` which allows the developer to specify whether the dropdown list should open for multi-input and multi-combobox components when the addon button is clicked. Default is true. Should be useful when developer is handling `addOnButtonClicked` events
=> fix(core,platform): openDropdownOnAddOnClicked event for multi components 

libs/core/src/lib/form/form-control/form-control.component.ts, libs/platform/src/lib/form/input/input.component.html
fixes #9358 
Fixes a bug where aria-label was not being applied to fdp-input
=> fix: aria-label not being properly applied to fdp-input

libs/docs/core/calendar/e2e/calendar.e2e-spec.ts, libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz-dependencies.ts, libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz-module-wrapper.ts
Closes https://github.com/SAP/fundamental-ngx/issues/9267
@fundamental-ngx/cdk added to stackblitz deps
This fixes like 80% of examples, the rest is broken because some files not being passed to stackblitz, read more here https://github.com/SAP/fundamental-ngx/issues/9460.
=> fix(docs): @fundamental-ngx/cdk added to stackblitz deps

libs/docs/core/table/examples/table-column-sorting-example.component.html, libs/docs/core/table/examples/table-toolbar-example.component.html, libs/docs/core/table/table-docs.module.ts, libs/docs/platform/table/e2e/table.po.ts, libs/docs/platform/table/examples/platform-table-default-example.component.html, libs/docs/platform/table/platform-table-docs.component.html, libs/docs/platform/table/platform-table-docs.component.ts, libs/docs/platform/table/platform-table.module.ts, libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
=> fix(core,platform): table toolbar title updates

libs/docs/platform/list/examples/platform-list-border-less-example.component.ts, libs/platform/src/lib/list/list.component.ts
closes #9315 
- Changed default ItemSize to Infinity (no limit);
- Updated match params to reflect itemSize property;
=> fix(platform): dont limit list items rendering if itemSize is empty

libs/core/src/lib/multi-combobox/multi-combobox.component.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts, libs/platform/src/lib/form/multi-input/base-multi-input.ts, libs/platform/src/lib/form/multi-input/multi-input.component.ts
fixes none
When any multi-input/multi-combobox is open and the user has `[openDropdownOnAddOnClicked]="false"`, if the dropdown is open and they click the addon, we should still close the dropdown. Input specifies "open" not toggle
=> fix(core,platform): addon button should always close popover if it is open despite inputs

libs/docs/platform/table/e2e/table-contents.ts, libs/docs/platform/table/e2e/table.e2e-spec.ts, libs/docs/platform/table/examples/platform-table-freezable-example.component.html, libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.scss, libs/platform/src/lib/table/table.component.ts
fixes #9492 
Previously if a non-frozen table cell was partially obstructed by a frozen one, the focus for the entire non-frozen cell was still visible. Also, if a non-frozen cell was entirely obstructed by a frozen one and was navigated via keyboard, the cell would not be scrolled to, and it would appear as though focus was lost (when it was simply on the hidden element). This fixes both issues
https://user-images.githubusercontent.com/2471874/224383490-f335beac-be47-4394-a032-203b12b0d898.mov
=> fix(platform): table with freezing columns hidden cell issues

libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
fix special calendar e2e - when we check the special days the first check should validate whether the 7th day after today is special, and that the day after that should not be special
=> test(core): fix special calendar e2e

libs/cdk/src/lib/utils/directives/line-clamp/line-clamp.directive.ts
When `fd-text` is expandable, and the text length changes from exceeded long to short (for example, `maxLines` is set to 3 and the text changed from 4 lines to 1 line), the `MORE/LESS` button won't disappear. Vice versa, the `MORE/LESS` button won't show when the text changes from short to long.
stackblitz to reproduce: https://stackblitz.com/edit/angular-2miaxw?file=src/app/text-expandable.component.html
This fix makes it to check the line count every time when the text changes, this makes the `MORE/LESS` button to show/disappear properly.
=> fix(core): fd-text does not show/hide 'MORE/LESS' button correctly when text length changes

libs/i18n/src/lib/languages/albanian.ts, libs/i18n/src/lib/languages/arabic.ts, libs/i18n/src/lib/languages/belarusian.ts, libs/i18n/src/lib/languages/bulgarian.ts, libs/i18n/src/lib/languages/chinese.ts, libs/i18n/src/lib/languages/croatian.ts, libs/i18n/src/lib/languages/czech.ts, libs/i18n/src/lib/languages/english.ts, libs/i18n/src/lib/languages/french.ts, libs/i18n/src/lib/languages/georgian.ts, libs/i18n/src/lib/languages/german.ts, libs/i18n/src/lib/languages/hebrew.ts, libs/i18n/src/lib/languages/hindi.ts, libs/i18n/src/lib/languages/italian.ts, libs/i18n/src/lib/languages/polish.ts, libs/i18n/src/lib/languages/portuguese.ts, libs/i18n/src/lib/languages/romanian.ts, libs/i18n/src/lib/languages/russian.ts, libs/i18n/src/lib/languages/sinhala.ts, libs/i18n/src/lib/languages/spanish.ts, libs/i18n/src/lib/languages/turkish.ts, libs/i18n/src/lib/languages/ukrainian.ts, libs/i18n/src/lib/models/lang.ts, libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html, libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.spec.ts
As part of this changed other actions were updated to match this requirement
closes #9551
Introduced additional attributes: `title` and `aria-label`. 3 other actions updated as well to match this requirement. 
As part of this change i18n files updated as well. languages are defaulted to English and some of them are already translated (en, de, cz)
=> fix(platform): missing tooltip - aria label for table toolbar actions

libs/core/src/lib/breadcrumb/breadcrumb.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.spec.ts, libs/core/src/lib/breadcrumb/breadcrumb.module.ts, libs/i18n/src/lib/languages/albanian.ts, libs/i18n/src/lib/languages/arabic.ts, libs/i18n/src/lib/languages/belarusian.ts, libs/i18n/src/lib/languages/bulgarian.ts, libs/i18n/src/lib/languages/chinese.ts, libs/i18n/src/lib/languages/croatian.ts, libs/i18n/src/lib/languages/czech.ts, libs/i18n/src/lib/languages/english.ts, libs/i18n/src/lib/languages/french.ts, libs/i18n/src/lib/languages/georgian.ts, libs/i18n/src/lib/languages/german.ts, libs/i18n/src/lib/languages/hebrew.ts, libs/i18n/src/lib/languages/hindi.ts, libs/i18n/src/lib/languages/italian.ts, libs/i18n/src/lib/languages/polish.ts, libs/i18n/src/lib/languages/portuguese.ts, libs/i18n/src/lib/languages/romanian.ts, libs/i18n/src/lib/languages/russian.ts, libs/i18n/src/lib/languages/sinhala.ts, libs/i18n/src/lib/languages/spanish.ts, libs/i18n/src/lib/languages/turkish.ts, libs/i18n/src/lib/languages/ukrainian.ts, libs/i18n/src/lib/models/lang.ts
closes #9534
Updated wrapping link to have proper aria attribute and added title to the `more` icon so it shows some tooltip .  
The `"More"` also added to the i18n files. 
-   [X] the commit message(s) follows the guideline:
-   [X ] tests for the changes that have been done
-   [X ] all items on the PR Review Checklist are addressed :
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
=> fix(core): no tooltip for breadcrumb when overflow dots are shown

libs/core/src/lib/action-bar/action-bar.component.ts, libs/docs/core/action-bar/action-bar-header/action-bar-header.component.html, libs/docs/platform/action-bar/platform-action-bar-header/platform-action-bar-header.component.html, libs/docs/platform/approval-flow/platform-approval-flow-header/platform-approval-flow-header.component.html, libs/docs/platform/page-footer/platform-page-footer-header/platform-page-footer-header.component.html, libs/docs/platform/thumbnail/platform-thumbnail-header/platform-thumbnail-header.component.html, libs/docs/platform/upload-collection/platform-upload-collection-header/platform-upload-collection-header.component.html, libs/platform/src/lib/action-bar/action-bar.component.ts, libs/platform/src/lib/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts, libs/platform/src/lib/approval-flow/approval-flow-approver-details/approval-flow-approver-details.component.ts, libs/platform/src/lib/approval-flow/approval-flow-messages/approval-flow-messages.component.ts, libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.ts, libs/platform/src/lib/approval-flow/approval-flow-select-type/approval-flow-select-type.component.ts, libs/platform/src/lib/approval-flow/approval-flow-team-list/approval-flow-team-list.component.ts, libs/platform/src/lib/approval-flow/approval-flow-toolbar-actions/approval-flow-toolbar-actions.component.ts, libs/platform/src/lib/approval-flow/approval-flow-user-details/approval-flow-user-details.component.ts, libs/platform/src/lib/approval-flow/approval-flow-user-list/approval-flow-user-list.component.ts, libs/platform/src/lib/approval-flow/approval-flow.component.ts, libs/platform/src/lib/page-footer/page-footer.component.ts, libs/platform/src/lib/thumbnail/thumbnail-details/thumbnail-details.component.ts, libs/platform/src/lib/thumbnail/thumbnail-image/thumbnail-image.component.ts, libs/platform/src/lib/thumbnail/thumbnail.component.ts, libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.ts
deprecate unmaintained Ariba specific components(updated documentation too)
- ActionMenu (core and platform)
- ApprovalFlow (platform)
- Page Footer (platform)
- Thumbnail (platform)
- UploadCollection (platform)
=> chore(core,platform): deprecate unmaintained Ariba specific components

libs/core/src/lib/button/base-button.ts, libs/core/src/lib/segmented-button/segmented-button.component.spec.ts, libs/core/src/lib/segmented-button/segmented-button.component.ts
closes #9633
- Simplified change detection;
- Use `asyncScheduler` for triggering the callback function when buttons being changed; …
=> fix(core): simplify change detection for segmented button

libs/platform/src/lib/search-field/search-field.component.html
closes #9559 
The inputText value of ```fdp-search-field``` is now being populated when selecting an item via the Enter key in the suggestion dropdown, even when wrapped by a ```form``` tag. This is done by preventing the default behaviour of the browser when handling the event:
```(keydown.enter)="onItemClick(value); $event.preventDefault()"```
Additionally, the browser's default autocomplete function is silenced for the ```<input>``` element, as ```fdp-search-field``` has its own autocomplete function.
=> fix(platform): search field input value updated when used in form tag

libs/platform/src/lib/table/models/table-rows-rearrange-event.model.ts, libs/platform/src/lib/table/table.component.ts
closes #9665
Added additional information regarding drop row event such as:
insertAt: before or after;
mode: shift or group;
dropRow: row that dragged row was dropped on
=> fix(platform): extend TableRowsRearrangeEvent with new data

libs/core/src/lib/overflow-layout/directives/overflow-item-ref.directive.ts, libs/core/src/lib/overflow-layout/directives/overflow-layout-item.directive.ts, libs/core/src/lib/overflow-layout/interfaces/overflow-item-ref.interface.ts, libs/core/src/lib/overflow-layout/overflow-layout.service.ts
closes #9530 
- Fixed overflow layout calculation mechanizm;
- Fixed issue when directive was refering to detached html element causing incorrect width calculation
- …
=> fix(core): fix overflow layout calculation

libs/platform/src/lib/table/components/table-cell-content/table-cell-content.component.html, libs/platform/src/lib/table/components/table-cell-content/table-cell-content.component.ts, libs/platform/src/lib/table/table.component.html
fixes none
Change detection issue with the the expanded/collapsed icon not updating and the `[class.fd-table__row--draggable]="enableRowReordering && _rowsDraggable"` addition fixes the mouse cursor on draggable child items
=> fix(platform): minor table visual issues

libs/cdk/src/lib/utils/services/resize-observer.service.ts, libs/cdk/src/lib/utils/utils.module.ts
related to https://github.com/SAP/fundamental-ngx/issues/9361#issuecomment-1508931202
- Resize observer was cleaned up prematurely
- Breakpoint directive was not exported and as a result the examples on stackblitz might not have worked in some cases
=> fix(cdk): resize observer cleanup and breakpoint directive export absence

libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html, libs/docs/platform/table/e2e/table-contents.ts, libs/docs/platform/table/examples/platform-table-p13-columns-example.component.html, libs/platform/src/lib/table/components/table-column/table-column.component.ts, libs/platform/src/lib/table/components/table-column/table-column.ts, libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.spec.ts, libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
Introducing new input property which removes column from the P13n list
closes #9520
Introduced new `disableP13n` property on the `TableColum` that excludes columns from P13n Dialog. By default all columns are included.
=> fix(platform): exclude columns from p13n dialog

apps/docs/project.json
closes #9724 for good
Even though commands themselves were cached, the root command was not properly saved and after an RC, release is exactly the same contents, so it was not triggered as it should have been
=> fix(docs): api absence in prod builds

libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss
fixes none. quick docs thing that's been bothering me
before:
after:
=> fix(docs): background color on the search input in side nav

libs/core/src/lib/dialog/base/dialog-base.class.ts, libs/core/src/lib/dialog/dialog.component.spec.ts, libs/core/src/lib/message-box/message-box.component.spec.ts
fixes #9794 
Dialog was previously using `keyup` which cannot be prevented coming from focusable item's `keydown`. Need to use `keydown` for dialog escape
=> fix(core): escape key when using focusable grid closes dialog

libs/docs/platform/table/platform-table-docs.component.html, libs/platform/src/lib/table/table.component.html
fixes #9964 
Fixes an accessibility issue where cells that can't be clicked to expand the row still had aria-expanded attribute. Also a doc typo
=> fix(platform): do not set aria-expanded for table cells that do not expand

libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss, libs/docs/shared/src/lib/documentation-base.component.scss
fixes none
A user stumbled across this issue when using the JAWS screenreader: "whenever focus goes to the tooltip in linear reading mode, the screen goes blank."
Which I think is actually caused by these styles in the documentation somehow. So I'm removing those as they don't seem to really do anything, unless anyone objects
=> fix(docs): sidebar container css bug

libs/platform/src/lib/table/table.component.ts
=> fix(platform): if entire table row is not focusable, focus first cell

libs/core/src/lib/multi-combobox/multi-combobox.component.html, libs/core/src/lib/multi-combobox/multi-combobox.component.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/docs/core/multi-input/examples/multi-input-mobile-example/multi-input-mobile-example.component.html
part of #9236 
multi-combobox and multi-input mobile mode - removing tokens from the tokenizer is not reflected in the selection list when the popover is opened, nor the selected model
also removes fd-list-item from headers
=> fix(core): bug where token would not be removed from mobile mode

libs/core/src/lib/select/select.component.html, libs/core/src/lib/select/select.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/10088
The placeholder in Select component should be italic with color `var(--sapField_PlaceholderTextColor)`. 
The fix is done here, not in Fundamental-ngx as we can't control the value of aria-selected without JavaScript.
=> fix(core): add the correct styling for Select placeholder

libs/datetime-adapter/src/lib/dayjs-datetime-formats.ts
fixes none
Fixes an issue where the DayJS adapter would require leading zeros in front of the day or month, if less than 10, and if no leading zero was provided, would revert to US-style date formatting for any locale.
=> fix: dayjs adapter was enforcing double digits for month and day

libs/core/src/lib/checkbox/checkbox/checkbox.component.html, libs/core/src/lib/checkbox/checkbox/checkbox.component.ts, libs/docs/core/checkbox/checkbox-docs.component.html, libs/docs/core/checkbox/checkbox-docs.component.ts, libs/docs/core/checkbox/examples/checkbox-label-wrapping-example.component.ts, libs/docs/core/checkbox/examples/index.ts
closes #9832
part of #9823 
Not much has changed, but I noticed that label wrapping was missing from the API
=> feat(core): added wrapping to the checkbox label

libs/nx-plugin/src/generators/sap-component/files/docs/project.json.template, libs/nx-plugin/src/generators/sap-component/generator.ts
closes none
SAP component generator depended on angular.json and also on public_api.ts files, which are not used anymore in our library
=> chore(tooling): fixed sap-component generator

libs/core/src/lib/popover/popover-mobile/popover-mobile.component.html, libs/core/src/lib/popover/popover-service/popover.service.ts, libs/core/src/lib/popover/popover.component.spec.ts, libs/core/src/lib/popover/popover.component.ts, libs/docs/core/popover/e2e/popover.e2e-spec.ts, libs/docs/core/popover/e2e/popover.po.ts, libs/docs/core/popover/examples/popover-mobile/popover-mobile-example.component.html
part of #9236 
Both `PopoverComponent` and `PopoverService` extend `BasePopoverClass`. Both were emitting the `isOpenChange` event, causing mobile popovers to be opened twice. This is an immediate fix for that problem but I think we need to restructure these components, in my opinion it is not great to have the component and service extending the same base class
This solution of ascending the element parent node tree feels a bit code smelly but I think it is the best option for two reasons
1. We can solve the problem of ascending the parent tree by requiring the application developer to add `fd-popover-body` wrapper around the contents of the dialog. I'd like to avoid this since it is a breaking change
2. I thought why not just add `fd-popover-body` to the `popover-mobile.component.html` …
=> fix(core): redundant popover open/close/event things

libs/platform/src/lib/table-helpers/services/table.service.ts
closes #10154
Table sort rules event was not updated when state changed
=> fix(platform): fixed table sort rules update

libs/platform/src/lib/table/table.component.ts
closes #10183
We refactored the way how we set rows but did not update the main index in the main array. 
-   [na] tests for the changes that have been done
-   [na] Run npm run build-pack-library and test in external application
-   [na] update `README.md`
-   [na] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)
=> fix(platform): update tablerows index

libs/datetime-adapter/src/lib/dayjs-datetime-adapter.ts, libs/docs/core/dayjs-datetime-adapter/examples/date-picker-dayjs-adapter-example.component.ts, libs/docs/core/dayjs-datetime-adapter/examples/dayjs-adapter-options-example.component.ts
fixes none
Our doc application was working fine due to providing the adapter at a higher level and having that bleed in to all the examples, but the example code wasn't working in isolation on stackblitz or in a test project. This fixes that
=> fix(docs): dayjs datetime adapter docs

libs/docs/core/table/examples/table-column-sorting-example.component.html
=> fix: add focusAutoCapture to table popover

libs/cdk/src/lib/utils/directives/focusable-grid/focusable-grid.directive.ts, libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts, libs/cdk/src/lib/utils/directives/focusable-item/focusable-list.position.ts, libs/cdk/src/lib/utils/directives/focusable-item/focusable.item.ts, libs/cdk/src/lib/utils/directives/focusable-item/get-item-element.ts, libs/cdk/src/lib/utils/directives/focusable-item/index.ts, libs/cdk/src/lib/utils/directives/focusable-item/is-item-focusable.ts, libs/cdk/src/lib/utils/directives/focusable-list/focusable-list.directive.ts, libs/core/src/lib/table/directives/table-cell.directive.ts
closes none
Previously items should have extended FocusableItemDirective, although that is not a big deal in many cases, there are cases when that behavior is limiting and in general, depending on interface and not on inheritance better dev practice, so this PR does that, introduces the interface and alters behavior
=> feat(cdk): focusable item interface

libs/core/src/lib/shared/interfaces/search-component.interface.ts, libs/core/src/lib/shellbar/deprecated-shellbar-compact.directive.ts, libs/core/src/lib/shellbar/product-menu/product-menu.component.html, libs/core/src/lib/shellbar/product-menu/product-menu.component.ts, libs/core/src/lib/shellbar/shellbar-action/shellbar-action.component.spec.ts, libs/core/src/lib/shellbar/shellbar-action/shellbar-action.component.ts, libs/core/src/lib/shellbar/shellbar-actions-mobile/shellbar-actions-mobile.component.ts, libs/core/src/lib/shellbar/shellbar-actions/shellbar-actions.component.ts, libs/core/src/lib/shellbar/shellbar-logo/shellbar-logo.component.spec.ts, libs/core/src/lib/shellbar/shellbar-logo/shellbar-logo.component.ts, libs/core/src/lib/shellbar/shellbar-sidenav.directive.ts, libs/core/src/lib/shellbar/shellbar-subtitle/shellbar-subtitle.component.spec.ts, libs/core/src/lib/shellbar/shellbar-subtitle/shellbar-subtitle.component.ts, libs/core/src/lib/shellbar/shellbar-title/shellbar-title.component.spec.ts, libs/core/src/lib/shellbar/shellbar-title/shellbar-title.component.ts, libs/core/src/lib/shellbar/shellbar.component.spec.ts, libs/core/src/lib/shellbar/shellbar.component.ts, libs/core/src/lib/shellbar/shellbar.module.ts, libs/core/src/lib/shellbar/user-menu/shellbar-user-menu.component.ts, libs/platform/src/lib/search-field/search-field.component.html
closes #9852
- Added helper div;
- Migrated shellbar lib to standalone components
=> feat(core): shellbar horizon update

libs/core/src/lib/carousel/carousel-item.directive.ts, libs/core/src/lib/carousel/carousel-item/carousel-item.component.ts, libs/core/src/lib/carousel/carousel.component.html, libs/core/src/lib/carousel/carousel.component.spec.ts, libs/core/src/lib/carousel/carousel.component.ts, libs/core/src/lib/carousel/carousel.directive.spec.ts, libs/core/src/lib/carousel/carousel.directive.ts, libs/core/src/lib/carousel/carousel.module.ts, libs/docs/core/carousel/carousel-docs.component.html, libs/docs/core/carousel/carousel-docs.module.ts, libs/docs/core/carousel/e2e/carousel.e2e-spec.ts, libs/docs/core/carousel/examples/carousel-background-example.component.html, libs/docs/core/carousel/examples/carousel-background-example.component.ts, libs/docs/core/carousel/examples/carousel-content-navigation-example.component.html, package.json, yarn.lock
closes #9821
- Added vertical carousel buttons changes;
- Added background configuration;
Vertical carousel markup change:
Previously navigation buttons had icons `sap-icon--slim-arrow-left` and `sap-icon--slim-arrow-left` ignoring the direction. Now if vertical navigation is applied, buttons will have icons `sap-icon--slim-arrow-up` and `sap-icon--slim-arrow-down` respectively.
=> feat(core): horizon carousel update

libs/cdk/src/lib/utils/components/dynamic-portal/dynamic-portal.component.ts, libs/core/src/lib/toolbar/deprecated-toolbar-size.directive.ts, libs/core/src/lib/toolbar/toolbar-form-label.directive.ts, libs/core/src/lib/toolbar/toolbar-item.directive.ts, libs/core/src/lib/toolbar/toolbar-label.directive.ts, libs/core/src/lib/toolbar/toolbar-overflow-button-menu.directive.ts, libs/core/src/lib/toolbar/toolbar-overflow-button.directive.ts, libs/core/src/lib/toolbar/toolbar-separator.component.ts, libs/core/src/lib/toolbar/toolbar-spacer.directive.ts, libs/core/src/lib/toolbar/toolbar.component.html, libs/core/src/lib/toolbar/toolbar.component.spec.ts, libs/core/src/lib/toolbar/toolbar.component.ts, libs/core/src/lib/toolbar/toolbar.module.ts, libs/docs/core/toolbar/examples/toolbar-overflow-grouping-example.component.html, libs/docs/core/toolbar/examples/toolbar-overflow-priority-example.component.html, libs/docs/core/toolbar/examples/toolbar-separator-example.component.html, libs/docs/core/toolbar/examples/toolbar-size-example.component.html, package.json, yarn.lock
closes #9824
Removed inner `<div class="fd-toolbar">...</div>`.
Now classes and other attributes applied to the root `fd-toolbar` element.
=> feat(core): toolbar horizon update

libs/docs/platform/message-popover/examples/default/message-popover-default-example.component.html, libs/docs/platform/message-popover/examples/default/message-popover-default-example.component.ts, libs/docs/platform/message-popover/examples/form-generator/form-generator-component-example.component.ts, libs/platform/src/lib/message-popover/components/message-popover-form-wrapper/message-popover-form-wrapper.component.ts, libs/platform/src/lib/message-popover/components/message-view/message-view.component.ts, libs/platform/src/lib/message-popover/directives/message-popover-form-item.directive.ts, libs/platform/src/lib/message-popover/message-popover.component.spec.ts, libs/platform/src/lib/message-popover/message-popover.component.ts, libs/platform/src/lib/message-popover/models/message-popover.interface.ts, libs/platform/src/lib/message-popover/platform-message-popover.module.ts, libs/platform/src/lib/message-popover/utils.ts
closes #9889
- Fixed issue with platform form field not visible to the Message Popover;
- Migrated to standalone components;
- Horizon 2023 update
=> feat(platform): message popover horizon update

libs/core/src/lib/button/base-button.ts
fixes #10222 
downported to ng15 with version 0.43.4
=> fix(core): no initial aria-pressed value for buttons

libs/core/src/lib/bar/bar.component.ts
fixes #10217 
Was also wondering if the `_isCozy$` BehaviorSubject in the content density observer service should default to true, i.e.
`private readonly _isCozy$ = new BehaviorSubject<boolean>(true);`
=> fix(core): dialog bar cozy issue

libs/core/src/lib/date-picker/date-picker.component.ts, libs/core/src/lib/datetime-picker/datetime-picker.component.ts
closes #10323
- Focus trap now temporary pauses when the date(time) picker being opened;
- Fixed issue with setting initial focus in datetime picker;
-   [x] change …
=> fix(core): datepicker outer focustrap

libs/platform/src/lib/table/table.component.ts
closes #10321
Previously, `rowHeight` input property would be overriden by changes in content density. Now it checks whether previous rowHeight is content-density related. If not, ignore content density changes.
=> fix(platform): custom row height

libs/platform/src/lib/table/table.component.html
closes #10367 
Previously we had tbody helper for virtual scroll table where we set total height of the table contents. This approach didn't work with safari and firefox well.
Now we have inner table cell with height applied to it which works fine in chrome, safari and ff
=> fix(platform): cell height instead of tbody

libs/core/src/lib/dialog/base/dialog-base.service.ts, libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts, libs/core/src/lib/dialog/index.ts, libs/core/src/lib/dialog/utils/dialog-container.model.ts, libs/core/src/lib/message-box/message-box-container/message-box-container.component.ts
closes none;
Previously we had `dismissAll` method in `DialogService` which just removed dialog instance from the array of opened dialogs.
Now this method actually dismisses all dialog instance with optional reason and destroys dialog components.
=> fix(core): dialog service dismiss all

libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts, libs/platform/src/lib/table/components/table-toolbar/table-toolbar.ts, libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.ts
part of #10283
using table-toolbar header as a `aria-labelledby` for the table
=> feat(platform): added aria-labelledby to the table

libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts, libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.ts
part of #10283 
In previous merge to the downport, I forgot to add the input for `aria-labelledby`
=> feat(platform): table aria-labelledby input

libs/core/src/lib/checkbox/checkbox/checkbox.component.html
=> fix(core): checkbox label container gap issue

libs/core/src/lib/token/token.component.scss
=> fix(core): default element style breaking standalone tokens

libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
closes none
When predefined selected value did not exist in the initial list of the items, it would throw an error because faulty logic would push `undefined` into the list of the suggestions. This fix patches that error and now it creates from the selection data items which should be rendered
=> fix(platform): fixed non-existent predefined selected value selection

.prettierignore, libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.ts
closes #10201
If there are no items to show, we now hide the selection column and the checkbox in it
SHOULD BE DOWNPORTED
=> fix(platform): hiding selection column when data is not visible

libs/core/src/lib/list/list.component.spec.ts, libs/core/src/lib/list/list.component.ts, libs/platform/src/lib/list/action-list-item/action-list-item.component.spec.ts, libs/platform/src/lib/list/list.component.html, libs/platform/src/lib/list/list.component.ts
closes #10387
Previously list component would set role without considering the attribute applied to it's element. Now it checks whether `role` is being set by the user, and if so, return user-defined role attribute.
=> fix(core): custom list role

libs/core/src/lib/link/link.component.scss
closes #10135
This change adds spacing to the fd-link
=> fix(core): added spacing to the icons in fd-link

libs/i18n/src/lib/languages/albanian.ts, libs/i18n/src/lib/languages/bulgarian.ts, libs/i18n/src/lib/languages/chinese.ts, libs/i18n/src/lib/languages/czech.ts, libs/i18n/src/lib/languages/english.ts, libs/i18n/src/lib/languages/french.ts, libs/i18n/src/lib/languages/georgian.ts, libs/i18n/src/lib/languages/hindi.ts, libs/i18n/src/lib/languages/italian.ts, libs/i18n/src/lib/languages/polish.ts, libs/i18n/src/lib/languages/russian.ts, libs/i18n/src/lib/languages/turkish.ts, libs/i18n/src/lib/languages/ukrainian.ts, libs/i18n/src/lib/models/lang.ts, libs/platform/src/lib/table/components/table-row/table-row.component.html
=> fix(platform): screenreader only span for empty platform table cells

libs/core/src/lib/icon/icon.component.ts, libs/core/src/lib/list/directives/list-navigation-item-arrow.directive.ts, libs/core/src/lib/list/list-component.interface.ts, libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.html, libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts, libs/core/src/lib/vertical-navigation/vertical-navigation.component.scss
closes #10388
- Fixed issue with focusing button instead of whole vertical nav item;
- Fixed issue with focus outline of the parent expanded item;
- Added role="presentation" for icon and button
=> fix(core): vertical nav keyboard navigation

libs/core/src/lib/token/token.component.html
closes #10382
- Removed `aria-readonly` from the element with the role that is not associated with that aria attribute.
=> fix(core): remove incorrect aria attribute

libs/cdk/src/lib/data-source/ng-package.json, libs/cdk/src/lib/forms/ng-package.json, libs/cdk/src/lib/ng-package.json, libs/cdk/src/lib/package.json, libs/cdk/src/lib/utils/ng-package.json, libs/i18n/project.json
Fixed https://github.com/SAP/fundamental-ngx/actions/runs/6313731280/job/17142547649
i18n package lacked the dependency on `cdk` itself, it only had dep on `cdk-utils`
=> chore: fixed build dependencies

libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts, libs/platform/src/lib/table-helpers/table.ts
fixes #10552 
Adjusts the functionality when resizing frozen columns to match that of sapui5. When the user resizes a frozen column such that it will be wider than the table, the column becomes unfrozen.
=> fix(platform): when a frozen column is made wider than the table, unfreeze all columns

libs/core/src/lib/busy-indicator/busy-indicator.component.html, libs/core/src/lib/busy-indicator/busy-indicator.component.scss, libs/core/src/lib/busy-indicator/busy-indicator.component.spec.ts
=> fix(core): some improvements to using labels with block busy indicator

libs/core/src/lib/tabs/tab-list.component.html
part of https://github.com/SAP/fundamental-ngx/pull/10576
- Only interactive elements should have a tab index. Tab content is not guaranteed to be an interactive element, so the forced default tabindex is the wrong a11y, causing us to fail the audit.
- No guide on how to get started, so it's easy to miss things, like the project uses yarn, getting version conflicts on `npm i`
- Top level package version is redundant for monorepos such as this (it being outdated for months proves that point, but also recommended to be removed [here](https://github.com/lerna/lerna/issues/2879#issuecomment-1471606448))
=> fix(core): tab list tabindex fix

libs/core/src/lib/tabs/tab-list.component.spec.ts, libs/core/src/lib/tabs/tab-list.component.ts
covering https://github.com/SAP/fundamental-ngx/pull/10596
Related to issue, but imo it is not an actual bug: #9994 
PR #4120 replaced the index emit with TabPanel. The index in itself also holds information that's not easily accessible by only the emitted Tab. Right now consumers need to get the index by searching the DOM for the emitted value by various means, while we have index readily available inside fundamental. \
Index can come handy in many situations from querying fresh data, update the queryparams in the browser to create deeplinking and so on, all of which are possible without the index as well, but way simpler with it.
=> feat(core): add index emit to tab selection

libs/core/src/lib/avatar/avatar.component.html, libs/core/src/lib/avatar/avatar.component.ts
closes #10732
- Added ability to pass font family for avatar glyph.
-   [x] …
=> feat(core): avatar glyph font family

libs/core/src/lib/time/time-column/time-column.component.html
=> fix(core): time picker hour/minute/seconds being read twice on JAWS

libs/core/src/lib/popover/popover-service/popover.service.ts
closes none
Previously we disposed overlayRef only when it had attached content. With Close scroll strategy, content is being disposed before the actual detachment happening, thus the condition did not match and the inner state of the popover service didn't update itself to mark the popover as closed.
This PR fixes this condition and disposes the overlay each time popover has being closed.
=> fix(core): popover close strategy fix

libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
closes none
This PR fixes the issue with core calendar e2e bug that happening on the specific date, which is [end-of-month-day] - 7 days. Originally, e2e script incorrectly added new day by simply adding +1 to days number, which could result in 32.
=> fix(e2e): core calendar fix

libs/platform/src/lib/shared/domain/data-source.ts
closes #10661
- INitial issue caused by `getMatchingStrategyStartsWithPerTermReqexp` which is used only with `MatchingStrategy.STARTS_WITH_PER_TERM`. It uses regular expression, but does not escape the special characters that may affect the regex itself (`()`, `$`, `^`, etc.).
=> fix(platform): special characters escape

libs/platform/src/lib/table/table.component.html
=> fix(platform): table rows should not have tabindex="-1"

libs/platform/src/lib/table/table.component.html
=> fix(platform): rows should not have tabindex="-1"

apps/docs/src/styles.scss, libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts, libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss
closes #10814
- When user selects item from the dropdown via keyboard ENTER or SPACE, close the dropdown manu, clear input field and focus the input field;
- Updated fonts so it would work for fiori and horizon
=> fix(core): multi input close dropdown when item selected

libs/core/src/lib/combobox/combobox.component.ts
closes #10829
- Marked groupFn as an optional input property.
=> fix(core): combobox groupFn nullable type

libs/core/src/lib/multi-input/multi-input.component.html, libs/docs/platform/multi-input/platform-multi-input-docs.component.html
closes #10811
- Disable autocomplete functionality if `includes` input property is `true`.
=> fix(core): disable autocomplete if includes enabled

libs/core/src/lib/input-group/input-group.component.html, libs/core/src/lib/input-group/input-group.component.ts, libs/core/src/lib/multi-input/multi-input.component.html
part of #10627
- feat(core): added addonButtonAriaHidden input to the input group
- fix(core): added aria hidden to the input group addon button when the title is passed to the multi-input
=> fix(core): multi input addon aria hidden

libs/core/src/lib/select/select.component.html
closes #10806
- Changed role from `listbox` to `combobox`;
- Added `aria-roledescription="listbox"` attribute;
- Added `aria-hidden="true"` for dropdown icon so it wouldn't be read by the screenreader while reading select value.
=> fix(core): select aria attributes

libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
=> fix(platform): move initial focus to search input on p13

libs/core/src/lib/switch/switch.component.html
closes
Fixed default "off" icon for the switch
=> fix(core): fixed switch default off icon

libs/core/src/lib/file-uploader/file-uploader.component.spec.ts, libs/core/src/lib/file-uploader/file-uploader.component.ts, libs/docs/core/file-uploader/examples/file-uploader-example/file-uploader-example.component.html, libs/docs/core/file-uploader/examples/file-uploader-example/file-uploader-example.component.ts
fixes none
Public function `clear()` did not work and setting the ngModel to an empty array did not work. Bug was raised to me on teams, fixed while investigating. Added examples as well
=> fix(core): cannot clear file uploader

libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html, libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts, libs/platform/src/lib/table/table.component.ts
fixes https://github.com/SAP/fundamental-ngx/issues/10900
Exposes a cellFocused event on the platform table as well as a focusCell function. This can be utilized to re-focus a cell after refreshing the datasource or navigating away from a page. I've added this functionality to the preserved state example
=> fix(platform): add cellFocused event and focusCell method to platform table

libs/platform/src/lib/table/table.component.ts
part of the #11002 needs downporting
State needs to be reset, when data source instance is swapped, otherwise data from old data source gets leaked into the new list of the items
=> fix(platform): clear table rows on data source changes

libs/docs/core/dynamic-page/dynamic-page-docs.component.ts, libs/platform/src/lib/table/table.component.ts
fixes none
dynamic page had the wrong template for the facets example for stackblitz. also a platform table console log i noticed.
=> fix(core): dynamic page facets stackblitz

libs/core/src/lib/file-uploader/file-uploader.component.html
closes #11027 
File Uploader buttonAriaLabel is not working
With code
```
<fd-file-uploader
#fileUploaderComponentRef
ariaLabel="Choose file"
ariaLabelledBy="Choose file"
placeholder="Select the file "
buttonLabel="Browse"
buttonAriaLabel="browse file"
accept=".png,.jpg"
[required]="true"
[(ngModel)]="files"
[multiple]="true"
(selectedFilesChanged)="handleFileSelection($event)"
>
</fd-file-uploader>
```
```
<button fd-button="" class="fd-button fd-button--standard file-uploader__button" type="button"><span class="fd-button__text ng-star-inserted"> Browse
</span></button>
```
```
<button fd-button="" class="fd-button fd-button--standard file-uploader__button" ng-reflect-aria-label="browse file" ng-reflect-label="Browse" ng-reflect-disabled="false" type="button" aria-label="browse …
```
=> fix(core): file uploader buttonAriaLabel is not working

libs/platform/src/lib/table-helpers/helpers.ts, libs/platform/src/lib/table/table.component.ts
=> fix(platform): do not select parent row if tristate is disabled

libs/cdk/utils/directives/auto-complete/auto-complete.directive.spec.ts, libs/cdk/utils/directives/auto-complete/auto-complete.directive.ts
closes #10710
Removing chinese symbols resulted in triggering keyup event before ngModel was stable with updated value.
This fix ensures that the zone is stable and all changes are applied.
=> fix(cdk): ensure stable zone before applying autocomplete

libs/platform/table-helpers/directives/table-data-source.directive.ts, libs/platform/table-helpers/table.ts, libs/platform/table/table.component.ts
closes #11057
The issue was with late callback function call when data source changed. This fix calls cleanup of the table rows right when the data source is being set.
=> fix(platform): reset table rows before new rows emitted

libs/platform/table/table.component.ts
Addition to #11057
Previous fix did not account for set page with previous dataSource. This one resets the page to first.
=> fix(platform): reset pagination when ds changed

libs/docs/platform/action-list-item/e2e/action-list-item.po.ts, libs/docs/platform/approval-flow/e2e/approval-flow.po.ts, libs/docs/platform/display-list-item/e2e/display-list-item.po.ts, libs/docs/platform/list/e2e/list.po.ts, libs/docs/platform/object-list-item/e2e/object-list-item.po.ts, libs/platform/list/action-list-item/action-list-item.component.html, libs/platform/list/action-list-item/action-list-item.component.spec.ts, libs/platform/list/base-list-item.ts, libs/platform/list/display-list-item/display-list-item.component.html, libs/platform/list/display-list-item/display-list-item.component.spec.ts, libs/platform/list/free-content-list-item/free-content-list-item.component.html, libs/platform/list/free-content-list-item/free-content-list-item.component.spec.ts, libs/platform/list/list-group-footer.component.ts, libs/platform/list/list-group-header.component.ts, libs/platform/list/list.component.html, libs/platform/list/list.component.spec.ts, libs/platform/list/list.component.ts, libs/platform/list/object-list-item/object-list-item.component.html, libs/platform/list/object-list-item/object-list-item.component.spec.ts, libs/platform/list/standard-list-item/standard-list-item.component.html, libs/platform/list/standard-list-item/standard-list-item.component.spec.ts
closes #10993
Instead of having `fdp-list -> ul  -> fdp-list-item -> li` element tree, now we would have `fdp-list -> div.fd-list -> fdp-list-item -> div.fd-list__item`, which is more correct. It should not affect the accessibility tools since we already use roles for the list and list items.
Resulting markup will change:
Before:
```html
<fdp-list>
<ul class="fd-list">
<fdp-standard-list-item>
<li class="fd-list__item">...</li>
</fdp-standard-list-item>
</ul>
</fdp-list>
```
After:
```html
<fdp-list>
<div class="fd-list">
<fdp-standard-list-item>
<div class="fd-list__item">...</div>
</fdp-standard-list-item>
</div>
</fdp-list>
```
=> fix(platform): correct list markup

libs/platform/value-help-dialog/components/select-tab/select-tab.component.html, libs/platform/value-help-dialog/components/select-tab/select-tab.component.ts, libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html, libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
closes #11050
Added input property `allowSelectAll`. By passing `false`, it will hide "select all" checkbox in selectiion table.
=> feat(platform): allow disabling select all in vhd

libs/core/multi-input/multi-input.component.html
closes: https://github.com/SAP/fundamental-ngx/issues/10849
Added the [title] attribute to <fd-token> & <ng-template #list>
Tested the fix on Windows edge browser. Can safely assume that the fix should work on all modern browsers.
=> fix(core): hover tooltip for multi input

libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts, libs/cdk/src/lib/utils/services/observers/attribute.observer.ts, libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
closes none
Original issue can be observed here: https://ng-15-downport--fundamental-ngx.netlify.app/#/core/popover
The cause of the issue was with `MutationObserverFactory` which triggered zone detection, which caused `ngAfterContentChecked` callback function of popover control component to be triggered infinitely.
This fix moves the mutation observer detection out of the Angular CDR cycle allowing us to manipulate native attributes without having `detectChanges` side-effects.
=> fix(cdk): tabbable observer out of the zone

libs/platform/table/table.component.scss
closes #11089
Added `white-space: nowrap` styling for tree table cells.
=> fix(platform): tree table text overflow

libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.scss
closes #11224
This PR introduces minimal height of the VHD select tab content.
=> fix(platform): vhd content min height

libs/platform/table-helpers/directives/table-initial-state.directive.ts
closes #11201
Previously, `TableInitialStateDirective` did not take into account `visible` input property of the column, which resulted in rendering all available columns during table initialization.
=> fix(platform): initial visible columns

libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.html, libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.ts, libs/docs/platform/vhd/platform-vhd.docs.component.html, libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html, libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
closes #11225
- Added `tokenValidator` input function that is being triggered during submission of VHD values.
- Updated default example with usage of  `tokenValidator`
=> feat(platform): vhd validator

libs/core/multi-combobox/multi-combobox.component.html, libs/core/multi-combobox/multi-combobox.component.ts, libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.html, libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.ts, libs/docs/core/multi-combobox/examples/multi-combobox-forms/multi-combobox-forms-example.component.html, libs/docs/core/multi-combobox/examples/multi-combobox-group/multi-combobox-group-example.component.html, libs/docs/core/multi-combobox/examples/multi-combobox-group/multi-combobox-group-example.component.ts, libs/docs/platform/multi-combobox/examples/multi-combobox-forms/multi-combobox-forms-example.component.html, libs/platform/form/multi-combobox/commons/base-multi-combobox.ts, libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.html
closes #10958
Previously we called `onTouched` callback function when user focused the input field. Now it is being called when user focuses out the input field and when the dropdown list is closed.
=> fix(core,platform): touched correct usage

libs/core/date-picker/date-picker.component.html, libs/core/date-picker/date-picker.component.scss, libs/core/datetime-picker/datetime-picker.component.html, libs/core/datetime-picker/datetime-picker.component.scss, libs/core/dialog/dialog.component.scss
closes #11209 
When user opens some of the popovers or dialogs that have buttons in the footer, it may result in additional scrollbar appearing, even though the height is visibly enough to fit all of the elements.
The issue appears due to the click area of the button which has absolute positioning and messing around with the calculated height of the content.
This PR adds overflow: hidden for date picker and dialog components
=> fix(core): popover footer button overflow

libs/core/step-input/step-input.component.html, libs/core/step-input/step-input.component.ts, libs/docs/core/step-input/examples/step-inpt-default-example/step-input-default-example.component.ts
Add a prop `isFullWidth` to Step Input that would allow the user to set the control to full width. This way the control will take the entire width of the wrapping element. 
Note: the css class will come with the latest version of fund-styles
=> feat(core): add full width modifier for Step Input

libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html, libs/core/src/lib/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html, libs/core/src/lib/facets/facet/facet.component.html, libs/core/src/lib/facets/facet/facet.component.ts, libs/core/src/lib/title/title.component.ts, libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html, libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
fixes #10351 
Regarding the `[style.transform]` line, I am not sure why the arrow was always rendering pointing down previously. If you changed the previous lines to 
```
<i *ngIf="!collapsed" class="sap-icon--customer"></i>
<i *ngIf="collapsed" class="sap-icon--calendar"></i>
```
You would see the customer when the page was not collapsed, and the calendar when it is. Unclear as to why the icon would not change for `"sap-icon--slim-arrow-up"` vs `"sap-icon--slim-arrow-down"`
=> fix(core): dynamic page accessibility bugs

versions.json
add link to version 0.48 as docs so it will be available in the older doc switcher
=> docs: add link to version 0.48 as docs

libs/core/list/list-focus-item.model.ts, libs/core/list/list-item/list-item.component.ts
closes #11289
Previously list item tabindex relied on static get property, thus if used inside `OnPush` component with async data, correct attribute may not have being applied.
This PR uses signal-based tabIndex attribute which automatically notifies parent view for detection if value changed.
=> fix(core): reactive tabindex property

libs/btp/splitter/splitter.component.scss
fixes none, user reported on slack. splitter styles not being imported since the btp move
=> fix(btp): fix splitter style import

libs/core/tabs/tab-list.component.ts, libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts, libs/platform/icon-tab-bar/icon-tab-bar.component.ts
closes #10969
Previously icon tab bar and core tabs could open only tabs that are located outside overflow menu.
This PR fixes the issue and allows opening tabs that are hidden under overflow menu.
=> fix(core,platform): tabs programmatic overflow item open

libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.html, libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts
closes #11380
Previously there was no value comparator between multi input and vhd component, that resulted in an unexpected `selected` rows selection.
This PR adds value comparator by ID's that handles accurate selection for multi input and for vhd.
=> fix(docs): vhd value comparator fix

libs/cdk/src/lib/forms/cva/cva.directive.ts, libs/core/src/lib/combobox/combobox.component.ts, libs/core/src/lib/input-group/input-group.component.ts, libs/core/src/lib/multi-input/multi-input.component.ts, libs/core/src/lib/rating-indicator/components/rating-indicator.component.ts, libs/core/src/lib/select/select.component.ts, libs/core/src/lib/slider/slider.component.ts, libs/core/src/lib/time-picker/time-picker.component.ts, libs/docs/core/select/e2e/select.e2e-spec.ts, libs/docs/core/table/e2e/table.e2e-spec.ts, libs/docs/platform/select/e2e/select.e2e-spec.ts, libs/platform/src/lib/form/date-picker/date-picker.component.ts, libs/platform/src/lib/form/datetime-picker/datetime-picker.component.ts, libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts, libs/platform/src/lib/form/step-input/base.step-input.ts, libs/platform/src/lib/list/base-list-item.ts, libs/platform/src/lib/list/list.component.html, libs/platform/src/lib/shared/form/base.input.ts
closes #11343
The root cause of the issue is with how we were detecting changes when new model value was set.
Previously we used markForCheck which would trigger a detection during own detection cycle, which resulted in later layout update in Platform Component.
This PR updates writeValue methods and uses detectChanges, additionally, removing unnecessary detectChanges/markForCheck calls after base class writeValue was called.
=> fix(core,platform): detect changes when control value being updated

libs/docs/platform/table/e2e/table.po.ts, libs/platform/table/components/table-p13-dialog/columns/columns.component.html, libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
fixes none. Use focus outline instead of background when rearranging column order
=> fix(platform): p13 dialog active issue

libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts
closes #11401
Previously we assigned nested object property with new selected value array.
This approach does not work correctly due to the fact that the reference to the object remains the same, meaning change detector does not detect any changes in the input property of vhd. This PR uses direct object assignment for cdr to detect changes in the object.
=> fix(docs): use direct object assignment to trigger correct detection

libs/core/multi-combobox/multi-combobox.component.html
closes https://github.com/SAP/fundamental-ngx/issues/11404
The height of the list element was broken because of `fd-list--selection` class. We need this class in multiline list case so we add it if the list is Byline
=> fix(core): add fix for broken list height in Multi Combobox

libs/cdk/data-source/tsconfig.json, libs/cdk/data-source/tsconfig.lib.json
closes none
There was an issue with tsconfig references which resulted in invalid typescript configuration.
=> fix(cdk): data source package tsconfig

libs/platform/smart-filter-bar/smart-filter-bar.component.ts
closes none
After standalone migration, we made `SmartFilterBarService` provided in `SmartFilterBarComponent`. This resulted in unexpected behavior when users would provide this service in their components to add additional configuration, e.g. custom component renderers. Since SmartFilterBarComponent also provides `SmartFilterBarService`, it receives different instance than the config was applied to.
This PR tries to inject parent service and falls back to the local one.
=> fix(platform): smart filter bar service scope fix

libs/docs/core/object-status/examples/object-status-clickable-and-icon-example.component.html, libs/docs/core/object-status/examples/object-status-default-example.component.html, libs/docs/core/object-status/examples/object-status-icon-text-example.component.html, libs/docs/core/object-status/examples/object-status-inverted-example.component.html, libs/docs/core/object-status/examples/object-status-large-example.component.html, libs/docs/platform/object-status/examples/platform-object-status-clickable-and-icon-example.component.html, libs/docs/platform/object-status/examples/platform-object-status-icon-text-example.component.html, libs/docs/platform/object-status/examples/platform-object-status-inverted-example.component.html, libs/docs/platform/object-status/examples/platform-object-status-large-example.component.html
none, reported by designers
update the examples of Object Status with the correct icons representing the state
=> docs(core,platform): update the state icons for Object Status

libs/core/date-picker/date-picker.component.ts
closes #11476
closes #11366
The issue was caused by not updating currently selected date value which is used for calendar component to correctly calculate month grid.
=> fix(core): update displayed calendar date

libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
closes #11486 
Icon Tab Bar used `cloneDeep` on every resize event, `cloneDeep` itself had some major performance issues.
This PR uses spread syntax to clone tab which is more performant than `cloneDeep`.
Since we do not touch any inner references of the object, we are safe in terms of overriding original information.
=> fix(platform): optimize icon tab bar

libs/platform/table/components/table-p13-dialog/columns/columns.component.html, libs/platform/table/components/table-p13-dialog/columns/columns.component.ts, libs/platform/table/components/table-p13-dialog/filtering/filtering.component.html, libs/platform/table/components/table-p13-dialog/grouping/grouping.component.html, libs/platform/table/components/table-p13-dialog/sorting/sorting.component.html
fixing few issues:
- remove the usages of `fdkInitialFocus` from the wrong buttons
- import the directive `fdkInitialFocus` in the column dialog
- remove focus styling from the item wrongly added
=> fix(platform): fix p13n focus elements

libs/core/multi-combobox/multi-combobox.component.scss, libs/core/multi-combobox/select-all-toggler/select-all-toggler.component.scss
part of DH 123. noticed this was still open and assigned to me
before:
after:
before:
after:
=> fix(core): css tweaks for core multi-combobox from old DH

libs/platform/table/components/table-p13-dialog/columns/columns.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/11551
bumped the z-index of the toolbar to 10 so that the checkboxes with z-index 5 go under it
=> fix(platform): add proper z-index to Table toolbar so checkboxes don't go over it

libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html, libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts, libs/core/dynamic-page/dynamic-page.component.html, libs/core/dynamic-page/dynamic-page.component.ts, libs/core/dynamic-page/dynamic-page.interface.ts, libs/docs/platform/dynamic-page/e2e/dynamic-page.po.ts, libs/platform/dynamic-page/dynamic-page.component.html
closes https://github.com/SAP/fundamental-ngx/issues/11549
- removed role="region" from Dynamic Page component
- removed role="region" from Dynamic Page Subheader component
- changed `section` to `article` in Dynamic Page component
=> fix(core): remove role region from Dynamic Page component

libs/core/card/card-title.directive.ts, libs/core/card/card.component.ts, libs/core/card/index.ts, libs/core/card/token.ts
closes https://github.com/SAP/fundamental-ngx/issues/11548
Cards have `role='region'` which should be labeled by the Card title. 
The current PR:
- adds id to Card Title component
- uses this id for `aria-labelledby` of the parent Card component
=> fix(core): add aria-labelledby for Card component

libs/platform/value-help-dialog/components/define-tab/define-tab.component.html, libs/platform/value-help-dialog/components/define-tab/define-tab.component.scss, libs/platform/value-help-dialog/components/define-tab/define-tab.component.ts
part of https://github.com/SAP/fundamental-ngx/issues/11494
The list group headers in VHD were not rendered properly because the text content was not wrapped in a element with `fd-list-title` directive. Additionally added CSS for showing border-bottom for the group item in a list with no separators.
=> fix(platform): add visual fixes for option list in VHD

libs/core/input-group/input-group.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/11585
On focus state the information combobox button in Quartz loses the arrow. It's due to the arrow becoming white and the background becoming transparent. The transparent background was coming from fund-ngx library and for this reason wan't taking the proper color from fundamental-styles.
**Before:**
**After:**
=> fix(core): add css fix for missing error in combobox

libs/cdk/utils/directives/focusable-item/focusable-item.directive.ts
fixes none. Rolls back a PR that broke keyboard support when using [allCellsFocusable]="true"
=> fix: roll back tabindex change

libs/core/shellbar/shellbar-actions-mobile/shellbar-actions-mobile.component.html
closes #11386
Hiding shellbar action sheet if there is no search element and actions
=> fix(core): hiding action sheet in shellbar if not needed

libs/core/shellbar/product-menu/product-menu.component.html, libs/core/shellbar/product-menu/product-menu.component.scss, libs/core/shellbar/product-menu/product-menu.component.ts, libs/core/shellbar/shellbar-title/shellbar-title.component.html
closes https://github.com/SAP/fundamental-ngx/issues/11611
- made Shellbar title heading 1 element
- in case of Product menu, the span element with the text remains a span as we can't put a heading element inside a button. To handle this problem we add a visually hidden heading 1 element as a sibling to the button
=> fix(core): a11y fix for Shellbar component

libs/core/select/select.component.scss
closes none (reported in Slack)
when an application doesn't have Button component, the CSS for button in Select is not imported and results in 
The current PR adds the button css to Select component
=> fix(core): import Button css to Select component

libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
PR https://github.com/SAP/fundamental-ngx/pull/11535 added validator input for p13 filter component. 
But it caused a regression, when there is no  `<fdp-table-p13n-filter [validator]="validator" />` inside 
```html
<fdp-table-p13-dialog [table]="table"> </fdp-table-p13-dialog>
``` 
Table filter cannot be opened.
This issue can be reproduced on both 0.49 and 0.43
- StackBlitiz https://stackblitz.com/edit/p6cmyh?file=src%2Fapp%2Fplatform-table-p13-filter-example.component.html
=> fix(platform): check validator before open Filtering Settings Dialog

libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts, libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.spec.ts
fixes #11614 
already fixed by @InnaAtanasova on main here: https://github.com/SAP/fundamental-ngx/pull/11767/files#diff-9147dfcd23f2e521ff9713a02abe871d8307183e4baac7361497f7760299359bL42
=> fix(core): remove tabindex from dynamic page header

libs/docs/platform/table/child-docs/clickable-rows/clickable-rows-docs.component.html, libs/docs/platform/table/examples/platform-table-activable-example.component.html, libs/docs/platform/table/examples/platform-table-activable-example.component.ts, libs/platform/table-helpers/models/index.ts, libs/platform/table-helpers/models/table-cell-activate-event.model.ts, libs/platform/table-helpers/models/table-row-activate-event.model.ts, libs/platform/table-helpers/services/table-row.service.ts, libs/platform/table/components/table-row/table-row.component.html, libs/platform/table/table.component.ts
fixes #11639 
Decided to piggyback on the rowActivate event. This works similarly, it just passes columnIndex instead of the row index. Also, row does not need to be activable. WIP because I am open to name suggestions
=> fix(platform): add cellActivate event to platform table

libs/core/dynamic-page/dynamic-page.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/11862
if no content is provided the padding should be removed
No content:
With content:
=> fix(core): remove padding when subheader is empty

libs/core/message-box/message-box-semantic-icon/message-box-semantic-icon.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/11995
updated the default status icons for Message Box
=> fix(core): update Message Box status icons

libs/docs/platform/table/child-docs/advanced/advanced-examples-docs.component.html, libs/docs/platform/table/examples/advanced-scrolling/advanced-scrolling-example.component.html, libs/docs/platform/table/examples/advanced-scrolling/advanced-scrolling-example.component.ts, libs/platform/src/lib/table-helpers/directives/index.ts, libs/platform/src/lib/table-helpers/directives/table-advanced-viewport.directive.ts, libs/platform/src/lib/table-helpers/directives/table-visible-cell.directive.ts, libs/platform/src/lib/table-helpers/index.ts, libs/platform/src/lib/table-helpers/services/table-advanced-viewport-root.service.ts, libs/platform/src/lib/table-helpers/table-helpers.module.ts, libs/platform/src/lib/table/components/table-row/table-row.component.html, libs/platform/src/lib/table/components/table-row/table-row.component.ts, libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.ts
None (Requested by Sourcing)
Currently, even with `virtualScroll`, which handles large amount of items, but platform table has issue with large amount of columns which causes some slowness and even page freeze. The idea in this quick fix is to render table cell data only in viewport and reduce DOMNodes, js event listener...
- Implement IntersectionObserver to control the rendering in viewport.
- Introduce property input `onlyRenderVisibleCells` which can be used with any platform table feature (`virtualScroll`, `pageScrolling`, etc...). This toggle is to enable this change.
- Introduce property input `useCellPlaceholder` to use placeholder [fd-busy-indicator] when cell is not within viewport.
- Change affects scrolling behavior and experience, for example, it affects `renderAhead` of …
=> fix(platform): quick fix performance for platform table with many columns

libs/docs/core/dynamic-page/examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html, libs/platform/icon-tab-bar/components/icon-tab-bar-tab/icon-tab-bar-tab.component.ts, libs/platform/icon-tab-bar/interfaces/tab-config.interface.ts, libs/platform/icon-tab-bar/types.ts
closes https://github.com/SAP/fundamental-ngx/issues/12022
- fix the problem with overflow btn (more) not working on smaller screens
- update the example in Dynamic Page using Tabs
=> fix(platform): add fix for overflow button not working in Icon Tab Bar

libs/platform/table/components/table-view-settings-dialog/filtering/filters-list-step.component.html
closes https://github.com/SAP/fundamental-ngx/issues/11964
Filter dialog in Platform table was using navigation list and then links inside the list items. Refactored the markup to use a normal list with interactive items (for the states).
=> fix(platform): use correct markup for the list in Filter dialog for Platform table

libs/core/dialog/dialog-body/dialog-body.component.ts, libs/platform/table/components/table-view-settings-dialog/filtering/filters.component.html, libs/platform/table/components/table-view-settings-dialog/grouping/grouping.component.html, libs/platform/table/components/table-view-settings-dialog/sorting/sorting.component.html
closes https://github.com/SAP/fundamental-ngx/issues/11980
The table settings dialogs (sorting, grouping and filtering dialogs) have an additional padding around the list in their content area.
The fix:
- added an input prop to dialog body that is not set through dialog config
- set the prop to true for table dialogs
=> fix(core, platform): add option to remove additional paddings from table settings dialogs

libs/platform/table/table.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/11979
When a table is sorted by a specific column, the respective column header changes the text font weight from 700 (semibold) to 400 (regular). It should stay consistent with the other column headers at 700. Added a CSS fix.
=> fix(platform): add fix for incorrect font weight for column header in sorted state

libs/cdk/utils/pipes/search-highlight.pipe.ts, libs/core/multi-combobox/base-multi-combobox.class.ts, libs/core/multi-combobox/multi-combobox.component.ts, libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.html, libs/docs/core/multi-combobox/examples/multi-combobox-datasource/multi-combobox-datasource-example.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12040
- adds option to set the matching strategy from the component
- adds fix for highlighting the matching string in the list items
=> fix(core): add option to set the matching strategy for multi combobox

libs/core/popover/popover-body/popover-body.component.scss, libs/docs/core/inline-help/examples/inline-help-example.component.html
closes none, reported by designers
Inline help long text doesn't wrap on multiple lines. Added a CSS fix.
=> fix(core): CSS fix to allow long text to wrap for Inline Help

libs/core/grid-list/components/grid-list-item/grid-list-item.component.html, libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts, libs/core/grid-list/components/grid-list/grid-list.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/12048
- the title of the Grid List Item is hard-coded and can't be customized. Changed the `h4` element to a div with `role='heading'` and aria-level that can be set by the user. The default is level 4. 
- added the missing class `fd-grid-list__item-title` to the title which was causing the incorrect size and weight bug.
- removed the hard-coded `is-compact` classes for the radio button and checkbox. Now is using the content density service.  Removing the hard-coded `is-compact` fixed the misalignment of the elements. 
- the CSS fix is added to comply with the visual specs for multi select grid list item:
=> fix(core): fix the title font size and alignment for Grid List Item

libs/docs/platform/docs-data.json
fixes none, something I just noticed
=> docs: remove now-unused i18n link

libs/core/combobox/combobox.component.spec.ts, libs/core/combobox/combobox.component.ts
https://github.com/SAP/fundamental-ngx/issues/11848
Keeping input and form control value in sync (unless using objects only).
One exceptional scenario is when the user do not use `communicateByObject`, but does use `displayFn`. `displayFn` expects one of the `item` objects, that is why in `inputText` setter we need to set `_value`, not call `setValue`.
[this example](https://fundamental-ngx.netlify.app/#/core/combobox#display-object) and many others can be used to validate. select one of the items, modify the text input and open the select again by the chevron button. there should be no selected highlighting when `communicateByObject` is false, since the new valid value is what the user typed.
=> fix(core): control value not updating properly on user input

libs/platform/src/lib/table/table.component.ts
fixes #12070 
When fetching new rows from a child data source, the table was previously inserting new data at the end of the parent row's children. It needs to be recursively searching through all children/grandchildren/etc of the parent, checking their expanded state, and setting the new start index based on that.
=> fix(platform): when loading child datasource, need to recursively check all expanded children for insertion index

libs/core/combobox/combobox.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12097
Step 1: select a value, the json value is updated
Step 2: clear the input, the json value is set to null
Before the fix the json value was keeping the previous selection when the input was cleared.
=> fix(core): clear the json value if input is empty in Combobox

libs/core/multi-combobox/multi-combobox.component.ts, libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12102
The provided fix will clear the search input and close the options list when the user makes the selection by clicking on the checkbox. Currently this happens only when the user clicks on the text.
=> fix(core,platform): clear input and close options list on checkbox selection for Multi combobox

libs/docs/core/dialog/dialog-docs.component.ts, libs/docs/core/dialog/examples/auto-label/auto-label-dialog-example.component.ts, libs/docs/core/dialog/examples/component-based/dialog-example.component.ts, libs/docs/core/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.ts, libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.ts, libs/docs/core/dialog/examples/dialog-configuration/dialog-configuration-example.component.ts, libs/docs/core/dialog/examples/dialog-form/form-dialog-example.component.ts, libs/docs/core/dialog/examples/dialog-full-screen/dialog-full-screen-example.component.ts, libs/docs/core/dialog/examples/dialog-inner-popover/dialog-inner-popover.component.ts, libs/docs/core/dialog/examples/dialog-mobile/dialog-mobile-example.component.ts, libs/docs/core/dialog/examples/dialog-position/dialog-position-example.component.ts, libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.ts, libs/docs/core/dialog/examples/stacked-dialogs/first-dialog-example.component.ts, libs/docs/core/dialog/examples/template-based/template-based-dialog-example.component.ts, libs/platform/wizard-generator/components/dialog-wizard-generator/dialog-wizard-generator.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/11873 fix(dialogs): Updated documentation
Description:
Updated documentation of dialog component, removed deprecated DialogModule and replaced with standalone components
=> docs: update dialog documentation

libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.html, libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.ts, libs/docs/platform/table/examples/platform-table-default-example.component.ts, libs/docs/platform/table/examples/virtual-scroll-whole-row/platform-table-virtual-scroll-whole-row-example.component.html, libs/docs/platform/table/examples/virtual-scroll-whole-row/platform-table-virtual-scroll-whole-row-example.component.ts, libs/docs/platform/table/platform-table-docs.component.html, libs/docs/platform/table/platform-table.module.ts, libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts, libs/platform/src/lib/table-helpers/models/directives.ts, libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts, libs/platform/src/lib/table-helpers/table.ts, libs/platform/src/lib/table/components/table-row/table-row.component.html, libs/platform/src/lib/table/components/table-row/table-row.component.ts, libs/platform/src/lib/table/table.component.html, libs/platform/src/lib/table/table.component.scss, libs/platform/src/lib/table/table.component.ts, libs/platform/src/lib/table/tests/table.component-virtual-scrolling.spec.ts
fixes #11491 
Adds a new input to the platform table `[scrollWholeRows]`, intended to be used in conjunction with `[virtualScroll]="true"`. Modifies the behavior of (vertical) virtual scrolling for the table. When the user performs a scroll (via mousewheel, scrollbar, keyboard arrows, etc), rather than scrolling pixel by pixel, an entire row will be scrolled. This changes the UX to more closely match that of UI5. It also comes with some inherent performance improvements such as not rendering hidden `<tr>`s.
This is added as a new feature. If the developer does not add `[scrollWholeRows]="true"`, they'll see the previous virtual scrolling behavior
=> feat(platform): virtual scroll whole rows enhancement for ng15

libs/core/src/lib/tabs/tab-list.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12035
The fix from https://github.com/SAP/fundamental-ngx/pull/10762 handles content body with static height and when there is a new item being added asynchronously. However, it created a side effect which triggers many calls on `onScroll` from scroll-spy directive even when there is no change to dynamic content body.
The scenario mentioned above has only handled if there is a new change to tab list. Therefore, this fix will add a check if there is a change to the size of tab list and will only execute `onScroll` from scroll-spy directive if that is a case.
After fix:
Remove redundant calls and regression check on previous fix:
https://github.com/user-attachments/assets/3507b243-6a3d-408a-801f-9330654b6a6c
=> fix(core): Remove redundant api calls on dynamic page

libs/core/src/lib/breadcrumb/breadcrumb-item.component.ts, libs/core/src/lib/breadcrumb/breadcrumb.component.html, libs/core/src/lib/breadcrumb/breadcrumb.component.ts, libs/docs/core/breadcrumb/examples/breadcrumb-examples.component.ts, libs/docs/core/breadcrumb/examples/breadcrumb-href-example.component.html, libs/docs/core/breadcrumb/examples/breadcrumb-routerLink-example.component.html
=> fix(core): remove breadcrumb click proxy, allowing events on original breadcrumb item to be passed to overflow item

libs/platform/form/combobox/commons/base-combobox.ts
closes [#12036](https://github.com/SAP/fundamental-ngx/issues/12036)
fix(combobox): support null as `dataSource`
Description:
Updated base combobox component, now it supports null as `dataSource`
=> fix(platform): Combobox with asyc dataSource

libs/platform/table/components/table-p13-dialog/filtering/filtering.component.ts
closes [#12061](https://github.com/SAP/fundamental-ngx/issues/12061)
Fixed issue related to table filtering reset
=> fix(platform): resolve filter reset related issue

libs/core/message-box/message-box.component.html, libs/core/message-box/message-box.component.ts, libs/docs/core/message-box/examples/complex-template/complex-template-example.component.ts, libs/docs/core/message-box/examples/template-based/template-based-message-box-example.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12180
- remove role dialog from the host
- change role dialog to role alertdialog as per SR specs
- updated some of the examples to use aria-label
=> fix(core): remove role dialog on the host el of Message Box

libs/cdk/src/lib/utils/directives/line-clamp/line-clamp.directive.ts
=> fix(core): bug where line clamp directive would not set textContent when originalText is falsy

libs/core/form/form-message/form-message.component.ts
I see no reason to hide this configurability. On the flip side in cases where you'd want to have a notification and a dropdown as well (e.g. required multi input shows message to the users) it makes styling harder as you can only target (without good old CSS reflection) the other element, cannot set a clear precedence between the 2.
=> fix(core): users cannot customize class names on form-messages

libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.spec.ts, libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts, libs/platform/table/components/table-view-settings-dialog/table-view-settings-dialog.component.spec.ts, libs/platform/table/components/table-view-settings-dialog/table-view-settings-dialog.component.ts
closes [#12095](https://github.com/SAP/fundamental-ngx/issues/12095)
When the filter/sort/group settings dialog is triggered multiple times(only happens when the component is busy with other functionality), the settings dialogs are rendered in a stacked order multiple times.
below is the link to the stackblitz, where the problem can be reproduced(click on reload multiple times and then click the sorting button on the header multiple times, after a few seconds multiple sort settings dialog is rendered on the screen)
https://stackblitz.com/edit/6vfrhd-4ghmut?file=src%2Fapp%2Fplatform-table-sortable-example.component.ts
https://github.com/user-attachments/assets/bfc80b68-afd2-4758-814f-f85b38d6f6e8
https://github.com/user-attachments/assets/b500d2f9-bcd3-40e5-9191-ce60892a253d
1. Visual …
=> fix(platform): dismiss existing dialogs before rendering new one

libs/core/input-group/input-group.component.scss
closes none
This PR removes the input background colour for Chrome autocomplete.
**NOTE: a fix is provided also in FNGX**
**_Before:_**
**_After:_**
=> fix(core): remove the default background for autofill input

libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts
fix(core): ensure grid list item selection works with navigation in multiselect mode.
closes [#12218](https://github.com/SAP/fundamental-ngx/issues/12218)
When trying to select a grid list item that has navigation in multiselect mode with a mouse click, only the navigation event was fired, and the select did not go through. This fix ensures that both the navigation and selection events are handled correctly.
=> fix(core): ensure grid list item selection works

libs/platform/table/table.component.spec.ts, libs/platform/table/table.component.ts
closes [11877](https://github.com/SAP/fundamental-ngx/issues/11877)
Fdp Table Headers were not sticky because the enclosing container's height was not definite.
As part of the fix, if the `bodyHeight` is not passed or  invalid, the default container size is set to `100%`.
Without the default `bodyHeight`, the content overflows and the headers don't get sticky on scrolling.
https://github.com/user-attachments/assets/9ad222f9-d069-4486-9218-360780aabfd4
When predefined `bodyHeight` is provided, eg 330px,
https://github.com/user-attachments/assets/11d8597f-863a-4cec-90da-f0801e18551c
When invalid  `bodyHeight`  or empty `bodyHeight` or no `bodyHeight` provided, then we have fallback height as 100%
https://github.com/user-attachments/assets/987a1ba5-0eed-48ef-93d9-4bd2d566de22
1. Visual …
=> fix(platform): table headers are not sticky when body is overflowing

libs/docs/platform/table/examples/platform-table-default-example.component.html, libs/platform/table/components/table-toolbar/table-toolbar.component.html, libs/platform/table/components/table-toolbar/table-toolbar.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12236
exposes the input props of the search field in Table toolbar
=> feat(platform): add option to hide refresh and search buttons in Table toolbar search

libs/platform/table/components/table-p13-dialog/grouping/grouping.component.html, libs/platform/table/components/table-p13-dialog/grouping/grouping.component.ts
…oupings
closes #11605 
fix: update grouping selection flow to prevent duplicate groupings
- Disable "Add" button when the number of rules equals the number of columns.
- Disable "Add" and "Remove" buttons if the rule's column key is not selected.
- Filter available columns for each rule based on already selected columns.
- Ensure the "Add" button is disabled if all columns are used.
- Ensure the "Add" and "Remove" buttons are disabled if no rule is selected.
=> fix(platform): update grouping selection flow to prevent duplications

libs/core/select/select.component.html, libs/core/select/select.component.scss
related to https://github.com/SAP/fundamental-ngx/issues/10088
Was fixed before and then broke again
The select placeholder was not rendered with proper styling. Was due to removing aria-selected attribute, which was also used to determine if the control has a placeholder text.
=> fix(core): add proper styling for Select placeholder

libs/platform/variant-management/variant-management.component.html
closes https://github.com/SAP/fundamental-ngx/issues/12391
- on select event the list item gets the proper state (selected)
- the focus is on the first item per List behaviour/specs
=> fix(platform): update Valiant Management list item state on select event

libs/cdk/utils/directives/auto-complete/auto-complete.directive.ts
fix(core): handle IME input correctly to prevent accidental deletion of characters
closes [#12232](https://github.com/SAP/fundamental-ngx/issues/12232)
- Added handling for `compositionstart` and `compositionend` events to properly manage IME input (e.g., Chinese, Japanese).
- Introduced `isComposing` flag to bypass autocomplete logic during IME composition.
- Updated `inputText` synchronization after IME input ends to ensure it matches the finalized value.
- Prevented unwanted modifications of input value when using IME, addressing the issue where typing and deleting partially composed characters could remove the last English character.
=> fix(core): combobox handle IME input correctly to prevent accidental deletion of characters

libs/platform/table/components/table-toolbar/table-toolbar.component.html, libs/platform/table/table.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/12408
By design specs, the Toolbar in Table should have border bottom. Currently, this border is visible in most cases because the table header cells have borders all around. In the case of **noOuterBorders**, the lack of border bottom in Toolbar is causing discrepancy with the design. 
- removed the property that hides the border of the Toolbar
- removed the top border of table header cells as it was causing "double" border effect.
=> fix(platform): add border to Toolbar in all types of Platfrm table

libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.html, libs/core/dynamic-page/dynamic-page.component.scss, libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/10550
closes https://github.com/SAP/fundamental-ngx/issues/12411
- when Message strip is dismissed, the element is still present in the DOM and for this reason the container ignores the CSS that checks for empty container. Now we set the padding to 0 when the container has class `.fd-has-display-none`. This will remove the extra spacing when Message Strip is dismissed (issue 12411)
- the div element with class `fd-dynamic-page__collapsible-header-visibility-container` is displayed even if there's no content inside. This is due to having the if condition inside the div, not outside. With the current fix, if there's collapsible content only then this container is rendered. The "border" that appears when collapsible is set to false now …
=> fix(core): address some Dynamic Page header issues

libs/docs/platform/table/examples/platform-table-p13-columns-example.component.html, libs/docs/platform/table/examples/platform-table-p13-columns-example.component.ts, libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts
closes [#12293](https://github.com/SAP/fundamental-ngx/issues/12293)
- Enhance the <fdp-table-p13-dialog [table]="table"></fdp-table-p13-dialog> component to emit an event with the selected column details when the OK button is clicked in the dialog.
- This allows the application to subscribe to this event and persist the user’s selected columns.
=> fix(platform): fdp-table  Enhance the <fdp-table-p13-dialog [table]="table"> component to emit an event with the selected column

libs/cx/nested-list/nested-list/nested-list.component.ts
fix(cx): fix cx side bar keyboard navigation
closes [#12337](https://github.com/SAP/fundamental-ngx/issues/12337)
Refactor nested list component to improve performance and fix subscription bug
Before:
https://github.com/user-attachments/assets/3b577335-48d0-4e84-9481-168a51ff4d94
After: 
https://github.com/user-attachments/assets/f71073d4-40fb-42fe-9275-b9030b6a8f84
=> fix(cx): fix cx side bar keyboard navigation

libs/core/src/lib/multi-input/multi-input.component.html, libs/core/src/lib/multi-input/multi-input.component.ts
=> fix(core): more customization of aria attributes for multi-input

libs/core/avatar-group/directives/avatar-group-item-renderer.directive.ts
fix(core): avatar group rendering/width calculation
closes [#12400](https://github.com/SAP/fundamental-ngx/issues/12400)
- Fixed the  problem where users were unable to see the avatar group items
[Old.webm](https://github.com/user-attachments/assets/dbfa1870-9c6c-4c3d-bd65-4f3e193ed735)
[new.webm](https://github.com/user-attachments/assets/7408036d-2bbe-41a6-88ad-925c6b143bbf)
=> fix(core): avatar group rendering/width calculation

libs/core/message-strip/alert/message-strip-alert.service.ts, libs/docs/core/message-strip/examples/message-strip-auto-dismiss-example.component.ts
One-off Observable never completes, only if `ref.dismiss()` is called on the alert reference directly.
First commit contains reproduction for the above images 👆
=> fix(core): Message strip alert complete

libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.html, libs/platform/table-helpers/directives/table-virtual-scroll.directive.ts, libs/platform/table-helpers/models/directives.ts, libs/platform/table/table.component.html, libs/platform/table/table.component.scss, libs/platform/table/table.component.ts
fixes #12263 
Updates virtual scroll logic to cooperate with "popping" columns on small screens. Also adds a new input `[secondaryRowHeight]` which behaves similarly to `[rowHeight]`, but for the popping columns which are moved into the first column when the screen is set to a small width. Additionally, this PR updates the docs to explain that `[rowHeight]` (as well as `[secondaryRowHeight]`) behaves more like a minimum height, rather than a height. More on that [here](https://github.com/SAP/fundamental-ngx/issues/12475). Lastly, some more updates to the virtual scrolling docs stressing the importance that each row must be of the same height for virtual scrolling to behave smoothly.
=> fix(platform): virtual scroll should account for popping columns

libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html, libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts, libs/core/facets/facet/facet.component.html, libs/core/facets/facet/facet.component.ts, libs/core/shared/index.ts, libs/core/shared/types/heading-level.ts, libs/core/toolbar/toolbar.component.html, libs/core/toolbar/toolbar.component.ts, libs/docs/core/dynamic-page/examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-dynamic-container-height-example/dynamic-page-dynamic-container-height-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.html, libs/docs/core/dynamic-page/examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html, libs/platform/table/components/table-toolbar/table-toolbar.component.html, libs/platform/table/components/table-toolbar/table-toolbar.component.ts
fixes #11893 
A while ago @InnaAtanasova made the heading for dynamic page configurable. This takes the heading type and moves it to a shared folder, and makes the heading of table toolbar configurable in the same way as dynamic page.
=> fix(core,platform): make headingLevel a shared type, use for table toolbar

libs/platform/src/lib/table/table.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12450
Issue: We have a listener on tableLoading to perform cell refocus whenever `loadingState` is false. However, this is executed asynchronously in `setTimeout`. Since table loading can be triggered either from internal or provided by application through `[loading]`, there is a chance that it still runs when `loadingState` is true. For example, `loadingState` is set true from application when fetching the table and busy indicator is displayed on UI and `scrollIntoView` from `focusCell` will use busy indicator instead of table for position recalculation which gives the wrong position to scroll the table.
Solution: Add `loadingState` recheck to ensure that the code is only run when table is not loading.
=> fix(platform): Recheck loadingState before refocus table cell

libs/core/notification/notification-group-header/notification-group-header.component.ts, libs/core/notification/notification-group/notification-group.component.spec.ts, libs/core/notification/notification-group/notification-group.component.ts, libs/core/notification/notification-utils/notification-group-base.ts, libs/i18n/src/lib/models/fd-language-key-identifier.ts, libs/i18n/src/lib/translations/translations.properties, libs/i18n/src/lib/translations/translations.ts
closes none, 
addresses @mikerodonnell89 comments on Notifications PR https://github.com/SAP/fundamental-ngx/pull/12476#pullrequestreview-2340785897
=> fix(core): translations for Notification component

libs/core/table/directives/table-cell.directive.ts, libs/core/table/table.component.scss, libs/docs/core/table/examples/table-example.component.html, libs/docs/platform/table/examples/platform-table-custom-column-example.component.html, libs/docs/platform/table/examples/platform-table-custom-width-example.component.html, libs/docs/platform/table/examples/platform-table-default-example.component.html, libs/platform/table-helpers/table-column.ts, libs/platform/table/components/table-column/table-column.component.ts, libs/platform/table/components/table-header-row/table-header-row.component.html
closes https://github.com/SAP/fundamental-ngx/issues/11919
- adds CSS to make cells inside Table header non-interactive (**will be removed when we adopt the latest fund-styles version**)
- Core: adds `nonInteractive` input to `table-cell` directive
- Platform: adds `nonInteractive` input to `table-column` component
- update examples
=> fix(core, platform): add option to make individual Table header cells non-interactive

libs/core/dynamic-page/dynamic-page.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/12558
add to Dynamic Page header higher z-index than the one Table header has so that the  Dynamic Page header box-shadow is not hidden.
=> fix(core): add bigger z-index to show Dynamic page box-shadow

libs/core/list/list-item/list-item.component.ts, libs/platform/settings-generator/layouts/settings-generator-sidebar-layout/settings-generator-sidebar-layout.component.html, libs/platform/settings-generator/models/settings.model.ts
closes https://github.com/SAP/fundamental-ngx/issues/12546
Settings Generator was not taking into account the `id` that were passed in the config object, the IDs were auto generated from List component.
=> fix(core, platform): add custom IDs to Setting Generator list items

libs/docs/platform/form-generator/examples/platform-form-generator-example.component.ts, libs/platform/form/form-generator/controls/dynamic-form-generator-select/dynamic-form-generator-select.component.html
feat(platform): form-generator Add support for dynamic width in `Select` component through width property
closes [#12302](https://github.com/SAP/fundamental-ngx/issues/12302)
This implementation allows users to specify the width property on the Select component, enabling them to dynamically adjust its width as needed.
=> feat(platform): form-generator Add support for dynamic width in select

libs/core/combobox/combobox.component.html, libs/core/combobox/combobox.component.ts, libs/docs/core/combobox/examples/combobox-example.component.html
closes https://github.com/SAP/fundamental-ngx/issues/12545
adds `width` property that enabled the user to set a custom width for the Combobox
=> fix(core): add option to set a custom width to Combobox

libs/core/file-uploader/file-uploader.component.spec.ts, libs/core/file-uploader/file-uploader.component.ts
=> fix(core): prevent potential for infinite loop when two file uploaders have the same ngModel

libs/core/list/list.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/11592
role=navigation should not be used on `<ul>` tag as it's invalid role for ul tag
=> fix(core): remove navigation role from List

libs/platform/icon-tab-bar/icon-tab-bar.component.ts
=> fix(platform): icon-tab-bar _generateTabBarItems function improvement

libs/docs/platform/table/examples/platform-table-default-example.component.html, libs/platform/table-helpers/pipes/cell-styles.pipe.ts, libs/platform/table/components/table-header-row/table-header-row.component.html, libs/platform/table/components/table-header-row/table-header-row.component.ts, libs/platform/table/table.component.html, libs/platform/table/table.component.scss, libs/platform/table/table.component.ts
fix(platform): table ensure all borders are hidden when border options are enabled
closes [#10729](https://github.com/SAP/fundamental-ngx/issues/10729)
This fix addresses the issue where vertical and horizontal borders are still displayed in the Platform Table component, despite enabling the `noHorizontalBorders`, `noVerticalBorders`, `noBorders`, `noOuterBorders`, and `noBodyBorders` options. Specifically:
- Removed the vertical border before the last column.
- Removed the horizontal border below the table header when border-hiding options are applied.
=> fix(platform): platform table border fix

libs/core/select/select.component.html, libs/core/select/select.component.scss, libs/core/select/select.component.ts, libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.html, libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.ts
fix(core): Add Support for Multi-line Messages in Select Component Dropdown
closes [#11430](https://github.com/SAP/fundamental-ngx/issues/11430)
- Refactored the select component to manage text display mode.
- Adjusted padding in the select component message to eliminate unnecessary space.
- Introduced a new input property, textOverflow, to control how text is displayed in the dropdown list, allowing for either ellipsis or full text.
***
=> fix(core) Add Support for Multi-line Messages in Select Component Dropdown

libs/core/multi-input/multi-input.component.ts
fix(core): trim search term in MultiInputComponent to handle leading/trailing spaces
closes [#12635](https://github.com/SAP/fundamental-ngx/issues/12635)
- Updated `_defaultFilter` method to trim the search term before filtering.
- Ensured that accidental spaces do not affect search results.
https://github.com/user-attachments/assets/c0c8c015-ab7f-40d1-bf89-7685cb8de3e1
https://github.com/user-attachments/assets/ccf8bfbc-a4f6-4991-acba-d736c9928fb4
=> fix(core): trim search term in MultiInputComponent to handle leading/trailing spaces

libs/core/combobox/combobox.component.html
fix(core): combobox dynamic groupFn
closes [#12518](https://github.com/SAP/fundamental-ngx/issues/12518)
Fixed dynamic function re-creation issue.
[old.webm](https://github.com/user-attachments/assets/ed2eacfa-e867-43e4-8e6c-f69216a2aaa4)
***
[new.webm](https://github.com/user-attachments/assets/422ed22d-d6b0-4f85-bd91-85dfa6d648cd)
=> fix(core): combobox dynamic groupFn

libs/core/form/form-label/form-label.component.html, libs/core/form/form-label/form-label.component.scss, libs/core/form/form-label/form-label.component.ts, libs/docs/core/wizard/e2e/wizard.po.ts, libs/docs/core/wizard/examples/wizard-dialog-example.component.html, libs/docs/core/wizard/examples/wizard-example.component.html, libs/docs/core/wizard/examples/wizard-visible-summary-example.component.html, libs/platform/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.html
fixes #11385 
- platform wizard generator labels and data now wrap automatically on the summary page
- core wizard example default documentation edited to demonstrate how to handle text wrapping (not obvious in example)
- added class to fd-form-label to allow for text wrapping
=> fix(core,platform): wizard template, a11y updates

libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
=> fix(platform): bug where enter key would not freeze/unfreeze columns

libs/platform/dynamic-page/dynamic-page.component.html
closes #12738 
remove emtpy tab in dynamic page with tabs
=> fix(platform): remove emtpy tab in dynamic page with tabs

libs/platform/table/table.component.ts
closes [#12677](https://github.com/SAP/fundamental-ngx/issues/12677)
Fixed an issue where using `semanticHighlighting` and `group` properties simultaneously in `fdp-table` caused unexpected behavior. Updated logic to ensure compatibility and proper rendering when these features are used together.
https://github.com/user-attachments/assets/afc02800-6207-4dd4-8e0a-ac4b789a7415
=> fix(platform): table spanning

libs/core/list/list-item/list-item.component.ts, libs/platform/table/components/table-p13-dialog/columns/columns.component.html
fixes #12672 for the main branch
- Adds an input `preventClick` to the list item component which allows the user to disable default selection/deselection behavior for list items
- Utilizes this new input on the platform table p13 dialog so that clicking a list item doesn't handle selection - user must manually click the checkbox
=> fix(core,platform): clicking list item in p13 dialog should not toggle checkbox

libs/core/popover/base/base-popover.class.ts, libs/core/popover/popover-body/popover-body.component.ts, libs/docs/core/multi-combobox/e2e/multi-combobox.po.ts, libs/docs/platform/multi-combobox/e2e/multi-combobox.po.ts, libs/docs/platform/multi-input/e2e/multi-input.po.ts, libs/docs/platform/table/e2e/table-settings-dialog.e2e-spec.ts
=> fix(core): make popover body have dialog role by default

libs/platform/search-field/search-field.component.html, libs/platform/search-field/search-field.component.ts
fixed #12617 
Fixes a bug where tabbing to the platform search field input would not properly apply the border focus styles.
=> fix(platform): bug fix for search field not applying active style on initial focus

libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html, libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts
=> feat(platform): add option for configuring VHD dialog title heading level

libs/docs/core/notification/examples/notification-group/notification-group-example.component.html, libs/docs/core/notification/examples/notification-group/notification-group-example.component.ts
closes none
- Import Title component as the CSS wasn't coming
- update the settings icon
=> docs(core): update Notifications doc examples

libs/platform/form/form-group/form-group.component.html
bringing the change from https://github.com/SAP/fundamental-ngx/pull/12700
fix(platform): fix form generator button group alignment
closes https://github.com/SAP/fundamental-ngx/issues/11003
=> fix(platform): update form generator markup to match styles

libs/core/wizard/wizard.component.ts
fixes #13048 
Also makes sure to not reproduce an overlapping bug like #12290 
https://github.com/user-attachments/assets/8b2e9337-cdc2-4f7a-a112-ca8bd34c34ba
=> fix(core): wizard height calculation & content overlapping

libs/cdk/src/lib/utils/functions/key-util.spec.ts, libs/cdk/src/lib/utils/functions/key-util.ts, libs/core/src/lib/multi-combobox/multi-combobox.component.ts, libs/platform/src/lib/form/combobox/commons/base-combobox.ts, libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
closes https://github.com/SAP/fundamental-ngx/issues/13118
When IME is used, on window, for spacebar or any keydown that IME detects that needs conversion, KeyboardEvent has properties of 'Process' as key and 229 as keyCode. On combobox keydown handler, this is not checked and will set focus on list which stops the processing input conversion.
When input method is processing, we should not interrupt the ime process and set focus on list in this case. Therefore, add check against it.
Relevant information: https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#ime_and_composition_keys
```
"Process" [3] | The Process key. Instructs the IME to process the conversion. | VK_PROCESSKEY (0xE5) |   |  
-- | -- | -- | -- | --
``` …
=> fix(platform): do not set focus on list when there is IME processing

libs/core/dynamic-page/dynamic-page.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/12932
Non collapsible header of Dynamic page displays box-shadow when used with Icon Tab Bar. This PR removes the shadow.
=> fix(core): remove Dynamic page shadow when used with Icon Tab Bar

libs/core/message-strip/message-strip.component.html, libs/core/message-strip/message-strip.component.ts, libs/docs/core/message-strip/examples/message-strip-example.component.html
closes https://github.com/SAP/fundamental-ngx/issues/13106
Added an input prop `dismissBtnTitle` that will allow the user to provide more descriptive information about the button.'
Provided an example update
=> fix(core): add an option to provide more descriptive title for Message Strip dismiss btn

libs/core/list/list.component.scss, libs/docs/core/list-byline/examples/list-byline-standard-example/list-byline-standard-example.component.html
closes https://github.com/SAP/fundamental-ngx/issues/13107
Use specificity to ensure correct height of the group header in byline list
=> fix(core): set correct height for List with Byline group header

libs/core/flexible-column-layout/flexible-column-layout.component.html, libs/core/flexible-column-layout/flexible-column-layout.component.ts, libs/docs/core/flexible-column-layout/examples/default/flexible-column-layout-example.component.html
closes https://github.com/SAP/fundamental-ngx/issues/13146
We previously provided titles for the splitter buttons using the expandTitle and collapseTitle input properties. I’ve added four additional inputs to allow different titles for the expand and collapse states of the button between the start and mid columns, as well as the button between the mid and end columns. Previously, both buttons shared the same titles.
=> fix(core): add additional options to set the flexible column layout splitter title

libs/core/date-picker/date-picker.component.html, libs/docs/core/date-picker/examples/date-picker-i18n-example.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/13143
Add option to change Today button label through the config object:
Results in:
=> fix(core): date picker today btn i18n

libs/core/form/form-control/form-control.component.scss
closes none (reported on Slack)
The negative z-index of input didn't show the element in the docs. The issue is fixed in fund-styles, this one is a temporary one and will be removed after we adopt fund-styles version above  v0.39.2
=> fix(core): remove neg z-index from readonly input

libs/core/popover/popover-body/popover-body.component.scss
part of https://github.com/SAP/fundamental-ngx/issues/13200
In some cases, the text of the Inline Help is cut, which is caused by the popover inner container inheriting the border radius of the popover body. The fix was to set this radius to 0 in case of Inline Help.
Before:
After:
=> fix(core): fix the Inline Help text cut corners

libs/platform/table-helpers/pipes/cell-styles.pipe.ts, libs/platform/table/components/table-header-row/table-header-row.component.html
Fixes a bug where "vertical" and "horizontal" were switched on the header cells in regards to the inputs that show/hide the borders.
Before:
https://github.com/user-attachments/assets/8430efa8-d8d3-40c1-978e-840ca7147741
After:
https://github.com/user-attachments/assets/ae5b5842-e881-4d5a-b2b9-dc83e9e35771
=> fix(platform): bug with horizontal and vertical switched for table header cells

libs/nx-plugin/src/executors/transform-translations/executor.ts
Fixes a problem with our translation nx generator, which was ran as a pre-commit hook. Files modified by NX were not being properly staged.
Nx provides the `FsTree` for modifying files on the filesystem. As a built-in failsafe, nx does not actually persist changes to the filesystem as soon as the script sees the `FsTree.write()` function. By default, files modified within the generator aren't actually persisted to the filesystem until after the generator's successful completion. However you can get around this by calling `flushChanges` in the generator script. We were seeing our translation commit problem because we were attempting to `git add` the modified files inside the generator before calling `flushChanges`, so there wasn't actually anything to `git add` yet
=> chore: fix translation executor not being able to stage files for commit

libs/core/nested-list/nested-list/nested-list.directive.ts, libs/cx/nested-list/nested-list/nested-list.component.ts, libs/i18n/src/lib/translations/translations.properties, libs/i18n/src/lib/translations/translations.ts, libs/i18n/src/lib/translations/translations_en_US_sappsd.ts
part of #12692 
The index/total count of each item in the side nav was being announced twice, once by default as it typically does for all lists, and again a second time because we had added it manually - not sure exactly why it had been added manually, that would take some digging through the history. 
But looking in to this problem did make me realize that we have no mechanism for removing variables from the more complex translations that require some arguments to be passed with the string to be translated. I think, in cases like this where we would need to do that, it'll have to be a multi-step process:
1. The `translations.properties` file needs to be altered to have the new ideal translation in the default language. See [here](https://github.com/SAP/fundamental-ngx/compare/fix/12692?e …
=> fix(core): remove index/total from cx list translation

libs/docs/platform/table/child-docs/advanced/advanced-examples-docs.component.html, libs/docs/platform/table/child-docs/clickable-rows/clickable-rows-docs.component.html, libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html, libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.html, libs/docs/platform/table/child-docs/preserving-state/preserved-state-docs.component.html, libs/docs/platform/table/child-docs/row-selection/row-selection-docs.component.html, libs/docs/platform/table/child-docs/settings-dialog/settings-dialog-docs.component.html, libs/docs/platform/table/index.ts
fixes none
Many examples in the platform table docs had incorrect direct links, often making things difficult to communicate with developers looking for solutions
=> chore: fix links in platform table documentation

libs/core/busy-indicator/busy-indicator.component.ts, libs/docs/core/busy-indicator/examples/busy-indicator-basic-example.component.html, libs/docs/core/busy-indicator/examples/busy-indicator-extended-example.component.html, libs/docs/core/busy-indicator/examples/busy-indicator-label-example.component.html, libs/docs/core/busy-indicator/examples/busy-indicator-size-example.component.html, libs/docs/core/busy-indicator/examples/busy-indicator-wrapper-example.component.html
closes none
- new input prop ariaValueText
- added aria-valuetext, aria-valuemin and aria-valuemax attributes
- updated the examples in the documentation
=> fix(core): adopt the a11y changes for Busy Indicator from v0.40.0

libs/core/feed-input/feed-input.component.html, libs/core/feed-input/feed-input.component.ts, libs/docs/core/feed-input/examples/feed-input-circle-avatar-example/feed-input-circle-avatar-example.component.html, libs/docs/core/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.html, libs/docs/core/feed-input/examples/feed-input-example/feed-input-example.component.html, libs/docs/core/feed-input/examples/feed-input-grow-example/feed-input-grow-example.component.html, libs/docs/core/feed-input/examples/feed-input-no-avatar-example/feed-input-no-avatar-example.component.html, libs/docs/core/feed-input/examples/feed-input-placeholder-example/feed-input-placeholder-example.component.html
closes none
- adds the additional container div with class `fd-feed-input__container`
- updates role and aria-label for the parent element
- updates doc examples
=> fix(core): a11y update for Feed Input

libs/docs/platform/schema/schemas/table-schema.ts, libs/docs/platform/table/examples/platform-table-default-example.component.html, libs/docs/platform/table/platform-table-docs.component.html, libs/docs/platform/table/platform-table-docs.component.ts, libs/platform/table/components/table-view-settings-dialog/filtering/filter-step.component.html, libs/platform/table/components/table-view-settings-dialog/filtering/filters-list-step.component.html, libs/platform/table/components/table-view-settings-dialog/settings-dialog/settings-dialog.component.html
=> fix(platform): heading level for sort/filter table dialogs should be h2

libs/platform/table/components/table-view-settings-dialog/filtering/filters-list-step.component.html
fixes none. A problem I noticed when working on screenreader for platform table filter dialog. 
My first thought was to use `role="heading"` on all `<li fd-list-group-header>` elements, but `heading` is not a valid child role of `ul` elements.  I think this may be the best option, which unfortunately would mean we need to make this change all over the library and docs. Looking for your opinions @InnaAtanasova @droshev 
before:
after:
=> fix(core): fd-list-group-header should not be adjacent to fd-list-item

libs/core/action-sheet/action-sheet.component.html, libs/core/action-sheet/action-sheet.component.scss, libs/core/action-sheet/action-sheet.component.ts, libs/docs/core/action-sheet/examples/action-sheet-mobile/action-sheet-mobile-example.component.html
closes none
Adopts the breaking changes from fund-styles version 0.40.0, where the control title is now placed in a Bar element. 
Added 2 new inputs: `controlTitle` and `controlTitleHeading`.
=> fix(core): add control title to Action Sheet in mobile mode

libs/docs/core/breadcrumb/examples/breadcrumb-href-example.component.html, libs/docs/core/breadcrumb/examples/breadcrumb-routerLink-example.component.html
closes none
the links inside the Breadcrumbs should have aria-current and aria-label
=>  docs(core): update aria attr for Breadcrumb

libs/core/shellbar/shellbar.component.html
closes https://github.com/SAP/fundamental-ngx/issues/13332
The incorrect hover style of the back and hamburger buttons was caused by an incorrect CSS class being applied.
=> fix(core): apply correct class to back and hamburger buttons in ShellBar

libs/platform/table-helpers/directives/table-cell-resizable.directive.ts, libs/platform/table/components/table-column-resizer/table-column-resizer.component.scss, libs/platform/table/components/table-column-resizer/table-column-resizer.component.ts
fixes #13334 
Fixes an issue where, if you right-click a vertical border to drag it rather than left-click, the logic to hide the resizing border would break. Also fixes an issue where the resize border would not occupy 100% height
=> fix(platform): do not start table column resize when right mouse button clicked

libs/core/combobox/combobox.component.html, libs/core/combobox/combobox.component.ts, libs/docs/core/combobox/examples/combobox-search-field-example.component.html, libs/docs/core/combobox/examples/combobox-search-field-example.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/13360
- added option to set the max width of the dropdown via `dropDownMaxWidthPx` input property
- added option to remove the max-width of the dropdown via  `noDropDownMaxWidth` property. This way the dropdown will take the width of the input element.
**Custom max-width. In this case 992px:**
**No max-width:**
=> fix(core): add option to customize Combobox dropdown width

libs/docs/platform/table/examples/platform-table-custom-title-example.component.html, libs/platform/table/components/table-toolbar/table-toolbar.component.html, libs/platform/table/table.component.scss
closes https://github.com/SAP/fundamental-ngx/issues/13213
Left and right actions inside Table toolbar can be customized and should show a separator if needed. The reason the separator wasn't showing in the example is because the elements were projected inside a span element. To fix this:
1. changed the container of the projected elements to a `div`, 
2. added a class `fd-toolbar__group` that is a flex container which has a gap 0.5rem between the elements and aligns them vertically. 
Additionally, for the container of the right actions, some CSS code improvements were added: now the spacing between the elements is achieved with flex gap and there's no need of RTL handling.
=> fix(platform): show Toolbar separator in custom Toolbar inside Platform Table

libs/core/multi-input/multi-input.component.spec.ts, libs/core/multi-input/multi-input.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/13052
When a user navigates through multi inputs using the tab button, focus now skips disabled inputs and only goes to enabled ones.
https://github.com/user-attachments/assets/f73dd8f9-f213-4fe6-be3d-e16393eeba11
=> fix(core): disable tab focus on disabled multi input

libs/platform/form/combobox/commons/base-combobox.ts
closes https://github.com/SAP/fundamental-ngx/issues/13475
Hungarian alphabet characters (such as á, é, í, ó, ö, ő, ú, ü, ű) were not appearing in the Combobox input. This happened because their key codes overlap with special characters on the English keyboard, and our input handling logic was blocking them.
This change removes the restrictive checks so that all valid characters, including those from the Hungarian alphabet and other international keyboards, can be entered into the Combobox input field.
=> fix(platform): allow Hungarian special alphabet characters in Combobox input

libs/core/toolbar/toolbar.component.html, libs/core/toolbar/toolbar.component.ts, libs/docs/core/toolbar/examples/toolbar-title-example.component.html
closes none
The title element inside the Toolbar previously had an `aria-level` attribute set without the required `role="heading"`. This PR adds the missing role to ensure proper accessibility.
Additionally, the `headerSize` input property is now explicitly set to 4 for the Toolbar Title. Without this, the compiled CSS classes included `fd-title--hP`, which is invalid. The font size continues to be controlled by the `fd-toolbar__title` class.
Lastly, the title id was previously rendered as "undefined" when not provided by the user. A default id is now generated if none is specified. 
Before:
Now:
=> fix(core): add role heading to title element in Toolbar

libs/core/dynamic-page/dynamic-page.component.scss
reported in Slack
When dismissible Message strip is used in Dynamic Page Subheader, and the message strip is set to dismiss in several seconds, the Dynamic Page Subheader loses its paddings.
=> fix(core): not reset Dynamic Page Header paddings when Message strip is used

libs/core/combobox/combobox.component.spec.ts, libs/core/combobox/combobox.component.ts, libs/docs/core/combobox/combobox-docs.component.html, libs/docs/core/combobox/combobox-docs.component.ts, libs/docs/core/combobox/examples/combobox-inside-dialog-example.component.html, libs/docs/core/combobox/examples/combobox-inside-dialog-example.component.ts
closes https://github.com/SAP/fundamental-ngx/issues/12669#issue-2621028090
Problem:
When combobox is used within a dialog, when the dialog is created with `focusTrapped: true`, user is not able to navigate up and down the dropdown options. The reason is that focus is trapped on the popup and its child components, but the combobox dropdown is not a child component of the popup, it is positioned within a separate overlay. 
Solution:
Pausing and unpausing the focus trapped logic upon opening and closing the dropdown allows the user to interact with the combobox dropdown. When the dropdown is open, we pause current focus trap and arrow keys work as expected within the combobox. When the dropdown is closed, focus trap is unpaused again and focus is back on the dialog. …
=> fix(core): Combobox inside a Dialog - Not able navigate through the invoked drop-down values using keyboard

libs/core/form/form-control/form-control.component.scss, libs/core/form/form-control/form-control.component.ts, libs/core/form/form-item-control/form-item-control.ts, libs/core/form/form-item/form-item.component.scss, libs/core/form/form-item/form-item.component.ts, libs/core/form/form-label/form-label.component.html, libs/core/form/form-label/form-label.component.scss, libs/core/form/form-label/form-label.component.ts, libs/core/form/form-message/form-message.component.scss, libs/core/form/form-message/form-message.component.ts, libs/core/illustrated-message/components/illustrated-message-section/illustrated-message-section.component.spec.ts, libs/core/quick-view/quick-view-group-item-label/quick-view-group-item-label.component.spec.ts, libs/docs/core/input/examples/input-state-example.component.html, libs/docs/core/textarea/examples/textarea-state-example.component.html
part of https://github.com/SAP/fundamental-ngx/issues/13490
This changes concern ONLY textarea and input with directive `fd-form-control` (input[fd-form-control], textarea[fd-form-control])
Combobox, DatePicker, etc. belong to Input Group and there the logic for handling states will be different.
=> fix(core): adopt a11y breaking changes for Textarea and Input states
