.github/workflows/create-hotfix.yml
.github/workflows/create-release.yml
.github/workflows/on-pull-request.yml
.github/workflows/on-schedule.yml

Closes https://github.com/SAP/fundamental-ngx/issues/8758
Node16 by default for everything.

chore(docs): node16

---

libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.ts
libs/platform/src/lib/dynamic-page/dynamic-page.component.html

Refers to DXP.
Adopts https://github.com/SAP/fundamental-styles/pull/3920
Wrapping mode for Dynamic Page's (core & platform) Title & Subtitle elements.

feat(core,platform): dynamic page title & subtitle wrapping

---

libs/core/src/lib/step-input/step-input.component.spec.ts
libs/core/src/lib/step-input/step-input.component.ts

fixes #8831 
Now matches the functionality of the ui5 web component step input when clearing the input

fix(core): do not disable step input increment/decrement when value is null

---

CHANGELOG.md
package.json

bump package.json version 0.36.2

chore(ci): bump package.json version 0.36.2

---

e2e/tsconfig.json
e2e/wdio.base-config.js
libs/docs/core/calendar/e2e/calendar.po.ts
libs/docs/core/segmented-button/e2e/segmented-button.e2e-spec.ts
libs/docs/platform/search-field/e2e/search-field.e2e-spec.ts
package.json
yarn.lock

Closes https://github.com/SAP/fundamental-ngx/issues/8806
* `tsconfig-paths`
No visual diff.

fix(e2e): tsconfig-paths

---

.github/workflows/bump-styles.yml

Fixes the message of the commit which being made in process of bump-styles github action workflow.

fix(docs): bumping styles version commit message

---

libs/i18n/src/lib/directives/patch-language.directive.ts
libs/i18n/src/lib/languages/pluralization/set1.ts
libs/i18n/src/lib/pipes/fd-translate.pipe.ts
libs/plugins/wdio/.eslintrc.json

Fixes lint errors on main that prevents release to be made.

chore(docs): fix lint errors

---

libs/core/src/lib/dialog/base/dialog-config-base.class.ts
libs/core/src/lib/dialog/dialog-body/dialog-body.component.ts
libs/core/src/lib/dialog/dialog.component.scss
libs/core/src/lib/notification/notification-group/notification-group.component.ts
libs/core/src/lib/notification/notification/notification.component.scss
libs/core/src/lib/notification/notification/notification.component.ts
libs/core/src/lib/popover/popover-body/popover-body.component.ts
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.html
libs/core/src/lib/popover/popover-mobile/popover-mobile.component.ts
libs/core/src/lib/popover/popover.component.ts
libs/core/src/lib/tabs/tab-list.component.scss
libs/docs/core/notification/examples/component-as-content/notification-content.component.html
libs/docs/core/notification/examples/notification-group/notification-group-example.component.html
libs/docs/core/notification/examples/notification-mobile/notification-mobile-example.component.html
libs/docs/core/notification/examples/notification-mobile/notification-mobile-example.component.ts
libs/docs/core/notification/examples/notification-options/notification-options-example.component.html
libs/docs/core/notification/examples/template-as-content/notification-open-template-example.component.html
libs/docs/core/notification/notification-docs.component.html
libs/docs/core/notification/notification-docs.component.ts
libs/docs/core/notification/notification-docs.module.ts

Closes https://github.com/SAP/fundamental-ngx/issues/7965
Notification mobile mode (in Popover).

feat(core): notification mobile (in popover)

---

libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts

part of #8557 
Solves [this](https://github.com/SAP/fundamental-ngx/issues/8557#issuecomment-1220624224): Added  keyboard support for mobile mode in menu.

fix(core): Add keyboard support for mobile mode in menu

---

libs/core/src/lib/form/form-label/form-label.component.html
libs/core/src/lib/form/form-label/form-label.component.scss
libs/core/src/lib/icon/icon.component.scss
libs/platform/src/lib/form/form-group/form-field/form-field.component.scss
libs/platform/src/lib/form/form-group/form-group-header/form-group-header.component.html
libs/platform/src/lib/form/form-group/form-group-header/form-group-header.component.ts
libs/platform/src/lib/form/form-group/form-group.component.html

Closes https://github.com/SAP/fundamental-ngx/issues/8727
Inline help & form messages in form placement issues.

fix(core, platform): inline help in form

---

.github/actions/get-version/action.yml
.github/actions/get-version/index.js
.github/actions/wait-for-netlify/action.yml
.github/actions/wait-for-netlify/index.js
.github/workflows/update-versions.yml
package.json
versions.json
yarn.lock

Follows up https://github.com/SAP/fundamental-ngx/pull/8774
Fixes for update versions workflow.
Issues fixed
* workflow triggered with `workflow_run` event didn't get the commit that made in process of previous workflow.
* getting the version done wrong.

fix(docs): update versions workflow

---

libs/docs/platform/list/examples/platform-list-free-content-example.component.html
libs/docs/platform/list/examples/platform-list-free-content-example.component.ts
libs/docs/platform/list/platform-list-docs.component.html
libs/docs/platform/list/platform-list-docs.component.ts
libs/docs/platform/list/platform-list-docs.module.ts
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.spec.ts
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
libs/platform/src/lib/list/list-group-footer.component.ts
libs/platform/src/lib/list/list-group-header.component.ts
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/list/list.module.ts
libs/platform/src/lib/list/public_api.ts
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html

closes #8657 
Added new component which renders projected content for platform list. …

feat(platform): free content list item

---

libs/docs/platform/standard-list-item/examples/platform-standard-list-item-example.component.html
libs/platform/src/lib/list/base-list-item.ts
libs/platform/src/lib/list/display-list-item/display-list-item.component.html
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html

closes #8757 
* Refactored standard list item and display list item components to support advanced description and secondary text objects
* Updated doc example to show the usage of the advanced description object.
-   [x] …

feat(platform): add separate title property

---

libs/core/src/lib/avatar/avatar.component.ts
libs/platform/src/lib/list/list.component.spec.ts
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/list/object-list-item/object-list-item.component.spec.ts
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.spec.ts

closes #8847 
* Updated list component so it would trigger change detection after new items being set;
* Delay setting new items until component is fully ready and all child components are available;
* Fix small issue with core avatar when loading new image happened on every image set, even if the image is the same one.
2. API and …

fix(platform): trigger detection when datasource is changed

---

libs/core/src/lib/menu/menu-item/menu-item.component.spec.ts
libs/core/src/lib/menu/menu-item/menu-item.component.ts
libs/core/src/lib/menu/menu.component.spec.ts
libs/core/src/lib/menu/menu.component.ts
libs/core/src/lib/menu/services/menu.service.ts
libs/core/src/lib/split-button/split-button.component.spec.ts
libs/core/src/lib/split-button/split-button.component.ts
libs/docs/core/menu/examples/menu-with-submenu-example.component.html
libs/docs/core/menu/examples/menu-with-submenu-example.component.ts

Closes https://github.com/SAP/fundamental-ngx/issues/8928
* feat: creating nested menus dynamically
* fix: dynamically created submenus disappear when trying to hover over them.
https://user-images.githubusercontent.com/20265336/200002231-3c1a8338-60de-473d-b456-01f6f81766dc.mov
*Border radius issue fix https://github.com/SAP/fundamental-styles/pull/4007*
https://user-images.githubusercontent.com/20265336/200054500-831bbdd0-1969-465a-9829-f54e244fed68.mov

feat(core): creating submenus dynamically

---

libs/core/src/lib/file-uploader/file-uploader.component.html
libs/core/src/lib/file-uploader/file-uploader.component.scss
libs/core/src/lib/file-uploader/file-uploader.component.ts
libs/core/src/lib/popover/popover-body/popover-body.component.ts
package.json
yarn.lock

Closes none.
Addressing BC from styles in file uploader component. 
PR In styles: https://github.com/SAP/fundamental-styles/pull/4043

chore(core,platform): styles bump to 0.26.0-rc.37 and BC processing

---

libs/docs/platform/wizard-generator/examples/wizard-generator-default-example.component.ts
libs/platform/src/lib/wizard-generator/components/wizard-generator-step/wizard-generator-step.component.html
libs/platform/src/lib/wizard-generator/interfaces/wizard-generator-form-group.interface.ts

Closes https://github.com/SAP/fundamental-ngx/issues/8991
FDP Wizard Generator form group hint.

feat(platform): wizard generator group hint

---

libs/docs/platform/list/examples/platform-list-with-more-button-example.component.html
libs/docs/platform/list/platform-list-docs.component.html
libs/platform/src/lib/list/list.component.html
libs/platform/src/lib/list/list.component.scss
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/list/list.module.ts
libs/platform/src/lib/list/load-more-content.directive.ts
libs/platform/src/lib/list/public_api.ts

closes #8960
Added ability to declare custom load more button content and example of showing how to do that

feat(platform): custom load more content on lists

---

package.json
yarn.lock

bump theming-base-content version 11.1.47

chore(deps): bump theming-base-content version 11.1.47

---

libs/platform/src/lib/fundamental-ngx.module.ts

fix(platform,docs): added missing export of PlatformMultiComboboxModule

---

libs/platform/src/lib/search-field/search-field.component.html
libs/platform/src/lib/search-field/search-field.component.ts

closes #8988 
Added input property `disableSearch` to disable search button in search-field.

feat(platform): add toggling search button in search-field

---

libs/core/src/lib/select/option/option.component.html
libs/platform/src/lib/form/select/select/select.component.html
libs/platform/src/lib/form/select/select/select.component.spec.ts
libs/platform/src/lib/form/select/select/select.component.ts

fix(platform): select multi column options

---

libs/docs/core/calendar/calendar-docs.component.ts
libs/docs/platform/file-uploader/examples/platform-file-uploader-example.component.html

closes none
There were some minor exceptions thrown in docs

chore(docs): fixed documentation page errors

---

libs/core/src/lib/tabs/deprecated-tabs-compact.directive.ts

closes #9054 
Initially, I forgot to add providers, so that structure could get value from DI

fix(core): fixed deprecated tab list compact directive

---

libs/docs/core/action-bar/examples/action-bar-back-example.component.html
libs/docs/core/action-bar/examples/action-bar-contextual-menu-example.component.html
libs/docs/core/action-bar/examples/action-bar-long-string-title-truncation-example.component.html
libs/docs/core/action-bar/examples/action-bar-mobile-example.component.html
libs/docs/core/action-bar/examples/action-bar-no-back-example.component.html
libs/docs/core/calendar/examples/calendar-mobile-example/calendar-mobile-example.component.html
libs/docs/core/list/examples/list-data-example/list-data-example.component.html
libs/docs/core/radio/examples/radio-example.component.html
libs/docs/core/table/examples/table-toolbar-example.component.html
libs/docs/core/textarea/examples/textarea-state-example.component.html
libs/docs/core/toolbar/e2e/toolbar.po.ts
libs/docs/core/toolbar/examples/toolbar-overflow-example.component.html
libs/docs/core/toolbar/examples/toolbar-overflow-grouping-example.component.html
libs/docs/core/toolbar/examples/toolbar-overflow-priority-example.component.html

Refers to https://github.com/SAP/fundamental-ngx/issues/8982
Removed hard-coded content density from some examples where it's not supposed.

fix(docs): removing of hardcoded density

---

libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.ts

closes #9091 
Added live announcer to describe amount of found search results. …

fix(docs): add live announcer for sidebar search

---

libs/core/src/lib/list/list-component.token.ts
libs/core/src/lib/list/list-item/list-item.component.html
libs/core/src/lib/list/list-item/list-item.component.ts
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/list/list-unread-indicator.interface.ts
libs/core/src/lib/list/list.component.spec.ts
libs/core/src/lib/list/list.component.ts
libs/core/src/lib/list/public_api.ts
libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.html
libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.ts
libs/docs/core/list-byline/list-byline-docs.component.html
libs/docs/core/list-byline/list-byline-docs.component.ts
libs/docs/core/list-byline/list-byline-docs.module.ts
libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.html
libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.ts
libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.html
libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.ts
libs/docs/platform/standard-list-item/platform-standard-list-item-docs.module.ts
libs/platform/src/lib/list/base-list-item.ts
libs/platform/src/lib/list/list.component.html
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
package.json
yarn.lock

closes #8874 
Added unread indicator in core's and platform's list components. Applied for byline list item in core and Standard list item in platform.
-   [x] …

feat(core,platform): add unread indicator

---

libs/core/src/lib/scrollbar/scrollbar.component.ts
libs/core/src/lib/wizard/wizard.component.ts
libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts

fix: wizard scroll on top after step change

---

libs/core/src/lib/tabs/tab-list.component.html
libs/docs/core/tabs/e2e/tabs.e2e-spec.ts
libs/docs/platform/dynamic-page/e2e/dynamic-page.e2e-spec.ts

fix(core): removed forbidden aria-selected attribute from div

---

libs/core/src/lib/popover/popover-body/popover-body.component.html

Related to https://github.com/SAP/fundamental-ngx/issues/8897#issuecomment-1361733265

fix(core): fix missing popover arrow

---

libs/core/src/lib/button/button.component.html

Relates to https://github.com/SAP/fundamental-ngx/issues/9011
Feature to have custom icon or any content on button **before** the text.

feat(core): custom icon placement on core button

---

apps/docs/src/styles.scss
e2e/wdio.base-config.js
libs/core/src/lib/popover/popover-body/popover-body.component.scss
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss
libs/fn/src/lib/avatar/avatar.component.scss
libs/fn/src/lib/button/button.component.scss
libs/fn/src/lib/checkbox/checkbox/checkbox.component.scss
libs/fn/src/lib/form/form-control/form-control.component.scss
libs/fn/src/lib/form/form-label/form-label.component.scss
libs/fn/src/lib/generic-tag/generic-tag.component.scss
libs/fn/src/lib/info-label/info-label.component.scss
libs/fn/src/lib/input/input.component.scss
libs/fn/src/lib/message-strip/message-strip.component.scss
libs/fn/src/lib/message-toast/message-toast.component.scss
libs/fn/src/lib/notification/notification.component.scss
libs/fn/src/lib/object-status/object-status.component.scss
libs/fn/src/lib/progress-bar/progress-bar.component.scss
libs/fn/src/lib/radio/radio-button/radio-button.component.scss
libs/fn/src/lib/search/search.component.scss
libs/fn/src/lib/select/select.component.scss
libs/fn/src/lib/slider/slider.component.scss
libs/fn/src/lib/switch/switch.component.scss
libs/fn/src/lib/tabs/tabs/tabs.component.scss
libs/platform/src/lib/menu/menu.component.scss

continuation of [#9080](https://github.com/SAP/fundamental-ngx/pull/9080)
Some imports were left out and are not fixed with this PR

fix(core,fn,docs): fixed incorrect import paths from styles

---

libs/core/src/lib/menu/menu.component.html
package.json
yarn.lock

Refers to https://github.com/SAP/fundamental-ngx/issues/8897#issuecomment-1361911872
this pr applies changes from https://github.com/SAP/fundamental-styles/pull/4136

fix(core): submenu visibility

---

tools/executors/prepare-library/utils/sync-versions.ts

Dependency versions are more permissive now

fix(ci): fixed versions of our 3rd party dependencies

---

libs/core/src/lib/feed-list-item/components/item/feed-list-item.component.html

Refers to https://github.com/SAP/fundamental-ngx/issues/8897#issuecomment-1366010523
Feed List Item more element tab index issue fix.
Not tabbable.
Tabbable.

fix(core): feed list item more el tabindex

---

libs/core/src/lib/timeline/components/timeline-node/timeline-node.component.html

fix(core): remove timeline node tab index

---

libs/cdk/src/lib/forms/cva/cva-control.class.ts
libs/cdk/src/lib/forms/cva/cva.directive.ts
libs/cdk/src/lib/forms/index.ts
libs/core/src/lib/multi-combobox/base-multi-combobox.class.ts
libs/core/src/lib/multi-combobox/multi-combobox.component.ts
libs/docs/cdk/forms/examples/default/forms-default-example.component.ts

Continuation of https://github.com/SAP/fundamental-ngx/pull/9176#issuecomment-1372475329

feat: trying to remove need for inheritance

---

apps/docs/src/assets/images/sapIllus-Spot-NoMail.svg
libs/core/src/lib/illustrated-message/illustrated-message.component.html
libs/core/src/lib/illustrated-message/illustrated-message.component.ts
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
libs/docs/core/illustrated-message/examples/illustrated-message-dot-example.component.html
libs/docs/core/illustrated-message/examples/illustrated-message-dot-example.component.ts
libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
libs/docs/core/illustrated-message/illustrated-message-docs.component.html
libs/docs/core/illustrated-message/illustrated-message-docs.component.ts
libs/docs/core/illustrated-message/illustrated-message-docs.module.ts
package.json
yarn.lock

closes #9114
closes #9173 because styles are updated

feat(core): added illustrated message dot type

---

libs/cdk/src/lib/README.md
libs/core/src/lib/README.md
libs/cx/src/lib/README.md
libs/platform/src/lib/README.md

Tiny fix for readme files for correct build workflow badge

fix: update release badge for correct workflow

---

libs/cx/src/lib/side-navigation/side-navigation.component.scss

fixes none. Missed this in the original PR

fix(cx): css import for side nav

---

README.md

docs(core,platform): add support info in README.md

---

libs/docs/platform/search-field/e2e/search-field.e2e-spec.ts
libs/docs/platform/search-field/examples/platform-search-field-basic-example.component.ts
libs/platform/src/lib/search-field/search-field.component.html
libs/platform/src/lib/search-field/search-field.component.scss
wdio_docs.conf.js

closes https://github.com/SAP/fundamental-ngx/issues/9199
The Search field suggestions menu was not handling properly the case where we have many items. 
Note: the css code is done here as this component is specific for Platform

fix(platform): add fix for Search Field suggestions menu overflow

---

libs/platform/src/lib/form/checkbox/checkbox.component.ts

relates #8963
Changed the description of checked and value input properties to be more clear on what each property does.

fix(platform): more clear typedoc for checkbox component

---

libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.ts
libs/platform/src/lib/form/multi-input/multi-input.module.ts
libs/platform/src/lib/list/base-list-item.ts
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html

closes #9281
- Added checkbox click event for platform list;
- Multi input component now toggles the selection instead of always trying to add item to the selected array
- Now check for selected items happens with comparing the value instead of the label;
- Removed old autofocus in favour of fdkInitialFocus directive.
2. API and …

fix(platform): listen to checkbox changes

---

libs/docs/core/multi-input/examples/multi-input-example/multi-input-example.component.html
libs/docs/core/multi-input/examples/multi-input-example/multi-input-example.component.ts
libs/docs/platform/multi-input/examples/platform-multi-input-example.component.html
libs/docs/platform/multi-input/examples/platform-multi-input-example.component.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts

closes #9280
Added `searchTermChange` output event for platform multi input.

feat(core): add search change event

---

libs/core/src/lib/radio/radio-button/radio-button.component.ts

fix(core): fix radio button reactive touched

---

libs/docs/platform/table/examples/platform-table-columns-ngfor-example.component.html
libs/docs/platform/table/examples/platform-table-columns-ngfor-example.component.ts
libs/docs/platform/table/platform-table-docs.component.html
libs/docs/platform/table/platform-table-docs.component.ts
libs/docs/platform/table/platform-table.module.ts
libs/platform/src/lib/table/components/table-column/table-column.component.ts
libs/platform/src/lib/table/components/table-column/table-column.ts
libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.html
libs/platform/src/lib/table/components/table-p13-dialog/grouping/grouping.component.html
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.html
libs/platform/src/lib/table/components/table-view-settings-dialog/filtering/filters.component.html
libs/platform/src/lib/table/components/table-view-settings-dialog/grouping/grouping.component.html
libs/platform/src/lib/table/components/table-view-settings-dialog/sorting/sorting.component.html
libs/platform/src/lib/table/table.component.spec.ts
libs/platform/src/lib/table/table.component.ts

closes #9311 closes #9212
Added support of dynamically rendered columns in platform table …

feat(platform): dynamic columns support

---

libs/docs/platform/table/e2e/table.e2e-spec.ts
libs/docs/platform/table/examples/platform-table-custom-title-example.component.html
libs/docs/platform/table/examples/platform-table-custom-title-example.component.ts
libs/docs/platform/table/examples/platform-table-default-example.component.html
libs/docs/platform/table/platform-table-docs.component.html
libs/docs/platform/table/platform-table.module.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html

closes #9312
Added example of custom platform table title …

feat(docs): add custom title example

---

libs/cdk/src/lib/utils/drag-and-drop/dnd-item/dnd-item.directive.ts
libs/core/src/lib/segmented-button/segmented-button.component.ts
libs/core/src/lib/token/tokenizer.component.ts
libs/core/src/lib/toolbar/toolbar.component.ts
libs/docs/shared/src/lib/core-helpers/docs-section-title/docs-section-title.component.ts
libs/platform/src/lib/icon-tab-bar/directives/dnd/icon-bar-dnd-item.directive.ts

closes #9224
- Fixed drag&drop memory leak;
- Fixed segmented button memory leaks;
- fixed Tokenizer memory leaks;
- fixed Toolbar memory leaks;
- Fixed documentation website memory leaks

fix: remove memory leaks

---

.github/workflows/on-schedule.yml

disable daily build - further to be deleted with all dependant files

chore(ci): disable visual testing

---

libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts
libs/core/src/lib/action-sheet/action-sheet-item/action-sheet-item.component.ts
libs/core/src/lib/avatar/avatar.component.ts
libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
libs/core/src/lib/calendar/calendar-header/calendar-header.component.ts
libs/core/src/lib/card/card-header.component.ts
libs/core/src/lib/input-group/input-group-directives.ts
libs/core/src/lib/link/link.component.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/object-identifier/object-identifier.component.ts
libs/core/src/lib/radio/radio-button/radio-button.component.ts
libs/core/src/lib/token/tokenizer.component.spec.ts
libs/core/src/lib/token/tokenizer.component.ts
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
libs/docs/core/message-box/e2e/message-box.e2e-spec.ts
libs/fn/src/lib/avatar/avatar.component.ts
libs/fn/src/lib/form/form-control/form-control.component.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/radio-group/radio/radio.component.ts

Changed view child references to element ref for some components to reduce the level of inclusion.

fix(core): use static element ref property

---

libs/docs/core/message-box/e2e/message-box.e2e-spec.ts

Fixes flacky core-message-box e2e tests.

fix(e2e): core message box

---

libs/docs/platform/table/platform-table-docs.component.html
libs/platform/src/lib/table/table.component.html

closes #9115 
- Extended a documentation for scrolling example;
- Added `role="feed"` for the div that responsible for infinite scroll of the table data.

feat(platform): table role feed

---

libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts

fixes none
Type error, possibly related to new dependencies in #9391 but this fixes it ahead of time

fix: type error

---

libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
libs/core/src/lib/form/form-message/form-message.component.scss
libs/core/src/lib/popover/popover-body/popover-body.component.scss
libs/core/src/lib/step-input/step-input.component.scss
libs/docs/core/form-message/e2e/form-message-contents.ts
libs/docs/core/form-message/examples/form-message-example.component.html
libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.html
libs/docs/platform/wizard-generator/e2e/wizard-generator.e2e-spec.ts
libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/combobox/combobox.component.scss
libs/platform/src/lib/form/input-message-group-with-template/input-message-group-with-template.component.scss
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.scss
libs/platform/src/lib/form/step-input/step-input.scss
package.json
yarn.lock

Follow-up https://github.com/SAP/fundamental-styles/pull/4154
Closes none.
Fixes various Form Message related issues.

fix(core,platform): form message issues

---

libs/cdk/src/lib/README.md
libs/core/src/lib/README.md
libs/cx/src/lib/README.md
libs/fn/src/lib/README.md
libs/platform/src/lib/README.md

docs(core): update new component link

---

libs/core/src/lib/table/directives/table-fixed.directive.ts
libs/core/src/lib/table/public_api.ts
libs/core/src/lib/table/table.component.ts
libs/core/src/lib/table/table.module.ts
libs/docs/core/card/examples/card-table-example.component.html
libs/docs/core/shared/src/lib/api-files.ts
libs/docs/core/table/examples/table-fixed-example.component.html
libs/docs/core/table/examples/table-fixed-example.component.ts
libs/docs/core/table/table-docs.component.html
libs/docs/core/table/table-docs.component.ts
libs/docs/core/table/table-docs.module.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts
package.json
yarn.lock

feat(core,platform): update fundamental-styles version, adopt breaking changes

---

libs/docs/platform/table/e2e/table-contents.ts
libs/docs/platform/table/e2e/table.e2e-spec.ts
libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
libs/docs/platform/table/examples/platform-table-groupable-example.component.html
libs/docs/platform/table/examples/platform-table-page-scrolling-example.component.html
libs/platform/src/lib/table/directives/table-cell.directive.ts
libs/platform/src/lib/table/table.component.html

closes #9370
- Added rowIndex property of `*fdpCellDef` directive;
- Updated examples row reflect row index column;
3. …

feat(platform): introduce table row index

---

libs/core/src/lib/avatar/avatar.component.html
libs/core/src/lib/avatar/avatar.component.ts
libs/core/src/lib/list/list-item/list-item.component.html
libs/core/src/lib/list/list-item/list-item.component.ts
libs/docs/platform/standard-list-item/examples/platform-standard-list-item-border-less-example.component.html
libs/docs/platform/standard-list-item/examples/platform-standard-list-item-border-less-example.component.ts
libs/platform/src/lib/approval-flow/approval-flow-user-list/approval-flow-user-list.component.ts
libs/platform/src/lib/list/action-list-item/action-list-item.component.ts
libs/platform/src/lib/list/base-list-item.ts
libs/platform/src/lib/list/display-list-item/display-list-item.component.ts
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/list/object-list-item/object-list-item.component.html
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.html
libs/platform/src/lib/list/standard-list-item/standard-list-item.component.ts

closes #9279 
- Added ability to pass all avatar parameters to platform list item component; …

feat(platform): pass avatar properties

---

libs/core/src/lib/layout-panel/layout-panel-footer/layout-panel-footer.component.spec.ts
libs/core/src/lib/layout-panel/layout-panel-footer/layout-panel-footer.component.ts
libs/core/src/lib/layout-panel/layout-panel-title/layout-panel-title.directive.spec.ts
libs/core/src/lib/layout-panel/layout-panel-title/layout-panel-title.directive.ts
libs/core/src/lib/layout-panel/layout-panel.component.scss
libs/core/src/lib/layout-panel/layout-panel.component.spec.ts
libs/core/src/lib/layout-panel/layout-panel.component.ts
libs/docs/core/layout-panel/examples/layout-panel-footer-variations-example.component.html
libs/docs/core/layout-panel/examples/layout-panel-footer-variations-example.component.ts
libs/docs/core/layout-panel/examples/layout-panel-transparent-example.component.html
libs/docs/core/layout-panel/examples/layout-panel-transparent-example.component.ts
libs/docs/core/layout-panel/layout-panel-docs.component.html
libs/docs/core/layout-panel/layout-panel-docs.component.ts
libs/docs/core/layout-panel/layout-panel-docs.module.ts

closes none
- update the component and its elements to the latest changes introduced in Fundamental-styles
- update the documentation with more examples

fix(core): update Layout Panel to latest design

---

libs/docs/core/table/examples/table-toolbar-example.component.html
libs/platform/src/lib/table/table.component.html

fixes #9465 
Some minor tweaks to header visuals to match the specs

fix(core,platform,docs): minor tweaks to table header styles

---

package.json
yarn.lock

upgrade theming-base-content version 11.2.1

chore(deps): upgrade theming-base-content version 11.2.1

---

libs/core/src/lib/dialog/dialog.component.html

fix(core): dialog should be scrollable if needed

---

libs/cdk/src/lib/utils/functions/index.ts
libs/cdk/src/lib/utils/functions/is-odd.ts
libs/core/src/lib/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
libs/core/src/lib/dialog/dialog.component.scss
libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
libs/core/src/lib/illustrated-message/illustrated-message.component.ts
libs/core/src/lib/link/link.component.html
libs/core/src/lib/link/link.component.scss
libs/core/src/lib/list/list-component.interface.ts
libs/core/src/lib/list/list-component.token.ts
libs/core/src/lib/list/list-item/list-item.component.html
libs/core/src/lib/list/list-item/list-item.component.ts
libs/core/src/lib/multi-combobox/multi-combobox.component.ts
libs/core/src/lib/popover/base/base-popover.class.ts
libs/core/src/lib/popover/popover-service/popover.service.spec.ts
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/core/src/lib/segmented-button/segmented-button.component.spec.ts
libs/core/src/lib/segmented-button/segmented-button.component.ts
libs/core/src/lib/select/option/option.component.html
libs/core/src/lib/select/option/option.component.ts
libs/core/src/lib/text/text.component.html
libs/core/src/lib/text/text.component.spec.ts
libs/core/src/lib/timeline/timeline.component.ts
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
libs/docs/core/form-message/examples/form-message-example.component.html
libs/docs/core/form-message/examples/state-message/form-messaging-state-example.component.html
libs/docs/core/grid-list/grid-list-docs.component.ts
libs/docs/core/schema/src/lib/switch.schema.ts
libs/docs/core/switch/switch-docs.component.html
libs/docs/core/switch/switch-docs.component.ts

fixes #9552
- Fixed dialog 100% width and height;
- Fixed dialog double scrollbar when resizer is visible;
- Fixed illustrated message with async svg config;
- Fixed core list item and unread indicator;
- Fixed switch docs schema;
- Fixed timeline vertical line overflowing the icon;
- Fixed segmented button initial state and highlighting selected button;

fix(core): various bugfixes

---

libs/core/src/lib/form/form-label/form-label.component.ts
libs/docs/core/form-message/e2e/form-message-contents.ts
libs/docs/core/input/e2e/input.e2e-spec.ts

Fixed failing core-input and core-form-message e2e tests

fix(e2e): fix failing e2e tests

---

libs/core/src/lib/scrollbar/scrollbar.directive.ts

closes #9515 
Yeah, the title is self-explanatory, [additional info](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet#browser_compatibility)

fix(core): replaced CSSStyleSheet with ordinary style

---

.github/actions/bump-version/index.js
.github/actions/nodejs/action.yml
.github/actions/update-version-on-main/action.yml
.github/workflows/create-hotfix.yml
.github/workflows/create-release.yml
.github/workflows/update-versions.yml

closes none
some version updates and minor fixes

fix(ci): various ci updates

---

libs/platform/src/lib/table/table.component.html

fix(platform): keyboard support for sort popovers

---

libs/core/src/lib/avatar/avatar.component.ts
libs/docs/core/avatar/examples/avatar-accent-colors-example.component.ts
libs/docs/core/avatar/examples/avatar-background-image-example.component.ts
libs/docs/core/avatar/examples/avatar-borders-example.component.ts
libs/docs/core/avatar/examples/avatar-circle-example.component.ts
libs/docs/core/avatar/examples/avatar-default-image-with-alternative-options-example.component.ts
libs/docs/core/avatar/examples/avatar-icon-example.component.ts
libs/docs/core/avatar/examples/avatar-initials-example.component.ts
libs/docs/core/avatar/examples/avatar-placeholder-example.component.ts
libs/docs/core/avatar/examples/avatar-tile-example.component.ts
libs/docs/core/avatar/examples/avatar-transparent-example.component.ts
libs/docs/core/avatar/examples/avatar-zoom-icon-example.component.ts

closes #9558 
- Changed HostBinding to renderer.setStyle. This way we don't need to change any of our markup, yet, styling will be applied appropriately;
- Reduced cdr calls amount;
- Marked all avatar example components with `ChangeDetectionStrategy.OnPush`
-   [x] check for console logs (warnings, …

fix(core): use renderer instead of cdr

---

libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.scss

fixes #9439 
stricter stylings for hidden label in value help dialog

fix: value help dialog hidden label

---

libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
libs/docs/shared/src/lib/core-helpers/code-example/code-example.component.html
libs/docs/shared/src/lib/core-helpers/code-example/code-example.component.ts
libs/docs/shared/src/lib/core-helpers/code-example/example-file.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz.service.ts
libs/docs/shared/src/lib/getAsset.ts
libs/docs/shared/src/lib/shared-documentation-page.module.ts

closes probably none
This PR adds functionality to loading code examples on demand

chore(docs): added lazy load of the code examples

---

libs/fn/src/lib/avatar/project.json
libs/fn/src/lib/button/project.json
libs/fn/src/lib/cdk/project.json
libs/fn/src/lib/checkbox/project.json
libs/fn/src/lib/form/project.json
libs/fn/src/lib/generic-tag/project.json
libs/fn/src/lib/info-label/project.json
libs/fn/src/lib/input/project.json
libs/fn/src/lib/list/project.json
libs/fn/src/lib/message-strip/project.json
libs/fn/src/lib/message-toast/project.json
libs/fn/src/lib/notification/project.json
libs/fn/src/lib/object-status/project.json
libs/fn/src/lib/progress-bar/project.json
libs/fn/src/lib/radio/project.json
libs/fn/src/lib/search/project.json
libs/fn/src/lib/segmented-button/project.json
libs/fn/src/lib/select/project.json
libs/fn/src/lib/slider/project.json
libs/fn/src/lib/switch/project.json
libs/fn/src/lib/tabs/project.json
libs/fn/src/lib/utils/project.json

Removed redundant runs for the library, which is not maintained anymore

chore(fn): remove fn targets

---

libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.scss
libs/platform/src/lib/table/table.component.scss

closes #9573
closes #9503
- Added styling for cases when semantic table has no vertical borders;
- Fixed issue with rendering resize handle of platform table with black border (artifact from newer version of fundamental-styles);
-   [x] API boundary …

fix(platform): semantic borderless example

---

package.json
yarn.lock

closes #9629
Updated fundamental-styles version to the latest stable release

chore: update fundamental-styles

---

libs/core/src/lib/segmented-button/segmented-button.component.spec.ts

Small improvement to keep track on correct CVA implementation

feat(core): add cva tests for segmented button

---

libs/docs/platform/settings-generator/examples/default/settings-generator-default-example.component.ts
libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.ts
libs/docs/platform/settings-generator/examples/message-popover/settings-generator-message-popover-example.component.ts

fix a type in settings generator doc

docs(platform): fix a type in settings generator

---

libs/core/src/lib/popover/base/base-popover.class.ts
libs/core/src/lib/popover/popover-service/popover.service.spec.ts
libs/core/src/lib/popover/popover-service/popover.service.ts

closes #9624
The `appendTo` is never assigned to the service scope, so it is always `undefined` when the `_getPositionStrategy` checks for it, meaning it will always attach it to the trigger element.
There is some padding around the trigger button which makes it a bit confusing to noticed. The screenshot below is without the padding and without the `display: block`:
-   [x] Mouse vs. …

fix(core): attach popover to different container via append to

---

libs/platform/src/lib/table/table.component.ts

fix(platform): automatically sticky table header

---

libs/cx/src/lib/side-navigation/side-navigation.component.scss
libs/docs/platform/link/e2e/link.e2e-spec.ts
package.json
yarn.lock

closes #9691
Updated @fundamental-styles/cx version which brings new functionality of the content-density

fix(cx): updated styles version and fixed side nav content density

---

libs/docs/platform/table/platform-table-docs.component.html
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts

fix(platform): add input to disable drag and drop

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

fix(platform): only scroll freezable cells when using l/r keyboard buttons, freezable column width not updating on table data load

---

libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/input-group/input-group-directives.ts
libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/input-group/input-group.component.ts
libs/core/src/lib/input-group/input-group.module.ts
libs/core/src/lib/multi-combobox/base-multi-combobox.class.ts
libs/core/src/lib/multi-combobox/multi-combobox.component.scss
libs/core/src/lib/multi-combobox/multi-combobox.component.ts
libs/core/src/lib/multi-input/multi-input.component.scss
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/token/tokenizer.component.scss
libs/docs/core/combobox/combobox-docs.component.html
libs/docs/core/multi-combobox/multi-combobox-docs.component.html
libs/docs/core/multi-input/multi-input-docs.component.html
libs/docs/platform/combobox/platform-combobox-docs.component.html
libs/docs/platform/multi-combobox/platform-multi-combobox-docs.component.html
libs/docs/platform/multi-input/platform-multi-input-docs.component.html
libs/platform/src/lib/form/combobox/commons/base-combobox.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.ts

closes #9686
- Fixed keyboard navigation for core/platform combobox;
- Fixed keyboard navigation for core/platform multi-input;
- Fixed keyboard navigation for core/platform multi-combobox;
- Dropdown button for core/platform combobox, multi-input, multi-combobox is now not focusable same way as in ui5;
- Previously, if user clicked on the dropdown button, we opened the dropdown and placed focus on the first dropdown list item. Now when user clicks on the dropdown button, we place focus on the input field.
- All core/platform combobox, multi-input and multi-combobox components now follow same keyboard navigation logic: when focusing the input field and pressing alt key + arrow down, we open the dropdown and shift focus on the first item of the dropdown list.
-   [x] …

fix(core,platform): multi combobox/input keyboard behaviour

---

libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts
libs/docs/platform/approval-flow/e2e/approval-flow.po.ts
libs/docs/platform/approval-flow/examples/platform-approval-flow-custom-status-example.component.html
libs/docs/platform/approval-flow/examples/platform-approval-flow-custom-status-example.component.ts
libs/docs/platform/approval-flow/platform-approval-flow-docs.component.html
libs/docs/platform/approval-flow/platform-approval-flow-docs.component.ts
libs/docs/platform/approval-flow/platform-approval-flow-docs.module.ts
libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.html
libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.ts
libs/platform/src/lib/approval-flow/approval-flow.component.html
libs/platform/src/lib/approval-flow/approval-flow.component.ts
libs/platform/src/lib/approval-flow/interfaces/approval-status.ts

closes #9518
Introduced custom status labels and custom color mapping for the approval flow. 
-   [X] the commit message(s) follows the guideline:
-   [X] tests for the changes that have been done
-   [X] all items on the PR Review Checklist are addressed :
-   [x] Run npm run build-pack-library and test in external application
-   [x] update `README.md`
-   [x] [Breaking Changes Wiki](https://github.com/SAP/fundamental-ngx/wiki/Breaking-Changes)

fix(platform): custom status for approval flow

---

libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html

duplicate to https://github.com/SAP/fundamental-ngx/pull/9690
closes #9688

fix(core): fix grid list item semantic colors

---

libs/core/src/lib/scrollbar/scrollbar.directive.ts

fixes #9637 
Closed the previous PR which was a temp fix

fix(core): fd-scrollbar should prevent scroll event from bubbling

---

translation_v2.json

fix: testing translation_v2

---

package.json
yarn.lock

upgrade theming-base-content version 11.3.2

chore(deps): upgrade theming-base-content version 11.3.2

---

libs/docs/platform/table/platform-table-docs.component.html
libs/platform/src/lib/table/models/table-rows-rearrange-event.model.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

fixes #9463 
I will draft up some examples of how this could work

fix(platform): open up drag and drop to sorting/filtering/etc

---

libs/platform/src/lib/table/table.component.scss

closes #9719 
relates #9749
Applied indentation according to design guidelines.

fix(platform): fix table indentation

---

libs/core/src/lib/bar/bar.component.ts
libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.ts
libs/core/src/lib/dialog/dialog.component.ts
libs/core/src/lib/input-group/input-group.component.scss
libs/core/src/lib/menu/menu-mobile/menu-mobile.component.ts
libs/core/src/lib/multi-combobox/mobile/mobile-multi-combobox.component.ts
libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
libs/core/src/lib/select/select-mobile/select-mobile.component.ts
libs/platform/src/lib/form/combobox/combobox-mobile/combobox/combobox-mobile.component.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox-mobile/multi-combobox/multi-combobox-mobile.component.ts
libs/platform/src/lib/form/multi-input/multi-input-mobile/multi-input-mobile.component.ts
libs/platform/src/lib/search-field/search-field-mobile/search-field/search-field-mobile.component.ts
libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.ts
libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts

fix: various dialog fixes

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.spec.ts

fix(platform): failing combobox unit test

---

libs/cdk/src/lib/utils/toast/base-toast-positions.ts
libs/cdk/src/lib/utils/toast/base-toast.service.ts
libs/cdk/src/lib/utils/toast/classes/base-toast-ref.ts
libs/docs/core/message-toast/examples/message-toast-position-example.component.html
libs/docs/core/message-toast/examples/message-toast-position-example.component.ts

closes #9909
- Changed logic of defining global position of a toast. Now for global position it can accept `ConnectedPosition` with `boundTo` property of an anchor element;
- Added example of a bound to a button message toast
-   [x] API boundary …

feat(core): message toast bound to element

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.ts

fix(platform): bug where combobox selection event fires twice

---

libs/cdk/src/lib/utils/dynamic-component/dynamic-component-container.ts
libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
libs/core/src/lib/message-box/message-box-container/message-box-container.component.ts

fix(core,cdk): markForCheck after attaching portal

---

libs/core/src/lib/table/table.component.scss

fixes none. as discussed with @droshev we need this now, before we can update styles version

fix(core): hardcode table css prop

---

apps/docs/src/app/platform/documentation/platform-documentation-data.ts
libs/docs/platform/table/child-docs/preserving-state/preserved-state-docs.component.html
libs/docs/platform/table/child-docs/preserving-state/preserved-state-docs.component.ts
libs/docs/platform/table/examples/platform-table-p13-group-example.component.ts
libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html
libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts
libs/docs/platform/table/platform-table.module.ts
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filter-rule.component.html
libs/platform/src/lib/table/table.component.ts

closes #9752
- Added ability to set initial page for the platform table;
- Added ability to set initial `expanded` state of the row;
- Added ability to load pages before initial page (works in conjunction with `pageScrolling` input property);
- Added output event for pagination state changes;
- Added output event for table scrollable body scroll;
- Added output event for cases when new table rows are being rendered;
- Added example showing how to preserve the table state and data, and restore it when table is re-initialized;
- `fixed p13 filter dialog fields vertical alignment.
-   [x] Content Density …

feat(platform,docs): table preserved state

---

libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html

show the current version on the doc

docs(core,platform): show the current version on the doc

---

libs/core/src/lib/radio/radio-button/radio-button.component.html

closes #9851
[Only one minor change was needed ](https://github.com/SAP/fundamental-styles/wiki/Breaking-Changes#radio-button-4501)

chore(core): radio button changes adoption

---

package.json
yarn.lock

theming-base-content version 11.4.2

chore(deps): theming-base-content version 11.4.2

---

libs/core/src/lib/select/select.component.ts

fix(core): select focus on page load bug

---

libs/core/src/lib/popover/popover-body/popover-body.component.ts

closes #9747
Temporarily added class name mapper until the https://github.com/SAP/fundamental-styles/pull/4569 is merged and styles are updated in the fd-ngx

fix(core): fixed popover arrow placement

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.module.ts

fix(platform): do not use fdkClicked

---

libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.module.ts

fix(core): localize combobox addon button

---

libs/core/src/lib/token/tokenizer.component.html
libs/core/src/lib/token/tokenizer.component.ts

fixes #10051 
also a bug where "0 more" text could appear in the tokenizer

fix(core): tokenizer bug when removing tokens

---

libs/core/src/lib/checkbox/checkbox/checkbox.component.html
libs/core/src/lib/grid-list/components/grid-list-item/grid-list-item.component.html
libs/docs/core/grid-list/e2e/grid-list.po.ts
libs/docs/platform/approval-flow/e2e/approval-flow.po.ts

will be needed for https://github.com/SAP/fundamental-styles/pull/4608
I am fairly sure this can be merged right away without needing hardcoded css from the aforementioned pr

fix(core): new checkbox hidden element for a11y

---

libs/docs/core/alert/alert-docs.component.html
libs/docs/core/button/button-docs.component.html
libs/docs/core/dialog/dialog-docs.component.html
libs/docs/core/input-group/input-group-docs.component.html
libs/docs/core/pagination/pagination-docs.component.html
libs/docs/core/slider/slider-docs.component.html
libs/docs/core/switch/switch-docs.component.html
libs/docs/core/tabs/tabs-docs.component.html
libs/docs/platform/slider/slider-docs.component.html
libs/docs/platform/table/platform-table-docs.component.html
libs/docs/shared/src/lib/core-helpers/playground/playground.component.html

closes #9396
Allow the playground to have link

docs(core,platform): add link to the playground examples

---

README.md
apps/docs/src/index.html
libs/core/src/lib/README.md
libs/platform/src/lib/README.md

docs(core,platform): minor doc updates

---

libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.html
libs/docs/platform/table/examples/preserved-state/platform-table-preserved-state-example.component.ts
libs/platform/src/lib/table-helpers/helpers.ts

closes #9928
- Added 1s delay for the example;
- Fixed issue with incorrect scroll position when dataSource has some delay in data retrieval;
- Fixed issue with calculating `hidden` state of the child rows;
-   [x] …

fix(platform): preserved state fixes

---

libs/platform/src/lib/table-helpers/models/table-row.model.ts
libs/platform/src/lib/table/table.component.ts

closes #10095 
- Fixed collapse/expand all functionality
- Added event emitters for those 2 methods …

fix(platform): fix expand all functionality

---

libs/docs/platform/table/examples/platform-table-freezable-example.component.html
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss

closes #9927 
- Added mock element that mimics focus outline for the table tbody
- Updated freezable columns example to reflect this change.
-   [x] change the API …

fix(platform): table tbody focus

---

libs/core/src/lib/dynamic-page/directives/dynamic-page-header-subtitle.directive.ts
libs/core/src/lib/dynamic-page/directives/dynamic-page-header-title.directive.ts
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.spec.ts
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
libs/core/src/lib/dynamic-page/dynamic-page.module.ts
libs/core/src/lib/dynamic-page/index.ts
libs/core/src/lib/dynamic-page/models/title-directive-context.ts
libs/docs/core/dynamic-page/dynamic-page-docs.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.ts
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.scss
libs/platform/src/lib/dynamic-page/directives/dynamic-page-header-subtitle.directive.ts
libs/platform/src/lib/dynamic-page/directives/dynamic-page-header-title.directive.ts
libs/platform/src/lib/dynamic-page/dynamic-page-header/title/dynamic-page-title.component.ts
libs/platform/src/lib/dynamic-page/dynamic-page.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.module.ts
libs/platform/src/lib/dynamic-page/index.ts

closes #9929
Introducing custom _subtitle template_ that can be added to the `DynamicPage` header. this will allow application developer to customize and extends subtitle 
-   [x] different combinations of components - free …

feat(platform,core): custom title and subtitle template for dynamic page

---

libs/cdk/src/lib/utils/components/dynamic-portal/dynamic-portal.component.ts
libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.spec.ts
libs/core/src/lib/busy-indicator/busy-indicator-extended/busy-indicator-extended.directive.ts
libs/core/src/lib/busy-indicator/busy-indicator.component.spec.ts
libs/core/src/lib/busy-indicator/busy-indicator.component.ts
libs/core/src/lib/busy-indicator/busy-indicator.module.ts
libs/core/src/lib/dialog/dialog-body/dialog-body.component.html
libs/core/src/lib/dialog/dialog.module.ts
libs/core/src/lib/dialog/utils/dialog-ref.class.ts
libs/core/src/lib/link/link.component.spec.ts
libs/core/src/lib/link/link.component.ts
libs/core/src/lib/link/link.module.ts
libs/core/src/lib/object-identifier/object-identifier.component.spec.ts
libs/core/src/lib/text/text.component.spec.ts
libs/core/src/lib/text/text.component.ts
libs/core/src/lib/text/text.module.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.spec.ts
libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.ts
libs/i18n/src/lib/directives/patch-language.directive.ts
libs/i18n/src/lib/i18n.module.ts
libs/i18n/src/lib/pipes/fd-translate.pipe.ts

closes #9827
part of #9823 
Migrated some parts to standalone and updated busy indicator. added example to the dialog module for added example on fd-styles side

feat(core): busy indicator horizon

---

libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

fix(platform): table checkbox space scroll bug

---

libs/core/src/lib/slider/deprecated-slider-cozy.directive.ts
libs/core/src/lib/slider/slider-position.directive.ts
libs/core/src/lib/slider/slider.component.html
libs/core/src/lib/slider/slider.component.spec.ts
libs/core/src/lib/slider/slider.component.ts
libs/core/src/lib/slider/slider.model.ts
libs/core/src/lib/slider/slider.module.ts
libs/docs/core/schema/src/lib/slider.schema.ts
libs/docs/core/slider/examples/index.ts
libs/docs/core/slider/examples/vertical/vertical-slider-example.component.html
libs/docs/core/slider/examples/vertical/vertical-slider-example.component.ts
libs/docs/core/slider/slider-docs.component.html
libs/docs/core/slider/slider-docs.component.ts
libs/docs/platform/schema/schemas/slider-schema.ts
libs/docs/platform/slider/slider-docs.component.html
libs/docs/platform/slider/slider-docs.component.ts
libs/platform/src/lib/slider/slider.component.html
libs/platform/src/lib/slider/slider.component.spec.ts
libs/platform/src/lib/slider/slider.component.ts
libs/platform/src/lib/slider/slider.module.ts

closes #9854 
- Added vertical slider appearance;
- Added range group draggable section;
- Refactored some of the methods to be more performant;
- Reverted dayjs version bump due to wrong formatting
-   [x] different …

feat(core,platform): slider horizon update

---

package.json
yarn.lock

update to theming-base-content v.11.6.1

chore(deps): update to theming-base-content v.11.6.1

---

lerna.json
libs/cdk/src/lib/package.json
libs/core/src/lib/package.json
libs/cx/src/lib/package.json
libs/datetime-adapter/package.json
libs/fn/src/lib/package.json
libs/i18n/package.json
libs/moment-adapter/package.json
libs/platform/src/lib/package.json

Synchronized versions across the library

chore: synchronized versions

---

.github/actions/npm-publish/index.js

Removed dry run from the publish script, which needed to be removed after replacement of the environment

chore: removed hardcoded dry-run from publish script

---

libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
libs/core/src/lib/message-box/message-box-container/message-box-container.component.ts

fix(core): remove manual change detection from dialog container

---

libs/core/src/lib/tabs/tab-list.component.ts
libs/core/src/lib/tabs/tab-panel/tab-panel.component.ts

fix(core): add option to focus first focusable element in tab panel when using stacked tabs

---

libs/platform/src/lib/table/components/table-row/table-row.component.html

fix(platform): line break in template adding whitespace to table text

---

libs/core/src/lib/button/button.component.html

closes #10186 
- Fixed case when icon position is 'after' and button has projected text …

fix(core): correct icon placement

---

libs/docs/shared/src/lib/core-helpers/code-snippet/code-snippet.component.ts

closes #10219
- Added handler for the observable code content

fix(docs): highlight async content

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.ts
libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-condition-field/smart-filter-bar-condition-field.component.html
libs/platform/src/lib/smart-filter-bar/smart-filter-bar.component.html

closes #10182 
- Added aria-label for the 'Refresh' button;
- Added aria-label for the field condition dialog opener button …

fix(platform): add missing labels

---

apps/docs/project.json
libs/docs/i18n/examples/i18n-translation-customization-example/i18n-translation-customization-example.component.html
libs/docs/i18n/platform-i18n-docs.component.ts

closes #10199 
Fixed issue with  i18n example source file path.

fix(docs): i18n example sources

---

libs/core/src/lib/wizard/wizard.module.ts
libs/docs/core/wizard/examples/loading/wizard-loading-example.component.ts
libs/docs/core/wizard/examples/wizard-branching-example.component.ts
libs/docs/core/wizard/examples/wizard-customizable-example.component.ts
libs/docs/core/wizard/examples/wizard-dialog-example.component.ts
libs/docs/core/wizard/examples/wizard-example.component.ts
libs/docs/core/wizard/examples/wizard-mobile-example.component.ts
libs/docs/core/wizard/examples/wizard-ngfor-example.component.ts
libs/docs/core/wizard/examples/wizard-visible-summary-example.component.ts

closes #9862
`WizardModule` now provides `WizardService`

fix(core): provided wizard service

---

libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.scss
libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
libs/core/src/lib/popover/base/base-popover.class.ts
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/docs/core/form-message/examples/form-message-example.component.html
libs/docs/core/form-message/examples/form-message-example.component.ts
libs/docs/core/list/examples/list-example.component.html
libs/docs/core/list/examples/list-examples.component.ts
libs/docs/core/list/list-docs.module.ts

closes #9666
Added ability to pass `ElementRef` as a container target for the popover for the form message component.
3. …

feat(core): form message popover placement

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/table/components/table-row/table-row.component.html

fix(platform): add new strings for platform table single selection cells

---

libs/cdk/src/lib/package.json
libs/cdk/src/lib/utils/services/themes.service.ts
libs/core/schematics/add-dependencies/index.ts
libs/core/src/lib/action-bar/action-bar.component.ts
libs/core/src/lib/alert/alert-service/alert.service.ts
libs/core/src/lib/alert/alert-utils/alert-config.ts
libs/core/src/lib/alert/alert-utils/alert-container.component.ts
libs/core/src/lib/alert/alert-utils/alert-ref.ts
libs/core/src/lib/alert/alert.component.ts
libs/core/src/lib/alert/alert.module.ts
libs/core/src/lib/package.json
libs/core/src/lib/side-navigation/side-navigation.component.ts
libs/core/src/lib/splitter/splitter-pagination/splitter-pagination.component.ts
libs/fn/src/lib/form/form-label/form-label.component.ts
libs/moment-adapter/package.json
libs/moment-adapter/src/lib/moment-datetime-adapter.ts
libs/moment-adapter/src/lib/moment-datetime.module.ts
libs/platform/src/lib/action-bar/action-bar.component.ts
libs/platform/src/lib/approval-flow/approval-flow.component.ts
libs/platform/src/lib/form/select/commons/base-select.ts
libs/platform/src/lib/package.json
libs/platform/src/lib/page-footer/page-footer.component.ts
libs/platform/src/lib/thumbnail/thumbnail-details/thumbnail-details.component.ts
libs/platform/src/lib/thumbnail/thumbnail-image/thumbnail-image.component.ts
libs/platform/src/lib/thumbnail/thumbnail.component.ts
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.ts
package.json
yarn.lock

`deprecated-decorator` was causing too much of issues. removed it

fix: removed `deprecated-decorator`

---

libs/nx-plugin/src/generators/sap-component/generator.ts

fix: project generator using wrong path for fn and platform

---

libs/docs/core/message-strip/examples/message-strip-auto-dismiss-example.component.ts
libs/docs/core/message-strip/message-strip-docs.component.html
libs/docs/core/message-strip/message-strip-docs.component.ts
libs/docs/core/message-strip/message-strip-docs.module.ts
libs/docs/core/shared/src/lib/api-files.ts

Added auto dismiss example to the message strip docs and added missing classes from the list of the message strip API tab

chore(docs): added example of the auto dismiss to the message strip docs

---

commitlint.config.js

fix: add shared to scope-enum

---

libs/docs/shared/NEW_COMPONENT.md

Related to issue https://github.com/SAP/fundamental-ngx/issues/6495

docs(core): updated new component readme

---

apps/docs/src/app/app.module.ts
libs/docs/shared/src/index.ts
libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html
libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
libs/docs/shared/src/lib/services/docs.service.ts
libs/docs/shared/src/lib/shared-documentation.module.ts
libs/docs/shared/src/lib/tokens/lerna-json.token.ts
libs/docs/shared/src/lib/utilities/libraries.ts

fix(docs): fixed docs current version value

---

CONTRIBUTING.md

fix(docs): update contributing docs

---

libs/core/src/lib/avatar/avatar.component.html
libs/core/src/lib/carousel/carousel.component.html
libs/core/src/lib/date-picker/date-picker.component.html
libs/core/src/lib/illustrated-message/illustrated-message.component.html
libs/core/src/lib/scrollbar/scrollbar.directive.ts
libs/core/src/lib/time-picker/time-picker.component.html
libs/core/src/lib/upload-collection/upload-collection-form-item/upload-collection-form-item.component.html
libs/core/src/lib/wizard/wizard-step-indicator/wizard-step-indicator.component.html
libs/platform/src/lib/approval-flow/approval-flow.component.html
libs/platform/src/lib/form/form-generator/form-generator/form-generator.component.html
libs/platform/src/lib/form/form-group/form-field/form-field.component.html
libs/platform/src/lib/list/list.component.html
libs/platform/src/lib/settings-generator/layouts/settings-generator-sidebar-layout/settings-generator-sidebar-layout.component.html
libs/platform/src/lib/settings-generator/settings-generator-content/settings-generator-content.component.html
libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-conditions-dialog/smart-filter-bar-conditions-dialog.component.html
libs/platform/src/lib/smart-filter-bar/components/smart-filter-bar-settings-dialog/smart-filter-bar-settings-dialog.component.html
libs/platform/src/lib/split-menu-button/split-menu-button.component.html
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
libs/platform/src/lib/table/components/table-row/table-row.component.html
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html
libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
libs/platform/src/lib/wizard-generator/components/wizard-summary-step/wizard-summary-section/wizard-summary-section.component.html

closes #10347
- Fixed issue with style element of scrollbar directive;
- Migrated all `style` attributes to `[style...]` in order to set styling via JavaScript (Style attribute is blocked by this policy, and the only way is to use js instead)

fix(core,platform): fix csp style-src

---

libs/core/src/lib/rating-indicator/components/rating-indicator.component.html
libs/docs/core/rating-indicator/e2e/rating-indicator.po.ts

closes none
fix the aria-label for rating-indicator

fix(core): correct aria-label for rating-indicator

---

libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.html
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts

closes #10386 
Downporting the feature request

feat(core): removed addon button on mobile mode in multi-input

---

libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.ts
libs/platform/src/lib/table/components/table-toolbar/table-toolbar.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

closes #10283
added `aria-labelledby` to the table

feat(platform): added aria-labelledby to the table

---

libs/platform/src/lib/table/table.component.html

Cherry pick of https://github.com/SAP/fundamental-ngx/pull/10440

fix(platform): cell height instead of tbody

---

libs/platform/src/lib/table/table.component.ts

Cherry pick of https://github.com/SAP/fundamental-ngx/pull/10439

fix(platform): custom row height (#10439)

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts

fix(core): localize tokenizer more label #10106

---

e2e/tsconfig.json
libs/docs/platform/multi-combobox/e2e/multi-combobox.e2e-spec.ts
libs/docs/platform/multi-combobox/e2e/tsconfig.json
libs/docs/platform/multi-combobox/examples/multi-combobox-remote-datasource/multi-combobox-remote-datasource-example.component.ts
libs/docs/platform/multi-combobox/platform-multi-combobox-docs.component.html
libs/docs/platform/multi-combobox/platform-multi-combobox-docs.component.ts
libs/docs/platform/multi-combobox/platform-multi-combobox-docs.module.ts
libs/docs/platform/wizard-generator/e2e/wizard-generator.po.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts

closes #10377
Downport of the  https://github.com/SAP/fundamental-ngx/pull/10456

fix(platform): fixed multi combobox async value selection token

---

libs/core/src/lib/button/base-button.ts
libs/core/src/lib/button/button.component.ts
libs/docs/platform/wizard-generator/e2e/wizard-generator.po.ts

fix(core): move button type to aria-description #10292

---

libs/platform/src/lib/search-field/search-field.component.html

fix(platform): search field a11y fixes

---

libs/cdk/src/lib/utils/drag-and-drop/dnd-list/dnd-list.directive.ts
libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.html
libs/platform/src/lib/table-helpers/directives/table-draggable.directive.ts
libs/platform/src/lib/table-helpers/table.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.ts

Downport of https://github.com/SAP/fundamental-ngx/pull/10476

fix(platform): fix dragdrop with virtual scroll

---

libs/core/src/lib/multi-input/multi-input.component.html

fix(core): add aria-multiselectable to multi input options list

---

libs/core/src/lib/wizard/wizard.component.scss

Related to issue https://github.com/SAP/fundamental-ngx/issues/10027
Fixed an issue where .fd-scollbar was not properly encapsulated

fix(core): fixed issue with styling encapsulation

---

libs/cdk/src/lib/utils/directives/auto-complete/auto-complete.directive.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts
libs/docs/core/multi-input/examples/multi-input-async-example/multi-input-async-example.component.ts
libs/docs/core/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts
libs/docs/core/multi-input/examples/multi-input-option-item-example/multi-input-option-item-example.component.ts
libs/docs/core/multi-input/multi-input-docs.component.html
libs/docs/core/multi-input/multi-input-docs.component.ts
libs/docs/core/multi-input/multi-input-docs.module.ts
libs/docs/platform/form-generator/e2e/form-generator.e2e-spec.ts

closes
This is a downport request to ng15 of the feature in #10415

feat(core): added ability to pass OptionItem to multi-input

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/table/components/table-row/table-row.component.html
libs/platform/src/lib/table/components/table-row/table-row.component.ts

Downport of https://github.com/SAP/fundamental-ngx/pull/10486

fix(platform): row selection tooltip

---

libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.ts
libs/platform/src/lib/table/table.module.ts

fix(platform): table header cells without popovers should have aria-haspopup false

---

libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.model.ts

Downport of https://github.com/SAP/fundamental-ngx/pull/10505

fix(platform): table boolean filter reset

---

libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts

Downport of https://github.com/SAP/fundamental-ngx/pull/10498

fix(core): childless list item aria-expanded

---

libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts
libs/platform/src/lib/table-helpers/table-column.ts
libs/platform/src/lib/table/components/table-group-row/table-group-row.component.html
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html

closes #10212
Downport of the #10423

feat(platform): always showing title on the thead contents

---

libs/platform/src/lib/table/components/table-row/table-row.component.html
libs/platform/src/lib/table/components/table-row/table-row.component.ts
libs/platform/src/lib/table/table.component.html

closes #10261 
Downport of #10480

feat(platform): table tree nodes are operable using left and right arrow keys

---

.prettierignore
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.ts

closes #10201
Downport of the #10428

fix(platform): hiding selection column when data is not visible

---

libs/core/src/lib/list/list.component.spec.ts
libs/core/src/lib/list/list.component.ts
libs/platform/src/lib/list/action-list-item/action-list-item.component.spec.ts
libs/platform/src/lib/list/list.component.html
libs/platform/src/lib/list/list.component.ts

Downport of https://github.com/SAP/fundamental-ngx/pull/10501

fix(core): custom list role

---

libs/core/src/lib/table/directives/table-row.directive.ts
libs/platform/src/lib/table/components/table-group-row/table-group-row.component.ts
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.ts
libs/platform/src/lib/table/components/table-popping-row/table-popping-row.component.ts
libs/platform/src/lib/table/components/table-row/table-row.component.ts

fix(core,platform): add role="row" and aria-expanded to tr elements

---

libs/platform/src/lib/search-field/search-field.component.ts
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html

fix(platform): some improvements to search field and VHD aria labels

---

libs/cdk/src/lib/utils/directives/auto-complete/auto-complete.directive.ts
libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.spec.ts
libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.component.ts
libs/core/src/lib/multi-input/multi-input-mobile/multi-input-mobile.module.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/multi-input/multi-input.module.ts
libs/docs/core/multi-input/examples/multi-input-addon-clicked-example/multi-input-addon-clicked-example.component.ts
libs/docs/core/multi-input/examples/multi-input-async-example/multi-input-async-example.component.ts
libs/docs/core/multi-input/examples/multi-input-compact-example/multi-input-compact-example.component.ts
libs/docs/core/multi-input/examples/multi-input-custom-item-example/multi-input-custom-item-example.component.ts
libs/docs/core/multi-input/examples/multi-input-displaywith-example/multi-input-displaywith-example.component.ts
libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.ts
libs/docs/core/multi-input/examples/multi-input-example/multi-input-example.component.ts
libs/docs/core/multi-input/examples/multi-input-filter-example/multi-input-filter-example.component.ts
libs/docs/core/multi-input/examples/multi-input-form-example/multi-input-form-example.component.ts
libs/docs/core/multi-input/examples/multi-input-includes-example/multi-input-includes-example.component.ts
libs/docs/core/multi-input/examples/multi-input-mobile-example/multi-input-mobile-example.component.ts
libs/docs/core/multi-input/examples/multi-input-new-tokens-example/multi-input-new-tokens-example.component.ts
libs/docs/core/multi-input/examples/multi-input-option-item-example/multi-input-option-item-example.component.ts
libs/docs/core/multi-input/multi-input-docs.component.html
libs/docs/core/multi-input/multi-input-docs.component.ts

closes #10341
Multi-input now allows a OptionItem interfaces as dropdown values and also typings have been improved slightly

feat(core): multi input option item

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/table/components/table-row/table-row.component.html

fixes #10320 
First idea, open to suggestions

fix(platform): empty cell screenreader issue

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/search-field/search-field.component.html

fix(platform): search field accessibility update

---

libs/docs/platform/table/examples/platform-table-freezable-example.component.html
libs/platform/src/lib/table-helpers/models/column-freeze-event.model.ts
libs/platform/src/lib/table-helpers/table.ts
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.spec.ts
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html

Downport of https://github.com/SAP/fundamental-ngx/pull/10529

fix(platform): fix freeze functionality

---

libs/core/src/lib/list/directives/list-navigation-item-arrow.directive.ts
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.html
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.scss

Downport of https://github.com/SAP/fundamental-ngx/pull/10503

fix(core): vertical nav keyboard navigation

---

libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html

Downport of https://github.com/SAP/fundamental-ngx/pull/10532

fix(platform): checkbox column tabindex

---

libs/core/src/lib/dynamic-page/dynamic-page.component.spec.ts
libs/core/src/lib/dynamic-page/dynamic-page.component.ts
libs/core/src/lib/scrollbar/scrollbar.directive.ts
libs/core/src/lib/tabs/tab-list.component.html
libs/core/src/lib/tabs/tab-list.component.ts
libs/docs/core/tabs/e2e/tabs.e2e-spec.ts
libs/docs/core/tabs/e2e/tabs.po.ts
libs/platform/src/lib/dynamic-page/dynamic-page.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.component.ts

closes #10375 
Downport of the #10517

feat(core,platform): dynamic page snap on scroll disable input

---

libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.ts

closes #10436
- Added detection call on popover close event.
-   [x] missing …

fix(core): datetime picker detection fix

---

libs/core/src/lib/token/tokenizer.component.ts

closes #10295 
Downport of the #10534

feat(core): tokenizer up down arrow keys navigation

---

libs/core/src/lib/token/tokenizer.component.ts

Part of #10295
Added support for navigation between tokens using vertical arrow keys

feat(core): tokenizer vertical arrow keys navigation

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/search-field/search-field.component.html

fix(platform): search field accessibility improvements

---

libs/platform/src/lib/table/components/table-row/table-row.component.html

fix(platform): add aria-selected to multiselect first td

---

libs/platform/src/lib/form/select/select/select.component.ts

fixes a console error when opening platform select

fix(platform): console error when opening platform select

---

libs/core/src/lib/popover/popover-control/popover-control.component.ts
libs/core/src/lib/popover/popover.component.html
libs/core/src/lib/progress-indicator/progress-indicator.component.html
libs/core/src/lib/progress-indicator/progress-indicator.component.scss
libs/core/src/lib/progress-indicator/progress-indicator.component.spec.ts
libs/core/src/lib/progress-indicator/progress-indicator.component.ts
libs/core/src/lib/progress-indicator/progress-indicator.module.ts
libs/docs/core/progress-indicator/examples/progress-indicator-animation.component.ts
libs/docs/core/progress-indicator/examples/progress-indicator-default.component.ts
libs/docs/core/progress-indicator/examples/progress-indicator-state.component.ts
libs/docs/core/progress-indicator/examples/progress-indicator-truncation.component.ts
libs/docs/core/progress-indicator/progress-indicator-header/progress-indicator-header.component.html

closes #9850
- Applied changes for progress indicator from this PR: https://github.com/SAP/fundamental-styles/pull/4631
- Migrated component to standalone
-   [x] …

feat(core): progress indicator horizon update

---

libs/core/src/lib/token/token.component.html

Downport of https://github.com/SAP/fundamental-ngx/pull/10541

fix(core): remove incorrect aria attribute

---

libs/core/src/lib/multi-combobox/multi-combobox.module.ts
libs/core/src/lib/token/token-input.directive.ts
libs/core/src/lib/token/token.component.spec.ts
libs/core/src/lib/token/token.component.ts
libs/core/src/lib/token/token.module.ts
libs/core/src/lib/token/tokenizer.component.spec.ts
libs/core/src/lib/token/tokenizer.component.ts
libs/docs/core/token/examples/token-compact-example/token-compact-example.component.ts
libs/docs/core/token/examples/token-example/token-example.component.ts
libs/docs/core/token/examples/token-readonly-example/token-readonly-example.component.ts
libs/docs/core/token/examples/token-selected-example/token-selected-example.component.ts
libs/docs/core/token/examples/tokenizer-compact-example/tokenizer-compact-example.component.ts
libs/docs/core/token/examples/tokenizer-example/tokenizer-example.component.ts
libs/docs/platform/vhd/examples/initial-loading/platform-vhd-initial-loading-example.component.ts
libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.ts
libs/docs/platform/vhd/examples/platform-vhd-input-example.component.ts
libs/docs/platform/vhd/examples/platform-vhd-strategy-labels-example.component.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
libs/platform/src/lib/form/multi-input/multi-input.component.ts
libs/platform/src/lib/value-help-dialog/value-help-dialog.module.ts

relates #9920
- Migrated token and tokenizer components to standalone;
- Updated imports across all pcakages.

feat(core): token standalone migration

---

libs/cdk/src/lib/utils/helpers/dfs.ts
libs/cdk/src/lib/utils/helpers/index.ts
libs/docs/platform/table/examples/platform-table-tree-example.component.html
libs/docs/platform/table/examples/platform-table-tree-example.component.ts
libs/docs/platform/table/index.ts
libs/platform/src/lib/table-helpers/helpers.ts
libs/platform/src/lib/table/table.component.ts

closes #10454
Fixed tree initial selection visualization and fixed tree tristate in general

fix(platform): table initial selection hydration

---

libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.scss
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/multi-input/multi-input.module.ts
libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts

Downport of https://github.com/SAP/fundamental-ngx/pull/10555

fix(core): multi input description text

---

libs/core/src/lib/date-picker/date-picker.component.html
libs/core/src/lib/date-picker/date-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/form/form-message/popover-form-message.service.spec.ts
libs/core/src/lib/form/form-message/popover-form-message.service.ts
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/core/src/lib/time-picker/time-picker.component.html
libs/core/src/lib/time-picker/time-picker.component.ts

closes #10554 
- Replaced plain text with templateRef with inner `fd-form-message` component. …

fix(core): use template ref to initialize styles

---

libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.spec.ts
libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.component.ts
libs/core/src/lib/combobox/combobox-mobile/combobox-mobile.module.ts
libs/core/src/lib/combobox/combobox.component.spec.ts
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/combobox/combobox.module.ts
libs/core/src/lib/combobox/list-group.pipe.ts
libs/docs/cdk/initial-focus/examples/nested-elements-example/nested-elements-example.component.ts
libs/docs/core/bar/examples/bar-custom-shellbar-example.component.ts
libs/docs/core/combobox/examples/combobox-async-example.component.ts
libs/docs/core/combobox/examples/combobox-byline-example.component.ts
libs/docs/core/combobox/examples/combobox-columns-example.component.ts
libs/docs/core/combobox/examples/combobox-disabled-example.component.ts
libs/docs/core/combobox/examples/combobox-displaywith-example.component.ts
libs/docs/core/combobox/examples/combobox-dynamic-example.component.ts
libs/docs/core/combobox/examples/combobox-example.component.ts
libs/docs/core/combobox/examples/combobox-forms-example.component.ts
libs/docs/core/combobox/examples/combobox-group-example.component.ts
libs/docs/core/combobox/examples/combobox-height-example.component.ts
libs/docs/core/combobox/examples/combobox-includes-example.component.ts
libs/docs/core/combobox/examples/combobox-mobile/combobox-mobile-example.component.ts
libs/docs/core/combobox/examples/combobox-open-control-example.component.ts
libs/docs/core/combobox/examples/combobox-search-field-example.component.ts
libs/docs/core/combobox/examples/combobox-search-function-example.component.ts
libs/docs/core/combobox/examples/combobox-template-example.component.ts

closes #10429 
- Added check if dropdown have multiple labels that are exact to the search term. If found, do not set value automatically.
-   [x] change the API …

fix(core): do not set value if identical labels found

---

package.json
yarn.lock

update theming-base-content version 11.6.8

chore(deps): update theming-base-content version 11.6.8

---

libs/core/src/lib/select/select.component.html

recreation of https://github.com/SAP/fundamental-ngx/pull/10568

fix(core): listbox has aria-selected attribute

---

libs/core/src/lib/token/token.component.ts

fix(core): update token total count properly

---

libs/core/src/lib/dialog/base/dialog-base.service.ts
libs/core/src/lib/dialog/dialog-container/dialog-container.component.ts
libs/core/src/lib/dialog/index.ts
libs/core/src/lib/dialog/utils/dialog-container.model.ts
libs/core/src/lib/message-box/message-box-container/message-box-container.component.ts

Downport of dialog dismiss all bugfix

fix(core): dialog dismiss all downport

---

libs/cdk/src/lib/utils/datatypes/index.ts
libs/cdk/src/lib/utils/datatypes/object-nesting.types.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/multi-input/pair-selection.model.ts
libs/docs/core/multi-input/examples/multi-input-option-item-example/multi-input-option-item-example.component.ts
libs/i18n/src/lib/models/lang.ts

closes #10341
closes #10378
This adds ability to have `identifier` on OptionItem. Also adds more type-safety to the multi-input

feat(core): multi input value identifier

---

.github/actions/npm-publish/index.js
lerna.json
package.json

This should sync versions on npm and report properly the name of the published packages

chore(ci): fixed npm publish undefined reporting and synced versions

---

libs/cdk/src/lib/utils/datatypes/index.ts
libs/cdk/src/lib/utils/datatypes/object-nesting.types.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.spec.ts
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/multi-input/pair-selection.model.ts
libs/docs/core/multi-input/examples/multi-input-option-item-example/multi-input-option-item-example.component.ts

related to #10341 
downport of the #10601

feat(core): downport multi input option identifier

---

libs/core/src/lib/popover/popover-body/popover-body.component.scss
libs/core/src/lib/popover/popover-service/popover.service.ts

fix(core): popover header/footer should be sticky, and popovers should be able to grow

---

libs/core/src/lib/busy-indicator/busy-indicator.component.html
libs/core/src/lib/busy-indicator/busy-indicator.component.scss

fix(core): 10412

---

libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts
libs/i18n/src/lib/languages/german.ts
libs/i18n/src/lib/languages/index.ts

feat: downport german i18n

---

libs/core/src/lib/micro-process-flow/components/micro-process-flow-item/micro-process-flow-item.component.ts
libs/docs/core/breadcrumb/examples/breadcrumb-routerLink-example.component.html
libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
libs/docs/core/panel/panel-docs.component.html
libs/docs/platform/smart-filter-bar/examples/platform-smart-filter-bar-custom-filter-example.component.ts
libs/platform/src/lib/upload-collection/upload-collection/upload-collection.component.html

part of #10649 
- fixed router links in breadcrumb example
- fixed assets injection context call in illustrated message
- fixed micro-process-flow info-label white-space wrap
- fixed text on panel compact example
- fixed missing providers in smart filter bar docs
- hiding platform upload collection pagination if no items present

fix(docs,core): various defect hunt issues

---

libs/core/src/lib/token/tokenizer.component.html

fix(core): tokenizer more button focus issue

---

libs/core/src/lib/multi-input/multi-input.component.html

fix(core): add role="button" to show all link

---

CONTRIBUTING.md

part of https://github.com/SAP/fundamental-ngx/pull/10576

docs: update CONTRIBUTING.md with local setup steps

---

libs/core/src/lib/multi-input/multi-input.component.html

fix(core): add role to show all button

---

libs/core/src/lib/inline-help/inline-help.directive.ts

fixes this: https://github.com/SAP/fundamental-ngx/issues/10649#issuecomment-1744718462

fix(core): inline help screenreader bug when using template

---

libs/core/src/lib/date-picker/date-picker.component.html
libs/core/src/lib/date-picker/date-picker.component.ts
libs/core/src/lib/datetime-picker/datetime-picker.component.html
libs/core/src/lib/datetime-picker/datetime-picker.component.ts
libs/core/src/lib/form/form-message/popover-form-message.service.spec.ts
libs/core/src/lib/form/form-message/popover-form-message.service.ts
libs/core/src/lib/popover/popover-service/popover.service.ts
libs/core/src/lib/time-picker/time-picker.component.html
libs/core/src/lib/time-picker/time-picker.component.ts

fixes #10600 
downport of https://github.com/SAP/fundamental-ngx/pull/10574

fix(core): form message styles

---

libs/core/src/lib/token/tokenizer.component.html
libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/german.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts

fix(core): add aria-label to tokenizer

---

libs/core/src/lib/token/tokenizer.component.html
libs/i18n/src/lib/models/lang.ts
libs/i18n/src/lib/translations/translations_bg-BG.json
libs/i18n/src/lib/translations/translations_cs-CZ.json
libs/i18n/src/lib/translations/translations_de-DE.json
libs/i18n/src/lib/translations/translations_en-US.json
libs/i18n/src/lib/translations/translations_fr-FR.json
libs/i18n/src/lib/translations/translations_hi-IN.json
libs/i18n/src/lib/translations/translations_it-IT.json
libs/i18n/src/lib/translations/translations_ka-GE.json
libs/i18n/src/lib/translations/translations_pl-PL.json
libs/i18n/src/lib/translations/translations_ru-RU.json
libs/i18n/src/lib/translations/translations_sq-AL.json
libs/i18n/src/lib/translations/translations_tr-TR.json
libs/i18n/src/lib/translations/translations_uk-UA.json
libs/i18n/src/lib/translations/translations_zh-CN.json

fix(core): add aria-label to fd-tokenizer

---

libs/docs/core/popover/e2e/popover-contents.ts
libs/docs/core/popover/e2e/popover.e2e-spec.ts
libs/docs/core/popover/examples/popover-complex-example/popover-complex-example.component.html
libs/docs/core/popover/examples/popover-complex-example/popover-complex-example.component.ts
libs/docs/core/popover/examples/popover-simple/popover-example.component.html
libs/docs/core/popover/examples/popover-simple/popover-example.component.ts

Updated popover examples(proper markup for the header and footer), simplified some examples

chore(docs): popover examples

---

libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.ts

docs: add Portuguese brazil in doc

---

libs/docs/core/popover/examples/popover-focus-example/popover-focus-example.component.html
libs/docs/core/popover/examples/popover-simple/popover-example.component.html

remove hardcoded fdCozy from popover examples

docs(core): remove hardcoded fdCozy from popover examples

---

libs/btp/navigation/navigation.component.scss

closes none as far as I know
Before
After

fix(btp): fixed z-index of the home list item when expanded or popup

---

libs/btp/navigation/directives/navigation-list-spacer.directive.ts
libs/btp/navigation/index.ts
libs/btp/navigation/navigation-component.token.ts
libs/btp/navigation/navigation-content-end.component.ts
libs/btp/navigation/navigation-content-start.component.html
libs/btp/navigation/navigation-content-start.component.ts
libs/btp/navigation/navigation-list-item-component.token.ts
libs/btp/navigation/navigation-list/navigation-list-item.component.ts
libs/btp/navigation/navigation-list/navigation-list-overflow-item.component.html
libs/btp/navigation/navigation-list/navigation-list-overflow-item.component.ts
libs/btp/navigation/navigation.component.scss
libs/btp/navigation/navigation.component.ts
libs/btp/navigation/navigation.types.ts
libs/core/src/lib/popover/popover-body/popover-body.component.scss
libs/core/src/lib/theming/theming.service.ts
libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html
libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.ts
libs/docs/btp/navigation/navigation-docs.component.html

closes none
- fixed popover resize capturing text;
- changed theming initialization mechanizm;
- added tablet and mobile examples for btp vertical navigation
- Changed overflow mechanizm calculation for btp vertical navigation

fix(core,btp): various dh fixes

---

libs/btp/navigation/navigation-content-start.component.ts
libs/btp/navigation/navigation-link.component.ts
libs/btp/navigation/navigation-list-component.token.ts
libs/btp/navigation/navigation-list-item-component.token.ts
libs/btp/navigation/navigation-list/navigation-list-item.component.html
libs/btp/navigation/navigation-list/navigation-list-item.component.ts
libs/btp/navigation/navigation-list/navigation-list.component.ts
libs/btp/navigation/navigation.component.scss
libs/btp/navigation/navigation.component.ts
libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html

closes none
Fixes use-case when navigation item is not wrapped in a group

fix(btp): snapped functionality for ungrouped items

---

libs/docs/platform/approval-flow/e2e/approval-flow.e2e-spec.ts

fix(platform): approval flow e2e

---

libs/core/src/lib/time/time-column/time-column.component.html

fix(core): remove assertive from time column

---

libs/btp/navigation/directives/navigation-home.directive.ts
libs/btp/navigation/navigation-component.token.ts
libs/btp/navigation/navigation-link.component.ts
libs/btp/navigation/navigation-list-item-component.token.ts
libs/btp/navigation/navigation-list/navigation-list-item.component.html
libs/btp/navigation/navigation-list/navigation-list-item.component.ts
libs/btp/navigation/navigation-list/navigation-list.component.html
libs/btp/navigation/navigation.component.scss
libs/btp/navigation/navigation.component.ts
libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html

closes none;
- Added ability to set routerLink for home item and highlight when it's active;
- Added ability to remove separator between home item and the rest of the items.

fix(btp): custom vertical nav home

---

libs/cdk/src/lib/utils/directives/index.ts
libs/cdk/src/lib/utils/directives/multi-announcer/multi-announcer.directive.ts
libs/core/src/lib/multi-combobox/multi-combobox.component.html
libs/core/src/lib/multi-combobox/multi-combobox.module.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/multi-input/multi-input.module.ts
libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/german.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/portuguese.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox.module.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.module.ts

fix(core): improved multi-input screenreader (ng15)

---

libs/core/src/lib/scroll-spy/scroll-spy.directive.ts
libs/core/src/lib/tabs/tab-list.component.ts
libs/docs/core/popover/e2e/popover.e2e-spec.ts
libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.html
libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.ts

closes #10741
- Added handler for dynamic tab addition to the tabs list;
- Updated stacked tabs example to have ability to dynamically add new tabs
-   [x] change …

fix(core): dynamic stacked tabs

---

libs/btp/tool-header/src/components/tool-header/tool-header.component.scss

closes none
Styles were imported incorrectly into the scss

fix(btp): incorrect import of the styling of tool-header

---

libs/core/src/lib/scroll-spy/scroll-spy.directive.ts
libs/core/src/lib/tabs/tab-list.component.html
libs/core/src/lib/tabs/tab-list.component.ts
libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.html
libs/docs/core/tabs/examples/tab-stacked-content-example/tab-stacked-content-example.component.ts

fix(core): async scenario handler

---

e2e/wdio/driver/wdio.ts

closes none
- Forced page reload instead of soft one (going to home and returning to prev page)

fix(e2e): temporary do a full page refresh

---

libs/core/src/lib/multi-input/multi-input.component.ts

closes none
- Fixes the issue with adding custom token to core multi input

fix(core): multi input new token

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/german.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/portuguese.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/approval-flow/approval-flow-node/approval-flow-node.component.html

chore(platform): downport missing approval flow translations

---

libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.html
libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts

closes #8663
Updated the example component to notify illustrated message that the scene config is loaded.
3. …

fix(docs): illustrated message async data example

---

libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.html
libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.ts
libs/docs/core/vertical-navigation/examples/vertical-navigation-condensed-example.component.html
libs/docs/core/vertical-navigation/examples/vertical-navigation-condensed-example.component.ts

closes #10765
Previously, we set `condensed` state for the vert nav items only when vert nav component is initialized.
Now vert nav component reacts to the changes of the `condensed` input property and updates the list accordingly taking into consideration possible changes in the list itself too.
- …

fix(core): reactive condensed state

---

libs/core/src/lib/carousel/carousel-item/carousel-item.component.html
libs/core/src/lib/carousel/carousel-item/carousel-item.component.ts
libs/core/src/lib/carousel/carousel.component.scss
libs/core/src/lib/carousel/carousel.component.ts

DH issues
- Fixed carousel vertical keyboard navigation
- Fixed focus lost on keyboard navigation
- Fixed carousel busy indicator misplacement

fix(core): various carousel fixes

---

e2e/wdio/driver/wdio.ts
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts

fix(e2e): core calendar fix

---

libs/core/src/lib/icon/icon.component.ts
libs/docs/core/icon/examples/icon-color-example.component.ts
libs/docs/core/icon/icon-docs.component.html
libs/docs/core/icon/icon-docs.component.ts

closes #10781
- Refactored Icon Component to use signals;
- Added color and background input properties
- Added example for colored icons
-   [x] change the API …

feat(core): icon component text and background color

---

libs/platform/src/lib/shared/domain/data-source.ts

fix(platform): special characters escape

---

libs/core/src/lib/table/table.component.scss
libs/platform/src/lib/table/table.component.scss

fix: table cell focus issue

---

libs/core/src/lib/busy-indicator/busy-indicator.component.scss

closes #9919
- Issue appears because of the focused button has a greater `z-index` value than busy-indicator's overlay container. …

fix(core): busy indicator overlay z-index

---

libs/core/src/lib/popover/base/base-popover.class.ts
libs/core/src/lib/popover/popover-body/popover-body.component.ts

fix(core): do not make popover scrollbar focusable

---

apps/docs/src/styles.scss
libs/cx/schematics/ng-add/styles.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss

fix: add 72-SemiboldDuplex font

---

libs/core/src/lib/link/link.component.html
libs/core/src/lib/link/link.component.scss
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts
libs/docs/core/link/e2e/link.e2e-spec.ts
libs/docs/core/link/examples/link-example.component.html

relates https://github.com/SAP/fundamental-styles/issues/4912
- Since link icon is placed in container element, icon's margin and self-positioning didn't worked as expected;
- Introduced wrapper component that mimics the styling of the icon element itself (margins, inline-flex, etc.);
- Added `subtle` link example.
2. API and …

fix(core): link icon position

---

libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts
libs/docs/core/calendar/e2e/calendar.e2e-spec.ts

fix(core): close dropdown item when keyboard is used

---

libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.spec.ts

fix(platform): remove selected duplicates

---

libs/core/src/lib/multi-input/multi-input.component.html
libs/docs/platform/multi-input/platform-multi-input-docs.component.html

fix(core): disable autocomplete if includes enabled

---

.github/workflows/create-release.yml
.github/workflows/on-pull-request.yml
.github/workflows/on-schedule.yml

Replaced Volta-based nx ci workflows with the locally written matrix of the simple node-based actions

chore(ci): fixed long-standing problem of the volta action

---

libs/i18n/src/lib/translations/translations_en-US.properties

Added comments for assigned lines

fix(i18n): comments 116-248

---

libs/i18n/src/lib/translations/translations_en-US.properties

fix(i18n): denis comments part 2

---

libs/i18n/src/lib/translations/translations_en-US.properties

- add comment for lines 249 through 323
- fix some minor typos

fix(i18n): add comments for translations lines 249 through 323

---

libs/platform/src/lib/search-field/search-field.component.html

fix(platform): keyboard improvements for search field

---

libs/i18n/src/lib/languages/albanian.ts
libs/i18n/src/lib/languages/bulgarian.ts
libs/i18n/src/lib/languages/chinese.ts
libs/i18n/src/lib/languages/czech.ts
libs/i18n/src/lib/languages/english.ts
libs/i18n/src/lib/languages/french.ts
libs/i18n/src/lib/languages/georgian.ts
libs/i18n/src/lib/languages/german.ts
libs/i18n/src/lib/languages/hindi.ts
libs/i18n/src/lib/languages/italian.ts
libs/i18n/src/lib/languages/polish.ts
libs/i18n/src/lib/languages/portuguese.ts
libs/i18n/src/lib/languages/russian.ts
libs/i18n/src/lib/languages/turkish.ts
libs/i18n/src/lib/languages/ukrainian.ts
libs/i18n/src/lib/models/lang.ts
libs/platform/src/lib/table/components/table-row/table-row.component.html

fix(platform): remove title tooltip from table checkbox

---

libs/core/src/lib/input-group/input-group.component.html
libs/core/src/lib/input-group/input-group.component.ts
libs/core/src/lib/multi-input/multi-input.component.html

closes #10627
Downport of the #10914

fix(core): multi input addon aria hidden

---

libs/platform/src/lib/form/select/select/select.component.html
libs/platform/src/lib/shared/form/base.input.ts

fix(platform): aria-labelledby for select

---

.gitignore
libs/platform/src/lib/table-helpers/pipes/column-sorting-direction.pipe.spec.ts
libs/platform/src/lib/table-helpers/pipes/column-sorting-direction.pipe.ts
libs/platform/src/lib/table-helpers/pipes/index.ts
libs/platform/src/lib/table-helpers/table-helpers.module.ts
libs/platform/src/lib/table/components/table-header-cell-content/table-header-cell-content.component.html
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html
libs/platform/src/lib/table/components/table-header-row/table-header-row.component.ts

fix(platform): aria sort attribute

---

libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
libs/core/src/lib/multi-combobox/multi-combobox.component.html
libs/core/src/lib/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.html

fix(core,platform): multi announcer improvements

---

libs/core/src/lib/token/tokenizer.component.html

closes #10827
Moved `aria-label` attribute to a div with `role="listbox"`.

fix(core): tokenizer listbox label

---

libs/core/src/lib/select/select.component.html

fix(core): select aria attributes

---

libs/core/src/lib/multi-combobox/multi-combobox.component.ts

closes #10950
Using flat list of the suggestions

fix(core): fixed group item selections and deselections

---

libs/core/src/lib/list/list-item/list-item.component.ts

fix(core): downport of 10715 (remove link role from list item)

---

libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html

fix(platform): move initial focus to search input on p13

---

libs/cdk/src/lib/utils/pipes/search-highlight.pipe.ts
libs/docs/core/icon/icon-header/icon-header.component.html
libs/docs/core/icon/icon-header/icon-header.component.ts
libs/docs/core/icon/index.ts
libs/docs/core/icon/search-icons/available-sap-icons.ts
libs/docs/core/icon/search-icons/search-icons.component.html
libs/docs/core/icon/search-icons/search-icons.component.ts
libs/docs/shared/src/lib/core-helpers/header-tabs/header-tabs.component.html
libs/docs/shared/src/lib/core-helpers/header-tabs/header-tabs.component.ts
libs/platform/src/lib/table-helpers/directives/table-cell.directive.ts
package.json
yarn.lock

closes
Added search of the icons depending on their tags, groups and names

chore(docs): added search page of the icons

---

libs/cdk/src/lib/forms/index.ts
libs/cdk/src/lib/forms/models/control-type.model.ts
libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/list/list-focus-item.model.ts
libs/core/src/lib/list/list-item/list-item.component.ts
libs/core/src/lib/list/list.component.ts
libs/core/src/lib/select/select-key-manager.service.ts
libs/core/src/lib/select/select.component.ts
libs/core/src/lib/select/select.interface.ts
libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/commons/base-combobox.ts
libs/platform/src/lib/form/select/commons/base-select.ts
libs/platform/src/lib/form/select/index.ts
libs/platform/src/lib/form/select/select/select.component.html

feat(core,platform): dropdown control tabout strategy

---

libs/core/src/lib/datetime-picker/datetime-picker.component.ts

fix(core): bug where datetime picker cannot be opened a 2nd time

---

libs/platform/src/lib/table/table.component.ts

closes #11002 
downport of the #11019

fix(platform): clear table rows on data source changes (#11019)

---

versions.json

docs: update versions.json

---

libs/docs/shared/src/lib/core-helpers/toolbar/toolbar.component.html

docs: add version selector

---

libs/core/src/lib/menu/menu.component.spec.ts
libs/core/src/lib/menu/menu.component.ts

fix(core): allow dev to pass disableScrollbar to menu

---

libs/core/button/base-button.ts
libs/core/segmented-button/segmented-button.component.ts
libs/platform/button/button.component.html
libs/platform/button/button.component.spec.ts

fix(core,platform): button should not set aria-pressed by default

---

libs/core/splitter/splitter-pane-container/splitter-pane-container.component.ts
libs/core/splitter/splitter-split-pane/splitter-split-pane.component.ts
libs/docs/core/splitter/examples/api/splitter-api-example.component.html
libs/docs/core/splitter/examples/api/splitter-api-example.component.ts

fixes none. Issue raised to me via slack. Programmatically updating pane "size" property after init did not adjust pane size

fix(core): allow for programmatic change of pane size

---

libs/core/combobox/combobox.component.ts
libs/docs/platform/vhd/examples/column-template/platform-vhd-column-template-example.component.html
libs/docs/platform/vhd/examples/column-template/platform-vhd-column-template-example.component.ts
libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.html
libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.ts
libs/docs/platform/vhd/platform-vhd.docs.component.html
libs/docs/platform/vhd/platform-vhd.docs.component.ts
libs/platform/value-help-dialog/components/select-tab/select-tab.component.html
libs/platform/value-help-dialog/components/select-tab/select-tab.component.ts
libs/platform/value-help-dialog/components/value-help-dialog-filter/value-help-dialog-filter.component.ts
libs/platform/value-help-dialog/directives/value-help-column-def.directive.ts
libs/platform/value-help-dialog/directives/value-help-filter-def.directive.ts
libs/platform/value-help-dialog/index.ts
libs/platform/value-help-dialog/models/vhd-component.model.ts
libs/platform/value-help-dialog/models/vhd-filter.model.ts
libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html
libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts

closes #10997
- Added ability to define custom filter control;
- Updated basic example with added `Verified` column that is either 'Yes' or 'No', and combobox control to filter the column.
- Added ability to define custom renderer for the column;
- Added example with custom renderer and boolean filters …

feat(platform): vhd custom filter controls

---

libs/core/src/lib/button/button.component.ts
libs/core/src/lib/segmented-button/segmented-button.component.ts

fixes https://github.com/SAP/fundamental-ngx/issues/10805

fix(core): segmented button improvements

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.ts

fix(platform): fdp-combobox selection issues

---

libs/core/splitter/README.md
libs/docs/core/splitter/e2e/splitter.e2e-spec.ts
libs/docs/core/splitter/e2e/spltiller.po.ts
libs/docs/core/splitter/examples/api/splitter-api-example.component.ts
libs/docs/core/splitter/examples/default/splitter-default-example.component.ts
libs/docs/core/splitter/examples/required-parent-width/splitter-required-parent-width-example.component.ts
libs/docs/core/splitter/splitter-docs.component.html
libs/docs/core/splitter/splitter-header/splitter-header.component.ts

fix(docs): splitter docs incorrectly using slider for selectors etc

---

libs/core/src/lib/multi-combobox/multi-announcer/multi-announcer.directive.ts
libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.ts
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts

feat(platform): allow disabling select all in vhd

---

libs/core/overflow-layout/overflow-layout.service.ts

closes none
Fixes issue when there's [forceVisibility]=true applied to the first items

fix(core): first forced item case

---

libs/core/shellbar/shellbar-actions-mobile/shellbar-actions-mobile.component.ts
libs/core/shellbar/shellbar.component.ts
libs/docs/core/shellbar/examples/shellbar-collapsible-example.component.html
libs/docs/core/shellbar/examples/shellbar-collapsible-example.component.ts

closes #11126
Fixed issue with dynamically rendered search component in shellbar.

fix(core): dynamically render search field

---

libs/cdk/utils/directives/overflow-list/overflow-list.directive.ts
libs/cdk/utils/pipes/async-or-sync.pipe.ts
libs/docs/platform/settings-generator/examples/custom-control/settings-generator-custom-control-example.component.ts
libs/docs/platform/settings-generator/examples/default/settings-generator-default-example.component.ts
libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.ts
libs/docs/platform/settings-generator/examples/message-popover/settings-generator-message-popover-example.component.ts
libs/platform/form/form-generator/interfaces/dynamic-form-item.ts
libs/platform/icon-tab-bar/components/closable-icon-tab-bar.class.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-icon-type/icon-tab-bar-icon-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.spec.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.spec.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
libs/platform/icon-tab-bar/interfaces/tab-config.interface.ts
libs/platform/settings-generator/default-config.ts
libs/platform/settings-generator/models/settings.model.ts
libs/platform/settings-generator/settings-generator-content/settings-generator-content.component.html
libs/platform/settings-generator/settings-generator-content/settings-generator-content.component.ts
libs/platform/settings-generator/settings-generator.component.scss

closes #11045
- Added `--sapBackgroundColor` to content area;
- Migrated settings generator tabbed layout to use platform icon tab bar instead of core tabs;
- Updated icon tab bar to be compliant with Settings generator async properties;
- Adjusted dialog size for the examples;
- Adjusted dialog heading paddings;
- Adjusted settings section heading paddings;
-   [x] Mouse vs. Keyboard …

fix(platform): settings generator style update

---

libs/core/src/lib/file-uploader/file-uploader.component.ts
libs/core/src/lib/object-status/object-status.component.ts
libs/platform/src/lib/table/table.component.ts

Downport of https://github.com/SAP/fundamental-ngx/commit/3eacc6d2960a5bbc0ab5f75f4074c54fb7ddfe27

fix(core): non-focusable object status

---

libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html

fix(platform): p13 a11y fixes

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.spec.ts
libs/platform/src/lib/form/combobox/combobox/combobox.component.ts
libs/platform/src/lib/shared/form/collection-base.input.ts

fix(platform): combobox selection issue

---

apps/docs/src/styles.scss
libs/cx/schematics/ng-add/styles.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/styles.scss

fix(docs): add missing font

---

libs/core/calendar/calendar-header/calendar-header.component.ts
libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
libs/core/datetime/datetime-adapter.ts
libs/datetime-adapter/src/lib/dayjs-datetime-adapter.ts
libs/moment-adapter/src/lib/moment-datetime-adapter.ts
package.json
yarn.lock

closes #10230
Adjusted date manipulation in dayjs adapter

fix(core): dayjs utc offset fix

---

libs/core/multi-input/multi-input.component.html
libs/core/multi-input/multi-input.component.ts
libs/platform/form/multi-input/multi-input.component.html
libs/platform/form/multi-input/multi-input.component.ts

fix: add addonIconTitle input to multi input

---

libs/core/token/tokenizer.component.html

fix(core): aria-hidden tokenizer if tokenList length is 0

---

libs/platform/form/combobox/combobox/combobox.component.spec.ts
libs/platform/form/combobox/commons/base-combobox.ts

fix(platform): combobox escape bug

---

libs/platform/src/lib/table/table.component.scss

fix(platform): tree table text overflow

---

libs/docs/platform/table/examples/platform-table-freezable-example.component.html
libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts
libs/platform/src/lib/table/table.component.ts
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.scss

Downports of #11235 and #11233

fix(platform): unfrozen area min width

---

libs/platform/src/lib/table-helpers/directives/table-initial-state.directive.ts

fix(platform): initial visible columns

---

libs/docs/core/dynamic-page/dynamic-page-docs.component.html
libs/docs/core/dynamic-page/dynamic-page-docs.component.ts
libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-routing/dynamic-page-routing-example.component.ts
libs/docs/core/dynamic-page/index.ts
libs/platform/icon-tab-bar/directives/icon-tab-bar-free-content.directive.ts
libs/platform/icon-tab-bar/icon-tab-bar.component.html
libs/platform/icon-tab-bar/icon-tab-bar.module.ts
libs/platform/icon-tab-bar/index.ts

relates #11209
Added example of tabbed routing with Dynamic Page.

feat(core,docs): dynamic page tabbed routing

---

netlify.toml

delete cache during netlify build for ng15

chore: delete cache during netlify build for ng15

---

libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.html
libs/docs/platform/vhd/examples/platform-vhd-basic-example.component.ts
libs/docs/platform/vhd/platform-vhd-docs.module.ts
libs/docs/platform/vhd/platform-vhd.docs.component.html
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.ts

feat(platform): vhd validator

---

libs/core/action-sheet/action-sheet-body/action-sheet-body.component.ts
libs/core/action-sheet/action-sheet-item/action-sheet-item.component.html
libs/core/action-sheet/action-sheet-item/action-sheet-item.component.ts
libs/core/checkbox/checkbox/checkbox.component.html
libs/core/checkbox/checkbox/checkbox.component.scss
libs/core/date-picker/date-picker.component.html
libs/core/date-picker/date-picker.component.ts
libs/core/dialog/dialog-default/dialog-default.component.html
libs/core/dialog/dialog-full-screen-toggler-button/dialog-full-screen-toggler-button.component.ts
libs/core/dialog/dialog.component.ts
libs/core/file-uploader/file-uploader.component.ts
libs/core/message-strip/alert/default-config.ts
libs/core/message-strip/alert/message-strip-alert.service.ts
libs/core/message-strip/alert/message-strip-alert/message-strip-alert.component.ts
libs/core/message-strip/alert/open-message-strip-alert.config.ts
libs/core/message-strip/alert/tokens.ts
libs/core/popover/base/base-popover.class.ts
libs/core/popover/popover-service/popover.service.ts
libs/docs/core/dialog/examples/dialog-full-screen/dialog-full-screen-example.component.html
libs/docs/core/feed-input/examples/feed-input-disabled-example/feed-input-disabled-example.component.html
libs/docs/core/feed-input/examples/feed-input-example/feed-input-example.component.html
libs/docs/core/feed-input/examples/feed-input-grow-example/feed-input-grow-example.component.html
libs/docs/core/feed-list-item/examples/fli-avatar/fli-avatar-example.component.html
libs/docs/core/feed-list-item/examples/fli-mobile/fli-mobile-example.component.html
libs/docs/core/list/examples/list-example.component.html
libs/docs/core/list/examples/list-examples.component.ts
libs/docs/core/message-strip/examples/message-strip-alert-example.component.ts
libs/docs/platform/feed-input/examples/platform-feed-input-disabled-example/platform-feed-input-disabled-example.component.html
libs/docs/platform/feed-input/examples/platform-feed-input-example/platform-feed-input-example.component.html
libs/docs/platform/feed-input/examples/platform-feed-input-max-height-example/platform-feed-input-max-height-example.component.html

relates #11307 closes #11168
Potentially closes #11209 needs to be tested on stackblitz after merge
See individual commits

fix(core,docs,platform): various defect hunting issues

---

libs/core/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
libs/core/facets/facet/facet.component.html
libs/core/title/title.component.ts

fix(core): dynamic page bugs

---

libs/core/select/select.component.scss
libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.html
libs/docs/core/select/examples/select-semantic-state-example/select-semantic-state-example.component.ts

closes #11313
Updated Core select documentation: Added form message example with event triggers to show/close form message. …

feat(docs): core select form message with triggers

---

libs/docs/platform/icon-tab-bar/examples/two-click-area/icon-tab-bar-two-click-area-example.component.html
libs/docs/platform/icon-tab-bar/examples/two-click-area/icon-tab-bar-two-click-area-example.component.ts
libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.html
libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.html
libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.ts
libs/platform/icon-tab-bar/components/text-type-tab-item/icon-tab-bar-text-type-tab-item.component.html
libs/platform/icon-tab-bar/components/text-type-tab-item/icon-tab-bar-text-type-tab-item.component.ts
libs/platform/icon-tab-bar/icon-tab-bar.component.html
libs/platform/icon-tab-bar/icon-tab-bar.component.scss
libs/platform/icon-tab-bar/icon-tab-bar.component.ts
libs/platform/icon-tab-bar/index.ts

closes #10592 
Added support for multi-click tab variant. …

feat(platform): icon tab bar multi-click tab

---

.github/workflows/create-release.yml

log the commits during gh action

chore: log the commits during gh action

---

.github/workflows/create-release.yml

remove git log and disable gh pages cache

chore: remove git log and disable gh pages cache

---

.github/actions/bump-styles-version/action.yml
.github/actions/bump-version/action.yml
.github/actions/generate-conventional-release-notes/action.yml
.github/actions/get-version/action.yml
.github/actions/npm-publish/action.yml
.github/actions/release-tags/action.yml
.github/actions/update-versions/action.yml
.github/actions/wait-for-netlify/action.yml

chore(ci): migrate to node20

---

package.json
yarn.lock

update theming-base-content v11.11.0

chore(deps): update theming-base-content v11.11.0

---

libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-header/platform-icon-tab-bar-header.component.html
libs/platform/icon-tab-bar/components/closable-icon-tab-bar.class.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-filter-type/icon-tab-bar-filter-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-icon-type/icon-tab-bar-icon-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-process-type/icon-tab-bar-process-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.html
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
libs/platform/icon-tab-bar/components/popovers/icon-tab-bar-popover-base.class.ts
libs/platform/icon-tab-bar/components/popovers/icon-tab-bar-popover/icon-tab-bar-popover.component.html
libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.html
libs/platform/icon-tab-bar/components/popovers/text-type-popover/text-type-popover.component.ts

closes none
- Added keyboard navigation explanation;
- Added keyboard support for removing the tab for closable tabs.
3. …

feat(docs,core): icon tab bar navigation improvements

---

libs/core/multi-combobox/multi-combobox.component.html
libs/core/multi-input/multi-input.component.html
libs/docs/core/multi-input/e2e/multi-input.e2e-spec.ts
libs/docs/platform/multi-input/e2e/multi-input.e2e-spec.ts
libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/form/multi-input/multi-input.component.html

closes #10998
This PR fixes placeholder behavior according to the guidelines: if multi input/combobox value is set, hide placeholder.

fix(core,platform): multi input and combobox placeholder behavior

---

libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html

fix(platform): disallow select all for single select

---

libs/core/multi-combobox/multi-combobox.component.html
libs/core/multi-combobox/multi-combobox.component.ts
libs/docs/core/multi-combobox/e2e/multi-combobox.e2e-spec.ts
libs/docs/core/multi-combobox/examples/multi-combobox-byline/multi-combobox-byline-example.component.html
libs/docs/core/multi-combobox/examples/multi-combobox-byline/multi-combobox-byline-example.component.ts
libs/docs/core/multi-combobox/multi-combobox-docs.component.html
libs/docs/core/multi-combobox/multi-combobox-docs.component.ts
libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.html
libs/docs/core/multi-input/examples/multi-input-dropdown-width-example/multi-input-dropdown-width-example.component.ts

closes #11025
- Added example for core multi input to render dropdown list items as a byline list items;
- Added example for core multi combobox to render dropdown list items as a byline list items;
-   [x] different …

feat(core,docs): multi input combobox byline example

---

libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.html
libs/docs/platform/vhd/examples/platform-vhd-multi-input-example.component.ts

fix(docs): vhd value comparator fix

---

libs/platform/src/lib/table/components/table-row/table-row.component.html
libs/platform/src/lib/table/components/table-row/table-row.component.ts

fix(platform): live announcer should say whether column is fixed

---

package.json
yarn.lock

chore(deps): tbc v11.12.0

---

libs/platform/search-field/search-field.component.html
libs/platform/search-field/search-field.component.scss
libs/platform/search-field/search-field.component.spec.ts
libs/platform/search-field/search-field.component.ts

closes #10234
Migrated to core's popover
-   [x] missing API documentation or …

fix(platform): search field simplification

---

libs/docs/platform/docs-data.ts
libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.html
libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.ts
libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-example.component.html
libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-example.component.ts
libs/docs/platform/table/examples/standard-pagination/platform-table-standard-pagination-example.component.html
libs/docs/platform/table/examples/standard-pagination/platform-table-standard-pagination-example.component.ts
libs/docs/platform/table/index.ts
libs/i18n/src/lib/models/fd-language-key-identifier.ts
libs/i18n/src/lib/translations/translations.properties
libs/i18n/src/lib/translations/translations.ts
libs/platform/table-helpers/services/table.service.ts
libs/platform/table-helpers/table.ts
libs/platform/table/components/growing-button/table-growing-button.component.html
libs/platform/table/components/growing-button/table-growing-button.component.ts
libs/platform/table/index.ts
libs/platform/table/table.component.html
libs/platform/table/table.component.scss
libs/platform/table/table.component.ts
libs/platform/table/table.module.ts

closes #11369 
- Added Growing button component to platform table;
- Added example for growing button;
- Added alternative example with core pagination;
-   [x] …

feat(platform,docs): table growing button

---

libs/platform/value-help-dialog/components/define-tab/define-tab.component.html
libs/platform/value-help-dialog/components/define-tab/define-tab.component.scss

closes #7425
- Removed unnecessary styles
- Adjusted visuals for define tab controls
- Items are now vertically centered
- No huge gap between condition selector and value controls
- Added space between columns
-   [x] …

fix(platform): simplify vhd styles

---

libs/core/facets/facet/facet.component.html
libs/core/title/title.component.ts

fixes none. part of https://github.com/SAP/fundamental-styles/pull/5180

fix(core): use div for facet title

---

libs/i18n/src/lib/translations/translations_ar.properties
libs/i18n/src/lib/translations/translations_bg.properties
libs/i18n/src/lib/translations/translations_cs.properties
libs/i18n/src/lib/translations/translations_da.properties
libs/i18n/src/lib/translations/translations_de.properties
libs/i18n/src/lib/translations/translations_el.properties
libs/i18n/src/lib/translations/translations_es.properties
libs/i18n/src/lib/translations/translations_fi.properties
libs/i18n/src/lib/translations/translations_fr.properties
libs/i18n/src/lib/translations/translations_he.properties
libs/i18n/src/lib/translations/translations_hr.properties
libs/i18n/src/lib/translations/translations_hu.properties
libs/i18n/src/lib/translations/translations_it.properties
libs/i18n/src/lib/translations/translations_ja.properties
libs/i18n/src/lib/translations/translations_kk.properties
libs/i18n/src/lib/translations/translations_ko.properties
libs/i18n/src/lib/translations/translations_ms.properties
libs/i18n/src/lib/translations/translations_nl.properties
libs/i18n/src/lib/translations/translations_no.properties
libs/i18n/src/lib/translations/translations_pl.properties
libs/i18n/src/lib/translations/translations_pt.properties
libs/i18n/src/lib/translations/translations_ro.properties
libs/i18n/src/lib/translations/translations_sh.properties
libs/i18n/src/lib/translations/translations_sk.properties
libs/i18n/src/lib/translations/translations_sl.properties
libs/i18n/src/lib/translations/translations_sv.properties
libs/i18n/src/lib/translations/translations_th.properties
libs/i18n/src/lib/translations/translations_tr.properties
libs/i18n/src/lib/translations/translations_zh_CN.properties
libs/i18n/src/lib/translations/translations_zh_TW.properties

fix: translation delivery

---

libs/i18n/src/lib/translations/translations.ts

fix(core): update total tokens text

---

libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.html
libs/core/src/lib/form/form-input-message-group/form-input-message-group.component.ts
libs/core/src/lib/popover/popover.component.ts

fix(core): disable form message group prevent defaults

---

package.json
yarn.lock

theming-base-content v.11.12.2

chore(deps): theming-base-content v.11.12.2

---

libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.html

fix(platform): upadte vhd search field placeholder

---

libs/core/dialog/dialog-close-button/dialog-close-button.component.ts
libs/core/dialog/dialog-default/dialog-default.component.html
libs/docs/core/dialog/examples/dialog-object-example/dialog-object-example.component.ts

pass closeButtonAriaLabel to close btn ariaLabel

fix(core): pass closeButtonAriaLabel to close btn ariaLabel

---

libs/i18n/src/lib/translations/translations.properties

fix(core): update total token text 2

---

package.json
yarn.lock

chore(deps): semver v.7.6.0

---

libs/docs/platform/table/e2e/table.po.ts
libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.html
libs/platform/src/lib/table/components/table-p13-dialog/grouping/grouping.component.html
libs/platform/src/lib/table/components/table-p13-dialog/sorting/sorting.component.html

fix(platform): fix p13 dialog focus

---

libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.html
libs/docs/platform/table/child-docs/pagination/table-pagination-docs.component.ts
libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-outer-scroll-example.component.html
libs/docs/platform/table/examples/custom-pagination/table-custom-pagination-outer-scroll-example.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/11445
Added an example to Platform docs for a Table with growing behaviour (more button) and outer scroll

docs(platform): add outer scroll to Table with growing button

---

package.json
yarn.lock

chore(deps): update zone.js v0.14.4

---

libs/core/grid-list/components/grid-list-item/grid-list-item.component.html
libs/core/grid-list/components/grid-list-item/grid-list-item.component.ts
libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.html
libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.scss
libs/docs/core/grid-list/examples/auto-height/grid-list-auto-height-example.component.ts
libs/docs/core/grid-list/examples/index.ts
libs/docs/core/grid-list/grid-list-docs.component.html
libs/docs/core/grid-list/grid-list-docs.component.ts
package.json

closes none
Request coming from CX

feat(core): add auto height option for Grid List items

---

libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.html

fixes [#10967](https://github.com/SAP/fundamental-ngx/issues/10967) - update doc examples

docs(core): update unread examples with aria-description

---

libs/docs/core/icon/examples/icon-example.component.ts
libs/docs/shared/src/lib/utilities/icons.ts
package.json
yarn.lock

chore(deps): theming-base-content v11.13.0

---

libs/docs/core/message-strip/message-strip-header/message-strip-header.component.html
libs/docs/core/message-strip/message-strip-header/message-strip-header.component.ts
libs/docs/core/message-toast/message-toast-header/message-toast-header.component.html
libs/docs/core/message-toast/message-toast-header/message-toast-header.component.ts

docs(core): document the usage of overlay

---

libs/docs/platform/approval-flow/examples/platform-approval-flow-example.component.html
libs/docs/platform/approval-flow/examples/platform-approval-flow-example.component.ts
libs/platform/src/lib/approval-flow/approval-flow.component.ts

This is "ng-15-downport" PR
main branch PR: https://github.com/SAP/fundamental-ngx/pull/11545
None
- add an `@input` to remove space node from ApprovalFlow graph to remove the redundant spaces
- update the example for this new input
given this data set: 
<details>
<summary>Click me for json</summary>
<code>
[
{
"id": "AAAAADPBWVA+7y",
"name": "Project Owner",
"description": "",
"approvers": [
{
"id": "PG20869910",
"teamId": "PG20869910",
"name": "Project Owner",
"imgUrl": ""
}
],
"status": "Pending",
"targets": [
"AAAAADPBWVA+8H",
"AAAAADPBWVA+8M"
],
"isEveryoneApprovalNeeded": true,
"disableActions": false
},
{
"id": "AAAAADPBWVA+8C",
"name": "User",
"description": "",
"approvers": [
{
"id": "sUser2569",
"teamId": "sUser2569",
"name": "User",
"description": "Enterprise User",
"imgUrl": …

fix(platform): [ng-15-downport] add input to remove space node from pprovalFlow graph

---

libs/core/popover/popover-body/popover-body.component.spec.ts

test(core): remove wrong import

---

libs/core/popover/popover-body/popover-body.component.spec.ts
libs/platform/schematics/utils/package-utils.ts

chore: fixed lint issues

---

libs/core/select/select.component.html

fix(core): redundant aria-label on select component

---

libs/docs/platform/table/child-docs/p13-dialog/p13-dialog-docs.component.html
libs/docs/platform/table/e2e/table-p13-dialog.e2e-spec.ts
libs/docs/platform/table/e2e/table-settings-dialog.e2e-spec.ts
libs/docs/platform/table/e2e/table.po.ts
libs/docs/platform/table/examples/platform-table-p13-filter-example.component.html
libs/docs/platform/table/examples/platform-table-p13-filter-example.component.ts
libs/docs/platform/table/platform-table.module.ts
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.component.ts
libs/platform/src/lib/table/components/table-p13-dialog/filtering/filtering.model.ts
libs/platform/src/lib/table/components/table-p13-dialog/table-p13-dialog.component.ts
libs/platform/src/lib/table/components/table-p13-dialog/table-p13-filter.component.ts

fix(platform): add validator input for p13 filter component

---

libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts

fix: do not set tabindex="-1" in setTabbable

---

libs/docs/platform/table/examples/platform-table-custom-title-example.component.ts
libs/platform/src/lib/table/components/table-row/table-row.component.html

fix(platform): table empty cell screenreader text

---

.github/ISSUE_TEMPLATE.md

added a note to the new issue template for users to avoid links to internal sources

chore(core): update ISSUE_TEMPLATE

---

libs/core/src/lib/combobox/combobox.component.html
libs/core/src/lib/combobox/combobox.component.ts

fix: use paste event to open popover in fd-combobox

---

versions.json

docs: add 0.49 docs

---

libs/cdk/utils/directives/focusable-list/scroll.ts

fix: issue with scrolling when topEl would be the cell instead of row

---

CHANGELOG.md
lerna.json
libs/btp/CHANGELOG.md
libs/btp/package.json
libs/cdk/CHANGELOG.md
libs/cdk/package.json
libs/core/CHANGELOG.md
libs/core/package.json
libs/cx/CHANGELOG.md
libs/cx/package.json
libs/datetime-adapter/CHANGELOG.md
libs/datetime-adapter/package.json
libs/i18n/CHANGELOG.md
libs/i18n/package.json
libs/moment-adapter/CHANGELOG.md
libs/moment-adapter/package.json
libs/nx-plugin/CHANGELOG.md
libs/nx-plugin/package.json
libs/platform/CHANGELOG.md
libs/platform/package.json

chore(release): publish 0.49.2

---

libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html

fix(platform): vhd keyboard improvements

---

libs/core/button/base-button.ts
libs/core/shellbar/index.ts
libs/core/shellbar/shellbar-actions-mobile/shellbar-actions-mobile.component.html
libs/core/shellbar/shellbar-actions/shellbar-actions.component.html
libs/core/shellbar/shellbar.component.ts
libs/core/shellbar/user-menu/shellbar-user-menu-button.directive.ts
libs/core/shellbar/user-menu/shellbar-user-menu.component.html
libs/core/shellbar/user-menu/shellbar-user-menu.component.ts
libs/docs/core/shellbar/examples/custom-user-menu-example.component.ts
libs/docs/core/shellbar/shellbar-docs.component.html
libs/docs/core/shellbar/shellbar-docs.component.ts

closes #11246
- Added ability to render fully custom user menu in shellbar and added the example for it.
- Fixed example renderings in the shellbar documentation page

feat(core): added ability to render fully custom user menu in shellbar

---

libs/i18n/src/lib/models/fd-language-key-identifier.ts
libs/i18n/src/lib/translations/translations.properties
libs/i18n/src/lib/translations/translations.ts
libs/platform/table/components/table-view-settings-dialog/filtering/filter-step.component.html

fix(platform): added title to filter navigate back button

---

libs/cdk/utils/directives/only-digits/only-digits.directive.ts
libs/core/pagination/pagination.component.html
libs/core/pagination/pagination.component.ts

fix(core): pagination accessibility improvements

---

libs/datetime-adapter/tsconfig.json
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/tsconfig.json
tsconfig.base.json

allow synthetic default import

fix: allow synthetic default import

---

libs/platform/src/lib/menu/menu-trigger.directive.ts

fix(platform): focus menu button trigger when closed

---

libs/core/tree/components/tree-item/tree-item.component.html
libs/core/tree/components/tree-item/tree-item.component.ts
libs/docs/core/tree/examples/simple-tree-example.component.html
libs/docs/core/tree/examples/simple-tree-example.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/11687
- add input prop to Tree item for custom background
- add input prop to Tree item for custom CSS object
- add Customization example

feat(core): add possibility to apply custom background and CSS to Tree item

---

libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz-dependencies.ts
package.json
yarn.lock

add fundamental packages for stackblitz and update common-css version

fix: add fundamental packages for stackblitz and update common-css

---

libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.scss
libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
libs/docs/core/icon/examples/icon-color-example.component.scss
libs/docs/core/icon/examples/icon-color-example.component.ts
libs/docs/core/icon/examples/icon-tnt-example.component.scss
libs/docs/core/icon/examples/icon-tnt-example.component.ts
libs/docs/core/icon/icon-docs.component.ts

fix icon stackblitz examples
part of #10844

docs(core): fix icon stackblitz examples

---

libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts

docs(core): fix illustration msg stackblitz

---

libs/docs/core/input-group/input-group-docs.component.ts

input group stackblitz
part of #10844

docs(core): input group stackblitz

---

libs/docs/core/menu/menu-docs.component.ts

menu stackblitz
part of #10844

docs(core): menu stackblitz

---

libs/docs/core/message-strip/examples/message-strip-alert-example.component.ts
libs/docs/core/message-strip/examples/message-strip-auto-dismiss-example.component.ts
libs/docs/core/message-strip/message-strip-docs.component.html
libs/docs/core/message-strip/message-strip-docs.component.ts

part of #10844
message strip stackblitz

docs(core): message strip stackblitz

---

libs/docs/core/micro-process-flow/micro-process-flow-docs.component.ts

docs(core): micro process flow stackblitz

---

libs/docs/core/multi-input/examples/multi-input-async-example/multi-input-async-example.component.ts

docs(core): multi input stackblitz

---

libs/docs/core/popover/examples/popover-simple/popover-example.component.ts
libs/docs/core/popover/popover-docs.component.ts
libs/docs/core/popover/popover-header/popover-header.component.ts

popover stackblitz part of #10844

docs(core): popover stackblitz

---

CHANGELOG.md
lerna.json
libs/btp/CHANGELOG.md
libs/btp/package.json
libs/cdk/CHANGELOG.md
libs/cdk/package.json
libs/core/CHANGELOG.md
libs/core/package.json
libs/cx/CHANGELOG.md
libs/cx/package.json
libs/datetime-adapter/CHANGELOG.md
libs/datetime-adapter/package.json
libs/i18n/CHANGELOG.md
libs/i18n/package.json
libs/moment-adapter/CHANGELOG.md
libs/moment-adapter/package.json
libs/nx-plugin/CHANGELOG.md
libs/nx-plugin/package.json
libs/platform/CHANGELOG.md
libs/platform/package.json

chore(release): publish 0.50.0-rc.21

---

libs/docs/core/slider/slider-docs.component.html
libs/docs/core/slider/slider-docs.component.ts

docs(core): slider sb

---

libs/docs/core/table/table-docs.component.ts

table stackblitz part of #10844

docs(core): table stackblitz

---

libs/core/tile/directives/tile.directives.spec.ts

test(core): remove slide tile unit

---

libs/docs/core/time-picker/e2e/time-picker.e2e-spec.ts
libs/docs/core/time-picker/e2e/time-picker.po.ts

test(core): remove compact time picker e2e

---

libs/docs/core/timeline/timeline-docs.component.ts

timeline stackblitz part of #10844

docs(core): timeline stackblitz

---

libs/docs/core/tree/tree-docs.component.ts

tree stackblitz part of #10844

test(core): tree stackblitz

---

libs/docs/core/tabs/e2e/tabs.po.ts

test(core): tabs test e2e fix

---

.github/workflows/testing.yml

introduce daily e2e/unit run without cache

chore(ci): introduce daily e2e/unit run without cache

---

libs/docs/core/dynamic-page/dynamic-page-docs.component.html
libs/docs/core/dynamic-page/dynamic-page-docs.component.ts
libs/docs/core/dynamic-page/e2e/dynamic-page.po.ts
libs/docs/core/dynamic-page/examples/dynamic-page-example.component.ts

dynamic page stackblitz part of #10844

docs(core): dynamic-page stackblitz

---

libs/docs/core/shellbar/shellbar-docs.component.ts

shellbar stackblitz part of #10844

docs(core): shellbar stackblitz

---

libs/docs/core/flexible-column-layout/flexible-column-layout-docs.component.ts

flexible column layout stackblitz part of #10844

docs(core): flexible column layout stackblitz

---

libs/docs/core/layout-grid/layout-grid-docs.component.ts

docs(core): layout grid sb

---

libs/docs/core/theming/examples/theming-example.component.ts
libs/docs/core/theming/examples/theming-url-example.component.ts
libs/docs/core/theming/theming-docs.component.ts

theming stackblitz part of #10844

docs(core): theming stackblitz

---

libs/docs/core/truncate/truncate-docs.component.ts

truncate stackblitz part of #10844

docs(core): truncate stackblitz

---

.github/workflows/testing.yml

chore(ci): fix testing.yml

---

.github/workflows/testing.yml

chore(ci): update testing.yml

---

libs/docs/core/moment-datetime-adapter/e2e/moment-datetime-adapter.e2e-spec.ts
libs/docs/core/moment-datetime-adapter/e2e/tsconfig.json
libs/docs/core/moment-datetime-adapter/moment-datetime-adapter-docs.component.html
libs/docs/core/moment-datetime-adapter/moment-datetime-adapter-docs.component.ts

remove moment-datetime-adapter stackblitz part of #10844

docs: remove moment-datetime-adapter stackblitz

---

libs/docs/core/status-indicator/examples/status-indicator-clickable-type.component.ts
libs/docs/core/status-indicator/status-indicator-docs.component.html
libs/docs/core/status-indicator/status-indicator-docs.component.ts

status indicator stackblitz part of #10844

docs(core): status indicator stackblitz

---

libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html

fix(platform): header cell popover freeze button should be keydown

---

libs/docs/platform/approval-flow/examples/platform-approval-flow-custom-status-example.component.ts
libs/docs/platform/approval-flow/examples/platform-approval-flow-example.component.ts
libs/docs/platform/approval-flow/platform-approval-flow-docs.component.html

approval flow sb part of #10844

docs(platform): approval flow sb

---

libs/docs/platform/date-picker/examples/mobile/platform-date-picker-mobile-example.component.ts
libs/docs/platform/date-picker/platform-date-picker-docs.component.ts

docs(platform): datepicker sb

---

libs/docs/platform/datetime-picker/examples/mobile/platform-datetime-picker-mobile-example.component.ts
libs/docs/platform/datetime-picker/platform-datetime-picker-docs.component.ts

datetime picker stackblitz part of #10844

docs(platform): datetime picker stackblitz

---

libs/docs/platform/icon-tab-bar/e2e/icon-tab-bar.po.ts
libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-configurable-paddings-example/platform-icon-tab-bar-configurable-paddings-example.component.ts
libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-filter-type-example/platform-icon-tab-bar-filter-type-example.component.ts
libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-icon-only-type-example/platform-icon-tab-bar-icon-only-type-example.component.ts
libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-icon-type-example/platform-icon-tab-bar-icon-type-example.component.ts
libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-process-type-example/platform-icon-tab-bar-process-type-example.component.ts
libs/docs/platform/icon-tab-bar/examples/platform-icon-tab-bar-text-type-example/platform-icon-tab-bar-text-type-example.component.ts
libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.html
libs/docs/platform/icon-tab-bar/platform-icon-tab-bar-docs.component.ts

icon tab bar stackblitz part of #10844

docs(platform): icon tab bar stackblitz

---

libs/platform/src/lib/table/components/table-header-row/table-header-row.component.html

fix(platform): prevent keyboard press on checkbox header cell from scrolling page

---

libs/docs/platform/input-group/e2e/input-group.po.ts
libs/docs/platform/input-group/examples/platform-input-group-form-example.component.ts
libs/docs/platform/input-group/platform-input-group-docs.component.html
libs/docs/platform/input-group/platform-input-group-docs.component.ts

input group stackblitz part of #10844

docs(platform): input group stackblitz

---

libs/platform/table/components/table-toolbar/table-toolbar.component.html

fix(platform): table toolbar not passing aria label input to search field

---

libs/platform/table/table.component.ts

fix(platform): make platform table loading input public

---

libs/docs/platform/menu/platform-menu-docs.component.ts

fdp menu stackblitz part of #10844

docs(platform): fdp menu stackblitz

---

libs/docs/platform/message-popover/examples/default/message-popover-default-example.component.ts
libs/docs/platform/message-popover/examples/form-container/form-container-example.component.ts
libs/docs/platform/message-popover/examples/form-generator/form-generator-component-example.component.ts
libs/docs/platform/message-popover/message-popover-docs.component.html
libs/docs/platform/message-popover/message-popover-docs.component.ts

git push --set-upstream origin docs/fdp-message-popover-sb part of #10844

docs(platform): message popover stackblitz

---

libs/docs/platform/link/examples/platform-link-example.component.html
libs/docs/platform/link/examples/platform-link-example.component.ts
libs/docs/platform/link/examples/platform-link-misc-examples.component.html
libs/docs/platform/link/examples/platform-link-misc-examples.component.ts
libs/docs/platform/link/examples/platform-link-types-example.component.html
libs/docs/platform/link/examples/platform-link-types-example.component.ts
libs/docs/platform/link/platform-link-docs.component.html
libs/docs/platform/link/platform-link-docs.component.ts

docs(platform): fdp link examples

---

libs/docs/platform/object-list-item/examples/platform-object-list-item-border-less-example.component.ts

platform object list item stackblitz part of #10844

docs(platform): object list item stackblitz

---

libs/docs/platform/standard-list-item/e2e/standard-list-item.e2e-spec.ts
libs/docs/platform/standard-list-item/examples/platform-standard-list-item-border-less-example.component.html
libs/docs/platform/standard-list-item/examples/platform-standard-list-item-example.component.html
libs/docs/platform/standard-list-item/examples/platform-standard-list-unread-example.component.html
libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.html
libs/docs/platform/standard-list-item/platform-standard-list-item-docs.component.ts

standard list stackblitz part of #10844

docs(platform): standard list stackblitz

---

libs/docs/platform/settings-generator/examples/custom-layout/settings-generator-custom-layout-example.component.ts
libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.ts
libs/docs/platform/settings-generator/settings-generator-docs.component.ts

settings generator stackblitz part of #10844

docs(platform): settings generator stackblitz

---

libs/docs/platform/variant-management/variant-management-docs.component.ts

variant management stackblitz part of #10844

docs(platform): variant management stackblitz

---

libs/docs/platform/vhd/platform-vhd.docs.component.ts

value-help dialog stackblitz part of #10844

docs(platform): value-help dialog stackblitz

---

libs/docs/platform/wizard-generator/examples/wizard-generator-condition-example.component.ts
libs/docs/platform/wizard-generator/examples/wizard-generator-customizable-example.component.ts
libs/docs/platform/wizard-generator/examples/wizard-generator-dialog-example.component.ts
libs/docs/platform/wizard-generator/examples/wizard-generator-responsive-dialog-example.component.ts
libs/docs/platform/wizard-generator/examples/wizard-generator-visibility-between-steps-example.component.ts
libs/docs/platform/wizard-generator/examples/wizard-generator-visible-summary-branching-example.component.ts
libs/docs/platform/wizard-generator/platform-wizard-generator-docs.component.ts

wizard generator sb part of #10844

docs(platform): wizard generator sb

---

libs/docs/core/list-byline/examples/list-byline-unread-example/list-byline-unread-example.component.html
libs/docs/core/list/examples/list-data-example/list-data-example.component.ts
libs/docs/core/list/examples/list-data-example/sort.pipe.ts
libs/docs/core/list/list-docs.component.ts

list stackblitz part of #10844

docs(core): list stackblitz

---

libs/docs/core/content-density/content-density-docs.component.ts
libs/docs/core/content-density/examples/content-density-example.component.ts

content density stackblitz part of #10844

docs(core): content density sb

---

libs/core/src/lib/list/directives/list-icon.directive.ts
libs/core/src/lib/popover/popover-body/popover-body.component.scss
libs/docs/platform/list/examples/platform-list-free-content-example.component.html
libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.spec.ts
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
libs/platform/src/lib/list/list.component.ts
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.ts

fix(platform): some improvements to platform table header popover

---

libs/core/list/directives/list-icon.directive.ts
libs/core/popover/popover-body/popover-body.component.scss
libs/docs/platform/list/examples/platform-list-free-content-example.component.html
libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
libs/platform/list/free-content-list-item/free-content-list-item.component.spec.ts
libs/platform/list/free-content-list-item/free-content-list-item.component.ts
libs/platform/list/list.component.ts
libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.html
libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.ts

fix(platform): table header popover a11y improvements

---

libs/platform/src/lib/value-help-dialog/components/select-tab/select-tab.component.html
libs/platform/src/lib/value-help-dialog/value-help-dialog/value-help-dialog.component.html

fix(platform): remove tabindex from scrollable containers in VHD

---

libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts

fix(platform): check validator before open Filtering Settings Dialog

---

package.json
yarn.lock

align common-css version with fundamental-styles 0.36

fix(deps): align common-css version with fundamental-styles 0.36

---

libs/btp/README.md
libs/i18n/README.md

docs(btp,i18n): add license link in i18n and btp packages' README.md

---

libs/core/message-toast/message-toast.module.ts

closes #11983 
removed OverlayContainer override

fix(core): remove OverlayContainer override

---

.github/mergeable.yml

closes none
add Davit as reviewer and remove old contributors

chore(core): update mergeable reviewers

---

libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts

fix(platform): commented icon-tab-bar selection method logic part to fix scroll issue

---

libs/core/shellbar/shellbar.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/12085

fix(core): check if shellbar is initialized before setting input breakpoints

---

libs/core/schematics/add-dependencies/index.ts
libs/core/schematics/ng-add/index.ts

… steps appropriately.
closes #11659

fix(core): update schematics for ngAdd

---

libs/core/fundamental-ngx.module.ts

closes https://github.com/SAP/fundamental-ngx/issues/12060

fix(core): add missing Object Attribute module

---

libs/docs/core/dynamic-page/e2e/dynamic-page.e2e-spec.ts
libs/docs/platform/icon-tab-bar/e2e/icon-tab-bar.e2e-spec.ts

fix(platform): commented failed e2e tests

---

CHANGELOG.md
lerna.json
libs/btp/CHANGELOG.md
libs/btp/package.json
libs/cdk/CHANGELOG.md
libs/cdk/package.json
libs/core/CHANGELOG.md
libs/core/package.json
libs/cx/CHANGELOG.md
libs/cx/package.json
libs/datetime-adapter/CHANGELOG.md
libs/datetime-adapter/package.json
libs/i18n/CHANGELOG.md
libs/i18n/package.json
libs/moment-adapter/CHANGELOG.md
libs/moment-adapter/package.json
libs/nx-plugin/CHANGELOG.md
libs/nx-plugin/package.json
libs/platform/CHANGELOG.md
libs/platform/package.json

chore(release): publish 0.50.2

---

libs/core/combobox/combobox.component.spec.ts

test(core): combobox

---

libs/docs/core/dynamic-page/e2e/dynamic-page.e2e-spec.ts
libs/docs/platform/icon-tab-bar/e2e/icon-tab-bar.e2e-spec.ts

fix(core): fix icon-tab-bar e2e tests

---

libs/core/src/lib/multi-combobox/multi-combobox.component.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts

fix: reset input but do not close popover when checkbox clicked on multi combobox

---

package.json
yarn.lock

chore(deps): theming-base-content 11.17.1

---

libs/platform/src/lib/table/components/table-row/table-row.component.html

fix(platform): remove attr.title from small cells

---

libs/core/schematics/add-theming/add-theming.spec.ts
libs/core/schematics/add-theming/index.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/theming/sap_belize_fonts.css
libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz.service.ts

docs: fix stackblitz belize

---

versions.json

add links to versions 0.50 and 0.51

docs: add links to versions 0.50 and 0.51

---

libs/docs/platform/table/child-docs/scrolling/table-scrolling-docs.component.html
libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts

fix(platform): trackBy function not working with scrollWholeRows

---

libs/docs/core/multi-combobox/e2e/multi-combobox.e2e-spec.ts
libs/docs/platform/multi-combobox/e2e/multi-combobox.e2e-spec.ts

fix(core, platform): combobox e2e tests

---

libs/core/product-switch/product-switch-body/product-switch-body.component.html
libs/core/product-switch/product-switch-body/product-switch-body.component.ts
libs/core/product-switch/product-switch-body/product-switch.item.ts
libs/docs/core/product-switch/examples/product-switch-list/product-switch-list-example.component.ts
libs/docs/core/shellbar/examples/shellbar-growing-group-example/shellbar-growing-group-example.component.html

closes https://github.com/SAP/fundamental-ngx/issues/12130
This commit introduces support for setting icons with custom font families in the Product Switch component.

feat(core): add font family support to product switch component

---

libs/core/text/text.component.scss

clean up text css which is coming from fundamental-styles

fix(core): clean up text css

---

libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
libs/platform/src/lib/table/table.component.html
libs/platform/src/lib/table/table.component.scss

fix(platform): pageScroll/virtualScroll lag, and bug where new page of data would not be fetched after scroll

---

libs/docs/platform/button/e2e/button.e2e-spec.ts
libs/platform/src/lib/button/button.component.html
libs/platform/src/lib/button/button.component.ts

fix(platform): fdp-button role and title issues

---

libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.html
libs/platform/src/lib/table/components/table-p13-dialog/columns/columns.component.ts

fix(platform): enable move up / move down buttons at all times for p13 columns dialog

---

libs/docs/platform/table/examples/platform-table-freezable-example.component.html
libs/docs/platform/table/platform-table-docs.component.html
libs/platform/table/table.component.ts

fix(platform): table freezing incorrect columns, and better explanation of how it works in the docs

---

libs/platform/icon-tab-bar/icon-tab-bar.component.ts

fix(platform): add missing badge property in tabConfig.

---

libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
libs/platform/src/lib/table-helpers/table.ts
libs/platform/src/lib/table/table.component.ts

fix(platform): scrollWholeRows should emit tableScrolled event when using pageScrolling

---

libs/platform/table/components/table-view-settings-dialog/filtering/filter-step.component.html

fix(platform): table icon label not read

---

libs/core/src/lib/multi-input/multi-input.component.ts

fix(core): multi-input new token bug

---

apps/docs/src/app.config.ts

closes [#12212](https://github.com/SAP/fundamental-ngx/issues/12212)
Fixed the bug where navigation did not work when clicking on a content list item on the documentation's home page. This ensures that users can navigate correctly by selecting items from the content list.

fix(core): fixed link navigation on main page

---

apps/docs/src/app.config.ts

fix: roll back 12213

---

README.md

docs: remove readme contents links

---

libs/core/avatar/avatar-icon.pipe.ts
libs/core/avatar/avatar.component.spec.ts
yarn.lock

fix(core): update avatar state icons

---

package.json
yarn.lock

theming-base-content version 11.18.0

chore(deps): theming-base-content version 11.18.0

---

libs/docs/platform/table/examples/platform-table-default-example.component.ts
libs/platform/src/lib/table-helpers/services/table-column-resize.service.spec.ts
libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts
libs/platform/src/lib/table-helpers/table.ts
libs/platform/src/lib/table/table.component.ts

fix(platform): add input for restricting table column min width

---

libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.html
libs/docs/core/dialog/examples/dialog-complex/dialog-complex-example.component.ts

docs(core): update dialog example to prevent jaws from reading title twice

---

libs/core/src/lib/busy-indicator/busy-indicator.component.ts
libs/platform/src/lib/table/table.component.html

fix(core,platform): add preventWheelEvents input to busy indicator

---

libs/platform/src/lib/table-helpers/directives/table-cell-resizable.directive.ts

fix(platform): platform table column resizer performance improvements

---

.github/actions/nodejs/action.yml
.github/workflows/create-release.yml

chore(ci): fix ci

---

versions.json

docs: add link to 0.52

---

libs/docs/platform/table/examples/platform-table-custom-column-example.component.html
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.html
libs/platform/src/lib/list/free-content-list-item/free-content-list-item.component.ts
libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html

fix(platform): screenreader should announce posinset and setsize for table header popover

---

libs/docs/core/action-bar/action-bar-header/action-bar-header.component.html

remove deprecate from action bar

docs(core): remove deprecate from action bar

---

libs/core/wizard/wizard.component.scss
libs/core/wizard/wizard.component.spec.ts
libs/core/wizard/wizard.component.ts

closes [#12290](https://github.com/SAP/fundamental-ngx/issues/12290)
Wizard content overlaps when the dialog-body's height is smaller than the wizard content's height. 
This PR fixes the issue of fetching the appropriate dom element's(title, body, footer) height and dynamically calculating the required body height for the wizard content.
Wizard content overlapping on the wizard footer.
https://github.com/user-attachments/assets/e7a4b26d-e37c-47eb-925c-f36386df5a7c
Wizard Content is no longer overlapping after dynamically calculating the current height for wizard body
https://github.com/user-attachments/assets/159440d1-02de-46fc-bc71-9ae8f5b90720
- …

fix(core): wizard content overllaping fixed

---

libs/platform/table/table.component.ts

fix(platform): table grouping spanning 
closes [#12261](https://github.com/SAP/fundamental-ngx/issues/12261)
- Fixed table grouping spanning

fix(platform): table grouping spanning 

---

libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
libs/platform/src/lib/table/tests/table.component-virtual-scrolling.spec.ts

fix(platform): broken _getNumberOfRowsToDisplay() function

---

libs/core/src/lib/busy-indicator/busy-indicator.component.ts
libs/platform/src/lib/table-helpers/directives/table-virtual-scroll.directive.ts
libs/platform/src/lib/table/table.component.html

fixes #12372 maybe, this branch is currently WIP for testing only

fix(platform): more specific targeting of blocking wheel event when using scrollWholeRows

---

libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.spec.ts
libs/platform/value-help-dialog/value-help-dialog/value-help-dialog.component.ts

fix(platform): vhd should reset search after closing dialog

---

libs/platform/smart-filter-bar/directives/smart-filter-bar-subject.directive.spec.ts

add more time for smart filter bar unit test

test(platform): add more time for smart filter bar unit test

---

libs/platform/smart-filter-bar/smart-filter-bar.component.html

closes:[#12368](https://github.com/SAP/fundamental-ngx/issues/12368) 
- Added overflow feature to smart filter bar component

feat(platform): FilterBar overflow feature

---

libs/core/datetime-picker/datetime-picker.component.ts

fix: datetime adapter passing date format, not dateTime

---

libs/platform/icon-tab-bar/components/icon-tab-bar-base.class.ts

fix(platform): icon-tab-bar check for selectedUid

---

libs/core/datetime-picker/datetime-picker.component.ts

fix(core): handle invalid date inputs gracefully

---

libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.html
libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.spec.ts
libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts
libs/docs/core/date-picker/date-picker-docs.component.html
libs/docs/core/date-picker/date-picker-docs.component.ts
libs/docs/core/date-picker/examples/date-picker-special-day-example/date-picker-special-day-example.component.html
libs/docs/core/date-picker/examples/date-picker-special-day-example/date-picker-special-day-example.component.ts

fix(core): Refactor calendar day view component to use signal version of inputs. add special day rules example for DatePicker

---

libs/cx/nested-list/nested-item/nested-item.component.ts

fix(cx): Add ariaHidden input property and set it default false

---

libs/platform/src/lib/table/components/table-cell-header-popover/table-cell-header-popover.component.html

fix(platform): prevent filter input from losing focus when entering spaces

---

libs/core/wizard/wizard-step/wizard-step.component.html
libs/core/wizard/wizard-step/wizard-step.component.ts

fix(core): wizard steps - anchors should have role="navigation"

---

libs/core/form/form-label/form-label.component.html
libs/docs/core/input/examples/input-example.component.html

fix(core): form label white space

---

libs/docs/core/input/e2e/input.e2e-spec.ts

test(e2e): remove obsolete tests

---

libs/docs/core/input/examples/input-state-example.component.html
libs/docs/core/textarea/examples/textarea-state-example.component.html

docs(core): textarea and input state form message a11y improvements

---

libs/core/calendar/calendar-views/calendar-month-view/calendar-month-view.component.html
libs/core/calendar/calendar-views/calendar-year-view/calendar-year-view.component.html

fix(core): stop month/year cell to change size on date picker month/year range selection

---

libs/core/tabs/tab-list.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/12035
ng-15 https://github.com/SAP/fundamental-ngx/pull/12125

fix(core): Remove redundant api calls on dynamic page 

---

libs/core/src/lib/input-group/input-group.component.html
libs/docs/core/multi-input/e2e/multi-input.po.ts

fix(core): input group should not fall back to glyph for button title

---

libs/core/calendar/calendar-views/calendar-day-view/calendar-day-view.component.ts

fix(core): build day view grid on specialDaysRule update.

---

libs/platform/table/table.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/12450
ng-15 https://github.com/SAP/fundamental-ngx/pull/12517

fix(platform): Recheck loadingState before refocus table cell

---

libs/docs/core/dialog/dialog-docs.component.html
libs/docs/core/dialog/examples/auto-label/auto-label-dialog-example.component.html
libs/docs/core/dialog/examples/component-based/dialog-example.component.ts
libs/docs/core/dialog/examples/dialog-backdrop-container/dialog-backdrop-container-example.component.html
libs/docs/core/dialog/examples/dialog-configuration/dialog-configuration-example.component.html
libs/docs/core/dialog/examples/dialog-full-screen/dialog-full-screen-example.component.html
libs/docs/core/dialog/examples/dialog-full-screen/dialog-full-screen-example.component.ts
libs/docs/core/dialog/examples/dialog-mobile/dialog-mobile-example.component.html
libs/docs/core/dialog/examples/dialog-object-example/dialog-object-example.component.html
libs/docs/core/dialog/examples/dialog-position/dialog-position-example.component.html
libs/docs/core/dialog/examples/dialog-state/dialog-state-example.component.html
libs/docs/core/dialog/examples/stacked-dialogs/first-dialog-example.component.ts
libs/docs/core/dialog/examples/stacked-dialogs/second-dialog-example.component.ts
libs/docs/core/dialog/examples/template-based/template-based-dialog-example.component.html

fix(core): remove role="dialog" from dialog body in docs

---

libs/docs/core/combobox/examples/combobox-example.component.html

fix: combobox e2e

---

versions.json

add Angular version to the older versions links

docs: add Angular version to the older versions links

---

libs/core/breadcrumb/breadcrumb.component.html
libs/core/breadcrumb/breadcrumb.component.ts
libs/core/menu/menu.component.html
libs/core/menu/menu.component.ts
libs/core/overflow-layout/overflow-layout.component.html
libs/core/overflow-layout/overflow-layout.component.ts
libs/docs/core/breadcrumb/examples/breadcrumb-href-example.component.html
libs/docs/core/breadcrumb/examples/breadcrumb-routerLink-example.component.html
libs/i18n/src/lib/models/fd-language-key-identifier.ts
libs/i18n/src/lib/translations/translations.properties
libs/i18n/src/lib/translations/translations.ts

fix(core): breadcrumb aria updates per new specs

---

package.json
yarn.lock

chore(deps): update lerna 8.1.8

---

libs/docs/core/side-navigation/side-navigation-header/side-navigation-header.component.html

add a deprecate message on the doc example

docs: add a deprecate message on the doc example

---

libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
package.json
yarn.lock

chore(deps): theming-base-content 11.20.0

---

libs/core/message-toast/message-toast.component.ts

closes none
add appropriate role to Message Toast

fix(core): add a11y improvements for Message Toast

---

package.json
yarn.lock

chore(deps): theming-base-content 11.22.0

---

libs/core/multi-input/multi-input.component.ts
libs/platform/form/multi-input/base-multi-input.ts

fix(core,platform): multi input focus switching bug

---

.github/actions/nodejs/action.yml
.github/workflows/create-release.yml
.github/workflows/on-pull-request.yml
.github/workflows/testing.yml
libs/i18n/src/lib/translations/translations.ts
package.json
yarn.lock

chore(deps): update yarn 4.5.1

---

libs/docs/platform/table/e2e/table.po.ts

fix: failing platform table p13 e2e

---

libs/core/notification/directives/notification-popover.directive.ts
libs/docs/core/notification/examples/notification-group/notification-group-example.component.html

fixes #11537 
Parameters of the issue have changed since it was initially opened, but this tidies things up a bit

fix(core): notification a11y improvements

---

libs/docs/shared/src/lib/core-helpers/sections-toolbar/sections-toolbar.component.scss

Removes native scrollbar track that displays on docs page sidenav is using chrome on desktop.
It's not a big deal but unpleasant to see nontheless.
-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation
-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change …

fix(docs): extra scrollbar track showing on docs page for chrome

---

libs/core/illustrated-message/illustrated-message.component.html
libs/core/illustrated-message/illustrated-message.component.ts
libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.html
libs/docs/core/illustrated-message/examples/illustrated-message-inline-example.component.ts
libs/docs/core/illustrated-message/illustrated-message-docs.component.html
libs/docs/core/illustrated-message/illustrated-message-docs.component.ts

bring inline SVG support to illustration message

fix(core): bring inline SVG support to illustration message

---

libs/core/src/lib/step-input/step-input.component.html

fix(core): add spinbutton role to step input

---

libs/core/src/lib/popover/base/base-popover.class.ts
libs/core/src/lib/popover/popover-body/popover-body.component.ts
libs/docs/platform/multi-combobox/e2e/multi-combobox.po.ts

fix(core): make popover body have dialog role by default

---

libs/platform/table/components/table-row/table-row.component.ts
libs/platform/table/table.component.html

fix(platform): table row has incorrect aria-rowindex

---

libs/platform/table-helpers/services/table.service.ts

fix(platform): unused var build error

---

libs/core/select/select.component.html

fix: select whitespace

---

libs/platform/table/components/table-toolbar/table-toolbar.component.html
libs/platform/table/components/table-toolbar/table-toolbar.component.ts

feat(platform): add searchFieldInputText input and searchFieldInputChange events to platform table toolbar

---

libs/core/radio/radio-button/radio-button.component.html
libs/core/radio/radio-button/radio-button.component.ts
libs/docs/core/radio/examples/index.ts
libs/docs/core/radio/examples/radio-truncation-example.component.html
libs/docs/core/radio/examples/radio-truncation-example.component.ts
libs/docs/core/radio/radio-docs.component.html
libs/docs/core/radio/radio-docs.component.ts

closes none
Radio Button was missing label wrapping behavior, which Checkbox has.

fix(core): add label wrapping behavior for Radio Button

---

libs/platform/src/lib/table-helpers/services/table-column-resize.service.ts

fix(platform): bug where vertical blue resizing line stays after horizontal scrolling platform table

---

libs/docs/platform/table/e2e/table-settings-dialog.e2e-spec.ts

fix: table e2e tests

---

versions.json

docs: add link to 0.54 docs

---

libs/platform/src/lib/form/auto-complete/auto-complete.directive.ts

fixes #12983 
This is basically a copy of #11051 and #12340 but for platform

fix(platform): autocomplete should support japanese keyboard input source

---

libs/docs/platform/datetime-picker/e2e/datetime-picker.e2e-spec.ts

simplify e2e for today testing in datetime

test(core): simplify e2e for today testing in datetime

---

libs/core/segmented-button/segmented-button.component.spec.ts

fix lint in segmented button test

chore: fix lint in segmented button test

---

.github/workflows/on-pull-request.yml

test: pause running e2e

---

libs/docs/platform/settings-generator/examples/dialog/settings-generator-dialog-example.component.html

remove the header in settings gen dialog example

docs(platform): remove the header in settings gen dialog example

---

.github/workflows/on-pull-request.yml

closes
-   [ ] visual misalignments/updates
-   [ ] check Light/Dark/HCB/HCW themes
-   [ ] RTL/LTR - proper rendering and labeling
-   [ ] responsiveness(resize)
-   [ ] Content Density (Cozy/Compact/(Condensed))
-   [ ] States - hover/disabled/focused/active/on click/selected/selected hover/press state
-   [ ] Interaction/Animation - open/close, expand/collapse, add/remove, check/uncheck
-   [ ] Mouse vs. Keyboard support
-   [ ] Text Truncation
-   [ ] check for console logs (warnings, errors)
-   [ ] API boundary values
-   [ ] different combinations of components - free style
-   [ ] change the API values during testing
-   [ ] missing API documentation or it is not understandable
-   [ ] …

test: test nx with update on on-pull-request.yml

---

libs/platform/form/select/select/select.component.html

fix(platform): fixed visual bug in select docs

---

libs/cx/nested-list/nested-link/nested-link.component.ts

fix(cx): nested link component import bug

---

eslint.config.js
libs/docs/core/date-picker/examples/date-picker-special-day-example/date-picker-special-day-example.component.html
libs/platform/value-help-dialog/components/define-tab/define-tab.component.scss
package.json
yarn.lock

Fixes a commit hook failure. Also 2 minor unrelated visual fixes I noticed on date picker and VHD

fix: dependencies, minor visual bugs, lint rule

---

package.json
yarn.lock

chore(deps): fix specific nx version

---

libs/docs/core/file-uploader/file-uploader-docs.component.html
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/angular.json
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/package.json

docs: fix stackblitz

---

libs/core/avatar-group/avatar-group.component.ts
libs/core/avatar-group/components/default-avatar-group-overflow-body/default-avatar-group-overflow-body.component.ts

fix(core): popover bugs in avatar group

---

libs/btp/navigation/components/navigation-item/navigation-list-item.component.spec.ts
libs/btp/navigation/components/navigation-start/navigation-content-start.component.ts
libs/btp/search-field/src/search-field.component.ts
libs/core/grid-list/components/grid-list-filter-bar/grid-list-filter-bar.component.ts
libs/core/input-group/input-group.component.ts
libs/platform/menu/menu.component.ts
libs/platform/value-help-dialog/components/select-tab/select-tab.component.ts
libs/platform/wizard-generator/components/wizard-body/wizard-body.component.ts

chore: fix lint errors

---

libs/core/segmented-button/segmented-button.component.ts

fix segmented btn in reactive forms

fix(core): fix segmented btn in reactive forms

---

versions.json

docs: bump versions

---

libs/docs/core/icon/examples/icon-businessSuiteInAppSymbols-example.component.ts
libs/docs/core/icon/examples/icon-example.component.ts
libs/docs/shared/src/lib/utilities/icons.ts
package.json
yarn.lock

bring theming-base-content version 11.26.0

chore: bring theming-base-content version 11.26.0

---

libs/core/schematics/add-theming/add-theming.spec.ts
libs/core/schematics/add-theming/index.ts
libs/platform/table/components/table-view-settings-dialog/settings-dialog/settings-dialog.component.ts

fix: remove belize from schematics, update cdk imports in platform table

---

libs/core/avatar-group/avatar-group.component.html
libs/core/avatar-group/avatar-group.component.scss
libs/core/avatar-group/avatar-group.component.ts
libs/core/avatar-group/components/avatar-group-host.component.scss
libs/core/avatar-group/components/avatar-group-host.component.ts

I missed two cases in https://github.com/SAP/fundamental-ngx/pull/12955 
and they are covered now

feat: lazy load popover body in all cases for the avatar group

---

libs/core/multi-input/multi-input.component.ts

fix(core): checkbox clicking in multi input

---

eslint.config.js
libs/btp/navigation/components/navigation-item/navigation-list-item.component.html
libs/btp/navigation/components/navigation-item/navigation-list-item.component.ts
libs/btp/navigation/components/navigation-link/navigation-link.component.ts
libs/btp/navigation/components/navigation/navigation.component.scss
libs/btp/navigation/components/navigation/navigation.component.ts
libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.html
libs/docs/btp/navigation/examples/basic-example/navigation-basic-example.component.ts
libs/docs/btp/navigation/examples/parent-item-link/navigation-parent-item-link.component.html
libs/docs/btp/navigation/examples/parent-item-link/navigation-parent-item-link.component.ts

- brings the latest CSS for BTP Vertical navigation
- adds Quick create button

fix(btp): update the styling for Vert nav

---

.github/actions/nodejs/action.yml
.github/workflows/create-release.yml
.github/workflows/on-pull-request.yml
package.json
yarn.lock

chore(ci): ci scripts cleanup

---

libs/btp/navigation/components/navigation-end/navigation-content-end.component.ts
libs/btp/navigation/components/navigation-item/navigation-list-item.component.ts
libs/btp/navigation/components/navigation-link/navigation-link.component.ts
libs/btp/navigation/components/navigation-more-button/navigation-more-button.component.ts
libs/btp/navigation/components/navigation-start/navigation-content-start.component.ts
libs/btp/navigation/components/navigation/navigation.component.ts
libs/btp/tool-header/src/components/tool-header-product-switch.component.ts
libs/btp/tool-header/src/components/tool-header/tool-header.component.ts
libs/core/card/header/card-header-main.component.ts
libs/core/dynamic-page/dynamic-page-header/subheader/dynamic-page-subheader.component.ts
libs/core/generic-tag/generic-tag.component.ts
libs/core/notification/notification-group-header/notification-group-header.component.ts
libs/core/select/select.component.ts
libs/cx/project.json
libs/platform/dynamic-page/dynamic-page.component.ts
libs/platform/form/date-picker/date-picker.component.ts
libs/platform/form/input-group/input-group.component.ts
libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.ts
libs/platform/form/multi-input/multi-input.component.ts
libs/platform/icon-tab-bar/components/icon-tab-bar-text-type/icon-tab-bar-text-type.component.ts
libs/platform/project.json
libs/platform/settings-generator/layouts/settings-generator-sidebar-layout/settings-generator-sidebar-layout.component.ts
libs/platform/table/components/growing-button/table-growing-button.component.ts
libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
libs/platform/table/components/table-group-row/table-group-row.component.ts
libs/platform/table/components/table-view-settings-dialog/filtering/filters-list-step.component.ts
libs/platform/table/components/table-view-settings-dialog/filtering/filters.component.ts
libs/platform/table/components/table-view-settings-dialog/grouping/grouping.component.ts
libs/platform/table/components/table-view-settings-dialog/sorting/sorting.component.ts

this is done using `nx generate @angular/core:cleanup-unused-imports`

chore: delete unused imports

---

libs/i18n/src/lib/translations/translations_en_US_sappsd.properties

chore: Translation Delivery

---

libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.html

fix(core): incorrect roles for vertical navigation

---

libs/core/src/lib/combobox/combobox.component.ts
libs/core/src/lib/multi-combobox/multi-combobox.component.html
libs/core/src/lib/multi-combobox/multi-combobox.component.ts
libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/popover/popover.component.ts
libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/commons/base-combobox.ts
libs/platform/src/lib/form/multi-combobox/commons/base-multi-combobox.ts
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/src/lib/form/multi-combobox/multi-combobox/multi-combobox.component.ts
libs/platform/src/lib/form/multi-input/base-multi-input.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.ts

fix(core,platform): combobox/multi-input/multi-combobox escape key handling

---

libs/core/multi-combobox/multi-combobox.component.html
libs/core/multi-input/multi-input.component.html
libs/platform/form/multi-combobox/multi-combobox/multi-combobox.component.html
libs/platform/form/multi-input/base-multi-input.ts
libs/platform/form/multi-input/multi-input.component.html

fixes none
Some further improvements I found while working on #13167

fix(core,platform): combobox/multi-input/multi-combobox escape improvements

---

libs/i18n/src/lib/translations/translations_en_US_sappsd.properties

Translation Delivery

---

libs/core/src/lib/multi-input/multi-input.component.html
libs/core/src/lib/multi-input/multi-input.component.ts
libs/core/src/lib/token/tokenizer.component.ts
libs/platform/src/lib/form/multi-input/multi-input.component.html
libs/platform/src/lib/form/multi-input/multi-input.component.ts

fix(core,platform): move token count announcer logic to tokenizer

---

libs/core/src/lib/datetime-picker/datetime-picker.component.ts

fixes #12839 
downport of #12433

fix(core): datepicker should not display invalid date text

---

libs/core/dynamic-page/dynamic-page.component.html

fix(core): fix dynamic page scrolling

---

libs/platform/table/components/table-cell-header-popover/table-cell-header-popover.component.ts
libs/platform/table/components/table-view-settings-dialog/filtering/filters-list-step.component.html

fix(platform): keyboard improvements for table filtering and header popover

---

libs/platform/search-field/search-field.component.html

fix(platform): search field should have aria-controls only if it has a menu

---

libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.html
libs/core/src/lib/dynamic-page/dynamic-page-header/header/dynamic-page-header.component.ts
libs/docs/core/dynamic-page/examples/dynamic-page-column-layout-example/dynamic-page-column-layout-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-dynamic-container-height-example/dynamic-page-dynamic-container-height-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-facets-example/dynamic-page-facets-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-responsive-example/dynamic-page-responsive-example.component.html
libs/docs/core/dynamic-page/examples/dynamic-page-tabs-example/dynamic-page-tabs-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-facets-example/platform-dynamic-page-facets-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-flexible-column-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-non-collapsible-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-responsive-padding-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-snap-scroll-example.component.html
libs/docs/platform/dynamic-page/examples/platform-dynamic-page-tabbed-example.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.component.html
libs/platform/src/lib/dynamic-page/dynamic-page.component.ts
package.json

fix(core,platform): add input for dynamic page header title heading level

---

libs/platform/src/lib/table/components/table-toolbar/table-toolbar.component.html

fix(platform): fix platform table aria-haspopup incorrect values

---

libs/cdk/src/lib/utils/directives/focusable-item/focusable-item.directive.ts

fix(cdk): focusable item tabindex bug

---

libs/docs/platform/table/child-docs/preserving-state/preserved-state-docs.component.html
libs/platform/table/table.component.ts

fix(platform): remove requirement that tableScrolled event only emitted with pageScrolling

---

libs/core/src/lib/list/list-navigation-item/list-navigation-item.component.ts
libs/core/src/lib/vertical-navigation/vertical-navigation.component.html
libs/cx/src/lib/nested-list/nested-content/nested-list-content.directive.ts
libs/cx/src/lib/nested-list/nested-link/nested-link.component.ts

fix(core,cx): vertical and side nav announcing selection incorrectly

---

libs/i18n/src/lib/translations/translations_hi.ts
libs/i18n/src/lib/translations/translations_ka.ts

chore: fix i18n files

---

libs/cx/side-navigation/side-navigation.component.spec.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/package.json
libs/i18n/src/lib/translations/translations_hi.ts
libs/i18n/src/lib/translations/translations_ka.ts
netlify.toml
package.json
yarn.lock

chore(deps): migrate to nx v.20.8.1

---

libs/core/object-attribute/object-attribute.component.ts
libs/core/object-attribute/project.json

remove fdp from core object attribute

fix(core): remove fdp from core object attribute

---

libs/core/bar/bar.component.ts
libs/docs/core/bar/examples/bar-custom-shellbar-example.component.html
libs/docs/core/bar/examples/bar-default-example.component.html
libs/docs/core/bar/examples/bar-floating-footer-example.component.html
libs/docs/core/bar/examples/bar-footer-example.component.html
libs/docs/core/bar/examples/bar-header-example.component.html
libs/docs/core/bar/examples/bar-header-subheader-example.component.html
libs/docs/core/bar/examples/bar-page-example.component.html
libs/docs/core/bar/examples/bar-page-responsive-example.component.html
libs/docs/core/bar/examples/bar-subheader-example.component.html
libs/docs/core/bar/examples/bar-with-title-example.component.html

closes none
- add role to the parent element
- update documentation with aria-label

fix(core): bring a11y improvements for Bar component

---

libs/platform/src/lib/form/combobox/combobox/combobox.component.html
libs/platform/src/lib/form/combobox/combobox/combobox.component.ts
libs/platform/src/lib/form/form-group/form-field/form-field.component.html
libs/platform/src/lib/form/form-group/form-field/form-field.component.ts

fix(platform): platform form field should announce form message

---

libs/core/src/lib/file-uploader/file-uploader.component.spec.ts
libs/core/src/lib/file-uploader/file-uploader.component.ts

fix(core): file uploader should only emit events when files change

---

libs/core/button/base-button.ts
libs/core/button/button.component.spec.ts
libs/core/button/button.component.ts
libs/core/file-uploader/file-uploader.component.html

fix(core): file uploader button a11y

---

libs/core/popover/popover-body/popover-body.component.html
libs/core/resizable-card-layout/resizable-card-layout/resizable-card-item/resizable-card-item.component.html
libs/core/resizable-card-layout/resizable-card-layout/resizable-card-layout.component.scss

closes none
- a11y updates for handles
- CSS update (to ensure the min touch area of the handle): it's also added to fund-styles https://github.com/SAP/fundamental-styles/pull/6051

fix(core): update for resize handle in Popover and Card Layout

---

apps/docs/project.json
nx.json
package.json
yarn.lock

chore(deps): update nx v.21.0.1

---

libs/core/combobox/combobox.component.ts

fix(core): combobox bug when selecting object with matching display values

---

versions.json

docs: add link to version 0.56

---

libs/docs/core/icon/search-icons/available-sap-icons.ts
libs/docs/shared/src/lib/core-helpers/stackblitz/code-example-stack/angular.json
libs/docs/shared/src/lib/core-helpers/stackblitz/stackblitz.service.ts
package.json
yarn.lock

docs: icon font paths for stackblitz

---

libs/core/multi-combobox/multi-combobox.component.ts
libs/core/multi-input/multi-input.component.ts

fix(core): fd-multi-combobox select all should clear input

---

package.json
yarn.lock

theming-base-content v.11.30.1

chore(deps): theming-base-content v.11.30.1

---

libs/core/shellbar/shellbar-action/shellbar-action.component.html

fix(core): shellbar action alignment bug

---

libs/platform/table/components/table-p13-dialog/columns/columns.component.ts
libs/platform/table/components/table-p13-dialog/table-p13-dialog.component.ts

fix(platform): persist column reordering when reopening columns p13 dialog

---

libs/datetime-adapter/src/lib/dayjs-datetime-formats.ts
libs/docs/core/datetime-picker/datetime-picker-docs.component.html
libs/docs/core/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.html
libs/docs/core/datetime-picker/examples/datetime-picker-complex-i18n-example/datetime-picker-complex-i18n-example.component.ts
libs/docs/core/dayjs-datetime-adapter/examples/date-picker-dayjs-adapter-example.component.ts

fix: update default dayjs parse rule, doc improvements

---

libs/datetime-adapter/src/lib/dayjs-datetime-adapter.spec.ts
libs/datetime-adapter/src/lib/dayjs-datetime-adapter.ts
libs/datetime-adapter/src/lib/dayjs-datetime-formats.ts

fixes https://github.com/SAP/fundamental-ngx/issues/13326
implement fallback formatter for datetime adapter

fix(core): implement fallback formatter for datetime adapter

---

libs/docs/core/icon/examples/icon-example.component.ts
libs/docs/shared/src/lib/utilities/icons.ts
package.json
yarn.lock

theming-base-content v.11.31.1
`smart-watch` and `vr-glasses` can be seen once we adopt latest fundamental-styles.

chore(deps): theming-base-content 11.31.1

---

libs/platform/approval-flow/approval-flow-add-node/approval-flow-add-node.component.ts
libs/platform/approval-flow/approval-flow-user-list/approval-flow-user-list.component.html
libs/platform/approval-flow/approval-flow-user-list/approval-flow-user-list.component.ts
libs/platform/list/list.component.ts

closes https://github.com/SAP/fundamental-ngx/issues/12093
ng-15 https://github.com/SAP/fundamental-ngx/pull/12107
This is a following up on https://github.com/SAP/fundamental-ngx/pull/12505. This has similar change but address some feedback on code review.
Our application is in the process of migrating to Angular 20. We would like to migrate some of the fixes which only exist in Angular 15 downport to main branch.

fix(platform): cache user selection after searching for new user list for approval flow

---

libs/docs/shared/src/lib/core-helpers/header/header.component.ts

docs: remove the deprecation

---

package.json
yarn.lock

chore: nx 21.3.10

---

package.json
yarn.lock

test CI testing
issue in NX:https://github.com/nrwl/nx/issues/32236

test(ci): revert to NX 21.2

---

libs/core/user-menu/user-menu.component.scss

closes https://github.com/SAP/fundamental-ngx/issues/13453

fix(core): import menu css in user menu
